### PR TITLE
3rdparty: Add Freetype and link to GSdx

### PR DESCRIPTION
**Pull request by turtleli**
Necessary for #1431. Possibly could be trimmed slightly (would save 2-3MB).

### CODE REVIEW

**Comment by gregory38** [comment]
I'm not against to trim it a bit. What is the size currently ?

**Comment by turtleli** [comment]
11MB.

**Comment by gregory38** [comment]
Yes trim it :)

**Comment by turtleli** [comment]
Trimmed - size is now 8.2MB.

**Comment by gregory38** [comment]
So much to draw 10 letters on the screen. Anyway, we can't do better. You can merge it.

Actually won't it be possible to only upload a binary file ? (the .a equivalent on windows). Or does it depends on the windows version ?

**Comment by turtleli** [comment]
Well, we'd still need the include files (1.8MB), and the compiled static .lib file is 5.7MB (VS2015). So we won't be saving much space.

**Pull request merged**
