### PR TITLE
Add Danish translation

### PR DESCRIPTION
**Pull request by rffontenelle**

### CODE REVIEW

**Comment by Jakob5566** [comment]
Thanks for the help!

**Comment by Jakob5566** [comment]
I've now testet the new build and something is wrong. I cannot choose Danish in Language Selection. What could possibly be wrong?

**Comment by gregory38** [comment]
I think it is normal. So far only the source code was updated. I will push the precompiled mo file on my next compilation.

**Comment by Jakob5566** [comment]
Okay - didn't know that :)

**Pull request merged**
