### PR TITLE
GS/HW: Don't try to dirty targets which don't overlap

### LINKED ISSUE #5431: [BUG]: Rally Fusion - Race of Champions (USA) car texture bug
### Describe the Bug

Rally Fusion - Race of Champions (USA) SLUS-20361 (1.02) car texture bug (game run is slow)

screenshot 1
screenshot 2

### Reproduction Steps

in game play only

### Expected Behavior

_No response_

### PCSX2 Revision

1.7.2271

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i7

### GPU

gtx 950m

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

The current invalidation code sucks, but at least this stops things which are blatently wrong from happening.

TC:NYC will have some slight glitches after this PR, I'll fix that in a follow-up.

Fixes rainbow vomit in COD2, haunting ground mirror, glitched textures in rally fustion, maybe others..

### Rationale behind Changes

Untitled

Fixes #5431.

### Suggested Testing Steps

Test affected games.

### CODE REVIEW

**Review by JordanTheToaster — APPROVED** [review]

**Comment by EnekoT2001** [comment]
Just checked haunting ground and it works perfectly! I'd consider it perfectly playable now, it has 0 bugs and 0 glitches now, this is so amazing! You made my day, week, and probably month tbh im so happy, i also tested forbidden siren 2 (it was another game i had in handy) and i see no regressions at all.

Also, this also fixes the transparency isues on haunting ground (spoiler for very late in the game) 

<details>
 <summary>Screenshots (spoilers)</summary>


Haunting Ground_SLES-52877_20230223122014

Haunting Ground_SLES-52877_20230223122909


Haunting Ground_SLES-52877_20230223122910

</details>

**Comment by pjagiello** [comment]
This also seems to fix a longstanding Gradius V cutscene glitch! (https://github.com/PCSX2/pcsx2/issues/6958)

**Comment by RedDevilus** [comment]
There will be a ton of other fixes, but kinda hard to detect which games it fixed but thanks for reporting.

**Comment by xRassyx** [comment]
the latest pcsx2 update brought back the rainbow issue in haunting ground. its much worse now

**Comment by xRassyx** [comment]
https://imgur.com/a/GuMkmQu

**Comment by xRassyx** [comment]
[https://imgur.com/a/GuMkmQu](url)

**Comment by refractionpcsx2** [comment]
yeah we're aware

**Comment by xRassyx** [comment]
is there a fix for it? i kind of wish that i can roll back my flatpak version of pcsx2

**Comment by refractionpcsx2** [comment]
You could not use flatpak and just download an app image of an older version from our website.

**Comment by xRassyx** [comment]
im unsure of the site and i appreciate your help

**Comment by EnekoT2001** [comment]
> the latest pcsx2 update brought back the rainbow issue in haunting ground. its much worse now

wow just tried it and yeah completely broken sadly, will use an older version until is fixed, i hope it gets fixed because pcsx2 keeps getting new QoL improvements and new features and i dont wanna miss out on those :( i was really happy to be able to use the official build finally after months of having to compile it myself by mixing a PR build and the main build

**Comment by refractionpcsx2** [comment]
how can you not know our website but use our app? O_o its pcsx2.net, it's not rocket science, a quick google would have got that too.

**Comment by xRassyx** [comment]
it only lets me download the latest version of the stable or builds

**Comment by refractionpcsx2** [comment]
if you go to the "downloads" section, there's a previous versions tab.

**Comment by xRassyx** [comment]
oh nevermind! thanks!

**Comment by EnekoT2001** [comment]
do any of you know which build is the last one that doesnt have this issue btw? been trying a few but no dice :(

**Comment by refractionpcsx2** [comment]
I don't but I guess go for the one after this? so 4128

**Comment by EnekoT2001** [comment]
That's weird the last version i used was 4179 and i don't remember having any issues, i tried it again and it works fine, ill keep trying going to newer versions until i find which one broke it

**Comment by refractionpcsx2** [comment]
Then use that, I guess?

**Comment by refractionpcsx2** [comment]
4297 is probably the version that broke it.

**Comment by EnekoT2001** [comment]
> 4297 is probably the version that broke it.

ok yeah i just checked and 4296 works fine and 4297 has the issue so it's that, thank you ! do you know if stenzek is aware of this issue? i want to explain the issue in that PR but maybe they already know, thank u again

**Comment by refractionpcsx2** [comment]
Sten is very much aware, just got bigger fish to fry at the moment, I'm sure he will get around to looking at it at some point

**Comment by EnekoT2001** [comment]
Oh i understand, I'll keep an eye out and use the older version for HG in the meanwhile then, thank you and sorry to bother

**Pull request merged**
