### PR TITLE
3rdparty: Upgrade PortAudio to v190600_20161030

### PR DESCRIPTION
**Pull request by MrCK1**
Changelog: https://app.assembla.com/wiki/show/portaudio/pa_stable_v190600_20161030

- The repo has been moved to Git, and is now being hosted on Assembla [here](https://app.assembla.com/spaces/portaudio/git/source/master?type=branch).

- 2 commits that were pushed after release have been included here as well. (A typo fix for CMakeLists.txt and another small patch).

- I've left out the "extraneous folders and files" using the previous upgrade as a reference, but nothing important should be missing otherwise.

- ~#390~ and ~#1775~ should be revisited to see if any issues still exist.

### CODE REVIEW

**Comment by gregory38** [comment]
2nd issue is on Linux which don't use the 3rdparty.

I would like to know the status of the first bug before any merge. I don't want to add a port audio regression for no gain. Besides maybe we could move them to submodule too to avoid more pollution of the git history

**Comment by mirh** [comment]
> uuid.lib(cguid_i.obj) : error LNK2005: _GUID_NULL already defined in portaudio.lib(pa_win_wdmks.obj) [C:\projects\pcsx2\plugins\spu2-x\src\Windows\Spu2-X.vcxproj]

> C:\projects\pcsx2\bin\plugins\Spu2-X.dll : fatal error LNK1169: one or more multiply defined symbols found [C:\projects\pcsx2\plugins\spu2-x\src\Windows\Spu2-X.vcxproj]

**Comment by MrCK1** [comment]
Closing this for now. We can upgrade PortAudio at a later date, and probably integrate it as a submodule instead. The remaining issue above seems to be internal to PortAudio but I don't know if it ever got squashed in a newer release.

**Comment by turtleli** [comment]
So... not sure if you've noticed or not, but this PR doesn't even build on AppVeyor.

**Comment by MrCK1** [comment]
@turtleli Since there more work do be so, I wasn't paying attention to Appveyor. Does it need to be added to the build list or something?

**Comment by MrCK1** [comment]
Yeah, that's what I did the 2nd time around here.

Either way, don't merge this yet. I still have to look into HostApi behavior and make sure nothing in PortAudio_Out has been deprecated ect. It seems to have changed between the old and new plugins.

**Comment by atomic83GitHub** [comment]
Any status on this? My laptop show the same issue as #390 (IDT audio ship with microsoft high definition audio driver.).

**Comment by MrCK1** [comment]
@turtleli This should be good to go now that the #390 is closed.

**Comment by turtleli** [comment]
> 2 commits that were pushed after release have been included here as well. (A typo fix for CMakeLists.txt and another small patch).

What's the other patch?

**Comment by MrCK1** [comment]
I believe it was this one: https://app.assembla.com/spaces/portaudio/git/commits/bc40f42cba713db3349bb1120b5d3475dd45e37e

There was only 3 additional commits made since the release here anyways: https://app.assembla.com/spaces/portaudio/git/commits/list

**Comment by turtleli** [comment]
> I believe it was this one: https://app.assembla.com/spaces/portaudio/git/commits/bc40f42cba713db3349bb1120b5d3475dd45e37e

It's not.

**Comment by MrCK1** [comment]
Sorry, I think my original description was wrong, only the CMake patch could have been added since the other 2 commits were made after this PR was opened.

**Comment by turtleli** [comment]
I think the commit message should mention the additional commit that was added.

**Comment by lightningterror** [comment]
@MrCK1 Status ?

**Comment by MrCK1** [comment]
Sorry, I forgot about that. I'll work on it soonish.

**Comment by MrCK1** [comment]
Sorry for letting this sit so long. I'm totally lost on what additional commits I've added ect, and I also have additional plans in the future which may be integrated into another PR. I will come back to this once I get a chance to review some code.

**Pull request closed without merging**
