### PR TITLE
Console log message for current renderer.

### PR DESCRIPTION
**Pull request by ssakash**

### CODE REVIEW

**Comment by ssakash** [comment]
The following PR creates a log message with the current renderer mentioned on the message. did some testing and looks stable enough. :)

**Comment by karasuhebi** [comment]
So when will the current renderer be printed in the log? Upon launch? When you switch renderers in the GSdx Plugin Settings window?

**Comment by ssakash** [comment]
Yes, on both of those instances and additionally when F9 toggle is done.

**Comment by karasuhebi** [comment]
Sweet!

**Pull request merged**
