### PR TITLE
GameDB: Add Tiger Woods PGA Tour series VU Clamping Mode fixes

### PR DESCRIPTION
**Pull request by FlatOutPS2**
Fixes black textures on characters in Tiger Woods PGA Tour 2004, 2005,
and 06 through 10.

Also add Jak 2 US CRC to GSCrc list. Fixes issue: #1603

### CODE REVIEW

**Comment by avih** [comment]
Do you know for a fact that the DB fix works on all the versions which you modified?

**Comment by FlatOutPS2** [comment]
All games use the same engine and have the exact same issues. I can't confirm 2008 and 2009, but as it has been confirmed they have the exact same issue and engine, the fix should be the same too.

The name changes are the correct ones. The previous names weren't in sync with the online list, some aren't now because the years on the compatibility list don't use the abbreviation (2006-2006 should be 06-10), otherwise they're in sync now.

**Comment by avih** [comment]
OK, please add to the DB commit message which serials are known to fix the issue and which are presumed to fix it.

**Comment by gregory38** [comment]
Thanks for the jak2 crc.

**Comment by avih** [comment]
Thanks. For some reason I didn't get a notification when you updated the commit message, and only noticed it now.

**Pull request merged**
