### PR TITLE
GameDB: Add Mipmap and Trilinear to The Incredibles

### PR DESCRIPTION
**Pull request by Buzzardsoul**
### Rationale behind Changes
The streets were looking inaccurate in #7969 's gs dump.

### Suggested Testing Steps
Make sure that I have not missed any game region.

### CODE REVIEW

**Comment by Buzzardsoul** [comment]
> You should use full mipmapping and trilinear filtering if you are going to add it.

I will add those.

**Comment by Buzzardsoul** [comment]
Done and done! :D

**Comment by JordanTheToaster** [comment]
Also could you squash all 3 of these commits? Sorry :P

**Comment by Buzzardsoul** [comment]
i'll open a new one then.

**Pull request closed without merging**
