### PR TITLE
Several Compilation Fixes for Fedora System

### PR DESCRIPTION
**Pull request by jobs-git**

### CODE REVIEW

**Comment by gregory38** [comment]
I'm bit surprised that it doesn't work on Fedora, never got complains so far. 

Do you really have an /usr/lib/i686 directory ? And what is `nosegneg` ?

**Comment by jobs-git** [comment]
I don't what fedora devs did, that is were glib and glibc dependencies are located.

**Comment by turtleli** [comment]
What version of Fedora are you using?

**Comment by jobs-git** [comment]
I am in Fedora 21 x86_64

**Comment by jobs-git** [comment]
I can confirm to have successfully cross-compiled PCSX2 (32bit) on Fedora x86_64 system without any special attempt other than satisfy all dependencies. It's up to the developers now if its mergeable.

**Comment by turtleli** [comment]
Hmm. I can compile and run PCSX2 **without** this PR on a Fedora 23 x86_64 VM (wxGTK3 GTK3 SDL1.2). Are you sure you have everything set up correctly?

**Comment by frantisekz** [comment]
I can compile on F23 without this PR too. (wxGTK3, GTK3, SDL2)

@turtleli if you want SDL2 on Fedora,  check out my copr build of wxGTK: https://copr.fedorainfracloud.org/coprs/frantisekz/wxGTK3-SDL2/

@jobs-git Why are you testing this on unsupported Fedora release?

**Comment by jobs-git** [comment]
I guess this is a problem with fedora 21, it seems its difficult to support fedora release, as it changes too fast. I am closing this now.

**Pull request closed without merging**
