### PR TITLE
GSdx: Adjust Aggressive state crc level.

### PR DESCRIPTION
**Pull request by lightningterror**
Create a Aggressive state function instead of adjusting the hacks
separate, move the aggressive only there, also use "else if" checks
instead. It's more efficient this way.

### CODE REVIEW

**Comment by turtleli** [comment]
> also use "else if" checks instead

I don't think this is correct?

**Comment by avih** [comment]
I think this patch hurts readability because now when you look at one of those functions you can't tell it's an aggressive hack, especially when aggressive is still used at other functions which have also non-aggressive hacks.

Performance wise, absolutely negligible.

I don't think it's worth it.

**Comment by lightningterror** [comment]
> I think this patch hurts readability because now when you look at one of those functions you can't tell it's an aggressive hack, especially when aggressive is still used at other functions which have also non-aggressive hacks.

You could say the same for partial and full level then, anyway when I first open the file I check the states in the bottom to find out which group of category they fall in to, also the hack themselves are still separated and grouped.

> I don't think this is correct?

The description ? I could put statements instead.

**Comment by avih** [comment]
> You could say the same for ...

I guess we see things differently.

**Comment by lightningterror** [comment]
Ah you're right about that, I guess it slipped my mind.

**Comment by lightningterror** [comment]
I meant as in this method is more efficient(better), since it doesn't call the games on aggressive state anymore on lower level when it does nothing.

**Pull request merged**
