### PR TITLE
Pad: Jogcon and Negcon emulation

### LINKED ISSUE #10698: [Feature Request]: Namco neGcon controller support
### Description

As initially discussed with Stenzek and pandubz on Discord, the Namco neGcon is officially supported by a bunch of PS2 titles such as Ridge Racer V. You can technically emulate a DS2 with the neGcon, but then officially supported games won't expose neGcon calibration options or change buttons prompts to neGcon prompts (I, II, A, B).

### Reason

Would enable accurate emulation of the Namco neGcon controller in officially supported titles.
Would enable for better steering precision in racing games, considering you can't replicate the "neGcon mode" twist precision even when using it as a DualShock 2.

### Examples

RRV
Example screenshot of how Ridge Racer V behaves once it detects a neGcon controller: button prompts are changed to match the neGcon and a special "neGcon calibration" option is unlocked.

### PR DESCRIPTION
**Pull request by Florin9doi**
### Description of Changes
- Jogcon and Negcon emulation
- [x] ~Draft at the moment because the controller windows only have placeholder images. Any volunteer interested in contributing?~

### Rationale behind Changes
- Closes #10698

### Suggested Testing Steps
- Ridge Racer V

### CODE REVIEW

**Comment by kamfretoz** [comment]
Here's the one for Negcon:
image

And here's the file:
[Negcon.zip](https://github.com/user-attachments/files/16403839/Negcon.zip)

**Comment by kamfretoz** [comment]
And here's for Jogcon:
image

Here's the file:
[Jogcon.zip](https://github.com/user-attachments/files/16407768/Jogcon.zip)


Credit to MBee as always.

**Comment by lightningterror** [comment]
> And here's for Jogcon: image
> 
> Here's the file: [Jogcon.zip](https://github.com/user-attachments/files/16407768/Jogcon.zip)
> 
> Credit to MBee as always.

Maybe the images can be darkened to match the existing dualshock image we use for consistency.

**Comment by kamfretoz** [comment]
> Maybe the images can be darkened to match the existing dualshock image we use for consistency.

We were aiming for accurate depiction of the real controllers itself.

**Comment by Florin9doi** [comment]
I added the images and I'm marking the PR ready.
Thank you.

**Review by F0bes — APPROVED** [review]
Code lgtm. Savetstates work. Don't have any games that use these controllers to test with though.

**Comment by reif99** [comment]
IMG_0182
Did a Negcon pad get implemented?? I have the latest version of pcsx2 and are dying to use a real negcon in the PS2 games that support it

**Comment by kamfretoz** [comment]
> Did a Negcon pad get implemented?? I have the latest version of pcsx2 and are dying to use a real negcon in the PS2 games that support it

It does, for now you'll need to use the Nightly channel as this hasn't dropped into the stable channel just yet.

**Comment by reif99** [comment]
Having a go with Ridge Racer 7, the negcon is working great, well done!!

**Comment by eVenent** [comment]
Oh, wow. Tested it and it looks very cool. Unfortunately, there are not many Jogcon games for PS2. So far works great.
@Florin9doi are you planning to implement Jogcon in Duckstation too? 

Great job! It gives us motivation for playing Ridge Racer again. ❤

**Pull request merged**
