### PR TITLE
GameDB: Add EETimingHack to Cricket 2002

### LINKED ISSUE #8509: [BUG]: EA Sports Cricket 2002 (Europe) (v2.00) Graphic and Running Animation Bug
### Describe the Bug

1. A graphical bug when in any match in game, where a camera angle of the batting/bowling crease to the top left of the screen is displayed whenever the ball is hit, the camera however, overlaps with a picture from the menu screen. 

2. Running Animation issue- When batting and a ball is hit, you are unable to make a run as the batsmen simply move back and forth in a loop. This is also the case when the computer is on the batting team, however. occasionally the computer is able to make a run and display the entire running animation. 

Cricket 2002_SLES-50424_20230330123455
Cricket 2002_SLES-50424_20230330125513

### Reproduction Steps

Graphic Bug- Play Now > Select Batting or Bowling after the coin toss > Wait for if bowling or hit the ball if batting and the camera angle of the crease will display to the top left of the screen.

Running Animation Bug (Player Perspective)- Play Now > Select Batting after the coin toss > Hit the ball and press circle to make a run.

Running Animation Bug (Computer Perspective)- Play Now > Select Bowling after the coin toss > Bowl a ball and wait for the AI or computer to make a run. 

### Expected Behavior

The camera angle of the batting/bowling crease is not supposed to overlap with a patch/image from the menu screen.

The running animation is supposed to function as in the game of cricket where the two batsmen run across to each other's opposing end in order to complete a run. The current bug/glitch is detrimental to the fundamentals of the game as a single run affects the score in a match of a longer duration. 

The game's ball and batting physics is the best I have seen of a cricket game which is why I really hope these little yet very impactful details like the running animation could be fixed at the very least. 

Cricket 2002_SLES-50424_20230330125513

### PCSX2 Revision

PCSX2 v1.7.4287

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

AMD Ryzen 5 4500U

### GPU

AMD Radeon Graphics

### GS Settings

Rendering: Internal Resolution - 3x Native (1080p)

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by Buzzardsoul**
### Rationale behind Changes
As was discussed in #8509, this fixes the running animation, however, it does not fix the other issue that was mentioned. As such it will not close it.

### CODE REVIEW

**Comment by Mrlinkwii** [comment]
the rounding it had  added ( the last few days) should of fixed it

**Comment by Buzzardsoul** [comment]
> the rounding it had added ( the last few days) should of fixed it

I don't own the game so I wouldn't know. If this is not needed. You guys are free to close it.

**Comment by refractionpcsx2** [comment]
okay well do you want to confirm with the guy you asked to set it if it works without it?

**Comment by Mrlinkwii** [comment]
apart from the  HW  mode issue , the game seems fine on master

**Comment by Buzzardsoul** [comment]
> okay well do you want to confirm with the guy you asked to set it if it works without it?

All in which he mentioned was that the EEtiminghack fixes the running animation and that the Software renderer fixes the graphical bug. Take that as you will. But I trust that @Mrlinkwii is more knowledgeable about this situation. As such I will close this for now.

**Pull request closed without merging**
