### PR TITLE
Qt: Use black and white icons for github and discord

### PR DESCRIPTION
**Pull request by TellowKrinkle**
### Description of Changes
Follow up for #8724
Switches github icon to a separate black and white icon
Switches discord from a blue icon to black/white

### Rationale behind Changes
Outlines on icons don't work so well at 32x32

### Suggested Testing Steps
Look at menu bar icons

### CODE REVIEW

**Comment by kamfretoz** [comment]
Looks perfect on Windows!

Dark theme:
pcsx2-qt-clang_RAvBZYUI4x

White theme:
pcsx2-qt-clang_X8WBzhpJbV

Do you think it's worthwile to change the icon for the forum as well or is it good enough as it is already?

**Comment by TellowKrinkle** [comment]
Up to you.  It's multiple colors, so it probably won't have as much trouble with blending in to backgrounds.  But it's also now one out of like 3 icons that are color, with all the rest black/white.

**Comment by kamfretoz** [comment]
for the sake of consistency, i'll look for a better forum icon replacement

**Review by JordanTheToaster — APPROVED** [review]

**Review by Mrlinkwii — APPROVED** [review]

**Comment by JordanTheToaster** [comment]
Also fixes the console log "iCCP: known incorrect sRGB profile."

**Pull request merged**
