### PR TITLE
GameDB: Fix glows in Ratatouille

### PR DESCRIPTION
**Pull request by NicknineTheEagle**
### Description of Changes
Enable Auto Flush GS HW hack in Disney-Pixar Ratatouille.

### Rationale behind Changes
Fixes glows from lights showing up through walls in the game.

### Suggested Testing Steps
Bug can be easily reproduced in the very first level by looking at the sun with and without obstructions.

### CODE REVIEW

**Review by lightningterror — COMMENTED** [review]
Can you post a gsdump of the issue?

**Comment by NicknineTheEagle** [comment]
> Can you post a gsdump of the issue?

Here you go.
[ratatouille_glows_bug.zip](https://github.com/PCSX2/pcsx2/files/9088178/ratatouille_glows_bug.zip)

**Comment by lightningterror** [comment]
I wasn't able to reproduce the issue that requires auto flush.

**Comment by NicknineTheEagle** [comment]
> I wasn't able to reproduce the issue that requires auto flush. Maybe the angle is not good when you took the dump.

That is strange, it's reproduced consistently on my end. Did you happen to change GS settings while the sun was obstructed? What happens is that glows are just not updated so if, for example, you switch from SW to HW while the sun is obstructed, the sun glow will permanent disappear instead.

**Comment by lightningterror** [comment]
Does the issue also appear on sw renderer if you disable auto flush?

**Pull request merged**
