### PR TITLE
PCSX2: Minor lingual correction of a Trace Logging text-string.

### PR DESCRIPTION
**Pull request by pgert**
Minor lingual correction of a Trace Logging text-string.

### CODE REVIEW

**Comment by lightningterror** [comment]
Small nitpick, can you update the commit name and description to something like this perhaps ?

> Name/summary:**PCSX2: Minor lingual correction.**
> Description: **Small correction to trace logging string.** or **Update trace logging message/string.**

Makes it a bit more clear what the changes are.

**Comment by pgert** [comment]
This string annoys me: it isn't the enabling of trace logging that is typically very slow, but trace logging itself (right?). The string is translatable, and since there are other PRs up right now that also changes translatable strings, then this should be a good time to alter this.

I should have posted this in a seperate comment, so I'll post it here.

**Comment by FlatOutPS2** [comment]
@pgert What is done? The commit title and message are unchanged.

**Comment by pgert** [comment]
The first comment is what shows in the build-description, isn't it?.

**Comment by lightningterror** [comment]
You need to rebase the existing commit.
Open Git shell on your master branch > git rebase -i HEAD~1 > you will see the commit in the text editor opened > you replace "pick" with "r" > first row is the commit title, second row is empty, third row is the description
image
> you save the file > on git shell again you type git push -f
And your changes should be pushed.

**Comment by pgert** [comment]
I don't have Git installed, but use TortoiseSVN only.
Would a change of the title into "Minor lingual correction of a Trace Logging text-string" be enough?

**Comment by lightningterror** [comment]
It should be ok tho add the PCSX2 at the beginning.
Something like this 
`PCSX2: Minor lingual correction of a Trace Logging text-string.`

**Comment by pgert** [comment]
OK. Sorry for the inconvenience.

**Comment by lightningterror** [comment]
Ah when you said title I thought you meant commit title, I'm not sure how you do it in TortoiseSVN, what we are saying is the commit title needs updating not the PR title.

I don't know if those with write access can rename the commit properly.

**Pull request merged**
