### PR TITLE
onepad: add a first time wizard to notify that plugin auto-map the Gamepad

### PR DESCRIPTION
**Pull request by gregory38**
It should avoid some bug reports of not-working-as-expected GUI

Please review the wizard user string.

### CODE REVIEW

**Comment by gregory38** [comment]
@turtleli Could you review my English. Thanks you.

**Comment by ramapcsx2** [comment]
May I?
"The OnePad GUI is mostly provided to map keyboard/mouse to the virtual PS2 pad"
I recommend making that:
"The OnePad GUI is provided to map keyboard/mouse to the virtual PS2 pad"

"Gamepads/Joysticks are Plug & Play. Player Gamepad can be selected in the 'Gamepad Configuration' panel."
Not sure, but is this meant to say:
"Gamepads/Joysticks are Plug & Play. The active Gamepad can be selected in the 'Gamepad Configuration' panel."

The other string is fine, imho :)

**Comment by gregory38** [comment]
of course. Thanks you 👍

**Comment by turtleli** [comment]
I'd add 'the' between 'map' and 'keyboard/mouse' in the first sentence, and use a lowercase g for gamepad in the final sentence. I'd also use 'and' instead of '&' in the second sentence, though that might just be my personal preference.

**Comment by gregory38** [comment]
Done. Do you prefer uppercase or lowercase for the Plug and Play.

**Comment by turtleli** [comment]
Probably lowercase? Don't have a strong preference.

**Comment by gregory38** [comment]
It was to follow the Plug and Play trademarks.

**Comment by turtleli** [comment]
I'm guessing lowercase is probably correct, but I've been contaminated by Windows. ;)

You forgot to make 'Gamepad' in the final sentence lowercase.

**Pull request merged**
