### PR TITLE
fxaa.fx: Purge d3d9 shader code

### PR DESCRIPTION
**Pull request by lightningterror**
Looks like I forgot this one.

### CODE REVIEW

**Comment by gregory38** [comment]
Did you check external shader too ?

**Comment by lightningterror** [comment]
Yeah I already purged it in the first pr.
https://github.com/PCSX2/pcsx2/pull/2762/files#diff-af3f7d4af20ebd169a87459cd23d36a1L24

**Comment by gregory38** [comment]
Check gl too as it is the same compiled file.

**Comment by lightningterror** [comment]
> Check gl too as it is the same compiled file.

I know, I did the changes with that in mind.

**Comment by gregory38** [comment]
Perfect

**Pull request merged**
