### PR TITLE
Gsdx pseudo depth read

### PR DESCRIPTION
**Pull request by gregory38**
Purpose of PR is to support all possible color/depth conversion during a read. I don't know if games use those cases but at least something is implemented.

### CODE REVIEW

**Comment by gregory38** [comment]
Actually I'm not sure it will fix any issue :(

**Comment by gregory38** [comment]
TODO for myself:
extract useful bit of patch 3 and potentially target_psm.bpp of patch 2.

**Comment by ramapcsx2** [comment]
Ah yeah, that code.. I think it affected Grandia 3 and FFX-2 (pause screen in both titles), the slowness of opening menus in ArTonelico and, from the comments, Busen0: Wizardry and Chaos Legion.

I recommend you make this a configurable user option so you can work on this / people can test it better.

**Comment by gregory38** [comment]
Drop the code until I found a real testcase to validate those depth read.

**Pull request closed without merging**
