### PR TITLE
Add hack for R3 save state, remove hack for Save State in Title (PCSX2 does it now)

### PR DESCRIPTION
**Pull request by Sarania**
Not ready for merge yet(new stuff to add I guess) Basically what it says above - I removed the "Save State in Title" hack because PCSX2 does it now. In it's place, I added an "R3 Saves State" hack. PLEASE IGNORE ALL COMMITS BUT THE LAST ONE(e.g. the overclock stuff) as I was still learning Github when I did that and so did it on the master branch and it carried over when I made a branch. The overclock stuff was reverted before I did this lilypad stuff! Also that made the comments for that appear here. Anyway, I learned it now so that won't happen again at least XD

I did the work and tested it thoroughly, but please feel free to go over the changes and see. Also, here is a screenshot:

### CODE REVIEW

**Comment by avih** [comment]
I don't quite get how we have the previous discussion of the EE thingy here on this Lylipad PR...

**Comment by Sarania** [comment]
@avih 
Because of what I explained here http://forums.pcsx2.net/Thread-Github-help

And I know that about branches now, but I didn't when I did the OC stuff and so even when I make a new branch now, it includes the OC stuff. Anyway I know how to get rid of it now, and once this particular PR is dealt with, I will.

**Comment by karasuhebi** [comment]
Looks good to me. Although I believe it should be 'R3 saves state', and while you're at it, why not make the word 'toggles' lowercase in the L3 option as well? Turbo seems like a proper noun though so that's OK. :)

While we're at it, which slot does it save in? 0? Also could you make it so R3+button loads the state? That would be sweet.

**Comment by Sarania** [comment]
I can make it say "R3 Saves State" and I can _probably_ make it so that R3 + something loads state, I'll have to look into that.

It saves in the currently selected slot - all it does is send a push of F1 to PCSX2.

**Comment by karasuhebi** [comment]
@Sarania I think the key (see what I did there? XD) to this option's appeal is the fact that you don't need to interact with the keyboard at all, that it's done entirely via your controller. So I don't think it should be R3+key, but R3+button. As far as wish button? I'm not entirely sure on that. My first reaction was R3+Select or R3+Guide/PS but maybe ask for some feedback in the forums?

**Comment by Sarania** [comment]
@karasuhebi 

Yeah I meant what button. With my Joy2Key setup I always did R3 save and select load, so R3 + select seems reasonable. I'll look into that.

Also I changed it to "R3 saves state" and "L3 toggles turbo" (it just looked weird as "L3 toggles Turbo")

I'll probably also group the L3/R3 ones together.

**Comment by karasuhebi** [comment]
@Sarania Yeah I know what you mean with the casing on the L3 option. Do you have any control over the width of that options box? If you can make it a bit longer maybe you can fit 'L3 toggles Turbo Mode' or something like that. Also I like the idea about putting the two options next to each other.

**Comment by Sarania** [comment]
@karasuhebi I do have control over it, but things get messy if I alter it. Lots and lots of repositioning to do to make everything nice. I was lucky about the deprecated "Save state in title" which gave me space lol.

**Comment by karasuhebi** [comment]
@Sarania Haha understood. It's funny how things just work out sometimes. :D

**Comment by Sarania** [comment]
Given the space issues, if I do add the combo for load, I wonder how to make it known? It would be a shame for it to be a "hidden feature"

**Comment by avih** [comment]
Well, first of all, it doesn't do save state but rather "Press F1", so it only works if F1 is mapped to save state (which it is by default - but users can change it via PCSX2_keys.ini).

Also, IIRC Lylipad also works as a PS1 plugin and IIRC the save state title hack is useful there, and this is the only/official repository of Lylipad, so this will remove this feature when used as a PS1 plugin (it was also useful as a PCSX2 plugin hack but it was also buggy so we moved the save state title into PCSX2 itself some time ago and fixed the bugs).

Also, we already have an "R3 toggles turbo" hack, so what happens if both of them are checked? it should probably a radio button which doesn't let you choose both of them together. Or a drop down menu which lets you choose a "special" action/hack for R3.

So overall, while not useless, I think it's a bit hacky.

Isn't it possible to use a tool such as motionjoy or something similar, and just use it to map whatever gamepad buttons to whatever key presses without being limited to hacks which Lylipad offers?

**Comment by Nobbs66** [comment]
That's one reason I opted to try and do a proper binding in lilypad. Speaking of which, why don't we just increase the window size for lilypad and add swapable bindings for the turbo hack as well.

**Comment by Sarania** [comment]
@avih - I'll have to check if the save state title thing works with PS1 - if it does, I can keep it and work around that. I only removed it because you had marked it as deprecated, and I was derping about it being used in PS1 emulators.

As for R3 toggles turbo - what? We have an L3 toggles turbo hack, but I don't know of any on R3.

As for the last bit, yes there is ways to do it with 3rd party programs, but it's always nice to not have to.

**Comment by karasuhebi** [comment]
@avih I'll admit that your F1 key concern is a valid one but it's my understanding that the R3 hack which is already implemented works the same way. I also definitely agree with putting the old option back in place, since as you said this is a PS1 plugin as well. I would imagine @Sarania didn't know that at the time he coded this. Thanks for the info on that because I surely didn't.

And yes, It's entirely possible to do all of this via JoyToKey, but so is mapping all of your controller's buttons to corresponding keys on a keyboard to play a PS2 game in PCSX2. So by that logic, Lilypad's controller binding feature is in itself not needed. All you need is Lilypad's keyboard bindings + JoyToKey and you're good to go :p

Also the turbo mode is L3, not R3 so there's no need to worry if they're both checked.

This is definitely a hack but I can still see its usefulness, specially as a stopgap measure while either @Nobbs66 or @Sarania find a way to implement this properly.

**Comment by avih** [comment]
Right, I confused R3/L3. Sorry.

Still this R3 hack and the other L3 hacks are sort of fixed, limit users to these exact buttons and these exact hacks. What is someone wants to bind R3 to slow motion? Or bind L4 to GSdx HW/SW rendering?

The scope of the hack is very limited, and it add hacks to Lilypad.

An external tool, especially if there's a simple open source one (which I don't know if there is - I don't use gamepad mapping tools) would be better suited for such task IMO.

Though still, while I didn't try it out, the hack itself seems relatively safe, but still has all these limitations which I mentioned.

**Comment by Nobbs66** [comment]
@avih  Why can't we create an actual binding option like we have for the rest of the ps2 controls? We have the mouse binding. So, why couldn't we add a save and load state binding?

**Comment by Sarania** [comment]
Yeah okay, the save state in title does work with PCSX-R (although for whatever reason, the save state hotkey fails to work with lilypad chosen as plugin lol). So I can put that back in, I wasn't thinking there. I'll have to lengthen the options menu, but that might be best since I can fit in info about the Load state combo then too.

Also, the state keys are the same in PCSX-R, so this would actually work there too.

As for people changing the default hotkeys - I don't think there are many, and those that do likely aren't wanting to bind them to the controller anyway.

Personally myself, I always used JoyToKey for this before, but half the time I forget to run it first, and it's a pain. Also I'm not sure there are any open source ones - I only know of JoyToKey and xpadder.

**Comment by avih** [comment]
> @avih Why can't we create an actual binding option like we have for the rest of the ps2 controls? We have the mouse binding.

Yeah, I thought of that too. If we're putting such stuff inside Lylipad, we might as well add 3 custom bindings to the "normal" PS2 gamepad buttons, where we can map a gamepad button to custom/1/2/3 and then set each of the custom ones to generate a user configurable keypress.

**Comment by karasuhebi** [comment]
@Nobbs66 I think that would be ideal but isn't that what you've been trying to do without any success up to this point? I'm guessing it's not as easy as it sounds so like I said, this could be a nice stopgap while you guys figure out how to implement it the 'proper' way.

@Sarania Given the space issues, I would suggest adding in tooltips so that the L3+button thing doesn't turn into a hidden feature. I would also take that tooltip as a chance to tell people that this only works with the default hotkey binds in PCSX2.

**Comment by Sarania** [comment]
@avih @Nobbs66

That's another way to go about it too, and I guess it would be the most versatile as well.

**Comment by Sarania** [comment]
Although just FYI - this is not far from a binding itself, since whatever key the user binds to R3 will be the one used. The only drawback here is not being able to use R3 in games.

**Comment by Nobbs66** [comment]
You're not directly using the save state function though

**Comment by Sarania** [comment]
I'm not sure you can even do that from within a plugin, it would have to be exposed via the framework.

**Comment by avih** [comment]
AFAIK, correct, the API between PCSX2 and the input plugin only allows it to pass PS2 gamepag information and not generic commands like "do save state".

But a generic custom bindings where the user chooses which keypress is generated by which gamepag button bypasses this relatively elegantly.

**Comment by Sarania** [comment]
@avih oh I see, Like you could make a binding "When I press X, send Y" key, so even if the user had changed the hotkeys, it would work.

Yeah that's pretty sweet. I like that way,

**Comment by Sarania** [comment]
The trick with that is twofold though, now that I think about it. #1 it's a double binding(key to press, key to send) which I'm not sure can be implemented sanely. #2 That would likely confuse users a good bit more than simple checkbox.

**Comment by karasuhebi** [comment]
@avih Speaking of which, is there plans to implement changing hotkeys into the UI? I think that'd be pretty useful plus it would expose more people to the knowledge that it's actually something you can do in PCSX2. I would venture a guess most users don't know they have the option to change hotkeys (or which hotkeys are there by default) in the first place.

**Comment by avih** [comment]
Yeah, it requires some thingking on how to present it. It's basically adding the functionality of Joy2Key into Lylipad.

Technically, Lylipad has all the required functions already (to capture both the gamepad key which generates the keypress and also the capture the keypress which will be sent).

Maybe add another tab of Pad2Key and play with the UI for it there?

**Comment by Nobbs66** [comment]
Yeah, I would add a new tab in the gui

**Comment by Sarania** [comment]
That would be the cleanest way to implement it, yeah.

**Comment by Sarania** [comment]
Well, that requires learning some new stuff about Lilypad, but it should be doable. I'll take a whack at it tomorrow. If it's TOO insane, like hours and hours and hours of work, then I think it's best just to fix this way up, put the "save state in title back" and so forth.

**Comment by avih** [comment]
> @avih Speaking of which, is there plans to implement changing hotkeys into the UI?

No such plans. If someone wants to work on it, patches are welcome.

As for the fact that it's not advertised, there were some threads on the forum with some suggestions, but that's off topic for this PR.

**Comment by Sarania** [comment]
@avih @karasuhebi @Nobbs66 

Since I'm gonna try the other way, I'll close this PR for now(that way I can sort my fork issues out too). Once I get things sorted(either the new way or a better version of this one), I'll make a new one.

**Comment by ramapcsx2** [comment]
Just chiming in to say I like where this was going. Cheers :)

**Comment by imkrut** [comment]
Is there any progress on this front? Personally, I think having a "hotkey" button that allows you to combo with another button is the way to go (obviously with custom mapping).

So for example, you press R3 as the hotkey and while holding you can press say, L1 for loading , R1 for saving , L2 for fastforward press and R2 for Fastforward toggle, and R3 + Home/guide could be exit.

Obviously the R3 hotkey can be something else, and you can potentially map other stuff like R3 + Dpad.

I have the same method on retroarch and it works perfectly for all systems

**Comment by ramapcsx2** [comment]
@imkrut Is this the default mapping in Retroarch (or your own unique setup)?

**Pull request closed without merging**
