### PR TITLE
GS: Handle Auto Flush across pages + improve performance

### LINKED ISSUE #168: Graphics issue: Jak 3 (USA) - SCUS97330 - Corrupted textures and excessive player shadow
**-PCSX2 version:**
1.2.1.r5873 - compiled on Feb  3 2014

**-PCSX2 options:**
Defaults, no settings modifications affect the issue.

**-Plugins used:**
- gsdx32-sse4-r5875
- lilypad-r5875
- spu2-x-r5875
- cdvdGigaherz

**-Plugin settings:**
Tested GSdx DX9/11 hardware;
DX11 seems to make things worse by having more of an impact.
SkipDraw 1 used to remove player shadow altogether.

**-Description:**
Basically, most textures are corrupted. One great example is the right eye of most characters (also an issue in previous installments of the game).

**-How to replicate:**
Boot the game and enjoy the black-textured landscape and corrupted eyes and miscellaneous objects.

**-Last known version to work:**
Unknown, probably never worked.

**-PC specifications: CPU:**
- Intel Core i5 650 @ 4.1GHz 54 °C
- 4.00GB Dual-Channel DDR3 @ 819MHz (9-9-9-24)
- Gigabyte Technology Co., Ltd. P55-UD6 (Socket 1156) 50 °C
- 1023MB NVIDIA GeForce GTX 560 Ti (EVGA) 69 °C
- 465GB Western Digital WDC WD5000AAKX-00ERMA0 ATA Device (SATA) 45 °C

**-Other comments:**
The graphical corruption, including the missing eye(s), is also present in previous installments, including, but not limited to Jak and Daxter (SCUS97558 & SCUS97124).

### LINKED ISSUE #3005: Ghosting effect in Sniper Elite and bad performance on split screen multiplayer
***PCSX2 version:***
``(1.5-3179)``

***PCSX2 options:***
``(OpenGl Hardware and Direct3D11 tested all settings default, tried every option on the video plugin menu only skipdraw "fixed" it but made a lot of graphical glitches occur, there's no ghosting effect on software modes but perfomance is terrible)``

***Plugins used:***
Everything default

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
This ghosting effect is the problem:
image
image

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
Launch the game with any Hardware mode

***PC specifications:***
CPU: Intel I3 6100 GPU: GTX 950 OS: Windows 7 64 Bit)``

### LINKED ISSUE #4950: [BUG]: Tomb Raider The Angel of Darkness: Software rendering glitch at the upper left of the screen.
### Describe the Bug

In the game "Tomb Raider The Angel of Darkness", there is a small glitch which appears in the upper left of the title screen with the software render. This bug existed for a very long time so it shouldn't be a regression.

### Reproduction Steps

Load the game, stay at the title screen with the software render.

### Expected Behavior

The game should display the title screen fine from the very top to the very bottom.

### PCSX2 Revision

pcsx2-v1.7.0-dev-1966-gbfbe86a3d5-windows-x86

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

I9 9900k

### GPU

RTX 3070

### GS Settings

Software render.

### Emulation Settings

_No response_

### GS Window Screenshots

The bug in action:

Software render:

Capture d’écran 2021-10-28 202926

### Logs & Dumps

GSdump:
[TR Title screen software issue.zip](https://github.com/PCSX2/pcsx2/files/7436588/TR.Title.screen.software.issue.zip)

### LINKED ISSUE #5081: Meta: Auto Flush destroying performance
### Description

Games that tank performance when using autoflush (SW and HW). On SW it's enabled by default. On HW it's disabled by default.

- [ ] Alter Echo
- [ ] Need For Speed Underground 2
- [ ] Need For Speed Undercover
- [ ] Hitman Contracts
- [ ] Spider-Man: The Movie
- [ ] Powerdrome

### Reason

Better to have a tracker for games that don't like autoflush.

### Examples

Alter Echo;
SW autoflush: 42% (20.79)
SW no autofl: 250% (124.90)
Lost VPS = -208%  (-104.11)

SWAutoFlushAlterEcho1
SWNoAutoFlushAlterEcho2

8x HW autoflush: 86% (43.02)
8x HW no autofl: 154% (76.93)
Lost VPS = -68%  (-33.91)

8xHWAutoFlushAlterEcho3
8xHWNoAutoFlushAlterEcho4

### LINKED ISSUE #5524: [BUG]: Ratchet and Clank Going Commando: Glitchy shadows in some specific scenarios.
### Describe the Bug

In the game "Ratchet and Clank going commando", there is a bug with the shadows where they will produces glitches in some very specific cases.

One of these case is when driving the mining vehicle on Grelbin, when in close proximity with the camera, the shadows will start glitching out by showing missing polygons/holes in geometry.

### Reproduction Steps

Load the GSdump and see the problem, or, take the mining vehicle on Grelbin and drive around those small dunes in the desert, you will see the shadows glitching out when the camera is near the vehicle.

### Expected Behavior

The shadows should not glitch out when in close proximity to the camera (verified on real hardware).

### PCSX2 Revision

v1.7.2360-1-g6ab77be8f	

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

I9 9900K

### GPU

RTX 3070

### GS Settings

Half pixel offset to special texture to fix some upscaling glitches.

### Emulation Settings

EE Timing hack, VU kickstart hack.

### GS Window Screenshots

The bug in action:

PCSX2 (not very obvious because it is hard to notice when camera is close, look for the missing shadow geometry under the vehicle):

Capture d’écran 2022-02-14 150835

### Logs & Dumps

GSdump:
[Ratchet going commando shadow glitch.zip](https://github.com/PCSX2/pcsx2/files/8061430/Ratchet.going.commando.shadow.glitch.zip)

Emulog:
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/8061432/emuLog.txt)

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Handles auto flushing across page boundaries to improve accuracy, also improve performance slightly by checking texture+page boundaries.

### Rationale behind Changes
Auto flush was very aggressive and didn't really emulate the behaviour of the PS2 caching 1 page of texture in memory very well. Plus due to the aggressiveness it flushed a lot more frequently than it needed to.

### Suggested Testing Steps
Test games that require auto flush, make sure they work okay, note any performance or graphical improvements. This affects Software and Hardware modes.

Jak 2 in 3x native has increased from 32fps in the below scene to 92fps!  (To get the lighting correct when upscaling you need HPO (Special Texture) )

Jak 3's shadows during the intro are fixed and performance is again about 3 fold. Fixes #168

Beyond Good and Evil water almost looks like water, it might be actually fixed in the game, but it's hard to tell from a GS Dump.

Tomb raider menu is fixed. Fixes #4950

Fixes glitchy shadow in Ratchet & Clank Going Commando. Fixes #5524

And as for the tracking thread for Auto Flush killing performance, it's no longer a huge issue, so Fixes #5081

Performance impact from post effect in Sniper Elite is also brought down to basically nothing so it can be turned permanently on. Fixes #3005

Goodies:

Jak 2:

Master:
image

PR:
image

Jak 3:

Master:

image

PR:

image

Beyond Good and Evil:

Master:

image

PR:

image

Tomb Raider:

Master:

image

PR:

image

### CODE REVIEW

**Review by lightningterror — APPROVED** [review]

**Comment by refractionpcsx2** [comment]
Updated the PR again, I was being totally stupid! (Don't code at 4am kids) and now I'm checking the CORRECT thing, the speed boost in Jak 2 is huge!

**Comment by refractionpcsx2** [comment]
Did some more changes to increase the accuracy of the page crossing, and gained another 7fps in Jak 2 at 3x Native, so now the GS Dump runs at 86fps instead of 79fps :)

**Comment by refractionpcsx2** [comment]
Okay I'm done messing with this now. Best I could do without breaking the SW renderer was 70fps in Jak 2 at 3x Native, let's hope that's enough.

**Comment by refractionpcsx2** [comment]
Okay guys, I couldn't let this lie and I hated everything about this PR.

Now it makes sense to me, doesn't feel at all hacky AND it fixed a bunch of stuff and massively improved performance! I just hope nobody finds any regressions, this is great news for Jak players 🥳

**Comment by DonelBueno** [comment]
First of all, thanks for the great work on the PR.

Just a note, Jak II is slower for me in Vulkan than in OpenGL, but it is unrelated to auto flush, it happens even with it off.
It also happens in master, so it has nothing to do with this PR, I just thought this could be a good opportunity to pont it out.

I have a GTX 1070. Does that also aplly to you? I think it's the only game where that happens.

**Comment by refractionpcsx2** [comment]
There is a couple of games, it happens. I guess somebody can look at it at some point, maybe if @stenzek gets bored.

**Pull request merged**
