### PR TITLE
Qt: Resize default headersize BIOS + Adding 4 new themes

### PR DESCRIPTION
**Pull request by RedDevilus**
### Description of Changes

image

Theme 1 (Untouched Lagoon - Light):
image

Theme 2 (Baby Pastel - Light):
image

Theme 3 (PCSX2 - Light):
Theme4PCSX2Blue

Theme 4 (Scarlet Devil - Dark):
image

### Rationale behind Changes

The BIOS width looked off visually for an enduser. Also adding color themes will add some personality and choice for all sorts of people along with 2 color themes for colorblind people.
### Suggested Testing Steps

Get the Qt build and test the themes. Not really concerned with how the BIOS selector looks.

### CODE REVIEW

**Comment by lightningterror** [comment]
Theme 2 (Baby Pastel - Light) is barely readable.

**Comment by refractionpcsx2** [comment]
Those first 2 themes are barely readable, the text gets lost in the background colours.

**Comment by refractionpcsx2** [comment]
as for the "colourblind" themes, I doubt white text on yellow is going to do a colourblind person any favours.

**Comment by RedDevilus** [comment]
Example of the yellow theme;
Tritanopia:
Yellow2Tritanopia
Deuteranopia:
Yellow1Deuteranopia

Example of the blue theme;
Blue Cone Monochromacy:
Blue2Blue Cone Monochromacy
Tritanopia
Blue1Tritanopia


I'll fix the other themes to be more legible

**Comment by coornio** [comment]
my-eyes

Please do tell me that we'd be able to modify the colors of the themes and/or add our own variants, some of these are plain terrible!

**Comment by RedDevilus** [comment]
I'm already revising them the initial PR is for placeholder colors.

**Comment by RedDevilus** [comment]
XP called back and they took the colour vomit back.

**Comment by seta-san** [comment]
Can’t we just allow the underlying os handle theme?

**Comment by RedDevilus** [comment]
Perhaps in the future we can copy OS dark/light + accents.

**Comment by seta-san** [comment]
I don’t know. Themes like this feels like a step backwards. It feels very windows 3.1

**Comment by RedDevilus** [comment]
How about not picking the themes you don't like?

**Comment by shikulja** [comment]
can't you use frameworks instead to make the theme match with mica\aero?
https://github.com/alexmercerind/flutter_acrylic
https://doc.qt.io/qt-5/qtquickcontrols2-material.html
https://github.com/githubuser0xFFFF/QtFluentDesign
https://github.com/TGSAN/CloudMoe-UI-Framework
https://github.com/marunemitsu/QTFluent

**Comment by BinhoKof99** [comment]
on the QT interface it is getting in the background when closing it

**Comment by BinhoKof99** [comment]
on the QT interface it is getting in the background when closing it

**Comment by RedDevilus** [comment]
> can use frameworks instead to make the theme match with mica\aero? [alexmercerind/flutter_acrylic](https://github.com/alexmercerind/flutter_acrylic) [doc.qt.io/qt-5/qtquickcontrols2-material.html](https://doc.qt.io/qt-5/qtquickcontrols2-material.html) [githubuser0xFFFF/QtFluentDesign](https://github.com/githubuser0xFFFF/QtFluentDesign) [TGSAN/CloudMoe-UI-Framework](https://github.com/TGSAN/CloudMoe-UI-Framework) [marunemitsu/QTFluent](https://github.com/marunemitsu/QTFluent)

Seems nice but atleast want to bring some themes in and revision what I already have. Qt is still not intended for public so I'll check again in the future.

**Comment by coornio** [comment]
While at it, maybe a good idea to consider a "debug" UI that has basically all the possible elements the emulator might use. Would be good for:

A) checking potential mistakes
B) creating themes and only having to check one place

**Comment by RedDevilus** [comment]
I'm not going to bother doing that at the moment and I still have to do the progress report. Just going to fix the current themes and do a future PR.

**Comment by BinhoKof99** [comment]
another question is that only users who have avx2 instructions that are using the qt interface will not have this interface for the rest that do not have this instruction???

**Comment by BinhoKof99** [comment]
another question is that only users who have avx2 instructions that are using the qt interface will not have this interface for the rest that do not have this instruction???

**Comment by RedDevilus** [comment]
I have no idea what you are talking about, this is not about SSE4 vs AVX2.

**Comment by RedDevilus** [comment]
It should be better now that the initial opening of this PR. I've edited the original post with newer pictures as well if you are interested.

**Review by Mrlinkwii — APPROVED** [review]

**Comment by Daisouji** [comment]
Scarlet's good for non-colorblind theme
Deutrernopia too, it's good to contrast White on Grey.

**Review by Satan86 — APPROVED** [review]

**Comment by RedDevilus** [comment]
Multiple approvals and I ~~ignored all the dissatisfactions~~ see this ready for merge.

**Review by F0bes — CHANGES_REQUESTED** [review]
'Colour blind' accessible themes need to be labelled as such. Right now they look like normal themes designed to just burn my eyes. And I'm a light mode user.

**Comment by RedDevilus** [comment]
image
I do label them as such.

**Review by gtgamer468 — APPROVED** [review]

**Comment by F0bes** [comment]
Oh, I thought plumber was for the colour blind...

**Comment by RedDevilus** [comment]
Plumber is no longer an option, nobody seems to like it.

**Comment by RedDevilus** [comment]
So I changed my mind, colorblind people already can use the good default light and dark themes and the ones I made might as well be made by a hobgoblin eating poop.

A future endeavor to make people choose or make their own themes and not color vomit. So the initial PR was 8 new themes but it's now 4 (8 in total if you count the 4 default themes).
rainbow-pride

**Review by F0bes — APPROVED** [review]

**Pull request merged**
