### PR TITLE
simplify the conditional statement,

### PR DESCRIPTION
**Pull request by ssakash**

### CODE REVIEW

**Comment by ssakash** [comment]
the earlier PR was not yet corrected. https://github.com/PCSX2/pcsx2/pull/227

hence, I made a new PR with the corrected conditional statement on the referenced commit.

**Comment by avih** [comment]
No. The discussion at #227 was not concluded, and there's no point in changing such stuff. If you want to discuss this, do that where the discussion has started already.

Also, it's not a simplification, it's a change, and like @sudonim1 said, this is delicate code.

You don't just send a PR without saying what it's good for, because it has to be good for something, right?

**Comment by ssakash** [comment]
there is no functional change, it does the same thing. only the conditional statement is simplified. what change are you talking about ?

**Comment by avih** [comment]
So just no. There are millions of non functional changes which we can do, but unless they serve a very good purpose, we don't do them because it's pointless. Please don't submit other PRs for similar non functional changes.

**Comment by ssakash** [comment]
yes, you're right. non-functional changes are pointless but, when a certain function does the same thing and the amount of work need for the function is reduced then, I think It's a little useful even if it's negligible. (I hope you could find the difference by looking at the changes)

if you think reducing a extra additional operator doesn't matter much then, you don't need to merge it.

**Comment by avih** [comment]
Just no.

**Comment by ssakash** [comment]
Okay, thanks for the well detailed reason on not merging this.

**Comment by avih** [comment]
No problem. Thank you too for the detailed reason for yes merging this.

**Pull request closed without merging**
