### PR TITLE
This should make replay loading work in Virtua fighter 4 after enabling fast cdvd speedhack

### PR DESCRIPTION
**Pull request by prafullpcsx2**

### CODE REVIEW

**Comment by ramapcsx2** [comment]
@prafullpcsx2 it will break Tales of the Abyss. 
You cannot easily make this hack compatible with all games. In fact, the current version is making it better for most of the otherwise incompatible games.
If you need a list of them, check out an old HDLoader compatibility list and sort by those that require a certain DMA mode.

**Comment by willkuer** [comment]
I guess adding an automatic/manual gamefix 'Force Fast CDVD Read' or something similar would be reasonable then. I think you are also not able to add speedhacks to the gamedbf, or?

**Comment by mirh** [comment]
Currently supported entries are linked [here](https://github.com/PCSX2/pcsx2/issues/1976#issuecomment-310780221). 
Kind of relates to #1894

**Comment by lightningterror** [comment]
Adding patches comments in the gamedb is a somewhat okay alternative.

I wouldn't want this to be merged if it breaks other games.

**Comment by woj1993** [comment]
What about having few methods of fast cdvd and list witch allows choosing metod or entry in gamedb that chose right metod for game?

**Comment by lightningterror** [comment]
Maybe something like this?

```
	if (EmuConfig.Speedhacks.fastCDVD) {
		if(gamecrc || (eCycle < Cdvd_FullSeek_Cycles))
			eCycle = 3000;
	}
```

**Comment by MrCK1** [comment]
That wouldn't work. The '''||''' operator means that both statements on each side have to be true. Even if the crc was specific, it doesn't make sense here.

**Comment by lightningterror** [comment]
Hmm I thought it was an or statement , well then using else statement would work no?

**Comment by mirh** [comment]
>  The || operator means that both statements on each side have to be true

I thought that was what && operator was about.

**Comment by refractionpcsx2** [comment]
|| is logical OR, so either statement has to be true for it to pass. && would be logical AND, meaning both statements would have to be true

**Comment by atomic83GitHub** [comment]
So, this PR solve Virtua fighter 4, Roland Garros 2003 but break Tales of the Abyss?

**Comment by lightningterror** [comment]
I think it breaks other games as well.

**Comment by prafullpcsx2** [comment]
@lightningterror : Virtua Fighter 4 fix comes into action only when fast cdvd speedhack is enabled, so how can it break other games in normal mode? Yes, the fix may make some games (like tales of the abyss) incompatible with fast cdvd speedhack but that's about it.

**Comment by FlatOutPS2** [comment]
You could add a second layer of fast CDVD support, the original functionality and a forced option.

**Comment by lightningterror** [comment]
@prafullpcsx2 are you gonna continue working on this or can I close it for now and reopen it when you decide to resume ?

**Comment by prafullpcsx2** [comment]
I am reopening this pull request. I tested Tales of the Abyss today and it seems to work fine with this even after enabling cdvd speedhack. @ramapcsx2 Can you please explain which part of the game breaks with these changes? 

@atomic83GitHub reported that this also reduces loading times of Oni and helps in beyond good and evil.

Regarding changes related to Roland Garros 2003 @refractionpcsx2 earlier stated that most probably these changes are correct. I haven't faced any regressions so far with both these changes. So may be it's time to commit them?

**Comment by ramapcsx2** [comment]
Abyss breaks semi-randomly in certain cut sequences and when roaming the overworld and fighting monsters. There is a cut scene with 2 people in front of one big tree early in the game, it breaks reliably on that with the hack enabled.
I forgot what other games broke, but there were a few. Check the HDLoader compatibility list for entries that require a different HDD mode. Those games are most likely to be affected.

**Comment by prafullpcsx2** [comment]
I played Abyss for about 20 minutes today but didn't encounter any problems. Will probably play more tomorrow to find out the problem areas if any.

**Comment by GovanifY** [comment]
I will close this PR for now, as master seems to have checks that make more sense to me and the PR seemed to have issues.

```
<<<<<<< HEAD
	if( cpuRegs.PERF.n.pccr.val & ((1 << (cpuRegs.CP0.n.Status.b.KSU + 2)) | (cpuRegs.CP0.n.Status.b.EXL << 1)))
=======
	if( cpuRegs.PERF.n.pccr.b.U0 )
>>>>>>> be07348b5 (Trying to fix Roland Garros 2003)
```

with ` 	if( cpuRegs.PERF.n.pccr.val & 0xf )` being used before the PR change for reference

**Pull request closed without merging**
