### PR TITLE
GameDB: Add Blending Accuracy to Spyro: Enter the Dragonfly

### PR DESCRIPTION
**Pull request by CRASHARKI**
### Description of Changes
Added Blending Accuracy 3 for Spyro: Enter the Dragonfly

### Rationale behind Changes
Added Blending Accuracy 3 to fix Gems not shining properly.

### Suggested Testing Steps
Just playing the game will show the visual improvement/correction on gems.

### CODE REVIEW

**Comment by Mrlinkwii** [comment]
i think you messed up it says that theirs 58k changes :/

**Comment by CRASHARKI** [comment]
I must have messed it up, there should be only 2 lines added.

**Comment by CRASHARKI** [comment]
Okay, now it should be alright.

**Comment by RedDevilus** [comment]
Do you have before and after pictures? Also OSD stats to how much it increases it as stuff like AMD GPUs can't handle blending well (for now till ROV)

**Comment by CRASHARKI** [comment]
Sure, here's some screenshots, you can see the reflection change on gems and golden numbers. Before applying Blending Accuracy 3:
Spyro - Enter the Dragonfly_SLES-51043_20230722164659

After applying Blending Accuracy 3 (closer to software renderer and real hardware):
Spyro - Enter the Dragonfly_SLES-51043_20230722164335

I didn't really understand the other thing about performance, but I've checked and there's already around 220 games using recommendedBlendingLevel 3 or 4 in the GameIndex.yaml, many of them to fix reflections too.

**Review by JordanTheToaster — APPROVED** [review]

**Pull request merged**
