### PR TITLE
OSX and 64-bit compatibility testing

### PR DESCRIPTION
**Pull request by aktau**
This is just a branch I'm using to try to get as far as possible in compiling things on 64-bit OSX. Up until now, not even one file gets compiled before it errors out. But, the number of errors is diminishing. Currently looking at things like:

**UPDATE 4**: Slowly but surely getting there. Current error listed below

Summary:

| Library | Builds | Works |
| --- | --- | --- |
| libUtilities | Yes | ? |
| libx86emitter | Yes | ? |
| pcsx2 core | In progress | ? |

```
[ 58%] Building CXX object pcsx2/CMakeFiles/pcsx2-dbg.dir/gui/AppMain.cpp.o
In file included from /Users/Kevin/github/aktau/pcsx2/pcsx2/gui/AppMain.cpp:17:
/Users/Kevin/github/aktau/pcsx2/pcsx2/gui/MainFrame.h:133:15: warning: 'MainEmuFrame::DispatchEvent' hides overloaded virtual function [-Woverloaded-virtual]
        virtual void DispatchEvent( const PluginEventType& plugin_evt );
                     ^
/Users/Kevin/github/aktau/pcsx2/pcsx2/gui/AppEventListeners.h:146:15: note: hidden overloaded virtual function 'IEventListener_AppStatus::DispatchEvent' declared here: type mismatch at 1st parameter ('c
onst AppEventInfo &' vs 'const PluginEventType &')
        virtual void DispatchEvent( const AppEventInfo& evtinfo );
                     ^
In file included from /Users/Kevin/github/aktau/pcsx2/pcsx2/gui/AppMain.cpp:17:
/Users/Kevin/github/aktau/pcsx2/pcsx2/gui/MainFrame.h:134:15: warning: 'MainEmuFrame::DispatchEvent' hides overloaded virtual function [-Woverloaded-virtual]
        virtual void DispatchEvent( const CoreThreadStatus& status );
                     ^
/Users/Kevin/github/aktau/pcsx2/pcsx2/gui/AppEventListeners.h:146:15: note: hidden overloaded virtual function 'IEventListener_AppStatus::DispatchEvent' declared here: type mismatch at 1st parameter ('c
onst AppEventInfo &' vs 'const CoreThreadStatus &')
        virtual void DispatchEvent( const AppEventInfo& evtinfo );
                     ^
/Users/Kevin/github/aktau/pcsx2/pcsx2/gui/AppMain.cpp:238:3: error: Unsupported Target Platform.
#       error Unsupported Target Platform.
        ^
/Users/Kevin/github/aktau/pcsx2/pcsx2/gui/AppMain.cpp:241:10: error: use of undeclared identifier 'vkey'
        switch (vkey)
                ^
/Users/Kevin/github/aktau/pcsx2/pcsx2/gui/AppMain.cpp:250:21: error: use of undeclared identifier 'vkey'
        m_kevt.m_keyCode = vkey? vkey : ev.key;
                           ^
/Users/Kevin/github/aktau/pcsx2/pcsx2/gui/AppMain.cpp:250:27: error: use of undeclared identifier 'vkey'
        m_kevt.m_keyCode = vkey? vkey : ev.key;
                                 ^
/Users/Kevin/github/aktau/pcsx2/pcsx2/gui/AppMain.cpp:895:12: warning: implicit conversion of NULL constant to 'uptr' (aka 'unsigned long') [-Wnull-conversion]
        pDsp[1] = NULL;
                ~ ^~~~
                  0
3 warnings and 4 errors generated.
```

### CODE REVIEW

**Comment by gregory38** [comment]
@aktau any status on that. Do you want to try a rebase to keep a small path set for either integration or to help future port?

**Comment by mgracer48** [comment]
this is so old
when will you guys add it

**Comment by willkuer** [comment]
Maybe you just read the comment directly above yours?

This commit needs a rebase and is not mergable. The original poster did not answer for a long time. Gregory did a lot to enable 64bit portability. He (and others) are working really hard to make this real in their free time. And then you come up with this comment?

**Comment by mgracer48** [comment]
im sorry i didn't know
i didn't mean to be rude :(

**Comment by gregory38** [comment]
As a matter of fact, most of this PR is merged + the additional work of another dev. However, a port to MAC + a port to 64 bits is just too big to be done in one shot.

**Comment by lightningterror** [comment]
I'll be closing this since most of the PR has already been added to master, plus it's been sitting here for years and it's not mergeable at the moment with conflicts.

@aktau you can ping us when you want to continue working on it so we can reopen the PR.

**Pull request closed without merging**
