### PR TITLE
USB-GunCon2: Support binding to controller

### LINKED ISSUE #7891: [Feature Request]: onscreen Targeting reticule when Guncon 2 mode is enabled for USB
### Description

A simple targeting reticule or crosshairs that appear on screen when Guncon mode is enabled in the USB settings, allowing you to see where you are aiming without having to unlock the mouse while playing games

### Reason

Due to the size of an average mouse icon, it can be hard to see where you are aiming at times in light gun games. By having a larger targeting reticule, it can be hard to see where you are aiming. A targeting reticule can also help players have a more seamless game experience as well, I believe.
Also, by having it be 2 separate reticule colours based on which usb port it is assigned to, this allows for possible 2 player guncon games to be playable.
This also might help for folks using a wiimote or or joycon gyro controls as a mouse pointer, which allows them the ability to use the controllers as a mock lightgun.

### Examples

I believe such a mode is activated when Guncon 1 and Justifier mode is enabled in duckstation
Certain versions of Melon DS (definitely in retroarch, not sure about standalone) have an onscreen reticule  to indicate where you are aiming/touching the second screen.
I believe Mame also has this for light gun games, but I can not recall exactly.

### LINKED ISSUE #9256: [Feature Request]: Add Absolute Values to gamepad for lightgun games
### Description

Hello

### Reason

I've got positionnal arcade gun , and lot of emulator work , but with PCSX2 i need left analog stick move to absolute value like MAME do for example.

### Examples

With this features Time Crisis 2 for example will work without flash and with a crosshair 
Hope someone could help me ;)
Thanks 

Edit : Finally I think i's requier a patch for each game and not a special controller setting

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Smaller version of #8437.

In addition to the default pointer-based configuration, this PR allows you to bind a controller to aiming instead, which apparently some lightguns use.

Also adds custom cursors/crosshairs, which will hide the system cursor when active.

image
image

### Rationale behind Changes

Closes #7891.
Closes #9256.

### Suggested Testing Steps

To test this with a controller, simply bind all four relative directions to e.g. an analog stick, and pick a crosshair image, so you can see where you're aiming.

Make sure mouse based aiming still works (clear all four relative axes by right clicking the bindings).

### CODE REVIEW

**Comment by stenzek** [comment]
Originally I had this setting the pointer to the axis values relative to display area, but window area probably makes more sense, I'm guessing people with these lightguns probably calibrate them to the display edges?

So I've changed it to that - as long as the axis values reported by the lightgun are relative to the PCSX2 window (or monitor if fullscreen), then it should work fine.

**Comment by Bandicoot37** [comment]
So wonderful ,thanks so much
Hope someone will make a patch for each game to remove flash 
But this is so great now many many thanks

**Comment by Bandicoot37** [comment]
Strange thing , my X axis roll from left to right side ( to be clear the middle of screen isn't good ) no problem with Y axe

**Comment by phasermaniac83** [comment]
Hi! I've just tested and seems to work, but only if I start windowed. If I start game fullscreened, the cursor stays at top left corner. Maybe I'm missing something, thanks

**Comment by stenzek** [comment]
I'll check it tomorrow.

**Comment by stenzek** [comment]
@phasermaniac83 please check #9752 and confirm it fixes the issue. I can only test with a controller since I don't own any lightguns.

**Comment by draccfacc** [comment]
What can be improved: custom crosshair needs support of .cur files, not only .jpeg and  .png. Cause there are no pictures of crosshairs with transparent backgroundand you can't see through it.. .cur files work well though. Basically the standard crosshair in PCSX 2 is a mouse cursor of Windows so if I understand it right all is need to be done is to change standart mouse cursor to a .e.g. crosshair cursor .cur file.

**Comment by stenzek** [comment]
Pull requests welcome, but I'm not adding that. You can easily convert the file format yourself, it's not the emu's responsibility to do **everything**.

**Comment by OctopusButtons** [comment]
THANK YOU for the work on this custom cursor feature, I used it in Time Crisis 2 and it was wonderful.  (With a crosshair file I colored/modified myself and it was wonderful.)

On Mac, https://appahead.studio/apps/cursor-pro/ is excellent for getting a glowing targeting ring (customizable) that is Namco Arcade Game appropriate.  But on **Windows** it seems that all the custom cursors require deep free-reign system access and are all in the wildlands of suspicious malware apps, even on the Microsoft Store Microsoft disclaims all responsibility and says the OS-level access can’t be vetted or controlled.

THANK YOU.

**Comment by OctopusButtons** [comment]
> What can be improved: custom crosshair needs support of .cur files, not only .jpeg and .png. Cause there are no pictures of crosshairs with transparent backgroundand you can't see through it.. .

The crosshair files I found from searching online all had alpha/transparent backgrounds and transparent “white space” (aka shows up as grey-white checkerboard pattern in many image viewing apps).  Mr. Do’s MAME pack, and another set.  I used free **paint.net** app to change colors too, and I deleted un-needed shapes in the crosshair by painting over them with transparent/alpha shapes.  Selection tool > select an area of alpha (grey/white checkerboard) > copy > paste > adjust the pasted shape to block out unwanted parts of crosshair shape.

**Pull request merged**
