### PR TITLE
Extend LTO support and remove warnings

### PR DESCRIPTION
**Pull request by np511**
Adds option to change number of cores (so default of four can be changed) to CMake and build.sh and removes LTO warnings.

### CODE REVIEW

**Comment by gregory38** [comment]
in the build script there already a variable that contains the number of core. I don't see the point to add another option. And potentially Cmake got an handy variable too. Did you check it ?

**Comment by np511** [comment]
> in the build script there already a variable that contains the number of

> core. I don't see the point to add another option. And potentially Cmake

> got an handy variable too. Did you check it ?

I just took a look in the build script - let me clarify: the number doesn't need to be the number of cores on the system - usually, setting them equal makes compilation faster, but you can set the number lower or higher if you want.

**Comment by gregory38** [comment]
Hum. Let's be honest, the best setting is likely the number of core. IMHO, it doesn't worth to add another option. Nobody will check LTO scaling on multiple core system ;)

**Comment by np511** [comment]
> Hum. Let's be honest, the best setting is likely the number of core. IMHO,
> it doesn't worth to add another option. Nobody will check LTO scaling on
> multiple core system ;)
*Sighs* Alright, I'll change it later.

**Comment by np511** [comment]
Oops. I've been updating PCSX2 every day (sometimes more). When I pushed this commit, I changed the origin remote url in the config file - and then "git pull" started updating from my fork.

I'll fix this later, I now have two separate folders cloned - one of here, one of the fork.

How do I make my changes part of the first commit (instead of creating a second one?)

**Comment by gregory38** [comment]
`git commit --amend` and then force push. Otherwise, I will use the github option to do it.

**Comment by np511** [comment]
Fixed this

**Pull request merged**
