### PR TITLE
Re:Re:Fix & Add Japanese Game Titles.

### PR DESCRIPTION
**Pull request by nassau-tk**
### Description of Changes

Fixed a large number of Japanese game titles.
And, Re-fix [ name-en: ].
*Trial & Demo will fix later.
### Rationale behind Changes

This is a difficult task for non-Japanese people, so I did it myself.
*I'm JP.
### Suggested Testing Steps

Put on the "resources" folder and check booting PCSX2.
If the .yaml file has problem then PCSX2 will not boot(Crash).

This is [Third attempt] lol

### CODE REVIEW

**Comment by TellowKrinkle** [comment]
You may want to run ajv locally to fix the issues instead of waiting for the CI to run after each one
```
npm install ajv-cli
ajv validate -s ./pcsx2/Docs/gamedb-schema.json --spec=draft2020 -d ./bin/resources/GameIndex.yaml
```

**Comment by TellowKrinkle** [comment]
Also, you can just add more commits instead of opening a new PR for each one
We can squish them all into one commit when we merge

**Comment by nassau-tk** [comment]
Oh!
Thank you for your fixing!!
I'm glad for your kindness.
And, I'm so sorry for my poor knowlddge.

I will more learn about github!

Thank you.

**Comment by TellowKrinkle** [comment]
I made a few more changes:
- It appears you did a find and replace from `!` to `！` (fullwidth), and it affected both English and Japanese titles.  I've undone the change for all non-Japanese titles
  - I did not undo this for "Strawberry Panic！ [初回限定版]" and "Strawberry Panic！ [通常版]", since they are Japanese games, even though they use English for the entire title.  Should I?
- It appears you accidentally undid the last few commits that changed the gamedb.  I've re-applied those.

Let me know if those make sense to you and if so, I'll squish them all into the main commit so the change list is a bit smaller.

**Comment by nassau-tk** [comment]
I assume that name: and name-sort: in Japanese games are all full-width "!".

I think it's okay to use half-width characters for name-en: in Japanese games as well.

**Comment by TellowKrinkle** [comment]
> I assume that name: and name-sort: in Japanese games are all full-width "!".

Correct.

**Comment by TellowKrinkle** [comment]
I've squished all the commits into one.
If that looks good to you, let me know and I'll merge it.

**Comment by nassau-tk** [comment]
Yes, It seems very nice.

The most important purpose this time is to display Japanese and sort based on Japanese as much as possible.

It's was done by your help!

In the future, I would like to modify the Demo/Trial version and make minor corrections.

**Comment by TellowKrinkle** [comment]
> In the future, I would like to modify the Demo/Trial version and make minor corrections.

Sounds good.  Make a new PR with that when you're ready.

**Comment by pgert** [comment]
@nassau-tk:
You might want to check this out, if you haven't done so already:
https://forums.pcsx2.net/Thread-GameDB-Gamefixes-update-discussion?pid=566963#pid566963

**Comment by nassau-tk** [comment]
@pgert 

Shouldn't I have fixed it personally?

**Comment by pgert** [comment]
> @pgert
> 
> Shouldn't I have fixed it personally?

I ment if there is something there that is new to you.

**Comment by nassau-tk** [comment]
Thank you for your inform!!

**Pull request merged**
