### PR TITLE
Qt: Resizes + better tooltips + Savestate warning

### PR DESCRIPTION
**Pull request by RedDevilus**
### Description of Changes

Bigger tooltip window
Controllers button shows up correctly at different DPI percentages 
Rename some options.

image

image

image

### Rationale behind Changes

More sense and more obvious settings or options.
### Suggested Testing Steps

Check the GUI in Qt

### CODE REVIEW

**Comment by Florin9doi** [comment]
image

**Comment by refractionpcsx2** [comment]
> image

Can't really do that, unless we diligently kept a list of last versions a specific savestate version worked on, which we don't currently.

**Comment by refractionpcsx2** [comment]
Yeah I agree that's probably the best setup for that dialog.

**Comment by RedDevilus** [comment]
Tracking savestate version suck but hooking up:
image

The link to the site and close are all feasible. but it's just one of many revisions to come either way.

**Comment by RedDevilus** [comment]
Is the PR fine for now or does anyone else have doubt/questions about the suggested changes? I plan to do more smaller PRs either way.

**Comment by Florin9doi** [comment]
> Can't really do that, unless we diligently kept a list of last versions a specific savestate version worked on, which we don't currently, but that sounds like a maintenance annoyance, and people _will_ forget.

This is offtopic, but isn't necessary to determine the latest supported version for a specific savestate if we'd save the emulator version inside savestates together with [SaveVersion](https://github.com/PCSX2/pcsx2/blob/0e73bf1e6d0a7f33d5eed135b4b30787753d7693/pcsx2/SaveState.cpp#L947-L962) and we would suggest same version.

**Comment by stenzek** [comment]
Personally I'd rather just do state migration, like I have in duckstation. The USB PR pulls in my state wrapper class which supports this, we can move the other components over it too eventually.

**Comment by refractionpcsx2** [comment]
> > Can't really do that, unless we diligently kept a list of last versions a specific savestate version worked on, which we don't currently, but that sounds like a maintenance annoyance, and people _will_ forget.
> 
> This is offtopic, but isn't necessary to determine the latest supported version for a specific savestate if we'd save the emulator version inside savestates together with [SaveVersion](https://github.com/PCSX2/pcsx2/blob/0e73bf1e6d0a7f33d5eed135b4b30787753d7693/pcsx2/SaveState.cpp#L947-L962) and we would suggest same version.

I guess, I more figured the user would want the most up to date version before it exploded.  Either way, Sten is right, it would be better to replace our savestate system with his so interversion compatibility isn't quite so deadly, although I worry about new stuff not being in the correct state if the state has changed, but you have more luck than you currently do.

**Pull request merged**
