### PR TITLE
Fpu double

### PR DESCRIPTION
**Pull request by gregory38**
I completely redo the EE FPU in the interpreter.

The tests show must better results. Error is now an ULP due to bad rounding. (double => float uses a trunc)

Flag management must be reviewed.

### CODE REVIEW

**Comment by gregory38** [comment]
Flags management is better. But the cache coherency of double suck, so I will remove it, it would avoid to break save state for nothing.

On accuracy, the full mode have extra handling for add/sub to avoid rounding issue. It could also be implemented on the interpreter. However code is quite close to fully do the addition/sub with int.

**Comment by arcum42** [comment]
I've gone ahead and rebased this and resolved the conflicts.

**Comment by MrCK1** [comment]
Guess I'll test it later probably not much help anyways :P

**Comment by arcum42** [comment]
No idea how useful a pr it is, but now at least it's up to date and can be tested and worked on properly.

Fortunately, the conflicts didn't really require me to know that much about the pr to resolve.

**Comment by atomic83GitHub** [comment]
Please note that this PR makes some unplaybles games on interpreter playable. Stuntman even goes further than normal (still broken tho).

**Comment by lightningterror** [comment]
Closing as it's not currently being worked on, if anyone wishes to continue they can reopen the pr.

**Pull request closed without merging**
