### PR TITLE
GS/HW: Favour newer draw on source overlap + improve target overwrite

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Improve target selection on tex in rt and improve detection of targets to be deleted.

### Rationale behind Changes
Just the way some games do things confuses the TC, this improves it

### Suggested Testing Steps
Test games below, make sure everything is okay. Any Tex in RT games are probably a good shout too (including Valkyrie Profile 2)

### Guitar Hero III - Legends of Rock:
Master:
image
PR:
image

Master:
image
PR:
image

### Project Snowblind:
Master:
image
PR:
image

Master:
image
PR:
image

### Tomb Raider Legend:
Master:
image
PR:
image

Master:
image
PR:
image

### Urban Chaos:
Master:
image
PR:
image

### CODE REVIEW

**Comment by pedrib** [comment]
Had heavy screen corruption while in / near the water and turning the camera in Tomb Raider: Anniversary:
Lara Croft Tomb Raider - Anniversary_SLUS-21555_20240526222503

Tested this build, and it seems to have disappeared!

However since the water is now clear I have discovered some minor texture flickering when moving the camera outside of the water. I don't think it's unrelated to this fix, since there are a few minor surfaces that also have texture flickering, and they are nowhere near water.

**Comment by Kazeira** [comment]
Tomb Raider Legend (PAL version) isn't fixed on my side
image

**Comment by Mrlinkwii** [comment]
@Kazeira  can i have a gs dump please :)

**Comment by Kazeira** [comment]
Here for go [Tomb Raider - Legend_SLES-53908_GSdump.zip](https://github.com/PCSX2/pcsx2/files/15483269/Tomb.Raider.-.Legend_SLES-53908_GSdump.zip)

**Comment by refractionpcsx2** [comment]
It's broken for me, but not that badly

image

the bug you're showing looks like either you have manual fixes enabled or you're not using this PR.

**Comment by Kazeira** [comment]
I'm using this PR and I made sure to disable manual fixes before testing it.
I even made multiple tests to be sure, the more the game is upscaled the worse it looks, at native resolution the texture is so blurry that it's less noticeable

**Comment by refractionpcsx2** [comment]
can you try your own GS Dump (do start file then select it) and see if you get the same results as me? I am resolving the current problem I have, but I want to check this anyways.

**Comment by refractionpcsx2** [comment]
Okay well I just pushed a change, and I checked upscaling and it's fine, I also fixed the problem I had

Have a picture at 8x

image

**Comment by Kazeira** [comment]
Tested it and it works perfectly.
With this PR and #11302, Crystal Dynamics' Tomb Raider games will finally look good (Align to Native + Merge sprites for imperfect but better results)
All that's missing now is an option to use mipmaps only on garbage textures and these games and many others will look almost perfect when upscaling.

**Comment by refractionpcsx2** [comment]
Just made some other tweaks, which reduces some of the uploads and other stats on the above mentioned games, and a couple of others.


catwoman_ghost ['Draw Calls: -37 [389=>352]', 'Render Passes: -21 [126=>105]', 'Uploads: -23 [43=>20]'] 
DT_Carnage_SLUS-21793_20230908174547 ['Draw Calls: -38 [974=>936]', 'Render Passes: -38 [386=>348]', 'Uploads: -9 [179=>170]']
DT_Carnage_SLUS-21793_20240401130158 ['Draw Calls: -56 [782=>726]', 'Render Passes: -57 [429=>372]', 'Uploads: -14 [183=>169]']
DT_Carnage_SLUS-21793_20240401130227 ['Draw Calls: -44 [1074=>1030]', 'Render Passes: -46 [405=>359]', 'Uploads: -11 [278=>267]']
dt_racer_overlay ['Draw Calls: -28 [1658=>1630]', 'Render Passes: -29 [598=>569]', 'Uploads: -2 [258=>256]']
gt4slow ['Draw Calls: -2 [1274=>1272]']
GT4_-_channel_shuffle_2019 ['Draw Calls: -2 [1189=>1187]']
gt4_brigthness_contrast ['Draw Calls: -2 [2172=>2170]']
gt4_shuffle ['Draw Calls: -2 [1081=>1079]']
Prince_of_Persia_-_Warrior_Within_SLES-52822_20221114035744 ['Draw Calls: -127 [333=>206]', 'Render Passes: -127 [186=>59]', 'Uploads: -32 [48=>16]']
Project_-_Snowblind_SLUS-21037_20230804184427 ['Draw Calls: -49 [386=>337]', 'Render Passes: -40 [165=>125]', 'Copies: -2 [15=>13]', 'Uploads: -18 [117=>99]']
Project_-_Snowblind_SLUS-21037_20240316203245 ['Draw Calls: -66 [326=>260]', 'Render Passes: -49 [165=>116]', 'Copies: -2 [9=>7]', 'Uploads: -26 [110=>84]']
Tomb Raider - Legend _PAL-M8__SLES-53908_20220610120301 ['Draw Calls: -121 [748=>627]', 'Render Passes: -124 [149=>25]', 'Uploads: -31 [89=>58]']
Tomb Raider - Legend_SLES-53908_20230227204314 ['Draw Calls: -121 [750=>629]', 'Render Passes: -124 [149=>25]', 'Uploads: -31 [89=>58]']
Tomb Raider - Legend_SLES-53908_20230726233524 ['Draw Calls: -138 [199=>61]', 'Render Passes: -110 [138=>28]', 'Uploads: -57 [81=>24]']
Tomb Raider - Legend_SLES-53908_20240405040020 ['Draw Calls: -101 [484=>383]', 'Render Passes: -76 [114=>38]', 'Uploads: -47 [133=>86]']
Tomb Raider - Legend_SLES-53908_20240529130038 ['Draw Calls: -228 [531=>303]', 'Render Passes: -217 [303=>86]', 'Uploads: -21 [62=>41]']
Tomb_Raider_-_Legend_SLES-53908_20240427151445 ['Draw Calls: -4 [277=>273]', 'Render Passes: -2 [104=>102]', 'Copies: -1 [8=>7]', 'Uploads: -4 [44=>40]']

**Review by Mrlinkwii — APPROVED** [review]

**Comment by bigol83** [comment]
Quicky checked Prince of Persia Warrior Within in the starting are and the speed went from 80 fps to 110fps, running at 3x native with Vulkan.

**Comment by refractionpcsx2** [comment]
nice :D makes sense! I'm continuing to mess to improve handling of channel shuffles, I've reduced a texture size from Metal Gear Solid 3 from bonkers to sensible, not sure if it'll fix anything or improve the speed, but we'll see...

If it makes it, this may all go very wrong and I end up scrapping it.

**Comment by refractionpcsx2** [comment]
Okay got some wins out of that.

Eragon:
Master:
image
PR:
image

on top of that some stat reductions, this is the final figures for this PR

Catwoman ['Draw Calls: -37 [389=>352]', 'Render Passes: -21 [126=>105]', 'Uploads: -23 [43=>20]']

Call of Duty 2 ['Draw Calls: +1 [81=>82]', 'Uploads: +1 [33=>34]']

Death_by_Degrees ['Render Passes: +1 [229=>230]']

DT_Carnage_SLUS-21793_20240401130158 ['Draw Calls: -56 [782=>726]', 'Render Passes: -57 [429=>372]', 'Uploads: -14 [183=>169]']

DT Racer ['Draw Calls: -28 [1658=>1630]', 'Render Passes: -29 [598=>569]', 'Uploads: -2 [258=>256]']

Eragon ['Draw Calls: -1 [128=>127]']

Gran Turismo 4 ['Draw Calls: -2 [1274=>1272]']

Hitman - Blood Money_SLES-53028_20230819082820 ['Draw Calls: +3 [492=>495]', 'Render Passes: +2 [396=>398]']
['Draw Calls: -14 [485=>471]', 'Render Passes: -15 [379=>364]', 'Uploads: -4 [53=>49]']

Hitman 2 ['Draw Calls: +98 [410=>508]', 'Render Passes: +100 [313=>413]', 'Uploads: +46 [10=>56]']  (idk what's going on here lol, Hitman games are very broken anyways)

Metal Gear Solid 3 - Snake Eater ['Draw Calls: +1 [242=>243]', 'Barriers: -1 [15=>14]']
Metal Gear Solid 3 - Snake Eater ['Draw Calls: +1 [56=>57]', 'Render Passes: +1 [27=>28]', 'Barriers: -2 [3=>1]', 'Uploads: +1 [5=>6]']

Metal Gear Solid 3 - Subsistence ['Render Passes: -1 [12=>11]', 'Copies: +1 [3=>4]']
Metal_Gear_Solid_3 - Subsistence ['Render Passes: -2 [22=>20]', 'Copies: +1 [6=>7]']
Metal_Gear_Solid_3 - Subsistence ['Draw Calls: +1 [418=>419]', 'Render Passes: -1 [19=>18]']

Prince of Persia - Warrior Within ['Draw Calls: -127 [333=>206]', 'Render Passes: -127 [186=>59]', 'Uploads: -32 [48=>16]']

Project - Snowblind  ['Draw Calls: -49 [386=>337]', 'Render Passes: -40 [165=>125]', 'Copies: -2 [15=>13]', 'Uploads: -18 [117=>99]']

Stolen ['Draw Calls: -64 [2184=>2120]', 'Render Passes: -64 [1951=>1887]', 'Barriers: -62 [165=>103]']

SWAT - Global Strike Team ['Draw Calls: -69 [600=>531]', 'Render Passes: -68 [326=>258]', 'Copies: -35 [39=>4]']

Tomb Raider - Legend  ['Draw Calls: -121 [748=>627]', 'Render Passes: -124 [149=>25]', 'Uploads: -31 [89=>58]']

Urban Chaos ['Render Passes: +1 [39=>40]']

**Review by JordanTheToaster — APPROVED** [review]

**Review by kamfretoz — APPROVED** [review]

**Comment by pedrib** [comment]
Tested the latest changes on Tomb Raider: Anniversary and all is good, no screen artifacts where they used to be. Thanks!

**Comment by refractionpcsx2** [comment]
great! Thanks for testing! :)

**Comment by pedrib** [comment]
> great! Thanks for testing! :)

My pleasure, you guys are the real kings for developing this emulator!

**Review by Mrlinkwii — APPROVED** [review]

**Comment by nitram3** [comment]
> Tested it and it works perfectly. With this PR and #11302, Crystal Dynamics' Tomb Raider games will finally look good (Align to Native + Merge sprites for imperfect but better results) All that's missing now is an option to use mipmaps only on garbage textures and these games and many others will look almost perfect when upscaling.

Is there's some manual fixes that should be enabled, because I still have the bloom issues after both PRs if upscaling?
And if I enable align to Native and Merge sprites, Lara's model and post processing become broken.

**Comment by refractionpcsx2** [comment]
it will tell you on the screen what you need to re-enable if you're doing manual fixes. I'm hoping we will add align to native in a future update.

**Comment by nitram3** [comment]
Thank you, but I've looked in the gameindex.yaml, so all good. I didn't know about this before; is it possible that a few years ago automatic fixes weren't a thing?
Turns out that my problem was caused by the 50/60 fps patch, which apparently brakes the game graphics.

**Comment by RedDevilus** [comment]
> Thank you, but I've looked in the gameindex.yaml, so all good. I didn't know about this before; is it possible that a few years ago automatic fixes weren't a thing? Turns out that my problem was caused by the 50/60 fps patch, which apparently brakes the game graphics.

1.6: game specific are compat patches (pnach) ee and vu clamping and rounding, game fixes (and before versions)
1.7: on top of 1.6 added mtvu (default with 3+ cores), softwarethreads 3 (default with 3+ cores) instantvu, dynamic patches, renderer fixes, upscaling fixes, with pcsx2 patches also being more verbose and easy to handle and preincluded for 60 FPS patches and other types.

So there were automatic fixes but they expanded in scope and quality.

**Pull request merged**
