### PR TITLE
GS: Use 16bit RGBA unorm for HDR

### PR DESCRIPTION
**Pull request by tellowkrinkle**
### Description of Changes
It looks like #7131 wasn't enough to make half floats viable
So we're trying with 16-bit unorm instead
Should allow up to 256 overlaps all laying down 255s, or some slightly larger number of smaller values

Alternative to #7132
May break games that use HDR without accumulation blends, we haven't found any yet, but there's always going to be that one game...

### Rationale behind Changes
Improved performance in HDR

### Suggested Testing Steps
Test HDR games
Test OGL and DX (I only tested Metal and Vk)

### CODE REVIEW

**Comment by lightningterror** [comment]
[BigMuthaTruckers.zip](https://github.com/PCSX2/pcsx2/files/9741041/BigMuthaTruckers.zip)
[Castlevania shadow.zip](https://github.com/PCSX2/pcsx2/files/9741043/Castlevania.shadow.zip)
[Lord of the rings Third Age.zip](https://github.com/PCSX2/pcsx2/files/9741044/Lord.of.the.rings.Third.Age.zip)

Here are some dumps where hdr is enabled without accumulation blend.
For Castlevania and Big Mutha you will need to force disable barriers.

**Comment by refractionpcsx2** [comment]
Here's dumps which are usually affected by HDR, all seem to work absolutely fine on this PR! (booo to floats! down with floats!)

[narnia.zip](https://github.com/PCSX2/pcsx2/files/9741563/narnia.zip)
[sly2.zip](https://github.com/PCSX2/pcsx2/files/9741565/sly2.zip)
[evolutionsnowboarding.zip](https://github.com/PCSX2/pcsx2/files/9741567/evolutionsnowboarding.zip)
[Full spectrum warrior.zip](https://github.com/PCSX2/pcsx2/files/9741568/Full.spectrum.warrior.zip)

**Comment by refractionpcsx2** [comment]
I went through ALL my dumps, no regressions, and all the speed improvements of #7132 
Good job :)

**Review by Mrlinkwii — APPROVED** [review]

**Comment by tellowkrinkle** [comment]
Big Mutha Truckers uses 1202 (Cd * As) which should run fine as long as alpha is ≤1.0.  The trace uses it for darkening, but that doesn't mean the game doesn't use it for brightening elsewhere.
Castlevania Shadow uses 0111 (Normal alpha blend equation but with Ad), which will be equally broken on both float and unorm
LotR uses 2101 (Cd - As * Cd) which should run fine as long as alpha is ≤1.0.  The trace uses 1.0 and 0.25 alpha with an RGB24 texture and AEM, so we should be fine here.

**Comment by GN876** [comment]
on an RTX 3080, I got 2x the framerate in Sly 2 at 6x native. Framerates in Echo Night: Beyond are also better (around 30% I think) compared to latest master. In both games I didn't see even a single visual issue.

**Comment by lightningterror** [comment]
Here are some benchmarks with my 750ti on 3x native:

Master:
```
Full Spectrum Warrior
OpenGL 93 fps
Vulkan 98 fps
Direct3D11 95 fps
Direct3D12 95 fps

Sly 2
OpenGL 41 fps
Vulkan 46 fps
Direct3D11 39 fps
Direct3D12 40 fps
```

PR:
```
Full Spectrum Warrior
OpenGL 134 fps
Vulkan 141 fps
Direct3D11 134 fps
Direct3D12 125 fps

Sly 2
OpenGL 74 fps
Vulkan 92 fps
Direct3D11 76 fps
Direct3D12 78 fps
```

**Pull request merged**
