### PR TITLE
Push valid target

### LINKED ISSUE #914: Ratchet & Clank - Blurred Background only in top left corner
Version - 1.3.1-1282
Specs - i5 2500k @ 4.0 GHz, 11 GB RAM, GTX 660 3GB
In hardware mode, when the game is paused the entire background is grey except for the top left corner which is blurred correctly. Software mode handles this correctly, displaying the current screen blurred behind the pause screen.

Hardware - capture

Software - capture

Log - https://gist.github.com/deadair3210/3a6e1d8bbc8611583726

### LINKED ISSUE #5431: [BUG]: Rally Fusion - Race of Champions (USA) car texture bug
### Describe the Bug

Rally Fusion - Race of Champions (USA) SLUS-20361 (1.02) car texture bug (game run is slow)

screenshot 1
screenshot 2

### Reproduction Steps

in game play only

### Expected Behavior

_No response_

### PCSX2 Revision

1.7.2271

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i7

### GPU

gtx 950m

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by JanLeonard**
### Description of Changes

Adding selectionable hack that pushback coordinates from valid target instead of given rectangle in TextureCache,
should be a safe hack, didn't break anything i've tested as of yet.

### Rationale behind Changes

Fix R&C Games  and Rally fusion and maybe others glitchy background in HW renders,
mostly safe as of my testings.

image

image

fixes #914 
fixes #5431

i've tested randomly some gs dumps on issue tab labelling TextureCache

### Suggested Testing Steps

To test other games that have similar or Texture HW issue in general:
Pick Qt build from this PR and enable the option in Manual Fixes, the fix applies on the fly, no need to restart.

image

### CODE REVIEW

**Comment by EvilPlayer1** [comment]
Is it normal that in menus background is rendered in native resolution?
Screenshot 2022-06-07 21-01-45

**Comment by F0bes** [comment]
Yes, if it's a texture it won't be upscaled without texture replacement.

**Comment by EvilPlayer1** [comment]
> Yes, if it's a texture it won't be upscaled without texture replacement.

Thank you for the information

**Comment by iMineLink** [comment]
Mhm I guess it is native resolution because it will be uploaded from the local GS memory if the whole target is marked dirty.

**Comment by jascio** [comment]
Yeah it’s native resolution as it is now in master, 
It isn’t noticeable because it’s only a small square

**Comment by JanLeonard** [comment]
Yes, even now in master if you look closly the little square is taken down to native resolution.
Quick note:
R&C UYA and deadlocked need disabledepth emulation hack instead of partial invalidation which is present now in gamedb. (Aquatos/ catacomb issue)

**Comment by refractionpcsx2** [comment]
Disable depth emulation? What effect does that have on the rest of the game? I dislike disabling depth emulation, where disabling partial invalidation just makes the TC have to work a bit harder, I can live with that.

**Comment by JimScript** [comment]
Well I figure that this problem might be different, but I might as well say the lego racers 2 corner problem is not fixed by this hack:
gs_20220607203222_LEGO Racers 2_SLUS-20042
As for disable depth emulation, it actually improves aquatos by getting rid of an emboss effect wherein disabling partial invalidation does not.
Partial:
gs_20220607205646_Ratchet _ Clank - Up Your Arsenal_SCUS-97353
Depth:
gs_20220607205658_Ratchet _ Clank - Up Your Arsenal_SCUS-97353

**Comment by JanLeonard** [comment]
> Disable depth emulation? What effect does that have on the rest of the game? I dislike disabling depth emulation, where disabling partial invalidation just makes the TC have to work a bit harder, I can live with that.

On the rest of the game itself it seems that has no negative effects and even “fixes” that bloom from what @JimScript describe, however if disablePartialInvalidation is used without disabledepth, even throw exception on depth pointer when used a debug/dev build. So in fact it seem’s to be a “safer” hack in this/those game/s but I’ve not tested entire game with this.
Can you explain why dislike disabling depth,
What could it cause which could be tested?
Those games require a full read instead of r.intersect in theory bc useful part is wrong detected

**Comment by iMineLink** [comment]
@JimScript try #5534 out of curiosity, see if it improves the dirty area detection.

**Comment by JimScript** [comment]
Well @iMineLink, I'm not sure what you mean by "dirty area detection", but I tried both games with #5534 with no apparent difference.

**Comment by JanLeonard** [comment]
He meant to Test this bug/dump with his #5534 PR

> Well I figure that this problem might be different, but I might as well say the lego racers 2 corner problem is not fixed by this hack: 
gs_20220607203222_LEGO Racers 2_SLUS-20042

**Comment by JimScript** [comment]
Oh, well that PR didn't fix that issue, but setting the skipdraw range to 0-70 does(at least in gameplay, menus are still glitchy):
gs_20220608015955_LEGO Racers 2_SLUS-20042

**Comment by JanLeonard** [comment]
Users have reported broken texture/ corrupted colours so there's no point leaving it here.
Closing it

**Pull request closed without merging**
