### PR TITLE
GSdx-d3d: Purge Direct3D9 Render entirely

### LINKED ISSUE #1171: GSDX: Drop (or) keep D3D9 renderer ?
It was recently stated that the last stable version (1.4) will be the final version which will have support for windows XP, so having D3D9 renderer isn't as necessary as before since we don't have to worry about people with windows XP.

**Advantages on removing D3D9 renderer:**
- Initial step on removing DX SDK dependency.
- prevents inexperienced users from using D3D9 since it misses lots of recent changes like Snowblind fix and other stuffs.
- D3D9 renderer also has lots of other issues which aren't present on D3D11/OpenGL. less better choices makes it more user friendly for the users.
- No need to have a logo for D3D9 and also saves space at combo box.

**Disadvantages on removing D3D9 renderer:**
- People with graphics cards lower than Fermi / AMD equivalent can't use any renderers on GSDX.

### PR DESCRIPTION
**Pull request by lightningterror**
Nothing else to say.

Close #1171

### CODE REVIEW

**Comment by tadanokojin** [comment]
Press F to pay respect.

**Comment by mirh** [comment]
Did 1.6 come earlier?

**Comment by arcum42** [comment]
Unless there are going to be other DirectX renderers in the future, all the common DirectX files could probably be merged in with the DX11 ones.

**Comment by lightningterror** [comment]
Ye I know. Well it's a job that can wait a bit :)

**Comment by turtleli** [comment]
I can still see
https://github.com/PCSX2/pcsx2/blob/fce3918562fac3730619a5d8c89809fdf4ebedb1/plugins/GSdx/GSdx.cpp#L219
and
https://github.com/PCSX2/pcsx2/blob/fce3918562fac3730619a5d8c89809fdf4ebedb1/plugins/GSdx/GSdx.cpp#L310
in the master branch...

**Pull request merged**
