### PR TITLE
Lilypad default xinput controls

### PR DESCRIPTION
**Pull request by KrossX**
Default configuration for xinput controller 0 and 1, for port 0 and 1 respectively.

### CODE REVIEW

**Comment by ramapcsx2** [comment]
Cheers!
Will merge and test once CI tests are through and I'm back from uni :)

**Comment by KrossX** [comment]
That was quick. O.O

**Comment by bositman** [comment]
Does default config work for controllers? Last time I checked even if I had binded everything on my logitech cordless 2, switched to my second (same) controller, nothing would work and I had to remap everything

**Comment by KrossX** [comment]
Only for the xinput backend though.

**Comment by ramapcsx2** [comment]
Tested on 2 machines and working nicely with 360 pads :)

**Comment by bositman** [comment]
Cool

**Pull request merged**
