### PR TITLE
Debugger: Cleanup and fixes

### PR DESCRIPTION
**Pull request by F0bes**
### Description of Changes
- Page Up/Down hotkey for the disassembly view
- Stops certain actions from being performed if the VM is dead (fixes crashes)
- Add the missing functionality of toggling breakpoints on or off through the breakpoint dialog and list
- Add a 'NOP Instruction(s)' context menu action for the disassembly view

### Rationale behind Changes
Fixes / Features

### Suggested Testing Steps
Test the above.

### CODE REVIEW

**Comment by Goatman13** [comment]
Enabling breakpoint while game is running freeze pcsx2 with this info.
```
[  269.0132] (VMManager) Pausing...
[  269.0139] Hit store breakpoint @0x10009000
QMetaObject::invokeMethod: Dead lock detected
```
This happen only when i enable breakpoint using "enable" tick from the list. Disabling work fine, also enabling/disabling from "edit" breakpoint work fine. 

Other features from PR work as expected.

**Comment by kakashi314** [comment]
This pr will close #7750 with it.

**Comment by F0bes** [comment]
Sorry, I don't implement logpoints here.

**Comment by F0bes** [comment]
> Enabling breakpoint while game is running freeze pcsx2 with this info.
> 
> ```
> [  269.0132] (VMManager) Pausing...
> [  269.0139] Hit store breakpoint @0x10009000
> QMetaObject::invokeMethod: Dead lock detected
> ```
> 
> This happen only when i enable breakpoint using "enable" tick from the list. Disabling work fine, also enabling/disabling from "edit" breakpoint work fine.
> 
> Other features from PR work as expected.

Forgot to execute it on the VM thread. Fixed. PR should be ready to go.

**Review by Mrlinkwii — APPROVED** [review]

**Review by JordanTheToaster — APPROVED** [review]

**Review by RedDevilus — APPROVED** [review]

**Pull request merged**
