### PR TITLE
GameDB: Add Hitman Blood Money HW fix to the US versions

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Adds the HW fix for Blood Money to the US version.

### Rationale behind Changes
I didn't think the US version was affected, so I didn't add it, apparently it is.

### Suggested Testing Steps
Watch CI

### CODE REVIEW

**Comment by Parallax71** [comment]
hola, y hay fix para la version EUR?

**Comment by refractionpcsx2** [comment]
It's already done.

**Comment by Parallax71** [comment]
> It's already done.

yu-huuu  !!!!!  ....... un millon de gracias !!

**Comment by refractionpcsx2** [comment]
I wasn't fixing that. I was fixing a regression caused by a recent update. The game is still broken.

**Comment by Parallax71** [comment]
> I wasn't fixing that. I was fixing a regression caused by a recent update. The game is still broken.
> 
> I was fixing this image

aaahhh... perdón, te había entendido mal, creí que las sombras rojas eran las que estaban arregladas, perdona, no hablo ingles y uso el traductor de google, lo siento. Aun así... gracias igualmente por tu trabajo  :)

**Comment by refractionpcsx2** [comment]
No, sorry. The top left corner square is related to the red shadow problem. I'm going to try and tackle that later, but I don't make any promises.

**Comment by Parallax71** [comment]
> No, sorry. The top left corner square is related to the red shadow problem. I'm going to try and tackle that later, but I don't make any promises.

muchisimas gracias por todo, aun así esperaré el arreglo aunque no prometas nada, solo por estar ahí haciendo esos arreglos ya es mas que suficiente, es una pena porque este hitman blood money y Manhunt son mis 2 juegos favoritos de PS2 de todos los tiempos y justo estos dos juegos se muestran mal (Manhunt tiene el problema ese de los focos de luz). En fin, lo dicho, gracias por todo. Un saludo.

**Comment by Gadetron** [comment]
> No, sorry. The top left corner square is related to the red shadow problem. I'm going to try and tackle that later, but I don't make any promises.

any luck?

**Pull request merged**
