### PR TITLE
iR5900 Recompiler: Skip exception handler for (i)FlushCache syscalls

### PR DESCRIPTION
**Pull request by F0bes**
### Description of Changes
Skips handling exceptions when FlushCache and iFlushCache syscalls

### Rationale behind Changes
The cache isn't supported in the recompiler anyways. It might increase performance by a little bit

### Suggested Testing Steps
Benchmark EE heavy games

### CODE REVIEW

**Review by refractionpcsx2 — APPROVED** [review]

**Comment by refractionpcsx2** [comment]
> I can see a 4-14 fps improvement in cases where EE is limited.

Can you do comparisons using capframex or something? that's a LOT more than I was expecting.  We calculated about 1% difference, unless your framerate is like 400fps or higher.

**Comment by Buzzardsoul** [comment]
This is one of them
untitled

**Comment by Buzzardsoul** [comment]
Silent Hill 2:
untitled

**Comment by Buzzardsoul** [comment]
Shadow of the colossus: 
untitled

**Comment by Buzzardsoul** [comment]
Spyro enter the dragonfly:
untitled

**Comment by F0bes** [comment]
📈

**Comment by refractionpcsx2** [comment]
Stonks.

What is the first game graph?

**Comment by Buzzardsoul** [comment]
> Stonks.
> 
> What is the first game graph?

I was testing many games, I don't recall :/

But here's my final test, 
Crash tag team racing:
untitled

**Review by Mrlinkwii — APPROVED** [review]

**Comment by polybiusproxy** [comment]
@Buzzardsoul Unrelated, but how are you doing those graphs?

**Comment by Buzzardsoul** [comment]
> @Buzzardsoul Unrelated, but how are you doing those graphs?

At the same spot in a new game, I'd press f11

**Comment by refractionpcsx2** [comment]
You're using clang builds of both, right?

**Comment by Buzzardsoul** [comment]
> You're using clang builds of both, right?

I'm using v1.7.5004 from the updater, and this one: [PCSX2-windows-Qt-x64-AVX2-pr[9954]-sha[55f82a2]-title[iR5900 Recompiler Skip jump to interpreter for iFlushCache syscalls]](https://github.com/PCSX2/pcsx2/suites/16131298440/artifacts/921070438)

**Comment by refractionpcsx2** [comment]
did you use the pcsx2-qtx64-avx2-clang.exe from that archive?

**Comment by Buzzardsoul** [comment]
> did you use the pcsx2-qtx64-avx2-clang.exe from that archive?

nope

**Comment by refractionpcsx2** [comment]
> > did you use the pcsx2-qtx64-avx2-clang.exe from that archive?
> 
> nope

can you, please? the other one is slower.

**Comment by refractionpcsx2** [comment]
I just tried Crash Tag Team Racing and I got 173fps on both builds. So there's something really wrong with your numbers.

**Comment by Buzzardsoul** [comment]
> I just tried Crash Tag Team Racing and I got 173fps on both builds. So there's something really wrong with your numbers.
Here's crash tag team racing
untitled

**Comment by refractionpcsx2** [comment]
This is my crash tag team racing. I don't trust your numbers, sorry

image

**Comment by Buzzardsoul** [comment]
I mean, something is definitely off on my end. But still that's a pretty good change you have on your end.

**Comment by refractionpcsx2** [comment]
yeah, it's roughly 1%

**Comment by Goatman13** [comment]
Does it affect EE cycles? I guess it is because syscall handler and flush cache itself is not running. Not sure if that really matter for any game, but flush cache can take 1000 - 3000 cycles (not really accurate number, just observation). Normally DMA, VU0/1, IOP are running then, some picky game with tight loop can be problematic without burning those cycles.

**Comment by refractionpcsx2** [comment]
the calls did nothing for the JIT, they were nops. cycle counting will be no different.

**Comment by Goatman13** [comment]
Cool then, nice work!

**Comment by Dreadmoth** [comment]
Aggregate of 3 runs:

PCSX2-pr9954-ratchet

**Comment by Buzzardsoul** [comment]
> Aggregate of 3 runs:
> 
> PCSX2-pr9954-ratchet

Can you do one for Shadow of the colossus? That one is rather heavy on the ee

**Comment by F0bes** [comment]
So Goatman has a point. When we nop the syscall we don't end up firing the guests syscall exception handler.
What is done for the INTC or WaitLoop hack? Do we fast forward cycles. We could possibly do that here.

Here is the amount of cycles it takes to execute 5 FlushCache calls from the perspective of the guest.
<table>
<tr>
 <td>
 <td> Master (1.7.5007)
 <td> PR
<tr>
 <td>Interpreter
 <td> ~3562 Clock cycles
 <td> ~3704 Clock cycles
<tr>
 <td> Recompiler
 <td> ~3704 Clock cycles
 <td> ~32 Clock cycles
</table>

Full test details below

Source is available here: https://github.com/F0bes/flushcache-cycles/blob/master/flushcache_cycles.c
<details>
<summary>Master Recompiler</summary>

Using timer for following iterations
FlushCache()x5 took ‾1785 bus cycles (3570 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
FlushCache()x5 took ‾1781 bus cycles (3562 CPU clock cycles)
Using cop0 count for following iterations
FlushCache()x5 took ‾3564 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles
FlushCache()x5 took ‾3561 cycles

</details>

<details>
<summary>Master Interpreter</summary>

Using timer for following iterations
FlushCache()x5 took ‾1856 bus cycles (3712 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1851 bus cycles (3702 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1851 bus cycles (3702 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1851 bus cycles (3702 CPU clock cycles)
FlushCache()x5 took ‾1851 bus cycles (3702 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1851 bus cycles (3702 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1851 bus cycles (3702 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
Using cop0 count for following iterations
FlushCache()x5 took ‾3707 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles

</details>

<details>
<summary>PR Recompiler</summary>
Using timer for following iterations
FlushCache()x5 took ‾20 bus cycles (40 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
FlushCache()x5 took ‾16 bus cycles (32 CPU clock cycles)
Using cop0 count for following iterations
FlushCache()x5 took ‾34 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles
FlushCache()x5 took ‾31 cycles

</details>

<details>
<summary>PR Interpreter</summary>

Using timer for following iterations
FlushCache()x5 took ‾1856 bus cycles (3712 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1851 bus cycles (3702 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1851 bus cycles (3702 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1851 bus cycles (3702 CPU clock cycles)
FlushCache()x5 took ‾1851 bus cycles (3702 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1851 bus cycles (3702 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1851 bus cycles (3702 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
FlushCache()x5 took ‾1852 bus cycles (3704 CPU clock cycles)
Using cop0 count for following iterations
FlushCache()x5 took ‾3707 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles
FlushCache()x5 took ‾3704 cycles


</details>

**Comment by F0bes** [comment]
Updated it to include the cycles that would've been burned by the exception handler executing.
The PR now takes ~3532 CPU cycles for the above test. (At least that's what the guest thinks happened :wink:)

The only concern might be that games rely on the COP0 exception registers being set.

Please retest and re-benchmark as well.

**Comment by refractionpcsx2** [comment]
Did my FFX run again, average of 3 runs, numbers are about the same, maybe a little lower, but we could be talking margin of error there.

image

**Comment by refractionpcsx2** [comment]
Best of 3 on Crash Tag Team Racing didn't go so well :( Keep in mind that the GS was set to null renderer for this, to make sure the GS thread wasn't bottlenecking

image

**Comment by stenzek** [comment]
We could try not cutting the block early as well. See https://github.com/PCSX2/pcsx2/blob/master/pcsx2/x86/ix86-32/iR5900.cpp#L2406-L2410

**Review by kamfretoz — APPROVED** [review]

**Comment by Goatman13** [comment]
This PR fixed "David Douillet Judo" missing fighter portraits/stats, on character select screen.
Probably some timing issue and game is happier with hardcoded exception handler/flush cache cycles.

**Comment by F0bes** [comment]
😎

**Pull request merged**
