### PR TITLE
GameDB: Serial with ':' to '-' + GS HW and other Fixes

### PR DESCRIPTION
**Pull request by RedDevilus**
### Description of Changes

GameDB serials with ':' replaced with ' - '
+
Spacing consistent for comments
+
GS HW Fixes and other fixes for:
- Adventures of Cookie & Cream, The (Fixes https://github.com/PCSX2/pcsx2/issues/5779)
- Brothers in Arms - Earned in Blood / Road to Hill 30
- Black
- Chaos Legion
- God Hand
- Knockout Kings 2001 (Fixes https://github.com/PCSX2/pcsx2/issues/5709)
- Kuon
- Project Eden
- Psi-Ops - The Mindgate 
- Punisher, The 
- Ratchet Deadlocked (USA) / Gladiator (Europe) / 3 Up Your Arsenal
- Silent Hills Origins / Shattered Memories / 3 / 4
- SoulCalibur II / III

### Rationale behind Changes

Windows doesn't like you to use ':' in folders this caused issues for when CK1 did savestates in folders and now it's also messing with unable to add covers in Qt so better to replace them and also to avoid other issues now and the future.

WX:
https://github.com/PCSX2/pcsx2/pull/4747
Relevant comment:
image

Qt:
image
image

### Suggested Testing Steps

Test relevant games.

### CODE REVIEW

**Comment by RedPanda4552** [comment]
Is the true solution to this problem to go into GameIndex.yaml and modify every entry which may legitimately have a ":" in it? Or is it to look at code which is writing to the file system and make it stop writing illegal characters?

**Comment by RedDevilus** [comment]
I just avoid the issue that it it's going through illegal characters, most of the GameDB entries already use '-' vs about 200 entries containing ':' so it also streamlines the GameDB.

**Comment by RedPanda4552** [comment]
":" is not an illegal character for a game name though. Some may legitimately use it. So my angle is, how feasible is it to instead of overwriting GameIndex.yaml to correct for code that doesn't do error checking, write code that does error checking? If the names in GameIndex.yaml have to match names on the file system then I also have to call into question why we are using names as unique identifiers for files rather than serials or CRCs. Maybe I've been out of the loop but I don't see how display names having illegal file system characters can be an issue for something which, to my knowledge, shouldn't be written to the file system.

**Comment by RedDevilus** [comment]
> ":" is not an illegal character for a game name though. Some may legitimately use it. So my angle is, how feasible is it to instead of overwriting GameIndex.yaml to correct for code that doesn't do error checking, write code that does error checking? If the names in GameIndex.yaml have to match names on the file system then I also have to call into question why we are using names as unique identifiers for files rather than serials or CRCs. Maybe I've been out of the loop but I don't see how display names having illegal file system characters can be an issue for something which, to my knowledge, shouldn't be written to the file system.

It's fine if you launch a game sure but it's when you want to make a cover for Qt, or an older version of the gamestate revision that copied the game name of the GameDB as the folder. So instead the solution was to completely ignore the GameDB which to me isn't a solution either and sure this may not be the best approach but I don't see a problem revising a minority of entries.

You can check it here
[GameSerialsPCSX2-27March2022.txt](https://github.com/PCSX2/pcsx2/files/8358553/GameSerialsPCSX2-27March2022.txt)

Like if we just look at Eyetoy most of them are using '-' and only a few use ':' in the name. I'm not against error checking perhaps we can combine that with the PR.

**Comment by Blackbird88** [comment]
While you're at it, could you please add **[Demo]** to **Gran Turismo - Nissan Micra Edition**. I forgot to do it while adding it and it'd be silly to make whole PR for such small thing 😃

**Comment by RedDevilus** [comment]
Silent Hills Origins;
Old:
image
New:
image

Lost track of how many GS HW Fixes I have added.

**Comment by RedDevilus** [comment]
Other examples that should fix these games;

Ratchet 3 Up Your Arsenal:
Ratchet3UpYourArsenal
Ratchet Deadlocked (USA) Gladiator (Europe):
RatchetDeadlockedUSAGladiatorEurope

**Comment by RedDevilus** [comment]
Black;
Old:
image
New:
image

**Comment by RedDevilus** [comment]
Note: In future we should do error-checking on those special characters in case someone modifies it or there is an edge-case.

**Comment by RedDevilus** [comment]
Project eden;

Old:
image

New:
image

**Comment by RedDevilus** [comment]
SoulCalibur 3 clip provided from Discord user:


https://user-images.githubusercontent.com/24227051/160715774-c15cdbf1-e16d-4723-9a81-0d49ad7abea0.mov

**Comment by RedDevilus** [comment]
Kuon;
MTVU on:
image

MTVU off:
image

**Comment by RedDevilus** [comment]
Seem Soul Calibur II has the same issue as the third entry but to a lesser degree.

**Comment by RedDevilus** [comment]
Thanks Git for making no sense.

**Pull request closed without merging**
