### PR TITLE
GS: Fix up CLUT offset handling in 32bit I8 mode

### LINKED ISSUE #1597: Multiple palette context issue in harley davidson
For the record

It was fixed by the reverted commit 8d4fadb3c88b571a09873bc22009a771333a70ec

The explanation from the PR

```
Game: harley davidson

    write tex0 ctx0
    write tex0 ctx1
    draw ctx 0

Previous GSdx behavior will load the clut every write of TEX0. In the
above case the draw will take the wrong clut.

To be honest, it could be a wrong emulation on the EE core emulation.
The hardware likely got a single clut (1KB cache is quite expensive)
So clut loading must be skipped if the context is wrong.

Next draw will use the ctx1 clut so I apply TEX0 when the context is switched
```

### LINKED ISSUE #1628: Romance of the Three Kingdoms VII [SLPM-62010] font bug
SLPM62010,font bug

Added by refractionpcsx2:

Text on the menu has always displayed incorrectly however it was mostly right back in the 1.0.0 days. After sudonim's changes back in 2fbcafc the text became black and has stayed as such ever since.

Related forum thread with screenshots and info: http://forums.pcsx2.net/Thread-ROTK8

Followup thread re-highlighting the issue: http://forums.pcsx2.net/Thread-Bug-Report-Romance-of-the-Three-Kingdoms-8-NTSC-U-C

Note has been made in GSClut.cpp line 162 under WriteCLUT32_I8_CSM1

### LINKED ISSUE #2390: RTK IX Wording Are Black Unable To See
PCSX2 version:
PCSX2 1.4.0-20160105132032

PCSX2 options:
Defaults, Speedhacks Abled

Plugins used:
GSdx 20160105132032 (MSVC 19.00, AVX) 1.0.0 [gsdx32-avx
LilyPad (20151231175709) 0.11.0 [lilypad]
SPU-2X 20151231175709 2.0.0 [spu2-x]
cdvdGigaherz (20151231175709ll_ 0.9.0 [cdvdGigaherz]
USBnull Driver 20151231175709 0.7.0 [USBull]
FWnull Driver 20151231175709 0.7.0 [FWnull]
DEV9null Driver 20151231175709 0.5.0 [DEV9null]

Description of the issue:
Unable to read the wording of the game as it is in black.

How to reproduce the issue:
When go into the game

Last known version to work:
Don't know

PC specifications:
Operating System =  Microsoft Windows 10 Home (build 16299), 64-bit
Physical RAM     =  8077 MB
CPU name         =  Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Graphic = Nvidia GEFORCE GTX 950M

Photos:

These are the example of the issue.

Thank you.

### LINKED ISSUE #2650: GTA San Andreas Buggy Texture
***PCSX2 version:***
Build v1.5.0-dev-2633-ga8e8cb9b6

***PCSX2 options:***
OpenGL Software, AA1, 3 rendering threads and mipmapping.

***Note:*** 
Happens on any hardware or software setting I have.

***Description of the issue:***
Car dirt produces a pink, mirror like effect
gt

***How to reproduce the issue:***
Simply grab a car (preferably a light colored car to be more noticable) and drive it around the countryside or the beach to accumulate a bit of dirt or mud.

***Last known version to work:***
None, I think.

***PC specifications:***
Intel i5-4570
8GB DDR3 RAM
Nvidia GTX 1060 6GB
Windows 10 Pro 64-bit

### LINKED ISSUE #4396: [BUG] The History Channel: Battle for the Pacific - Graphical glitch
**Describe the bug**
The weapon has a broken texture on it or at least i think so

**To Reproduce**
Just start the game happens on DX11, open gl and software mode 

**Expected behavior**
no graphical glitch

**GS Settings**
Default

**Emulation Settings**
Default speed 2

**GS Window Screenshots**

video

**System Info (please complete the following information):**
PCSX2 1.7.0-20210424200746 - compiled on Apr 24 2021
	Operating System =  Microsoft Windows 10 Pro (build 19042), 64-bit
	Physical RAM     =  10210 MB
	CPU name         =  Intel(R) Core(TM) i5-3570S CPU @ 3.10GHz
	Vendor/Model     =  1050 ti
	CPU speed        =  3.092 ghz (4 logical threads)

**Logs and Dumps**
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/6370872/emuLog.txt)
[snaps.zip](https://github.com/PCSX2/pcsx2/files/6370873/snaps.zip)

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Fixes CLUT writing for games which use an offset to write to sections of the CLUT in PSMCT32 mode with I8. Wraps CLUT memory when reading with an offset

### Rationale behind Changes
Writing with offset was broken and previously used the "clut_reload_on_draw" hack, which wasn't really the solution. Also remove CLUT memory wrapping code (by duplicating it) didn't really work, so now it properly wraps.

### Suggested Testing Steps
Test games mentioned, make sure the colours are correct. Test other games just to make sure nothing is broken.

Games which previously needed the load_clut_before_draw hack
Cabela's Hunting games
Harley Davidson
Fixes #1597

Also fixes Romance of the Three Kingdoms games colours.
Fixes #1628
Fixes #2390

The History Channel: Battle for the Pacific 
Fixes #4396 

Other games apparently fixed

NPPL Championship Paintball 2009
Spider-Man Friend or Foe 
Apparently fixes Rapala Pro Fishing also

Correctly clamping of CLUT reading with offset to repeat last CSA offset fixes GTA San Andreas dirt
Fixes #2650

### CODE REVIEW

**Comment by F0bes** [comment]
Played GT3 for a good 2 hours with it. No visible issues.

**Comment by gilderoylockhart01** [comment]
Yeah long awaited PR that's for sure, and it does work fine in the games which did have problems with CLUT. I tested Spiderman Friend or Foe but you can expect a bunch of Activion games such as Cabela to be fixed as well.

The only remaining gremlin is Virtual-On but well, not related isn't it?

**Comment by refractionpcsx2** [comment]
Virtual-On is an invalidation issue, like other Sega games I believe it draws to the CLUT and should invalidate it, but it doesn't, I need to look in to it.  Forcefully invalidating it makes the game work.

**Comment by prafullpcsx2** [comment]
Harley Davidson – Race to Rally

image
image

Romance of Three Kingdoms VII

image
image
  
Spiderman Friend or Foe

image
image
 
Cabela’s Dangerous Hunts 2

image
image
 
NPPL Championship Paintball 2009

image
image
  
History Channel: Battle for the Pacific

image
image
 
Grand Theft Auto San Andreas

image
image
  
Rapala Pro Bass Fishing

image
image

Romance of Three Kingdoms VIII

image
image
 
Cabela’s Legendary Adventures

image
image
  
Shamu’s Deep Sea Adventures

image
image

Cabela’s Big Game Hunter 2005 Adventures

image
image

**Review by Mrlinkwii — APPROVED** [review]

**Comment by refractionpcsx2** [comment]
Updated GTA pictures

Before:

image

After:

image

**Pull request merged**
