### PR TITLE
GameDB: Various fixes

### LINKED ISSUE #10936: [BUG]: Jak X afterburner detaches from vehicle during sharp turns
### Describe the Bug

During Jak X, you can drift around corners. If you drift tightly enough, the afterburner effect on the back of the car starts teleporting off to the side of the vehicle. Ref actually fixed a regression not too long ago that made this bug worse, but it is still present, and I do not ever recall it happening on original hardware. Console log showed nothing, and it is not a GS issue. GS dump and screenshot below anyway just so there's something to see.

The afterburner will teleport to the side you're drifting against. For example, if you're making a sharp left turn, the afterburner will teleport to the left side of the vehicle, and vice versa. In terms of angle, the afterburner remains parallel with the vehicle (I could be misremembering, but I think the issue ref fixed actually did affect the angle). Although in the image below, the afterburner is only horizontally offset from the exhaust, it can become depth-offset as well (although I think it only ever teleports backwards, not forwards, in terms of depth). The depth and horizontal offsets can happen simultaneously, so it can move to the side and backwards, for instance, although it seems like these two are in contention with each other (i.e. a lot of horizontal offset seems to mean less depth offset).

The issue is present on vehicles other than the Road Blade (the one pictured).

### Reproduction Steps

Go into a race and then drift (hold circle while turning) around a tight corner. This will show up in the first race of the game, Spargus City, plenty of times. The afterburner effect should sporadically teleport away from the vehicle.

### Expected Behavior

The afterburner effect should stay attached to the vehicle's exhaust pipes.

### PCSX2 Revision

v1.7.5584

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Manjaro – Flatpak

### CPU

Ryzen 7 5800X

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

Jak X - Combat Racing_SCUS-97429_20240316084925

Jak X - Combat Racing_SCUS-97429_20240316084924

### Logs & Dumps

[Jak X - Combat Racing_SCUS-97429_20240316084924.zip](https://github.com/PCSX2/pcsx2/files/14624241/Jak.X.-.Combat.Racing_SCUS-97429_20240316084924.zip)

### LINKED ISSUE #11386: [BUG]: Ape Escape 3 SPS Glitch
### Describe the Bug

An sps glitch with the character's light saber when entering a plane in the 'Airplane Squadron' level. Rounding and clamping modes seem to affect it, but not fix it.

### Reproduction Steps

Play Ape Escape 3's level 'Airplane Squadron' until you reach this specific airplane.

### Expected Behavior

For the saber's beam to look normal. Like this:
Ape Escape 3_SCUS-97501_20240612230306

### PCSX2 Revision

1.7.5877

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i7-7600

### GPU

GTX 1050 TI

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

Ape Escape 3_SCUS-97501_20240612225448

### Logs & Dumps

Savestate:
[SCUS-97501 (7571AAEE).01.p2s.zip](https://github.com/user-attachments/files/15810304/SCUS-97501.7571AAEE.01.p2s.zip)

### LINKED ISSUE #11389: [BUG]:  SPS in Jackie Chan Adventures (SCES-52412)
### Describe the Bug

SPS when entering Spain in Jackie's and Jade's character models. Fixed by disabling Instant VU1

https://github.com/PCSX2/pcsx2/assets/126727903/4c335029-deeb-4a37-a037-d2c4e7198a54

### Reproduction Steps

Simply reach Spain. Or use my savestate:
[SCES-52412 (AC4DFD5A).01.p2s.zip](https://github.com/user-attachments/files/15827370/SCES-52412.AC4DFD5A.01.p2s.zip)

### Expected Behavior

No SPS

### PCSX2 Revision

1.7.5886

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i7-7600

### GPU

GTX 1050 TI

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by JordanTheToaster**
### Description of Changes
Just a little fixing for bloom alignment now that Align To Native HPO is safer to use. Very nice.

Fixes #10936 
Fixes #11386 
Fixes #11389 

### Rationale behind Changes
Fix good.

### Suggested Testing Steps
Make sure CI is happy boi.

### CODE REVIEW

**Comment by DonelBueno** [comment]
Can I suggest some changes to the GameDB for this PR?


**NFS: Hot Pursuit 2 (Recommend High Blending)**

Medium Blending:


High Blending:


Software:



**Jak 3 (Recommend High Blending, affects the pause menu and the press start screen, probably more)**

Medium Blending:
PCSX2_2024_06_18_02_38_38_241
PCSX2_2024_06_18_02_44_29_664

High Blending:
PCSX2_2024_06_18_02_43_23_310
PCSX2_2024_06_18_02_44_36_854

Software:
PCSX2_2024_06_18_02_43_42_700
PCSX2_2024_06_18_02_44_25_177


**Sega Rally 2006 (Remove Blending Recommendation)**

Minimum Blending:
PCSX2_2024_06_18_02_39_52_682

Maximum Blending:
PCSX2_2024_06_18_02_39_36_966

Software:
PCSX2_2024_06_18_02_39_58_255

**Comment by bigol83** [comment]
Dragon Quest VIII with HPO to Native gives main character hair red outlines

Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20240618113511
[Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20240618113511.gs.zip](https://github.com/user-attachments/files/15883736/Dragon.Quest.VIII.-.Journey.of.the.Cursed.King_SLES-53974_20240618113511.gs.zip)

**Comment by DonelBueno** [comment]
> Dragon Quest VIII with HPO to Native and Round Sprite to Full give main character hair red outlines. Even just RS to Full still gives main character red outlines.
> 

That's unfortunate. Well, at least HPO align to native seems to be a modest improvement over master and not cause negative effects. Anyway, I honestly these red outlines are less distracting than the black lines, but of course that's subjective.

**Comment by bigol83** [comment]
Align to Native alone has the red oulines on the hair, too. Considering that @refractionpcsx2 fixed Valkyrie Profile going pixelated after camera transitions, i wonder if Dragon Quest VIII being pixelated on camera change can be fixed too. Aggressive Native Scaling actually is the only real solution to the right side lines without any side effects whatsoever.  
I know he said he didn't like the way character black outlines became too thick with Aggressive Native Scaling, but that would easily be the less distracting issue and the best outcome.

**Comment by JordanTheToaster** [comment]
> Virtua Racing

Now a fan of adding RS Full to TS2 and DQ8 has aforementioned issues but I've added everything else.

**Comment by refractionpcsx2** [comment]
DQ8 negative effects from Align to Native (look at the water)

image

and full round kinda breaks the position of the post lighting on the sword in this scene (not that it's great.

**Comment by refractionpcsx2** [comment]
As for the pixelation, it still happens, that PR wasn't a magic bullet, unfortunately.

image

Here's the dump if you wanna try it yourself
[Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230303225648.gs.zip](https://github.com/user-attachments/files/15886500/Dragon.Quest.VIII.-.Journey.of.the.Cursed.King_SLES-53974_20230303225648.gs.zip)

**Comment by bigol83** [comment]
> As for the pixelation, it still happens, that PR wasn't a magic bullet, unfortunately.
> 
> image
> 
> Here's the dump if you wanna try it yourself [Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230303225648.gs.zip](https://github.com/user-attachments/files/15886500/Dragon.Quest.VIII.-.Journey.of.the.Cursed.King_SLES-53974_20230303225648.gs.zip)

I know it happens, I tested it because I hoped it would have fixed Dragon Quest too, I also checked and saw that pressing F9 even with Native Scaling set to Aggressive fixes the pixelation and removes the black lines without any side effects. That is until there is a battle transition and it goes back to being pixelated. Then pressing F9 fixes the pixelation again and so on.

**Comment by DonelBueno** [comment]
> > Virtua Racing
> 
> Not a fan of adding RS Full to TS2 and DQ8 has aforementioned issues but I've added everything else.

You only forgot to remove the blending recommendation for Sega Rally 2006 (SLPM-66212).

**Comment by JordanTheToaster** [comment]
> You only forgot to remove the blending recommendation for Sega Rally 2006 (SLPM-66212).

I got rid of it previously but as it turns out it came back and I have made doubly sure it stays gone. Pesky blend rec.

**Comment by refractionpcsx2** [comment]
@DonelBueno also Timesplitters crosshair is fixed by Native Scaling: Normal, which is a much better solution than round sprite :D So we'll add that

**Comment by DonelBueno** [comment]
> @DonelBueno also Timesplitters crosshair is fixed by Native Scaling: Normal, which is a much better solution than round sprite :D So we'll add that

Good one, I forgot to test native scaling.

**Review by Mrlinkwii — APPROVED** [review]

**Comment by AmyRoxwell** [comment]
Round Sprite Full fixes the Option title, removing the lines while upscaling for some sprites

Saint Seiya Meiou Hades Juunikyuu Hen_SLPS-25744_20240619171634

Saint Seiya Meiou Hades Juunikyuu Hen_SLPS-25744_20240619171640

**Comment by crashGG** [comment]
Another Century’s Episode 3 THE FINAL
master:
strong flickering on the title screen when use Hardware Rendering
software:
Another Century's Episode 3 - The Final_SLPS-25784_20240621092730

pr:
change deinterlacing : 6
no more flickering, but the brightness of the game screen is halved.
Another Century's Episode 3 - The Final_SLPS-25784_20240621092839

but with this fix
gameFixes:
    - SoftwareRendererFMVHack
See here:https://github.com/PCSX2/pcsx2/pull/11434
The issue is basically solved.

**Comment by JordanTheToaster** [comment]
> but with this fix gameFixes: - SoftwareRendererFMVHack See here:#11434 The issue is basically solved.

Looks fine here?

image

**Comment by crashGG** [comment]
> > but with this fix gameFixes: - SoftwareRendererFMVHack See here:#11434 The issue is basically solved.
> 
> Looks fine here?
> 
> image

Fine. Except for the flickering for a few seconds when the game starts, the game screen is normal afterwards. Switching SoftwareRendererFMV seems to be the best stopgap solution until a better way is found.

**Comment by crashGG** [comment]
> > but with this fix gameFixes: - SoftwareRendererFMVHack See here:#11434 The issue is basically solved.
> 
> Looks fine here?
> 
> image

The new master build 5921 has solved this issue

**Pull request merged**
