### PR TITLE
Free bsd fixes

### PR DESCRIPTION
**Pull request by martymac**
### Description of Changes

Here are 3 patches necessary to build recent pcsx2 on FreeBSD. I've already updated the port upstream, see:

https://www.freshports.org/emulators/pcsx2/

Cheers,

Ganael.

### CODE REVIEW

**Comment by RedDevilus** [comment]
Could you prefix the commits like 'build:' ?

**Comment by martymac** [comment]
Hello,

Done, thanks for your feedback.

I've not prefixed the commit related to shm_open(3) call as it breaks at runtime.

Cheers,

Ganael.

**Comment by lightningterror** [comment]
Commits can be squashed.

**Comment by martymac** [comment]
I've squashed build-related commits.

**Pull request merged**
