### PR TITLE
GS/HW: RTA improvements and enhancements

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Improvements to RTA to make it more functional and accurate.

### Rationale behind Changes
There were opportunities to improve things, so went ahead and did it.
More followup from https://github.com/PCSX2/pcsx2/pull/10853

### Suggested Testing Steps
Test random games including ones below, make sure everything is good.

### Vulkan Improvements (Basic Blending):

Ace Combat:
Master:
image
PR:
image

Hitman 2:
Master:
image
PR:
image

Need for Speed Underground 2 (previously required medium blending)
Master:
image
PR:
image

Tales of the Abyss (difficult to see, look in the top right):
Master:
image
PR:
image

### Direct3D Improvements (Basic Blending):

Ace Combat:
Master:
image
PR:
image

Ape Escape 2:
Master:
image
PR:
image

Bully:
Master:
image
PR:
image

God of War (This was a recent regression)
Master:
image
PR:
image

Hitman 2:
Master:
image
PR:
image

Jojo no Kimyou na Bouken
Master:
image
PR;
image

Mercenaries:
Master:
image
PR:
image

Need for Speed Underground 2:
Master:
image
PR:
image

Okage - Shadow King:
Master:
image
PR:
image

Spider-Man 3:
Master:
image
PR:
image

Star Wars Battlefront 2 (I think this was also a regression):
Master:
image
PR:
image

Tales of the Abyss:
Master:
image
PR:
image

Time Crisis 2:
Master:
image
PR:
image

Waga Ryuomiyo - Pride of the Dragon Peace:
Master:
image
PR:
image

### CODE REVIEW

**Comment by bigol83** [comment]
Even with these changes the NFS Undergound 2 demo in Burnout 3 still requires Medium blending with Vulkan renderer to correctly match software.

I will leave a gsdump so you can check 

[Burnout 3 - Takedown_SLES-52585_20240324005747.gs.zip](https://github.com/PCSX2/pcsx2/files/14733898/Burnout.3.-.Takedown_SLES-52585_20240324005747.gs.zip)

**Comment by refractionpcsx2** [comment]
Yes the reflections still require a higher blend, it's the post processing that no longer requires it.

**Review by JordanTheToaster — APPROVED** [review]

**Comment by bigol83** [comment]
> Yes the reflections still require a higher blend, it's the post processing that no longer requires it.

This is a comparison at native resolution between software and Vulkan with basic blending

Software

Burnout 3 - Takedown_SLES-52585_20240324110152


Vulkan basic blending

Burnout 3 - Takedown_SLES-52585_20240324110159


It's that green tint in Software that is red in Vulkan basic blending what i was talking about.

**Comment by refractionpcsx2** [comment]
> > Yes the reflections still require a higher blend, it's the post processing that no longer requires it.
> 
> This is a comparison at native resolution between software and Vulkan with basic blending
>
> It's that green tint in Software that is red in Vulkan basic blending what i was talking about.

That could be we're still doing a shuffle wrong, unless you're implying it does the green tint fine in high blend?

**Comment by bigol83** [comment]
> > > Yes the reflections still require a higher blend, it's the post processing that no longer requires it.
> > 
> > 
> > This is a comparison at native resolution between software and Vulkan with basic blending
> > It's that green tint in Software that is red in Vulkan basic blending what i was talking about.
> 
> That could be we're still doing a shuffle wrong, unless you're implying it does the green tint fine in high blend?

Green tint is there with Medium blending both in Master and in this PR.

**Comment by refractionpcsx2** [comment]
Okay yeah, Jordan just took a look and it looks like the RT alpha is shooting up to 255, I'm going to assume that's not quite right :P I'll have a look to see if there's anything I can do about it

**Comment by refractionpcsx2** [comment]
Okay, so the game ruins our fun.

It does a clear of the alpha after the render target has been changed in to full range, which would normally reset it, but because they decided to do the clear twice, our "primitive no gaps" check fails and doesn't reset the alpha, so it's broken once it gets to the post effect.

Fortunately I don't believe the full game does this.

**Review by kamfretoz — APPROVED** [review]

**Pull request merged**
