### PR TITLE
InputManager: Support using raw input for pointer bindings

### LINKED ISSUE #7888: [Feature Request]: Support for two lightguns
### Description

Now that Guncon2 support has been added, would be nice to play with two guns.
Most lightguns for pc (guncon2driver, Ems topgun, aimtrak, sinden...) are detected as absolute coordinates mice.
As I've read mice can be used separately with rawinput.

### Reason

This would alllow to play 2p lightgun games like Virtua Cop Elite or Vampire Night and 1p dual gun action games like Time Crisis or Gunfighter 2

### Examples

This feature is supported by Mame, Retroarch and some standalone emulators

### LINKED ISSUE #7891: [Feature Request]: onscreen Targeting reticule when Guncon 2 mode is enabled for USB
### Description

A simple targeting reticule or crosshairs that appear on screen when Guncon mode is enabled in the USB settings, allowing you to see where you are aiming without having to unlock the mouse while playing games

### Reason

Due to the size of an average mouse icon, it can be hard to see where you are aiming at times in light gun games. By having a larger targeting reticule, it can be hard to see where you are aiming. A targeting reticule can also help players have a more seamless game experience as well, I believe.
Also, by having it be 2 separate reticule colours based on which usb port it is assigned to, this allows for possible 2 player guncon games to be playable.
This also might help for folks using a wiimote or or joycon gyro controls as a mouse pointer, which allows them the ability to use the controllers as a mock lightgun.

### Examples

I believe such a mode is activated when Guncon 1 and Justifier mode is enabled in duckstation
Certain versions of Melon DS (definitely in retroarch, not sure about standalone) have an onscreen reticule  to indicate where you are aiming/touching the second screen.
I believe Mame also has this for light gun games, but I can not recall exactly.

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Also adds crosshair support to GunCon 2.

Windows only.

I think things are mostly done, just needs bug fixing and polish. But I don't really have the energy to do so at the moment, maybe someone else wants to help.

### Rationale behind Changes

Supporting multiple pointers/mice.

### Suggested Testing Steps

Not really relevant for now.

Fixes #7891
Fixes #7888

### CODE REVIEW

**Comment by carolis15** [comment]
Is there an option to show crosshairs?

**Comment by stenzek** [comment]
Yes, that's what the description says. You need to provide your own image in the settings for the USB device.

**Comment by carolis15** [comment]
Thanks, it works like a charm! Could it be possible to add an option to use a gamepad as a lightgun? For P1 I use a Sinden lightgun for P2 a wiimote as a gamepad. This option works great with other emus as MAME, Supermodel and Flycast

**Comment by stenzek** [comment]
I've considered it, but it's not straightforward, currently the cursor drawing is attached to the pointer position in InputManager. I'd have to rejig things a little, and like I said in the OP, not having much energy for it at the moment.

**Comment by Comfarol** [comment]
Tested v1.7.4356 for the Raw input changes. Currently if you bind left, middle and right mouse clicks they will be used by both guns so when one person shoots, they both shoot. Not sure if this has been reported before, apologies if it has.

**Comment by RickBlake** [comment]
When 'Enable Raw Input' is unchecked, I go to USB Port 1 > GunCon2 > Pointer/Aiming. 
I click in that field, move the cursor, and it registers as a pointer.
I start Time Crisis 2, I can calibrate and play the game.

When 'Enable Raw Input' is checked, I go to USB Port 1 > GunCon2 > Pointer/Aiming. 
I click in that field, move the cursor, it is not registered. Only when I click a button the pointer is registered. 
I start Time Crisis 2, trigger works (i can hear gun shots) but aiming doesn't, I can't calibrate. With the crosshair image on, it is stuck in the top left of the screen.

**Comment by stenzek** [comment]
Sorry, I'm not going to be actioning any feedback for this PR, as I stated in the OP, I don't have any interest in completing it (it also states testing is not applicable).

Unless you're planning on contributing code changes, please refrain from commenting and clogging up the thread.

Thanks.

**Comment by Dradyoz** [comment]
Nice try, this is about crosshairs not dual guns operating independantly - Allow DEMULSHOOTER intergration - having two light guns to operate independant has been missing since verion 1.6  Why can't Demulshooter intergration do some of the heaving lifting?

**Comment by magicray1028** [comment]
Has the crosshair function been removed in the latest nightly? Im having trouble finding the setting to add a crosshair under controller settings.

**Comment by refractionpcsx2** [comment]
This is not a place for support @magicray1028 please use the forums or discord if you want help.

**Comment by stenzek** [comment]
@Dradyoz rude people like you are exactly why I lost interest in finishing this PR (because I don't really have any interest in it personally).

I'm locking this thread, since obviously reading and being nice is too difficult.

Please remember we're people too, specifically volunteers, giving up our free time. We don't owe you anything, and we work on what we feel like, not what you instruct us to prioritize.

**Pull request closed without merging**
