### PR TITLE
Add ZSO Support

### PR DESCRIPTION
**Pull request by orcutt989**
### Description of Changes

Adds ability to play ZSO files.

### Rationale behind Changes

This is a popular format that has been in development and many people are switching to this format over CSO and ISO.
https://github.com/PCSX2/pcsx2/issues/6585
https://github.com/PCSX2/pcsx2/issues/6055
https://github.com/PCSX2/pcsx2/issues/6050

### CODE REVIEW

**Comment by orcutt989** [comment]
@JoseAaronLopezGarcia I fixed up your CPP file and struggled with Visual Studio, and got a working build, but when I load a ZSO file it just does nothing.

Here is the build - https://file.io/wsPRz35mv4M3

**Comment by F0bes** [comment]
Please learn how to use git or at least GitHub desktop. Creating a commit for every file deletion in an effort to fix this mess is not going to help you. You will be asked to squash them together.

**Comment by orcutt989** [comment]
Its mostly Visual Studio. I will close and cleanup and reopen.

**Comment by JoseAaronLopezGarcia** [comment]
So is it working?

**Pull request closed without merging**
