### PR TITLE
Explicit fail on missing dependency in package mode

### PR DESCRIPTION
**Pull request by nE0sIghT**
This patch introduces cmake options for every PCSX2 component allowing to explicitly specify needed parts.
In addition every STATUS message for missing dependency changed to FATAL_ERROR so build system will explicitly fail if requested component can not be built.

### CODE REVIEW

**Comment by micove** [comment]
I like this PR but there is a big and inconsistent change of behavior.

Before this:
Missing dependencies => skip
Missing folder => skip

After this:
Missing dependencies => all fail but common libs is skipped
Missing folder => 8 fail and 10 get skipped

I agree with the missing dependencies should equal a failure. I'm not sure if a missing folder should equal a failure. Also, it feels random when they fail or get skipped.

I prefer
Missing dependencies => all fail even common_libs
Missing folder => all skip but fix common_libs in ${CMAKE_SOURCE_DIR/CMakeLists.txt

Basically:
In ${CMAKE_SOURCE_DIR/CMakeLists.txt
```
# make common
if(common_libs)
    add_subdirectory(common/src/Utilities)
    add_subdirectory(common/src/x86emitter)
endif()
```
This need to check for those folders existing.

In ${CMAKE_SOURCE_DIR/cmake/SelectPcsx2Plugins.cmake
```
Remove all the "AND EXISTS "${CMAKE_SOURCE_DIR}" (there are ~8)

This is already checked in:
${CMAKE_SOURCE_DIR/CMakeLists.txt
${CMAKE_SOURCE_DIR/plugins/CMakeLists.txt
```

Also 2 pedantic issues:
- For consistency the 2nd error for core
```
message(FATAL_ERROR "PCSX2 core miss some dependencies: ${msg_dep_pcsx2}")
to
message(FATAL_ERROR "PCSX2 core miss GTK dependency")
```
- For consistency don't set (var, FALSE) before the message(FATAL_ERROR). Half of them set it to false and half don't. Pick one and stick to it. It's probably not needed so removing it should be less clutter.

Summary:
It's fine but things are not consistent. To be fair this fixes some old issues and some consistency issues are present before too.

**Comment by nE0sIghT** [comment]
Thanks for review.
I pushed new commits - hope them address all issues

**Comment by micove** [comment]
FWIW, I looked at it again and it looks fine to me now. :)

**Comment by gregory38** [comment]
```
This patch introduces cmake options for every PCSX2 component allowing to explicitly specify needed parts.
```
Why? If possible I want to keep the build simple. Unsupported plugins are in extra, good plugins are in standard build. The only exception is lilypad. The only reason to use extra plugin is CDVD plugin.

```
In addition every STATUS message for missing dependency changed to FATAL_ERROR so build system will explicitly fail if requested component can not be built.
```
I'm against it. It is painful to install all 32bits lib on some systems. It reduce the dependency requirement if you want to build a single plugin/core. Providing 10 options is not nice.

**Comment by nE0sIghT** [comment]
> Why?

The reason is to simplify configuration of only needed parts and avoid [creepy sed in Gentoo ebuilds] (https://github.com/nE0sIghT/vortex-overlay/blob/084278ffdff047b5c6c41479c72060b5f430230a/games-emulation/pcsx2/pcsx2-1.3.1-r2.ebuild#L79).
Link i provided is for 1.3.1 tag, and indeed it's [much simpler in current git version](https://github.com/nE0sIghT/vortex-overlay/blob/084278ffdff047b5c6c41479c72060b5f430230a/games-emulation/pcsx2/pcsx2-9999-r2.ebuild#L70). But there is 2 pad plugins and you said about CDVD also.
And if you look at even early attempt to package PCSX2 for Gentoo (from another author) - it [looks like that](https://github.com/armills/overlay/blob/master/games-emulation/pcsx2/pcsx2-9999.ebuild#L60). I want to avoid that in the future.

> Unsupported plugins are in extra, good plugins are in standard build. The only exception is lilypad. The only reason to use extra plugin is CDVD plugin.

In this PR i tried to mimic removed EXTRA_PLUGINS option by setting defaults for new options in respect to removed one and list all extra plugins in build.sh.
I understand that it will be a bit harder to configure only one plugin for building in generic case but otherwise i will stuck with sed or distro-specific patch in Gentoo. Or just will take away user's freedom to choose and force building hardcoded components like in binary distros.

> I'm against it. It is painful to install all 32bits lib on some systems. It reduce the dependency requirement if you want to build a single plugin/core.

But there is real problem for packaging. For example after [that commit](https://github.com/PCSX2/pcsx2/commit/5c046180a1dcd49c165b48b72d069dab7a93dd42) i silently lost GSdx plugin but all my builds was successful.
Currently there is no way to explicitly request specific parts to build and (what is more important) there is no way to forbid something to build even if all dependencies sufficed (it's about CDVD, for example).

**Comment by gregory38** [comment]
1.3.1 tag is just a test of the git tag command. It is as good/bad at latest git.
Let's be pragmatic:

* create a macro => message will be warning in normal mode and fatal in package mode.

* on the plugin choice. There is no choice ;)
Pad => onepad only. Lilypad is for dev only.
Gs => gsdx or zzogl. However ZZogl has legal issue, is slower and has more gliches. ZZogl is only useful for people with a GL2 GPU/drivers (or dev). Very small market (likely limited by a too old PC). Time to move on.
Spu => spu2x
Cdvd => choice of some plugins
Others => null

For distribution, it is easy. We disable lilypad and enable a couple of cdvd plugins (1/2 could be enough).

**Comment by nE0sIghT** [comment]
> For distribution, it is easy. We disable lilypad and enable a couple of cdvd plugins (1/2 could be enough).

Is it ok to move Lilypad/CDVDnull to extra plugins and CDVDiso to not extra?

**Comment by gregory38** [comment]
In package mode yes. However don't you need the null plugin to read iso?

**Comment by nE0sIghT** [comment]
Hmm i see now that CDVDiso is not needed really and CDVDlinuz is not working.

**Comment by gregory38** [comment]
Cdvd plugins are only useful to read from a DVD. It is often recommended to dump the dvd as iso to avoid various issue

**Comment by gregory38** [comment]
I pushed some change in GIT. Tell me if it is ok with you.
1/ move lilypad to extra plugin in package mode
2/ use fatal error in package mode.

**Comment by nE0sIghT** [comment]
Looks good, thank you!

**Pull request closed without merging**
