### PR TITLE
gsdx tc: miss a set scaling call

### PR DESCRIPTION
**Pull request by gregory38**
Likely impact issue #83/#694

Try to play few game to ensure no regression on scaling behavior.

### CODE REVIEW

**Comment by ramapcsx2** [comment]
Devil May Cry is fixed :)
I don't have a savegame for that spot in Xenosaga but I'll keep checking a few other games.
Great job :)

**Comment by FlatOutPS2** [comment]
Yeah, DMC is fixed. And I've noticed no regressions in other games so far either.

**Comment by FlatOutPS2** [comment]
It does not fix a similar looking issue in This Is Football 2003 cutscenes:

A GSdump in case you're interested:
[This Is Football 2003 - cutscene top left corner duplicate image issue (SW and HW).zip](https://github.com/PCSX2/pcsx2/files/517986/This.Is.Football.2003.-.cutscene.top.left.corner.duplicate.image.issue.SW.and.HW.zip)

**Comment by bositman** [comment]
I only got a black screen in both SW and HW in Xenosaga cuscene with this...any specific option I'm supposed to be using?

**Comment by gregory38** [comment]
I didn't push yet the extra fix to handle the greyscacle (YUV). I'm not happy with my patches. I also nees to look at the sw renderer.

**Comment by gregory38** [comment]
So let's merge it so I can work further on the xenosaga issue.

**Pull request merged**
