### PR TITLE
GS-TC: Don't skip depth lookup on KOF2002 - The King of Fighters 2002

### PR DESCRIPTION
**Pull request by Immersion95**
KOF2002 is affected by this exact same [SVCChaos issue](https://github.com/PCSX2/pcsx2/issues/1862).

In HW, the menu isn't showed and only the blue background is displayed. Software displays it perfectly.

HW : 
gs_20220506120513_King of Fighters 2002_ The _SNK Best Collection_ _NTSC-J__SLPS-25573

SW :
gs_20220506120518_King of Fighters 2002_ The _SNK Best Collection_ _NTSC-J__SLPS-25573

This was solved by [this PR](https://github.com/PCSX2/pcsx2/pull/2382), I just added KOF2002 to the list.

I also attached GS dumps as no issue was opened : [snaps.zip](https://github.com/Immersion95/pcsx2/files/8639202/snaps.zip)

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Could you prefix your commits with GS rather than gsdx please. gsdx doesn't exist anymore :)

**Comment by lightningterror** [comment]
Are we sure it's the same issue?

**Comment by refractionpcsx2** [comment]
yes some after pictures with the use of this PR would also be helpful

**Comment by Immersion95** [comment]
> yes some after pictures with the use of this PR would also be helpful

Yes it does work, here it is : 
gs_20220506154653_King of Fighters 2002_ The _NTSC-J__SLPS-25347

[snaps PR.zip](https://github.com/PCSX2/pcsx2/files/8641169/snaps.PR.zip)

**Pull request merged**
