### PR TITLE
Qt: Revision default hotkeys v2

### PR DESCRIPTION
**Pull request by RedDevilus**
### Description of Changes

There has been a re-order of keybindings, new keybindings and missing Single Frame GS Dump, Multi Frame GS Dump and Input Recording mode.

To be decided for the rest if it needs default hotkeys and which key or key combinations would be best.

image
image
image
image
image

### Rationale behind Changes

Consistency with older hotkeys, better code readability which mimics GUI structure.
### Suggested Testing Steps

Test hotkeys.

### CODE REVIEW

**Comment by RedDevilus** [comment]
F8:
image

Shift + F8: 
image

Control + Shift + F8:
image

Spamming different combination seems to work fine:
image

**Comment by coornio** [comment]
Perhaps it might be a good idea to consider a combination of keys friendlier to one-handed use for the GS dumps? From the left ctrl/shift the F8 key is too far, and using the right ctrl/shift with your left hand is awkward. You can surely use both hands at once but in some situations you might be required to do an action ingame while the recording is happening.

With this in mind, perhaps we should think about how to make one-handed use of multi-frame dumps easier, or even the possibility of changing it to a start/stop record function altogether so you won't have to hold the buttons down for the duration (with failsafe duration in case someone forgets and automatic cancel if they save/load a savestate).

**Comment by stenzek** [comment]
There's always the gs dump item in the debug menu.

**Comment by RedDevilus** [comment]
> There's always the gs dump item in the debug menu.

Yeah, that's what people use now, but it's nice to have the same hotkeys on Qt.

**Comment by Rex000** [comment]
A toggle for muting audio would be nice in the "General" tab.

**Pull request merged**
