### PR TITLE
Gamedb: update changes to pdf

### PR DESCRIPTION
**Pull request by Mrlinkwii**
### Description of Changes

updates the gameindex.pdf

### Suggested Testing Steps

look at the pdf

### CODE REVIEW

**Comment by BlueR20** [comment]
So laggy. Please make this can run at slow computer.

**Comment by refractionpcsx2** [comment]
Are you trolling?

**Comment by BlueR20** [comment]
You think I'm trolling? C'mon. I'm serious here.

**Comment by lightningterror** [comment]
> You think I'm trolling? C'mon. I'm serious here.

This isn't a support forum. Use either the forum or discord.

**Pull request merged**
