### PR TITLE
GSdx: Update D3D fbmask emulation on texture shuffle

### PR DESCRIPTION
**Pull request by lightningterror**
Improves accuracy on Sly series.

Rendering is still bad and needs a lot more work but
it's a little bit better.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Is this ready to go or do you need to do more work?

**Comment by gregory38** [comment]
It would be better to use the gl macro for debug. Maybe rename them. And in a separate commit

**Comment by gregory38** [comment]
Or add a dx macro

**Comment by lightningterror** [comment]
> Is this ready to go or do you need to do more work?

If Gregory is ok with it yea.

**Comment by gregory38** [comment]
Please put a macro for those debug message. 

Potentially, it could be a good idea to keep ps_sel.fbmask logic to print a warning in debug build. You should add that rendering is still bad in the commit message.
The game writes only a couple of bits of the colors.
* Old code was write nothing
* New code is write all bits
Both solutions are wrong. Even if the new one is potentially "better".

**Comment by gregory38** [comment]
There are a bunch of macro at the bottom of `stdafx.h`. Gl main print function is `GSDeviceOGL::DebugOutputToFile`

What we need to do
* Create a global logger object with inheritance so it could dispatch the log to the good API (GL/Dx)
* Instantiate an object pointer in GS.cpp
* Then add handy macro that will call the logger object. Macro will save some typing and allow to remove code in release build without adding `ifdef` everywhere.

For the interface of the logger object it is a bit complicated. I propose that we use the [gl_spec](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDebugMessageInsert.xhtml) as a base. I don't know others APIs but it is unlikely that we need more. We need a `type`, a `severity` and finally a `message` (that might need to be formatted).

```
enum class LogSeverity {
    notification,
    warning,
    error,
    fatal,
};

enum class LogType {
    texture_cache, 
    gs_register,
    performance,
    not_supported,  
    special_effect,  // typically hle stuff
    info,
};


class GSLog {
   // Depends on the API
  virtual insert_message(enum type, enum severity, const std::string& msg);

public:
   // There are various example of printf formatting. Potentially you can use the format function
   void Insert(enum type, enum severity, const char* fmt, ... );
   void Flush(); // should call  GSDeviceOGL::DebugOutputToFile for gl

  // if enable is false, all message related to type should be discarded. Otherwise we keep them
  // maybe add a similar function for severity. I don't know.
  void Control(enum type, bool enable);
};

class GSLogOGL : public GSLog {
   ...
   do inheritance
   ...
};
```

With those kinds of macros. Potentially, we can hide severity inside the macro, for example gs_register info are always a `notification`
```
LOG_CACHE(LogSeverity::Error, "my_message with integer %i", tex_id);
=> call: g_log->Insert(LogType::texture_cache, ...)
```


I'm well aware that it might sound a complicated project. But it is an interesting project, and you will learn plenty of stuff. Don't hesitate to google a lot :)

**Comment by lightningterror** [comment]
> Edit: potentially we could a separate PR for this one. And things aren't well defined in my brain, feel free to tune it. We just need something generic enough so we can control the message information easily and that will work for both API.

Alright will remove the debug changes and plan them for a future PR, who knows how long it will take :laughing:

**Comment by lightningterror** [comment]
Okay so no regressions spotted, Sly series sees an improvement - no more darker stripes.

@refractionpcsx2 it's all yours, merge it.

**Comment by refractionpcsx2** [comment]
Your wish is my command :)

**Pull request merged**
