### PR TITLE
Removing broken images - Adding new ones 1/2

### PR DESCRIPTION
**Pull request by bositman**
Because changing them with one commit fails for some magical reason -_-

### CODE REVIEW

**Comment by Sarania** [comment]
So doing the same thing in a single commit breaks it, but using two works? Lol. Github is so bad sometimes -.-

**Comment by ssakash** [comment]
I think the placement of the images seem a bit weird, we're having the first set of images below ``Project Details`` section (_which seems fine_) but the next set of images are placed below the ``Notes`` section, I seriously don't understand the reason behind placing them at two different locations.

Maybe it would be better to follow a syntax like this one?

```
Here are some screenshots of PCSX2 playing PS2 games by emulating the PS2 console,

[pictures]
```

**Comment by FlatOutPS2** [comment]
Or just:

`
# Screenshots

[screenshot 1] [screenshot 2]
[screenshot 3] [screenshot 4]
......
[screenshot n-1] [screenshot n]
`

**Comment by ssakash** [comment]
Regarding the screenshots placement, Flatout's suggestion seems better.

On the other hand, I feel the table for the Q&A section seems superfluous and waste of previous vertical space, having the Appveyor, Travis, Coverity status logos at the top without the table would be much better. (Refer the readme of this [**repository**](https://github.com/ssakash/cutechess) for example)

Also that way, it's more easier to check if the latest commit is building properly (or) if Coverity has detected a new defect without scrolling all the way to the bottom of the page. -_-

**Comment by bositman** [comment]
Sure go ahead and modify this PR :P

**Comment by ssakash** [comment]
@bositman 

Updated the PR. By the way, here are some other good screenshots taken from [pcsx2.net](http://pcsx2.net/demo-videos-screenshots/screenshots.html) which could potentially be included to the ReadMe file replacing/without replacing the current ones.

GT4
Grandia3
SOC
P4
VP2
FF

Here are some of my nitpicks on the current screenshots,

* God of War - Don't like the blood spilling around due to Kratos's slash using his weapons, let's remove it?
* Rogue Galaxy - Looks rather bland, could potentially be replaced with the Grandia 3 screenshot.

**Comment by bositman** [comment]
I have around 50 good screenshots from the website, which are best are mostly a matter of preference. If you remove the gore from god of war, it gets a bit pointless don't you think? :P Anyway I could find one of my others without the blood if you think that matters

**Comment by FlatOutPS2** [comment]
Why not replace the 18+ violence of GOW2 with a 2D game screenshot. Both 2D games that were there before have been replaced by 3D games. :p

**Comment by bositman** [comment]
You can have GOW2 screenshots without gore. GOW1 and 2 are some of the most known PS2 games which most users will want to play. So why have 2D games instead of 3D games? You can argue forever, since as said before it's a matter of preference. I didn't choose judging by my preference, but by the game's popularity on the PS2 (and exclusivity, ie stuff people would use a PS2 emulator for.)
If you can get better ones, go ahead.

**Comment by FlatOutPS2** [comment]
Actually, all of the games you choose are either rereleases/HD ports or weren't exclusive at the time...

**Comment by turtleli** [comment]
As an alternative opinion: do we need screenshots in the readme?

**Comment by FlatOutPS2** [comment]
> As an alternative opinion: do we need screenshots in the readme?

Other emulators PPSSPP and Dolphin do not haven any on their github pages either, so we could follow suit.

**Comment by bositman** [comment]
Lol? Which one wasn't PS2 exclusive? Almost everything has an HD re-release these days....Anyway I always like checking out some screenshots of what a project can do when viewing the github page, I think it's nice.

**Comment by ssakash** [comment]
I also think it's nice to have the screenshots, livens up the readme file in my humble opinion.

**Comment by FlatOutPS2** [comment]
> Lol? Which one wasn't PS2 exclusive? Almost everything has an HD re-release these days....Anyway I always like checking out some screenshots of what a project can do when viewing the github page, I think it's nice.

The DBZ one. 

Let's just replace the Rogue Galaxy screenshot with the Persona 4 one, which was also exclusive(at the time) and popular. And find a good goreless GOW screenshot, then just merge and be done with it. :p

**Comment by gregory38** [comment]
I want screenshot. And yes bloodless for kid.

**Comment by ssakash** [comment]
@bositman 

Any update on this? I don't think it's ideal to leave the main page with broken image links for too long. ;)

**Comment by gregory38** [comment]
@bositman @ssakash can I squash your change and merge it.

**Comment by ssakash** [comment]
> @bositman @ssakash can I squash your change and merge it.

Well, I'm still highly against including the current GOW2 picture. It would be nice to either remove it (or) replace it with a screenshot without gore. After that's done, I don't see any reasons to delay the merge.

**Comment by FlatOutPS2** [comment]
We could consider replacing GOW2 with a different game, like GT4. As currently all the games are action adventures/RPG's.

What about this:
gt4

**Comment by ssakash** [comment]
> What about this:

Would've been perfect if it weren't for the ``Replay`` icon at the top left. :P

**Comment by FlatOutPS2** [comment]
> Would've been perfect if it weren't for the Replay icon at the top left. :P

The same goes for several of the current selections. And it's not that hard to avoid it :P
gt4

**Comment by gregory38** [comment]
So it can be added. Honestly the replay, can be tuned later.

**Comment by bositman** [comment]
So what do you need from me to close this PR? I thought this would be a 5 min job and you turned it into the middle-eastern :P

**Comment by gregory38** [comment]
Boys and me want a picture without blood. Otherwise we push this PR and someone will fix it later.

**Comment by FlatOutPS2** [comment]
> Boys and me want a picture without blood.

I actually want to replace at least one game(GOW would be an easy pick to replace) with a game from a different genre, as it's all action adventures/RPG's.

And as @ssakash mentioned the Rogue Galaxy screenshot isn't very good. It could be replaced by the Persona 4 one posted above as it's one of the better looking available screenshots.

**Comment by bositman** [comment]
OK I'll let you guys decide and slip away from this :P

**Comment by gregory38** [comment]
I let people asks a PR to improve the bloody image.

**Comment by FlatOutPS2** [comment]
You could've at least squashed the commits...

**Comment by gregory38** [comment]
I wanted to do it. But bosit comment said it doesn't work in 1 shot. In doubt, I kept it in mulitple commit.

**Comment by FlatOutPS2** [comment]
Wouldn't it then still be fine with just the two latest commits?

**Pull request merged**
