### PR TITLE
GameDB: God of War 2 mipmapping fixes

### PR DESCRIPTION
**Pull request by JordanTheToaster**
### Description of Changes
Fixes missing godrays and likely other effects throughout the game.

Before:
God of War II_SCUS-97481_20240429184048

After:
God of War II_SCUS-97481_20240429184051

### Rationale behind Changes
Godrays look nice.

### Suggested Testing Steps
Make sure CI is happy boi.

### CODE REVIEW

**Comment by Filoppi** [comment]
I suppose it would be possible to fix the issue highlighted here in the same way:
https://wiki.pcsx2.net/Burnout_3:_Takedown
> Street directions are visible further than they should in Hardware mode at higher resolutions
image
where basically these yellow arrows that are used to outline the edges of the track always end up using their highest resolution mip map, but the intensity (alpha transparency) of the arrow changes as mip maps get higher resolution, so when playing at a higher output resolution (with the HW renderer) you always see them from a distance, even if you were not supposed to.
I suppose there's a way to find their texture hash and force them to use the original mip map they would have used at each camera distance?
Sorry, I'm new to pcsx2.

Dolphin addressed this issue like this:
https://dolphin-emu.org/blog/2017/11/03/dolphin-progress-report-october-2017/#50-5745-add-heuristic-for-detecting-custom-mipmaps-by-tomcc
https://forums.dolphin-emu.org/Thread-dolphin-custom-texture-mipmaps

**Comment by JordanTheToaster** [comment]
> I suppose it would be possible to fix the issue highlighted here in the same way: https://wiki.pcsx2.net/Burnout_3:_Takedown

Burnout 3 has had mipmapping automatically for almost 2 years now.

**Comment by Filoppi** [comment]
So does that mean that issue is now fixed in HW rendering mode?

**Comment by JordanTheToaster** [comment]
> So does that mean that issue is now fixed in HW rendering mode?

yes

**Pull request merged**
