### PR TITLE
Add Disc Swap Support

### PR DESCRIPTION
**Pull request by seta-san**
fldef did a lot of the work

### CODE REVIEW

**Comment by seta-san** [comment]
> You reformatted an entire file which makes this pretty much impossible to review.

sorry. i didn't realize that happened. i picked it up after fldef gave up. how would i fix this?

**Comment by tadanokojin** [comment]
Probably best just to delete the commit, reapply your changes, and commit it again but making sure that you don't reformat the file when you save it.

The build is failing because you (or rather fldef) made a function `static` which is also `extern`. This doesn't make any sense.

**Comment by RedDevilus** [comment]
Could be easier to just get the master files and squash and then apply the changes.
Also the branch seems to be gone.
image

**Comment by fldef** [comment]
The fixes were not complete and included various known-breaking changes. I apologize for the confusion.

**Pull request closed without merging**
