### PR TITLE
pcsx2: forbid negative index of array in case of register allocation failure

### PR DESCRIPTION
**Pull request by gregory38**
CID 146870 (#1 of 1): Negative array index write (NEGATIVE_RETURNS)
5. negative_returns: Using variable xmmreg as an index to array ...

Open discussion: how to handle correctly bad register allocation?
    Currently negative index is returned and a message printed. It means
    we need to propagate the index check everywhere in order to not use it.

    I suspect that Instruction Generation is more or less corrupted so
    potentially we could just fire an exception.

### CODE REVIEW

**Comment by gregory38** [comment]
@refractionpcsx2 what do you think about it?

**Comment by refractionpcsx2** [comment]
I was thinking about that, then crying, then backing away slowly. 

The solution I was pondering was to forcefully free up the least  recently used xmm and get it to use that.  I mean this isn't a scenario that comes up often, if at all, so it's more for making coverity happy

**Comment by gregory38** [comment]
```
I was thinking about that, then crying, then backing away slowly. 
```
You mean the exception?

```
The solution I was pondering was to forcefully free up the least recently used xmm and get it to use that. I mean this isn't a scenario that comes up often, if at all, so it's more for making coverity happy 
```
Yeah, I'm thinking the same. However, current behavior is 100% sure crash if is happen.

**Comment by refractionpcsx2** [comment]
> You mean the exception?

Well, about that yes, and the potential mess of the fix to make it work properly xD



> Yeah, I'm thinking the same. However, current behavior is 100% sure crash if is happen.

Indeed, I think that's the best possible solution for this scenario to avoid crashing or breaking the emulation.

**Comment by refractionpcsx2** [comment]
I've been looking at the code for this and there doesn't really look like a way this could be reached unless some code does happen to use all 8 XMM's, which is unlikely considering the max will probably be a Source, Target and Destination plus maybe 2 Temps in a single op.  However in the case there is a failure to get a temp reg, it looks like there are alternative codepaths in place to handle that, it was just the allocation would have crashed if it continued how it did

**Comment by refractionpcsx2** [comment]
@gregory38  could do with your feedback on what I said earlier so we can conclude this :)

**Comment by gregory38** [comment]
Hum, personnally I'm fine to put an assert for debug and to try to free a register.

**Comment by refractionpcsx2** [comment]
Thats the problem, by this point it has already tried to find a free register which isn't required by the current opcode, if it gets this far somebody has made poor use of the XMM registers :P It's seriously unlike this will be reached and if it does, the code that calls it has a backup plan to not use temp regs and do things the slow way.

**Comment by gregory38** [comment]
There are also mmx/x86 reg (just checking my pr). What do you suggest exactly? Leave current code?

**Comment by refractionpcsx2** [comment]
Yeh, I'd suggest putting your returns in to stop it trying to allocate negative numbers, and that should be fine, if it crashes then due to other code not handling it (which I believe there is very little of) then somebody has coded something in the recompiler very badly :P

**Comment by gregory38** [comment]
Ok. I will also add some assertions to spot potential issue in debug build.

**Comment by refractionpcsx2** [comment]
sounds good :)

**Comment by gregory38** [comment]
So x86 and mmx already have an assert so I just did the same for the xmmreg. You can merge it, if it ok with you.

**Comment by refractionpcsx2** [comment]
Fine,. ill take responsibility :P

**Comment by gregory38** [comment]
So, I updated the coverity report. Lots of new issues (~ +70) appears because of the -1 propagation to caller functions. So what do we do?

**Comment by refractionpcsx2** [comment]
hmmm. ill look in to it and let you know

**Comment by gregory38** [comment]
Ok cool.

**Comment by gregory38** [comment]
Won't it be possible to throw an exception and to catch it in ```recompileNextInstruction``` ? Just asking because I really don't know very much on the recompiler.

**Comment by refractionpcsx2** [comment]
hmm, not sure, it goes through a few functions before coming back to then, I guess it could be done.  What I was pondering is if it returns -1 then call the interpreter instead.

**Comment by gregory38** [comment]
Yes it is a good idea. Would it be hard to implement?
The exception was to avoid the propagation of the -1 to all functions. I dunno if we have a single entry points that call the recFUNC stuff.

**Comment by refractionpcsx2** [comment]
we have some code in there to flush the rec and drop back to the interpreter for 1 op, don't worry about that :)  Just look at t hat PMTHL or whatever it was where the rec obviously can't do it lol

**Comment by gregory38** [comment]
Sure, but it was sure that you didn't need to call a function for each opcode :p
By the way, you own me a deep presentation of the recompiler. Maybe one day I will start the port to a new arch.

**Comment by refractionpcsx2** [comment]
I'll help where I can, I've learnt mostly through learning how recompilers work and deciphering the code that's there.

**Comment by willkuer** [comment]
Sorry for being slightly offtopic but as you are yourself i just ask: was writing the rec basic structure (not small bugfixes) a one man show or can something like that be written in a team? If one man show can you tell who did it?

**Comment by refractionpcsx2** [comment]
It's pretty much a one man show, at least until you have the emitter and possibly rec optimizations in, when it comes to translating the opcodes that can be done by multiple people.

**Pull request merged**
