### PR TITLE
crc hack for Raw Danger! (Zettai Zetsumei Toshi 2 US)

### PR DESCRIPTION
**Pull request by ssakash**
the following CRC hack also fixes the Graphical glitches on the US version of the game. hence, added it to the list. apparently the PAL version also can be fixed but, I don't know it's CRC.

### CODE REVIEW

**Comment by avih** [comment]
Did you test it yourself with `Raw Danger!` ? if not, how do you know that the Japanese version CRC hack works also with the US version?

How do you know that "apparently the PAL version can be fixed"? Do you know for a fact that there is even an issue with the PAL version?

**Comment by ssakash** [comment]
I did test the CRC hack with the US version and it fixes some post processing bugs. I had recently found out that, the japanese version didn't share the similar problem. that's when, I tested it with the CRC hack and found out that, it works well.

I don't have the PAL version on my possession, that was just a hunch, it may have the same problem. but, I can't figure it out since, I don't have the game.

**Comment by avih** [comment]
Please add a comment at the code like this:
`	{0x2905C5C6, ZettaiZetsumeiToshi2, US, 0},  // Raw Danger!`

Please change the commit title to: `crc hack for Raw Danger! (Zettai Zetsumei Toshi 2 US)` and remove the rest of the text.

**Comment by ssakash** [comment]
Done.

**Comment by avih** [comment]
Squash them into a single commit, and change the commit message to `crc hack for Raw Danger! (Zettai Zetsumei Toshi 2 US)`

**Comment by avih** [comment]
@ssakash, I meant the commit title/message, not the github title of the PR.

If you're not sure how to do that, I can do that for you. Just let me know.

**Comment by ssakash** [comment]
yeah, I will leave it to you.

**Comment by avih** [comment]
Thanks. 45e2fd9204db1489972af60b051eb1777c0fd4fa

**Comment by avih** [comment]
> yeah, I will leave it to you. I did squash them using the git rebase command and change the commit tittle but the changes are not taking place on Github, something is wrong on my side. it would be better if, you could do it for me.

Did you force push (`push -f`) after you made the changes? If you make changes to commit which you already published, then normal `push` will not work, and you will need to force push. That's OK when no one is tracking your branch which you only use for a PR, but usually it's not a good practice on "normal" public branches.

**Comment by ssakash** [comment]
That makes sense, I did the normal push. Thanks for the Information :smile:

**Pull request closed without merging**
