### PR TITLE
VMManager: Auto switch to 16:9 when ws patches are enabled/found

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Automatically switches the aspect ratio to 16:9 when set to auto, and widescreen patches are found for the running game.

### Rationale behind Changes

Saves manually setting the aspect ratio as well.

### Suggested Testing Steps

Test games with WS patches with AR set to auto.

### CODE REVIEW

**Review by JordanTheToaster — APPROVED** [review]

**Comment by Rex000** [comment]
That's really convenient. I believe the No-Interlacing patches require the Deinterlacing setting to be set to "None". If the same could be done for those too then that would be another nice convenience.

**Comment by refractionpcsx2** [comment]
It already doea.

**Comment by Rex000** [comment]
Really? I saw a tutorial on YT where they said you need to turn the Deinterlacing setting off manually for No-Interlacing patches. Maybe they didn't now about this.

**Comment by refractionpcsx2** [comment]
Maybe in future ask is instead of some random YouTube video.

**Comment by Rex000** [comment]
Ok I remember now it wasn't a YT video but a PCSX2 forum post:

https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=624309#pid624309

**Comment by RedDevilus** [comment]
> Ok I remember now it wasn't a YT video but a PCSX2 forum post:
> 
> [forums.pcsx2.net/Thread-No-interlacing-codes?pid=624309#pid624309](https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=624309#pid624309)

That's been changed recently to automatically switch to None if needed.

**Pull request merged**
