### PR TITLE
Gsdx micro optimization

### PR DESCRIPTION
**Pull request by gregory38**
Various small optimizations and cleanup. Except a big speed boost on  FULL blending accurate mode.

### CODE REVIEW

**Comment by gregory38** [comment]
@ramapcsx2 could you test the blending speed on rule of roses. The game still requires the FULL mode but maybe it is a bit faster now.

**Comment by bositman** [comment]
Blending none gave me 190 FPS, blending full 120 FPS

**Comment by gregory38** [comment]
How many fps for high? The new code detect the alpha value to only enable the "slow algo" when alpha is above 128. If the game always uses the full range of alpha value, full will be similar to ultra. I'm afraid it does.

**Comment by ramapcsx2** [comment]
The optimization is worthwhile in any case.
But it's a good idea to test this with a fitting GS dump that shows a significant slowdown with full or ultra blending. @bositman Could you create one?

**Comment by gendouhydeist** [comment]
VP Graphic glitch appear on #764

**Pull request merged**
