### PR TITLE
Windows: switch to wxWidgets 3.0

### PR DESCRIPTION
**Pull request by turtleli**
This makes PCSX2 on Windows use wxWidgets 3.0.

Switching to wxWidgets 3.0 causes error messages to appear in the console when it attempts to get the PS2EsetEmuVersion symbol for each plugin. This only exists in Windows GSdx, so every other plugin will generate error messages. I've decided to suppress the error messages since it's harmless if it fails to find the symbol.

### CODE REVIEW

**Comment by ADormant** [comment]
What about WxWidgets 3.1.0? https://github.com/PCSX2/pcsx2/pull/595

**Comment by turtleli** [comment]
Short answer - I'm not doing it?

Long answer:
 * 3.1.x is a development branch, 3.0.x is a stable branch.
 * Linux distros don't provide 3.1.x packages, so porting PCSX2 on Linux to 3.1.x isn't possible without causing users unnecessary hassle. I could compile my own packages for dev purposes, but that's a hassle for me as well.
 * I want both Windows and Linux to use the same version. At the very least, I feel it's easier to find and fix bugs that way.
 * Therefore 3.0.x .

**Comment by turtleli** [comment]
Don't merge yet - Small bug in where it places build files...

**Comment by turtleli** [comment]
Should be fixed now, but do check I'm not still being a right tool.

**Comment by ramapcsx2** [comment]
Testing on Win7 x64 here.
- Everything works as expected, all GUI commands respond, I feel the GUI thread is more responsive?
- GS window now starts up briefly in white before the first GSdx data comes in
- pcsx2.exe went from 6.4 to 8.9 MB

So far it looks great :)

**Comment by gregory38** [comment]
Yes, 3.1 is out of the scope.

**Comment by gregory38** [comment]
@bositman could you do some test too?

@ramapcsx2 did you test the debugger window? I remember that I got some issue on linux with the UTF8 string.

**Comment by ramapcsx2** [comment]
@gregory38 I see no issues with any of the GUI windows.

**Comment by turtleli** [comment]
Might want to hold on a merge again.. shouldn't affect too many people, but if someone uses spaces in the directory pcsx2 is in wxConfig30 will fail. Spacesareawfulthings.

Probably should mention SPU2-x also increases in size too.

**Comment by turtleli** [comment]
Should be fixed.

**Comment by refractionpcsx2** [comment]
Just so we don't look like Rockstar, is this okay with non-ascii characters in directory names too? :P

**Comment by turtleli** [comment]
Nope ;_; 

It never was though.

**Comment by refractionpcsx2** [comment]
I'm sure the current version supports Japanese/Chinese characters :/

**Comment by turtleli** [comment]
I tried D:\pcsx2さ on master. It died on wxConfig28.

**Comment by refractionpcsx2** [comment]
Lame :(  So do we not support unicode?

**Comment by turtleli** [comment]
Dunno. Actually, I'll play around later, since it's using full paths (not my decision), I'll try relative paths instead, should(?) work better.

**Comment by refractionpcsx2** [comment]
hopefully lol, would be a good addition to bring along with wx3 :)

**Comment by ramapcsx2** [comment]
Japanese Kanji worked in the iso picker as game file names at least.
( W:\ps2games\漢字 kanji.ISO.gz works fine )

**Comment by turtleli** [comment]
I think it's just the build system on Windows that can't cope in its current form. Or were we talking about different things to begin with?

**Comment by turtleli** [comment]
I've made Visual Studio use relative paths for wxConfig30, so wxWidgets should build regardless of directory path.

pcsx2 and the plugins however don't build with non-ascii characters in the directory path due to the custom build commands, but that's out of scope for this PR. It is possible to make it build though, I had pcsx2 build after some changes (if anyone wants to do this, I'd be happy to put up a branch that you can take a look at, I feel I've had enough of VS project files for a while).

**Comment by Pistachioman** [comment]
Can't you just slap a 'chcp 65001' at the start of the custom build commands to change the code page?

**Comment by turtleli** [comment]
I didn't try that method, I just altered stuff to use relative paths to completely avoid the issue.

Made another change. This makes sure the correct manifest is included regardless of the architecture it's compiled for. Not all that useful right now, but perhaps useful in the future (64-bits).

**Comment by gregory38** [comment]
Are we happy with this PR?

**Comment by refractionpcsx2** [comment]
Yes but shouldn't we look in to the debugger random crashing thing before we merge? No sense in covering up the problem without fixing it.

**Comment by gregory38** [comment]
Just saw the thread actually. I let you manage ;)

**Comment by refractionpcsx2** [comment]
I think @turtleli is debugging from the look of things :)

**Comment by turtleli** [comment]
Feel free to debug in my place ;) Yeah, still trying to find the problem, I think I'll just throw in a boatload of Console/emulog writes, I'm bound to find the problem that way.

Perhaps this should get wider testing in the meantime? I wonder whether this solves any other bugs (i.e. Arabic region bug). Can rebase if necessary

**Comment by refractionpcsx2** [comment]
It's a real bugger cos it has never crashed for me on startup, not once lol

**Comment by turtleli** [comment]
Yeah, doesn't crash for me either.

**Comment by ramapcsx2** [comment]
Same here; no crashes.
Going over the history of the debugger might help find the issue.
It's all on Github, maybe half a year ago or so.

I'm for merging this branch now btw. It happens to cover up the problem with the debugger crash but if we want to debug that, we can use a wx2.8 revision. It's no reason to hold development back.

**Comment by refractionpcsx2** [comment]
OK im cool with that :)

**Comment by gregory38** [comment]
So let's merge it. @turtleli very good jobs :+1:

**Comment by bositman** [comment]
Good job man :) *waits for mass panic with new bugs on forum* :P

**Comment by bositman** [comment]
---------------------------
wxWidgets Debug Alert
---------------------------
..\..\src\common\string.cpp(1186): assert "c < 0x80" failed in wxString::FromAscii(): Non-ASCII value passed to FromAscii().
Do you want to stop the program?
You can also choose [Cancel] to suppress further warnings.
---------------------------
Simply tried to run an ISO

**Comment by gregory38** [comment]
What is the name of your ISO (and directory?)

**Comment by bositman** [comment]
c:/mine/PCSX2/Samurai Warriors 2 (Europe).iso
PCSX2 path is c:/mine/PCSX2/pcsx2-v1.3.1-814-gf4e881a-windows-x86

**Comment by turtleli** [comment]
It's probably not ISO name related.

I don't know what settings you are using, but are you using folder memory cards or SPU2-X portaudio?

**Pull request merged**
