### PR TITLE
Greg/gsdx grow buffer 2441 v3

### PR DESCRIPTION
**Pull request by gregory38**
Replace #2566

### CODE REVIEW

**Comment by lightningterror** [comment]
It works but I'm seeing a couple of new warnings.

```1>d:\my documents\github\masterpcsx2\pcsx2\plugins\gsdx\GSVertexArrayOGL.h(60): warning C4244: '=': conversion from 'double' to 'std::size_t', possible loss of data (compiling source file GSTextureCacheOGL.cpp)
1>  d:\my documents\github\masterpcsx2\pcsx2\plugins\gsdx\GSVertexArrayOGL.h(51): note: while compiling class template member function 'GSBufferOGL<4>::GSBufferOGL(GLenum,std::size_t)' (compiling source file GSTextureCacheOGL.cpp)
1>  d:\my documents\github\masterpcsx2\pcsx2\plugins\gsdx\GSVertexArrayOGL.h(234): note: see reference to function template instantiation 'GSBufferOGL<4>::GSBufferOGL(GLenum,std::size_t)' being compiled (compiling source file GSTextureCacheOGL.cpp)
1>  d:\my documents\github\masterpcsx2\pcsx2\plugins\gsdx\GSVertexArrayOGL.h(234): note: see reference to class template instantiation 'GSBufferOGL<4>' being compiled (compiling source file GSTextureCacheOGL.cpp)
1>  ```

**Comment by lightningterror** [comment]
I experienced a driver crash when closing the application at that scene once, I'm not sure if that was just a coincidence or some kind of related issue.

**Comment by gregory38** [comment]
Hum, I'm not 100% sure that I can delete the buffers without a flush of the pipeline. Otherwise I don't know

**Comment by gregory38** [comment]
Do you manage to reproduce the crash ? I could add a glFinish() but we need to know if it is useful.

**Comment by lightningterror** [comment]
No I wasn't, it only happened once and can't reproduce it again so I guess it was just a coincidence.

**Comment by gregory38** [comment]
on which code did you get the crash by the way ? This one ?

**Comment by lightningterror** [comment]
Yes, first two commits.

**Comment by lightningterror** [comment]
I gave it a go after a fresh reboot and still wasn't able to replicate that crash it so I guess it was just a coincidence that time.

Works good and the warnings have been silenced :+1:

**Comment by gregory38** [comment]
Seriously github why didn't you like my force-push...

**Comment by gregory38** [comment]
closed via b6db0a3c3042d181ea548c0ee322a794ef152130

**Pull request merged**
