### PR TITLE
GameDB: Add fixes for Shadow of the Colossus and Puchi Copter 2

### PR DESCRIPTION
**Pull request by Buzzardsoul**
### Description of Changes
Title.

### Rationale behind Changes
Wander was drifting when charging his sword due to rounding issues. Fixes https://github.com/PCSX2/pcsx2/issues/11528
Puchi Copter 2 was hanging. I created a patch for it. Fixes https://github.com/PCSX2/pcsx2/issues/10380

### Suggested Testing Steps
Not needed. I finished Shadow of the Colossus with it enabled. And tested Puchi Copter 2 for a while for TLB misses and possible hanging.

### CODE REVIEW

**Comment by Buzzardsoul** [comment]
Extremely sorry for the mess. Github is alien to me.

**Comment by Mrlinkwii** [comment]
Was this patch tested ?

**Comment by Buzzardsoul** [comment]
> Was this patch tested ?

Multiple times. I tested it by applying it through the debugger after the freeze occurs, and through the gameindex. Both instances it was working perfectly fine.

**Comment by Buzzardsoul** [comment]
@Mrlinkwii If you guys are apprehensive about this, I can close this pr and let you do what you want to. It's what I prefer cause this is a mess I'm new to.

**Comment by Buzzardsoul** [comment]
Some of them weren't applying in PCSX2. Perhaps I wrote them incorrectly? Regardless, I'll close it and have someone else do prs till I get this right one day.

**Pull request closed without merging**
