### PR TITLE
GS: Adjust interlacing offsets to something more sensible.

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Adjusts the offset for the interlacing when upscaled to be half the upscale amount when in FFMD mode (which uses half height framebuffers)

### Rationale behind Changes
Baldurs Gate DA 2 3D became blurry after #6498 due to me pulling a value out of my butt which I didn't even really think properly about.

### Suggested Testing Steps
Test Baldurs Gate games for blurring

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
@Dreadmoth do you wanna test this?

**Comment by Dreadmoth** [comment]
Testing BGDA, BGDA2, Champions of Norrath, Champions: RTA.
Results seem to vary depending on resolution:

**Native:**  all games clearer UIs than master. Dark Alliance 2 3D is slightly clearer, other games 3D is slightly softer.

**2x, 3x Native:** all games slightly softer than master (UI and 3D)

**4x Native:** all games identical to master

**5x, 6x, 7x, 8x Native:** all games clearer 3D than master. Dark Alliance 2 UI is slightly softer, other games UIs are slightly clearer.

That branch name sounds about right...

**Comment by refractionpcsx2** [comment]
I hate this :( 

When you say softer than master, do you mean pre or post the other PR merging?

**Comment by Dreadmoth** [comment]
> When you say softer than master, do you mean pre or post the other PR merging?

Post merge.

**Comment by refractionpcsx2** [comment]
Okay, Well I've just made some more changes, and it's as clear as it was pre-merge on the "odd" upscales (3, 5, 7), I think this is the best it's gonna get.  The UI isn't clear, but I don't think it was ever going to be, since bilinear clears it right up (looks like native).

**Comment by refractionpcsx2** [comment]
I hate this, just so you know :)

Okay, this is basically back to how it was before I did that last PR, HOWEVER, I think the picture is more consistent at lower upscales, providing a slighly better image.  As seen below with 2x Native

image
image

**Pull request merged**
