### PR TITLE
Update arabic translations

### PR DESCRIPTION
**Pull request by roxas0zero**
hi, i just updated and corrected some of the arabic grammar translations in PCSX2, i hope this helps.

### CODE REVIEW

**Comment by lightningterror** [comment]
Can you update the .mo file as well? It can be auto generated with poedit.

**Comment by roxas0zero** [comment]
sure, i will :) thank you sir.

**Comment by roxas0zero** [comment]
since you will consider merging, let me work on the whole translations and i'll let you know once i'm done. thank you kindly.

**Comment by lightningterror** [comment]
mo files should be placed in `bin/Langs/ar_SA/`

**Comment by lightningterror** [comment]
@roxas0zero Status?

**Comment by roxas0zero** [comment]
i got busy, yes i'm continuing the translations and i'll place it in bin/Langs/ar_SA/

**Comment by lightningterror** [comment]
Are the English string changes needed?

**Comment by roxas0zero** [comment]
no its not, it was automatically changed by poedit

**Comment by RedDevilus** [comment]
Then your poedit settings are wrong. There is a pinned pdf for translators v6 in discord help channel to avoid messing with english strings when saving and compiling.
Here is same link:
https://my.pcloud.com/publink/show?code=kZDH81kZHH9txOzWRSfidhxYhMviSYe30lW7

**Comment by RedDevilus** [comment]
If you followed the guide, just do save and export for the 2 files and it should fix the english strings.

**Comment by roxas0zero** [comment]
all fixed, thank you.

**Comment by lightningterror** [comment]
There are some strings left for translating, do you wanna translate them too or shall I merge it as it is?

**Comment by roxas0zero** [comment]
Yes, is it ok to leave it open until I finish everything?
Thank you

**Comment by lightningterror** [comment]
Go for it.

**Comment by RedDevilus** [comment]
Don't worry i was looking for arabic translator anyway besides we can always let translators do work no matter the stage the development is in. If you feel you need another week or more you can do that. Quality is more important than speed.

**Comment by roxas0zero** [comment]
thank you, i'm really glad i can help.

**Comment by lightningterror** [comment]
Status?

**Comment by roxas0zero** [comment]
yes, please go ahead and merge.
thank you.

**Pull request merged**
