### PR TITLE
GSdx-Windows: Fix Shadeboost text bug

### LINKED ISSUE #2019: GSDX GUI regression
***PCSX2 version:***
Last 1.5 dev

***Description of the issue:***
The GUI (tested on Windows) have a bug in this section:
image
Updating any shade boost value will cause a bug look:

Before updating value:
image

After updating value:
image

***How to reproduce the issue:***
Load pcsx2 , GSDX and goes to the shader configuration section.

### PR DESCRIPTION
**Pull request by ssakash**
Fix a small oversight on my part. (Closes #2019)

### CODE REVIEW

**Comment by MrCK1** [comment]
Damn, you beat me to it. 😛

**Comment by ssakash** [comment]
> Damn, you beat me to it, I had just finished my PR. 

My bad, I wasn't aware that you were working on it. You could've saved both me and you some valuable time if you had mentioned about it earlier. 😛

**Comment by turtleli** [comment]
> Fix a small oversight on my part.

Well, not entirely your fault. I did merge it without testing, which I usually do... oh well.

**Comment by lightningterror** [comment]
I always use shade boost  , dunno why I never noticed it xD

**Pull request merged**
