### PR TITLE
GS: Partial target invalidation option, Z eliding

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Eventually hopefully we can make this the default, but it breaks too much at the moment.

Fixes missing/corrupted textures in True Crime: New York City.
Gets rid of an unnecessary readback in True Crime: New York City.

Stops some offscreen targets from expanding in size.

### Rationale behind Changes

Untitled

### Suggested Testing Steps

Test TC:NYC.

### CODE REVIEW

**Comment by Shoegzer** [comment]
TC: NYC shows a definite improvement with missing textures, though a few issues were observed that don't occur in master:

* Flashing of multi-colored "garbage" textures, randomly and when transitioning from indoors > outdoors
* Seemingly random white texture flashing while moving camera in indoor environments

A few other issues were also observed but may be discounted since they're apparent in master and I assume are not the target of this PR:

* No visible rain effects (raindrops visible as they hit the ground but not in the air) 
* Sun / lens flare appears through buildings as seen here:

pic

Test info:
* OS: Linux Mint 21.1 / kernel 5.19
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070 / driver 525.78
* Graphics settings forced at PS2-native wherever possible, including resolution.  Blending accuracy set to Maximum (very slow) (although no slowdown is observed).

**Comment by refractionpcsx2** [comment]
which of these issues are also present on master?

**Comment by Shoegzer** [comment]
The first two only seem to occur in the PR.  The latter two are also observed in master.

**Comment by refractionpcsx2** [comment]
Sorry, you did say that, my apologies.

**Comment by Shoegzer** [comment]
No worries on the misunderstanding.

I'm happy to provide GS dumps if it can help, though I haven't done that before.  I assume I just do a single-frame GS dump when I get to a problematic scene?  Also I don't believe I can get dumps for the first two issues as they occur randomly and too fast to catch, unless there's a way I'm not aware of?

**Comment by refractionpcsx2** [comment]
You can do single frame dumps for the most of them, but if the others kinda flash one frame, you could do a multi-frame dump, which is ctrl+shift+f8 by default, but you can chance it to something simpler in the hotkey setups if you wish,  once you manage to grab it upload the dump here :) I recommend not doing more than a couple of seconds at a time, they can get kinda big lol

**Comment by Shoegzer** [comment]
Hey thanks. I also found [this](https://github.com/PCSX2/pcsx2/wiki/How-to-Create-a-GS-Dump) which helps, though a bit outdated (GS dump is actually in `Tools`, rather than `Debug`). I set a hotkey for a multi-frame dump (it wasn't previously defined), but after pressing the hotkey, it created a zst archive and corresponding png in the /snaps directory as soon as I started capturing, so I think there's an issue with pcsx2 confusing single- and multi-frame dumps?

In any event, here are the single-frame dumps for the latter two issues, hope they help:

* No visible rain effects (raindrops visible as they hit the ground but not in the air): [norain.zip](https://github.com/PCSX2/pcsx2/files/10829268/norain.zip)

* Sun / lens flare appears through buildings: [visiblesun.zip](https://github.com/PCSX2/pcsx2/files/10829283/visiblesun.zip)

**Comment by refractionpcsx2** [comment]
Thanks :)

**Comment by stenzek** [comment]
Sun isn't getting fixed any time soon.

Game shuffles the depth (Z24) into the upper 8 bits of the buffer, then goes back to using it as a normal depth buffer for a couple of hundred draws, then pulls it out with P8H to draw to the alpha of the CLUT texture used for the sun.

TC can't handle this, not without allowing the same base pointer to be used in both colour and depth modes with unshared bits. Which is a can of worms.

**Comment by Shoegzer** [comment]
That's okay of course, and I understand lens flare issues are particularly tough problems to solve in this and other titles given texture cache limitations as you mentioned.  I'm just reporting the issues and glad to help wherever I can.  Thanks for the fix!  Better all the time.

**Comment by Shoegzer** [comment]
I got "lucky" as pcsx2 froze while also displaying garbage textures, so I did a single-frame GS dump which you can get [here](https://github.com/PCSX2/pcsx2/files/10832276/pixeljunk.zip).  This was taken from a build of pcsx2 made after this PR was merged.  Also, since it's merged I can open up a new issue on this if you think it's more appropriate there.

**Comment by refractionpcsx2** [comment]
I guess not as luck as you thought

image

**Comment by Shoegzer** [comment]
That's too bad. Is that from the gs dump itself? At least the .png from the zipfile I attached shows the issue, though I guess it's of limited value if the gs dump doesn't reflect the same.

**Comment by refractionpcsx2** [comment]
yes I ran your gs dump :(

**Comment by Shoegzer** [comment]
Okay, that's what I thought.  I'll keep trying to capture something, no promises..

**Pull request merged**
