### PR TITLE
Sw blending postprocessing

### PR DESCRIPTION
**Pull request by gregory38**
This PR adds a new combo box to replace accurate blending option. It also round differently the value in the shader to be more SW alike.

I think it is possible to accelerate colclip operation in the future with float texture or atomic. Unfortunately I didn't have any success currently. So I will postpone it to a later PR.

@ssakash do you have the code to
1/ add the new combo box
2/ remove the old aggressive check box

### CODE REVIEW

**Comment by ssakash** [comment]
I have the patch for the new combo box and removal of the other accurate options. though, should I also PR a new commit for the removal of aggressive checkbox in the following branch ? I haven't done it yet. (though should be easy, just the removal of the CONTROL in Resource file)

also, I sent the patch to @refractionpcsx2 for cross checking it. I'd push it to the branch after ref takes a look at it.

**Comment by gregory38** [comment]
Could you post the link to your branch? I will cherry-pick the commit. Yes add a commit that remove the box.

**Comment by refractionpcsx2** [comment]
Sorry I didn't look at the patch last night, can't check tonight as I'm out, but saturday looks like the day!

**Comment by ssakash** [comment]
@gregory38 
https://github.com/ssakash/pcsx2/tree/patch-40

compiled build link - https://www.dropbox.com/s/9kgsh5wuwi1gvb8/patch%2040.7z?dl=0

**Comment by gregory38** [comment]
You need to keep accurate date. It is a completely separated option

**Comment by gregory38** [comment]
@ssakash sorry to urge you.

I would like to merge the branch as soon as possible so the new opion land in time for next Ubuntu release. They will freeze it soon. Besides, I have another round of update (to accelerate the high level). So could you update your patch based on the above feedback. Thanks you.

**Comment by ssakash** [comment]
Yeah, I will get to it. sorry for the delay, I wasn't on git yesterday. just looked at the patches and suggestions, will update it soon. :)

**Comment by ssakash** [comment]
@gregory38 
here's the new branch with the updates: https://github.com/ssakash/pcsx2/tree/patch-41

also about the duplicate string, It's recommended to use 'CB_ADDSTRING' when working with combo box on resource files for better sorting. also it would be conflict for future CBS_SORT implementation. I think the current implementation is fine :)

**Comment by gregory38** [comment]
I mean the GSdx API.

```
ComboBoxInit(IDC_..., m_gs_acc_blend_level, theApp.GetConfig("....", 1));
```

```
			if(ComboBoxGetSelData(IDC_...., data))
			{
				theApp.SetConfig("....", (int)data);
			}
```

**Comment by ssakash** [comment]
I see, didn't know about these functions. by the way, updated the branch. please check it out : https://github.com/ssakash/pcsx2/tree/patch-41

**Comment by gregory38** [comment]
Thanks I merged your commit in a branch and fix a potential regression. Time to test it :)

**Comment by gregory38** [comment]
@prafullpcsx2 I found a regression that I will fix tonight.

**Comment by gregory38** [comment]
@refractionpcsx2 could you prove a build of this branch for prafull and others?

**Comment by refractionpcsx2** [comment]
Sure here you go http://www.filedropper.com/gsdx32-sse2-postproc2707

**Comment by refractionpcsx2** [comment]
Looks to work okay (the gui stuff) Tidy'd the options up a bit tho, it was all over the place :P

**Comment by refractionpcsx2** [comment]
Games seem to be fine, GoW2 looks nice apart from the bar across the middle of the screen :)

**Comment by ssakash** [comment]
> Looks to work okay (the gui stuff) Tidy'd the options up a bit tho, it was all over the place :P

Yep, it was quite crowded. :p that's why I suggest a landscape dialog bot.

**Comment by gregory38** [comment]
```
Games seem to be fine, GoW2 looks nice apart from the bar across the middle of the screen :)
```
What do you mean? Is it a regression, did you enable CRC to minimum, the game needs it.

```
 And of course you know about the SotC glitchyness
```
Could you try to add a 
```
glFinish();
````
in the end of the GSRendererOGL::SendDraw function?

**Comment by refractionpcsx2** [comment]
Ill try later, I'll probably be in about 11pm tonight, so ill give it a go.

As for GoW2 I didn't try that no, ill give it a shot.

**Comment by gregory38** [comment]
Ok. If you can also test the hdr-colclip branch. I change a barrier, maybe it is the reason. Still on this branch, I need another test ;)

There is a glFinish that kill my perf in the code (bottom of GSRendererOGL). It feels like a driver bug could you test blending unit high with/without the glfinish. Check SotC shadows, you will quickly see the issue.

**Comment by refractionpcsx2** [comment]
I don't think I'll do all that tonight :P But I'll certainly look at it.

**Comment by gregory38** [comment]
sure :)

**Comment by prafullpcsx2** [comment]
@gregory38 I am downloading VS2013 iso today and also making room on my HDD so most probably by tomorrow I will have things setup to compile on my own. Then I can quickly test out your new changes.

**Comment by gregory38** [comment]
That a great news for Ref ;)

**Comment by refractionpcsx2** [comment]
wahoo! \o/ :P

**Comment by refractionpcsx2** [comment]
OK the screen mess on SotC is gone with the hd-colclip branch and i see what you mean about it being corrupted without the glFinish in there.  Is the behaviour different on AMD cards then?

**Comment by gregory38** [comment]
Cool for the corruption. I think the improvement come from the barrier commit so I integrate it to this branch.

Yes colclip == 1is the old broken method. The HDR (as high dynamic range) version is much better but slower (mostly due to the glfinish).

I asked some help on the openGL forum in case I did something wrong. In the meantime, we need to find someone with an AMD GPU to test the behavior. On my side, I will try to replace the glFinish primitive by https://www.opengl.org/wiki/GLAPI/glWaitSync . I hope it will be lighter.

**Comment by gregory38** [comment]
@refractionpcsx2 could you give a quick test to ensure corruption is gone with this branch (sw-blending-postprocessing). If it is good, I will merge it :)

**Comment by gregory38** [comment]
Ok. A good guy confirms me that corruption is gone on suikoden. I will rebase the branch to squash a couple of commit and then I will merge it.

**Comment by refractionpcsx2** [comment]
So shall i check the SotC corruption on master or just be happy that it'll be sorted with the hdr-colclip branch? :p

**Comment by ssakash** [comment]
A good guy already tested it. :)

**Comment by gregory38** [comment]
Master must be fine now. I'm currently cleaning the hdr branch. I will drop the old colclip algo, code is really a complete mess.

**Comment by karasuhebi** [comment]
>In the meantime, we need to find someone with an AMD GPU to test the behavior.

What do you need me to test? Is it merged to master by now?

**Pull request closed without merging**
