### PR TITLE
cdvd:iso: Use Primary Volume Descriptor to find DVD layer break

### LINKED ISSUE #799: [Feature request] Cache failure to find a layer break
Up until now when PCSX2 tries to read an ISO file >4,3 GB with the internal ISO loader, we initiate a layer break search, which searches the whole ISO file for it. 

If not found, the search can take even a whole minute when PCSX2 looks unresponsive.

Since there are several ways to have ISO files above 4,3 GB and without a layer break (like mods, undubs etc), each time a user tries to boot such an ISO file, they have to wait for PCSX2 to search the whole file and then fail.

I suggest we cache the failure in the LayerBreakCache.ini just like we cache the success (although we won't be storing any sector obviously) so in the next boot, the user will not have to wait for the whole ISO to be read again, with the appropriate console log message.

Relevant code:
https://github.com/PCSX2/pcsx2/blob/9fa473a57de5592ed39f74a1ee2f39587522132e/pcsx2/CDVD/CDVDisoReader.cpp#L161

### PR DESCRIPTION
**Pull request by turtleli**
Needs lots of testing. I tried it on my ISOs and it seems to work, but I only have one DVD9 game (GT4), the rest are single layer.

Changes:
 * Uses a non brute force approach to find the DVD layer break address.
 * No longer caches the layer break address.

The DVD layer 0 sector count is stored in the Volume Space Size field of the Primary Volume Descriptor on DVD layer 0. This value is the same as the total sector count for a single layer DVD and the first layer 1 LSN of a dual layer DVD. So we should be able to use that to quickly find the layer break instead of starting from the middle of the ISO and searching outwards for the layer break (which may not exist).

Fixes #799

### CODE REVIEW

**Comment by bositman** [comment]
Tested all double layered ISOs I have, all checked out fine. Also tested games after the kayer break (like GoW 2) to make sure data is read correctly and had no problem.
Here are my results:

Guitar Hero Metallica (U).iso
	Image type  = DVD
isoFile: second layer found at sector 0x001fd030
 * CDVD Disk Open: DVD, Double layer:
 * * Track 1: Data (Mode 1) (4169808 sectors)

God of War II (U).iso
	Image type  = DVD
isoFile: second layer found at sector 0x001fcc30
 * CDVD Disk Open: DVD, Double layer:

God of War (U).iso
	Image type  = DVD
isoFile: second layer found at sector 0x001fbf30
 * CDVD Disk Open: DVD, Double layer:
 * * Track 1: Data (Mode 1) (4161520 sectors)

 Xenosaga - Episode I - Der Wille zur Macht (U).iso
	Image type  = DVD
isoFile: second layer found at sector 0x001fb290
 * CDVD Disk Open: DVD, Double layer:
 * * Track 1: Data (Mode 1) (4134912 sectors)

Samurai Warriors 2 Xtreme Legends DVD9 (U).iso
	Image type  = DVD
isoFile: second layer found at sector 0x001f3450
 * CDVD Disk Open: DVD, Double layer:
 * * Track 1: Data (Mode 1) (4049360 sectors)

Yakuza 2 (E).iso
	Image type  = DVD
isoFile: second layer found at sector 0x001ee060
 * CDVD Disk Open: DVD, Double layer:
 * * Track 1: Data (Mode 1) (4047024 sectors)

ATV Offroad Fury 4 (USA).iso
	Image type  = DVD
isoFile: second layer found at sector 0x001ee440
 * CDVD Disk Open: DVD, Double layer:
 * * Track 1: Data (Mode 1) (3858928 sectors)

Genji Dawn of the Samurai (E).iso
	Image type  = DVD
isoFile: second layer found at sector 0x001f8250
 * CDVD Disk Open: DVD, Double layer:
 * * Track 1: Data (Mode 1) (3841824 sectors)

IsoFile open ok: Genji Dawn of the Samurai (E).iso
	Image type  = DVD
isoFile: searching for layer1...
isoFile: second layer found at sector 0x001f8250

Dynasty Warriors 6 (U).iso
	Image type  = DVD
isoFile: second layer found at sector 0x001e2310
 * CDVD Disk Open: DVD, Double layer:
 * * Track 1: Data (Mode 1) (3749984 sectors)

Forbidden Siren 2 (E).iso
	Image type  = DVD
isoFile: second layer found at sector 0x001f07c0
 * CDVD Disk Open: DVD, Double layer:
 * * Track 1: Data (Mode 1) (2853552 sectors)

Gran Turismo 4 (U).iso
	Image type  = DVD
isoFile: second layer found at sector 0x001418c0
 * CDVD Disk Open: DVD, Double layer:
 * * Track 1: Data (Mode 1) (2594960 sectors)

**Comment by willkuer** [comment]
Would be interesting to know what happens if you build your iso in a wrong way. So what happens if ypu have a broken iso.


Is compression affecting the result?

**Comment by turtleli** [comment]
Great. :)

The only thing which can change is the layer break address, so if it's the same as on master then it's working correctly.

> Would be interesting to know what happens if you build your iso in a wrong way. So what happens if ypu have a broken iso.
> 

Well, for dual layer DVDs, if the layer 1 primary volume descriptor isn't in the right place it'll assume the ISO is single layered and output a warning message. For single layer it probably doesn't matter. The game will not work correctly at some point if the ISO is corrupt anyway.

> Is compression affecting the result?

Compression won't affect the result.

**Comment by bositman** [comment]
I guess merge it? :P

**Pull request merged**
