### PR TITLE
EE/IOP Timers: Rewrite gate functionality

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Rewrites Gating functionality following hardware tests.

### Rationale behind Changes
Gate behaviour was completely wrong in PCSX2. Did some extensive testing and modified the behaviour in PCSX2 to match the PS2.

### Suggested Testing Steps
Test CMR 2005, and any other games which ran too fast and needed EE cycle rate changes to slow it down, or things didn't happen when they should do.

Savestate version bump, sorry

### CODE REVIEW

**Comment by bigol83** [comment]
Oh, this could fix Valkyrie Profile 2 intro video being too fast compared to audio. That game needs EE under click at 60% to work at correct speed.

**Comment by refractionpcsx2** [comment]
It does not, sorry.

**Comment by bigol83** [comment]
> It does not, sorry.

Bummer.

**Review by JordanTheToaster — APPROVED** [review]

**Comment by refractionpcsx2** [comment]
So I ended up completely rewriting the gates, following tests on my PS2.

Savestate version bump, sorry

**Comment by weirdbeardgame** [comment]
Would this affect the IPU timings / should I test Myst III?

**Comment by refractionpcsx2** [comment]
Myst 3 doesn't use gates, but yeah, I guess it could affect IPU.

**Comment by seta-san** [comment]
What would use these gate functions? Cdvd? USB?

**Comment by refractionpcsx2** [comment]
it's usually display syncing, so I guess like, eyetoy at a stretch... but could also be pacing or even animation timing..

**Review by Mrlinkwii — APPROVED** [review]

**Pull request merged**
