### PR TITLE
CDVD: Rename cdrom files to Ps1CD for clarity of function

### PR DESCRIPTION
**Pull request by kenshen112**
### Description of Changes

Renames CDVD and Cdrom

### Rationale behind Changes

As the title states it's to make it easier to understand that one's focus is entirely on ps1 mode. The other is ps2 mode

### Suggested Testing Steps

See that it builds

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Why are you calling them PS2CD? 

Firstly, it's DVD's and CD's
Secondly the unit is *actually* called CDVD.

**Comment by kenshen112** [comment]
Sure, it was just kinda off the top of my head. I'll rename the ps1 stuff at least.

**Comment by kenshen112** [comment]
Ok, fixed

**Comment by refractionpcsx2** [comment]
Please rebase so your code doesn't conflict, at least.

**Comment by refractionpcsx2** [comment]
rename CDVD.h and CDVD.cpp back please.

**Comment by refractionpcsx2** [comment]
I Suggest you at least compile your code before committing it.

**Comment by kenshen112** [comment]
Yeah, sorry. I wasn't expecting this to have the issues it did

**Pull request merged**
