### PR TITLE
CI: Link with ffmpeg for AppImage

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Should cause linuxdeploy to pull in ffmpeg.

### Rationale behind Changes

Increase distribution compatibility.
Size will increase, but the appimage is already huge, so whatever. Packaging on Linux just sucks to begin with.

### Suggested Testing Steps

Test video capture with AppImage.

### CODE REVIEW

**Comment by RedDevilus** [comment]
Should ffmpeg also best be updated to 6.1.1? https://ffmpeg.org/download.html

**Comment by stenzek** [comment]
No, because it's using (and pulling in) the system libraries.

**Comment by stenzek** [comment]
48MB -> 94MB.... not worth it for a feature that barely anyone uses, IMO.

If you want video capture, I'd say just use the flatpak...

**Comment by TheTechnician27** [comment]
Made a 7-minute video and found no defect in it.

**Review by AmyRoxwell — APPROVED** [review]
Works On EndeavourOS (Arch Linux), Also, HEVC and other encoders on AMD gpus work on mesa drivers!

**Comment by AmyRoxwell** [comment]
Well, we have one problem, it doesn't utilize the gpu, it does all of it using the CPU, even if you have VAAPI and other packages that should make it work on the gpu, is there maybe some arguments that need to be put on the video encoder to make it utilize the gpu?

**Review by kamfretoz — APPROVED** [review]

**Comment by stenzek** [comment]
Meh. Gonna draft it I think. Distributing software on Linux just sucks.

The best move would probably be to build our own ffmpeg with the required modules enabled. But that also means building libx264 etc, and I really can't be arsed.

**Comment by lightningterror** [comment]
Closing as this is no longer being worked on.

**Pull request closed without merging**
