### PR TITLE
GameDB: Metal Gear Solid 3 PAL - Fix blurry characters

### PR DESCRIPTION
**Pull request by AndreAuth**
### Description of Changes
Fixes the blurry characters in Metal Gear Solid 3

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Can you get rid of the trailing spaces and put a period at the end of each of the comments?

Thanks :)

**Comment by AndreAuth** [comment]
I removed the whitespaces. Sorry :)

**Comment by refractionpcsx2** [comment]
Can you put periods at the ends of the comments too, please? :)

**Comment by AndreAuth** [comment]
Im so sorry :) Added them. Next time i will know.

**Comment by refractionpcsx2** [comment]
No problem, thanks!

**Pull request merged**
