### PR TITLE
Eyetoy: Add experimental support for JPEG and multiple resolutions

### PR DESCRIPTION
**Pull request by Florin9doi**
### Description of Changes
Add experimental support for JPEG and multiple resolutions

### Rationale behind Changes
* JPEG support required for EyeToy: Cameo games – JPEG, 640x480 : https://en.wikipedia.org/wiki/Digimask
  * Tested with MLB 07
* Support for Eyetoy Antigrav – MPEG, 160x112 : #4240
  * Won't work with normal webcams because a scaler isn't implemented, but can be tested with OBS

Demo:
Screenshot_2021-05-23_11-05-30

### CODE REVIEW

**Comment by lightningterror** [comment]
Shouldn't jpeg be under 3rdparty?

**Comment by lightningterror** [comment]
> > Shouldn't jpeg be under 3rdparty?
> 
> I had the same proposal when the USB plugin was initially merged: [#3889 (comment)](https://github.com/PCSX2/pcsx2/pull/3889#issuecomment-720960704), but it wasn't accepted.

Your proposal seems nice, keeps the code clean and any 3rdparty stuff separate.

**Comment by Florin9doi** [comment]
Rebased. This PR is required to reduce the Intro list down to one game: 
Untitled

**Comment by gil938271** [comment]
when is this going to be implemented?

**Comment by RedDevilus** [comment]
Needs a rebase again atleast.

**Comment by Florin9doi** [comment]
Are you going to merge this PR?

**Comment by jackun** [comment]
@Florin9doi feel free to ping

**Comment by Florin9doi** [comment]
Thanks @jackun

**Comment by gil938271** [comment]
how do i use the fix?

**Comment by gil938271** [comment]
through obs?

**Comment by Florin9doi** [comment]
Yes, you need to configure OBS to output 160x112 then Start Virtual Camera

**Comment by gil938271** [comment]
image
that is with obs

**Comment by gil938271** [comment]
image

**Comment by Florin9doi** [comment]
You probably haven't selected OBS camera in PCSX2>USB Settings>EyeToy settings or you haven't pressed "Start virtual camera" button in OBS
image

**Comment by gil938271** [comment]
image
is that is incorrect?

**Comment by gil938271** [comment]
can you show me your setup in obs? just a photo

**Comment by gil938271** [comment]
and yes I've activated the camera it still gave me a black screen iv tested it in eye toy play and it barley worked it just showed the camera capture the eyetoy didn't react at all

**Comment by Florin9doi** [comment]
[OBS](https://i.imgur.com/kjHhWC8.png)

You need to configure OBS and start OBS virtual camera before launching the game, but if it still doesn't works for you, you'd better join the discord server for support or wait for other optimizations.

**Comment by gil938271** [comment]
thanks just for curiusty what is your camera resolution? mine can go from 160*120 to 1280*800

**Comment by gil938271** [comment]
and.......................... it works. it require a few launches and shutdowns but it works. there is also a problem with the the camera fov/canvas size in antigrav. when you put a large canvas res in obs  the camera window is so big the you need to stand so close to the camera that the game becomes unplayable  luckily for me my camera supports 160x120 so i put my canvas size to that res without to much. (now that i think about it you can change the video feed in a way that would exceed the canvas so it is a none issue with a bit of tinkering)

**Comment by seta-san** [comment]
> ### Description of Changes
> Add experimental support for JPEG and multiple resolutions
> 
> ### Rationale behind Changes
> * JPEG support required for EyeToy: Cameo games – JPEG, 640x480 : https://en.wikipedia.org/wiki/Digimask
>   
>   * Tested with MLB 07
> * Support for Eyetoy Antigrav – MPEG, 160x112 : [[BUG] Black Screen - Eyetoy Antigrav #4240](https://github.com/PCSX2/pcsx2/issues/4240)
>   
>   * Won't work with normal webcams because a scaler isn't implemented, but can be tested with OBS
> 
> Demo:
> Screenshot_2021-05-23_11-05-30

i can't seems to get eyetoy cameo to work. i'm using 1.7 - 1504. i'm also testing with mlb 07

**Comment by tadanokojin** [comment]
Guys this isn't a support thread.

**Pull request merged**
