### PR TITLE
GS: Drop to SW for CLUT draws

### LINKED ISSUE #451: Driver Parallel Lines GSdx DX11/OpenGL SW Cars randomly changing color - HW garbage textures
I am using **pcsx2-v1.3.1-8-gf88bea5-windows-x86** from orphis buildbot.
Default settings (2-safe) except for:
GSdx10 software +2 rendering threads
SPU-X set to async mix and interpolation to cubic.

To reproduce just start a new game. While driving around you'll notice how your vehicle changes color randomly (red,white,black,blue) as well as other cars at sight, except for Taxis and Cops.

There are not known revisions of pcsx2 that previously worked OK with this game iirc. Last time i tested it was with svn r5559, unplayable using GSdx hardware mode due to graphics errors, while too slow with software mode.

BTW, i am using the igpu from processor HD Graphics 2000 with latest drivers installed 9.17.10.4101.  

**Log:**

PCSX2 1.3.1-20150201194910 - compiled on Feb  1 2015
Savestate version: 0x9a0a0000

Host Machine Init:
    Operating System =  Microsoft Windows 7 Enterprise Edition Service Pack 1 (build 
7601), 64-bit
    Physical RAM     =  7882 MB
    CPU name         =  Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
    Vendor/Model     =  GenuineIntel (stepping 07)
    CPU speed        =  3.299 ghz (4 logical threads)
    x86PType         =  Standard OEM
    x86Flags         =  bfebfbff 1fbae3ff
    x86EFlags        =  28100000

x86 Features Detected:
    SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX

Reserving memory for recompilers...

Loading plugins...
    Binding   GS: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins\GSdx32-
AVX.dll 
Windows 6.1.7601 (Service Pack 1 1.0)
    Binding  PAD: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins
\LilyPad.dll 
    Binding SPU2: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins\SPU2-
X.dll 
    Binding CDVD: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins
\cdvdGigaherz.dll 
    Binding  USB: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins
\USBnull.dll 
    Binding   FW: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins
\FWnull.dll 
    Binding DEV9: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins
\DEV9null.dll 
Plugins loaded successfully.

(GameDB) 9677 games on record (loaded in 161ms)
HLE Notice: ELF does not have a path.

Initializing plugins...
    Init GS
Windows 6.1.7601 (Service Pack 1 1.0)
    Init PAD
    Init SPU2
    Init CDVD
    Init USB
    Init FW
    Init DEV9
Plugins initialized successfully.

Opening plugins...
    Opening GS
    Opening PAD
    Opening SPU2
- SPU2-X: Enumerating PortAudio devices:
  **\* Device 0: 'Primary Sound Driver' (Windows DirectSound)
  **\* Device 1: 'Realtek HD Audio 2nd output (Realtek High Definition Audio)' (Windows 
  DirectSound)
  **\* Device 2: 'Speakers (Realtek High Definition Audio)' (Windows DirectSound)
  **\* Device 3: 'Speakers (Realtek High Definition Audio)' (Windows WASAPI)
  **\* Device 4: 'Realtek HD Audio 2nd output (Realtek High Definition Audio)' (Windows 
  WASAPI)
  **\* Device 5: 'Speakers (Realtek HDA Primary output)' (Windows WDM-KS)
  **\* Device 6: 'Headphones (Realtek HD Audio 2nd output)' (Windows WDM-KS)
    Opening CDVD
  - CDVD: Opening drive '\.\F:'...
  - CDVD: setSpindleSpeed success (11080KB/s)
  - CDVD: IO thread started...
  - CDVD: KeepAlive thread started...
  - CDVD: Disk Type: Double-Layer DVD
  - CDVD Disk Open: DVD, Single layer or unknown:
  - \* Track 1: Data (Mode 2) (1890800 sectors)
    Opening USB
    Opening FW
    Opening DEV9
    McdSlot 0: D:\BC\Juegos\Emus\Memcards\Main.ps2
    McdSlot 1: [disabled]
    Plugins opened successfully.
    EE/iR5900-32 Recompiler Reset
    Bios Found: USA     v02.20(10/02/2006)  Console
    BIOS rom1 module not found, skipping...
    BIOS rom2 module not found, skipping...
    BIOS erom module not found, skipping...
    (UpdateVSyncRate) Mode Changed to NTSC.
    (UpdateVSyncRate) FPS Limit Changed : 59.94 fps
    (SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_212.71;1
    (SYSTEM.CNF) Software version = 1.01
    (SYSTEM.CNF) Disc region type = NTSC
    ELF (cdrom0:\SLUS_212.71;1) Game CRC = 0xD720770D, EntryPoint = 0x001001A8
    (SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_212.71;1
    (SYSTEM.CNF) Software version = 1.01
    (SYSTEM.CNF) Disc region type = NTSC
    Not found Cheats file: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\cheats

### LINKED ISSUE #883: Burnout 3/Revenge/Dominator - Sun Glow Can Be Seen Through Surfaces
This is a known issue, but I'm opening this issue here so that if there is any progress on it being fixed, then it can be posted here and eventually (hopefully) marked as solved, in addition to the fact that it hasn't been mentioned on the issue tracker yet.

Anyway, this bug seems to be a core bug, as it appears in all of GSdx's software and hardware renderers, as well as in ZeroGS. It's a pretty easy issue to understand - you can see the sun through walls, when it should disappear when your view of it is completely (not partially) obscured by an object. The bug happens in Burnout 3: Takedown, Burnout Revenge and Burnout Dominator, of which the versions for all regions are affected (basically, PAL and NTSC.)

No combination of settings in the Emulation settings window, nor the GSdx settings window has been able to fix the bug (including Synchronized MTGS.)

### LINKED ISSUE #1860: Ace Combat 5 - See through sun in HW renderers
[Gs dump](http://www61.zippyshare.com/v/Zn7vCK0h/file.html). 
If I first toggle SW renderer, it then gets fixed.

### LINKED ISSUE #3993: [BUG] Sun flares shine through walls in hardware renderer.
**Bug Description**
In hardware renderer the sun flares shine through walls. Tested in Need for Speed Most Wanted.

**To Reproduce**
Play the game and make sure the sun is in front of you. Then you drive under a bridge.
You'll see that the sun is hidden in sofware renderer mode, but still visible in hardware mode. 

**Expected behavior**
The sun should be behind the objects. As in the software renderer.

**Settings**
I tried all possible settings in the GS plugin. Including hacks. It occurs in the default settings. It only disappears when switching to software mode. This means, it does not matter if using OpenGL or Direct3D. 
I just enabled the Half-pixel Offset to Normal (Vertex) to remove lines around the textures. But this has no effect to this issue.
Let me know if you would like any specific settings. However, I'm sure there is only software / hardware settings to work around this issue. No special settings here.

Maybe you can explain the reason for this issue. That would be interesting. Hopefully we can find a solution.
Using the Skipdraw Range hack should not be a solution. At that moment I found no value for it. 
Maybe we can reorder the layers. But maybe it's another issue. Not about the layers. Because when the sun is at the edge of the bridge, it is not only covered by the wall. It's a transition. Maybe a missing feature. Like raycast. See:
pcsx2-nfsmw-issue-sun-sw-edge
<sub>(Software Renderer. This is what is expected in hardware mode. But in HW mode, the sun is not covered.)</sub>

**GS Window Screenshots**

| Actual (HW) | Expected for HW (SW) |
| --- | --- |
| pcsx2-nfsmw-issue-sun-hw | pcsx2-nfsmw-issue-sun-sw |

[videos-webm](https://github.com/PCSX2/pcsx2/files/5676866/videos-webm.zip) (Videos with more frames. GitHub does not yet support videos (no audio) ... Use e.g. VLC to view it. Or just the browser by drag'n'drop.)

**System Info**
 - PCSX2 Revision: v1.7.0-dev-675-g85c3ee823
 - OS: Windows 10 Pro 64-bit (v2004)
 - CPU: AMD Ryzen 5 3600 (6/12 Cores)
 - GPU: Nvidia GeForce RTX 2070 Super
 - RAM: 32GB
 - SSD: Yes

### LINKED ISSUE #5200: [BUG]: Klonoa 2 Monster shadow effect missing in HW mode
### Describe the Bug

In Volk Underground Factory an Ow-Gow bars the path ahead that's supposed to have a shadow darkeneing effect. In HW mode this effect is not present. 

What it's supposed to look like: https://youtu.be/vDbeu5tosT4?t=4239

What HW mode renders: gs_20211221165858

### Reproduction Steps

Play Underground Factory on HW mode

### Expected Behavior

The Ow-Gow is supposed to render black

### PCSX2 Revision

1.7.2146

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

### CPU

Ryzen 3700X

### GPU

GForce 2070

### GS Settings

All defaults.

### Emulation Settings

All Defaults

### GS Window Screenshots

_No response_

### Logs & Dumps

https://www.dropbox.com/s/z4mbuuefavuiih3/gs_20211221165858.gs.xz?dl=0

### LINKED ISSUE #5409: [BUG]: Alias: Lights appears behind geometry all the time.
### Describe the Bug

In the game Alias, there is a bug where any light source will appear even behind any geometry such as a wall or pillar.

I treid everything so far, nothing could solve the problem.

### Reproduction Steps

Load the GSdump and see the problem.

### Expected Behavior

The lights should not cross geometry.

### PCSX2 Revision

v1.7.2276

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

I9 9900K

### GPU

RTX 3070

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

The bug in action:

Software render:
alias

### Logs & Dumps

GSdump:
[Alias GSdump - light problem.zip](https://github.com/PCSX2/pcsx2/files/7936448/Alias.GSdump.-.light.problem.zip)

### LINKED ISSUE #6105: [BUG]: Sega Ages 2500 Series Vol. 19 - Fighting Vipers: Black and White bug
### Describe the Bug

On all renderers except for software, the game seems to render in black and white instead of in actual color.

### Reproduction Steps

Just start the game up while using any renderer except for software and let it sit on the title until it goes through the attract mode intro, it should be noticeable right away.

### Expected Behavior

The game should be in regular color like the software renderer.

### PCSX2 Revision

v1.7.2746

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

Ryzen 5 5600H

### GPU

GTX 1650

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

Software Renderer:

Fighting Vipers color bug Software

OpenGL, Vulkan, DX11/DX12 Renderers:

Fighting Vipers color bug other renderers

### Logs & Dumps

[Sega Ages 2500 Series Vol. 19 - Fighting Vipers Black and White bug Vulkan.zip](https://github.com/PCSX2/pcsx2/files/8735665/Sega.Ages.2500.Series.Vol.19.-.Fighting.Vipers.Black.and.White.bug.Vulkan.zip)

Dump was made while using Vulkan, but it is replicable while using any of the hardware renderers.

### LINKED ISSUE #6720: [BUG] Klonoa 2: miscolored objects/enemies in HW mode
### Describe the Bug

In Klonoa 2: Lunatea’s Veil, when using the OpenGL or Vulkan renderer, multiple types of enemies/objects appear miscolored, which can be confusing to the player. I am filing these under the same issue as they very likely stem from the same underlying problem.

### Reproduction Steps

1. Run the game using the OpenGL or Vulkan renderer.
2. Steps depend on the enemy/object:
  - moving [Goomi](https://klonoa.fandom.com/wiki/Goomi):
    1. go to any stage where the object appears, e.g. Kingdom of Sorrow
    2. the moving Goomi incorrectly appears as regular green Goomi (which are normally stationary)
  - a long-lasting [Kiton](https://klonoa.fandom.com/wiki/Kiton)
    1. go to Kingdom of Sorrow (the only stage where this variant appears) and progress to the end of the 8th area until you encounter a wall and a Kiton 
    2. the enemy appears incorrectly as a regular Kiton with a blue body and yellow legs (which normally have a shorter use)
- [Likuri](https://klonoa.fandom.com/wiki/Likuri)
  1. go to any stage where the enemy appears, e.g. Ishras Ark
  2. grab a Likuri and merge it with two or three enemies
  3. the Likuri appears incorrectly as yellow (which should only be the case when merged with **only one** enemy)
- color-coded crystal boulders
  1. go to any stage where the object appears, e.g. Ishras Ark
  2. crystals that emit blue or red smoke are incorrectly rendered as yellow
- short-fuse [Boomie](https://klonoa.fandom.com/wiki/Boomie)
  1. go to any stage where the enemy appears, e.g. The Ark Revisited
  2. the enemy incorrectly appears as regular red Boomie (which normally explode after being captured, not when approached)

### Expected Behavior

 - moving [Goomi](https://klonoa.fandom.com/wiki/Goomi) should appear red
 - long-lasting [Kiton](https://klonoa.fandom.com/wiki/Kiton) should have a yellow body with black legs
 - [Likuri](https://klonoa.fandom.com/wiki/Likuri) should appear blue after merging with two enemies, and red after merging with three enemies
 - color-coded crystal boulders should be blue if they emit blue smoke, and red if they emit red smoke
 - short-fuse [Boomie](https://klonoa.fandom.com/wiki/Boomie) should appear pink on spawning and then alternate between black and white until blown up

### PCSX2 Revision

v1.7.3130

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Fedora 35

### CPU

AMD Ryzen 3700X

### GPU

AMD Radeon RX 6800 XT

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

| Enemy/object | Hardware (incorrect) | Software (correct) |
| ------------- | ------------- | ------------- |
| moving Goomi |   |   |
| long-lasting Kiton |   |   |
| Blue crystal and Likuri merged with two enemies |   |   |
| Red crystal and Likuri merged with three enemies |   |   |
| Short-fuse Boomie spawning |   |   |
| Short-fuse Boomies idling (with one regular Boomie in the middle)  |   |   |

### Logs & Dumps

[GS dumps on Google Drive](https://drive.google.com/drive/folders/1IzIL6t7AAZkSrKpOWEYTB9ev_5i_18iK?usp=sharing)

### LINKED ISSUE #6723: [BUG] Klonoa 2: missing transition effect on green platforms in HW mode
### Describe the Bug

In Klonoa 2: Lunatea’s Veil, there are green floating platforms that have a transition effect to alert the player about the platform disappearing. After being stepped on, the platform should fade to black and then quickly flash in a lighter green color before finally disappearing. The platform also shortly appears in the lighter green color when it appears again. These effects are **not** displayed when using the OpenGL or Vulkan renderer.

### Reproduction Steps

1. Run the game using the OpenGL or Vulkan renderer
2. Go to any stage that has the floating green platforms (e.g. right at the beginning of Noxious La-Lakoosha)
3. Step on the platform
4. The platform simply disappears after a certain period of time, but does not display the transition effect

### Expected Behavior

The platform should display the described transition effect after being stepped on.

### PCSX2 Revision

v1.7.3130

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Fedora 35

### CPU

AMD Ryzen 7 3700X

### GPU

AMD Radeon RX 6800 XT

### GS Settings

_No response_

### Emulation Settings

_No response_

#### Hardware renderer (missing effect)

https://user-images.githubusercontent.com/14016863/181267216-0dd71009-3358-4d17-a72a-74bd217e812a.mp4

#### Software renderer (effect displayed)

https://user-images.githubusercontent.com/14016863/181267240-e2610925-b90c-4f46-8ae1-c14cfd650b93.mp4

### Logs & Dumps

[GS dump on Google Drive](https://drive.google.com/file/d/1fIvzUSb-M_M03b3SsDq4_0Jfe3s7EdX4/view?usp=sharing)

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Tidy up some of the code.
Split out CLUT checks for drawing overwrite of the CBP (CLUT source address).
When drawing to the CLUT, use the sw renderer to do the heavy lifting

### Rationale behind Changes
Tidy code is happy code.
Old check for CLUT invalidation on draw wasn't really sufficient, now it checks more thoroughly.
Drawing the CLUT in hardware on the GPU, then invalidating the CLUT in GS memory and downloading it, thousands of times a frame in some cases, is slow and the HW renderer purposefully has a guard against this happening, but it breaks CLUT related stuff in the process, this forces those draws to be done in software so there's no issues arising from upscaling and there's no download required, so there's no huge performance loss.

### Suggested Testing Steps
Test stuff with lights showing through objects, bad colours, completely missing stuff. You will possibly need to change the new "CPU Clut Render" option in the HW fixes screen, but the below games have been added to the DB.

⚠️ NOTE: If you still experience light bleed, first check game fixes are enabled and hw manual fixes are disabled. If it's still broken, try lowering the upscale (though I think I've resolved this)⚠️ 

### Stuff this PR fixes

120-en no Haru: 120 Yen Stories - Broken sprite colours (actually had an alternative gamefix, but has been replaced)
Ace Combat 05 - Sun occlusion
Alias - Light occlusion (See-through lights)
Burnout 3/Dominator/Revenge - Sun occlusion
Cyber Troopers Virtual-On - Missing colours
Dog's Life - Jake going black when in smell-o-vision (maybe misdetection, but I'll take it)
Driver Parallel Lines - Car/People colours
Godfather, The - Light occlusion through walls. still need skipdraw 1 to remove post effect fail.
Guitar Hero Metallica - Bad colours during gameplay
Klonoa 2 - Pipe monster shadow, green platform transition effect, miscoloured enemies/objects
Minority Report - Light occlusion
PDC World Championship Darts 2008 - Light occlusion and overbright issues when Autoflush was enabled
Need For Speed Most Wanted - Sun occlusion
Fighting Vipers - Missing colours
Last Bronx - Missing colours
Sega Rally 95 - Missing colours (menu background requires disable depth)
Sonic Fighters - Missing colours
True Crime New York City - Light occlusion
Virtual Fighter 2 - Missing colours

Fixes #1860 (Ace Combat 05)
Fixes #5409 (Alias)
Fixes #883 (Burnout 3/Revenge/Dominator)
Fixes #451 (Driver - Parallel Lines)
Fixes #6105 (Fighting Vipers and other mentioned Sega Model 2 games)
Fixes #6723 (Klonoa 2 Platform transition)
Fixes #5200 (Klonoa 2 Shadow)
Fixes #6720 (Klonoa 2 Miscoloured enemies/objects)
~~Didn't solve #2942 (Hot Pursuit)~~
Fixes #3993 (NFS Most Wanted)

### Compairson shots

120-en no Haru: 120 Yen Stories:

Master (without CRC hack)
image

PR (without CRC hack)
image

Ace Combat 05:

Master:
image

PR:
image

Alias:

Master:
image

PR:
image

Burnout 3:

Master:
image
image

PR (Requires Autoflush + Preload frame, possibly)
image
image

Cyber Troopers Virtual-On:

Master:
image

PR:
image

Driver - Parallel Lines:

Master:
image

PR:
image

Godfather, The:

Master:
image

PR:
image

Klonoa 2:

Master:
image
image
image

PR:
image
image
image

Minority Report:

Master:
image

PR:
image

Need for Speed Most Wanted:

Master:
image

PR:
image

PDC World Championship Darts 2008:

Master:
image

PR:
image

Sega Rally 95:

Master:
image

PR:
image

Sonic Fighters:

Master:
image

PR:
image

True Crime New York City:

Master:
image

PR:
image

Virtual Fighter 2:

Master:
image

PR:
image

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Okay uhh, I kinda blew the scope of this PR out of the water a little, but at least now it's actually a huge improvement and not just some boring tidy up work.

**Comment by refractionpcsx2** [comment]
Okay the new stuff is actually a hw fix option now (temporarily added to the global settings but will be moving to per-game for release builds)

So if you have a game you wanna see if it helps, you can find it there for now.

Bonus:

Added 3ish new game to the list of fixes.

**Comment by waspennator** [comment]
Speaking of the Sega Ages games, shouldn't this be enabled for Last Bronx too, since it runs on the sega model 2 engine and also seems to have similar color issues according to others?

**Comment by refractionpcsx2** [comment]
> Speaking of the Sega Ages games, shouldn't this be enabled for Last Bronx too, since it runs on the sega model 2 engine and also seems to have similar color issues according to others?

Thanks! I didn't know about that one, so I've added it :)

**Comment by AhayriSG** [comment]
True Crime - New York City_SLES-53616_20221027102030
GS Dump
[True Crime - New York City_SLES-53616_20221027102030.gs.gz](https://github.com/PCSX2/pcsx2/files/9878400/True.Crime.-.New.York.City_SLES-53616_20221027102030.gs.gz)

**Comment by refractionpcsx2** [comment]
>  True Crime - New York City_SLES-53616_20221027102030 GS Dump [True Crime - New York City_SLES-53616_20221027102030.gs.gz](https://github.com/PCSX2/pcsx2/files/9878400/True.Crime.-.New.York.City_SLES-53616_20221027102030.gs.gz)

Thanks! I've added it to the GameDB :)

image

**Comment by refractionpcsx2** [comment]
Added Klonoa 2 to the list, fixes all the colours of objects, shadows, enemies, platform transitions.

**Comment by refractionpcsx2** [comment]
Added The Godfather - The Game (fixes the lights through objects but not the post filter, needs skipdraw 1 for that)

**Comment by refractionpcsx2** [comment]
Had to remove NFS Hot Pursuit 2's Busted screen, it was a misdetection as I suspected and having that working as it did (not greatly) was breaking Klonoa which was also misdetecting and breaking the picture.

I have attached the draws for NFS to the relevant issue for further investigation

**Comment by DonelBueno** [comment]
Great work, refraction!

I saw a mention of GT4 in this PR another day, but it didn't fix the sun through objetcs from my testing. Do you what is the problem there?

**Comment by refractionpcsx2** [comment]
Uhh I removed mention of that because it seems to be a different issue.  One tester said preload frame fixed it, but also lowering the resolution fixes it, it could be an issue with upscaling there.

But thanks :){

**Comment by DonelBueno** [comment]
Hmm, that's true, it works fine at native resolution, even on the master build. Preload frame data didn't make a difference here.

**Comment by refractionpcsx2** [comment]
In a weird coincidence with a support issue. Turns out this fixes the weird colours in Guitar Hero - Metallica, so I've added it to the gamedb

**Pull request merged**
