### PR TITLE
OpenGL printf wording corrections, removed Shadow Hearts CRC

### PR DESCRIPTION
**Pull request by bositman**
Some minor grammar fixes to OpenGL prints and removed Shadow Hearts CRC
which has been left behind, there is no patch for it in GSstate anymore.

### CODE REVIEW

**Comment by bositman** [comment]
Just making sure I didn't change the meaning of the OpenGL messages, that's why gregory was assigned (once again, sorry dude :P )

**Comment by refractionpcsx2** [comment]
"fprintf(stderr, "Note: the maximum supported supported by GSdx"

you might wanna rethink that.. :P

**Comment by bositman** [comment]
Goddamit :P

**Comment by refractionpcsx2** [comment]
That's better xD Sorry bud!

**Comment by gregory38** [comment]
:+1:

**Comment by karasuhebi** [comment]
Because that's the actual name of the API, and specifically in this case because it's an acronym that stands for something.

**Comment by refractionpcsx2** [comment]
because GL is Graphics Library, OpenGL is an acronym, not a name :P

**Pull request merged**
