### PR TITLE
Native DualShock 3 support in Windows by official Sony driver (sixaxis)

### PR DESCRIPTION
**Pull request by rewasdadmin**
Changed native DualShock 3 support in Windows from outdated libusb to official Sony driver (sixaxis), which is also standard for RPCS3 and Steam.

### CODE REVIEW

**Comment by stenzek** [comment]
Bunch of stylistic issues here, probably easiest to just run clang-format through the file.

That aside, the old pad code is effectively deprecated as it's tied to the old wx interface. If you wanted to implement this for Qt, you would create a new `InputSource`.

**Comment by eVenent** [comment]
It would be great to have official support for reWASD's Virtual DS3 controller in PCSX2. Sony's driver is now compatible with RPCS3, but not with PCSX2, so we need to add and remove official drivers to use these two emulators. Having official support for Sony's driver would fix everything and make the process easier.

**Comment by rewasdadmin** [comment]
We made this patch because many users had issues with libusb and asked us for some workaround.
You are free to move same code to Qt or elsewhere if needed and you can format it if needed according to your guidelines (we used Visual Studio 2019 and had no problems), sorry for inconvenience.

**Comment by refractionpcsx2** [comment]
Thanks for doing that, can you squash it down and correct your commit name, I would prefix it with "Pad:"

**Comment by refractionpcsx2** [comment]
To be fair to them, the rest of the file was spaces.

**Review by lightningterror — APPROVED** [review]
Much better now, needs to be tested.

**Comment by tij77** [comment]
Tested it with
(1) real DualShock3 connected to PC with USB cable using Sony sixaxis driver
(2) real DualShock3 connected to PC via Bluetooth using reWASD VirtualDS3 controller with sixaxis driver
(3) Nintendo Switch PRO connected to PC via Bluetooth using reWASD VirtualDS3 controller with sixaxis driver
(4) real DualShock3 connected to PC with USB cable using DsHidMini (HID device mode: SXS) 
(5) real DualShock3 connected to PC via Bluetooth using DsHidMini and BthPS3 (HID device mode: SXS)

In all cases PCSX2 able to detect controllers as Dual Shock 3. After controller binding, able to "Test Device", which confirms everything work including all pressure sensitive buttons (Nintendo Switch PRO pressure sensitivity was mapped in reWASD).

Tested binded controllers in Metal Gear Solid 2 Substance (USA) and everything work as expected (including pressure sensitivity)

**Comment by refractionpcsx2** [comment]
@tij77 that was with a WX build, right?

**Comment by tij77** [comment]
Yes ... tested it with WX build ... https://github.com/reWASD/pcsx2/releases/tag/sixaxis

**Comment by refractionpcsx2** [comment]
okay , can you try the build on this branch. Trying somebody else build defeats the point https://github.com/PCSX2/pcsx2/actions/runs/3153887892

**Comment by tij77** [comment]
will do

**Comment by refractionpcsx2** [comment]
Thanks :)

**Comment by tij77** [comment]
Will take some time (1 or 2 days) to test all builds ... will report as soon as have results

**Comment by refractionpcsx2** [comment]
No problem, take as long as you need, I appreciate the testing.

**Comment by tij77** [comment]
Do I need to attach some logs from testing, or my word is good enough?

**Comment by refractionpcsx2** [comment]
Word is fine, as long as you're not lying because that's not going to help anybody, that will just end up us reverting and removing the new code.

**Comment by tij77** [comment]
Got it ... will get back as soon as I have finished testing

PS. great work from PCSX2 team!!! Please continue your great work!!!

**Comment by refractionpcsx2** [comment]
Thanks! :) 

And again, appreciate the help.

**Comment by refractionpcsx2** [comment]
Just FYI, DSHidMini with XInput has pressure sensitivity in PCSX2, other configurations do not :)

As for the bug in WX, if it's still function (even if it's a pain) then it's not being touched, since WX is essentially legacy now.

Will wait for your resutls with DSHidMini in WX with the changes, but thank you for providing such an in-depth report :)

**Comment by tij77** [comment]
Yes, I am aware that @nefarius is working on passing DS3 capabilities via XInput. Last I checked it is still in beta. Ironically, if Qt kept DirectInput ... DS3 functionality will be still available in Qt via DsHidMini SDF mode like it is still available on wxWidgets.

When you mentioned "WX is essentially legacy now" - does it mean that wxWidgets will be deprecated in favor of Qt when version 17 gets to stable release (understandable as maintaining 2 interfaces is waist of valuable resources ... and Qt looks like a step forward in terms of UI)? Its a pity, since wxWidgets got sixaxis working now. IMHO sixaxis is best way to get DS3 working:
1. it works without any third party tools if you are using USB cable
2. DsHidMini (using SXS mode) and reWASD (using Virtual PS3 mode) can make this work via bluetooth. And DsHidMini is free thanks to @nefarius
3. this mode works with RPCS3 with full DS3 functionality (pressure sensitivity, gyro and accelerometers)

DualShock 3 have all functionality and feel of DualShock 2 with bluetooth support and without need of USB adaptors. Is there any chance sixaxis implementation in wxWidgets gets transfer to Qt? 

As for testing, as expected DsHidMini and reWASD have exactly same results as DualShock3 connected to PC via USB with sixaxis driver:

Qt builds - controller work but NO pressure sensitivity
wxWidgets builds - controller work INCLUDING pressure sensitivity

**Details of testing**

Some info on my system:
Windows 10 Version 21H1 (OS Build 19043.2006)
reWASD version 6.3.1 6778 (downloaded from https://www.rewasd.com/)
DsHidMini version 2.2.282.0 (downloaded latest from https://github.com/ViGEm/DsHidMini/releases/tag/v2.2.282.0)
BthPS3 version not indicated (downloaded latest from https://github.com/ViGEm/BthPS3/releases/tag/setup-v2.6.174.0)

DsHidMini setup: real DualShock 3 connected with bluetooth via BthPS3 ... using SXS mode

reWASD setup:
(1) real Sony DualShock3 connected with bluetooth via reWASD ... set up as Virtual DS3 controller with sixaxis driver
(2) GameSir T4PRO (connected to PC via bluetooth as Switch PRO controller) ... set up as Virtual DS3 controller with sixaxis driver

Testing method is same as performed with DualShock3 connected to PC via USB with sixaxis driver (described ealier). As expected both reWASD and DsHidMini have identical results as before:

Qt builds - controller work but NO pressure sensitivity
wxWidgets builds - controller work INCLUDING pressure sensitivity

**Comment by tij77** [comment]
I will try to convince reWASD to do this for Qt in their user forum ... as I do agree it is waist of effort if wx is deprecated (as it is working perfectly as intended)

I would have coded this myself ... but I have not done so in many many years ... not sure I am up to task.

**Comment by refractionpcsx2** [comment]
no problem, thank you for yours and reWSAD's efforts :) Would be great to have this going forward!

**Comment by nefarius** [comment]
> I'm pretty confident pressure sensitivity has worked in qt with DSHidMini for months now, Silent (of Silent Patch fame) modified it to work quite a while ago now, you need to make sure to copy the xinput dll file in to the pcsx2 folder, else this won't work.

This is correct. No Beta whatsoever 😛

**Comment by nefarius** [comment]
> Yes, I am aware that @nefarius is working on passing DS3 capabilities via XInput. Last I checked it is still in beta. Ironically, if Qt kept DirectInput ... DS3 functionality will be still available in Qt via DsHidMini SDF mode like it is still available on wxWidgets.

Already a thing for like half a year or so 😉

**Comment by tij77** [comment]
> > Yes, I am aware that @nefarius is working on passing DS3 capabilities via XInput. Last I checked it is still in beta. Ironically, if Qt kept DirectInput ... DS3 functionality will be still available in Qt via DsHidMini SDF mode like it is still available on wxWidgets.
> 
> Already a thing for like half a year or so 😉

@nefarius!!! ... thank you for your great work!!!

**Comment by rewasdadmin** [comment]
We have patched old Wx code because it is the core of current mainstream 1.6.0 version (with libusb).
Many users have complained about it, so we took our time and patched it.
We were basically unaware that this was legacy code (until now). We tried to make people's life easier and created own fork.
It was not very hard because old code revolves around HID and sixaxis interface relies on HID communication.
Unfortunately, it seems new Qt code does not support HID and DirectInput, so studying new interface would take more time.
It would be much faster if someone who has more experience with Qt and PCXSX2 would help port old HID code to new
interface, because this is not our area of expertise and would require a lot bigger involvement in PCSX2 project, which,
unfortunately, is not impossible for our team at the moment. Maybe some day, but not now.
So, until this happens, maybe it 's better to use at least our fork.
We don't think it is 'waisted effort' in any case, because everyone can check our code and port it to any application or GUI he wants.

**Comment by refractionpcsx2** [comment]
Alright, we'll leave it here for now then. Thanks for your contribution

**Comment by refractionpcsx2** [comment]
as #7196 has been merged, we now have DInput in Qt builds, so if you wanted to port it to that too, now you can :)

**Pull request merged**
