### PR TITLE
GS-HW: Improvements to tex in rt + invalidation

### LINKED ISSUE #2289: Hasbro Family game Night : Broken hardware render
***PCSX2 version:***
Last 1.5dev

***PCSX2 options:***
All default, speedhack disabled don't change the issue.

***Plugins used:***
All default

***Description of the issue:***
The GSDX plugin is unable to display the screen correctly under hardware mode (image cut in half), look:

capture

-Note: The software render is fine.
-Note2: OpenGL and DX backend are affected, I tried every possible hacks but nothing succed.
-Note3: ZZogl exibit the same issue.

***How to reproduce the issue:***
Load "Hasbro Family game Night" under GSDX hardware mode.

***Not a regression***

***Side note***
It seems that there is a another issue related the PCSX2 core, when a game board comes out, there are some little corruption around it, look this exemple (inside the red circle):
capture2

***PC specifications:***
Intel core I5 3230m AMD radeon hd 7600m Windows 10 64bit

***Core/GSDUMP***
https://drive.google.com/file/d/17Ix4qmS1p6KOsRX5wyFvrnIskpqFdvp9/view?usp=sharing

### LINKED ISSUE #2296: Trivial pursuit : Broken up-left part of the screen under hardware mode
***PCSX2 version:***
1.5dev 2266

***PCSX2 options:***
All default, speedhacks don't change the issue.

***Plugins used:***
All default

***Description of the issue:***
The upper-left part of the screen is completely broken under any hardware render look:

capture

Note: Software mode is fine
Note2: OpenGL and DX backend show the same issue, I try various hacks but nothing succed
Note3: Can be related to this https://github.com/PCSX2/pcsx2/issues/1318

***How to reproduce the issue:***
Load "Trivial pursuit" in a GSDX hardware render.

***Not a regression***

***PC specifications:***
Intel core I5 3230m AMD radeon hd 7600m Windows 10 64bit

***GSDUMP***
https://drive.google.com/file/d/1H7P73kpWmAtibZCOnsssI6ZQG98zXFHK/view?usp=sharing

### LINKED ISSUE #3155: [GSdx HW] Xenosaga III ntsc Error graphics on surfaces in the last dungeon
***PCSX2 version:***
PCSX2 1.5.0-dev-3302 - 20191023012101 - compiled on Oct 23 2019

***PCSX2 options:***
Default emulation settings (2 - safe)

***Plugins used:***
GSDX OGL, AVX2 and the defaults

Hardware mode OGL
Native res and up
Mipmapping, automatic CRC, accurate date and accurate blending all set as the defaults, but changing them up to full does not fix it either. Cannot find a HW hack that fixes it either.

Game generally needs the hacks disable safe features, merge sprite, preload frame data, and half pixel offset: special (texture) to look its best through most of the game in OGL hardware mode, but those do not fix this, nor does turning them off.

Virtually the same error exists in DX11 HW mode.

***Description of the issue:***
Error garbage graphics present in some surfaces in the last dungeon, most or all of the surfaces being somewhat transparent and "crystalline."
Different but yet similar looking (enough for them to probably all be the same root cause) forms of it are present throughout the last dungeon in the game.
https://ibb.co/LJ2nLC4 - example of the error
https://ibb.co/bvc93WP - what the same place looks like in software mode (correct)

***How to reproduce the issue:***
A GSDump is attached to this post.

A memory card save is also attached if needed.
Load the 36th save in the memory card, go to the right, then south/
backwards (towards the camera) and through the door and keep walking towards the camera and you'll run into one of the walls of it. You can run from any enemy battles encountered with the escape command. There are also more examples further on in the dungeon which can be reached by going backwards through the dungeon from the 37th save.

***Last known version to work:***
Most likely has never worked correctly in dx11 or ogl hardware mode given what I am seeing on the compatibility wiki, works in software mode

***PC specifications:***
Intel i5 6600, 8GB RAM, GTX 1060 3GB, Windows 8.1pro

[xenosaga 3 last dungeon graphics bug gsdump.zip](https://github.com/PCSX2/pcsx2/files/3844061/xenosaga.3.last.dungeon.graphics.bug.gsdump.zip)
[xenosaga 3 mcd001 for last dungeon graphics bug.zip](https://github.com/PCSX2/pcsx2/files/3844063/xenosaga.3.mcd001.for.last.dungeon.graphics.bug.zip)

### LINKED ISSUE #3285: Metal Gear Solid 2: Sons of Liberty cutscenes glitch in HW mode [SLUS-20144]
**pcsx2-v1.5.0-dev-3391-gbf9519433-7012-vs2019-Win32**

**PCSX2 options:**
Native resolution. Any settings. OpenGL HW.

**The problem:**
Vertical block appears on the left of the screen during cutscenes in HW mode. SW mode doesn't have it.

**Screens:**

**gsdx snap:**
[Metal Gear Solid 2 Sons of Liberty cutscenes glitch in HW mode [SLUS-20144].zip](https://github.com/PCSX2/pcsx2/files/8564770/Metal.Gear.Solid.2.Sons.of.Liberty.cutscenes.glitch.in.HW.mode.SLUS-20144.zip)

**How to replicate the problem:**
Start game, watch intro cutscene on the bridge. But it's present in many cutscenes throught the game.

**PC specifications:**
i7 2700, GTX 760, Windows 7 64 Bit

### LINKED ISSUE #3668: K-1 World Grand Prix 2006 - Black Screen
***PCSX2 version:***
``( v1.7.0-dev-213)``

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

- **Note**: In case the issue is a graphical problem with the GSdx plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
black screen in the menus on hardware renderer 
gsdx_20200904015915

then red when in the fight

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``

***Last known version to work:***
none

***PC specifications:***
CPU: Intel Core i5 4430 GPU: Geforce 960 OS: Windows 10 64 Bit)``

### LINKED ISSUE #7468: [BUG]: Monopoly: Top left half of the screen shows the top right half of the screen.
### Describe the Bug

See image. Top left half of the screen shows the top right half of the screen.

During FMVs it looks normal.

### Reproduction Steps

Start the game, and notice the top half of the screen is broken.
image

### Expected Behavior

_No response_

### PCSX2 Revision

1.6.0

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

i9-9900k

### GPU

RTX 3060

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### LINKED ISSUE #8067: [BUG]: Urban Reign: visual artefact
### Describe the Bug

When you have finished the last opponent this visual artefact appears.

### Reproduction Steps

Play first mission with hardware renderer. Software renderer is fine.

### Expected Behavior

_No response_

### PCSX2 Revision

v.1.7.4017

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Ryzen 7 5800X

### GPU

RTX 3080

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

Urban Reign_SLUS-21209_20230207071316

### Logs & Dumps
[Urban Reign_SLUS-21209_20230207125434.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/10673755/Urban.Reign_SLUS-21209_20230207125434.gs.xz.zip)

_No response_

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Tries to use page aligned rect calculations when possible for Invalidation, which is a lot more frequent than I hoped, so that's good.  Also extended it to TextureInRT since surface offsets seems to give garbage results in some cases and this works much better.

Also clear semi-dirty render targets when used for sources.

### Rationale behind Changes
Surface offsets isn't really designed to translate an incoming rectangle to physical blocks, which are not in a linear order, so the positions it gives can be incorrect for the hardware renderer and our very linear rectangles.

### Suggested Testing Steps
Test games, plus those listed below.

Fixes Ape Escape 3 pause screen regression (Invalidation misdetection)
Fixes Final Fantasy X transitions if you pause during them (invalidation misdetection)
Fixes Dog's Life Smell-o-vision causing corruption when leaving that mode (hopefully, I hate this game)
Fixes #8067 garbage in Urban Reign during fight scenes. (texture in rt dirty rects)
Fixes #7468 Monopoly corrupt/segmented screen (texture in dirty target)
Fixes Driving Emotion Type-S underlying issue with bad dirty rect
Fixes #2296 Trivial Pursuit (Texture in dirty target)
Fixes #2289 Hasbro Family Game night (Texture in dirty target, probably)
Fixes Primal glitchy textures (Texture in RT stuff, most likely)
Mostly fixes the LEGO Racers 2 sun bleed, not sure if it's just the game now or still a bug. (position in Z target on readback)
Fixes the Gundam Battle Assault 3 - Ft Gundam Seed lights in the background. (missing Z target on readback)
~~Fix regression on Takahashi Naoko no Marathon Shiyou yo! Setting width of 0, which later gets replaced, but it was being avoided (width 0 should always be replaced)~~ Handled in another PR already merged
Fixes Indiana Jones and the Emperors Tomb map (invalidation issues)
Fixes #3285 Metal Gear Solid 2's cutscene overlays (partial invalidation of different widths)
Fixes Zone of Enders 2nd Runner cutscene blur/post (partial invalidation of different widths)
Fixes #3668 Black screen on K-1 Grand Prix games (PCRTC output frame dirty) - Would recommend continuing to use the patch if you want upscaling.
Fixes #3155 Xenosaga Episode III crystaline surfaces and tex in rt compatibility.

Monopoly:
Master:
image

PR:
image

Trivial Pursuit:
Master:
image

PR:
image

Urban Reign:
Master:
image

PR:
image

Hasbro Family Game Night:

Master:
image

PR:
image

Indiana Jones and the Emperors Tomb:

Master:
image

PR:
image

Gundan Battle Assault 3:

Master:
image

PR:
image

### CODE REVIEW

**Comment by Shoegzer** [comment]
Good stuff @refractionpcsx2.  This PR does clean up some of the texture garbage with Vulkan in TC:NYC as I mentioned [here](https://github.com/PCSX2/pcsx2/pull/8242#issuecomment-1444494889), however there is still some remaining.  For example, when transitioning from indoors > outdoors, there is a rectangle of garbage visible in the lower-right corner of the load screen (prior to this PR it filled the entire screen).  I was finally able to capture this using a multi-frame GS dump, [here](https://github.com/PCSX2/pcsx2/files/10842983/tc_nyc_garbage_texture.zip).  

There is also a small rectangle of garbage in the lower-right that still frequently displays while driving, but I'm yet unable to capture that one without generating a massive GS dump.  Hopefully these two are linked and that won't be necessary.

**Comment by refractionpcsx2** [comment]
Cool, True Crime wasn't really my focus, but it's nice that it helps :) I'm still kinda working on this, ironing out some bugs when using texture in rt with the page align stuff. should be done with it soon, hopefully.

**Comment by refractionpcsx2** [comment]
Okay I think this PR is ready for review/testing :)

**Review by Mrlinkwii — APPROVED** [review]

**Comment by bigol83** [comment]
I tried this PR on Dragon Quest VIII and it fixes the black border lines but there is now this graphic glitch on torches

Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230302195953

**Comment by RedDevilus** [comment]
Can you post a gs dump? Tools > Single Frame GS Dump, which will be posted in PCSX2/snaps alongside screenshot. Then just double zip it like zst.zip probably works.

**Comment by bigol83** [comment]
[Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230302201912.gs.zip](https://github.com/PCSX2/pcsx2/files/10875101/Dragon.Quest.VIII.-.Journey.of.the.Cursed.King_SLES-53974_20230302201912.gs.zip)

Here it is

**Comment by yellows111** [comment]
Poinie's Poin's motion blur works [one of the issues you couldn't capture with a GSDump] with RT!
Before:
Poinie's Poin_SCPS-15013_20230225093303


After, Inside Target:
Poinie's Poin_SCPS-15013_20230303081229

After, Merge Targets:
Poinie's Poin_SCPS-15013_20230303080610

**Comment by refractionpcsx2** [comment]
Does that work on master as well using the same setting?

**Comment by yellows111** [comment]
> Does that work on master as well using the same setting?

v1.7.4179
Poinie's Poin_SCPS-15013_20230303081742

Doesn't seem like it.

**Comment by refractionpcsx2** [comment]
cool :) IS there any way you could do a multi frame GS Dump of that so I can do some testing? as I'm currently rewriting some of the functions on this PR to suck less, and it's good to have some test cases :) It should be holding down Ctrl+Shift+F8 by default, but you can change it in the hotkeys

Thanks!

**Comment by yellows111** [comment]
> cool! :) Is there any way you could do a multi frame GS Dump of that

I mean, yeah, i've got GSDumps of this happening, but the GSDump viewer appears to be based on GS/SWRenderer rather than GS/HWRenderer, which I guess makes sense for general graphical issues that would show up in SW (and thus, effect all renderers in theory), which makes it not show HW-only issues such as this.

[Poinie's Poin_SCPS-15013_20230225094038.gs.xz.gz](https://github.com/PCSX2/pcsx2/files/10883815/Poinie.s.Poin_SCPS-15013_20230225094038.gs.xz.gz) (sorry for the file extension, it's just most Multi-frame GSDump's of these are over 25mb, which means no inline uploads)

If I wanted to try and complain about the GSDump viewer, then maybe a new issue would be better for that (example: The "Confirm Disc Change" dialog does not make sense when viewing a GSDump)

**Comment by refractionpcsx2** [comment]
Oh that's annoying, the dump doesn't show it (working fine on master) :(

**Comment by bigol83** [comment]
This is a better gsdump because it clearly shows DQ8 torch glitch.

[Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230303225648.gs.zip](https://github.com/PCSX2/pcsx2/files/10886429/Dragon.Quest.VIII.-.Journey.of.the.Cursed.King_SLES-53974_20230303225648.gs.zip)

**Comment by refractionpcsx2** [comment]
hmm the torch looks the same in hardware and software here :/

**Comment by bigol83** [comment]
I downloaded my latest gsdump, the one i posted yesterday and it indeed shows the torch glitch. I also recorded a video of how it looks

https://user-images.githubusercontent.com/38129260/222893980-4723eb83-278b-4934-936f-818850f47a5c.mp4

**Comment by bigol83** [comment]
So, the code you didn't upload yet already has the fix? Nice. I will gladly wait for other updates and fixes to this PR.

**Comment by refractionpcsx2** [comment]
well, it works, yes lol. But other stuff is broken, I still have work to do.

**Comment by andyten** [comment]
Sakura Taisen - Atsuki Chishion

Sakura Taisen - Atsuki Chishioni_SLPM-67003_20230305131533

[Sakura Taisen - Atsuki Chishioni_SLPM-67003_20230305131903.zip](https://github.com/PCSX2/pcsx2/files/10890839/Sakura.Taisen.-.Atsuki.Chishioni_SLPM-67003_20230305131903.zip)

**Comment by refractionpcsx2** [comment]
> Sakura Taisen - Atsuki Chishion
> 
> Sakura Taisen - Atsuki Chishioni_SLPM-67003_20230305131533
> 
> [Sakura Taisen - Atsuki Chishioni_SLPM-67003_20230305131903.zip](https://github.com/PCSX2/pcsx2/files/10890839/Sakura.Taisen.-.Atsuki.Chishioni_SLPM-67003_20230305131903.zip)

yeah don't get too excited, I've re-broken this since :D I think this was a false fix.

**Comment by refractionpcsx2** [comment]
@yellows111 can you try your game on this PR again? Just curious if it still works

**Comment by yellows111** [comment]
### Overrides enabled
Texture inside RT, Inside Target

### Fresh config?
No. MTVU is disabled. (Default: enabled)
No other changes have been made except the above overrides.

# Tests

### Text
Yes.
Poinie's Poin_SCPS-15013_20230305171413

### Motion Blurring
Yes.
https://user-images.githubusercontent.com/25440281/222975660-e49b762c-d702-4431-9e9c-20c445405bd6.mp4

**Comment by refractionpcsx2** [comment]
Awesome! Thanks for retesting :) I was worried it wouldn't be working lol

**Review by JordanTheToaster — APPROVED** [review]

**Comment by bigol83** [comment]
Tested Dragon Quest VIII with the new updates to the code and torches issue has changed slightly, but still there.

It doesn't happen anymore in software mode, but in hardware mode it happens even at native resolution in every renderer. 
[Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230306115715.gs.zip](https://github.com/PCSX2/pcsx2/files/10897366/Dragon.Quest.VIII.-.Journey.of.the.Cursed.King_SLES-53974_20230306115715.gs.zip)


Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230306115715

**Comment by refractionpcsx2** [comment]
A couple more potential fixes from the recent changes  but both currently require you to manually enable Texture Inside RT (Inside Target)

This one of Metal Gear Solid 2, issue #3285 
Master:
image

PR:
image


Also Xenosaga Episode 3:

Master:
image

PR:
image

**Comment by refractionpcsx2** [comment]
@yellows111 @bigol83 if you guys could retest your respective games and make sure they're still working, I'd appreciate it.

**Comment by JordanTheToaster** [comment]
Fixes ZoE 2 with Tex in RT Inside Target

Master:
image


PR:
image

**Comment by Toastarrr** [comment]
Enabling textureInsideRT fixes the slow motion effect, but this PR causes lots of junk to appear for a single frame during a blur transition in Metal Gear Solid 2 even without enabling textureInsideRT

Master:
Metal Gear Solid 2 - Sons of Liberty_SLUS-20144_20230315044855

PR (with or without textureInsideRT):
Metal Gear Solid 2 - Sons of Liberty_SLUS-20144_20230315044624

**Comment by JordanTheToaster** [comment]
> Enabling textureInsideRT fixes the slow motion effect, but this PR causes lots of junk to appear for a single frame during a blur transition in Metal Gear Solid 2 even without enabling textureInsideRT

Already been fixed.

**Comment by bigol83** [comment]
> @yellows111 @bigol83 if you guys could retest your respective games and make sure they're still working, I'd appreciate it.

The torch graphic issue has been fixed but now the thick black borders have returned
[Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230315111015.gs.zip](https://github.com/PCSX2/pcsx2/files/10978539/Dragon.Quest.VIII.-.Journey.of.the.Cursed.King_SLES-53974_20230315111015.gs.zip)
Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230315111015

This game is never happy. 😐

**Comment by refractionpcsx2** [comment]
> Enabling textureInsideRT fixes the slow motion effect, but this PR causes lots of junk to appear for a single frame during a blur transition in Metal Gear Solid 2 even without enabling textureInsideRT

Can I get a GS Dump of that @Toastarrr because I can't reproduce it from the existing ones.

**Comment by refractionpcsx2** [comment]
@bigol83 I find that changing the upscaling hacks to use "round sprite (full)" instead fixes the black lines leaking down the screen, but I don't know what impact that'll have on the rest of the game.

Anyway, in true me fashion, I'm changing how stuff works again, so probably gonna be changing this again. Iterative work is fun lol

**Comment by Toastarrr** [comment]
> > Enabling textureInsideRT fixes the slow motion effect, but this PR causes lots of junk to appear for a single frame during a blur transition in Metal Gear Solid 2 even without enabling textureInsideRT
> 
> Can I get a GS Dump of that @Toastarrr because I can't reproduce it from the existing ones.

[Google drive link to gs dump](https://drive.google.com/file/d/1sUW2rXHk2XnIUcCCAWbiLDO4KOGLBCQH/view?usp=share_link)
I found that when I load from a save state that's closer to the junk frame, the effect works properly, but when I use a save state that's a couple of seconds older, you get the junk frame consistently

**Comment by Toastarrr** [comment]
> yes savestates may contain junk because the hardware renderer tries not to write information back to the GS memory, so it may just contain junk, and none of it is restored when you load a state, the only way you can try to avoid that is if you enable the "Read Targets When Closing" hardware fix, that will force it to flush things back to GS memory when making a savestate

GS dump looks the same on Master and PR, but it definitely only breaks on PR even using the exact same save state.

[Google drive link to save state SLUS-20144](https://drive.google.com/file/d/12lrOXHpmRamQ-l-aFh6QzBDz0ZU75rhC/view?usp=sharing)

**Comment by refractionpcsx2** [comment]
Okay yeah I can reproduce it with the savestate but not on master, looks like there's a bad GS Download happening, which would explain why it's baked in to the GS Dump you uploaded.

**Comment by refractionpcsx2** [comment]
okay that should be Metal Gear fixed up now, my bad :)

**Comment by Toastarrr** [comment]
I don't know if I'm just missing it or the effect is broken in a less visible way, but even without the textureInsideRT fix the boxes during slow motion and during the intro in MGS2 seem to be gone. They don't appear with the fix enabled either.

**Comment by yellows111** [comment]
> @yellows111 if you guys could retest your respective games and make sure they're still working, I'd appreciate it.

```
[   58.6587] (UpdateVSyncRate) Mode Changed to NTSC.
[   59.7998] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_1.txt
[   59.8133] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_2.txt
[   60.1292] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_3.txt
[   60.3967] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_4.txt
[   65.9697] (UpdateVSyncRate) Mode Changed to NTSC.
[   65.9904] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_5.txt
[   66.9977] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_6.txt
[   76.7978] (UpdateVSyncRate) Mode Changed to NTSC.
```
Title screen:
```
[  265.7239] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_7.txt
[  265.7277] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_8.txt
[  266.6898] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_9.txt
[  281.3541] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_10.txt
[  281.6045] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_11.txt
[  281.6068] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_12.txt
[  281.6090] CompileShaderToSPV: Failed to parse shader, writing to pcsx2_bad_shader_13.txt
```

[GS-HW/VK] was tested, but hotswitching between all HW renderers left a lot of
```
[  440.3744] 0(371) : error C1503: undefined variable "PS_SCALE_FACTOR"
```
's in the console for D3D11/D3D12. Safe to say, all HW renderers have been "amazingly broken".
Going to GS-SW... Now there's a texture seam on the menu with the default config.

Poinie's Poin_SCPS-15013_20230315170722
[Poinie's Poin_SCPS-15013_20230315170722.gs.gz](https://github.com/PCSX2/pcsx2/files/10982793/Poinie.s.Poin_SCPS-15013_20230315170722.gs.gz)

Poinie's Poin_SCPS-15013_20230315170221
[Poinie's Poin_SCPS-15013_20230315170221.gs.gz](https://github.com/PCSX2/pcsx2/files/10982787/Poinie.s.Poin_SCPS-15013_20230315170221.gs.gz)

Safe to say multiple things have went very wrong between the last time i've tested this game.

**Comment by refractionpcsx2** [comment]
That sounds like you've half updated, you're using an old version with new shaders, or visa versa.

**Comment by yellows111** [comment]
> That sounds like you've half updated, you're using an old version with new shaders, or visa versa.

Good old "forgetting the recursive extraction parameter" never fails to get me.

Alright, let's actually try this.

Text works.
Poinie's Poin_SCPS-15013_20230315172128

Motion Blur works fine.

https://user-images.githubusercontent.com/25440281/225390860-d0776928-cc9e-47cc-9247-0e8ffffa2ccf.mp4

**Comment by refractionpcsx2** [comment]
awesome :) I can confirm the software mode line in the menu, but I tried a build around 3600 (about 6 months or so ago) and it was still a problem then.

**Comment by refractionpcsx2** [comment]
@yellows111 sorry was that withor without Tex in RT? Need to know if I have to add it to the DB or not.

**Comment by yellows111** [comment]
> @yellows111 sorry was that with or without Tex in RT? Need to know if I have to add it to the DB or not.

Tested the above (https://github.com/PCSX2/pcsx2/pull/8289#issuecomment-1470449704) with Inside Targets, which is GameDB'd already for that check

Text is still broken without it, after all.
Poinie's Poin_SCPS-15013_20230315214537

**Comment by refractionpcsx2** [comment]
oh it's already in the DB, that's fine then! :)

**Comment by MetrosexualGarbodor** [comment]
"Inside Target" does indeed fix the crystals in Xenosaga III, but it still breaks the intro.

image

**Comment by refractionpcsx2** [comment]
alright, that's a shame, but I'll check the intro out. thanks for checking!

**Review by Mrlinkwii — APPROVED** [review]

**Comment by refractionpcsx2** [comment]
Kind of a late improvement, not perfect still but it's certainly better.

WRC 4:

Master:
image

PR:
image

**Comment by refractionpcsx2** [comment]
@MetrosexualGarbodor sorry can you test a new build of this PR again on Xenosaga, I think I caught the problem you were having.   If you turn all manual fixes off and let the auto fixes happen (I've put the tex in rt stuff on in the DB) and let me know if everything is good? Thanks :)

**Review by Toastarrr — APPROVED** [review]
The MGS2 "box" artifact seems to be gone, the slow motion effect works, and the blur doesn't create the junk frame. Excellent PR as far as MGS2 is concerned.

**Comment by refractionpcsx2** [comment]
Thanks @Toastarrr !

**Comment by MetrosexualGarbodor** [comment]
With the latest changes, the intro no longer breaks and the crystals are still fixed. 
image
image

I also checked several other parts of the game that usually have trouble and couldn't find anything else broken. All of this on Vulkan.

After this, the only remaining issues with Xenosaga III will be that weird ceiling shadow and the upscaling problems. Nicely done. 👍

**Comment by refractionpcsx2** [comment]
nice! Thanks for testing! :)

**Review by JordanTheToaster — APPROVED** [review]

**Comment by CookiePLMonster** [comment]
Regresses reflections in The Getaway.

v1.7.4244:
image

v1.7.4245:
image

**Comment by stenzek** [comment]
For documentation's sake, I'll copy/paste what I said here:

> start of frame, then it draws the reflection map (128x128) to 2800(RT)+2C00(Z)
> then it downloads 2800
> then it swaps to 640x448 1180(RT)+2300(Z)
> so it's putting the reflection RT in the middle of the depth for the last frame
> surely it clears for the reflection RT.. yep, it does
> so we'd need to kill any overlapping targets on clear, not targets which are fully contained by the clear
> and that seems like a big risk

**Pull request merged**
