### PR TITLE
GameDB: Add several XGKick hacks

### PR DESCRIPTION
**Pull request by FlatOutPS2**
Add XGKicks for Formula One 2001-2003 and World Of Outlaws - Sprint Cars to GameIndex file.

### CODE REVIEW

**Comment by bositman** [comment]
Would be nice to note what the gamefix fixes in the games

**Comment by refractionpcsx2** [comment]
> Would be nice to note what the gamefix fixes in the games

how do you mean? You mean on the forums?

**Comment by bositman** [comment]
With the commit message

**Comment by refractionpcsx2** [comment]
Most of them are in there :P

**Pull request merged**
