### PR TITLE
pad-linux: Add unsupported gamepad

### PR DESCRIPTION
**Pull request by AmFobes**

### CODE REVIEW

**Review by RedDevilus — CHANGES_REQUESTED** [review]
Should be alphabetically instead of L514 use L459 or something it has the same type of controller.

**Comment by lightningterror** [comment]
Can you also pr it upstream?

**Comment by AmFobes** [comment]
You mean here?
https://github.com/gabomdq/SDL_GameControllerDB/pull/418

**Comment by lightningterror** [comment]
Ah nice you already did it.

**Pull request closed without merging**
