### PR TITLE
[GSdx] Added temperature setting

### PR DESCRIPTION
**Pull request by Dogway**
Port from libretro's white_point shader.

### CODE REVIEW

**Comment by lightningterror** [comment]
You need to port the shader code to GSdx.fx as well.

**Comment by Dogway** [comment]
Yes, now I did, my bad for pulling this one first.

**Comment by lightningterror** [comment]
You can rebase and put the changes on to the same commit, no need to open separate prs.

**Comment by Dogway** [comment]
Sorry, first time here, I don't know how to put the commit on the same pr.

**Comment by lightningterror** [comment]
You need to either use Git or Github desktop and from there you can use git shell to properly rebase, squash commits ...etc

**Comment by Dogway** [comment]
Ok, now is well I think in #2989, this can be closed.

**Pull request closed without merging**
