### PR TITLE
IOP: Run the SPU at a consistent rate

### PR DESCRIPTION
**Pull request by Ziemas**
I guess this is more of an RFC than a PR, but having this code here doesn't make much sense to me so let's figure out if it's still useful.

```
Run the SPU once per 768th IOP cycle. And stop adjusting the SPU's
target cycle in IopDma, doing this makes little sense the SPU2 is so eager
about running itself on interactions from the core.

If we need finer timing for DMA transfers we could just run the SPU2
more often than every 765th cycle, it should handle that fine as far as
I can tell.
```

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
There's a bit of a problem with running every 768 cycles, that french game Titeuf runs slow and stutters internally if you sync every 768 cycles, * 12 is fine, any less and it gets weird.

I had changed this back to 768 cycles earlier until I discovered it caused problems and I changed it back again.

**Comment by Ziemas** [comment]
Ok, good to know. I'll check that out myself and see if I can figure anything out.

**Comment by gilderoylockhart01** [comment]
What is the status of this PR?

**Comment by refractionpcsx2** [comment]
I believe last it was touched Titeuf Mega-compet still had the stuttering issue with this.

**Comment by lightningterror** [comment]
Closing as it's not worked on atm.

**Pull request closed without merging**
