### PR TITLE
gsdx ogl: add an HLE shader to avoid upscaling line in ICO

### LINKED ISSUE #1816: Ico white lines
***PCSX2 version:***

1.5.0-dev-1882-g213fa1c

***PCSX2 options:***
-Using OpenGL (Hardware) "Tested too with DX11 hardware, but the problem is worse"
-Tested with/without widescreen patch
-Tested with trilinear ultra and bilinear ps2 filtering
-Using mipmaping basic
-Half pixel offset hack
-3x Internal resolution
-Accurate date
-Blending unit accuracy set to High
-CRC level: Partial
-Interlacing: Auto

***Plugins used:***
AVX2

***Description of the issue:***

White lines all of time you are near a wall.

***PC specifications:***
I7 4790k 4.4 GHZ
GTX 970
16 GB DDR3

Note: 2 Images and 1 link with two videos attached (The link of the videos expire in 1 week)
ico bug 2
ico bug 1

Link with the videos: https://we.tl/P7nIh8FNzK

### PR DESCRIPTION
**Pull request by gregory38**
ICO uses a depth of field effect for the fog. Depth is extracted
into the alpha channel of a texture. And then used as blending factor.
You need a 1:1 texture/pixel mapping otherwise you will line at boundaries.

In order to extract the DoF, ICO moves the depth buffer around the GS
memory. Memory moves are implemented in the not-scaled world. It means
that we can't have the above 1:1 ratio. And we don't know anymore that
data are coming from the current depth buffer.

The solution: I added a dedicated shader to read the depth buffer directly.
This way I have the guarantee that pixel/depth are aligned.

Close #1816

### CODE REVIEW

**Comment by gregory38** [comment]
@prafullpcsx2 a :gift: for you :smile:

**Comment by gregory38** [comment]
I forget to say you need at least CRC hack on minimum.

**Comment by FlatOutPS2** [comment]
> I forget to say you need at least CRC hack on minimum.

And below Full, otherwise the effect will be disabled.

**Comment by gregory38** [comment]
Actually maybe I can reuse others part of shader
* PS_DEPTH_FMT == 1 or 2
* PS_CHANNEL_FETCH == 3

It would reduce the size of the PR.

**Comment by prafullpcsx2** [comment]
Thanks @gregory38 .

This also fixes similar problem with Kya - Dark Lineage. I believe many other games suffer from this problem. I think instead of game specific crc it will be better to keep this in HW hacks.

**Comment by gregory38** [comment]
Honestly I would be surprised it works well for other games. Tbh I even surprised that it didn't break ICO. So far, when we have a display texture that is blended, the hack will sample from the current depth instead of the texture. It "works" because the texture is the depth that was moved. However I don't have any guarantee that it isn't a color buffer instead.

Note for myself​: check that current texture isn't already a known color/depth buffers. Might avoid some bad cases.

**Comment by lightningterror** [comment]
> Honestly I would be surprised it works well for other games.

Which other games do you think it can work for ?

**Pull request merged**
