### PR TITLE
GS: Only autoflush on move/self blend (Perf test)

### PR DESCRIPTION
**Pull request by refractionpcsx2**
Also Move overlap check to State

### Description of Changes
Attempts to improve performance when Auto Flush is enabled

### Rationale behind Changes
Auto Flush was very aggressive, this aims to cut down on aggressive flushing to hopefully improve performance a bit when Auto Flush is enabled (Especially in software)

### Suggested Testing Steps
Test games that require auto flush, make sure they aren't broken, compare performance with master.

Note: This might never get merged if it breaks a ton of stuff! If not then it's a good bonus!

### CODE REVIEW

**Comment by RedDevilus** [comment]
https://github.com/PCSX2/pcsx2/issues/5081

Might help?

**Comment by refractionpcsx2** [comment]
> #5081
> 
> Might help?

Forgot there was a meta, thanks!

**Comment by DonelBueno** [comment]
Is there a list of games that need autoflush? The only ones I know are the Syphon Filter ports from the PSP.

**Comment by JordanTheToaster** [comment]
Substatial performance increase with autoflush in software on NFS Underground 2.

Master
AF-Mster 1


PR
AF-PR 1

**Comment by refractionpcsx2** [comment]
> Is there a list of games that need autoflush? The only ones I know are the Syphon Filter ports from the PSP.

Not sure there is, I know Driv3r and GTA SA need it, but beyond that, I'm basically relying on the Wiki

**Comment by RedDevilus** [comment]
Default HW no autoflush:
image
Default SW with autoflush:
image
60-140 VPS (50 VPS is the normal because PAL)
HW with autoflush:
image
250-330 VPS but with artifacts

**Comment by RedDevilus** [comment]
[AlterEchoHWautoflush.zip](https://github.com/PCSX2/pcsx2/files/7918921/AlterEchoHWautoflush.zip)

**Comment by gilderoylockhart01** [comment]
I can handle the testing for that, I have several games which I know requires it at specific spots or with some specific effects.

I will update the thread with what I find.

**Comment by HelicopterP** [comment]
From the top of my head - Burnout 3 (sun is shinig through objects without it) and Jak 2 (shadows are messed up without it) need autoflush. I am unable to test this games at the moment, unfortunatelly.

**Comment by refractionpcsx2** [comment]
I just checked Jak 2, the shadows look the same to me with or without Auto Flush (even on master).  Not sure the best place to check Burnout 3, a GS Dump would be cool.

**Comment by gilderoylockhart01** [comment]
In Jak 2 the performance is almost not improved at all, actually, the game needs auto flush for an other rendering problem which is hard to track:

When approaching a volumetric effect, there is a sort of trail following the character, this effect needs auto flush in order to work as you can see here:

No AF:
Capture d’écran 2022-01-22 192727

AF:
Capture d’écran 2022-01-22 192709

The problem here is the absolutely terrible framerate, it's extremely slow with the hardware render in comparison to the software render.

**Comment by refractionpcsx2** [comment]
My Apologies, the HW auto flush option inteferes with the SW one, so they both need to be off if you want to toggle it for one renderer, mildly annoying! maybe we should combine the boxes.

Anyway I just made another change which makes it auto flush less, might be a bunch faster in some games.

**Comment by gilderoylockhart01** [comment]
Yeah, better combining this for booth render, it's far from a hack anyway.

Also, as a side note, some games will need to have auto flush AND memory wrapping enabled for some effects to work, memory wrapping is still a hack, which makes... little sense I guess considering it's more accurate to what a real console does.

**Comment by gilderoylockhart01** [comment]
In Jak 2, I can get full speed with auto flush and native resolution, anything higher (even 2x) will be super slow.

**Comment by refractionpcsx2** [comment]
weird, for me Jak 2 (at the start of the game) I go down from 115fps to 83fps, roughly, that's at x4

**Comment by gilderoylockhart01** [comment]
Excuse me, I didn't explain enough, Jak 2 will only be super slow when in front of that volumetric effect, if not the game will be fast yeah. I guess I will create a gsdump

As for Tekken Tag tournament, it's a *massive* improvement, goes from 50 ish % to almost 400% in the menus at 8x.

**Comment by gilderoylockhart01** [comment]
Here is the GSdump for Jak 2 and it's slow auto flush problem:
[Jak 2 slow auto flush.zip](https://github.com/PCSX2/pcsx2/files/7919094/Jak.2.slow.auto.flush.zip)

**Comment by gilderoylockhart01** [comment]
MGS2 transparency effects in the intro are not super slow as they used to be with auto flush hardware (there are still some slowdowns and minor glitches but those are different problems):

https://user-images.githubusercontent.com/90222976/150652647-e08ad719-ed53-4950-97f1-c0995cc5cb98.mp4

**Comment by refractionpcsx2** [comment]
Okay I see the problem with Jak 2, the number of texture copies blows up, so yeah that will screw the speed, that will have to be a thing for now.

**Comment by gilderoylockhart01** [comment]
007 is now fully accurate to what a real PS2 does (auto flush helps with the car's reflections), and this without tanking the frame-rate, isn't that beautiful ^^ (the only little gremlin is minor Z-fighting but that is common on the hardware renders):

https://user-images.githubusercontent.com/90222976/150653905-a0a595de-e89c-4c05-926b-1ebc000c6740.mp4

(PS, yeah, terrible video quality but hey, 10mb limit it is).

**Comment by refractionpcsx2** [comment]
Nice :)

**Comment by gilderoylockhart01** [comment]
I just have a random question about Ratchet shadows, why does the Vulkan and OpenGL hardware render renders them fine without auto flush?

**Comment by refractionpcsx2** [comment]
> I just have a random question about Ratchet shadows, why does the Vulkan and OpenGL hardware render renders them fine without auto flush?

on DX Auto Flush is kind of a hack for Ratchet because DX doesn't have barriers.

**Comment by gilderoylockhart01** [comment]
Ok, I said that because it's painfully slow with DX yeah.

**Comment by gilderoylockhart01** [comment]
Mmm, I have one weird case, catwoman is still fine with the software render (the game needs auto flush to prevent an image ghosting problem), but the hardware render is still bad, even with auto flush on, that's not an issue with this PR, but it is still something worth to look into:

Hardware render:

gs_20220123141311

Here is the dump:
[Catwoman broken auto flush hardware.zip](https://github.com/PCSX2/pcsx2/files/7920558/Catwoman.broken.auto.flush.hardware.zip)

**Comment by HelicopterP** [comment]
Ok, this is just for completion sake as this 2 games were mentioned before. Here are GS dumps with sun shining through a bridge in B3 and messed up shadows in J2 without autoflush. This two problems are unrelated to this PR. As far as I can see the behaviour is the same as master. Autoflush should be enabled in software mode for this two games to fix glitches. I repeat: unrelated to this PR. End of offtopic :p
[Burnout 3 sun.zip](https://github.com/PCSX2/pcsx2/files/7920622/Burnout.3.sun.zip)
[Jak 2 shadows.zip](https://github.com/PCSX2/pcsx2/files/7920623/Jak.2.shadows.zip)

**Pull request merged**
