### PR TITLE
GameDB: Various Depth Line and Upscaling Fixes

### PR DESCRIPTION
**Pull request by jeremybris**
### Description of Changes
Various HW Hack settings to fix depth issues and upscaling, including half-pixel offset, skipdraw, and wild arms hack.

| No Skipdraw | Skipdraw Fix | 
| ------------- | ------------- | 
| I-Ninja Screenshot 2022-03-15 122559 | I-Ninja Screenshot 2022-03-15 122618 | 
| Shrek 2Screenshot 2022-03-15 122209 | Shrek 2 Screenshot 2022-03-15 122150 | 
| TimeSplitters 2 Screenshot 2022-03-15 121239 | TimeSplitters 2 Screenshot 2022-03-15 121208 | 

### Rationale behind Changes
Better default graphical experiences for users.

### Suggested Testing Steps
Please test the games for any regressions, and check my code as well. 

I'm not sure, but I think the skipdraw values may be different with an Nvidia GPU, because I just came from an Nvidia GPU, and I vaguely remember them being higher. Can anyone confirm on any of these games with an Nvidia GPU? All of the skipdraw values are "1", except for Shrek 2, which is "2". 

Are these good changes? Tested with Ryzen 3900x, 6900 xt, Windows 11 latest version.

### CODE REVIEW

**Comment by jeremybris** [comment]
> Those aren't fixes, you're skipping the effects, you should try and see if any of the other hacks resolve the issues.

I agree with you. They are hacks. I thought that would be ok for the "gsHWHacks" section. I have already tried many settings, but I will try all of the "HW Hacks" settings when I get home from work.

**Comment by jeremybris** [comment]
After testing, skipdraw is the only hack that improves these issues. I found “Disable Depth Emulation” hack also effects these games, but does not improve the issues. Furthermore, the “Wild Arms Hack” helps to improve TimeSplitters 2 upscaling individually and even more.

Also, Github is telling me there is an error, because the value of skipdraw and skipdraw offset "must be between 0-1". It should be 2 for Shrek 2. What am I doing wrong?

**Comment by jeremybris** [comment]
> `After testing, skipdraw is the only hack that improves these issues. I found “Disable Depth Emulation” hack also effects these games, but does not improve the issues. Furthermore, the “Wild Arms Hack” helps to improve TimeSplitters 2 upscaling individually and even more.`
> 
> Are the issues also present on native resolution?

Yes, on all of them any HW mode. (No, on "Software" mode). 

I'm not getting this issue on the Burnout games anymore for some reason. Maybe it's because I updated PCSX2 recently, and there is a hack already present: "halfPixelOffset: 2 # Fixes depth lines.".

**Comment by jeremybris** [comment]
So half-pixel offset set to 2/"Special (Texture)", mitigates the issue for I-Ninja, but it is still there. For Shrek 2 and TimeSplitters 2, it has no effect. Going to update the PR, by removing Burnout hacks.

**Comment by refractionpcsx2** [comment]
Can you put a space after the # for your comments. Also remove the "see PR #5666 for more details", I'd rather the GameDB wasn't littered with things like that, the comment should be enough to describe the issue it's fixing.

Thanks

**Comment by jeremybris** [comment]
Changed, Squashed, and Rebased, I think.

| No Skipdraw | Skipdraw Fix | 
| ------------- | ------------- | 
| [GSDumps Link](https://drive.google.com/drive/folders/1PVpybu6ueFWu5U2GcbQIAsNMUsgMb9Kz?usp=sharing) | [GSDumps Link](https://drive.google.com/drive/folders/1yL2SreUKrWCbmrNPzL-sq1lWLOkmTC4J?usp=sharing) |

**Comment by refractionpcsx2** [comment]
ok thanks for doing that, but can you please change the commit message to be something more akin to our commit names, like
GameDB: Added various upscaling and HW fixes

or something. thanks :)

**Comment by jeremybris** [comment]
> ok thanks for doing that, but can you please change the commit message to be something more akin to our commit names, like GameDB: Added various upscaling and HW fixes
> 
> or something. thanks :)

Yes, sorry, I am learning Github as a student. And I appreciate your patience and communication.

**Comment by refractionpcsx2** [comment]
The way I would do it (i use TortoiseGit so it might be different for you), update your master branch that you branched from, rebase your new branch with the remote being the FETCH_HEAD, then fix your conflicts, and commit, squash any new commits then force push.

**Comment by jeremybris** [comment]
I found more. Rebasing, squashing, and adding to the PR. Let me know if you dislike or like any of these changes, because they can be added by someone else, individually.

| No Fix | GameDB Fix | 
| ------------- | ------------- | 
| James Bond 007: From Russia with Love Screenshot 2022-03-18 142523 | James Bond 007: From Russia with Love (Half-Pixel Offset: 2) Screenshot 2022-03-18 142459 | 
| James Bond 007: Everything or Nothing Screenshot 2022-03-18 143743 | James Bond 007: Everything or Nothing (Half-Pixel Offset: 2) Screenshot 2022-03-18 143805 | 
| The SpongeBob SquarePants Movie Screenshot 2022-03-18 161236 | The SpongeBob SquarePants Movie (Half-Pixel Offset: 2) Screenshot 2022-03-18 161301 | 
| Just Cause Screenshot 2022-03-18 145930 | Just Cause (Half-Pixel Offset: 2, Wild Arms Hack: 1) Screenshot 2022-03-18 145914 | 
| Tony Hawk's American Wasteland Screenshot 2022-03-18 144545 | Tony Hawk's American Wasteland (Skipdraw: 1, Skipdraw Offset: 1, Wild Arms Hack: 1) Screenshot 2022-03-18 144520 | 
| Tony Hawk's Underground 2 Screenshot 2022-03-18 144855 | Tony Hawk's Underground 2 (Skipdraw: 1, Skipdraw Offset: 1, Wild Arms Hack: 1) Screenshot 2022-03-18 144913 | 
| The Incredible Hulk Screenshot 2022-03-18 152956 | The Incredible Hulk (Skipdraw: 1, Skipdraw Offset: 1, Wild Arms Hack: 1) Screenshot 2022-03-18 152938 |

**Comment by refractionpcsx2** [comment]
yeah I tried one of the other Tony Hawks games and didn't push any fixes for the same reason, the merge sprite completely removes the shadows.

You also need to rebase your branch cos you have conflicts.

**Comment by jeremybris** [comment]
> yeah I tried one of the other Tony Hawks games and didn't push any fixes for the same reason, the merge sprite completely removes the shadows.
> 
> You also need to rebase your branch cos you have conflicts.

You are right. I did not notice that shadows are gone. These settings slightly improve visuals. Also, nevermind about Hulk, I am not getting that visual error anymore. I will try to rebase again.

mergeSprite: 1
wildArmsHack: 1
halfPixelOffset: 2

| No Fix | GameDB Fix | 
| ------------- | ------------- | 
| Screenshot 2022-03-18 183444 | Screenshot 2022-03-18 183421 |

**Comment by RedDevilus** [comment]
Can you change the comments to not mentions hack, people always gets wrong ideas about them besides it's useless for what it fixes.

**Comment by RedDevilus** [comment]
I'm also not that comfortable doing skipdraw, it looks to me you just enabled some random settings. Can you make comparison with and without skipdraw?

**Comment by RedDevilus** [comment]
image
image

I'm convinced these games are fixed with halfpixel offset 2 (Special Texture). It really feels you enabled some random settings to try and fix it.

**Comment by jeremybris** [comment]
Yes, I will remove # hack. The skipdraw are for three games now: I-Ninja, Shrek 2, and Timesplitters 2. The picture comparisons are in the original post, and GSDump comparisons are above in the comments. I can post more, if the pictures are unclear.

**Comment by jeremybris** [comment]
I tried half-pixel offset 2 (Special Texture), and it did not work for me. If it seems like random settings, that is probably because I have tried all the settings, and that is the only thing that worked. I will edit this post later with pictures of half offset 2.

**Comment by RedDevilus** [comment]
To be plain: You are using skipdraw too freely it should be last option for. In it's current state it won't be merged.

Just being honest that people don't know how to use the correct settings.

**Comment by refractionpcsx2** [comment]
You need to rebase and update your code, skipDraw and skipDrawOffset don't exist anymore, they are now skipDrawStart and skipDrawEnd, but do that once you've rebased.

**Comment by jeremybris** [comment]
> You need to rebase and update your code, skipDraw and skipDrawOffset don't exist anymore, they are now skipDrawStart and skipDrawEnd, but do that once you've rebased.

I will update those lines, thank you. Does a "Force Push" include a rebase? If not, I will have to rebase another way.

**Comment by RedDevilus** [comment]
Force push on it's own doesn't mean it will be a rebase. It's more that you don't sync from GitHub and push your own commits for the PR. But yeah I normally do `git rebase -i HEAD~3`  (3 being used as example of commits on the PR) and then replace everything but the first as fixup (basically squash but discard their messages) and save it from editor.
Finally doing `git push -f`. Though there are many ways on how you want to do the rebase.

**Comment by refractionpcsx2** [comment]
Yeah don't do merge commits, they don't fix the problem. you need to rebase then force push your changes. You're currently still conflicting with our master branch (maybe you need to rebase your master branch first?)

**Comment by jeremybris** [comment]
I deleted my commit by accident. I really appreciate everyone's help though (telling me about TortoiseGit helped a lot). I will practice rebasing on my own. Going to close, because I messed this up, and I am going to sleep.

Here's the code: https://github.com/jeremybris/pcsx2/commit/d5f2f884614b23ced1feced3850d6a2e9200c404 . If I remove skipdraw (and rebased), does eveything else look good? I used skipdraw as a last resort. Shrek 2 is the only game that badly needs it, and it is the only way to fix that game (besides fixing innate, depth issues).

**Comment by refractionpcsx2** [comment]
Since you were having trouble, I have thrown together a TortoiseGit Survival Guide for you, it walks you through all the things you will need to do to handle a Git repo with us.

[TortoiseGit Survival Guide.txt](https://github.com/PCSX2/pcsx2/files/8308526/TortoiseGit.Survival.Guide.txt)

**Comment by jeremybris** [comment]
I am teaching myself, so this will legit be my bible. Thank you for your help refraction!

**Pull request closed without merging**
