### PR TITLE
Greg/gsdx berserk 1526

### PR DESCRIPTION
**Pull request by gregory38**
First commit might require some tests.

### CODE REVIEW

**Comment by FlatOutPS2** [comment]
Does it require testing because it could trigger a regression in some games(if so, any likely candidates)?

**Comment by gregory38** [comment]
Try those games
* https://github.com/PCSX2/pcsx2/issues/1269
* Metal gears solid 3
Honestly texture cache updates are :scream: :gun:

**Comment by FlatOutPS2** [comment]
I had a hunch and was right, this also fixes the HUD on WWE Smackdown Shut Your Mouth! :+1:

**Comment by gregory38** [comment]
HW renderer ? Nice :smiley:

**Comment by FlatOutPS2** [comment]
It was broken on all renderers, now it's fixed on all renderers. ;)

**Comment by gregory38** [comment]
Oh even the SW renderer. Could you tell me if it is the 2nd or the 3rd commit that fix it.

**Comment by FlatOutPS2** [comment]
Sure, I'll check which one fixes it later.

I linked this HUD issue in https://github.com/PCSX2/pcsx2/issues/1562

So you can mark that one as solved when it's been merged.

**Comment by FlatOutPS2** [comment]
The Smackdown HUD issue is also solved by the 8 bits commit, so no 4 bits case yet. :p

**Comment by gregory38** [comment]
Ok. Honestly I'm already surprised that more 1 game uses this trick. I added the 4 bits because pseudonym told me that we ought to emulate all the cases. In doubt, it can't hurt, can it?

**Comment by FlatOutPS2** [comment]
I'm sure that it'll fix some game. If someone is crazy enough to use the illegal 8 bits, it's very likely there's someone crazy enough to use 4 bits as well.

**Comment by FlatOutPS2** [comment]
Test Drive Pause menu HUD is fixed by the first commit. :)

**Comment by gregory38** [comment]
Very good. 3 games fixed in one shot.

**Comment by FlatOutPS2** [comment]
The PR also seems to show a new effect that occurs when taking a picture of a ghost in Project Zero. Actual ghost still a no show in HW though. :p

**Comment by gregory38** [comment]
new effect ?

**Comment by FlatOutPS2** [comment]
It's new to PCSX2, as in as far as I know it has never been visible in earlier versions. ;)

**Comment by gregory38** [comment]
sw or hw ?

**Comment by FlatOutPS2** [comment]
Both I believe, but it's very noticeable in HW because the ghost itself is invisible(the effect occurs around the outline of the ghost).

**Comment by gregory38** [comment]
Maybe it would be easier to generate a nice dump so I can properly reproduce the ghost issue on my side.

**Comment by gregory38** [comment]
I pushed the 8/4 bits frame format to the master. Only remain the texture cache change that is unsafe.

**Comment by FlatOutPS2** [comment]
Played a bit in MGS3 but I didn't notice any regressions.

**Pull request merged**
