### PR TITLE
Debugger: use ulonglong for memory search + fix crash

### LINKED ISSUE #8420: [BUG]: Cannot search for values greater than 0x7FFFFFFF in memory search
### Describe the Bug

Cannot search for values greater than 0x7FFFFFFF in 4 and 8 bytes of type.
Is this a limitation of integer values?
This is a bit inconvenient because some opcodes have values greater than 0x7FFFFFFF.
Values greater than 0x7FFF by 2 bytes of type are searchable.

### Reproduction Steps

Launch the game.
Open the debugger.
Open the MemorySearch tab.

### Expected Behavior

Search for values greater than 0x7FFFFFFF.

### PCSX2 Revision

v1.7.4240

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### PR DESCRIPTION
**Pull request by Toastarrr**
### Description of Changes

Converts the value we're searching for to ulonglong instead of long

Fixes crash caused by searching for a value larger than the type
### Rationale behind Changes

Should fix #8420. Long was also not big enough to search for 64 bit values, so longlong should be used instead.
### Suggested Testing Steps

Search for values greater than 7FFFFFFF in the debugger. It should allow you to now.

An error box should now prevent you from searching for a value higher than the type you're searching for. On master, doing this causes PCSX2 to stop responding and begin rapidly consuming memory until it presumably crashes.

### CODE REVIEW

**Comment by Toastarrr** [comment]
Might be useful to eventually add a little box you can tick for signed values, but at least with this you can still search for them, you just need to convert to unsigned.

**Review by F0bes — COMMENTED** [review]
Might be nicer using `std::numeric_limits<type>` instead of using constant values such as `0xFFFFFFFFFFFFFFFF`

**Comment by Toastarrr** [comment]
> Might be nicer using `std::numeric_limits<type>` instead of using constant values such as `0xFFFFFFFFFFFFFFFF`

How does this look?

**Comment by refractionpcsx2** [comment]
Small nitpick, but for cases 6, 5 and 4, since all they do is break, you could remove the break from the top two so it just falls in to case 4, just condenses things a little :)

**Comment by Toastarrr** [comment]
> Small nitpick, but for cases 6, 5 and 4, since all they do is break, you could remove the break from the top two so it just falls in to case 4, just condenses things a little :)

Fixed. It looks neater now. Thank you!

**Review by F0bes — APPROVED** [review]
Looks fine to me

**Pull request merged**
