### PR TITLE
Auto depth skip hack initialization.[GUI]

### PR DESCRIPTION
**Pull request by ssakash**

### CODE REVIEW

**Comment by ssakash** [comment]
The following PR creates an dual state checkbox for the new Autodepthskip hack which was recently added as an customizable option.

I request further testing from Windows users before merging it.

**Comment by ssakash** [comment]
don't merge the PR yet, I have to make sure that it doesn't cause any conflicts in the resource.h file in comparison to the other commits.

**Comment by gregory38** [comment]
Can I merge it or not?

**Comment by ssakash** [comment]
yes, you can merge it.

**Comment by tsunami2311** [comment]
unless i mistaken about what this is ment to do, that hack isnt in the gsdx config window or the hw hack section

**Comment by refractionpcsx2** [comment]
I fixed your button for you so windows hosts can compile it :P

**Comment by ssakash** [comment]
Thanks @refractionpcsx2  :+1:

**Pull request merged**
