### PR TITLE
Update GSCrc.cpp

### PR DESCRIPTION
**Pull request by puzzo888**

### CODE REVIEW

**Comment by ssakash** [comment]
A more descriptive commit message might be useful, other than that LGTM 👍

**Comment by FlatOutPS2** [comment]
Do we add iso hacked (translation)CRC's to the database?

**Comment by danilaml** [comment]
Now it just changes tabs to spaces on one line and nothing else.

**Comment by gregory38** [comment]
So I disagree to add tons of hacked iso in the code. Otherwise, the PR is now empty so I will close it.

**Pull request closed without merging**
