### PR TITLE
Make Game Properties accessible from the toolbar

### PR DESCRIPTION
**Pull request by CookiePLMonster**
### Description of Changes
This PR changes the behaviour of the toolbar's `Settings` button:
* When the game is not running, open Global Settings (same as it is now).
* When the game is running, open a small context menu that allows the user to open Global Settings or Game Properties.

image

It also removes `File -> Settings` for consistency with DuckStation, besides a whole Settings menu is right next to it.

### Rationale behind Changes
More intuitive access to Game Properties, also signaling clearly what is what - currently it may be unclear whether clicking `Settings` changes global or per-game settings.

### Suggested Testing Steps
Make sure UI works as described.

### CODE REVIEW

**Review by Mrlinkwii — APPROVED** [review]

**Comment by JordanTheToaster** [comment]
When running a game clicking View no longer shows an option to go to game properties.

**Comment by CookiePLMonster** [comment]
It's been moved to `Settings`.

**Comment by JordanTheToaster** [comment]
> It's been moved to `Settings`.

It should still be in View as not everyone uses the toolbar.

**Comment by CookiePLMonster** [comment]
> > It's been moved to `Settings`.
> 
> It should still be in View as not everyone uses the toolbar.

image

**Review by JordanTheToaster — APPROVED** [review]
I am blind

**Pull request merged**
