### PR TITLE
Atomic v2

### PR DESCRIPTION
**Pull request by gregory38**
The PR replaces most of the old volatile code to real atomic. The remainings volatile are in MTVU/MTGS ring buffer. The ring buffer will need special memory access to keep performance optimization. To be safe, let's defer it for later.

### CODE REVIEW

**Comment by gregory38** [comment]
@turtleli by any chance, do you have any idea what it is wrong with clang? Otherwise I will just put back the volatile for the enum variable.

**Comment by turtleli** [comment]
Not really, I need to see whether it compiles with clang on my system, just in case it's a Travis CI thing.

**Comment by gregory38** [comment]
I have same issue on mine with my recent install of clang 3.7

**Comment by danilaml** [comment]
could be related to : https://llvm.org/bugs/show_bug.cgi?id=24908

**Comment by gregory38** [comment]
Ok. My hypothesis so far is the 64 bits atomic type on a 32 bits system. I put back the volatile as it isn't critical. Hopefully it will be good now.

**Comment by gregory38** [comment]
@turtleli Could you review my PR? Thanks you.

**Comment by turtleli** [comment]
Sure, will do.

**Comment by turtleli** [comment]
I think the PR is fine.

**Pull request merged**
