### PR TITLE
GameDB: SOCOM 3 + Combined Assault

### PR DESCRIPTION
**Pull request by RedDevilus**
### Description of Changes

Change Vu clamp from nearest to Extra+Preserve sign.
Fixes https://github.com/PCSX2/pcsx2/issues/5944
### Rationale behind Changes

Fixes SPS and invisible/flickering characters as nearest wasn't good enough.
### Suggested Testing Steps

Play any SOCOM 3 title.

### CODE REVIEW

**Comment by xCENTx** [comment]
Might as well include SOCOM Combined Assault in with this as it shares the very same issue

**Review by xCENTx — CHANGES_REQUESTED** [review]
Shouldn't it be vuClampMode: 3 ? for Extra + Preserve?

**Comment by RedDevilus** [comment]
It's not:
image

Source:
https://github.com/PCSX2/pcsx2/blob/master/pcsx2/Docs/GameIndex.md

**Comment by refractionpcsx2** [comment]
he's right, VU Mode it's 3, it's 2 on EE.

**Comment by RedDevilus** [comment]
I guess Qt is wrong, forgot about that.

**Comment by RedDevilus** [comment]
Not sure why it's doing that, I do see a different CRC to the patch in the GameDB.

**Comment by xCENTx** [comment]
Seems to be an issue with including the sun fix patch with CA. Removing it allows the GameDB to load. Not sure what I'm doing wrong here.
The CRC and GameID both match up
```
SCUS-97545:
  name: "SOCOM - U.S. Navy SEALs - Combined Assault"
  region: "NTSC-U"
  compat: 5
  roundModes:
    vuRoundMode: 0 # Fixes disappearing characters.
  clampModes:
    vuClampMode: 3 # Fixes SPS ingame.
  patches:
    D7CFDCCF:
      content: |-
        author=Prafull
        // Fix Slowdown when looking at sun (all Patches)
	      patch=1,EE,0019f480,word,00000000"
```

**Comment by refractionpcsx2** [comment]
There's a tab in there, that will break it.

**Comment by RedDevilus** [comment]
image
RIP

**Comment by RedDevilus** [comment]
image
Should be fine now on Qt.

**Comment by xCENTx** [comment]
ah yea the quote I knew wouldnt work ... dunce moment. The formatting was getting the best of me. That tab on the last statment fixed it

**Review by xCENTx — CHANGES_REQUESTED** [review]
line 7662
This is required for the massive slowdowns on Backwoods and Harvester. The slowdown also occurs in the campaign but I forget the names of the missions.

This patch for works on both the base version of the game `v1.0`
as well as the full patched version of the game (which is used by the SOCOM COMMUNITY) patch `v1.14`
```
SCUS-97545:
  name: "SOCOM - U.S. Navy SEALs - Combined Assault"
  region: "NTSC-U"
  compat: 5
  roundModes:
    vuRoundMode: 0 # Fixes disappearing characters.
  clampModes:
    vuClampMode: 3 # Fixes SPS ingame.
  patches:
    D7CFDCCF:
      content: |-
        author=Prafull
        //Fix Slowdown when looking at sun (all Patches)
        patch=1,EE,0019f480,word,00000000
```

**Comment by refractionpcsx2** [comment]
You left the rounding in, despite us not finding a use for it?

**Pull request merged**
