### PR TITLE
replace background image by a compatible version that doesn't produce…

### PR DESCRIPTION
**Pull request by willkuer**
… a warning message in png-lib

### CODE REVIEW

**Comment by willkuer** [comment]
It fixes the warning message reported in this thread (http://forums.pcsx2.net/Thread-Log-error-i-never-seen)

I just opened the file using irfanview and saved it again. It has slightly different size but seems to be equal otherwise.

**Comment by AdmiralCurtiss** [comment]
This actually looks very slightly different, the color tone changed. Compare:
https://github.com/willkuer/pcsx2/blob/26226e2094da392563ab82fe564af172debe36d4/pcsx2/gui/Resources/BackgroundLogo.png
https://github.com/willkuer/pcsx2/blob/9a9f3a691469f94ceaa1ca52757c9ffee3b9c470/pcsx2/gui/Resources/BackgroundLogo.png

It's probably negligible though.

**Comment by willkuer** [comment]
Wow in the direct comparison on github I haven't seen a difference. Maybe it was cached by the browser. Now the difference is obvious. I am not sure if I can repair that since I am a noob to deep img processing using photoshop.
The error message was displayed since the color profile was deprecated. According to https://wiki.archlinux.org/index.php/Libpng_errors a slight color shift is expected.

If nobody is disturbed I would keep it like that.

**Comment by willkuer** [comment]
I will try to keep the colors while conversion or at least manipulate the converted in a way that it more resembles the initial image. Just need some more time sine I don't have any spare.

**Comment by danilaml** [comment]
I almost can't see difference on my monitor http://screenshotcomparison.com/comparison/137900

**Comment by bositman** [comment]
I can confirm this fixes the error and personally can't see a difference between the 2 images, but if it can be done better, I won't merge it yet ;)

**Comment by ramapcsx2** [comment]
From what I can see, only this area changes: https://i.imgur.com/99LZVHX.png

But idk, just merge it :p Thanks, willkür :p

**Comment by turtleli** [comment]
I think it's actually the browser being too smart and altering the colour according to the monitor's colour profile.

For me it looks different on the browser but the same on the actual executable.

**Comment by willkuer** [comment]
It seems to strongly depend on the screen. Obviously different screens seem to display images differently depending in there encoding. I have the feeling some screens can display the img directly while other need to convert first into another profile or just ignore the profile.

I made the PNG using a PC where I had a bad display and haven't seen a difference. After the reply of admiral curtiss I revisited the images using a professional screen where the colorshift was obvious.  I think the bad screen just ignored the profile as it will be done by mot screens.

Unfortunately I don't know which image to optimize if it depends on the screen. And I don't have easy access to the professional screen.

So I would say again I would rather merge if you are OK with that.

**Comment by bositman** [comment]
Merged it is then, thanks ;)

**Comment by willkuer** [comment]
Thanks for my first PR ;)

**Pull request merged**
