### PR TITLE
GSDX: internal interpolation scaling, & fx updates

### PR DESCRIPTION
**Pull request by Asmodean-**
Hay,

This PR adds optional Bicubic, & Lanczos interpolation scaling, internally to GSdx. They're added to the "tv shaders" section of the UI. 

Mileage will vary per game, but they offer higher quality upscaling / downsampling results. While being a bit more expensive performance-wise than the usual nearest/linear (they're optional, of course)

PR also updates the post-fx shader to reflect this (_removed the scaling section as they should be done internally, anyway_). Also a few other updates including the addition of a new bilateral filter, & updates to the cel shaders, etc.

Comments below for anyone wanting more info.

Link to a build (Windows) if anyone would like to try:  https://onedrive.live.com/redir?resid=6892A77AF38E6A6!817&authkey=!AE_t0tMpuHwMplE&ithint=file%2czip

### CODE REVIEW

**Comment by tabnk** [comment]
gsdx_20160518125034
Without


With Lanczos 
gsdx_20160518125123

**Comment by FlatOutPS2** [comment]
On first glance I don't see much difference between those two screenshots. Are there any specific games this noticably improves things on?

**Comment by Asmodean-** [comment]
That clearly doesn't look right. Are you sure you've got it enabled. There's an apparent difference. Those two screens look like it's disabled in both.

It also won't translate well to screenshots taken by GSdx directly. Take them with screen print, and paste into paint, gimp, etc.

Also, on a secondary note: I personally prefer the Bicubic implementation.

**Comment by FlatOutPS2** [comment]
I've tried the same game and stage and both Lanczos and Bicupic show no difference to the TVshader being disabled.

**Comment by Asmodean-** [comment]
What PCSX2 binary version are you using?. It could be doing that thing again where the GSdx library features don't work correctly when using a different build/compiler version to the emulation itself.

I guess, I'll add a pcsx2 binary file to the archive later, when I'm home.

**Comment by FlatOutPS2** [comment]
I didn't use the dll you linked in the first post, but the appveyor automatic build. ;)
I tried both D3D11 and OGL.

**Comment by Dreadmoth** [comment]
Used AppVeyor build. OpenGL.

Drakan: The Ancients' Gates - 2048x2044 (4x Native) → 1920x1080

Default:
pcsx2 2016-05-20 02-08-36-97none

Lanczos:
pcsx2 2016-05-20 02-09-04-35lanc

Slightly softer image, but texture aliasing is reduced significantly :)

**Comment by FlatOutPS2** [comment]
I just found a game with a noticeable difference; Splinter Cell. But it's only really clear inside a building on some furniture and wall decorations.

**Comment by Asmodean-** [comment]
I'm suspecting driver voodoo here.

Can you please post gpu & driver rev, ta

**Comment by tabnk** [comment]
If can port jinc shader will be nice.

**Comment by gregory38** [comment]
Why did you close it?

**Comment by Asmodean-** [comment]
The scaling changes happening elsewhere (other PRs) are messing with some of the scaling logic here. I'll need to wait for these changes to settle down / committed so I can retest.

Also, not had much feedback on the implementation. I might delay, and rethink it. Still not sure if the TV shaders location is the best place for it.

I want to get around to reworking the post-processing for GSdx, but I've to get around to it.

**Pull request closed without merging**
