### PR TITLE
Qt: Search all the things!

### PR DESCRIPTION
**Pull request by KrossX**
### Description of Changes
Make search include more entry strings. It now includes not only the title, but the path and serial as well.

### Rationale behind Changes
Makes the search functionality more useful for when filenames might differ from the database ones and also allows for quick subdirectory filtering!
[Example](https://i.imgur.com/zaMdCfW.png) (warning: brightness)

### Suggested Testing Steps
Use the search thingy.

**#PS:** More information per entry like developer or publisher could come in handy. For example, when you want to quickly see all your Phoenix games.

**#stenzek:** \*cough* can't make PR \*cough*
https://github.com/KrossX/duckstation/tree/search_more

### CODE REVIEW

**Comment by KrossX** [comment]
Ooops, git'd wrong.

**Comment by refractionpcsx2** [comment]
yes you mis-gitted :P

**Comment by KrossX** [comment]
Let's see, how about now...

**Comment by refractionpcsx2** [comment]
Looks more promising :D

**Pull request merged**
