### PR TITLE
GameDB: Revise serial names + GSHWFixes

### PR DESCRIPTION
**Pull request by RedDevilus**
### Description of Changes

With Qt being released there were still illegal characters being used in the name (which stops you from using covers and more), also found some random typo mistakes.

Fixes https://github.com/PCSX2/pcsx2/issues/6170

GsHWFixes:
- Ratatouille
- Wild Arms series
- Tony Hawk Downhill Jam

Ratatouille;
Before:
image

After:
image

So it's not perfect, but you can use roundsprite to full but will give vertical line effect or you could use texture offsets.

Wild Arms Series;

Upscaled (no changes):
image
image

Half Roundsprite (used currently which wasn't perfect):
image
image

Wild Arms (new one for whole series):
image
image

Tony Hawk Downhill Jam;

Before:
image

After:
image

### Rationale behind Changes

Less tinkering.
### Suggested Testing Steps

Test ratatouille.

### CODE REVIEW

**Comment by coornio** [comment]
The perfect fix is to use Skipdraw 3 and HPO: special texture aggressive. The former removes one layer of the weird ghosting (seemingly without any actual graphical loss compared to software) while retaining vibrancy, and the latter helps aligning the remaining ghosting exactly to where it needs to be. 

gs_20220524004900

Honestly, this skipdraw might be worth it, it's practically harmless.

**Comment by RedDevilus** [comment]
Skipdraw might be for the second time be a good fix

**Comment by coornio** [comment]
Small update, any skipdraw value between 1 and 3 does away with the pesky ghost, whether it's 1,1 or 1,3 or anything inbetween. Not sure why. Just mentioning this in case it's important. It *might* have some effect elsewhere in the game, like some menu, so I'd recommend a bit more testing on it to be sure.

**Comment by RedDevilus** [comment]
No skipdraw:
image

Skipdraw 2:
image

The ghosting in hardware is because it's used as a blooming filter and looks off upscaled:
image

**Comment by RedDevilus** [comment]
```
    skipDrawStart: 2 # Removes blooming filter that makes it look like ghosting.
    skipDrawEnd: 2 # Removes blooming filter that makes it look like ghosting.
```
I'll put it in here to remember there is an issue upscaled (also native with chandeliers not working properly, actually general lighting)

**Comment by RedDevilus** [comment]
image
Should be fine now

**Pull request merged**
