### PR TITLE
cmake: Fix the build without portaudio (Again).

### PR DESCRIPTION
**Pull request by orbea**
I think this was broken after PR https://github.com/PCSX2/pcsx2/pull/3756.

### CODE REVIEW

**Comment by GovanifY** [comment]
PortAudio support is still hardcoded in for windows. If we want to reintroduce portaudio-less compilation we might want to add this in.
Is there an actual reason to compile without PortAudio though? It is currently, by far, our best audio output latency wise.

**Comment by orbea** [comment]
I am not sure if windows was ever a consideration, regardless its not something I can test. This is mostly important for *unix systems that may not always have portaudio, but do have SDL2.

**Comment by GovanifY** [comment]
LGTM then, but I would _highly_ recommend distros that do not ship PulseAudio to do so. Slackware thought process is "it adds complexity" but they fail to register that SDL adds even more in this corner case, and ends up recommending SDL over PA as a sound driver, which is pretty insane to me ngl.

**Comment by GovanifY** [comment]
LGTM then but aren't most modern distros supporting portaudio? As far as I know you are a manager of Slackware, so how is https://slackbuilds.org/repository/14.2/development/portaudio/ working out with this?
I'm fine with merging this either way, it's just curiosity at this point.

**Comment by orbea** [comment]
In my personal case pcsx2 is the only program which can use portaudio while many programs want SDL2, I don't think this uncommon. Also portaudio only builds with `-j1` which is annoying.

**Review by GovanifY — APPROVED** [review]

**Comment by gregory38** [comment]
Extra note: Portaudio got issue with pulseaudio too. It was the reason of sdl2 module. I don't know if it is fixed nowadays (unlikely)

**Comment by orbea** [comment]
Portaudio was also broken with alsa for a time, but that is now fixed. https://github.com/PCSX2/pcsx2/issues/1775

I think in general a lot more people are testing SDL2.

**Pull request merged**
