### PR TITLE
Gsdx crc management

### PR DESCRIPTION
**Pull request by gregory38**
First implementation of the new CRC hack management.

It misses 
1. the gui on Windows.
2. a nice (and verbose) tooltip

### CODE REVIEW

**Comment by gregory38** [comment]
depends on PR #571

**Comment by gregory38** [comment]
New version. Rebase against the new nocturne hack. Add a verbose tooltip.

It only misses a windows implementation of the box that will replace UserHacks_AggressiveCRC/UserHacks_DisableCrcHacks

@ssakash more GUI work for you

**Comment by ssakash** [comment]
I'll implement a drop down list for the the new CRC level variable. also, I guess it would be feasible to reuse the >dialog_message(IDC_CRC_LEVEL)

by the way, where should I make the commit ? CRC level branch (or) Master ?

**Comment by gregory38** [comment]
If you already have it, you can commit into this branch. This way we can merge both linux/windows in 1 shot.

**Comment by ssakash** [comment]
sure, I'll commit it the next second I reach my computer.

**Comment by gregory38** [comment]
Hum actually I don't think you can push in this branch. You need to do it to your fork. So it might be easier to merge this one first (or just add the box to control "crc_hack_level" value)

**Comment by ssakash** [comment]
I can still PR the commit in this branch. By the way, I hope you mean the drop down list as box. You can go ahead and merge this one first, I'll push my commits a little later when I get acess to my PC.

**Comment by i30817** [comment]
Could you make the memory deference in the nocturne hack inside a outer if for aggressive (or just early return if !aggressive) as discussed?

**Comment by ssakash** [comment]
No, I'm not doing anything related to the agressive hack functions. I'm just adding the GUI interface for windows for this CRC management. I'm adjusting windows of the dialogs for the moment till everything fits fine.

By the way, why not make a other PR for this ?

**Comment by i30817** [comment]
Oh i though this was a @gregory38 PR. My excuses, he just said he was going to do it and i didn't want to step any merge fingers.

**Comment by ssakash** [comment]
no, you were right. I thought you were addressing the changes on my current PR, apologies.

**Comment by gregory38** [comment]
Ok. I merged the code. @ssakash I let you add the ComboBox (like the renderer selection). Reuse the combox api.
```
	void ComboBoxInit(UINT id, const vector<GSSetting>& settings, uint32 selid, uint32 maxid = ~0);
	int ComboBoxAppend(UINT id, const char* str, LPARAM data = 0, bool select = false);
	bool ComboBoxGetSelData(UINT id, INT_PTR& data);
	void ComboBoxFixDroppedWidth(UINT id);
```

**Comment by karasuhebi** [comment]
Didn't @refractionpcsx2 already implement the combo box? I see it on the latest dev builds.

**Comment by ssakash** [comment]
Yeah, just a day before. I noticed that when my commits had a merge conflict when I decided to PR.

**Comment by gregory38** [comment]
Sorry it was blocking the GSdx test campaign

**Pull request closed without merging**
