### PR TITLE
Qt: Disable/remove unused buttons.

### PR DESCRIPTION
**Pull request by lightningterror**
### Description of Changes

Qt: Disable/remove unused buttons
Not implemented yet.
Disable:
Pause On Start,
Pause On Focus Loss,
Hide Mouse Cursor,
Disable Window Resizing.

Remove:
Cheats menu and toolbar.
### Rationale behind Changes

Unused/ non functional.
### Suggested Testing Steps

GUI still works and looks good, compiles.

### CODE REVIEW

**Comment by BParks21** [comment]
So there will be no way to hide the mouse cursor automatically?

**Comment by RedDevilus** [comment]
It's a temporary deletion but that doesn't mean it won't be inplemented in the future.

**Comment by BParks21** [comment]
> It's a temporary deletion but that doesn't mean it won't be inplemented in the future.

I see, thanks for the reply.

**Comment by stenzek** [comment]
Imo better to leave them there until they're implemented.

**Comment by BParks21** [comment]
> Imo better to leave them there until they're implemented.
> 
> Edit: Another option could just be to leave them perma-disabled until they're hooked up.

Was just curious about the option because with it checked or unchecked or functional, the mouse still disappears when not active in fullscreen with wxWidgets builds.

**Comment by lightningterror** [comment]
> Edit: Another option could just be to leave them perma-disabled until they're hooked up.

I thought about that but then people would be asking how to enable them, so I think it's better to remove until they are implemented.

**Comment by arcum42** [comment]
I think permadisabled's probably better because that way we remember that they are supposed to be there and need to be implemented. It'd be easier to forget if the buttons not there at all.

**Comment by stenzek** [comment]
The cheats item could probably go, but the others are reasonably straightforward to implement so disabling for them is better (might be able to do them this weekend).

**Pull request merged**
