### PR TITLE
Gsdx gta depth issue 1457

### PR DESCRIPTION
**Pull request by gregory38**
Need to test game on Dx (openGL support depth correctly)

### CODE REVIEW

**Comment by FlatOutPS2** [comment]
Why did you include the debugger, onepad and common commits here?

**Comment by gregory38** [comment]
Because I did those commit on master but I fogot to push them. I did the branch a bit later so it put everything. But once you merge it only 1 commit will be added.

**Comment by FlatOutPS2** [comment]
I see. It just confused me for a second when I was looking at the changed files and noticed all these unrelated changes.

OT: The colorfilter is working again for both D3D 9 and 11.

**Comment by gregory38** [comment]
Let's merge the pandora box.

**Comment by FlatOutPS2** [comment]
@gregory38 Everybody's Golf (4) has opened the box. This PR broke the renderering with depth emulation disabled/Direct3D HW renderers.

**Comment by gregory38** [comment]
I'm pretty sure it broke others games. Could you provide a clean revert ?

**Pull request merged**
