### PR TITLE
Linux -> Unix

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by gregory38** [comment]
Is it ok with the guys that do the MAC port. Or will it conflict with their works?

**Comment by uyjulian** [comment]
@juhalaukkanen @aktau ping

**Comment by ramapcsx2** [comment]
I don't think the MAC port is being worked on. And if it was, the change shouldn't interfere much.

**Comment by uyjulian** [comment]
Yep, it's just simple renaming.

**Comment by gregory38** [comment]
It is not that simple. Some code is linux only and is not unix compatible. The Mac guys only rename the good parts. Now I'm afraid they would need to revert back a part of this massive rename.

**Comment by uyjulian** [comment]
If there are merge conflicts, Git will tell the mac guys where the conflicts are

**Comment by avih** [comment]
As on previous PRs from you, this is a massive patch with zero explanations on what it fixes.

**Comment by aktau** [comment]
In my (admittedly old) PR, I've taken a different route: convert `__linux__` to `__unix__` where it's necessary (and makes sense), instead of point blank. This can be noticed by failures to compile (as @gregory38 alluded to). I think that leaves the commits easier to review. For this change, for example, it would be difficult to say whether it's good or bad.

**Comment by uyjulian** [comment]
@aktau Yeah, I agree, when I looked at the code again to start porting to FreeBSD, I noticed some linux-specific spots. I shouldn't have done it lazy. I'll close for now. <sub><sup>(Maybe because I was tired? Maybe I shouldn't be doing this in the middle of the night :-P)</sup></sub>

**Pull request closed without merging**
