### PR TITLE
GameDB: Patch to fix Valkyrie Profile 2 PAL FMV timing

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Patch to sync audio and video in Valkyrie Profile 2 FMV's

### Rationale behind Changes
I'm not sure on the source of this but, I suspect the game thinks somewhere that it's in NTSC mode instead of PAL (I think a few games do this), but I'm unsure where this would be.  This patch will suffice for the moment, until somebody completely dissects this game.

### Suggested Testing Steps
Test Valkyrie Profile 2 PAL FMV's

### CODE REVIEW

**Comment by Goatman13** [comment]
I think this patch can trigger anti-cheat mechanic (Gameguard) and break people game saves. This is irreversible, broken saves cannot be recovered. Protection is really nasty and trigger after few chapters, there is no way to tell if it's already broken or not.

**Comment by refractionpcsx2** [comment]
Ugh really?? Wow what a dumb thing to put in a single player game....

I guess I'll remove it again then...

**Comment by Goatman13** [comment]
Yeah, a lot of hassle to prevent cheats in single player game. As far as i know game scan code, and do some arithmetic operations on it to detect changes. Pnach file here have more info: https://forums.pcsx2.net/Thread-Post-your-PCSX2-cheats-patches-here?pid=595942#pid595942

**Comment by refractionpcsx2** [comment]
Good lord, that's a chonky patch... Sounds like they do a bunch of scary checks, but mostly to avoid ridiculous values? I'm not sure they'd go through the effort to check the fmv code all, but much cheating you can do the, but better to be safe than sorry I guess. Maybe somebody should play the game with the fix first, who is willing to be a sacrificial lamb, so to speak

**Comment by Goatman13** [comment]
"Sounds like they do a bunch of scary checks, but mostly to avoid ridiculous values?"
I think TriAce overdid it to whole code segment. I know codes like remove post processing triggered that protection.

**Comment by refractionpcsx2** [comment]
bonkers lol.

Well Technostrophe on the discord is going to check the patch with a sacrificial run, see if it's viable.

**Comment by refractionpcsx2** [comment]
looks like the intro (ingame cutscene) crashes half way through if you're in 16:9 with the patch.

I guess that's that then.

**Comment by Goatman13** [comment]
Yup that's what game protection do apparently.

**Comment by refractionpcsx2** [comment]
yeah, I mean in theory we could go through all the code and kill all these loops.

is it possible this is how it kills peoples saves, by hanging in the middle?

**Comment by Goatman13** [comment]
There is "save corruptor" function that rigger at some condition. To be honest if you really need it fixed just do it outside of EE memory. Like i don't know, in recompiler or something.

**Comment by refractionpcsx2** [comment]
Well we don't have any code in there to do it for that and I'm loathed to hack it in to the JIT just for one game. even the Dynapatch stuff will edit the memory as well, this will only be saved if the game then overwrites this again when the next scene is loaded.

**Pull request merged**
