### PR TITLE
Add file Project and Sln for Visual Studio 2015 and more !

### PR DESCRIPTION
**Pull request by Zangetsu38**
Preparing for the arrival of Visual Studio 2015.
Adding the project file and pcsx2_suite_2015.sln file.
Adding multiple x64 compile project for VS 2013, 2015,  does not change at compile in Win32.
Fix sln version VS 2013 Update 4
Add submodule wxWidgets for vs 2015 (Temporary) …
Delete folder wxwidgets3.0-3.0.1, Completely unusable.
The compilation now also displays error 6, Project need a update for VS 2015 : w32pthreads.v4 ,GSdx,  xpad, w32pthreads_lib, pcsx2.
http://pastebin.com/CvRHe3HB
Support for Windows XP had to be removed, otherwise problems with SDK and Visual 2015 has not seem to like xp.
Important, my modification not affect compile vs 2010 and 2013

### CODE REVIEW

**Comment by mirhl** [comment]
Did you use the right [toolset](https://msdn.microsoft.com/en-us/library/ms235435%28v=vs.140%29.aspx) for XP?

**Comment by Zangetsu38** [comment]
@mirhl  What ? I said that I could disable xp compatibility, because of a problem related to Windows 10 kits.
It's simple for him: "v140_xp = 8.1", and "v140 = 10.0"

**Comment by Zangetsu38** [comment]
Update, with update wxWidgets, now compilation show only 6 error.

**Comment by gregory38** [comment]
It would be much better to separate the unrelated change in multiple PR. 

```
 Delete sln and project for VS 2012 (Obsolete and useless)
```
Some people want to keep VS2012, personally I don't care, I'm on linux, but I don't think it is hurting VS2015 support to also allow VS2012 build.
```
Delete folder wxwidgets3.0-3.0.1, Completely unusable.
```
What is the issue with this version? Did it miss a couple of file to compile? PCSX2 must switch to wx3.0, removing the source won't help. Except if you have a better solution to manage 3rdparty lib on windows.

**Comment by Zangetsu38** [comment]
@gregory38 Kept the project and the .son Visual Studio 2012 while those in VS 2013 are, has in my opinion, useless.
Everyone VS 2013 now uses a long time, the 2012 is no longer useful.
For the folder wxwidgets 3.0-3.0.1, it was not used and simply could not do anything with, so needless to guarded.
The submodule I add the perfect replacement.

**Comment by gregory38** [comment]
Still some users ask us to keep VS2012 because they still use it.

WX3.0 is not YET used on windows, we are waiting someone to port the code to it (it was done on linux).
```
The submodule I add the perfect replacement.
```
Depending on 3rd party project for 3rd party sw isn't good from my point of view. But I let's windows dev make the choice.

**Comment by Zangetsu38** [comment]
@gregory38 I did not know there were still unused user VS 2012.
So I have a restore.

**Comment by uyjulian** [comment]
I suggest you squash all your changes.  
Or if you don't want to mess with git history, redo the commit from scratch.  
It kinda looks ugly with the merge/revert/oops stuff.

**Pull request closed without merging**
