### PR TITLE
gsdx: reimplement GSJobQueue with a boost queue

### PR DESCRIPTION
**Pull request by gregory38**
Warning: don't merge it. Only for benchmark/test.

It requires boost (only hpp files) + MSVC 2013 (for atomic)

It is a temporary commit to do some benchmark. If it works nicely, I will clean
old code/header properly.

### CODE REVIEW

**Comment by wareya** [comment]
Windows 7 64-bit OS (32-bit pcsx2, obviously)

My performance on a certain pause screen with the previous commit is about 48 FPS. My performance on the same pause screen with the current (PR'd) commit is about 30 FPS. The current commit also locks up the pcsx2 GUI for a second or two on an occasional basis, for no obvious reason.

Additionally, using more than 3 threads (per setting in GDSX) on the current commit causes my computer to be nearly unuseable, emulator included (<5 FPS). Using more than 3 threads on the previous commit results in basically no difference, possible a 1 or 2 FPS boost.

Using boost 1_57_0 headers.

**Comment by gregory38** [comment]
Thanks. Which CPU?

**Comment by wareya** [comment]
Phenom II X4 940 3.0ghz

**Comment by gregory38** [comment]
Ok. Unlike previous implementation, I don't stop threads. They keep polling for work. It means that you will be limited to 2 extra threads maximum (if you don't enable MTVU, 1 otherwise).

**Comment by wareya** [comment]
I get 42 FPS with two extra threads and MTVU 0
I get 38 FPS with two extra threads and MTVU 1
I get 26 FPS with one extra thread and MTVU 1
I get 26 FPS with one extra thread and MTVU 0

I get almost the same framerate between three extra threads with or without MTVU

**Comment by gregory38** [comment]
I posted a new version that add a wait on the producer thread. It reduces resources requirements a bit.

If it still compiles on windows, it will be nice to have a new test (without MTVU). If performance still sucks, you can edit file GSThread_CXX11.h line 63 to uncomment WAIT_NOT_EMPTY statement (ie. remove // at the front)

**Comment by wareya** [comment]
Compiles in VS 2013 Express. Haven't tried the others.

I get 42~43 FPS on the current HEAD with MTVU disabled and extra threads set to 2. Any other configuration gives a significant performance penalty (at best 35 FPS).

The pre-boost performance is nearly the exact same framerate with the same number of threads and with MTVU disabled. However, that pre-boost version can use more threads?

That said, performance per thread seems on-par now.

**Comment by gregory38** [comment]
My previous implementation reserves (and lock) a core for GS + extra threads. EE needs a cpu too. There are also the GUI + OS. It means it was limited to 1 extra thread for your 4 cores cpu.

This new implementation relaxes the GS thread constraint. The thread will sleep when its jobs is done. It allows you to use 2 extra threads. I'm curious of the results on an ht processor.

It also possibles to relax the reservation for extra threads. It is a bit slower on linux (at least on 8 cores cpu). You need to edit the code until I add a nice option.

**Comment by Dokman** [comment]
This may works better with a multithreated cpu like an amd fx 8350?

**Comment by wareya** [comment]
I'll give it a shot later (thread constraint).

**Comment by gregory38** [comment]
@Dokman 
Yes I think so. I need more test on more hardware (and more OSes). I think you need to add the path include into MSVC

**Comment by SerialHacker** [comment]
should i even bother testing this with a dual core or it would be impractical ?

**Comment by danilaml** [comment]
boost dependency with no real (actual performance-wise) benefit is no good... It's quite heavy.

**Comment by gregory38** [comment]
With current code, is 1 extra thread faster than none?

In the end I think the best option would be to create 3 queues based and only use low-latency queue for 6c/8c CPU. I need to check the SW rendering scaling for 5+ extra threads.

On boost dependency topic:
1/ It is only an experimentation
2/ I am well aware that boost is heavy. However in this case it is just a matter of (a single?) include files (nothing to compile).
2/ On linux it is really faster (at least on my CPU). And so far, a 4C/4T was tested on windows.
3/ It moves linux/windows code duplication in Boost.

**Comment by wareya** [comment]
Huh... My last test was on a weird HEAD. git pull must have silently failed then.

Take back my last test results; I'll recompile. Also, I have to do the pthread include bypass as well since it doesn't exist over here.

**Comment by SerialHacker** [comment]
i meant my hardware not the configuration :P

**Comment by wareya** [comment]
Did I do something wrong? http://i.imgur.com/UuxDI4D.png

**Comment by gregory38** [comment]
I need to fix some stuff.

**Comment by gregory38** [comment]
@wareya, @Dokman 
I pushed a new version that hopefully fix your issue. I also added BOOST_ROOT include path to GSdx project.

**Comment by gregory38** [comment]
Note: I did a force push (I don't know what is the impact for the pull).

**Comment by Bigpet** [comment]
Force push is just an issue if people already pulled something in the past, changed things and are trying to merge it now.

If you didn't rewrite the history before the changes in the pull-request it's not an issue.

**Comment by wareya** [comment]
Currently makes the emulator lock up and spin its wheels maxing out the rendering cores pretty much right after "booting".

**Comment by gregory38** [comment]
I pushed a new version, with new define name to easily understand the difference behavior.

The default of latest commit:
FULL_WAIT_LESS_CPU_INTENSIVE: same behavior as  master-branch. Likely the best for 2C/4C CPU.

The WAIT_ON_GS_STILL_CPU_INTENSIVE: no sleep for the rendering thread. Faster fps by thread but it requires more core. Likely the best for (6C?)/8C CPU.

**Comment by Dokman** [comment]
@gregory38 When the gsdx plugin run's the pcsx2 crash in avx mode

**Comment by gregory38** [comment]
That strange, I didn't touch anythings related to SSE/AVX.

**Comment by Dokman** [comment]
extrathreads=6 is this value no?

**Comment by gregory38** [comment]
???
The value is allowed for me.

**Comment by Dokman** [comment]
@gregory38 I mean is this the value i have to change for modify the extra core's or threats no?

**Comment by gregory38** [comment]
yes from 0 to 16

**Comment by gregory38** [comment]
I try to make the code more robust. Tell me if you still have a deadlock on windows? And try with WAIT_ON_GS_STILL_CPU_INTENSIVE configuration (easier to debug if there is a deadlock)

**Comment by wareya** [comment]
It no longer deadlocks and performance is back to pre-boost levels with FULL_WAIT_LESS_CPU_INTENSIVE, extra threads = 3, and MTVU=0, on a four-core SSE2 CPU.

**Comment by gregory38** [comment]
Thanks. So far it seems to highlight a Linux issue of pre-boost queue.
Could you do a quick check of the middle queue (WAIT_GS...) with extra thread 2/3 (1 is useless).

I'm curious of the performance of the ring buffer inside PCSX2 (MTVU & MTGS)

**Comment by wareya** [comment]
I tried with the middle def and it gave worse performance (but not abysmal). Don't remember the exact numbers, but it was more than marginal and less than broken.

**Comment by Dokman** [comment]
Now i test it with 6 cores

**Comment by Dokman** [comment]
you can implement a new cpu for computing?

**Comment by gregory38** [comment]
@wareya, Ok. Thanks. Let's see results on 6c/8c CPU.

@Dokman, sorry I don't understand.

**Comment by Dokman** [comment]
@gregory38 in my FX 8350 i has 40 - 50 FPS on Ratchet and clank with a lot of slowdowns like ever ._. but yes it works

I am referring  to MTVU hack if add a third core why not try to use more cores to the emulation?

**Comment by gregory38** [comment]
Some tasks can't be done in //. More core won't solve anythings. By the way PCSX2 already uses a high number of threads: GUI + EE + MTVU + MTGS (+ extra threads) + GPU driver thread + input plugin thread. 98% of the market is 4 cores and below.

For the story, I just overclocked my RAM from 2133MHz to 2666MHz. I retry my mini gsdx benchmark, I lost 5 fps... Conclusion bigger numbers don't mean bigger performances.

**Comment by Dokman** [comment]
And how can have a good performance cause like ever amd have a lor of troubles in single core power and a lot of people now uses amd how we can have a better performance?

**Comment by gregory38** [comment]
Change your CPU. It is only a matter of trade-off. AMD reduces ST performances to increase MT performances. It doesn't fit well PCSX2 need but it is very cost effective for application that supports 6+ threads.

**Comment by Dokman** [comment]
i know it but a new I7 5960X cost me 1119€ and the motherboard like 600€ more

**Comment by gregory38** [comment]
I know it is expensive (motherboard is 250E + 200 ram). Save your money, in a couple of years you might afford a better cpu (price will decrease).

But let's get back on track ;)

**Comment by gregory38** [comment]
I add an option to select the queue easily.
* On linux you can do it from the gui :)
* On windows, you must edit gsdx.ini file directly => "spin_thread"; possible values are 0 or 1.

**Comment by jobermayr** [comment]
Doesn't build with Boost < 1_54_0:
```
[ 75%] Building CXX object plugins/GSdx/CMakeFiles/GSdx-0.1.16.dir/GSRasterizer.cpp.o
In file included from /home/abuild/rpmbuild/BUILD/pcsx2/plugins/GSdx/GSRasterizer.h:30:0,
                 from /home/abuild/rpmbuild/BUILD/pcsx2/plugins/GSdx/GSRasterizer.cpp:25:
/home/abuild/rpmbuild/BUILD/pcsx2/plugins/GSdx/GSThread_CXX11.h: In instantiation of 'void GSJobQueueSpin<T>::ThreadProc() [with T = std::shared_ptr<GSRasterizerData>]':
/home/abuild/rpmbuild/BUILD/pcsx2/plugins/GSdx/GSRasterizer.cpp:1259:1:   required from here
/home/abuild/rpmbuild/BUILD/pcsx2/plugins/GSdx/GSThread_CXX11.h:217:5: error: 'class boost::lockfree::spsc_queue<std::shared_ptr<GSRasterizerData>, boost::lockfree::capacity<256ul>, boost::parameter::void_>' has no member named 'consume_one'
     if (m_queue.consume_one(*this))
     ^
/home/abuild/rpmbuild/BUILD/pcsx2/plugins/GSdx/GSThread_CXX11.h: In instantiation of 'void GSJobQueue<T>::ThreadProc() [with T = std::shared_ptr<GSRasterizerData>]':
/home/abuild/rpmbuild/BUILD/pcsx2/plugins/GSdx/GSRasterizer.cpp:1259:1:   required from here
/home/abuild/rpmbuild/BUILD/pcsx2/plugins/GSdx/GSThread_CXX11.h:128:5: error: 'class boost::lockfree::spsc_queue<std::shared_ptr<GSRasterizerData>, boost::lockfree::capacity<256ul>, boost::parameter::void_>' has no member named 'consume_one'
     if (m_queue.consume_one(*this))
     ^
make[2]: *** [plugins/GSdx/CMakeFiles/GSdx-0.1.16.dir/GSRasterizer.cpp.o] Error 1
```

**Comment by gregory38** [comment]
Yes I just saw it yesterday, boost 1.53 misses the consume_one interface. I'm currently looking to replace the boost queue with a dedicated re-implementation for GSdx.

**Comment by gregory38** [comment]
Superseeded by #482

**Pull request closed without merging**
