### PR TITLE
gui:linux: Redirect stdout/stderr to the PCSX2 console

### PR DESCRIPTION
**Pull request by turtleli**
This redirects plugin stdout/stderr messages to the PCSX2 console, similar to what Windows does.

As a side effect, for users using the Console to stdio option - plugin stderr messages are now red, and plugin stdout messages are now grey and bold (or at least they are for me).

Code potentially needs a few more comments, but it can be tested in the meantime.

woosh

2 days ago:
> I'll look at it in __a few weeks__ time, it'd be useful for the emulog output as well.

Never was good at counting days.

### CODE REVIEW

**Comment by gregory38** [comment]
Great jobs :) I need to play with it.

**Comment by turtleli** [comment]
Changes made - File added to Visual Studio, additional comments, other minor formatting stuff.

I just need to test that it degrades nicely if there's a freak failure (the stuff really shouldn't fail though) and if it works fine I'll have it merged.

**Comment by gregory38** [comment]
Ok. It might worth a test with gsdx-ogl debug feature enabled (in debug mode). It is quite verbose ;)

**Comment by micove** [comment]
Could
```
+    <ClCompile Include="..\..\Linux\LnxConsolePipe.cpp">
+      <ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">true</ExcludedFromBuild>
+      <ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Devel|Win32'">true</ExcludedFromBuild>
+      <ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">true</ExcludedFromBuild>
+    </ClCompile>
```

be changed to
```
+    <ClCompile Include="..\..\Linux\LnxConsolePipe.cpp">
+      <ExcludedFromBuild>true</ExcludedFromBuild>
+    </ClCompile>
```

I postponed my PR to cleanup all the VS files until after 1.4.0 but might as well not introduce new ones. I know that the VS gui add the 3 lines instead of just one but the liberal use of Conditions when not needed make it hard to read and I always handcraft those files in notepad.

**Comment by turtleli** [comment]
Sure. Will do.

The address sanitizer trips when closing pcsx2 (seems like a race condition due to the blocking read), so I probably need to rework things a little.

But yeah, it can handle the gsdx debug output.

**Comment by turtleli** [comment]
Updated - better cleanup during shutdown, smaller VS file change.

**Pull request merged**
