### PR TITLE
gsdx: implement fixed TEX0 for all renderers

### PR DESCRIPTION
**Pull request by gregory38**
It shall fix lupin texture for hw renderer. 007 Nightfire is also fixed.

Closes https://github.com/PCSX2/pcsx2/issues/258

### CODE REVIEW

**Comment by gregory38** [comment]
issue #695

**Comment by gregory38** [comment]
Hum reading back the issue. I'm afraid of corner case that will break (namely floating point coordinate).

**Comment by lightningterror** [comment]
@gregory38 here are the gsdumps from me and prafull.
[Lupin 3rd Issues.zip](https://github.com/PCSX2/pcsx2/files/2873870/Lupin.3d.Issues.zip)

**Comment by gregory38** [comment]
@lightningterror 
Could you test that for bilinear ? Try to play with it :)
```
diff --git a/plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp b/plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
index c4ed344e3..689cbf668 100644
--- a/plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
+++ b/plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp
@@ -845,6 +845,9 @@ void GSRendererOGL::EmulateTextureSampler(const GSTextureCache::Source* tex)
        tw = (int)(1 << m_context->stack.TEX0.TW);
        th = (int)(1 << m_context->stack.TEX0.TH);
        ps_cb.WH = GSVector4(tw, th, w, h);
+
+       //
+       ps_cb.HalfTexel = GSVector4(-0.5f, 0.5f).xxyy() / WH.xyxy();
    }
 
    // Only enable clamping in CLAMP mode. REGION_CLAMP will be done manually in the shader
```

**Comment by gregory38** [comment]
Or maybe use ps_cb.WH

**Comment by gregory38** [comment]
Please don't merge it !

I only pushed it for testing and backup. I will likely implement those commits differently.

**Pull request merged**
