### PR TITLE
GS:SW: Use doubles for Z

### PR DESCRIPTION
**Pull request by tellowkrinkle**
### Description of Changes
Makes the SW renderer use doubles for Z

<del>Has a noticeable (~3%) performance hit, so leaving this a draft for now, will only use it for large z values in the future</del> I think we've gotten performance to an acceptable level

### Rationale behind Changes
Reduce Z fighting

### Suggested Testing Steps
Test KOF, other zequal games / games with z fighting

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Speed losses on games which are fixed by this PR:
Destroy All Humans is fixed, and the perf loss is about 4%, but we're talking at over 210fps in both cases
Tony Hawk is about 6% but again, we're talking about 250fps here
KoF 94 fixed with about a 3.4% perf loss (but again, like 600fps down to 580fps lol)

Random other game speed losses:
GT4 147 -> 135fps (8.2%)
DT Racer 146 -> 135fps  (7.6%)
Driv3r 107 -> 101 (5.4%)
CoD 2 107 -> 100 (6.6%)

NFS MW was identical speeds (within margin of error)

Potential issues to make note of or test things from

Meta: #3692 

Individual issues:
#5780
#3496
#3609 (but awaiting feedback on some issues)
#5394
#4116

**Comment by iracusgithub** [comment]
This Pull Request works just fine with the majority of games I tested on.

However, theoretically, this float->to double approach might not be enough if a game abuse the floating-point arithmetic precision (kind of like what we have on the VUs or the COP1).

I have 2 questions regarding that:

Does the GS have a wider range of floats and/or follow the IEEE 754 standard for this?

And will a soft-float approach, considered in the future even if, it will likely be very,very slow?

**Comment by Lagahan** [comment]
Improves Quake 3
Master:

https://user-images.githubusercontent.com/5718411/167296320-58c3494c-bab0-4a4e-bc8e-198209b8f79c.mp4


PR:

https://user-images.githubusercontent.com/5718411/167296332-c9b5b4ee-f5e0-42fb-a2f5-dbe74f473188.mp4

**Comment by githubribbon45** [comment]
Hasbro Family Game Night is also fixed, the game table does not exhibit weird artifacts as seen in the issue report (https://github.com/PCSX2/pcsx2/issues/2289):

From the report:
35777821-cb9ac7fc-09b4-11e8-9980-dbf912d95639

With the PR:
https://user-images.githubusercontent.com/105116470/167296571-f801cc7c-7b65-4639-8c73-02b361e63d23.mp4

**Comment by refractionpcsx2** [comment]
@githubribbon45

> However, theoretically, this float->to double approach might not be enough if a game abuse the floating-point arithmetic precision (kind of like what we have on the VUs or the COP1).

Not a scenario that exists (explained below)

> I have 2 questions regarding that:
> 
> Does the GS have a wider range of floats and/or follow the IEEE 754 standard for this?

The GS doesn't use floats, it's completely integer (using 12.4 FIxed integers at most), we do that for speed and convenient of interpolating coordinates.

> And will a soft-float approach, be considered in the future even if, it will likely be very,very slow?

No need here.

**Comment by JordanTheToaster** [comment]
Sonic Hero's no longer has Z fighting during the opening gameplay.

**Comment by ps1freak26** [comment]
Ridge Racer 5's shine is back in software mode so #5575 is fixed.

**Comment by prafullpcsx2** [comment]
This pr seems to break game "Trapt". Initial screens are not visible in SW mode. Block dump attached.

[Trapt (2022-04-09 01-09-40).zip](https://github.com/PCSX2/pcsx2/files/8647666/Trapt.2022-04-09.01-09-40.zip)

**Comment by MarioSonic2987** [comment]
Fixes Z-fighting in Worms 4 Mayhem. It's more noticeable in battles.

**Before**:
image
**After**:
image

**Comment by MrCK1** [comment]
Confirmed that z-fighting in Shox is fixed

PR:
image

Master:
image
****

**Comment by TransparentBlue** [comment]
Does not improve Okami ( #2004 ) at all.
Does not Improve Gran Turismo 4 at all ( #3692 )
Improves Ape Escape 3 there's still some Zfigthing but you have to go out of your way to trigger it. ( #3692 )

**Comment by refractionpcsx2** [comment]
> Does not improve Okami ( #2004 ) at all. Does not Improve Gran Turismo 4 at all ( #3692 ) Improves Ape Escape 3, there's still some Zfigthing but you have to go out of your way to trigger it. ( #3692 )

what Z fighting in Okami? the issue you linked was Siren.

**Comment by TransparentBlue** [comment]
Sorry about that, shoud've been #2008, though it's also linked in the meta issue for Zfighting.

**Comment by refractionpcsx2** [comment]
and to be clear, you're only testing Software mode yes? Hardware won't be affected.

**Comment by refractionpcsx2** [comment]
cool, thanks for the clarification :)

**Review by refractionpcsx2 — APPROVED** [review]

**Review by JordanTheToaster — APPROVED** [review]

**Review by Mrlinkwii — APPROVED** [review]

**Pull request merged**
