### PR TITLE
Gsdx channel effect

### PR DESCRIPTION
**Pull request by gregory38**
Yeah more channel effect hle emulation #1318 #1313 

* Correct urban chaos HLE shader
* Add a GT3/4/concept HLE shader
* Add a Tales of Abyss HLE shader
* Use HLE shader for tekken5 (acid stage)
* Hack to disable channel in blood will tell (hopefully limited to this game)

Please test carefully above game and post-processing effect.

### CODE REVIEW

**Comment by avih** [comment]
Yay! Concept shader! :)

**Comment by gregory38** [comment]
I only have a gt4 dump. I hope they use the same mess effect for the series otherwise I'm screwed ;)

**Comment by FlatOutPS2** [comment]
> Add a GT3/4/concept HLE shader

Can you add Tourist Trophy as well?

**Comment by gregory38** [comment]
Yes I can. Is the game from gt series ?
Effect must the same otherwise it won't work. And we must be sure there isn't severals channel effects for the same games.

**Comment by FlatOutPS2** [comment]
Yes, Tourist Trophy is basically GT4 with bikes.

**Comment by gregory38** [comment]
Oh. Ok done.

**Comment by refractionpcsx2** [comment]
Just tried GT4.  Had CRC set to none (is that what you wanted?) and I get this, It did appear as a strong colour but i caught it near the end, it's much better but still an issue.
gt4

**Comment by FlatOutPS2** [comment]
The blue bar was there already before this PR. I haven't noticed any improvement in Tourist Trophy either.

**Comment by refractionpcsx2** [comment]
> The blue bar was there already before this PR. I haven't noticed any improvement in Tourist Trophy either.

Yeah I presumed that's what this was tackling ;p

**Comment by gregory38** [comment]
Did you try to set brightness/contrast? My dump has both as the same time. Is it your case?

**Comment by refractionpcsx2** [comment]
That was brightness 2 which historically had the mess over the screen, but not sure when that was fixed, not by this im afraid.

If it makes you feel any better the other GSDX's I have crashed going in to 3d but this one doesn't :P

**Comment by MrCK1** [comment]
I happened to find an unrelated issue in GT4 a few mins ago. Posted in #1313

**Comment by FlatOutPS2** [comment]
I compared the current GSdx with the one from dev-710 and didn't notice any improvement in the brightness settings either. No matter what I set it to, nothing changes in either version. You don't need to set it to 0 anymore though, but that goes for dev-710 too.

**Comment by gregory38** [comment]
On master the contrast effect is removed. So you don't see a mess but it doesn't apply correctly. Normally it must be good now (except my dump is brightness +5 / contrast +5). I don't know if the game will render it differently if only 1 is enabled

**Comment by refractionpcsx2** [comment]
Urban Chaos looks good, very close to software, only difference being HW is slightly brighter sky than SW.

Speed not bad, getting 70fps, looks like I'm gpu driver limited as the %'s both sit around 70%

**Comment by refractionpcsx2** [comment]
OK brightness/contrast have no effect on the picture, but it doesn't display garbage (results are immediate in GT4)

**Comment by FlatOutPS2** [comment]
> On master the contrast effect is removed. So you don't see a mess but it doesn't apply correctly. Normally it must be good now (except my dump is brightness +5 / contrast +5). I don't know if the game will render it differently if only 1 is enabled.

I see no difference at all between the effect removed(is it still removed with CRC set to none?) and this PR.

**Comment by gregory38** [comment]
You need at least minimal on CRC otherwise detection won't work and it will be like master.

:cry: it works on my dump
master

With pr
pr

**Comment by FlatOutPS2** [comment]
> You need at least minimal on CRC otherwise detection won't work and it will be like master.

Oops. That did the trick, now the brightness settings work in Tourist Trophy!

**Comment by refractionpcsx2** [comment]
I cant get more minimal than this :/
gsdx-gt4

**Comment by FlatOutPS2** [comment]
None (Debug) != Mimimal :p

**Comment by gregory38** [comment]
Yes the minimal level ;) not the minimal level :p lol

**Comment by refractionpcsx2** [comment]
oh you mean miniMUM :P minimal means loest lol

**Comment by refractionpcsx2** [comment]
OK now they work :P the flashy blue thing i posted before actually fills the screen (pretty much) with minimum as CRC level :P

**Comment by gregory38** [comment]
Ah yes, you're rigth. In my defense, I only use the ini file and not the gui, so don't remember the exact name of option.

By pretty much what do you mean? (maybe I need to extend the effect further, what is the resolution of the game)

**Comment by FlatOutPS2** [comment]
Does the Tekken 5 shader only affect one stage?

**Comment by refractionpcsx2** [comment]
> By pretty much what do you mean? (maybe I need to extend the effect further, what is the resolution of the game)

I was wrong, the blue bar is still just on the left, ill see if i can do a block dump of the transition so you can test it.

Settings were as picture above but CRC to minimum

**Comment by gregory38** [comment]
Maybe maybe not. I don't know. My dump is the acid stage but I know other stages use a channel effect. But maybe not the same.

**Comment by refractionpcsx2** [comment]
Here's a GT4 transition dump, apologies to the SSD ;) http://www.filedropper.com/gt4-transition

**Comment by FlatOutPS2** [comment]
Tekken 5 acid stage is green now, like software mode. If that was what was supposed to be fixed, it works. :P

I did notice a wrong fire/heat effect on the burning temple stage, but it seems unrelated.

**Comment by gregory38** [comment]
Actually I'm not sure it is the acid stage. Here the screenshot.
tekken5

@refractionpcsx2 
dump is fine here. It feels like a texture cache insanity. Did you try without HW hack?

**Comment by gregory38** [comment]
Maybe test to replace
```
		s[0].XYZ.X = (uint16)(m_context->XYOFFSET.OFX + 0);
		s[1].XYZ.X = (uint16)(m_context->XYOFFSET.OFX + 16384);

```
by
```
		s[0].XYZ.X = (uint16)(m_context->XYOFFSET.OFX - 640);
		s[1].XYZ.X = (uint16)(m_context->XYOFFSET.OFX + 16384);	
```

**Comment by refractionpcsx2** [comment]
> dump is fine here. It feels like a texture cache insanity. Did you try without HW hack?

Just tried it with HW Hacks completely disabled, still get the blue bar. All other settings again as my screenshot above but CRC @ Minimum

**Comment by FlatOutPS2** [comment]
The Tekken 5 stage from the screenshot is Moonlit Wilderness. It along with at least 2 other stages benefit from the shader! :D 

Tekken 5 burning temple the heat effect only works on the top half of the screen:
[Tekken 5 burning temple.zip](https://github.com/PCSX2/pcsx2/files/253075/Tekken.5.burning.temple.zip)

**Comment by gregory38** [comment]
@refractionpcsx2 I don't think I will be able to fix it. I have the game, I will need to play it. But I guess it is likely a texture cache issue. Or it could be another effect not emulated properly. Burnout/R&C also suffers of a left column issue.

```
The Tekken 5 stage from the screenshot is Moonlit Wilderness. It along with at least 2 other stages benefit from the shader! :D 
```
Ok good news. I will sleep well tonight ;)

```
Tekken 5 burning temple the heat effect only works on the top half of the screen:
```
Hum top half is working, so bottom half isn't working (like a too long list of game). I guess it could go in the meta tracker.

**Comment by gregory38** [comment]
By the way an interesting stat from a GS dump (license fail screen)

The frame is rendered with ~1730 GS draw calls. (one GS draw call could be several GPU draw call if a conversion is needed).
My HLE shader replaces 1540 GS draw calls by a single one !!!

**Comment by FlatOutPS2** [comment]
Tourist Trophy also often has the same blue left bar that GT4 has, but also some grey bars:
[Tourist Trophy.zip](https://github.com/PCSX2/pcsx2/files/253089/Tourist.Trophy.zip)

**Comment by gregory38** [comment]
Does the bug exists in CRC Full?

**Comment by FlatOutPS2** [comment]
> Does the bug exist in CRC Full?

Yes.

**Comment by refractionpcsx2** [comment]
> My HLE shader replaces 1540 GS draw calls by a single one !!!

That's a pretty good go, can't argue with that ;)

**Comment by MrCK1** [comment]
I guess this is a texture cache issue as well. With CRC None, I got a similar effect on IB-3 (right before the screen transition ends)
gsdx_20160506182010
gsdx_20160506182049

**Comment by tabnk** [comment]
Tested v1.5.0-dev-721-g265ea82.
GT4 brightness/contrast cannot change.

gsdx_20160507080431
GS dump here https://www.sendspace.com/file/rlmu38

**Comment by tabnk** [comment]
Tested v1.5.0-dev-721-g265ea82.
Tekken 5 missing menu bar in acid scene.
Incorrect
gsdx_20160507081107
Correct
gsdx_20160507081213

GS dump here https://www.sendspace.com/file/fi90zo

**Comment by gregory38** [comment]
Yes not yet in master and it requires crc minimum level not none. Because hle shaders are a kind of hack.

**Comment by refractionpcsx2** [comment]
@tabnk please make sure you are using the appveyor build in this project or a build of this product from this branch, pissing results from master is really not helpful at this point

**Comment by FlatOutPS2** [comment]
In Tekken 5 the menu bar that tabnk posted is missing when CRC is set to Partial or higher. It is there  at minimum and none.

**Comment by gregory38** [comment]
Ok. I move the Tekken5 (and tales of abyss) to full level.

**Comment by bositman** [comment]
Huh I just tried Tekken 5 to confirm all weird stuff it does are fixed and I get a crash after the Namco logo with every hardware renderer..only SW works

**Comment by gregory38** [comment]
I may need to rebase on master. I potentially fix the issue already.

**Comment by gregory38** [comment]
@bositman I did the rebase. Tell me if it works better. Thanks you.

**Comment by FlatOutPS2** [comment]
That did the trick. It doesn't crash on switching to Starblade anymore.

**Comment by bositman** [comment]
Crash gone indeed. My report for Tekken 5:
Moonlight wilderness stage (flower depth blur+colors): Both now work great, but only in native. Scaling causes thin black lines forming squares all over the screen
Burning temple stage: Heat movement effect: Works only in top vertical half of screen
Acid rain stage: Coloring was wrong, now looks perfect. Scaling causes lines here too
City at sunset stage: Lens flare-Sun: Not fixed, lens flare still gets bugged when a character is in front of it

**Comment by FlatOutPS2** [comment]
>  Burning temple stage: Heat movement effect: Works only in top vertical half of screen

The heat effect has black line squars all over the screen too at higher than native resolutions.

**Comment by tabnk** [comment]
Tekken 5 - Moonlight wilderness stage channel effect issue same as @bositman mention?

gsdx_20160507082216

GS dump here https://www.sendspace.com/file/cin0p0

**Comment by tabnk** [comment]
Tekken 5 Burning temple stage: Heat movement effect same as @bositman mention?
gsdx_20160507082125

GS dump here https://www.sendspace.com/file/50kx1u

**Comment by gregory38** [comment]
```
City at sunset stage: Lens flare-Sun: Not fixed, lens flare still gets bugged when a character is in front of it
```
Is it at half-top or half-bottom of the screen?

I'm aware of the scaling issue. It is the same issue that plague all games that read back the framebuffer. `Moonlight wilderness` does 3-4 frambuffer blending with itself, every time you have an half-texel offset so result is awful. All sampling code must be redone to bypass the texture cache rescaling. 

First I would like to fix remaining issue with the channel effect. ToA still get a texel scrambling issue. Ghost in the Shell/ Ridge Racer/ (man hunt?) would love a dedicated shader too.

**Comment by FlatOutPS2** [comment]
tekken 5
The lens-flare effect isn't half anything, it's just that there's a square the size of the sun in front of the characters when they stand in front of the sun. It looks fine in native resolution though, so it's a scaling issue too.

**Comment by gregory38** [comment]
Hum, the game has a resolution of game boy (192x128). Therefore an half pixel/texel shift is quite big. I think my increase of the framebuffer made the scaling worst. Maybe I will revert it until I recode the texture cache scaling.

**Comment by gregory38** [comment]
Ok. Tales of Abyss was only a CRC issue. Could I merge this PR ? Or is there any pending regression

**Comment by FlatOutPS2** [comment]
GT4 & Tourist Trophy don't have any regression, and Tekken 5 not any directly caused by this PR either.

**Comment by refractionpcsx2** [comment]
Cool so Tales and Urban Chaos no longer need CRC? Or is that additional stuff?

**Comment by lp200** [comment]
GT3 still missing crossfade effect 
tested v1.5.0-dev-732


non-TC plugin crossfade
gsdx_20150628092839

**Comment by gregory38** [comment]
@refractionpcsx2 Yes CRC are useless for those games. At least for now. They have both a dedicated shader for the channel effect. But so far, only 2 games use a 16 bits depth. UC moves depth to green channel and ToA moves it to alpha channel. The trick is that ToA masks the green channel so it is easy to distinguish between the 2.
Note: ToA effect likely requires BUA on high.

@lp200 
What CRC level did you set ?

**Comment by lp200** [comment]
@gregory38
Tested none and minimum 
This effect works correctly only in non-TC plugin ever.

Actual PS2
https://youtu.be/yV-AkUYZwOA?t=18

**Comment by gregory38** [comment]
What do you mean by "non-TC" plugin ?

**Comment by refractionpcsx2** [comment]
> UC moves depth to green channel and ToA moves it to alpha channel. The trick is that ToA masks the green channel so it is easy to distinguish between the 2.

That all sounds very much like we're guessing based on results, isn't there a definitive way to tell what it's trying to do and just have it do what it needs? there will probably be another game that uses the blue channel and one that does it with the red channel, so it would be better if we could see the sequence of events that makes that happen.

**Comment by refractionpcsx2** [comment]
> What do you mean by "non-TC" plugin ?

I think he means a Texture Cache Disabled build

**Comment by gregory38** [comment]
```
That all sounds very much like we're guessing based on results, isn't there a definitive way to tell what it's trying to do and just have it do what it needs? there will probably be another game that uses the blue channel and one that does it with the red channel, so it would be better if we could see the sequence of events that makes that happen.
```
Yes I'm guilty here, I looked at SW rendering behavior and I did the same for the HW renderer. It was mandatory for my head sanity.

On ToA you could extract the real information from the Vertex/Texture coordinate of the current draw call. UC requires the info of an extra doc call.

You can check the GS manual chapter 8 (GS memory format). The input texture is written as 16 bits depth and read as a 8 bits palette index. There are some tricks on WMS/WMT to mirror texture coordinate. And a lots of sprite to unscramble texel position to put them in the same order as a 32 bits color format. It is a huge&ugly mess.
ToA is "normal" case as it only extract the 8 msb bit of the depth. UC is more complicated because the game extracts only the "green channel of RGB5A1" depth (depth is pure 16 bits). I guess you understand why there are 2 draw calls for this game, as Green is in both MSB and LSB bits.

Honestly I think the number of games that use a channel effect on a 16 bits (depth) buffer are limited (GS emulation always prove me wrong). I don't think it worth to find a complex and not really generic solution. It is the limitation of the HLE shader approach, you end up with a shader per game due to small variation. 

```
I think he means a Texture Cache Disabled build
```
Oh. Hard to say if it is a related issue.

**Comment by refractionpcsx2** [comment]
Thanks for the explanation, that being said then is there any way we can print something when we thing a game is going to use one of these effects, just to say to report it if it does look broken? If this is going to be per-game, we will need to know about it, or hopefully find some common ground with those effects, hopefully something as simple as what you have done.

**Comment by gregory38** [comment]
There are various print for the openGL renderer. However it will be nice to enable them on windows. 
* need to either put back a null function pointer checker on the logger function / or put a dummy print function for dx. 
* then enable debug/dev define in debug/dev build respectively

There is a common ground that is detected (not 100% accurate), which is the read back of a 32/24/16 bits color/depth as a 8 bits color index.

**Comment by gregory38** [comment]
FWIW, I just toyed an idea to avoid postprocessing line. You can see the result (tekken 5) here http://forums.pcsx2.net/Thread-Align-sprite-doesn-t-work-in-latest-PCSX2

**Comment by refractionpcsx2** [comment]
That does looks great, can it be done efficiently and compatible?

**Comment by gregory38** [comment]
It depends. The fast way. We know when an old render buffer is read as a sprite texture. We know t min/max and xy min/max. We could make the hypothesis that most effect will be fullscreen area. It isn't always true. But hopefully most games just do a basic postprocessing.

The safe way will be more complex. But doable with a limited speed impact in most game.

**Comment by refractionpcsx2** [comment]
I hate to say it, but can we do both and have one as a hw hack? Preferably the fast option as always in, kind of like safe accurate blending

**Pull request merged**
