### PR TITLE
Optimize register list drawing

### PR DESCRIPTION
**Pull request by Kingcom**
Only draw the rows that are actually visible. Wasn't really an issue, but it can't hurt not to draw stuff you won't see anyway.

Also takes care of @turtleli 's remark.

### CODE REVIEW

**Comment by Kingcom** [comment]
And fixes a recently introduced issue with the mouse position calculation... GetViewStart reports in scroll units, for whatever reason, instead of pixels.

**Comment by turtleli** [comment]
Works fine.

Slight issue - Doesn't compile on Linux wx2.8 due to GetViewStart() (I think we're keeping wx2.8 compatibility on Linux until 1.4 is released)

**Comment by Kingcom** [comment]
What issue is there with GetViewStart()? As far as I can tell, it was around at the time: http://docs.wxwidgets.org/2.8.8/wx_wxscrolledwindow.html#wxscrolledwindowgetviewstart

**Comment by turtleli** [comment]
Oops, didn't notice that.

Both wx2.8 and wx3.0 have `void GetViewStart(int *x, int *y)` but only wx3.0 also has `wxPoint GetViewStart()`, which is what you've used. It would probably work fine if you changed it.

**Comment by Kingcom** [comment]
Okay, updated it.

**Pull request merged**
