### PR TITLE
Qt: Fix DPI scaling 125% + higher quality icons

### LINKED ISSUE #6255: [BUG]: Qt UI icons are pixelated when using fractional scaling
### Describe the Bug

UI icons looks pixelated and distorted while using 125% scaling in Windows.  With any higher scaling options everything looks fine

### Reproduction Steps

Set screen scaling to 125% in Windows display settings and open pcsx2-qtx64-avx2.exe

### Expected Behavior

_No response_

### PCSX2 Revision

v1.72828 (AVX2 - Qt)

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### PR DESCRIPTION
**Pull request by RedDevilus**
### Description of Changes

Qt: Fix DPI scaling 125% + higher quality icons

Upscaling on Qt didn't work properly as Windows calculates it differently, it's better to give far larger pictures and icons and let it downscale.

Also added most country flags that are relevant for PCSX2.

Reduces size icons from 3.5 MB to a whopping 0.21 MB (212 KB!) but looks even better for everyone.

Hopefully fixes #6255
### Rationale behind Changes

Less space used + fix that horrid blurry visual on start-up and 125% DPI on Windows
### Suggested Testing Steps

Test 125% but also other DPI levels to make sure

### CODE REVIEW

**Comment by RedDevilus** [comment]
QtIconBefore

QtIconAfter

**Comment by RedDevilus** [comment]
One thing I haven't fixed (yet if I feel like it is the stars needing a fixed amount:
image

**Comment by RedDevilus** [comment]
Tested on 125% DPI mainly but tested others (still looks better even with reduced sizes)
Before:
image

After:
image

**Comment by LeetPanda1337** [comment]
Nice. I also tried this for Duckstation. Sorry, I'm not developer and don't know how to use github, so i didn't understand how to send bug report in duckstation repo because there is no "issues" tab... 

duckstation-qt-x64-ReleaseLTCG_2022-05-29_18-38-18

**Comment by RedDevilus** [comment]
Yeah, I know Duckstation has the same issue, was looking at that as well.

**Comment by RedDevilus** [comment]
Keep in mind that there are still missing region flags as current ones are the american/europe/japanese/unknown flags that's also for something later to address.

**Comment by RedDevilus** [comment]
Haven't bothered hooking up the new region flags (still misses some) and I still have to change the GameDB to confirm to the correct region. Probably done in a new PR.

**Comment by MarcoEstevez** [comment]
Great work!

I wonder whether same fix could be applied to duckstation

image

I'm aware that is not the proper forum to ask this so please forgive me, but since developer who brought QT to pcsx2 is the maintainer of duckstation and https://github.com/stenzek/duckstation does not allow open issues I couldn't find a better way.

**Comment by MarcoEstevez** [comment]
Thanks for answering, I removed post cause I noticed it was already mentioned on the thread above

**Pull request merged**
