### PR TITLE
GSdx-gui: Put TC Offset X Y hacks in one line similar to Skipdraw Offset

### PR DESCRIPTION
**Pull request by lightningterror**
image

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Looks good to me 👍

**Comment by willkuer** [comment]
I get the point but the missing colon after offsets kind of looks awkward or? There was a possibility for a monster c-c-colon combo

**Comment by lightningterror** [comment]
I added after X and Y instead. Wasn't too sure after offset.

**Comment by willkuer** [comment]
Yes I know. I‘d say syntactically you did the best. Sometimes fate is just against UI design.

**Pull request merged**
