### PR TITLE
GameDB: Add Syphon Filter: The Omega Strain Demo disc Speed Fix

### PR DESCRIPTION
**Pull request by kakashi314**
### Description of Changes
like we discussed yesterday on discord, this is a patch for syphon filter in the demo disc using dynapatching, i will have leyo test it and see if it's working.

### Rationale behind Changes
It's how the game is supposed to be played.

### Suggested Testing Steps
Hold merge until i can get leyo to confirm that it's working well, and make sure i didn't put any typo.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
That's not how you do comments in YAML.

**Comment by kakashi314** [comment]
> That's not how you do comments in YAML.

damn, where do i put it then ? and what do i use ? # ?

**Comment by refractionpcsx2** [comment]
yes, the hash. I'd put it opposite the "pattern:" tag, personally, if it's ok with that.

**Comment by kakashi314** [comment]
i Hope Master ci accepts now

**Comment by kakashi314** [comment]
I know it's not opposite of pattern, but yaml validator is saying it's valid, so i'll go with it, but if you're not ok with it i'll be happy to change it :)

**Comment by kakashi314** [comment]
Now it's ready for checks

**Comment by refractionpcsx2** [comment]
I'll run the CI just to make sure it's valid

**Comment by kakashi314** [comment]
> I'll run the CI just to make sure it's valid

I'll update you after leyo is done testing.

**Comment by kakashi314** [comment]
If the comment is not too long for the Gameindex, then it's ready for merging

**Comment by refractionpcsx2** [comment]
My guess is there isn't enough pushback from the components because we have things running quickly compared to the console (especially half the GIF paths and the VU's), and their internal FPS limiter figured it could run at 50, but I suspect they never tested it on a PS2, cos it always ran at 25.

That's just my guess anyway.

**Pull request closed without merging**
