### PR TITLE
spu2x: remove hyperlink in windows about box

### PR DESCRIPTION
**Pull request by gregory38**
Code isn't free (and kinda useless)

### CODE REVIEW

**Comment by turtleli** [comment]
Compiles fine.

BTW, the About box isn't actually used at all.

**Comment by gregory38** [comment]
OoO, great people won't complain :)

**Comment by turtleli** [comment]
Indeed. :)

I'll merge this, then perhaps look into removing the About box.

**Comment by ramapcsx2** [comment]
Jake liked this ><

**Comment by gregory38** [comment]
I'm sorry but you know that copyright stuffs are annoying.

**Pull request merged**
