### PR TITLE
Fixed French translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**
Pull request for solving https://github.com/PCSX2/pcsx2/issues/1570

### CODE REVIEW

**Comment by gregory38** [comment]
The solution is to run the script to update all translations.

**Comment by FlatOutPS2** [comment]
> The solution is to run the script to update all translations.

Would be nice if we could do these updates first: https://github.com/PCSX2/pcsx2/issues/1620

**Comment by gregory38** [comment]
Please do a PR for all string changes. And please do it soon, otherwise it will be postponed after the release.

**Comment by gregory38** [comment]
I will integrate the PR if automatic translation update doesn't fix it.

**Comment by TotalCaesar659** [comment]
Sorry, I was busy and didn't read it. Do I have to check and fix this string in every language translation?

**Comment by TotalCaesar659** [comment]
OK, thank you very much.

**Comment by gregory38** [comment]
I updated all po file with latest string. It might need to fix a couple of fuzzy strings. Otherwise I think we can close this one.

**Pull request closed without merging**
