### PR TITLE
Fix some gcc warnings.

### PR DESCRIPTION
**Pull request by arcum42**
### Description of Changes
Got rid of some warnings in gcc over in the usb code. I decided clang warnings could wait for another time.

### Rationale behind Changes
Less warnings while compiling.

### Suggested Testing Steps
Compile pcsx2.

### CODE REVIEW

**Comment by arcum42** [comment]
No idea why rapidyaml wants to be part of this commit, as I didn't touch it.

**Comment by tellowkrinkle** [comment]
> No idea why rapidyaml wants to be part of this commit, as I didn't touch it.

Just Git submodules being great as always
git doesn't update submodules when you check out branches which makes it super easy to accidentally commit that

**Review by lightningterror — COMMENTED** [review]
Commits can be better named.

**Comment by arcum42** [comment]
Always planned on squashing the second commit with the first, which is why I wasn't too concerned with its name.

**Review by Mrlinkwii — APPROVED** [review]

**Pull request merged**
