### PR TITLE
Update 3rdparty

### PR DESCRIPTION
**Pull request by micove**
Update some 3rdparty dependencies
- bzip 1.0.4 has 2 security issues
- zlib 1.2.8 to sync with examples.
- glext is 25 months old.
- SoundTouch is a Frankenstein of various versions. I added x64 and cleaned up the vcxproj.
- wx3.0's polite message annoys me.

It compiles and should be safe. I'm doing a PR to see if there are any issues as to no update those.

The only outdated ones left are:
- libjpeg (could be replaced with libjpeg-turbo)
- libpng  (updated often, 1 point release behind)
- opencl (outdated and modified)
- w32pthreads (outdated and modified)
- winpcap (outdated)

### CODE REVIEW

**Comment by avih** [comment]
It should be safe to assume that you tested a bit at least one feature which uses the updated packages , right? :)

At the very least that sound stretching still performs well and that zlib didn't break save/load state, etc?

**Comment by micove** [comment]
Yes, I tested bzip, zlib, and soundtouch. Can't test OpenGL since my hardware does not support it.

I loaded a iso.gz to test zlib but I just checked the save states and they still work. These libraries have been used on the Linux side for years but I did some testing to see if the windows code path for those was different.

**Comment by avih** [comment]
Thanks.

> I'm doing a PR to see if there are any issues as to no update those.

So do you want to merge this now? or  still wait for something?

**Comment by gregory38** [comment]
openGL doesn't have any impact. It is only the new define to use newer extension. However I put them directly in GSdx so it can compile on older linux distribution.
What is your HW by the way?

**Comment by micove** [comment]
Oh okay, I will review the PR again and then merge it.

@gregory38 
I have a Mobility Radeon HD 4650 it supports OpenGL 3.3 and DX 10.1 from what I remember. To be fair it's suffering from artifacting since December and I can only use the generic drivers. I should get a Skylake laptop soon but I'm not thrilled about Optimus/Bumblebee.

**Comment by gregory38** [comment]
Both catalyst and the free driver must work. The free driver support more features. Globally you need 3.3 + a bunch of optional gl4 extensions.

**Comment by micove** [comment]
Yes, but since my card is artifacting it causes a kernel panic if I try to use the catalyst driver. I had to disable/blacklist it.

In windows, I can only use
```
Current Renderer: Direct3D9(Hardware mode) 
Microsoft Basic Render Driver (10.0.10240.16384)
```
In Linux can't remember it was something like VMware or Gallium SW rasterizer.

Anyway, when 25-30% of your screen is covered by permanent rainbow colored vertical bars and unusable you can't expect anything graphical intensive to work. I'm surprised that I can get 60 FPS with DX9 but the vertical lines ruin the experience hehe.

**Comment by mirhl** [comment]
@micove
Free driver which gregory was mentioning is radeon, catalyst is closed one. 

Also, if you are scared about optimus (but you still would like decent performance) you may want to check AMD's APUs. The fastest one (assuming you can find it) is as fast as a desktop 5770.

**Comment by micove** [comment]
I know, I mean the open source r600 driver was the one that fried my GPU.

What I tried to explain was that 
- Catalyst in Windwos (blue screen)
- Catalyst in Linux Kernel panic
- R600 in Linux it shows a bunch of errors and falls back to R600.


Also, I'm not scared of Optimus, I just hate it from a technical perspective but that is unrelated to this topic.

**Comment by micove** [comment]
Anyway, I just read the changes again and there was no API/ABI break so everything should work as before. I'm merging this so I can rebase the props PR that I'm working on.

**Comment by avih** [comment]
Sounds good to me. Thanks.

**Comment by gregory38** [comment]
I used to have a blue rainbow/fog of death in my hd5770. I disabled the low power state of the memory (bios update) and the card was working (with extra consumption). Now I have an nvidia gpu and the driver is 2x times (if not 3x) faster.

**Comment by mirhl** [comment]
AFAIK 4xxx series has been discontinued after ***4*** years (and nevertheless it still received another couple of updates till beyond 5 years from release)

Also, all the graphics cores released after.. Rx 200 I suppose (?) are going to get the new official unified [AMDGPU](http://www.phoronix.com/scan.php?page=news_item&px=AMD-AMDGPU-Released) open source kernel driver

**Comment by micove** [comment]
Laptop Bios are extra gimped. It only has 1-3 options and nothing useful.

In linux it used to idle at 40C but when I went to the open source driver since I had to update the xserver on sid it jumped to idle temp at 80C. This is the temperature of the cpu but since the CPU was at 1% utilization that was actually the heat from the GPU affecting the reading from the CPU which is right next to it on the laptop. The GPU was obviously running hotter than that. So I decided to enable the PM as documented in the open source docs and my screen turned into a checker pattern with rainbow and black pixels everywhere. After that rainbow vertical bars forever. I get more annoyed by not being able to go over 1024*768 resolution than the fact that I can't read ~33% of my screen since you can't see anything under the rainbow bars and they are spread out evenly every 2 inches and are about 1 inch thick.

**Comment by gregory38** [comment]
I mean the gpu bios. Like me on the past, it seems to be a low power memory feature. It gives the opportunity to learn the magic key ;)
Anyway it is a dangerous operation (flashing of gpu bios) so your best bet it to buy a new stuff. Besides I will maybe discontinue the GL3 support.

**Comment by micove** [comment]
Oh, GPU bios. Nahh, if I mess up the blind flash I will have a brick. I will get a new laptop soon anyway since I survived with this one waiting for Skylake. I already got used to moving windows left and right to avoid the vertical bars and be able to read text but I commit a lot of typos in the blind spots :\.

**Pull request merged**
