### PR TITLE
GameDB: Oni (PAL-F) Black Screen Fix & Missing Oni PAL Entries

### PR DESCRIPTION
**Pull request by Catarax**
The french version of Oni will be playable, no more stuck in a black screen after the intro videos. Added also the PAL-S and PAL-I Oni entries to the list.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
hmm, shouldn't be any games needing that any more :/

**Comment by Catarax** [comment]
Still needed in the latest build.

**Comment by refractionpcsx2** [comment]
There must be a DMA issue somewhere then.. damn

**Comment by willkuer** [comment]
Only in the french version it is needed? Or you just added spanish and italian version into the list and they probably need thr same hack but you can't test?

**Comment by Catarax** [comment]
SLES-50134 (PAL-E), SLES-50176 (PAL-F), SLES-50177 (PAL-G) use the same patch.
PAL-I and PAL-S need probably the same patch to work but i don't have theses specific version to confirm.

SLUS-20064 use the same kind of patch but at another adress.

**Comment by refractionpcsx2** [comment]
Will you be adding the other patches here or shall I go ahead and merge this?

**Comment by Catarax** [comment]
I could add the supposed patches for the other PAL Oni releaes but it'll remain untested.
I need your approval. Else, you can merge it. I don't plan to do more.

**Comment by Catarax** [comment]
I don't have the CRC of the others release so i can't do them at all. You can merge it.

**Comment by refractionpcsx2** [comment]
If you can't test the patches then best leave it, i'll just merge these :)

**Pull request merged**
