### PR TITLE
Catalan Translation

### PR DESCRIPTION
**Pull request by Dokman**
I am using the newest template, sorry for inactivity.

Frontend Translated

Emulation Settings menu:
EE/IOP done
VUs done
GS done
GS Window done
Speedhacks done
Game Fixes done
Other menus: done
Misc: Strings translated
PS: sorry for inactivity once again

To merge

### CODE REVIEW

**Comment by Dokman** [comment]
image

@Sarania @ssakash @gregory38 

I have translated the EE Cyclerate but... the text doesn't appear, why? you have add it in the template?

**Comment by gregory38** [comment]
You need to run it on 1.4 release. I will compile it against git with my script

**Comment by Dokman** [comment]
@gregory38 i can merge it? and how i can do it?

**Comment by Dokman** [comment]
in 20 minutos i will push a usable version

**Comment by Dokman** [comment]
@ghost it's done :smile:

**Comment by Dokman** [comment]
@gregory38 today i will push the description of everything or almost all the descriptions.

**Pull request merged**
