### PR TITLE
USB: Audio support for EyeToy / Konami ON-SAY microphone emulation

### LINKED ISSUE #4167: [Feature Request] Konami ON-SAY Microphone for Japanese Karaoke Revolution Games.
**Description**
This descriptor has been updated because i obtained the correct microphone for japanese karaoke revolution games.
I've got a descriptor for a konami branded E-UR040 microphone.

**Reason**
make Japanese Karaoke Revolution games work

Information for device AK5370           (VID=0x0556 PID=0x0001):

*** ERROR: Descriptor has errors! ***

------------------------------
Connection Information:
------------------------------
Device current bus speed: FullSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x002C
Current configuration value: 0x00
Number of open pipes: 0

------------------------------
Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0110	bcdUSB
0x00	bDeviceClass      
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x08	bMaxPacketSize0   (8 bytes)
0x0556	idVendor
0x0001	idProduct
0x0001	bcdDevice
0x01	iManufacturer
0x02	iProduct     
0x00	iSerialNumber
0x01	bNumConfigurations
Hex dump: 
0x12 0x01 0x10 0x01 0x00 0x00 0x00 0x08 0x56 0x05 
0x01 0x00 0x01 0x00 0x01 0x02 0x00 0x01 

-------------------------
Configuration Descriptor:
-------------------------
0x09	bLength
0x02	bDescriptorType
0x0076	wTotalLength   (118 bytes)
0x02	bNumInterfaces
0x01	bConfigurationValue
0x00	iConfiguration
0x80	bmAttributes   (Bus-powered Device)
0x2D	bMaxPower      (90 mA)
Hex dump: 
0x09 0x02 0x76 0x00 0x02 0x01 0x00 0x80 0x2D 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x00	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x01	bInterfaceSubClass   (Audio Control Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface
Hex dump: 
0x09 0x04 0x00 0x00 0x00 0x01 0x01 0x00 0x00 

AC Interface Header Descriptor:
------------------------------
0x09	bLength
0x24	bDescriptorType
0x01	bDescriptorSubtype
0x0100	bcdADC
0x0026	wTotalLength   (38 bytes)
0x01	bInCollection
0x01	baInterfaceNr(1)
Hex dump: 
0x09 0x24 0x01 0x00 0x01 0x26 0x00 0x01 0x01 

AC Input Terminal Descriptor:
------------------------------
0x0C	bLength
0x24	bDescriptorType
0x02	bDescriptorSubtype
0x01	bTerminalID
0x0201	wTerminalType   (Microphone)
0x02	bAssocTerminal
0x01	bNrChannels   (1 channels)
0x0000	wChannelConfig
0x00	iChannelNames
0x00	iTerminal
Hex dump: 
0x0C 0x24 0x02 0x01 0x01 0x02 0x02 0x01 0x00 0x00 
0x00 0x00 

AC Output Terminal Descriptor:
------------------------------
0x09	bLength
0x24	bDescriptorType
0x03	bDescriptorSubtype
0x02	bTerminalID
0x0101	wTerminalType   (USB Streaming)
0x01	bAssocTerminal
0x03	bSourceID
0x00	iTerminal
Hex dump: 
0x09 0x24 0x03 0x02 0x01 0x01 0x01 0x03 0x00 

AC Feature Unit Descriptor:
------------------------------
0x08	bLength
0x24	bDescriptorType
0x06	bDescriptorSubtype
0x03	bUnitID
0x01	bSourceID
0x01	bControlSize
bmaControls: 
 0x43	Channel(0) - Mute / Volume / Automatic Gain
0x00	iFeature

Hex dump: 
0x08 0x24 0x06 0x03 0x01 0x01 0x43 0x00 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x01	bInterfaceNumber
0x00	bAlternateSetting
0x00	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x02	bInterfaceSubClass   (Audio Streaming Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface
Hex dump: 
0x09 0x04 0x01 0x00 0x00 0x01 0x02 0x00 0x00 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x01	bInterfaceNumber
0x01	bAlternateSetting
0x01	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x02	bInterfaceSubClass   (Audio Streaming Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface
Hex dump: 
0x09 0x04 0x01 0x01 0x01 0x01 0x02 0x00 0x00 

AS Interface Descriptor:
------------------------------
0x07	bLength
0x24	bDescriptorType
0x01	bDescriptorSubtype
0x02	bTerminalLink
0x01	bDelay
0x0001	wFormatTag   (PCM)
Hex dump: 
0x07 0x24 0x01 0x02 0x01 0x01 0x00 

AS Format Type 1 Descriptor:
------------------------------
0x17	bLength
0x24	bDescriptorType
0x02	bDescriptorSubtype
0x01	bFormatType   (FORMAT_TYPE_1)
0x01	bNrChannels   (1 channels)
0x02	bSubframeSize
0x10	bBitResolution   (16 bits per sample)
0x05	bSamFreqType   (Discrete sampling frequencies)
0x001F40 	tSamFreq(1)   (8000 Hz)
0x002B11 	tSamFreq(2)   (11025 Hz)
0x005622 	tSamFreq(3)   (22050 Hz)
0x00AC44 	tSamFreq(4)   (44100 Hz)
0x00BB80 	tSamFreq(5)   (48000 Hz)
Hex dump: 
0x17 0x24 0x02 0x01 0x01 0x02 0x10 0x05 0x40 0x1F 
0x00 0x11 0x2B 0x00 0x22 0x56 0x00 0x44 0xAC 0x00 
0x80 0xBB 0x00 

Endpoint Descriptor (Audio/MIDI 1.0):
------------------------------
0x07	bLength
0x05	bDescriptorType
*** ERROR: Invalid descriptor length 0x07 for Audio/MIDI 1.0 endpoint (9 bytes expected)
Hex dump: 
0x07 0x05 0x81 0x01 0x64 0x00 0x01 

AS Isochronous Data Endpoint Descriptor:
------------------------------
0x07	bLength
0x25	bDescriptorType
0x01	bDescriptorSubtype
0x01	bmAttributes   (Sampling Frequency)
0x00	bLockDelayUnits   (undefined)
0x0000	wLockDelay
Hex dump: 
0x07 0x25 0x01 0x01 0x00 0x00 0x00 

Microsoft OS Descriptor is not available. Error code: 0x0000001F

--------------------------------
String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  
Hex dump: 

0x01   0x0000  "AKM             "
Hex dump: 
0x22 0x03 0x41 0x00 0x4B 0x00 0x4D 0x00 0x20 0x00 
0x20 0x00 0x20 0x00 0x20 0x00 0x20 0x00 0x20 0x00 
0x20 0x00 0x20 0x00 0x20 0x00 0x20 0x00 0x20 0x00 
0x20 0x00 0x20 0x00 

0x02   0x0000  "AK5370          "
Hex dump: 
0x22 0x03 0x41 0x00 0x4B 0x00 0x35 0x00 0x33 0x00 
0x37 0x00 0x30 0x00 0x20 0x00 0x20 0x00 0x20 0x00 
0x20 0x00 0x20 0x00 0x20 0x00 0x20 0x00 0x20 0x00 
0x20 0x00 0x20 0x00 

------------------------------

Whole Device Descriptor as hex dump: 
0x12, 0x01, 0x10, 0x01, 0x00, 0x00, 0x00, 0x08, 0x56, 0x05, 
0x01, 0x00, 0x01, 0x00, 0x01, 0x02, 0x00, 0x01

Whole Configuration Descriptor as hex dump: 
0x09, 0x02, 0x76, 0x00, 0x02, 0x01, 0x00, 0x80, 0x2D, 0x09, 
0x04, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x09, 0x24, 
0x01, 0x00, 0x01, 0x26, 0x00, 0x01, 0x01, 0x0C, 0x24, 0x02, 
0x01, 0x01, 0x02, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x09, 
0x24, 0x03, 0x02, 0x01, 0x01, 0x01, 0x03, 0x00, 0x08, 0x24, 
0x06, 0x03, 0x01, 0x01, 0x43, 0x00, 0x09, 0x04, 0x01, 0x00, 
0x00, 0x01, 0x02, 0x00, 0x00, 0x09, 0x04, 0x01, 0x01, 0x01, 
0x01, 0x02, 0x00, 0x00, 0x07, 0x24, 0x01, 0x02, 0x01, 0x01, 
0x00, 0x17, 0x24, 0x02, 0x01, 0x01, 0x02, 0x10, 0x05, 0x40, 
0x1F, 0x00, 0x11, 0x2B, 0x00, 0x22, 0x56, 0x00, 0x44, 0xAC, 
0x00, 0x80, 0xBB, 0x00, 0x07, 0x05, 0x81, 0x01, 0x64, 0x00, 
0x01, 0x07, 0x25, 0x01, 0x01, 0x00, 0x00, 0x00

------------------------------

Connection path for device: 
USB xHCI Compliant Host Controller
Root Hub
AK5370           (VID=0x0556 PID=0x0001) Port: 10

Running on: Windows 10 or greater (Build Version 22623)

Brought to you by TDD v2.17.0, Feb 23 2021, 14:04:02

### LINKED ISSUE #7626: [BUG]: EyeToy - Play [PAL] (SCES_515.13) - No audio and broken capture window in Video Message
### Describe the Bug

In EyeToy - Play [PAL] (SCES_515.13) when you want to record video messages or load and watch a saved video message, you hear and see that no audio is recording and the capture screen is always broken. The recording device used for this game series was the official [camera](https://en.wikipedia.org/wiki/EyeToy).

### Reproduction Steps

1.) Start the game normally

2.) Hit Start in the opening screen to access the main menu (you can also use the controller to navigate)

3.) Move to Video Messaging and select it to enter the Messages menu

4.) Hit Record Message and then you can reproduce the bug

### Expected Behavior

The recorded audio must be there when a recorded message is playing and the capture window must be shown in the same way as in the rest of the game.

### PCSX2 Revision

v1.7.3738

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 CPUs), ~2.6GHz

### GPU

NVIDIA GeForce RTX 2070

### GS Settings

1.) I use Skip MPEG Hack (Skips Videos/FMVs) to skip the introduction video, which you can not skip with the controller - all the rest is disabled

2.) 3a

3.) Auto Flush and Mipmapping are enabled in global settings - does not matter for this game if these two options are enabled or disabled3b

4.) 3c

5.) Use Blit Swap Chain is enabled in global settings - does not matter for this game if this option is enabled or disabled3d

### Emulation Settings

1.)

2.) Frame Rate Control is set to default

3.) 

4.) Little side question: Is it possible in the future to add certain special options, for example to flip the image horizontally, camera audio recording and so on?

### GS Window Screenshots

No screenshots, but a video for download:
<a href="https://www.file-upload.net/download-15061435/2022-12-1906-36-04_EyeToy-Play.mp4.html">2022-12-1906-36-04_EyeToy-Play.mp4</a>

### Logs & Dumps

Emulog:
[emulog.txt](https://github.com/PCSX2/pcsx2/files/10257052/emulog.txt)

Single Frame GS-Dump:
<a href="https://www.file-upload.net/download-15061438/SingleFrameGS-Dump.rar.html">SingleFrameGS-Dump.rar</a>

Multi Frame GS-Dump:
<a href="https://www.file-upload.net/download-15061439/MultiFrameGS-Dump.rar.html">MultiFrameGS-Dump.rar</a>

I do not think the dumps will be of much use in this particular case. Let us see. :)

### PR DESCRIPTION
**Pull request by Florin9doi**
### Description of Changes
- Merge Singstar and Logitech mics in a single device with 2 subtypes
- Audio support for EyeToy
- Konami On-Say microphone emulation / Jaleco Mic Converter / MTV Music Generator 2 Sampler Kit

### Rationale behind Changes
Closes #4167, Closes #7626, 

### Suggested Testing Steps
- Singstar
- EyeToy: https://github.com/PCSX2/pcsx2/issues/4763#issuecomment-2246832676
- Karaoke Revolution: https://github.com/PCSX2/pcsx2/issues/4167#issuecomment-2260417475

### CODE REVIEW

**Comment by GitHub-Khi** [comment]
This will only partially close my [#7626](https://github.com/PCSX2/pcsx2/issues/7626) report, right? Definitely a very good job for all these PRs. Respect - keep it up! :)

**Comment by Florin9doi** [comment]
> This will only partially close my [#7626](https://github.com/PCSX2/pcsx2/issues/7626) report, right? Definitely a very good job for all these PRs. Respect - keep it up! :)

Yes, this PR will only fix the audio. The video issue is a duplicate for #4635

**Comment by seta-san** [comment]
japanese karaoke revolution is working and judging my singing harshly.

**Comment by prafullpcsx2** [comment]
Thanks @Florin9doi 
It works fine now. Also did a video showing this

https://youtu.be/9-75TGd2D9I?si=X7ASVKhsvVpxRz2U

**Review by lightningterror — COMMENTED** [review]
Some new compiler warnings to cleanup:
https://github.com/PCSX2/pcsx2/actions/runs/10442579076/job/28915025584?pr=11715#step:13:770

**Comment by seta-san** [comment]
i know this just got merged but at some point i think we lost the second player microphone on both the konami and singstar

**Comment by Florin9doi** [comment]
Konami is a mono mic

**Comment by seta-san** [comment]
> Konami is a mono mic

no. it's got a second one. https://forums.pcsx2.net/attachment.php?aid=72457

**Comment by Florin9doi** [comment]
https://github.com/jackun/USBqemu-wheel/issues/63#issuecomment-781726802

**Comment by seta-san** [comment]
okay. cool. i thought maybe the interface to the ps2 was stereo and each microphone took one of two channels. i don't know if two players was ever possible then.

**Pull request merged**
