### PR TITLE
x86/iR5900: Fast forward timeout loops

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

God of War 2 and other games (e.g. NFS series) have these timeout loops which just spin for a few thousand iterations, usually after kicking something which results in an IRQ, but instead of cancelling the loop, they just let it finish anyway. Such loops look like:

```
00186D6C addiu  v0,v0, -0x1
00186D70 nop
00186D74 nop
00186D78 nop
00186D7C nop
00186D80 bne    v0, zero, ->$0x00186D6C
00186D84 nop
```

Skipping them entirely seems to have no negative effects, but we skip cycles based on the incoming value if the register being decremented, which appears to vary. So far I haven't seen any which increment instead of decrementing, so we'll limit the test to that to be safe.

### Rationale behind Changes

Reduces EE thread CPU usage by up to 40% when not VU bottlenecked in God of War 2.

### Suggested Testing Steps

Test GOW2, and see if any other games have these silly timeout loops. Some that I've found include the NFS series and Ratchet.

### CODE REVIEW

**Comment by lightningterror** [comment]
Maybe someone can do some benchmarks.

**Comment by JordanTheToaster** [comment]
something

kjrtkrkmrtkm

**Comment by TellowKrinkle** [comment]
> something
> 
> kjrtkrkmrtkm

Is there a reason one of those is a clang build and the other isn't?

**Comment by refractionpcsx2** [comment]
> > something
> > kjrtkrkmrtkm
> 
> Is there a reason one of those is a clang build and the other isn't?

all master builds are clang, it's just the old filename because updates.

**Comment by JordanTheToaster** [comment]
> Is there a reason one of those is a clang build and the other isn't?

There isn't an FPS difference between either exe for GOW 2 when doing these tests.

**Comment by lightningterror** [comment]
Can you repost the pictures with the game title named properly so they can be used in the progress reports?

**Comment by JordanTheToaster** [comment]
> Can you repost the pictures with the game title named properly so they can be used in the progress reports?

NO FUN ALLOWED

**Comment by stenzek** [comment]
The titles are the best part.

**Comment by refractionpcsx2** [comment]
I guess this is fine then :) If you wanna remove that logging, then we can mergey merge

**Comment by stenzek** [comment]
Done.

**Pull request merged**
