### PR TITLE
GS/DX12: Fix targets getting stuck undirtied

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Caused flickering/black frames/etc.

### Rationale behind Changes

Regression from something recent.

### Suggested Testing Steps

Check GTA:SA or GT4:O in DX12.

### CODE REVIEW

**Review by JordanTheToaster — APPROVED** [review]

**Comment by noobinthesky** [comment]
I am having issues wit this latest update. When selecting download and install on PCSX2, I am receiving the following message: 

Capture

**Comment by noobinthesky** [comment]
When I hit okay, I get this message. Fix? 

image

**Comment by kamfretoz** [comment]
@noobinthesky GitHub is not for support, go to our Discord server if you need help.

**Comment by noobinthesky** [comment]
> @noobinthesky GitHub is not for support, go to our Discord server if you need help.

Can you send me location for the server then?

**Pull request merged**
