### PR TITLE
GameDB: Delete Mipmap and Add Blending Accuracy to Spyro: Enter the D…

### PR DESCRIPTION
**Pull request by CRASHARKI**
…ragonfly

### Description of Changes

I got rid of the forced Mipmap and added Blending Accuracy 3 for Spyro: Enter the Dragonfly

### Rationale behind Changes

Mipmap imposition was removed since it downgrades the game graphics severely without adding/fixing anything, and makes everything look unnecessarily blurry. It also breaks compatibility with Texture-Packs. Added Blending Accuracy 3 to fix Gems not shining properly.

### Suggested Testing Steps

Just playing the game will show the visual improvements/corrections.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Take out the mipmap removal, the blending accuracy change is fine, but the game should have mipmapping, if you don't like it you can override it.

**Comment by Mrlinkwii** [comment]
>And original software's more limited/downgraded graphics shouldn't be imposed, since they are a personal preference and don't fix anything at all. 

it fixes stuff at native res in hw , upscaling is optional @CRASHARKI

**Comment by refractionpcsx2** [comment]
well, our first and foremost is accuracy, if you don't like the mipmapping effect you can disable it in the per game settings, we're not removing it from the db just because you like it more.

**Comment by Mrlinkwii** [comment]
@CRASHARKI  ill refer back to the  original pr  , it fixes mountain's textures in game in hw mode

**Comment by CRASHARKI** [comment]
@Mrlinkwii It doesn't. They just look blurry, that's not fixing, because there's nothing wrong with it. If someone wants accurate they would play on sw. Those who play hw seek best possible graphics.

**Comment by refractionpcsx2** [comment]
and as I said @CRASHARKI you're welcome to disable mipmapping in your per game settings if you don't like it.

**Comment by CRASHARKI** [comment]
So, we're ignoring the fact that it breaks texture-packs in favor of looking worse for the sake of "accuracy"? Which, btw, was never the intention of the developers, since the Gamecube version (in real hardware, of course) does not have blurry textures due to hardware limitations (like the PS2): https://youtu.be/qWs3LOMsxd8?t=36.

**Comment by refractionpcsx2** [comment]
again, for the 8th time, if you don't like it if or you want to use texture packs, then I suggest you turn off mipmapping in your per-game settings, 99% of people don't use texture packs, and if you are you should redump the textures with mipmaps, if that's not the issue then the texture replacement issue would need to be looked in to, but for now you can disable mipmaps.

**Pull request closed without merging**
