### PR TITLE
Corrections of GameIndex Regions

### PR DESCRIPTION
**Pull request by pgert**
Specifications & Corrections of PAL-regions, mainly extracted from:
http://redump.org/discs/system/ps2/
http://ns348841.ip-91-121-109.eu/psxdata/psx2/pal_list2.html
http://wiki.redump.org/index.php?title=Sony_Playstation_2_PAL_Missing_Dumps

### CODE REVIEW

**Comment by pgert** [comment]
This file is too large to be viewed online, here at GitHub.
If anyone is interested in examining it,
 you can download it and use WinMerge (or equivalent) to compare.
www.winmerge.org

**Comment by refractionpcsx2** [comment]
You've got a couple of NTSC-UK's in there, there is no such thing as NTSC in the UK.

I mean, we know what it is and it does exist, but nothing in the UK uses NTSC, we are completely PAL so that wouldn't have been a release format :P

**Comment by i30817** [comment]
Are those hacks of PAL games to 60 fps or something o.O
why would they think changing the region code would be a good idea?

**Comment by ramapcsx2** [comment]
pgert: 
Please provide a way for people to see diffs in your pull requests.
When github can't show them, you could create one locally and upload to pastebin, for example.
We need to be able to go over changes, not blindly merge stuff ;)

**Comment by refractionpcsx2** [comment]
I had a quick look, most of it is changing PAL-Unk to PAL-M5 or something :P you can view the raw file on here then just save it as newgamedb.dbf then use winmerge to check it against the one in the master git repo

**Comment by pgert** [comment]
@refractionpcsx2:
The NTSC just cought by attention.
The E in PAL-E & NTSC-E can refer to "English", "Europe" or "España".
To clarify, I changed all PAL-E that refers to "english" & the two NTSC-E
 entries (which both refers to "english") into PAL-UK & NTSC-UK.
I also changed the PAL-E entries that refer to "Europe" into PAL-MX.
All PAL-E entries now refer to "España" (let me know if I missed any).
I intend to make another PR if this one is accepted in which the PAL-E entries
 are changed into PAL-ES (PAL-S is a bad choise, since it can refer to "Sweden";
 if you see an S-sticker on a car then it refers to "Sweden").

@i30817:
No hacks are affected - this is for Clarification & Correctness purposes.

@ramapcsx2:
As refractionpcsx2 clarified.

**Comment by refractionpcsx2** [comment]
@pgert  S could also be translated as Spanish causing confusion, im sure classically S was Spanish. As for the NTSC-UK ones, that still doesn't make any sense, if it is english, it would make more sense to be NTSC-US, it's probably in american English rather than proper English anyway, also NTSC-US has been used in the past to describe their origin.

**Comment by AdmiralCurtiss** [comment]
Typically in the video game world the five major European languages/regions are written as EFIGS for English, French, Italian, German, Spanish. I would advise against using E for España.

**Comment by gregory38** [comment]
@refractionpcsx2 I let you check the diff. If you're happy, tell me I will manage the merge.

**Comment by refractionpcsx2** [comment]
I'm still not completely happy with the naming, it's very non-standard.  But u guys if everybody else is happy, it's just me. 

I'll check the diff when I get back from the airport tonight

**Comment by refractionpcsx2** [comment]
Gah I wish mobile github would let you edit posts,  my phone made a mess of that :/

**Comment by AdmiralCurtiss** [comment]
I'll once again recommend against using E for Spain. It's guaranteed to cause confusion.

**Comment by tony971** [comment]
End user here. If I saw "E," I would definitely think it stood for Europe. If not Europe, than English. España would be my last guess. You're writing "NTSC" as an English acronym. Why would you suddenly change to the Spanish spelling of Spanish?

**Comment by tony971** [comment]
And NTSC-UK doesn't make sense. Naming conventions are used to describe the region that the game is released for. You're creating a paradox in end users' heads by saying both "NTSC" and "UK." No game would exist for both an NTSC region and the UK. The only ones that would understand it are the ones who know your naming convention. Which, as of now, is just you. I'd suggest changing "UK" to something that doesn't make users think of a different region. US, like @refractionpcsx2 said, would work. Especially since these games were made for Americans.

US - American English
UK - British English
F - French
I - Italian
G - German
S - Spanish
EU - Multilingual

**Comment by mirhl** [comment]
Afaik, as admiralcrutiss said, the recurrent acronym is [EFIGS](https://en.wiktionary.org/wiki/EFIGS) so I would go against changing this dogma. 

Then it's even true that PAL-I is probably going to be a redundant (I mean.. no way there's a NTSC-I).. still I guess that better to be repetitive than lacking

**Comment by pgert** [comment]
@ AdmiralCurtiss & tony971 & mirhl:
Do you support PAL-ES for España?
As I mentioned, my intention is to make another PR if this one is accepted,
 in which the PAL-E entries are changed into PAL-ES. 

@ tony971:
NTSC-UK has been changed into NTSC-EN.
Are you OK with this?

**Comment by tony971** [comment]
You're still changing from NTSC (short for National Television Selection Comittee, an English acronym), to Espanã, the Spanish way of spelling Spanish. The second one wouldn't bother me but it might bother @AdmiralCurtiss and/or @mirhl

**Comment by tony971** [comment]
You're still changing from NTSC (short for National Television Selection Comittee, an English acronym), to Espanã, the Spanish way of spelling Spanish. The second one wouldn't bother me but it might bother @AdmiralCurtiss and/or @mirhl

**Comment by tony971** [comment]
And seeing as I'm an end user, their opinions are worth more than mine.

**Comment by tony971** [comment]
And seeing as I'm an end user, their opinions are worth more than mine.

**Comment by willkuer** [comment]
Can maybe somebody explain what ntsc-uk means? After change is ntsc-en the same as ntsc-us?

BTW you can not label pal-s as pal-e or pal-es but keep pal-g as pal-g. German is translated as Deutsch so you would need to change pal-g to pal-d or pal-de. But why should you do this strange native language conversion?

**Comment by mirhl** [comment]
I'm an end user too tbh. 
Anyway PAL-S would be the right one, if any. 

And again, what's this [NTSC-UK](http://it.urbandictionary.com/define.php?term=ntsc-uk) magic?

**Comment by refractionpcsx2** [comment]
There shouldn't even be an NTSC-UK, it doesn't exist, we don't use NTSC in the UK, anywhere.

it should be as simple as NTSC (assumed as english) and NTSC-J for Japan

**Comment by AdmiralCurtiss** [comment]
I'm starting to think it would make more sense to split this into two entries, one for region code and one for language. This would be much clearer, and provide precise information about what languages are on the disc rather than making you guess based on the region.

Either way, the North American "NTSC" region should probably actually be "NTSC-U/C", as [that's what Sony uses on their box arts and spines](http://www.gamefaqs.com/ps2/197344-final-fantasy-x/images/box-52703).

**Comment by mirhl** [comment]
You have a point for acronym correctness. 

I don't know if language should be included though. 
I mean.. region codes make sense. It's a purely technical affair (and it's even written on the disk). 
Languages? Not so easy.

**Comment by AdmiralCurtiss** [comment]
I believe that's all of them, though I can't actually find any visual proof of NTSC-C discs ([they are mentioned here](http://www.scei.co.jp/corporate/release/pdf/031128e.pdf) so they almost certainly exist though). Australia is part of PAL and most Asian countries just use NTSC-J.

And right now we definitely do have language information in the file, just sporadically and mixed together with the region. Dropping language entirely is of course also an option, but I feel like that would make the various European releases of the same game in different languages hard to distinguish.

**Comment by mirhl** [comment]
It seems they [indeed](http://128bit.me/index.php?topic=26234.0) existed. 
Though I guess you should look in Baidu rather than Google for this kind of material. 

Anyway, you definitively have a good point for distinguishing them. Though we either find some way to to it properly (which I'd like tbh) or we drop the idea in the first place if that's not possible. 
For example, at the moment we only have the "Region" parameter. And that definitively has only to keep the country code. 
So.. we should add comments, or another section to entries, idk. 

I see there are even some PAL-M15 games around the database.. but I wouldn't know if multiple PAL-M5 edition of the same game couldn't exist. Or if there couldn't be the same *number* of languages, but different *ones*.

**Comment by AdmiralCurtiss** [comment]
I've definitely seen multiple European 3-language releases of the same game, stuff like one having English, French, German and one having English, Italian, Spanish. The number of languages may not be unique.

I don't think the current file format supports that, but we could have something like one language per line, like:

    ---------------------------------------------
    Serial   = SCES-50916
    Name     = Ratchet & Clank
    Region   = PAL
    Language = English
    Language = French
    Language = German
    Language = Italian
    Language = Spanish
    Compat   = 5
    ---------------------------------------------

**Comment by mirhl** [comment]
That sounds reasonable 
Why not Language = English, French, German then?

**Comment by AdmiralCurtiss** [comment]
Also possible, though I feel that's more likely to lead to inconsistencies. But either way, I support something along the lines of that.

**Comment by willkuer** [comment]
I thought this is all about region codes. So the information where I brought the game and if there was a special release in my country for european nations not in which language it is synchronized.

**Comment by pgert** [comment]
This PR is to messy, so I'm closing this one and making a new one with no namechanges,
 PAL-E for English, PAL-S for Spanish and no change of NTSC-E into NTSC-EN.

**Comment by mirhl** [comment]
Again, leave languages separated of region codes.

**Comment by AdmiralCurtiss** [comment]
@willkuer How many games are you aware of that have received region-specific unique releases but aren't subbed/dubbed in that region's language? Language information seems much more useful to me.

**Comment by pgert** [comment]
Region-Correctness was a bad choise of words.
It's language-support that is specified.

**Pull request closed without merging**
