### PR TITLE
SPU: Delete broken/unused alsa backend

### PR DESCRIPTION
**Pull request by Ziemas**
Removing broken/unused code.

### CODE REVIEW

**Comment by arcum42** [comment]
Missed line 813 of pcsx2/pcsx2.vcxproj...

**Comment by Ziemas** [comment]
fixed

**Comment by ViNi-Arco** [comment]
Hello Mr. Ziemas, can I still use Alsa through SDL?
sldAlsaSound

**Comment by Ziemas** [comment]
Yes, using alsa through SDL will still work fine.

**Comment by arcum42** [comment]
Given that it didn't actually work, and we're fine with the current options anyways, seems fine to me.

**Pull request merged**
