### PR TITLE
gsdx: improve detection of channel shuffle

### PR DESCRIPTION
**Pull request by gregory38**
Improve rendering on Prince Of Persia (requires preload data hack)

Worth to re-test: MTGS2/3

Urban Chaos is a bit better but there still a bad overlay

Feel free to test and report regression :)

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Just to keep the data in relevant places, here is my results from this PR (already posted in issue #1318 )

Destroy All Humans - Background fading effect thing is fixed and has the right pattern on it, good job!
Urban Chaos - Yes much much better, still has a horrible "fog" effect
MGS3 - Ingame still looks fine, Codec is now a cartoony grey colour, which I think it is supposed to be going from google images! I don't know about infrared, haven't got that far.

**Comment by Blackbird88** [comment]
Yup MGS3 is fully fixed. You're genius!
image

**Comment by FlatOutPS2** [comment]
MGS3 codec screen bottom half was the clear fox logo for me. You couldn't see Snake's lower half.

**Comment by prafullpcsx2** [comment]
Kungfu Panda now displays stuff full screen but textures are still corrupted.

kf0
kf1

**Comment by gregory38** [comment]
@prafullpcsx2 
Yes, I still have one of your dump. However I didn't remember it was that bad.

**Comment by gregory38** [comment]
@FlatOutPS2 
What about `UserHacks_ColorDepthClearOverlap = 1` ? (unlikely to help but it is free to try)

**Comment by prafullpcsx2** [comment]
I wasn't expecting this but one of these changes made Horsez (first game) totally playable. Earlier it was painfully slow (hanged my pc if I used anything over native resolution) and didn't even had colors but now the game is running 200% speed with full colors.

**Comment by gregory38** [comment]
Yes, it reduces a lots the memory overhead (factor 5x-10x) when those effects are used.

**Comment by FlatOutPS2** [comment]
> What about UserHacks_ColorDepthClearOverlap = 1 ? (unlikely to help but it is free to try)

No change.

**Comment by prafullpcsx2** [comment]
Star wars battle front 2 also fixed.
swbf2after
swbf2before

**Comment by gregory38** [comment]
@prafullpcsx2 
I give a glance at the Kungfu Panda trace. So there is indeed a channel effect that is now (well I guess)  properly emulated. But otherwise the game is massively broken.  Potentially there are issue with unaligned 8 bits format. But I'm afrait it remains a tons of complex format issue.

**Comment by gregory38** [comment]
I pushed severals changes to make the code more robust + a dedicated fix for urban chaos.

**Comment by AmbientMalice** [comment]
A regression  has popped up. (MGS3, obviously.) Bottom half of screen is missing with sepia/murky filters.

gsdx_20160430111943

gsdx_20160430112014

**Comment by Blackbird88** [comment]
Is it only that particular cutscene? I don't see either of those issues.
image

**Comment by FlatOutPS2** [comment]
> I tried fiddling with settings and I can't get that bug. Must be something with your game idk.

Might be a difference between versions. I had the same issue as AmbientMalice. I haven't tried the latest update though.

**Comment by Blackbird88** [comment]
Well that's the point of this PR lol. You don't report bugs without using the AppVeyor build
https://ci.appveyor.com/api/buildjobs/coy4a3yjcm2fggn2/artifacts/pcsx2-v1.5.0-dev-687-ge1ea04f-gsdx-8b-subrt-940-vs2015-Win32-AppVeyor.7z

**Comment by gregory38** [comment]
It seems to be a different issue. So I'm not sure it is a regression. Could be a PAL/NTSC difference.

**Comment by FlatOutPS2** [comment]
> It seems to be a different issue. So I'm not sure it is a regression. Could be a PAL/NTSC difference.

Yeah, older versions don't show the fox logo in the codec screen at all, the bug was probably there all along, it just wasn't visible yet. Might be a typical half-screen bug.

**Comment by gregory38** [comment]
Dear Testers, I need your help to test various game. Here a selection of game that have a CRC hack to potentially bypass a similar effect. I'm not sure all of them use the channel effect but it could worth to check them.

Game to test
- [ ] GSC_Manhunt2
- [ ] GSC_TalesOfAbyss (based on the comment this one could be like urban chaos, so it might need a special hack)
- [ ] Star wars battle front 1 (2 is good :) )
- [ ] GSC_BlackHawkDown (night filter)
- [ ] GSC_JamesBondEverythingOrNothing (comment say huge vram usage)
- [ ] GSC_ZettaiZetsumeiToshi2
- [ ] GSC_TouristTrophy
- [ ] GSC_DeathByDegreesTekkenNinaWilliams

**Comment by FlatOutPS2** [comment]
Tourist Trophy - Original issue: Messed up patterns on screen when brightness not set to 0. This has improved on Partial, the patterns are now only at the bottom of the screen, the in-race menu screen & HUD opacity is wrong. On Minimal or none the issue is gone!
The black and white effect in failed licenses still doesn't show up in HW mode, but the patterns are gone there too in minimal.
There seems to be a regression with the shadows. With (a few weeks)older GSDX shadows in corners are fine, with a short flash of stretched extra shadows popping up at times, in current git the extra shadows are constant (mostly) in corners.

**Comment by gregory38** [comment]
Nearly all those game have the CRC enabled in partial so you need minimal to test it. The regression is likely due to all my previous hardware change :(

**Comment by FlatOutPS2** [comment]
The shadow issue is related to brightness setting, so you can bypass the regression.

There's still some slowdown when starting a race and grey bars pop up, but the RAM usage is down by 1GB!

**Comment by FlatOutPS2** [comment]
GT4 is even better. I didn't see a pattern when starting a race, and RAM spike is gone, completely gone. In some older GSdx is crashed at 3x native, with RAM 2GB+ higher, in other it spiked 1.5GB, but now nothing. Just smooth as butter.

**Comment by prafullpcsx2** [comment]
Manhunt 2 isn't fixed. Earlier left corner was showing correct brightness screen but now it's showing blue screen. 
manhunt2after
manhunt2before

**Comment by AmbientMalice** [comment]
@Blackbird88 For the record, my copy of MGS3 is PAL, and Subsistence Edition. I have a standard edition PAL sitting around somewhere, too.

**Comment by gregory38** [comment]
@prafullpcsx2 could you give me dump of manhunt. It look like the channel effect.

**Comment by FlatOutPS2** [comment]
Star Wars Battlefront (before):
swb_old
Star Wars Battlefront (after):
swb_pr
Star Wars Battlefront (software):
swb_soft

In Star Wars Battlefront the sky and fog are now visible in HW, but the fog isn't see through, and it also removes objects like the trees from the screen that are visible in software and old version without sky or fog.

**Comment by gregory38** [comment]
You're right for GT4, it uses less memory. However I'm not sure it was intented. Maybe I wrongly skip some draw calls. 

Star Wars Battlefront. I will put in the better but not yet perfect category. Potentially it could just be an interaction with the channel effect and another one. Could you post me a dump of the bad fog effect, it could worth to debug it.

**Comment by gregory38** [comment]
By the way, it would be nice to test regression on VP2 and Fight_Night_Round.

**Comment by refractionpcsx2** [comment]
ooh yeh, i wonder if the forest looks right now

**Comment by gregory38** [comment]
I think it is another effect. But the pattern is close (reading the RT as 8 bit index texture). I want to be sure my new changes aren't triggered as the wrong time.

**Comment by FlatOutPS2** [comment]
Battlefront GS dump:
[SW Battlefront.zip](https://github.com/PCSX2/pcsx2/files/243576/SW.Battlefront.zip)

**Comment by gregory38** [comment]
Thanks for the dump. I implemented the channel effect on color but not on depth (at least not properly). I need to think how to extend the mess to support this case too. Hopefully it will fix various the remaining rendering issue.

**Comment by FlatOutPS2** [comment]
JamesBondEverythingOrNothing: If anything the VRAM usage is low, didn't get above 400MB at 3x native. Is there a particular scene with issues?

**Comment by gregory38** [comment]
From the git
```
GSdx fixes: Skygunner crashing on boot. James Bond 007: Everything or Nothing doing a huge Vram usage when opening the weapons screen and making the system crawl at it. Couldn't test much with this one and only added the US version for now.
```
Might worth to test Skygunner too.

**Comment by FlatOutPS2** [comment]
Yeah, massive VRAM usage and crash on weapon select screen. Fixed now in OpenGL, goes from 450 to 650MB. Still full VRAM usage in D3D11, but no crash.

**Comment by gregory38** [comment]
Ok. Moder gpu has more vram too. You can stop the tests. Star wars show me some huge issue in my code. I will try to fix it asap.

**Comment by gregory38** [comment]
Sorry guys, you will need to retest your games. I made a rather important fix to properly sample a depth texture.

**Comment by prafullpcsx2** [comment]
@gregory38 : Here is manhunt 2 gs dump.
[manhunt2.zip](https://github.com/PCSX2/pcsx2/files/243652/manhunt2.zip)

**Comment by prafullpcsx2** [comment]
@gregory38 : Good job, Star wars battle front 2 overbright sky is also fixed with your depth texture fix

swbf2after
swbf2before

**Comment by gregory38** [comment]
That a channel effect but instead to do N consecutive draw calls. The game alternate between a channel effect and a normal rendering. Therefore I fail to detect it properly. It explain why only the corner is done properly. For the color, I think I move the wrong channel, I saw some red in SW texture whereas I saw some blue on HW texture.

**Comment by gregory38** [comment]
I think I got it. The game does
```
foreach page {
   do blue channel effect
   do green channel effect
  do red channel effect
}
``
Whereas others game does
```
do blue channel effect for all pages
do green channel effect for all pages
do red channel effect for all pages
```
So they inverted the loop. I need to find a way to detect it properly.

**Comment by FlatOutPS2** [comment]
Battlefront 1 fog is transparent now too. It does still have a light shift to the (up&)left with some sort of duplicate/mirroring effect to it.

HW:
swb-hw

SW:
swb-sw

**Comment by gregory38** [comment]
Native?

**Comment by prafullpcsx2** [comment]
Death by degrees also seems to be fixed. 

death by degrees after
death by degrees before

**Comment by Xcedf** [comment]
Not sure if this by this branch or latest master already has it but:
Ico now renders fog nicely on OGL HW, and same sort of fog rare issue in Okami, the issue was only presented in boss dungeons levels, also fixed
Thanks for your amazing work gregory
before:

after:

before:

after:

**Comment by refractionpcsx2** [comment]
Not sure if it is related, Destruction Derby has a bit of a half screen dusty smoke effect going on, also has depth issues with the lights.

Anyway here's a GS dump to have fun with :) http://www.filedropper.com/destructionderby-depth_1

**Comment by gregory38** [comment]
@prafullpcsx2 , @Xcedf 
Thanks for the feedback.

@refractionpcsx2 
The half screen issue is another bug. Otherwise the depth effect ought to be correct. It is a color shuffle (the one that you ported to Dx).

**Comment by refractionpcsx2** [comment]
> The half screen issue is another bug. Otherwise the depth effect ought to be correct. It is a color shuffle (the one that you ported to Dx).

the lights show through the cloth, they shouldn't do. they also shine through the post processing effect.

**Comment by gregory38** [comment]
Yes but due to the half screen bug some depth/color buffer are wrong and potentially even the top part of the buffer. Beside it is a racing game, and it seems they all do crazy stuff.

Anyway, currently I'm trying to find a solution for ManHunt2. It is a tough case.

**Comment by FlatOutPS2** [comment]
> Native?

Yeah, it's a scaling bug. I forgot to put the scaling down before doing the test.

**Comment by gregory38** [comment]
```
Yeah, it's a scaling bug. I forgot to put the scaling down before doing the test.
```
Phew! By the way, potentially round sprite offset could help here.

**Comment by FlatOutPS2** [comment]
Round sprite offset didn't help, but half-pixel offset removed the duplicates, which is the worst part of it. :)

**Comment by gregory38** [comment]
@prafullpcsx2 
Do you think ManHunt2 worth a fix or current CRC is enough. So far the only solution I see is to generate a dedicated shader for the effect and skip the hundreds of draw calls (of the channel effect).

**Comment by prafullpcsx2** [comment]
@gregory38 : I don't think we really need a fix for manhunt2. From what I have played current CRC is enough. Only missing thing is correct brightness which doesn't matter at all.

**Comment by gregory38** [comment]
Yes, I think the intent of effect is non-linear gamma/brightness correction.

**Comment by prafullpcsx2** [comment]
These changes also do help Catwoman game.

Earlier it was like this in HW mode-

before new changes hw

Now it's like this -

after new changes

Even software mode got ghosting effect in this game -

software

The game is expected to look like this -

expected

Attaching a gs dump just in case @gregory38 is interested to find out what's causing ghosting in software mode.
[catwoman.zip](https://github.com/PCSX2/pcsx2/files/243778/catwoman.zip)

**Comment by gregory38** [comment]
It could be wrong (rounding) coordinate from the VU. The ghost seem like a post processing effect applied with a wrong offset. Anyway so far results are very good. I think I will merge it tomorrow. This way I can rebase the others pr, it will ease testing.

**Comment by gregory38** [comment]
Ok guys. Thanks all for the test. Code is merged and you can now enjoy it in the master. Time to update the issue tracker accordingly :)

**Comment by Dreadmoth** [comment]
Ratchet & Clank menu issue #914 has improved, now a full column on the left side of the screen is rendered correctly (instead of just a square at top-left):

ratchet3

**Comment by gregory38** [comment]
I guess the game does the rendering in column. The effect is likely correcly detected for the first column.

**Pull request merged**
