### PR TITLE
Fix broken link and point to relevant wiki page

### PR DESCRIPTION
**Pull request by connorwaters**
Was looking to see if I might be able to contribute, and, well... How's this for a first contribution?

### CODE REVIEW

**Comment by karasuhebi** [comment]
Nice catch :D

**Comment by refractionpcsx2** [comment]
Any reason you didn't make the contribution page one of those in the list considering its a list of how to contribute? :P

**Comment by connorwaters** [comment]
Hm. You're right. That was an odd choice of placement.

**Comment by refractionpcsx2** [comment]
That's better :) Will just wait to see what some of the other guys think, then we can merge :)

**Comment by gregory38** [comment]
technically https://github.com/PCSX2/pcsx2/wiki/Todo-List is my todo list. Various idea that I wanted to test on GSdx ogl. I don't mind if people harvest my field ;) but it is better to start with the contributing page (that likely need an update).

**Comment by refractionpcsx2** [comment]
@gregory38  are you happy with this then?

**Comment by gregory38** [comment]
It would be better to separate (with big header)
1/ issue reporting
2/ general documentation
3/ todo list and stuff.

**Comment by gregory38** [comment]
Still alive?

**Comment by gregory38** [comment]
Someone pick your change. So I close this PR.

**Pull request closed without merging**
