### PR TITLE
Aggressive CRC hacks for SMT games

### PR DESCRIPTION
**Pull request by AltimorTASDK**
I added aggressive CRC hacks for SMT Nocturne, DDS1 and DDS2 that disable motion blur and the "smear" effect. Currently only NTSC-U is supported (I couldn't even find any other regions for DDS).

### CODE REVIEW

**Comment by AltimorTASDK** [comment]
Not sure if reading from 0x20000000+ for game memory is reliable, or if there's a proper way to do it

**Comment by avih** [comment]
@sudonim1, what say you about reading from this address?

**Comment by sudonim1** [comment]
It's not reliable, we just try to allocate at that address, there's no guarantee.

**Comment by sudonim1** [comment]
Also this is a generally bad idea, with MTGS the GS emulation isn't synchronised with EE emulation.

**Comment by AltimorTASDK** [comment]
"state" isn't something that's going to be changing constantly, it's just used to check when the player is entering a battle, in which case the game needs to be allowed to fade into the battle.

**Comment by AltimorTASDK** [comment]
Is there any sane way to read EE memory from the GS?

**Comment by i30817** [comment]
Will fix #497 if it's merged ... and i hope it will be ;-)

**Comment by i30817** [comment]
Hoping this can be made acceptable for merging.

**Comment by i30817** [comment]
Are you going to merge this @gregory38 ?

**Comment by gregory38** [comment]
Personnaly I think the best way will be to handle depth correctly. Anyway I think it will be better to squash the commit.

**Comment by gregory38** [comment]
@AltimorTASDK 
If you want to have your work merged, please rebase and squash your commit.

**Comment by AltimorTASDK** [comment]
not interested anymore

**Comment by i30817** [comment]
See #571 for a cherry pick of these commits.

**Comment by gregory38** [comment]
I don't know what is the current situation. It seems #571 will be the replacement so I close this one.

**Pull request closed without merging**
