### PR TITLE
Cherry-Picked and squashed commits from AltimorTASDK Aggressive CRC hacks for SMT games PR

### PR DESCRIPTION
**Pull request by i30817**
Altimor closed his Nocturne PR after being asked to squash them, due to disinterest, and in a private conversation i asked him to keep it open at least until i could cherry-pick the commits and submit the pull request myself. He agreed and here it is. I hope this is acceptable for merging.

### CODE REVIEW

**Comment by i30817** [comment]
Durr, i think i skipped a commit on the cherry pick. Will try again.

**Comment by i30817** [comment]
Ok no i didn't. He just removed the hack he had to fix "going through doors and getting into battles".

**Comment by bositman** [comment]
Could you post a screenshot with the hack and without it?

**Comment by gregory38** [comment]
And a gs dump for a better fix on the future

**Comment by gregory38** [comment]
And a comment explaining what is trying to fix. Sorry to be so picky but we have accumulated tons of hacks and nobody knows the purpose of any of them...

**Comment by i30817** [comment]
Someone else is going to have to add the GS dump  -_-; 
I can't actually build pcsx2 at the moment, lxc doesn't work with my current systemd and the build dependencies won't install in my bare linux 64 bits system.
But it looks like this:
http://gfycat.com/CostlyThunderousHorse

**Comment by bositman** [comment]
We don't know what the normal motion blur looks like, thus my initial comment: "Could you post a screenshot with the hack and without it?"

**Comment by i30817** [comment]
Look at any LP. For example, look at the legs of the MC during movement in this video
https://www.youtube.com/watch?feature=player_detailpage&v=gkZTYZ-OTp8#t=621

**Comment by gregory38** [comment]
Personnally I'm fine because it is an aggressive crc.

**Comment by gregory38** [comment]
@bositman is it ok with you ?

**Comment by bositman** [comment]
I couldn't see any difference in Digital Devil Saga 2 that I tried it but I'll take your word for it...
@i30817 before this gets merged, some small stuff, add a comment in the GSstate file about what the hack does and that you are using the same hack for all 3 games. Thanks

**Comment by i30817** [comment]
Did  do this right? Git keeps confusing me -_-;

**Comment by gregory38** [comment]
No. But I take care of it :)

**Pull request closed without merging**
