### PR TITLE
Replace volatile with real atomic

### PR DESCRIPTION
**Pull request by gregory38**
So far only GSdx was ported in order to test/play with std::atomic.

I used the default (strongest) atomic constraint, maybe a couple of them can be relaxed (but it could be very dangerous)

I only did a sanity check on linux. It need to be carefully tested and benchmarked too.

It requires at least VS2012 on windows.

### CODE REVIEW

**Comment by jobermayr** [comment]
Seems to has been successful on openSUSE/Packman Linux for ~ 2 weeks (no bug reports).

**Comment by ramapcsx2** [comment]
Hey, I got this error when trying to compile on VS2013 / Windows:

GSUtil.cpp (31): error C2280: 'std::atomic_flag::atomic_flag(const std::atomic_flag &)' : attempting to reference a deleted function

Apparently you can delete functions in c++11 now?

**Comment by gregory38** [comment]
Are you sure of the file and line?

**Comment by ramapcsx2** [comment]
It's copypasted from the error log. I can try again and get the actual code..

**Comment by ramapcsx2** [comment]
Okay, very weird but somehow the file name was wrong. This is correct now:

GSTextureSW.cpp(31): error C2280: 'std::atomic_flag::atomic_flag(const std::atomic_flag &)' : attempting to reference a deleted function
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\atomic(191) : see declaration of 'std::atomic_flag::atomic_flag'

Here's a screenshot as well: http://i.imgur.com/aZ36Kdq.png

**Comment by gregory38** [comment]
Better :+1:  Unfortunately I think there is a high probability that VS2013 doesn't support a part of the C++11 standard (initializer list). Or gcc is wrong, I need to check clang. Do you have latest "service pack" for the VS2013 (if there is any)?

**Comment by gregory38** [comment]
it works fine for Clang. I guess I will make the change only for linux... It sucks

**Comment by Bigpet** [comment]
@gregory38 well visual studio is not wrong, what you're doing is "unspecified" as explained [here] (http://en.cppreference.com/w/cpp/atomic/ATOMIC_FLAG_INIT)

> It is unspecified if it can be used with other initialization contexts.

**Comment by gregory38** [comment]
I found other people telling other thing. In any case, how to init the variable then?

**Comment by Bigpet** [comment]
You can look at the standard yourself, in the [november 2014 draft](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf) it's in 29.7.4

You can do

    STextureSW::GSTextureSW(int type, int width, int height)
    #ifdef _STD_ATOMIC_
    {
	std::atomic_flag_clear(&m_mapped);
    #else
    : m_mapped(0)
    {
    #endif

**Comment by gregory38** [comment]
Thanks for the link.
Actually I did that initially but I was afraid that the clear doesn't fully initialize the object. In practice the object is only a counter so I guess it will be fine. I don't see the point of this macro, if the clear is equivalent.

**Comment by Bigpet** [comment]
The point is initialization of static variables and the point is compatibility with C11 which naturally doesn't have this issue since C doesn't have constructors.

**Comment by gregory38** [comment]
Thanks for the explanation.

**Comment by gregory38** [comment]
Ok I pushed the fix. It is just a branch to test. I will rebase it properly next time.

**Comment by gregory38** [comment]
VS2010 was dropped so I will redo the code without the ifdef. It would be more readable.

**Pull request merged**
