### PR TITLE
gsdx ogl: replace eight 8MB PBO with a single fat 64MB PBO

### PR DESCRIPTION
**Pull request by gregory38**
Tests are welcome

### CODE REVIEW

**Comment by FlatOutPS2** [comment]
Do you like regressions? If so, good news! I get `GL_PIXEL_UNPACK_BUFFER: Sync Sync! Buffer too small` spammed in the log everywhere.

**Comment by gregory38** [comment]
Just the spamming ? Or is the rendering broken too. I guess we could just comment the message. Maybe it could be a good news to increases the size of the buffer further.

**Comment by FlatOutPS2** [comment]
Rendering looks fine. The spamming is massive though, it doesn't just affect gameplay, but continues in FMV's and menu's. The PR doesn't affect speed.

**Comment by gregory38** [comment]
What is the size of your GPU memory ? Actually I'm not even sure pbo uses GPU memory.
Could you try to increase the buffer size to 128MB instead of 64MB.
```
const  uint32 m_pbo_size = 64*1024*1024;
const  uint32 m_seg_size = 16*1024*1024;
```

**Comment by FlatOutPS2** [comment]
Doesn't make a difference.

**Comment by gregory38** [comment]
I posted a new version that print the returned status. Could you tell me what you have on your driver?

**Comment by FlatOutPS2** [comment]
It prints `911C`.

**Comment by gregory38** [comment]
Ok what is your GPU ? Do you have a slow GPU ?

**Comment by FlatOutPS2** [comment]
As it's been merged, did you fix the spamming issue?

**Comment by gregory38** [comment]
Yes. Well message might appears in debug build if you enable openGL trace.

**Pull request merged**
