### PR TITLE
GSdx-TC: Don't skip depth lookup on Jackie Chan Adv and SVC Chaos

### LINKED ISSUE #1838: [GSDX-TC] Regression in Jackie Chan Adventures
Jackie Chan Adventures doesn't seem to like the skip of drawcall (https://github.com/PCSX2/pcsx2/commit/87fc4c1e44cfa7215cf1b327e0c0f93cadfb5bda) in #1760 , reverting that and adding back ``return LookupSource(TEX0, TEXA, r);`` seems to fix the half screen flickering issue in Jackie Chan Adventures. FYI, this game also enters the half right path which is there for the Snowblind games.

Before #1760:

before

After #1760:

after

_**GSDump**_: [_**here**_](https://www.dropbox.com/s/8k47jq8h9qvbykp/JackieRegression.7z?dl=0)

### LINKED ISSUE #1862: SVC Chaos - Main menu invisible in Hardware mode
***PCSX2 version:***
v1.5.0 dev-1927

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
The main menu is completely black in Hardware mode. This is a regression following this commit:
https://github.com/PCSX2/pcsx2/commit/de38963904140259ca1b398234e04931f545bbf8
Specifically this line: `tex = tex_psm.depth ? m_tc->LookupDepthSource(context->TEX0, env.TEXA, r) : m_tc->LookupSource(context->TEX0, env.TEXA, r);`

***How to reproduce the issue:***
Set Renderer to any of the Hardware renderers, boot the game and advance to the main menu.

***Last known version to work:***
v1.5.0-dev-640

### PR DESCRIPTION
**Pull request by lightningterror**
This is a follow up to #1868

Issues:
SVC Chaos #1862
Jackie Chan #1838

Don't skip the draw calls on Jackie Chan Adv and SVC Chaos,
avoids regressions and we can use the old code for now.

Gregory: The correct fix would be to trace all textures writes to
be sure of the source. But it is a much bigger work.

Close #1862 
Close #1838

### CODE REVIEW

**Comment by gregory38** [comment]
Did you test the games ?

**Comment by lightningterror** [comment]
Yes and it behaves like  FlatOut said.

> SVC Chaos: It fixes the black screen on OpenGL HW, the regression is still there with the Direct3D HW renderers.
> Jackie Chan: Half-screen flickering is gone, half-black screen issue is still there.

**Comment by lightningterror** [comment]
I updated the PR and fixed the regression on D3D for SVC Chaos as well.

**Comment by lightningterror** [comment]
@refractionpcsx2 maybe you can merge this too while you're at it.

**Comment by refractionpcsx2** [comment]
Sure can do. Do you want it squashed and merged or rebase and merged?

**Comment by lightningterror** [comment]
Rebase merge.

**Comment by refractionpcsx2** [comment]
Done

**Comment by lightningterror** [comment]
Thanks. 2 more regressions down.

**Pull request merged**
