### PR TITLE
Introduce ENABLE_PNGPP option to control png++ usage  in GSdx.

### PR DESCRIPTION
**Pull request by nE0sIghT**
That change allows to disable png++ usage (in packaging mode) even if it is installed.

### CODE REVIEW

**Comment by gregory38** [comment]
Purpose?

**Comment by nE0sIghT** [comment]
In Gentoo I [can not make that dependency optional](https://github.com/gentoo/gentoo/pull/1#discussion_r36900222) if it can not be switched off completely.

It's not a big deal really, there is now two choices for Gentoo:
1. Unconditionally depend on png++
2. Make it optional, if that patch will be included in main pcsx2 repository

**Comment by gregory38** [comment]
png is already a dependency due to wxwidget. PNG++ is only a couple of hpp file, no .so file. Initially it was mandatory but sadly png++ isn't included in all distributions. What is the issue to have PNG++ as a dependency?

**Comment by nE0sIghT** [comment]
It's 42 files in Gentoo :-)
```
equery f pngpp | wc -l
42
```

I always try to minimize dependencies - it's source based distr and compilation time matters.
But as I said - it's not a big deal, I can force that dependency.

**Comment by gregory38** [comment]
Seriously
```
du -sh /usr/include/png++ 
200K	/usr/include/png++
```
Compilation impact, an extra file to compile...

**Comment by ramapcsx2** [comment]
I think both sides are equally valid. This is one of those times where it's best to move on ;)

**Pull request closed without merging**
