### PR TITLE
Qt: Change name of Adjust to Host Refresh Rate

### PR DESCRIPTION
**Pull request by JordanTheToaster**
### Description of Changes
Changes the name of Adjust To Host Refresh Rate to Scale to Host Refresh Rate.

### Rationale behind Changes
The name was inconsistent with the internal name and the description box text.

### Suggested Testing Steps
Make sure CI is happy.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Wouldn't something like "Scale" be a better word? "sync" sounds like vsync, which is a different option.

**Comment by JordanTheToaster** [comment]
> Wouldn't something like "Scale" be a better word? "sync" sounds like vsync, which is a different option.

The internal name uses sync but I can adjust the text and description to use scale if it makes it more clear.

**Comment by refractionpcsx2** [comment]
Yeah, I don't care so much about the internal names as only people who know what's going on need to know what it means, but on the UI, I'd like it top be clear and distinct for users, most of which expect us to tell them exactly what stuff does :P

**Comment by JordanTheToaster** [comment]
> Yeah, I don't care so much about the internal names as only people who know what's going on need to know what it means, but on the UI, I'd like it top be clear and distinct for users, most of which expect us to tell them exactly what stuff does :P

Ask and you shall receive.

**Review by Mrlinkwii — APPROVED** [review]

**Pull request merged**
