### PR TITLE
USB: Sony DPP-MP1 printer emulation

### PR DESCRIPTION
**Pull request by Florin9doi**
### Description of Changes
* Sony DPP-MP1 Digital Photo Printer emulation
* GamePrint① compatible
image

### Suggested Testing Steps
* Compatibility: https://gist.github.com/Florin9doi/57d496d3790d30704b596eb9c9c50205

Result: 
print_2021_12_13_01_01_00

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Can we not use .bmp instead of .ppm? just so people don't need specialised software just to open an image.

**Comment by refractionpcsx2** [comment]
also "snaps" might be a better folder to store prints in than logs.

**Comment by Florin9doi** [comment]
Changed to BMP format

**Comment by Mrlinkwii** [comment]
works well  here :slightly_smiling_face:

**Pull request merged**
