### PR TITLE
Qt: Fix window reopening after close

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Stops the window reopening after it's been closedl

### Rationale behind Changes

Regression from #6536.

### Suggested Testing Steps

Test closing window with game running.

### CODE REVIEW

**Comment by InterClaw** [comment]
@stenzek This PR introduces the inability to "Save State For Resume" when quitting PCSX2 from fullscreen (Alt-F4). The option is grayed out.

image

I have to restore from fullscreen and then quit to have the option to save the state.

Shall I log a separate bug for this? Or is this intended behavior?

**Comment by stenzek** [comment]
Not intended; this is fixed on my fork/branch, but unfortunately some members of the "team" have made it clear they do not want any further contributions from me (by removing my access amongst other things), therefore I'm unable to commit the fix.

So, can go ahead and open an issue, I guess.

**Comment by F0bes** [comment]
I'm postponing all of my work revolving PCSX2 directly until this gets resolved. Your comments are completely disrespectful to us and matter of fact, you wouldn't feel so isolated if you actually addressed issues properly.
You never had master access, you were never able to commit to our main branch, you can still contribute normally (not that I'm telling you to or saying you have an obligation). Publicly trying to pretend that you don't have rights to contribute at all is silly.

Not to mention that you were given contributor v1 (same rights as me) rights back once you actually calmed down and talked yesterday. But apparently that has been thrown the window.

**Comment by stenzek** [comment]
I feel like these sort of conversations would be better held in private, but if you want to have it here, I'm fine with that.

> Your comments are completely disrespectful to us and matter of fact, you wouldn't feel so isolated if you actually addressed issues properly.

I attempted to. Nobody responded (since the 10th) or had any interest in resolving the underlying communication issues, except to say that in this scenario, they wouldn't mind if I mentioned my fork, "especially if it's relevant to a conversation" (which it is here). Apparently, no matter what I do, it's wrong.

> Not to mention that you were given contributor v1 (same rights as me) rights back once you actually calmed down and talked yesterday.

I guess this was lost in communication somewhere, like everything else (possibly my fault, I don't check emails for this account). In which case, I retract that part of my comment. In which case, I'll rephrase: I don't feel comfortable contributing until these issues are resolved.

**Comment by refractionpcsx2** [comment]
> Not intended; this is fixed on my fork/branch, but unfortunately some members of the "team" have made it clear they do not want any further contributions from me (by removing my access amongst other things), therefore I'm unable to commit the fix.
> 
> So, can go ahead and open an issue, I guess.

Nobody has said they don't want further contributions, if you hadn't decided to remove everything you were doing, I wouldn't have got worried and removed access, which I would like to make clear, you HAVE back, it was removed for less than a few hours, so please don't dramatize it that you no longer have access and we're being super mean, that is extremely out of order.

> I attempted to. Nobody responded (since the 10th) or had any interest in resolving the underlying communication issues, except to say that in this scenario

I spoke to you about it for AGES about this, went in circles with you about it several times (despite the fact nobody blamed just you and I have spoken with all parties), then you started just making jabs, and I didn't have it in me any more to respond after you started doing that, I've had an extremely difficult week with you and other people causing me stress and I didn't need any more.

**Comment by refractionpcsx2** [comment]
Nobody doesn't want you around, you're a fantastic contributor, but you get angry easily. You say about other people being negative, but you're constantly negative about users (maybe justifiably sometimes) and us (constantly saying we don't want you around and we're using you etc), and when you start snapping at people in public, it looks really shit on the project, it doesn't make the place a friendly or professional place to be around. If we could have that, there wouldn't be a problem, but from the moment you showed up over a year ago, you've been angry at everything, and that's why everybody is so stand-offish with you.

I'm sorry if you are upset about what happened the other day, in retrospect it wasn't handled perfectly, but at the same time I feel you've blown it out of proportion and made it that it's a personal attack on you, when it very much wasn't.

I would like you to take a break and try to chill out a bit and relax, cos getting angry at every little thing (like someone who's been around for ages memeing about PCSX2, which is what set you off) is not good for anybody, and I don't have the energy right now to try and constantly diffuse the situation, it's starting to take a toll on me mentally, and I'm not here to sort out drama and other peoples problems, I want to have fun and make cool things.

**Comment by stenzek** [comment]
> but you're constantly negative about users (maybe justifiably sometimes)

Indeed. Hence why I've removed most of the ways of interacting with users :) Ignorance is bliss, right?

> you've been angry at everything, and that's why everybody is so stand-offish with you.

I think that's a bit of an exaggeration; there's a few trigger points yes, but nothing ever changes, so no point bringing it up. At least this realization is something good which come out of this whole ordeal.

> but at the same time I feel you've blown it out of proportion and made it that it's a personal attack on you, when it very much wasn't.
> cos getting angry at every little thing (like someone who's been around for ages memeing about PCSX2, which is what set you off) 

You're right, I didn't realize the person was memeing, and after being sleep deprived all week, responded in a very Australian way. I later clarified it with them, and there was no issue there. As for the other person, well, I don't really want to drag that dirty laundry into the public space, and it's a known fact that they're banned from multiple communities :)

**Comment by refractionpcsx2** [comment]
Maybe they are, but from what I understand, nothing bad. But yeah there's no need to air more dirty laundry, let's move along.

I hope we can continue to work together.

**Comment by 5d-0** [comment]
I guess i'm not really belong here but still wanna say some things about all of this. I don't know what really happened between you guys but i really hope it gets resolved in a respective manner. You all guys are amazing making this project alive to this day and constatly improving it over the years making a lot of people happy :)! To Stenzerk i wanna say that i absolutely adore what he did over the last months, giving a project a second breath with new gui, adding new renderes, fixing bugs etc, there are so many things been done i can't even count them all. It would be a real shame if Sten will leave the project. Again, hope it will be resolved in a respective manner to all members of the team. 
st_small_845x845-pad_1000x1000_f8f8f8-removebg-preview

**Pull request merged**
