### PR TITLE
gsdx-ogl: Fix scanline, diagonal, triangular TV shaders

### PR DESCRIPTION
**Pull request by turtleli**
The scanline, diagonal and triangular (F7) shaders are broken in OpenGL. This fixes it.

I'm doing a PR for this since I'm not familiar with GLSL.

### CODE REVIEW

**Comment by gregory38** [comment]
Oh! It is more logical  this way. I never understood what the behavior was so strange with the filtering...
I will test the compilation on Mesa but it seems goods.

**Comment by turtleli** [comment]
Yeah, I was wondering why people used the shaders and why the enums didn't match. And then I tried DX11 and realised it was broken. ;)

**Comment by gregory38** [comment]
I nearly forgot to push. Good jobs, I'm quite happy that you joined the team ^^
Which enums didn't match?

**Comment by turtleli** [comment]
Oh, the enums match, but since I usually use the OpenGL renderer I was wondering why ShaderConvert_SCANLINE did nothing, and ShaderConvert_DIAGONAL_FILTER and ShaderConvert_TRIANGULAR_FILTER were just red for me. Now I know!

**Comment by gregory38** [comment]
Oh me too, I found the naming strange :p

**Pull request merged**
