### PR TITLE
GS/HW: Move upscale multiplier to uniform

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Smaller version of #8209.

And a bunch of other TC changes:

- Fix first black frame when loading state or changing resolution.
- Fix disable shader cache option for Vulkan.
- Change texture scale to a scalar, we haven't had independent width/height scaling for some time.
- Separate size and scale in `LookupTarget()`, no more `real_w/real_h`.
- Align height to page size, instead of the height doubling bs for Spiderman 2. Fixes larger framebuffers being used for most games which render with 224 lines. (cleans up GT4, DMC, and others a bit).
- Don't screw with TEX0 on lookup if we're doing a shuffle.
- Scale factor is now applied per-draw rather than global config. Rejoice as you can scrollwheel through the upscaling dropdown without lagging.

### Rationale behind Changes

Making the TC less yuck.

### Suggested Testing Steps

I've fixed all the runner regressions I saw, so just test with a few of your usual games to make sure nothing's broken, particularly with upscaling.

### CODE REVIEW

**Comment by DonelBueno** [comment]
Is this ready for testing? The only regression I've noticed is that custom texture loading is broken.

Default textures:
PCSX2_2023_03_06_16_55_20_640

Custom Textures on Master:
PCSX2_2023_03_06_16_55_47_179

Custom Textures on this PR:
PCSX2_2023_03_06_16_55_13_944

**Review by JordanTheToaster — APPROVED** [review]

**Review by Mrlinkwii — APPROVED** [review]

**Comment by stenzek** [comment]
Replacement textures should be fine again.

That was a can of worms.. but at least the target-specific stuff is out of `GSTexture` now.

HPO Texture is actually semi broken in master - the offset didn't get reset when a texture was recycled... so if any games relied on it persisting through target invalidation, that won't work anymore. But it's better than it applying to targets which shouldn't have the offset applied.

**Review by JordanTheToaster — APPROVED** [review]
for real this time

**Review by Mrlinkwii — APPROVED** [review]

**Comment by Dreadmoth** [comment]
I think I might have found an issue:

Boot Ratchet & Clank (or load [a GS dump](https://github.com/PCSX2/pcsx2/files/10920544/Ratchet.Clank_SCES-50916_PR-8336.gs.zip)) with the following combinations of Internal Resolution settings (all other settings default):

---

Global Setting: 8x Native (or any upscaled resolution)
Game Setting: use Global Setting (or any specified resolution)

Result (normal):

Ratchet   Clank_SCES-50916_20230308220812

Resolution can be changed with the game running via either setting without causing issues.
Toggling to and from software mode or switching to another hardware renderer behaves normally.

---

Global Setting: Native (PS2)
Game Setting: 8x Native (or any upscaled resolution)

Result (holes in textures / meshes, most noticeable on Ratchet but affects objects throughout the scene):

Ratchet   Clank_SCES-50916_20230308214521

Normal appearance can be restored by changing to native resolution, but holes will reappear if resolution is increased again via either global or per-game settings.
Toggling to and from software mode or switching to another hardware renderer restores normal appearance, **and prevents the issue occurring again in the same PCSX2 session**.

---

Global Setting: Native (PS2)
Game Setting: use Global Setting (or specified Native (PS2))

Result (normal*):

Ratchet   Clank_SCES-50916_20230308224417

Toggling to and from software mode or switching to another hardware renderer behaves normally.

*If resolution is changed with the game running via either global or per-game settings, holes appear in textures / meshes. Normal appearance can be restored by changing to native resolution, but holes will reappear if resolution is increased again via either global or per-game settings. Toggling to and from software mode or switching to another hardware renderer restores normal appearance, **and prevents the issue occurring again in the same PCSX2 session**.

---

OS: Windows 10 22H2 (64-bit)
CPU: Intel Core i7-4770
GPU: NVIDIA GeForce GTX 1070 Ti (driver 531.18)

**Comment by JordanTheToaster** [comment]
> I think I might have found an issue:

Can't reproduce here with the dump.

**Comment by Dreadmoth** [comment]
Could be driver shenanigans? This behaviour does not occur on master.

⚠️Below videos contain some flickering. 

Extract build, load dump, change internal resolution from native/native (global/game) to native/8x -> holes appear:

https://user-images.githubusercontent.com/8492684/223752246-603a3e5b-abfd-4ede-b2b3-84f546609904.mp4

---
Toggling software and same vs. different session behaviour (reloading a dump seems to have the same effect as toggling software in-game)

https://user-images.githubusercontent.com/8492684/223764798-1ebd668f-4e64-4c61-a5ab-6f016e4a7530.mp4

---
Load dump, change change internal resolution from native/8x to 8x/8x, exit PCSX2, load dump -> no holes:

https://user-images.githubusercontent.com/8492684/223764917-a5337787-1d8d-4d20-85c1-2abaec7f723e.mp4

---

I reproduced it on a family member's PC, but their setup is pretty similar to mine:

OS: Windows 10 22H2 (64-bit)
CPU: AMD Ryzen 5 5600G 
GPU: NVIDIA GeForce GTX 1060 (driver 527.56)

Sorry if I'm overdoing it with the images and videos.

**Comment by RedDevilus** [comment]
Made regression for 50 cent:

[50CentGsdump.zip](https://github.com/PCSX2/pcsx2/files/11105623/50CentGsdump.zip)

50 Cent - Bulletproof_SLUS-21315_20230329231035

**Comment by refractionpcsx2** [comment]
Already fixed with #8505

**Pull request merged**
