### PR TITLE
Remove old project files, clean up 3rdparty

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by avih** [comment]
Why do you want to remove all these files? At the very least you should explain why they're not used anymore under any circumstances.

Also, about 3rd party files, I think it makes more sense to keep the original distribution unmodified (i.e. don't delete every file we don't use in them).

Such huge modifications to the repository should have at the very least a very very detailed commit message.

**Comment by uyjulian** [comment]
remove old project files -> they aren't used anymore
for example, there are some auto**** stuff in the plugins
there are some makefile in the plugins that have been replaced by cmakelists.txt
vs10 and vs11 files are broken
there are very old IDE workspace files in the plugins which I doubt are up to date
build.sh/build.bat/build.cmd in the plugins use those old project files
clean up third party folder -> Windows only
the Third Party folder is only used for Windows stuff, it's always been like that, so why keep stuff for other OSes in there?

**Comment by gregory38** [comment]
> vs10 and vs11 files are broken
If no one complains, I guess it could be removed. But some people want to keep VS2012 files (check http://forums.pcsx2.net/Thread-plan-to-stop-supporting-MSVC-2010-2012 )

> clean up third party folder
I agree with Avih, it makes more sense to keep all files, except if it is take too much disk space. However it is too late now, you will still download them as part of the history.

**Comment by avih** [comment]
vs10 files were fine last i checked (not more than few weeks ago). Though vs10 might not be enough now with the c++11 changes.

**Comment by gregory38** [comment]
Hum, in this case it is likely a minor issue for VS2010. C++11 isn't enabled for VS2010 so it must still work. Only Linux requires the c++11 change. That being said, I won't be against the removal of VS2010.

**Comment by avih** [comment]
I'd have preferred to keep vs2010 files as long as they work.

That being said, there's no one to maintain them, a move to c++11 would prevent usage of vs2010 anyway, and vs2013 (express) should be freely available.

I'd say let's keep them until they're no longer useful.

**Comment by uyjulian** [comment]
More individual files == SLOW transfers (even through you have a fast HDD)
Git compresses the history, so it's not a big deal.
If it reduces the filecount, that's good enough for me.

Also, the 3rd party files have already been modified.

**Comment by gregory38** [comment]
transfers from what to what?

**Comment by uyjulian** [comment]
transfers between VMs (via rsync or zip through sftp)

**Comment by gregory38** [comment]
Do you really need to transfer the 3rparty at all?

**Comment by uyjulian** [comment]
Yep, because I'm transferring the source code to build on Windows/Linux VMs.

**Comment by ramapcsx2** [comment]
How about cleanup in smaller chunks? Removing old and broken makefiles or actually useless 3rd party files sounds good to me.
It starts to become a management problem if it's all crammed into one single commit. Very easy to miss something that still is important, despite it not being referenced or apparently superseded.

**Comment by uyjulian** [comment]
Hm... I'll send in a new pull request that is less bloated later.

**Pull request closed without merging**
