### PR TITLE
3rdparty: Bump libchdr to support raw DVD ISO as CHD

### PR DESCRIPTION
**Pull request by rtissera**
### Description of Changes
This PR bumps libchdr to HEAD which provides full support for Huffman, LZMA and FLAC codecs for raw data (not CD specific codecs). 

### Rationale behind Changes
This allows PCSX2 to support loading PS2 DVD ISOs compressed with chdman _createraw_ command instead of _createcd_ command. 
See https://github.com/rtissera/libchdr/pull/74 for discussion, it can bring some improvements on compression and memory efficiency, quoting @2weak2live

### Suggested Testing Steps
1. Convert some DVD ISO to raw CHD using for instance this command line : chdman createraw -us 2048 -hs 16384 --force --input game.iso --output game.chd
2. Scan your games, verify game is properly recognized by PCSX2
3. Start compressed game, verify it can be played through same as uncompressed ISO

Of course, it's important that games are compressed this way with unit size of 2048 bytes. Hunk size can be different value, but 16384 seems to give good results.

I have tested this PR successfuly on Windows/x64 built with MSVC on both Debug/x64 and Release/x64-avx2 settings.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Can you also correct the commit name? Thanks :)

**Comment by RedDevilus** [comment]
HEAD (for tracking if bumped later again)

https://github.com/rtissera/libchdr/commit/fec8ab94212cc65d9d9a62cb3da924f5830c04b0

Feb 20, 192 commits

**Comment by rtissera** [comment]
Commit name fixed, I missed that, sorry !

**Comment by refractionpcsx2** [comment]
Thanks :)

**Comment by RedDevilus** [comment]
You have a redundant space , should be
 3rdparty:

**Review by Mrlinkwii — APPROVED** [review]

**Comment by 2weak2live** [comment]
Wow, that took a while to percolate up.  Enjoy!

**Comment by rtissera** [comment]
Probably going to propose a PR with similar changes for PPSSPP since it's basically the same situation : UMD based games are 99.9% single track MODE1/2048 ISO files.

**Pull request merged**
