### PR TITLE
LilyPad XInputness

### PR DESCRIPTION
**Pull request by KrossX**
Adds support for Scarlet Crush's XInput extensions. When the wrapper is used, allows real pressure with those controllers.

Also, allows using the GUIDE buttons while at it. Note that under Windows 10, the Xbox application would hijack the GUIDE button to itself.

I did test a common X360 controller and it still works, with the GUIDE button and all. Requires testing with SCP drivers/controller. 

Since all buttons are now pressure buttons, previous button configurations would be gone. This affects issue #1038.

### CODE REVIEW

**Comment by KrossX** [comment]
Here's a build for testing purposes: [LilyPad.zip](https://drive.google.com/open?id=0B1wssOeJs5_7ZzVwVjNGdVo5RUE)

**Comment by deadair3210** [comment]
I have ScarletCrush's drivers installed for my PS3 controller over bluetooth. If you need someone to test things, just tell me what to test and I would be glad to help

**Comment by KrossX** [comment]
Yay! Testing is certainly needed.

Just use the modified plugin (build posted earlier), clear the config and make a new one. Test that all works as usual, and try the GUIDE or PS button. 

Once that's done, use this [ELF](http://forums.pcsx2.net/attachment.php?aid=43040) and test all inputs and pressure. Make sure to have SCP's xinput wrapper on the PCSX2 directory.

**Comment by deadair3210** [comment]
Do i need to map the controller in any certain way, the API's that appear are DirectInput, XInput, and DualShock 3 Native Mode but for some reason that one is greyed out

**Comment by KrossX** [comment]
Nope, just the clear and map the thing as normal. Just make sure to map the PS/GUIDE button to something.

For SCP, you would be using XInput alongside SCP's wrapper in place.

**Comment by deadair3210** [comment]
I think I got it working. There are two problems. One, I am on 10 so I cant map the PS button to anything as it is detected as a Guide button and automatically brings up the Xbox quick bar. the other problem is the pressure numbers immediatluy jump to 255 instead of verying like the triggers
Video where i test all the buttons - https://youtu.be/0wLMb74ARXY

**Comment by deadair3210** [comment]
capture2
capture1
Lillypad Settings just in case i set something up wrong

**Comment by willkuer** [comment]
Thats probably because your controller doesnt support pressure sensitivity. Only DS/Playststion controller and possibly xbone controller support face button sensitivity.

Your shoulder buttons/triggers should work though.

**Comment by KrossX** [comment]
@deadair3210 You said to be using SCP drivers with a DS3 controller, so you're probably missing SCP's xinput wrapper. Be sure to place the wrapper in PCSX2's directory, it's the *XInput1_3.dll* file from the SCP driver.

**Comment by deadair3210** [comment]
My controller is a DualShock 3 from my PS3, so it should support pressure unless im mistaken in believing that the DS3 supports pressure

**Comment by deadair3210** [comment]
capture4
PCSX2 dir

**Comment by KrossX** [comment]
Alright! So you do have the wrapper in place. Let me see what might be messing it up...

**Comment by deadair3210** [comment]
Just tell me what to do to help

**Comment by KrossX** [comment]
Try using this build [LilyPad_02.zip](https://drive.google.com/open?id=0B1wssOeJs5_7eEVMemxfS0pzRjQ)

Using that build, just go to the plugin settings. A messagebox should show up before the settings window appears. This tests wrapper access.

If the messagebox does appear, try test pressure again with the ELF.

**Comment by deadair3210** [comment]
capture5

**Comment by deadair3210** [comment]
Same result with the elf, unfortunatly

**Comment by KrossX** [comment]
Well, something went right at least.

**Comment by deadair3210** [comment]
Wooot!

**Comment by KrossX** [comment]
This one is more annoying than anything: [LilyPad_03.zip](https://drive.google.com/open?id=0B1wssOeJs5_7blJYZVVuWkM0Z3M)

Replace the plugin and wrapper file from those in zip, then just test the ELF. If pressure should be working, you will see some messagebox appear.

**Comment by deadair3210** [comment]
1 replaced files
2 ran emulator and ran elf
3 pressed buttons, no dialog

**Comment by KrossX** [comment]
Well, that means the controller fails when checking the extension for some reason. SCP comes with its own LilyPad that supports pressure and all, can you test the ELF with it? You might need to remap the controls again though.

And for reference, the DS3 does indeed support pressure. I bought one just to test cases like these, but SCP kinda triggers some other driver on install and all ends in a nice BSoD... yay!

**Comment by deadair3210** [comment]
Same result with the Lillypad-SCP plugin supplied. Do the SCP drivers even support pressure?

**Comment by KrossX** [comment]
Yes of course, I implemented SCP support for Pokopom long ago and worked fine. Are you using the original ones though? Cuz the newer ones I think dropped support for the XInput thingy.

**Comment by deadair3210** [comment]
using version 1.2.2.175 of SCPDriver if that helps at all, not sure what new ones you would be talking about unless you are talking about this https://github.com/nefarius/ScpServer

**Comment by deadair3210** [comment]
i used these http://emulation-general.wikia.com/wiki/SCP_Driver_Package , as i could never get the git project to run right

**Comment by KrossX** [comment]
Yeah, those should work. o.O

You could try reinstalling. Unplug all controllers and uninstall SCP. Then download [1.2.0.160](http://forums.pcsx2.net/attachment.php?aid=49455) and copy the [1.2.2.175](http://forums.pcsx2.net/attachment.php?aid=49784) update on top, then install again. [SCP Thread](http://forums.pcsx2.net/Thread-XInput-Wrapper-for-DS3-and-Play-com-USB-Dual-DS2-Controller)

Though perhaps there's a setting in place messing things up? Check the **Configuration** on the **ScpMonitor**, see that **Disable Native Feed** is unchecked.

**Comment by deadair3210** [comment]
Shouldnt have to do a clean install as i just had to reinstall windows a few days ago. Also, what config page are you talking about, never could find it or even a mention of it

**Comment by KrossX** [comment]
ScpMonitor is included with the driver, run it and it creates system tray icon. Right click that icon, and you'll see the Configuration option.

Reinstall suggestion was only to make sure the driver files are from the official thread. Since the wrapper extension is being loaded fine, but the pressure support fails for your device. =S

**Comment by deadair3210** [comment]
Ok, will redownload to make sure my local package hasnt a problem. Never noticed the config page as i usually use the SCPServer program so i can keep an eye on the diag output

**Comment by deadair3210** [comment]
capture6
Just reinstalled the drivers, this is the config page of which you speak?

**Comment by deadair3210** [comment]
Sucesses! Just got pressure to work, seems it only works if you use DualShock 3 Native mode in lillypad-SCP. Is there an updated version of your lillypad that you want me to test now or do i just test the latest version that you sent me

**Comment by deadair3210** [comment]
capture7

**Comment by KrossX** [comment]
Nice! Can you test the very first version?

**Comment by deadair3210** [comment]
Plugin is working perfectly as far as i can tell, all buttons are working and reporting pressure. Extracted a clean copy of everything to make sure

**Comment by KrossX** [comment]
Yay! That's quite the good news indeed. Thanks for all the testing.

**Comment by deadair3210** [comment]
No problem! Have been wanting to get pressure working for PCSX2 for a while now, but wasnt sure how to do so as I am just starting to learn programming

**Comment by Blackbird88** [comment]
Wait so is this incorporating changes of Lilypad-Scp? Will that malware garbage MiJ finally get replaced?

**Comment by mirhl** [comment]
Shouldn't.. there be other changes?
I mean, I compared [SCP](https://github.com/nefarius/ScpServer/tree/master/Lilypad) and pcsx2 sources, and they are still quite different. 
[Lilypad.rc](https://github.com/PCSX2/pcsx2/blob/master/plugins/LilyPad/LilyPad.rc) still has the libusb note. Not to mention [DualShock3.cpp](https://github.com/PCSX2/pcsx2/blob/master/plugins/LilyPad/DualShock3.cpp). 

Besides, shouldn't the malware garbage crap MiJ already be replaced everywhere?

**Comment by KrossX** [comment]
No need for more changes. This ain't a merge of the LilyPad_SCP version, it just adds support for the SCP xinput extension to the xinput backend. Same result, without replacing libusb with more xinput code. It's also seamless between xinput devices, as all can share the same mapping.

**Comment by mirhl** [comment]
Yes, it's definitively elegant (this means there's still room for default drivers, right?)

But.. I mean, I can't understand why all the other changes then, if it was all this simple.

**Comment by KrossX** [comment]
LilyPad_SCP discriminates between normal xinput controller and scp xinput controller. That way, the SCP controllers are listed as DualShock 3 with the appropriate control names on the settings (square, tringle, etc) instead of generic xinput controller. It's fancier and makes sure those using the SCP version see the extensions are being used.

**Comment by Blackbird88** [comment]
So what is the advantage over Lilypad-Scp now? Lilypad-Scp at least shows correct controller name and button names.

**Comment by KrossX** [comment]
Other than the GUIDE button being usable for non-SCP controllers and no split for xinput mappings, there's no advantage. However, it's necessary if default xinput mappings are to be added. That way, the defaults would work for any xinput device be it SCP or not.

**Comment by Blackbird88** [comment]
You misunderstood me. So does this work same way as SCP? With all the correct names? If not then it'll get confusing real fast.

**Comment by KrossX** [comment]
It does not work the same way as LilyPad_SCP, it ain't a merge of LilyPad_SCP nor its replacement. It still requires proper driver and wrapper to be used, so the user shouldn't be ignorant that it's using a xinput wrapper. It would be the same as using x360ce, your control would be listed as a xinput device with standard xinput names. Those using the SCP wrapper (with proper drivers) would get the benefit of pressure support.

I've tried a few ways to show SCP extensions being enabled or in use, but haven't come up with a good way yet.

**Comment by Blackbird88** [comment]
I understand what you're doing. Trying to standardize the SCP's extended Xinput support, but in that case why is the MiJ libusb checkbox left alone?

**Comment by KrossX** [comment]
Why wouldn't it be left alone? It's another supported backend.

**Comment by mirhl** [comment]
I guess this has something to do with MiJ reputation. And I agree everything on the whole planet recalling that should be extirpated. 

Though, is that the only thing that uses libusb? 
Because I mean, if normal DS3 drivers were to support that, it would be fine I believe then

**Comment by KrossX** [comment]
Added default mappings for XInput, device 0 and 1 to port 0 and 1 respectively. A custom ini file is created if there's no previous file found.

This is why I added SCP support, so that SCP devices can benefit like any other XInput device and also get pressure support by default. =D

Test build: [LilyPad_04.zip](https://drive.google.com/open?id=0B1wssOeJs5_7T1pJQ2oxWWYzaHM)

**Comment by ramapcsx2** [comment]
Do you want me to merge this now? Is there still testing to do or some issues left?
Otherwise it'd be better to seperate the SCP stuff from the default ini stuff.
Default ini should go into the release, SCP stuff I don't know, haven't followed this.
If it's stable and an improvement, why not.

**Comment by KrossX** [comment]
Main caveat of this pull is that xinput configuration is incompatible. This is due to an extra button being added and all buttons now support pressure.

**Comment by KrossX** [comment]
My, that was an ugly way to rebase.

**Comment by deadair3210** [comment]
Was reconfiguring my controls and noticed something. More of an annoyance than a bug, but when reconfiguring or mapping buttons, the mapper will only register a button being pressed if the button reaches its max pressure. have to press pretty hard on them to get them to register

**Comment by KrossX** [comment]
I'll see if I can make it easier. Though in the meantime, it seems I broke the branch? =S

**Comment by danilaml** [comment]
@KrossX `rebase -i` is your friend xD

**Comment by willkuer** [comment]
```
git rebase -i pcsx2/master
```
(or with HEAD~n if you like it more) but more important
```
git push -f
```
to overwrite the history of the branch

**Comment by KrossX** [comment]
Yes! Thanks @danilaml and @willkuer, now it looks more like a proper thing again.

I just did what I was normally doing, clicking the GUI button that said "Update from ...." but it failed. I then tried to resolve the conflicts and it seemed fine. Problem, there where some missing files including the buildbot's for some reason (not even related to the conflicts). Then I ended up with that mess, but ditching the GUI in the process so there's a plus at least.

**Comment by willkuer** [comment]
Using the gui never worked for me. The git power shell appears highly confusing in the beginning but at least it does what you want it to do. And you can use it in parallel to the gui to keep advantages of both.

You still have these two - i think - unrelated commits in your changelog. So the rebase is still not completely clean.

**Comment by KrossX** [comment]
I think it's clean now. Those where leftovers from me thinking my master was messed up, and so I clicked the "Update from..." a bunch of times.

**Comment by KrossX** [comment]
@deadair3210 is it any better now? [LilyPad_05.zip](https://drive.google.com/open?id=0B1wssOeJs5_7YzJ4QkNYV180V2c)

**Comment by deadair3210** [comment]
Sorry it took so long, was away from my computer. Tested the plugin, works much better.

**Comment by gregory38** [comment]
@ramapcsx2 @bositman is it for you? Can we merge the code.

**Comment by bositman** [comment]
Can't test, don't have a pad supporting pressure buttons :/

**Pull request merged**
