### PR TITLE
GameDB: Add Quake 3 Revolution patch

### PR DESCRIPTION
**Pull request by lightningterror**
Removes intro and end credits FMVs.
Fixes hanging caused by FMVs.

https://forums.pcsx2.net/Thread-Quake-3-Revolution-SLUS-20167-U--29913
https://forums.pcsx2.net/Thread-Quake-3-Revolution-SLES-50126-E

### CODE REVIEW

**Comment by lightningterror** [comment]
p.s. @refractionpcsx2 I prefer if you merge prs using the third (rebase and merge) option.

On a side note looks like appveyor ignores the skip ci command, even adding skip appveyor doesn't do much, odd.

**Comment by refractionpcsx2** [comment]
Done as your request

**Comment by bositman** [comment]
I *think* it didn't work because you didn't leave a space after Fixes hanging caused by FMVs.

**Comment by lightningterror** [comment]
I don't know if it was that, I think I did earlier, as well as a new line before editing the commit, kinda too late now.
Will see in the future.

**Comment by turtleli** [comment]
https://github.com/appveyor/ci/issues/1865 - [skip ci]/[skip appveyor] currently only works on AppVeyor when it's in the commit title, which isn't great since it doesn't really provide useful information about what the commit is about.

I'm not sure [skip ci] should be used for GameIndex.dbf changes though since that just makes it harder for users to test changes.

**Pull request merged**
