### PR TITLE
CI/Linux: Add Flatpak build files

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

This PR adds a Flatpak build to our CI, using (almost) the same configuration as the AppImage.

Thanks to @charlesthobe for the assistance with putting the manifest together.

The current flatpak package was created without any discussion with us, and has several issues:
 - Out of sync with releases.
 - Built with gcc instead of clang (up to 15% slower in some games).
 - Until recently, disabled inlining => significant speed loss.
 - Not maintained by us, so we cannot debug or fix any problems with it.
 - No notification of updates.
 - Probably doesn't have working ffmpeg (at least not for all formats).

So, instead, I'm proposing we provide this package ourselves. I've been able to work around most of my grievances with the format (mainly by not having to confirm to flathub builder limitations listed below), overall it's definitely still a bit clunky (e.g. flatpak-builder crashes on syntax errors, and type errors are silently ignored), but it mostly works.

For several reasons, we can't use the flathub builders, including:
 - No internet access in the build environment (needed to download deps and patches).
 - Not in sync with our releases here, have to be manually updated.
 - Impossible for users to download pull request builds to test potential fixes.
 - Patches repo builds a zip, which doesn't have a fixed hash.

To make support easier, and minimize the chances of flatpak-specific issues, the flatpak follows the exact same build process as the AppImage (less using clang 16 instead of clang 12, because 12 isn't available on 22.08).

~~There's still a couple of issues I need to resolve~~, but we can get some discussion going, and see if anyone has any opposition for us doing this in the first place in the meantime.

Still TODO, but this will be post-merge:
 - Hook up publishing to flathub.
 - Make the automatic updater shell out to flatpak update, or whatever.

On the last point, that is a potential issue. We'll need to get a token from the flathub admins, so we can push releases from our CI to their repo. Hopefully that is something which can be arranged, if not, we'll have to run our own repo, or something..

~~As for the others, switching to the kde platform would probably fix them. I wanted to use the same qt libs as the appimage for consistency, and to reduce user's download sizes, but it might be less painful in the future to just switch over. Thankfully, we don't patch any qt code, only the build system, so that lowers the risk of different behaviour (although the KDE platform patches qt..)~~

### Rationale behind Changes

There's a non-trivial number of users using the flatpak. We want to provide the same experience regardless of which packaging format they use.

### Suggested Testing Steps

Test flatpak build (I'll do this, I don't think any of our testers have it installed).

Make sure the AppImage still works.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Tagging in @TellowKrinkle

**Review by TellowKrinkle — COMMENTED** [review]
Seems fine to me (once it fully works of course)

Not sure why you're asking me though, I don't generally touch flatpaks, and have no experience building them (so you'll probably want someone who knows how the flatpak build build system works to look at the flatpak-y parts).

**Review by Mrlinkwii — APPROVED** [review]

**Comment by qurious-pixel** [comment]
Could you add the extension to differentiate from the build artifacts?

something like:
PCSX2-linux-QT-AppImage-x64-pr[8942]-sha[a96398c]-title[CILinux Add Flatpak build files
PCSX2-linux-QT-Flatpak-x64-pr[8942]-sha[a96398c]-title[CILinux Add Flatpak build files

 `Windows|Linux: PCSX2-<tag>-<windows|linux+extension>-<32bit|64bit>--[additional hyphen seperated tags]`

image

**Comment by stenzek** [comment]
Not without potentially breaking the current release pipeline. It should have flatpak in the filename now, though.

32/64bit is redundant, we haven't supported 32bit for some time. Although arm64 will be a thing at some point, but I do not plan for that to work with Linux (only Mac/Windows), so it's a non-issue.

**Pull request merged**
