### PR TITLE
GS/HW: Redo some double half clear checks + Reduce CLUT flushes

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Redo some of the double half clear checks to try to catch the cases better.

### Rationale behind Changes
There was a lot of problems with misdetections, especially if no targets existed, making some bad targets being created. Naturally I ended up going down a spiral of regressions, so it went a bit further than I was hoping.
Also makes sure we don't flush on CLUT reload if the current draw isn't using a texture, unless the current draw is the new CLUT.

MGS thermal vision has many less draws now, but now has an upload due to a Double Half Clear misdetect, since the code is hit early due to a CLUT upload before the new context is set up.  The solution to this is going to be to delay CLUT reloads until it tries to draw more, but that's out of scope of this PR. Currently mitigated with `GS/HW: Assume not a DHC if clut overlap on depth clear` commit.

### Suggested Testing Steps
Test plenty of stuff, make sure nothing that does double half clears especially breaks.

Fixes shadow problems on Spiderman 2

Master:
image
PR:
image

Also reduces the number of drawcalls in some games:
DragonBall Z games seemed to lose around 100 drawcalls on average
Metal Gear Solid 2 Thermal Vision loses 259 drawcalls 
Xenosaga Episode 3 loses around 10 draw calls
Final Fantasy XII GS Dump I have had the following improvements

```Final Fantasy XII preload frame data texture issues
Draw Calls: -14 [577=>563]
Render Passes: -14 [26=>12]
Barriers: -15 [554=>539]
Copies: -1 [1=>0]
FPS 575 -> 595

### CODE REVIEW

**Review by Mrlinkwii — APPROVED** [review]

**Review by JordanTheToaster — APPROVED** [review]

**Comment by BParks21** [comment]
I'm seeing a very minor black line on the left side of Spider-Man's shadow. Not sure if that was always there in hw mode or not. Are you seeing that as well?

**Comment by refractionpcsx2** [comment]
Unlikely to be related to this, probably always been a problem, likely upscaling

**Comment by BParks21** [comment]
It does appear at native res though. Don't think it is upsacaling. It seems to be triggered in a similar fashion as the shadow issue. For instance switching from sw back to hw would correct the shadow but as soon as I jumped and moved spider man around I would get the roblox shadow lol. This black line behaves and is triggered in a similar way. Anyways just thought I'd mention it because of the similar way of reproducing it.

**Comment by refractionpcsx2** [comment]
Well if you can make a gsdump of it then we can take a look

**Comment by BParks21** [comment]
> Well if you can make a gsdump of it then we can take a look

Multi or single?

**Comment by refractionpcsx2** [comment]
if you can get a single to show it, then sure, otherwise a multi.  Just be sure to check your resulting dump after making it, before you post it :)

**Comment by BParks21** [comment]
> if you can get a single to show it, then sure, otherwise a multi. Just be sure to check your resulting dump after making it, before you post it :)
[snaps.zip](https://github.com/PCSX2/pcsx2/files/12707371/snaps.zip)

Here's a single lmk if you need the multi

**Comment by refractionpcsx2** [comment]
That doesn't show it

image

Also does it only happen with the Widescreen patch?

**Comment by BParks21** [comment]
Happens without the patch. Here's the multi 

https://drive.google.com/file/d/15lwJnNgzcc04d85zhIWN8eBAJ2buaUE4/view?usp=drive_link

**Comment by refractionpcsx2** [comment]
That's not showing it either

image


did you check the GS dump before you uploaded it?

**Comment by BParks21** [comment]
> That doesn't show it
> 
> image
> 
> Also does it only happen with the Widescreen patch?

No I didn't haha. I should of I'm a dumbass. I really thought it would show in the multi. Can you just jump and swing, then check to see if it appears. It only appears after I jump and swing.

**Comment by refractionpcsx2** [comment]
Then you should make a multi frame dump of you doing that ;)

**Comment by BParks21** [comment]
> Then you should make a multi frame dump of you doing that ;)

I thought that's what I did for the multi frame. Hang on let me do it again.

**Comment by RedDevilus** [comment]
> > Then you should make a multi frame dump of you doing that ;)
> 
> I thought that's what I did for the multi frame. Hang on let me do it again.

I suggest perhaps changing multiframe to a single key to make it easier. Or we should make a timed event button (like 10 seconds) so you don't have to hold and do an action in-game to trigger the issues.

**Comment by refractionpcsx2** [comment]
No you held down the buttons of you standing still.

**Comment by BParks21** [comment]
> No you held down the buttons of you standing still.

I uploaded a new multi dump that I tested, it is definitely visible in this one. 

https://drive.google.com/file/d/1rDXOBwBIx0uYYFuYPhRMFcVzbaIdbonl/view?usp=sharing

**Comment by refractionpcsx2** [comment]
yeah that didn't show a line, it just outright broke, looks like the double half clear died a death :(

image

**Comment by refractionpcsx2** [comment]
Wait no, now I'm being a dumbass, I forgot to update my master branch xD

I see the line

**Comment by BParks21** [comment]
> Wait no, now I'm being a dumbass, I forgot to update my master branch xD
> 
> I see the line

Looks like we are both dumbasses LMAO

**Comment by RedDevilus** [comment]
Uploaded how it looks for future reference.


https://github.com/PCSX2/pcsx2/assets/24227051/261840d0-fead-4868-b740-cfa0c2272ba9

**Comment by refractionpcsx2** [comment]
I see what's going on here, it's because of the rounding of the rect, so we're losing a pixel on the end.

**Comment by refractionpcsx2** [comment]
To give a bit more detail, the rect is doing 0,0-127,63, so it takes the rect as 127 pixels wide and 63 pixels tall, then adds the same on again, now it's 0,0-254,126, instead of 255,127.  Gonna be a pain to get that, so I'll just clamp it to page boundaries (which is basically what they're doing anyways)

**Comment by refractionpcsx2** [comment]
Should be fixed in master now.

**Comment by BParks21** [comment]
Looks good now.

**Pull request merged**
