### PR TITLE
Gsdx: gui changes

### PR DESCRIPTION
**Pull request by turtleli**
Changes (Windows):
 * CRC hack combobox moved to main dialog.
 * Added tooltip functionality. See #578.
 * Removed the hacks description box since tooltips are in place.
 * 3-state checkboxes converted to comboboxes. :)
 * Renderer specific hardware options show up only when the renderer is selected.

Changes (both):
 * Removed some now unused defines/enums and functions related to the changes.
 * Descriptions - Since the descriptions are no longer used for the Hacks description box, the descriptions no longer need to have "Sprite Hack", "Alpha Hack" etc at the top. Some formatting changes and minor fixes also made.

Windows build at http://turtleli.unospace.net/GSdx32-gui-SSE2.7z .

Tell me if there are tooltip bugs - Report the comctl32.dll version (see Console) and Windows version being used.

One bug I know of:
Windows 10, comctl32.dll, 6.16.10011 - edit control tooltips (skipdraw, TC Offsets) don't disappear unless the mouse is moved over the tooltip or the hacks dialog is closed. comctl32.dll, 5.82.10011 works fine.

### CODE REVIEW

**Comment by ssakash** [comment]
Looks good to me :+1:

one more concern though: could you also move MSAA to main dialog ? , it was requested by a lot of users before. I personally don't see a reason to get it limited to the hacks dialog.

**Comment by turtleli** [comment]
I won't be moving it in this PR. My main concern was to check that the tooltips are more or less working properly.

More improvements/changes can of course be made - There's a lot that can be done better and/or differently. But these changes should be a step in the right direction

**Comment by gregory38** [comment]
Did you test the rendering of tool-tip on linux ?

**Comment by turtleli** [comment]
Yes. It should look as good as (or as bad as) it does on Windows.

**Comment by vsub** [comment]
I don't know if this is a bug or it,s only here but when I hover over a button\checkbox which have a tooltip,the tooltip almost always appear for half a second then disappear and appear again(the second time it stays visible)
I'm on Win7 x64 Ultimate SP1

**Comment by ssakash** [comment]
> the tooltip almost always appear for half a second then disappear and appear again
I can't reproduce this issue on my side, on windows 10 currently.

**Comment by turtleli** [comment]
@vsub
It's either one of two things:
1. A bug that occurs on Windows 7.
2. It might be that you're moving the mouse ever so slightly just as the tooltip appears, therefore hovering over the tooltip and making it disappear, then reappear. I had a similar problem when I reduced the time that it took for the tooltip to appear to 0.2s (currently it's at the default of 0.5s). I could perhaps increase the time it takes for a tooltip to appear if this is the case.

@ssakash
Hmm. No :) My plan was a minor GUI revamp with tooltips to fix the worst parts of the GUI (what I think I've done, I did a bit extra, but oh well), and then a more proper redesign, but with user input - there are some good suggestions at the forums but I'd like it done in one go so the GUI doesn't change every few days and cause everyone confusion.

**Comment by avih** [comment]
@turtleli, speaking of tooltips, I think the one for the presets checkbox is broken since... not _too_ long ago (weeks?). It should be displaying a much longer tooltip, as if the whole part which explains a bit about the different levels is cut off. FYI ;)

**Comment by turtleli** [comment]
I don't think it's broken. However, there are two different messages - one for the preset checkbox, one for the presets slider. That's probably the confusing part and it probably should be changed.

**Comment by avih** [comment]
Hmm.. true.. There's is some value in the (partially) different messages, but also source for confusion indeed. No bright idea how to resolve this for now...

**Comment by turtleli** [comment]
Thinking again, it's not really that confusing. It's perhaps confusing to remember that there are two different messages but it makes sense from the user's perspective. However, the messages don't show up long enough on Windows (it's fine on Linux) - it shows up for 5 seconds, the default tooltip time.

**Comment by avih** [comment]
Yes, there's that too (tooltip duration).

**Comment by tsunami2311** [comment]
Nice, I would still Remove OpenCL Device there is no reason for to be there unless OpenCL render is used.

I would Also rename "Internal Resolution" to "Enhancements" (can cause glitchs) and put Shader boost, FXAA ,FX Shader, Texture Filtering, Anisotropic Filtering All in the that section, Along with MSAA Cause all those are meant to enhance the image.

Put Blending Unit Below CRC level in Opengl

Tool tips all seem to work on Windows except for AA1, FXAA, FX SHADER, Shader Boost, Anisotropic Filtering,Extra Rendering threads, granted some these should be self explanitory but Anisotropic Filtering not so much

**Comment by turtleli** [comment]
@tsunami2311 - Those items don't currently have tooltips. Perhaps they should be added (someone needs to come up with good descriptions). What Windows version are you using?

**Comment by tsunami2311** [comment]
@turtleli - Windows 10

**Comment by ssakash** [comment]
AA1 (edge anti-aliasing) - Removes the edge aliasing of Lines and Triangles.
AF - Enhances the image quality of textures by reducing aliasing effects,blur and by preserving detail at extreme viewing angles.

**Comment by tsunami2311** [comment]
isnt AA1 also only for software mode?

**Comment by ssakash** [comment]
yeah, that's right. it also needs to be included on the information.

though in my opinion, it would be better to grey out the software mode options when any non-software mode renderers have been used, this way it'd be pointless to include that information into the tooltip, the tooltip won't be visible when any other non-software mode renderers have been used. so it wouldn't cause any conflict.

**Comment by avih** [comment]
Looks good! (tested on Windows 8.1)

Suggestions:
- Make the tooltips last (yet) longer if possible. I'd say indefinitely if possible (until mouse move I guess).
- Disable the "Configure hacks" button when "Enable HW hacks" is unchecked. I realize there's value in allowing to change the hacks also when they're disabled, but I think there's also value, possibly higher, in disabling access to features which are currently disabled.
- Not 100% sure about this one, but maybe try to make the sides of the widget/text more consistent, especially in groups which have both checkboxes and dropdowns. checkboxes are typically to the left of the text, but dropdowns are usually to the right, and mixing those together at the same group makes it look a bit weird. For such groups, I'd say move the checkbox to the right of the text (similar to the "Internal resolution" box).

But these can be followups. Overall, looks very good IMO.

**Comment by gregory38** [comment]
```
AA1 (edge anti-aliasing) - Removes the edge aliasing of Lines and Triangles.
AF - Enhances the image quality of textures by reducing aliasing effects,blur and by preserving detail at extreme viewing angles.
```
AA1 is the internal GS mechanism to apply some anti-aliasing. As you said it help to reduce edge aliasing of lines and triangles.

AF I would just say: reduce texture aliasing at extreme viewing angles.Costly in perf.

**Comment by turtleli** [comment]
Ok. I'll add tooltips for those items to both GUIs soon. FXAA needs a better description I think.

 * Disable software mode options for HW renderer- Users F9 to the software renderer when there are hardware mode glitches, so I don't think that should be done.
 * Tooltip duration - I would have preferred it to be indefinite as well, but it's a Windows limitation. At most I can extend the duration for another 2 seconds.
 * Disable "Configure hacks" button when HW hacks isn't enabled - I'll do that unless someone objects.
 * Other GUI suggestions - I'll leave till after the PR. Making the Windows GSdx GUI even better will probably involve quite a bit of redesign, which will delay the more immediate improvements.

One thing I did forget to add was the ability to select the external shader and shader config via the GUI (feature exists in Linux), so maybe I should do that first.

**Comment by willkuer** [comment]
Does this enable hw hacks check box makes sense? Does one need a fast toggle for the hacks? I think it introduces confusion if someone plays with the hacks that don't get applied.

**Comment by avih** [comment]
> Does this enable hw hacks check box makes sense?

To me it makes some sense at least, even if not strictly required. The reason is that otherwise it's impossible to see if/which hacks are enabled without opening the hacks dialog, so this makes it simpler to uncheck in order to disable all hacks. It still doesn't show which hacks are enabled ehen it's checked, but at least it solves a part of the problem.

@turtleli re tooltip duration - make it as long as you can please ;) thx.

**Comment by turtleli** [comment]
Tooltip changes:
 * Both Windows and Linux: Added tooltips for FXAA, FX/External Shader, Shade Boost, Extra rendering threads, AA1 and AF
 * Linux: Added software mipmap tooltip.
 * Windows: Added DX9 alpha correction and Logarithmic Z tooltips.

Please check the descriptions.

Other changes (Windows):
 * Extended tooltip duration by 2.767s.
 * Disabled "Configure hacks" button unless "Enable HW Hacks" is ticked.

I plan on delaying external shader file selection on the Windows GUI till after this PR (unless people really me to include it, the GUI work is done). Right now it's OpenGL only, and I'm going to try and have it working for DX before adding it to the GUI.

Windows build is still at http://turtleli.unospace.net/GSdx32-gui-SSE2.7z .

**Comment by tsunami2311** [comment]
Looking Good on my end extend tooltip time is great change too, always thought it was to short.

Other then the moving/removal of things i mention earlier great step to making things less confusing

**Comment by ssakash** [comment]
Looks Good to me :+1:

**Comment by myownfriend** [comment]
"HW OGL Depth" can just be called "HW Depth" or "Hardware Depth" now that it's only shown when OGL is selected anyway.

In the Hacks Configuration Dialog, Alpha Stencil and Alpha shouldn't appear when OpenGL is enabled and "Direct3D only, OpenGL emulates those effects correctly with accurate options." should be removed from the tooltips. Same applies to MSAA and it's tooltip.

Can CRC Hack Level be defaulted to "Partial" for OpenGL and "Full" for DirectX since those are there recommended settings?

**Comment by myownfriend** [comment]
Also, how come some of the tooltips have rounded corners and some don't?

**Comment by turtleli** [comment]
* HW OGL Depth wording - I'll change it to Hardware Depth.
 * Hacks configuration dialog - I'll partially change it. I'll do as suggested for the checkboxes. I won't touch MSAA, I somewhat worry that there might be quite a few "MSAA is missing/disabled in the Hacks dialog when I choose OpenGL" questions appearing on the forums if I do. Disabling the combobox does unfortunately disable the tooltip.
 * CRC Hack Level - It's a reasonable suggestion, but I do wonder what the best behaviour for this should be. Should it happen when there's no ini, or all the time. I don't think I'll make the change in this PR.
 * Rounded corner tooltip inconsistency - What Windows version are you using? Might be a Microsoft at fault issue, but I forgot to investigate. I assume Windows 10 (I noticed it but completely forgot about it)

**Comment by willkuer** [comment]
I think changing to recommended is not a good idea. But is partial not recommended for both? I thought partial allows crc hacks for dx but not for ogl while full forces crc hacks for both and none disable crc hacks for both APIs. I think partial should be the default for both.

**Comment by turtleli** [comment]
Full is recommended for DX, Partial is recommended for OpenGL. Partial still has CRC hacks, just not as many.

**Comment by myownfriend** [comment]
Yup, I'm on Windows 10. Is it really a problem if people wonder where the MSAA option went though? According its tool tip, it doesn't do anything in OpenGL anyway so it's not like they were actually using it.

I'm not sure if it's well inferred in the concept that I linked to, but I put the MSAA options and FXAA option in one combo box just labeled "Anti-aliasing". Is this a possibility for a future PR? I know people might be wary about grouping them together since they're implemented in very different ways but they aim to achieve the same thing and you wouldn't really have both on at the same time.

On the topic of the CRC Hack Level, if the recommended settings aren't defaulted, can "Partial (openGL recommended)" be changed to "Partial (OpenGL Recommended)" a least? That's really bugging me lol

**Comment by turtleli** [comment]
MSAA - I think it would save some hassle. Maybe I'm overthinking it.

Concept - Maybe? This PR was more intended to fix things that were annoying (to me) and add tooltips. If someone wants to redesign the Windows GSdx GUI after this PR is done they're welcome to (but do make sure that users think it is an overall positive change, though that shouldn't be too difficult).

CRC Hack Level - Sure. Will change that. To "paRtIaL (oPeNGL RECOMMended)" ;) Nah, I'll change the text properly.

**Comment by tsunami2311** [comment]
I like the idea of make AA combo box and puting but FXAA/MSAA in there too,

**Comment by myownfriend** [comment]
Thanks! I'm gonna see if I can maybe do the other changes myself :-)

**Comment by mirhl** [comment]
I don't see this idea going well. FXAA is just post processing AA, and it's only on or off (and for this it's not even "hacky" technically.. you just blur the image pretty much)
MSAA is proper AA and as such it may have its problems. Also, you can take more or less samples.

**Comment by tsunami2311** [comment]
as i been saying for months MSAA has the same issue it has with  certain PS2 games via PCSX2 as it does with certain PC game engines. MSAA is not compatible for all ENGINES on the pc there for it not compatible with all ps2 games cause they all dont use the same engine. some engines have bad side effect some just wont allow MSAA. MSAA dont  play nice with deferred lighting  engines for instance. This dont make it a hack it make compatibility issue.

Both FXAA and MSAA are forms of AA one is shader based other hardware based one works for all game engines the other has compatibility issue with some types of engines. Which the reason FXAA and SMAA and all the other shader based AA was made.

Better to have the both in same place as they both have same purpose. Scaling is HACK and its  side effect are way more noticeable see then we have multiple hack to fight the issue it cause. MSAA side effects minute in comparison and  yet scaling it not hack section. which make even less sense then MSAA being there.

it more of matter of there both AA it make more sense to have combo box for AA listing both FXAA and MSAA, warnings can be put in the popup tool tips

**Comment by myownfriend** [comment]
If people were asking for the MSAA options to be moved to the main dialog anyway, then why not merge them into one combo box? Does it really matter that the MSAA options are hacks while FXAA is post-processing? If someone runs into an issue, they'll just stop using that option just like any other option.

While I can see some sense in separating them due to how vastly different they're implemented, this only makes sense to a developer, to the user who doesn't know a thing about that, it's just more combinations of switches that they turned on to have to troubleshoot. Putting them in the same combo box would at least inform this user that they're both used for the same purpose and one isn't needed when the other is on. Currently, that user might only be informed of these things if they read both options individual tooltips and even then, its not said in such a straight forward way.

Sure, you could have an area called Anti-aliasing that has three radio buttons (None, FXAA, MSAA) with the MSAA option enabling a combo box with MSAA options but that's needlessly complicated.

**Comment by gregory38** [comment]
Honestly you can't compare PS2 rendering with any PC games.

The basic anti aliasing method is called upscaling (or SSAA). It costs a big gpu as you need to render much more fragments (samples). It is very efficient as AA therefore it creates various glitches.

Msaa is an optimized SSAA. In short, the shader is run once for a groups of samples (instead of 1:1). It reduces the gpu cost but it breaks various alpha effect (same alpha is outputed for all samples of the same groups). The anti aliasing effect is less efficient therefore it avoids various glitches of SSAA (MSAA only improve the aliasing of geometry). I never tested it but I suspect that MSAA requires more CPU power (unlike pc game) to handle some post-processing effects (well DX supports a limited set). Or maybe more GPU power to interpolate the Nx samples into a standard texture.

Both upscaling (SSAA) and MSAA are done during the rendering.

Fxaa is just a frame filter that detect the edges and blur them.

You can enable all the 3 AA methods in the same times.

**Comment by turtleli** [comment]
Changes made ("Partial (OpenGL recommended)", alpha, alpha stencil tooltips changed and checkboxes hidden for OpenGL). Build at same location at before.

 * Has anyone on Windows 7 experienced the behaviour vsub did?
 * Do the inconsistent rounded tooltips/tooltip bugs affect anything other than Windows 10?

**Comment by tsunami2311** [comment]
@gregory38 

Point I was making is MSAA has compatibility issue with certian types of engines. which hold true PC or ps2.

IF MSAA is consider a hack then so should scaling  cause it cause more issue then MSAA, another thing HW HACKS should not even be call HW HACKS. IT should be called HW FIXES, everything in HW HACKS section is ment to FIX something broke from  HW rendering and or scaling.

MSAA does none of that. Everything in the section FIXES something cause by hw rendering, so just going by that logic MSAA  DONT belong in there.

**Comment by myownfriend** [comment]
@tsunami2311
The points you mentioned are why the concept I did changes "HW Hacks" to "Game Hacks" though I didn't even like that name. I like your idea off calling them fixes but I would called them Game Fixes. It's already currently in the "Hardware Mode Settings" area along with "Hardware Depth" which was previously "HW OGL Hacks". It's all very redundant saying "Hardware" so often.

Personally, I feel like the whole Hacks windows is out of place. I don't think there's a single option that's currently in the Hacks Configuration that I would really want to configure globally(other than MSAA which we both agree shouldn't be there). It seems weird that there would be a "Wild Arms Offset" checkbox in the main UI and buried two windows in or that there would be specific game fixes mentioned in the tool tips but there's no better places to put them.
 
It's for things like this that I really wish PCSX2 had a game list so that a user can set those parameters per game.

Just to nitpick about some other stuff:

"Settings" doesn't have to come after "Hardware Mode" and "Software Mode", we're in a settings windows, of course they're settings.

The Hardware Mode area is supposed to group settings that don't apply to software mode, yet Internal Resolution settings are also ignored in Software mode, so it should also be in that area as well?

**Comment by mirhl** [comment]
HW hacks name seems fine imo. 
Yeah, they fix something in the end, but they manage to do so because they *hack* a particular behavior in the GS. 

Resolution should be indeed one of these things, but I guess it makes sense there because your average player expect it to be between basic settings in every PC game. 

AF, texture filtering and all then are either something that haven't a "correct" correspondent on PC (so are intrinsically "hacked" by the very nature of HW rendering) or that causes too big performance hit to justify having them always enabled (their *enabling* "prevents" hacks, but it's better to leave the possibility to disable them)

**Comment by myownfriend** [comment]
I have another suggestion for the hacks dialog that I think can be implemented in this PR.
By grouping TC Offset X and TC Offset Y into a group called "Texture Coordinate Offset", you can shorten their names and place them horizontally making better use of space.

http://i.imgur.com/A6ikLag.png

**Comment by tsunami2311** [comment]
@myownfriend I like the idea for the AA and TC off, Could maybe do mock of of all the Image enhancing setting all in one section (Scaling,AA,AF,TF,Shaderboost,GSDX Shader) call image enhancements or something similar?

@mirhl for developer stand point that makes sense, from a end user stand point it does not. I will also bring up the whole Scaling is hack too why is not in there? it far more harmful  more noticeable then what msaa will cause.

Everything in HW HACKS FIXES issues cause my HW rendering  call MSAA does fix anything so again to end user that make no sense there for dont belong there. just like calling HW hacks is miss leading to end user cause any person that use it will realize everything in there "FIXES" an issue hw render cause calling HW fixes or something similar is more appropriate 

GUI changes are geared to make things simpler the end user.

Keeping all image "enhancing" options in one place  is best idea for that (Scaling,AA,AF,TF,Shaderboost,GSDX Shader) separating them make no sense

**Comment by mirhl** [comment]
It's not about *developer* POV. It's about logical POV imo. 
Software is for precision. Hardware is for increased performance, graphics or both. 

At the moment the maths my brain does is: main panel is for what *should* be enabled but I don't enable for speed
Hacks is for what *shouldn't* be enabled but I enable to fix/improve graphics

Resolution being the only exception indeed and I believe this is already most, if not the maximum that makes sense to met "user" expectations. 
Just my two cents.

**Comment by willkuer** [comment]
I think you should first finish the technical part of the pr. Later one can start a design contest in the forum including a poll.

**Comment by turtleli** [comment]
Yeah, any further changes to this PR will be to fix bugs only. I'd rather merge within the week than in 3 months time. Further GUI suggestions/discussion should take place elsewhere (maybe at the forums).

Since it was drowned out a bit:
 * Has anyone on Windows 7 experienced the behaviour vsub did?
 * Do the inconsistent rounded tooltips/tooltip bugs occur on versions of Windows earlier than 10?

**Comment by tsunami2311** [comment]
@mirhl 

Even from logic point of view it dont belong there, everything  in the HW hacks sections fixes some issue cause by hw rendering. MSAA does not, and logically, the sections should not be call HW HACKS. cause from logical stand point all the options in there are fixing issues yes there "hacks"  but there hacks that "Fix" things not cause issue like MSAA can.

Logically  "scaling" should be in that section then its hack( it dont fix thing  it enhances graphics). to ender user it make no sense msaa being there, just like for what ever that kept scaling out that section.

ALL graphicly enhancements should all be in same section, regardless if it "consider" a hack. points back to scaling why is not not treated the same way?

**Comment by gregory38** [comment]
Everything is hack. Except 8 bit texture, new gl option and potentially fxaa. Upacaling and msaa are the same. The idea of the panel is to provide noob setting. Hack are more dangerous to use. Yes msaa is like upscaling, but main options must be limited.
Ultimelately msaa/custom resolution/upscaling must be removed/merged/replaced. The future will be something like 
* number of sample (1x/2x/4x/8x)
* AA texture
* number of FS to run by sampler (0% - 100%)
(Note it will still be an hack)
Now lets back to the topic.

**Comment by karasuhebi** [comment]
>>Tooltip duration - I would have preferred it to be indefinite as well, but it's a Windows limitation. At most I can extend the duration for another 2 seconds.

I asked about this in #dolphin-emu since Dolphin uses wxWidgets as well and it seemed to have indefinitely-lasting tooltips in Windows. It turns out they time out after 25s. Apparently there's some issue with wxWidgets's SetAutoPop:
http://trac.wxwidgets.org/ticket/13793

Anyway you should be able to set it to 25000 like Dolphin does and we'll be good to go. :)

**Comment by turtleli** [comment]
??? It's a Windows limitation, GSdx doesn't use wxWidgets. And it's currently at 32767, the max.

**Comment by ssakash** [comment]
@karasuhebi

only the core of PCSX2 uses WxWidgets right now, GSdx uses Windows tooltips controls for tooltip and Windows CL for GUI resources.

**Comment by karasuhebi** [comment]
Oh I see. My bad. I thought GSdx used wxWidgets as well.

**Comment by turtleli** [comment]
I've changed the style of tooltip used, now they're all rectangular.

I will probably merge this within the next 2-3 days unless there are major problems.

**Pull request merged**
