### PR TITLE
Implement sprite unscaling

### PR DESCRIPTION
**Pull request by CookiePLMonster**
### Description of Changes
This feature decreases the position granularity of sprite draws (when upscaling) to match native scaling. This allows to discard position differences that would have been subpixel on native scaling but is not subpixel when upscaled.

In the current state of this PR, this option is introduced as a new option in HW Hacks, called **Unscale Sprite Position (PR TEST)**, enabled by default. This is not the final state, depending on the results it might be modified.
image

Fixes upscaling in several games that used to require Align Sprite to remove vertical lines on screen. Games I tested:
* Enthusia Professional Racing
* Taiko Drum Master
* TOCA Race Driver 3

For comparison, here's how these changes impact Enthusia:

Master, 8x scaling, no hacks. Notice seams all over the image:
pcsx2-avx2_CJMkDIZVU2

Master, 8x scaling, Align Sprite hack. Notice a single seam right in the middle of the image, visible on the sky:
pcsx2-avx2_mc0qxrNmOF

PR, 8x scaling, no hacks. Notice no seams at all:
pcsx2-avx2_BAxYhWFkT3

### Rationale behind Changes
Numerous games require an "Align Sprite" hack to upscale properly (eliminating vertical seams in the image), and that's based on not-so-safe heuristics. This PR introduces a change that should be far less hacky, perhaps good enough to be default behaviour and not locked behind a hack option.

### Suggested Testing Steps
Test any game requiring Align Sprite, Merge Sprite, and/or Wild Arms Offset hacks. In an ideal world, all 3 might not be needed anymore but I have not been able to try any games that would benefit from Merge Sprite 

When testing, **please ensure the following**, preferably also attach comparison screenshots for these cases:
* Test with **Unscale Sprite Position** enabled/disabled (essentially disabling the PR)
* Compare results of this option against **Align Sprite** and **Merge Sprite**.

### TODO for this PR:
* ~~Implement Direct3D11~~ **DONE**
* Not sure if discarding subpixel via `round` is the correct way. Could require something else maybe?
* If test results are good, remove Align Sprite? Maybe also Merge Sprite.

### CODE REVIEW

**Comment by seta-san** [comment]
is this on by default or is there an option you need to enable?

**Comment by refractionpcsx2** [comment]
it's on by default

**Comment by seta-san** [comment]
okay. i can say it doesn't fix GoW. it needs half-pixil offset: special (texture)

**Comment by refractionpcsx2** [comment]
It doesn't fix any displaced post processing effects that half pixel offset or wild arms fixes.

**Comment by CookiePLMonster** [comment]
Updated to include a Direct3D11 implementation.

**Comment by MarcoEstevez** [comment]
Is it real, i've been waiting for a real fix for years!!!!

**Comment by atomic83GitHub** [comment]
This PR fixes Finding Nemo:

Before:

Capture

After:

Capture1

**Comment by MarcoEstevez** [comment]
It fixes: Colin McRae Rally 3

master:
image

pr:
image

**Comment by MarcoEstevez** [comment]
Also Colin McRae Rally 04

before:
image

This pr:
image

**Comment by CookiePLMonster** [comment]
PR updated with an option to toggle these changes on/off (for testing) and with more suggested testing steps. When verifying fixes, please compare against **Align Sprite** and **Merge Sprite**.

**Comment by seta-san** [comment]
Does anyone know of any list of games that I might test?

**Comment by seta-san** [comment]
it fixes GoW2 underwater
pr
master

**Comment by refractionpcsx2** [comment]
> it fixes GoW2 underwater. it used to be fixed by align sprite
> pr
> master

Does Align or Merge sprite fix that on master?

**Comment by seta-san** [comment]
align fixed it. merge made it look weird

**Comment by seta-san** [comment]
this fixes soul calibur 2. previously align sprite worked.

**Comment by seta-san** [comment]
fixes drakengard 2 but it makes the game look really blurry.. align sprite and merge sprite fixes it and makes the image look sharp

**Comment by refractionpcsx2** [comment]
> fixes drakengard 2 but it makes the game look really blurry.. align sprite and merge sprite fixes it and makes the image look sharp

That looks like an interlacing problem, can you revisit this please?

**Comment by seta-san** [comment]
> fixes drakengard 2 but it makes the game look really blurry.. align sprite and merge sprite fixes it and makes the image look sharp

yeah. what do you need?

**Comment by refractionpcsx2** [comment]
> yeah. what do you need?

I  need you to check it again, and maybe mess with your interlacing settings.

**Comment by seta-san** [comment]
just cycled through them with F5. it makes it go through all sorts of different blurrinesses.

**Comment by seta-san** [comment]
cycling through the images it looks like there is a second version of the image just a few pixels up from where the image is supposed to be

**Comment by RedDevilus** [comment]
Here are some games which are not fixed by Align Sprite, Merge Sprite or even this PR upscaling fix:
I just checked places where align sprite and merge sprite wouldn't worked at all 
Meaning this was what i set default:
image


Star Wars Episode 3 Revenge Of the Sith (SLES-53155)
[Revenge3Sith.zip](https://github.com/PCSX2/pcsx2/files/7003647/Revenge3Sith.zip)

Naruto Shippuden Ultimate Ninja 5 (SLES-55605)
[Naruto5Ultimate.zip](https://github.com/PCSX2/pcsx2/files/7003655/Naruto5Ultimate.zip)

Arc The Lad Twilight of Spirits (SCES-51910)
[ArcTheLadTwilight.zip](https://github.com/PCSX2/pcsx2/files/7003667/ArcTheLadTwilight.zip)

Official Playstation Magazine 30 (SCED-51489) -- NBA Live 2003
[NBALive2003Demo.zip](https://github.com/PCSX2/pcsx2/files/7003759/NBALive2003Demo.zip)

**Comment by seta-san** [comment]
it fixes lifeline. before align sprite fixed it.
llmaster
llpr

**Comment by seta-san** [comment]
Doesn't fix star ocean, either the lines that go through the map or the lines that show up when going through doors... but then again none of the other hacks worked either.

**Comment by seta-san** [comment]
fixes colin mcrae rally 3.. align sprite worked...

**Comment by seta-san** [comment]
the double image blurring is back on tokyo xtreme racer 3. align sprite fixes the game. merge doesn't..
align
unscale

**Comment by seta-san** [comment]
[drakengard 2 decaling.zip](https://github.com/PCSX2/pcsx2/files/7012926/drakengard.2.decaling.zip) much smaller and 2d might make it simpler to figure out
tokyo extreme 3 https://ufile.io/1pl6bljg

**Comment by seta-san** [comment]
129850500-4fc7d90a-d223-4833-94cf-82f91cab36b0

i noticed this in the lifeline photos

**Comment by lightningterror** [comment]
Closing as it's currently not being worked on, pr can be reopened when work resumes.

**Pull request closed without merging**
