### PR TITLE
Disable gl threaded optimization

### PR DESCRIPTION
**Pull request by kenshen112**
### Description of Changes

Disable gl threaded optimizations in Linux

### Rationale behind Changes

Due to recent issues with Nvidia driver in Linux breaking the optimization. Pcsx2 has not run correctly with it enabled

### Suggested Testing Steps

Run Nvidia Linux and compare master to this performance-wise. Preferably in rolling release distros with the latest drivers

### CODE REVIEW

**Comment by tadanokojin** [comment]
`__GL_THREADED_OPTIMIZATIONS=0 mesa_glthread=true`

just delete.

**Comment by tadanokojin** [comment]
`mesa_glthread=true`

delete

**Comment by kenshen112** [comment]
> `__GL_THREADED_OPTIMIZATIONS=0 mesa_glthread=true`
> 
> just delete.

Done

**Comment by kenshen112** [comment]
Should I drop the MESA_NO_ERROR as well?
```

MESA_NO_ERROR

if set to 1, error checking is disabled as per KHR_no_error. 
This will result in undefined behavior for invalid use of the API, 
but can reduce CPU use for apps that are known to be error free.
```

**Comment by tadanokojin** [comment]
no

**Comment by Trevonn** [comment]
If the issue is with the NVIDIA driver why was `mesa_glthread=true` removed? That only affects the Mesa driver correct?

**Comment by tadanokojin** [comment]
not needed so I had him remove while he was here

**Comment by Trevonn** [comment]
Okay I understand and sorry for deleting my comment I misread the commit and thought I had spoken in error

**Comment by qurious-pixel** [comment]
A little late, but should this also be applied for `PCSX2-linux.sh` ?

https://github.com/PCSX2/pcsx2/blob/b61619cf4026f91ef05d70161dac1f5b5a4ea382/linux_various/PCSX2-linux.sh#L61

**Comment by tadanokojin** [comment]
taken care of here https://github.com/PCSX2/pcsx2/commit/64cc1b106ceabb2bb74c101beff5114cfbdc0cd2

**Pull request merged**
