### PR TITLE
GS: preserve target on different format write. 

### PR DESCRIPTION
**Pull request by iMineLink**
### Description of Changes
~~Based on #3895.~~
Avoid discarding the entire target upon incompatible format write (same block pointer), just mark the related rectangle as dirty.

### Rationale behind Changes
See #5317.

### Suggested Testing Steps
Check that #5317 is fixed.
Make sure no regressions occur.

### CODE REVIEW

**Comment by gilderoylockhart01** [comment]
This breaks Beyond good and evil shadows which were fin with the previous hack:

image

Also, wouldn't be a better thing to move this hack to "disable safe features" instead?

**Comment by refractionpcsx2** [comment]
Didn't notice any regressions, don't have an appropriate place in Destruction Derby to check either.

**Review by Mrlinkwii — APPROVED** [review]

**Comment by iMineLink** [comment]
Ok I made the logging super paranoid, to make it easier to check what's going on.
This seems to help also https://forums.pcsx2.net/Thread-Bug-Report-Conflict-Desrt-Storm.
Also, please re-test the shadows in beyond good and evil, if they are still broken (I didn't change this PR logic since creation so it could be) I'll investigate further.

**Comment by refractionpcsx2** [comment]
BGE Shadows look as good as master
Destruction Derby is fixed
Not noticed any other fixed (Don't have Conflict Desert Storm)

**Review by lightningterror — COMMENTED** [review]
> Also, please re-test the shadows in beyond good and evil, if they are still broken (I didn't change this PR logic since creation so it could be) I'll investigate further.

They look fine, same behavior as master, needs Texture inside RT to look better.
Note: Tested only on a gsdump.

**Comment by refractionpcsx2** [comment]
As noted above, improves linked issue is hugely improved in hw mode, but the top left side of the screen (Not quite like Desert Storm but kind of a similar symptom) is still black.

**Pull request merged**
