### PR TITLE
Debugger: Some more debugger updates

### PR DESCRIPTION
**Pull request by F0bes**
### Description of Changes

- Fix up the CSV exporting system to support decimal (oops)

- Add spacebar as a breakpoint hotkey
- Change the colour of a breakpoint when it's set and enabled vs set and not enabled
- I tried to fix up the breakpoint, stack and thread list columns. It looks a little goofy when empty but it's pretty okay when it's filled with data. (I either do this or re-implement columns myself **ʷʰᶦᶜʰ ᴵ ʷᶦˡˡ ʰᵃᵛᵉ ᵗᵒ ᵈᵒ ᶠᵒʳ ᵗʰᵉ ʳᵉᵍᶦˢᵗᵉʳ ʷᶦᵈᵍᵉᵗ**)
- Whenever a breakpoint is hit it'll take you to the breaking CPU tab and change the colour of the tab text
- Fall back to an unmangled symbol when a symbol cannot be demangled in the disassembly view (oops x2)
- Until the disassembly widget is updated, I've turned off pseudo instructions. It sometimes doesn't make any sense and can be confusing

### Rationale behind Changes
Who doesn't like improvements?

### Suggested Testing Steps
Test if what I said above works

### CODE REVIEW

**Comment by Ziemas** [comment]
Looks good to me, maybe it would be nicer to label unknown module exports with the ordinal number rather than the address though.

**Comment by F0bes** [comment]
> Looks good to me, maybe it would be nicer to label unknown module exports with the ordinal number rather than the address though.

I've made the naming scheme <module>::unkn_<num> instead

**Comment by Ziemas** [comment]
Function invalidation isn't working btw, after starting burnout 3 and going to the title screen i now have multiple entries for the kernel module functions.

**Comment by F0bes** [comment]
Are you talking about `ReleaseLibraryEntries` ?
I have it resetting the symbol table on IOP Reset (you might have to click the refresh button), unless there is another case where modules can be unloaded.

**Comment by Ziemas** [comment]
For example:
Screenshot_20231024_184125

The old one stayed in memory so I don't think it's hitting the clear code on IOP update reboot.

**Comment by F0bes** [comment]
I tested with another game. I'm certain that it's related to this. The first loaded mcman (from the kernel) was version 1.01 and the second was 2.07.
```
06h int RegisterLibraryEntries(export_table* t)
Registers an export table, returning 0 if successful.
If an export table under the given name is already registered, several things can happen:
- If the major versions differ, the new export table is also registered, being treated as separate.
- If the new table's minor version is higher, the old table is destroyed, and any imports connected to the old table are updated to the new table.
- If the new table's minor version is lower or the same, the function fails.
```
I guess I should store the loaded modules and their versions. :tired_face:

**Comment by F0bes** [comment]
I've dropped the IOP module analyzer. I'm sick of trying to massage the core debug tools to support it properly.

**Review by Mrlinkwii — APPROVED** [review]

**Pull request merged**
