### PR TITLE
Translations : some typo  fixes

### PR DESCRIPTION
**Pull request by Mrlinkwii**
### Description of Changes

fixes some typos mentioned in   #9062 

### Suggested Testing Steps

N/A

### CODE REVIEW

**Comment by Hazer-123** [comment]
Here

**Comment by refractionpcsx2** [comment]
> Here 

what is there? I don't see any issue there.

**Comment by Hazer-123** [comment]
@refractionpcsx2 Wrong image, sorry. This one below. "Calculate" not "Calclate".

**Comment by refractionpcsx2** [comment]
yes, he got that.

**Pull request merged**
