### PR TITLE
Enhance the EE recompiler making big speed gains

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

 - Add fastmem
 - Add delay slot swapping
 - Add COP2 sync elision
 - Add block analysis and use analysis
 - Add GPR register caching and renaming

### Rationale behind Changes

Brr.

### Suggested Testing Steps

Find out what's broken.

### CODE REVIEW

**Comment by seta-san** [comment]
the 3d opening to ffx 3x res
145-270 v-fps on master
260-415 v-fps on pr to give you an idea

**Comment by refractionpcsx2** [comment]
not new new numbers (I did them yesterday)
Jak and Daxter
image
Jak 3
image
Ratchet & Clank
image
Shadow of the Colossus
image
Soul Calibur 3
image
FFX-2 Intro Movie
image
True Crime NYC
image
Dark Cloud 2
image
Hitman Blood Money
image
Metal Gear Solid 3
image
MDK 2
image
Burnout 3
image
Tekken Tag
image

And saving the best to last... ICO
image

**Review by lightningterror — COMMENTED** [review]
Warnings can be cleaned up.
iCore, iCore-32, recVTLB, microVU_Macro, microVU_Macro

https://github.com/PCSX2/pcsx2/actions/runs/3356305627/jobs/5561277204#step:11:806

**Review by Mrlinkwii — APPROVED** [review]

**Review by JordanTheToaster — APPROVED** [review]
Small improvements are always welcome.

hjerjnertdjnretj

**Review by lightningterror — COMMENTED** [review]
A few more warnings in iR5900Templates.cpp, recVTLB.cpp

https://github.com/PCSX2/pcsx2/actions/runs/3370863751/jobs/5592311071#step:11:823

**Comment by refractionpcsx2** [comment]
Doing some extensive testing, I will update this as I find broken stuff.

Chicken Little - Stuck in place, if you jump out of it you slide until you either jump or fall off the edge of the map
Incredibles - Rise of the Underminer - CTD (crashdump below)
[Incrediblescrash.zip](https://github.com/PCSX2/pcsx2/files/9942460/Incrediblescrash.zip)

**Comment by ehw** [comment]
Tested Bouken Jidai Katsugeki Goemon (SLPM-65014) with these changes just in case something broke. Wasn't sure what to anticipate other than performance improvements, but wanted to give this game a go since it notoriously does some weird things that warranted it having a pretty sophisticated hack to even work properly.

Behavior both with and without the "Goemon-TLB" hack is the same in comparison to the main branch. Game still functions normally without the hack if using EE Interpreter (disable "Enable Recompiler" under EmotionEngine "Advanced System" settings).

**Comment by F0bes** [comment]
Here are some results when using fobesmark™
Basic Arithmetic: ~209VPS -> ~312VPS
Small Recompiler Blocks: ~64VPS -> ~73VPS
LD(x) and SD(x): ~205VPS -> ~290VPS

These numbers are completely meaningless as these tests are designed to be as outrageous as possible. But it's cool nonetheless.

**Comment by Berylskid** [comment]
Select "1x Scale" from Window Size with "Render to separate window" unchecked, then the game screen becomes too long horizontally.
This does not happen in the Master build.
This is a little inconvenient, albeit limited.

**Comment by Berylskid** [comment]
Tested Armored Core Nexus (NTSC-J) (SLPS-25338 and SLPS-25339):
- Cursor always goes downward automatically on menu part.
- It doesn't while playing Mission part.
I also tested Armored Core Last Raven (SLPS-25462) and this problem did not occur.

**Comment by JordanTheToaster** [comment]
> Tested Armored Core Nexus (NTSC-J) (SLPS-25338 and SLPS-25339):
> 
> * Cursor always goes downward automatically on menu part.
> * It doesn't while playing Mission part.
> 
> I also tested Armored Core Last Raven (SLPS-25462) and this problem did not occur.

Can't repro either of your issues.

**Comment by refractionpcsx2** [comment]
Was reproduced, only on the Japanese version.

**Comment by stenzek** [comment]
Fixed in latest push.

**Comment by mindinsomnia** [comment]
Sounds amazing, looking forward to trying it out.

Some games I can think of which had some major performance issues when I tested them last that would be worth testing:
Primal (only barely playable even on a high end PC)
Kim Possible: What's the Switch? (cutscenes had major performance issues)

**Pull request merged**
