### PR TITLE
GS: Improvements to MTBA Mip Mapping

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Fix up behaviour of MTBA (Automatic Mipmap addressing) based on the results of PS2 hardware tests.

### Rationale behind Changes
The behaviour was pretty much wrong and misunderstood.

### Suggested Testing Steps
Test games make sure there's no new Mipmapping garbage in the distance or anything.

Note: Parappa The Rapper 2 might have a glitch in hardware mode, the mipmaps aren't handled properly so it shows a horrible white poly in the corners instead of blending, software mode looks perfectly correct.

Fixes Cartoon Network Racing properly (before we just skipped the mipmapping, you will unlikely notice any difference)

### CODE REVIEW

**Comment by coornio** [comment]
Tested the Jak games and Dark Cloud just in case but haven't noticed anything off with their mipmapping, still as wrong as before :P

**Comment by refractionpcsx2** [comment]
I'm not sure the Jak games use MTBA

**Comment by refractionpcsx2** [comment]
Okay the testing on the PS2 has been completed and this PR is now ready to go.  Parappa still has problems in hardware mode, but it's hardware mode that's broken, not this.

**Comment by F0bes** [comment]
[sponk_psm4_mtba.zip](https://github.com/PCSX2/pcsx2/files/8237102/sponk_psm4_mtba.zip)
For the sake of having a good time you can run this elf on master and this pr and compare.
A PS2 does this
sponk_psm4_mtba

**Pull request merged**
