### PR TITLE
GameDB: Include Instant DMA to Ape Escape 3

### PR DESCRIPTION
**Pull request by micenest**
### Description of Changes
Includes the Instant DMA Hack to Ape Escape 3 (all regions).

### Rationale behind Changes
Fixes (if not, improves) performance in specific regions of the game that uses a camera-overlay of a region of the map to reproduce a screen (examples in maps 'The Big City' and 'Specter TV-Studio', 4 and 5 respectfully)

### Suggested Testing Steps
Has been checked with success and a major improvement in those maps inside a freeplay-mode save, but further tests are welcoming as well.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
What do you mean fixes performance? The game db isn't using game fixes as speed hacks , you're welcome to do that locally.

Unless it's something ridiculous like irs going from singke digit fps to full speed, then I'm not particularly interested in adding it.

**Comment by stenzek** [comment]
What CPU are you using? Also, show the CPU usage in the screenshot as well.

**Comment by refractionpcsx2** [comment]
I wouldn't consider that low fps, it's more than likely that readback is what's causing it to be slow. So disabling hardware readbacks may have the same effect.

I'm gonna say a no on this one, sorry.

**Comment by stenzek** [comment]
For the record, I checked the "Specter TV Studio" level, and the lowest I saw was 165fps in an area that has readbacks, which was around 130fps at 8x (making the readback take longer). So, plenty of time left over.

Instant DMA made no difference there. In areas without readbacks, it took it from around 280fps to 305fps, so not trivial, but again, more than sufficient room left over, so a hack isn't necessary.

(this was on a 5950X with a GTX 1080)

**Pull request closed without merging**
