### PR TITLE
gsdx: support RGB5A1 <=> depth conversion in texture cache

### PR DESCRIPTION
**Pull request by gregory38**
Fix bad depth effect in Silent Hill 4

### CODE REVIEW

**Comment by gregory38** [comment]
Windows build:
http://bositman.pcsx2.net/gregory_pull_request/pcsx2-v1.3.1-1079-g1498bad-windows-x86.7z

**Comment by gregory38** [comment]
Newer build (rebased on master)
http://bositman.pcsx2.net/gregory_pull_request/pcsx2-v1.3.1-1083-g6916211-windows-x86.7z

**Comment by karasuhebi** [comment]
Do you want testing to be done on other games to see if there's any regressions? Or just on Silent Hill 4?

**Comment by gregory38** [comment]
Currently it breaks silent hill 4 shadows :(

So no need to test others games.

**Comment by karasuhebi** [comment]
Okay. :-\

**Comment by gregory38** [comment]
I rebased the code on latest master. And maybe it will work better due to the exp typo fixed in one shader. Need to test silent hill 4.

**Comment by AmbientMalice** [comment]
@gregory38 I have Silent Hill 4. Would you post a built to test?

**Comment by gregory38** [comment]
Try to follow the appveyor link. (Otherwise I wil post the link when I come back from vacation)

**Comment by bositman** [comment]
Shadows in SH4 are fine now :) Here is the build: http://bositman.pcsx2.net/dumps/GSdx32-silent%20hill-4.rar
What was the initial issue this fixed?

**Comment by gregory38** [comment]
By now you mean broken on master and fixed in this branch? Or fixed by this branch?
I don't remember the initial issue. I think it was some extra strange color rendering (like a white sprite in some part of the screen). A depth effect was badly emulated due to the format (game read the depth as 16 bit color whereas other game read the depth as 32 bit color)

**Comment by gregory38** [comment]
Edit: I mean alredy fixed in master

**Comment by bositman** [comment]
I mean the shadows are ok using this PR. I'll look into the old GSdx thread in case someone had reported the initial issue there

**Comment by FlatOutPS2** [comment]
This is the related GSdx thread post: http://forums.pcsx2.net/Thread-GSdx-1-0?pid=476003&highlight=silent+hill+4#pid476003

**Comment by bositman** [comment]
It should go away if you set TC X and Y offsets to 500, or use native

**Comment by FlatOutPS2** [comment]
> It should go away if you set TC X and Y offsets to 500, or use native

Yeah, the offset removed the halo.

I've tried the commit with some other games and it create a regression in a few. In games where Hardware Depth renderers a depth effect, but with a small bug remaining, a line running along the ground and walls at the edge of the effect, the effect now creates all kinds of edges and lines.
Crash Unlimited:
Before:
gsdx_20160417153825
After:
gsdx_20160417153809

WRC II (blurred shots, but it clearly shows the regression):
Before:
gsdx_20160417154120
After:
gsdx_20160417154231

**Comment by gregory38** [comment]
Hum, code is still buggy as hell...
Could you post me a gs dump of Crash Twinsanity. Thanks you.

**Comment by FlatOutPS2** [comment]
Crash Twinsanity gs dump:
http://forums.pcsx2.net/attachment.php?aid=59622

**Comment by gregory38** [comment]
Did you enable VU cycle stealing when you generate the dump ?

**Comment by gregory38** [comment]
Ok. I got it. There is half-screen bug. And the regression is due to a wrong detection of a 16 bits format. Due to the texture shuffling effect, I must keep the depth to 32 bits... It is very annoying.

**Comment by gregory38** [comment]
In short, I need to reimplement completely depth management.

**Comment by gregory38** [comment]
See #1306

**Comment by jonaand** [comment]
there is not fix for silent hill origins shadow HW yeat?

**Pull request closed without merging**
