### PR TITLE
Update PCSX2_FAQ.doc to reflect changes made on the PCSX2 Forum

### PR DESCRIPTION
**Pull request by Jackson-S**
Update FAQ document with changes from forum post

### CODE REVIEW

**Comment by gregory38** [comment]
Could you describe on the commit what was updated ?

**Comment by Jackson-S** [comment]
I updated the original document to match https://forums.pcsx2.net/Thread-Sticky-PCSX2-Frequently-Asked-Questions, which is what the document appeared to be originally based on. I also corrected some minor spelling errors and changed the formatting to be more readable as a Word document. I have changed the commit title to reflect this more clearly.

**Comment by lightningterror** [comment]
Please update the system requirements to match the ones shown on github. The forum ones are outdated.

> System Requirements
> 
> Minimum
> 
> OS: Windows Vista SP2 or newer or GNU/Linux (32-bit or 64-bit)
> CPU: Any that supports SSE2 (Pentium 4 and up, Athlon64 and up)
> GPU: DirectX 10 GPU or better
> RAM: 2GB or more
> Recommended
> 
> OS: Windows 7/8/8.1/10 (64-bit) or GNU/Linux (64-bit)
> CPU: Intel Haswell (or AMD equivalent) @ 3.2GHz or better
> GPU: DirectX 11 GPU or greater
> RAM: 4GB or more

Also the emulator does support PS1 (PSX) emulation. It's just at an infant state.

I could have missed some other things as well but these caught my attention for now.

**Comment by atomic83GitHub** [comment]
For the minimum requirements, DX10 gpu is not neccesary. The DX9 render will be part of the 1.6 version.

**Comment by willkuer** [comment]
You can use more RAM employing a 64bit cpu. Both in-app (due to /LARGEADDRESSAWARE) and system-wide.

**Comment by mirh** [comment]
I'm not sure why minimum wouldn't still be 32 bit
And AMD's haswell equivalent would be ryzen

**Comment by willkuer** [comment]
Yeah that's true. It was more about the 'x64 is useless' part. But sure minimum should be x86 only I guess.

**Comment by Jackson-S** [comment]
I updated the system requirements to match the README.md, and also removed references to v0.9.6 that were in there as it won't appear in that repo. 
I also removed references to the forum FAQ as it's no longer a direct mirror of it and I feel it might be confusing to mention it when they aren't the same.

**Comment by turtleli** [comment]
Maybe just me, but I think it's better if the hyperlinks are obvious.

I note that on master the PDF in bin/docs doesn't match the word file in pcsx2/docs.

My observations:

General:
* The document formatting styles seem to be rathered messed up. Heading 1/2/3/etc all look the same. And it seems as if all the formatting has been done manually? It's probably why there are a few style inconsistencies.
 * The answers stuff all seem to be under Heading 2, when probably they should have the Normal/Text Body style.

Section 1:
* Section header isn't using the Header 1 style.
* Playstation -> PlayStation
* The DirectX redistributables are only required for Windows 7 and earlier. On Windows 8.1 and later the redistributables aren't necessary, except if the user wishes to use the SCP DS3 pressure sensitivity XInput wrapper since that hasn't been updated to work with both XInput 1.3 and 1.4.

Section 2:
* Section header isn't using Header 1 style. It's also indented, which is inconsistent.
* First question isn't using the Header 2 style.
* Ps2 -> PS2
* SVN -> git
* EBay -> eBay

Section 3
* Section header isn't using Header 1 style. It also has a blank line above it, which is inconsistent.
* First full stop is underlined.
* pc -> PC
* The spacing between questions is inconsistent.

Section 4
* Pcsx2 -> PCSX2
* The very last link is unrelated to running PCSX2 running on 64-bit Ubuntu.

**Comment by Jackson-S** [comment]
I can try and fix the heading thing, that's how it was in the original document. The rest of the changes are left in because that's how they were in the original, but I did want to change them and now that it's no longer a 1:1 copy of what already existed online I might go through and make those changes.

**Comment by MrCK1** [comment]
@turtleli 
> The DirectX redistributables are only required for Windows 7 and earlier. On Windows 8.1 and later the redistributables aren't necessary, except if the user wishes to use the SCP DS3 pressure sensitivity XInput wrapper since that hasn't been updated to work with both XInput 1.3 and 1.4.

You probably meant to say 8.0 instead of 7 correct?

**Comment by lightningterror** [comment]
No I think it's only 7 and lower. 8 and above have the files needed.

**Comment by turtleli** [comment]
Technically it is 8.0 or earlier, but 8.0 has been EOLd for quite a while so I decided to just write 7.

**Comment by mirh** [comment]
"anything before 8.1" should be the clearest and precisest imo.

**Comment by turtleli** [comment]
Section headings are still a bit inconsistent - The Section 1 heading has a different style to the rest (more noticeable in LibreOffice) while the rest have a blank line above them.

Section 1
* DirectX redist URL not hyperlinked

Section 2
* `For a better explanation refer to this thread` - Hyperlink is missing.
* EBay -> eBay

Section 4
* `How do I run precompiled Pcsx2` -> `How do I run precompiled PCSX2`

**Comment by Jackson-S** [comment]
Would it be better to convert the document to a PDF to avoid the idiosyncrasies of different editors? To allow for editing the original doc file can be left in.

**Comment by turtleli** [comment]
> Would it be better to convert the document to a PDF to avoid the idiosyncrasies of different editors?

I think the idea of the DOC file is to allow easier editing (maybe we could switch to the ODT format, though I don't know whether that's a good idea or not). It's exported to PDF afterwards and placed in bin/docs/PCSX2_FAQ.pdf .

**Comment by danilaml** [comment]
@turtleli the current doc could be easily converted into Markdown without losing much formatting.

**Comment by turtleli** [comment]
Yeah, guess that's another option, with the added benefit that it's easier to view any changes that have been made.

**Comment by lightningterror** [comment]
What's the status on this ?

**Comment by Jackson-S** [comment]
I’ve been in exams for the last few weeks so haven’t really looked at github, but nobody seems to have any comments on the latest version so presumably it’s okay?

**Comment by lightningterror** [comment]
Can you squash the commits in to one ?

**Comment by Jackson-S** [comment]
Sorry, I’m relatively new at this, how do I do that?

**Comment by lightningterror** [comment]
Open Git Shell
git rebase -i HEAD~7
follow the instructions provided in the text file > save > type the next command
git push -f

**Comment by gregory38** [comment]
no need to squash it can be done by github directly (the fat green button to merge has several option)

**Comment by Jackson-S** [comment]
Everything should be fine as far as I know, I have fixed all the errors everyone has brought up so far, and nobody has mentioned any new errors for more than a month now.

**Comment by gregory38** [comment]
Ok. Thanks you 👍

**Pull request merged**
