### PR TITLE
IPU: Overhaul DMA transfers

### LINKED ISSUE #4063: [BUG] Phase Paradox: hanging issues.
**Describe the bug**
Often during the game, the game logic will frezze for a couple of seconds during the intro or during entire minutes during gameplay with a "rxdma 3 sync timeout" error in the console.

**To Reproduce**
Just play the intro, it does have the issue during the ship destroy sequence.

**Expected behavior**
The game should never stops randomly like that and this console error should not appear.

**Emulation Settings**
Everything was tried with no success.

**System Info**
 - PCSX2 Revision: pcsx2-v1.7.0-dev-817-gc998a51f7-windows-x86
 - OS: Windows 10
 - CPU: I9 9900k
 - GPU: RTX 3070

**Logs and Dumps**
https://drive.google.com/file/d/1QkcxIVHTFBHYTTA9kb-jD78OCMfzbq4E/view?usp=sharing

Wait until the "we have more damage" line can be heard.

**Note:**

During the hang, the game is waiting for IPU_FROM to finish.

### LINKED ISSUE #4360: [BUG] Flipnic : Ultimate Pinball (SLUS-21157) hangs when starting the ufo shootdown mission
**Describe the bug**
The game hangs when trying to start the UFO shootdown mission in the metallurgy stage
the FMV for the mission intro plays and then the entire game freezes

**To Reproduce**
go on metallurgy A or B and shoot the ball into the area where the arrow is pointing to start the said mission
image

**Expected behavior**
after the FMV ends, the mission should start and the game should resume like normal

**GS Settings**
image

**Emulation Settings**
Safe preset

**System Info (please complete the following information):**
 -   PCSX2 1.7.0-dev-1187-g6cc969a89
 -   OS: Windows 10 x64
 -   CPU: Intel Core i3-6300
 -   GPU: AMD RX 560

**Logs and Dumps**

https://drive.google.com/file/d/1irBC8q3VN1rxYJJIZ1whpjynbvkzwKCU/view?usp=sharing

### LINKED ISSUE #5168: [BUG]: Top Trumps Adventures Vol. 2 - Dogs & Dinosaurs (Europe) - sles-54635 - BF31747C
### Describe the Bug

Freeze just before go ingame

Freeze on the screen : 
capture_15122021_171601

### Reproduction Steps

Just launch the game, start a character, 3 types of cards then freeze

### Expected Behavior

_No response_

### PCSX2 Revision

1.7.2120

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Ryzen 5 3600

### GPU

RTX 3070

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Change IPU DMA to only refill on request, also tidied up and bugfixed.  Also changed the internal FIFO to only contain the amount of data required to complete the currently in process command. 

Savestate bump required

### Rationale behind Changes
Some games expect the DMA to be in an exact state in order for it to clear itself and continue, else they hang. Top Trumps being one of the said games, but also Test Drive (Had to change how this functions). Additionally previously the internal fifo was always kept at 2 quadwords, even when it didn't need it, this caused some strange/bad behaviour when pausing/resuming the IPU, so it now only keeps enough data to process the command.

Also the DMA design was kind of terrible, so I rewrote it and it fixed some bugs, so that's cool!

### Suggested Testing Steps
Test videos, make sure ones that are known to work still work. Tekken 4, Fuuraiki, Tiger Woods 06 and Onimusha still are broken as much as before.

Fixes #5168 (Top Trumps)
Fixes #4063 (Phase Paradox)
Improves the moving billboard quality in Test Drive (Master has corruption)
Fixes video hang in Eggo Mania/Egg Mania - Eggstreme Madess (ptch no longer required)
Fixes Smackdown Shut Your Mouth Titantrons
Fixes Gladiator - Sword of Vengeance videos (patch no longer required) Partial #3489
Fixes #4360 (Flipnic UFO mission hang)

Also means Mana Khemia and Metal Saga no longer need a gamefix, however I'm leaving it on to be safe, it does no harm.

### CODE REVIEW

**Comment by gilderoylockhart01** [comment]
Ok so things are kind of.... weird as hell. The dma busy gamefix was made for SPR problematic cases right? Why did it fix IPU DMA related problems then?

**Comment by refractionpcsx2** [comment]
It wasn't made for SPR at all, it was made for any DMA.

**Comment by gilderoylockhart01** [comment]
Ahh ok then. Still, I will test Phase paradox to see if it's libdma errors are a thing of the past.

**Comment by gilderoylockhart01** [comment]
And we have one more winner: Phase Paradox IPU DMA problems are a thing of the past!

https://user-images.githubusercontent.com/90222976/146440768-d2f4decc-155c-41a6-842b-af592be00177.mp4

Closes: https://github.com/PCSX2/pcsx2/issues/4063

**Comment by refractionpcsx2** [comment]
Did you grab a build after 9am GMT today? I did make some changes :)

**Comment by gilderoylockhart01** [comment]
Yeah I did grab the very latest build after you did the last changes. Btw I also tested Myst III, but no luck with this one, I guess I will finish with MotoGP 3, I am confident about this one.

**Comment by gilderoylockhart01** [comment]
Haha, knew it, MotoGP 3 is also fixed:

https://user-images.githubusercontent.com/90222976/146447022-4cc3f9be-1670-4d76-914e-2ee638932903.mp4

Closes: https://github.com/PCSX2/pcsx2/issues/3708

**Comment by refractionpcsx2** [comment]
wow, nice, didn't expect that one

**Comment by refractionpcsx2** [comment]
Okay I'm removing Phase Paradox and Moto GP3 from the fixed list, Moto GP3 still doesn't; work (just tried it myself) and Phase Paradox was fixed ages ago, according to Prafull.

**Comment by gilderoylockhart01** [comment]
I will test the other movies on the menu when I will be back home.

**Comment by prafullpcsx2** [comment]
If you read the original motogp3 issue, movies were never bugged. It's the bonus photos that you unlock in challenge mode are bugged.

**Comment by gilderoylockhart01** [comment]
Yeah, you are right, I actually triggered the problem when watching photos.

**Comment by gilderoylockhart01** [comment]
Phase Paradox is unfortunately now broken again on your PR.

**Comment by refractionpcsx2** [comment]
Can I get a savestate and blockdump (maybe from the previous version if you still have it)

**Comment by gilderoylockhart01** [comment]
You are lucky, I still have the savestate taken with the previous build, here it is with the blockdump: https://drive.google.com/file/d/1h76fG4nm70izo0per3CNHl5b3GqDxZsh/view?usp=sharing

**Comment by refractionpcsx2** [comment]
This actually became more of a change than I was expecting but ended up improving the billboards in test drive, so it'd be good if people could give this a good test on things

**Comment by refractionpcsx2** [comment]
I made some more tidy up/tweak changes in behaviour, Tekken 4 now actually shows a frame or two of the video it just hung on before, but it still hangs, we just get further.

**Comment by gilderoylockhart01** [comment]
Yeah, there should be plenty of patches for that kind of problem right?

As for Myst 3 and motogp3, nope, still as bad.

**Comment by refractionpcsx2** [comment]
There's not as many patches as you'd think.

Yeah the list of fixes is nice, but it's not quite as extreme as I was hoping it was evolving to, maybe I need to revisit this later.

**Comment by gilderoylockhart01** [comment]
To be frank with you it's been a while since I looked at the GameDB. But yeah, a lot of them were removed from what I can see.

But, well, with this PR it's fine as is. I would sugest revisiting this after we got a proper vif fifo because that can be misleading in games like David Beckham Soccer for example.

**Comment by refractionpcsx2** [comment]
added some more fixes and tidied up a bunch of DMA code, added about another 3 games to the fix list as a result :)

Unfortunately the usual suspects are still broken

**Comment by gilderoylockhart01** [comment]
Mmm, I know of a "Prafull" guy which will be happy playing Flipnic not just for testing, but for real ^^.

**Comment by gilderoylockhart01** [comment]
Might be worth to check those 3 games as well:

WRC 3
Animation Battle - Recca no Honou
Growlanser Generations

As for Myst 3, nope, still bad, wtf did presto when doing this one.

**Comment by refractionpcsx2** [comment]
Growlanser is still broken
Dunno Animation Battle
WRC 3 Prafull said is 99% fixed although needed testing but that was yesterday, it might be all good now? I dunno.

**Comment by kenshen112** [comment]
> Might be worth to check those 3 games as well:
> 
> WRC 3
> Animation Battle - Recca no Honou
> Growlanser Generations
> 
> As for Myst 3, nope, still bad, wtf did presto when doing this one.

Myst 3 is known to be generally broken. Last I'd heard they couldn't really fix it for so e technical timing reason so there was a patch made a while back iirc

**Comment by refractionpcsx2** [comment]
Tekken 4 now works without a patch, the behaviour is strange, IDEC doesn't actually finish, but the game kills the command based on IPU_FROM DMA finishing, instead of the command not being busy anymore, but it's expecting a certain amount of data to be left otherwise it hangs.

**Comment by RedDevilus** [comment]
Tekken 4 (demo) works fine too

image
image

Merry Christmas X_X

**Comment by gilderoylockhart01** [comment]
Fixes Call Of Duty World at War final fronts IPU hanging problem: https://github.com/PCSX2/pcsx2/issues/5205

**Pull request merged**
