### PR TITLE
GSDumpGui: Automatically find the next free TCP port by setting requested port to 0

### PR DESCRIPTION
**Pull request by willkuer**
Fixes multiinstance crash as now every instance has its own port

### CODE REVIEW

**Comment by willkuer** [comment]
fixes multi instance crash reported in #1637

**Comment by willkuer** [comment]
Ok now it works. GsDumpGui handles multiple windows by via launching itsself several times and communicating between each instance via TCP instead of launching multiple windows in the same process. Honestly this is in some sense amazing and I wonder what the intention was.

It used a static port (9999) before but now will use the next free port the OS yields. This needs to be communicated to the clients and hence command line args needed to be touched.

**Comment by lightningterror** [comment]
Gave it a test and works as expected, both crashes when launching multiple instances or copy pasting a new exe have been resolved.

Are there any other pending changes or it's ready for merge?

**Comment by willkuer** [comment]
Done from my point of view.

Except you’d like to see the whole TCP/interprocess communication part removed. I really don’t get why it was done like that. Maybe to save the main gui in case the gs dump in the client crashes? Still it’s a questionable design. I don’t see it in the scope of this pr though.

**Comment by lightningterror** [comment]
Yeah higher priority are the crashes, improving the functionality can be done later.

**Pull request merged**
