### PR TITLE
Config: Add separate VU0/VU1 round/clamp mode options

### LINKED ISSUE #5188: [Feature Request]: Per-component Rounding/Clamping setting.
### Description

Currently, in PCSX2 we have 2 grouped categories, EE/IOP and VUs. When applying a rounding or clamping fix, this will affect all the components inside that group.

This approach is fine for the vast majority of games, but, a very few cases will break that approach.

Kung Fu Panda and Hardware Online Arena are 2 very good exemple of this. They will booth require 2 different settings on each VU. Which means PCSX2 will never be able to play those games properly in it's current form.

The request is pretty straight forward, being able to adjust clamping and rounding on a per-component basis so we can cover every cases.

I guess this is more of a 2.0 release request since I would imagine having QT would massively simplify such a request.

Could also do per address settings for specific parts of a program which require clamping/rounding.

### Reason

Increasing compatibility. In the current state of PCSX2 this can represent one important factor.

### Examples

Official Sony's emulator.

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

As discussed in #7241.

~Untested apart from checking the config loads as expected. Not complete, the big picture UI hasn't been updated, nor have the ints for clamping.~

~Also has no gamedb support yet.~

Note that when testing you'll probably want to disable game fixes (also in the advanced tab), to stop the existing gamedb overriding it (if any). Confirm in the console/log that the correct settings are being applied.

### Rationale behind Changes

#7241.

### Suggested Testing Steps

None at the moment.

Closes #5188

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
It looks like Setting VU1 RoundMode to Nearest is enough to fix the wheels in Destruction Derby Arenas without the tyres randomly changing shape, nice! :)

**Comment by refractionpcsx2** [comment]
Could be worth revisting Hitman Contracts, regarding #5719

**Comment by kakashi314** [comment]
Most of the games will only require VU1 clamping/rounding.

**Comment by refractionpcsx2** [comment]
Possibly yes, but for GameDB entries, I would recommend assuming both, unless otherwise required, or that's going to need so much testing to find out what needs what, and I don't think it's really worth the time.  But of course any games which have issues with the current round modes, or couldn't use them because of issues should be revisited.

**Comment by SlyCooperReloadCoded** [comment]
This most likely fix the Sly 3 bug without breaking shadows, just set VU0 clamping to Extra + Preserve Sign, either that or due to the randomness of the bug, I got lucky 30 level loads in a row.  Nah, this is the fix, it's gotta be, and shadows are fine.  Very good!

**Comment by SlyCooperReloadCoded** [comment]
Question, that one Ratchet and Clank mine glove bug, I don't play that game but wasn't that a VU issue?  Could be worth looking into, that is a very long-standing bug.

**Comment by kakashi314** [comment]
> Question, that one Ratchet and Clank mine glove bug, I don't play that game but wasn't that a VU issue? Could be worth looking into, that is a very long-standing bug.

The way i identify Which vector unit is responsible. is to guess whether it's visual (vu1) or game breaking (vu0).

**Comment by kakashi314** [comment]
> Question, that one Ratchet and Clank mine glove bug, I don't play that game but wasn't that a VU issue? Could be worth looking into, that is a very long-standing bug.

Most likely a VU0 issue.

**Comment by JanLeonard** [comment]
> Question, that one Ratchet and Clank mine glove bug, I don't play that game but wasn't that a VU issue? Could be worth looking into, that is a very long-standing bug.

this one are you refferring to? #354

**Comment by SlyCooperReloadCoded** [comment]
That looks like the one.  I see VU mentioned in there.  Yikes it's that old of an issue?  Hopefully this fixes that.

**Comment by stenzek** [comment]
FSUI/gamedb stuff added, good to go.

**Pull request merged**
