### PR TITLE
Implement rumble and isolate SDL code path

### PR DESCRIPTION
**Pull request by 3kinox**
@gregory38 
Okay, clean version of previous PR. Indent are fixed, Everything is in separated commits, change some not so clean change I did to be cleaner. The only redundant stuff that is left is to make sure that every commits compile while keeping each commits coherent.(emptying the DoHapticEffect before time).
SDL is also isolated in its own little class now so that I can proceed to make evdev backend.
Commits contains roughly the same thing as before otherwise. Sorry I closed previous one, I thought I could reopen it... But it is not possible after a force push. I will remember that one.
For GUI, it will be another PR(and according to all logic, not by me as I may contribute there too(since he is 3 meters away) but I am not the one who did the dev.
As for me, I will focus on implementing evdev backend for now.
Sorry for disturbance again, and don't kill yourself over mesa ;)

### CODE REVIEW

**Comment by gregory38** [comment]
It is much better, isn't it? :+1: 

I will try to do a deep review either today or tomorrow.

**Comment by 3kinox** [comment]
OK, I am on it for all corrections, will let you know when I am done. Shouldn't take too long.

**Comment by 3kinox** [comment]
@gregory38 
OK rebase and force push done. ~sleepy me now~

**Comment by gregory38** [comment]
```
Same time(and before I forget), I see that sixaxis_usb has no effect whatsoever for my sixaxis, is it to be expected?
```
It is a complex issue that depends on various device permission/SDL version/udev version.

**Comment by 3kinox** [comment]
@gregory38 
Ok, DONE.

**Comment by gregory38** [comment]
It seem good for me. I added some minor comments. How much did you test it? both SDL?

**Comment by 3kinox** [comment]
I will do modif then. I played a long streak on KH1 & DMC3. Played a little FFXII too. Yep, tested both. SDL1 was broken from begining for me though... I can't get my sixaxis to work properly.. Even with latest commits. After, shoegazer and another guy on issue tested too. Flat made too. So we got it covered i I guess. As said on forum, total overdrive just don't rumble, but as said I do guess it's not related to onepad, more likely core.

**Comment by 3kinox** [comment]
OK, last modifs you asked are done! I just fix the function.

**Comment by gregory38** [comment]
Ok perferct. For the comment the idea is to use a tag and a short summary. But it isn't critical (it would be for future contribution).
Nice jobs :+1:

**Comment by 3kinox** [comment]
Cool, on to evdev then! ;)

**Comment by gregory38** [comment]
by the way, try to build you code with clang, it will report several warnings. (./build.sh --clang)

**Comment by 3kinox** [comment]
I only got  key_status->press(cpad, i, min(-value /128, 0xFF)); which is not really mine

**Comment by gregory38** [comment]
From coverity but I spoted it with clang too. (granted that clang is quite a spammy compiler)
```
  void set_ff_intensity(u32 new_intensity)
117        {
   CID 152836 (#1 of 1): Unsigned compared against 0 (NO_EFFECT)unsigned_compare: This greater-than-or-equal-to-zero comparison of an unsigned value is always true. new_intensity >= 0U.
````

**Comment by 3kinox** [comment]
OK, I will fix. Basically my check is just useless right?;) Yep, that it is. Spammy like crazy, btw, pcsx2 can now build with it?

**Comment by gregory38** [comment]
I even manage to start a game ;) However it could crash later due to potential alignment issue. Code greatly improves those past months. Coverity also detected a big bug in the interpreter. Potentially it can boot more games ^^

**Comment by 3kinox** [comment]
OK great. We need full accurate interpreter to make new translator. C'est la base. New GUI is comming, I will merge on my fork, correct and then make the PR myself(he does not now how to do it lalala. You make him afraid when you review me too ;) )

**Comment by gregory38** [comment]
Yes you can quote me on that... There is another nasty issue in the recompiler that might worth a look. Currently if you build with omit frame pointer you have some crashes. Address sanitizer reports some badly aligned stack. It could be linked. I'm afraid that it could impact other ABI.
I think I will open a dev thread on the recompiler stuff to gather general info. Qemu link was interesting :)

I would really prefer that your co worker pushes his work. It is important for the copyright ownership. Beside I'm not a "vieux barbon" :p  I think it is normal to discuss a patch. You need to defend your work ;)

**Comment by 3kinox** [comment]
I will try to look into issue in recomp if you wish, but last time I looked my head hurt for 3 weeks. I can give you mails to ping if you want some more info, if you can think of anything to make pcsx2 somehow "deliverable" maybe I can even get other people to work haha. Though I doubt we'd be able to sell that ;)
OK. He is on it. I make him fix stuff. there are strange issue with keyboard where I can not help. He is on it. I told him to push by himself after ;) he said "maybe tonight".
I do research on evdev too. i read code from dolphin already. I will try to read directly SDL source code too.

**Comment by gregory38** [comment]
Ok. Priority is 1.4. Recomp crazyness will be for much later ;)
For evdev, you can also look at lilypad code. It was only a first trial and it uses ioctl directly (I wasn't aware of the nice wrapper lib). Normally it isn't complicated.

**Comment by gregory38** [comment]
(Stupid phone). Good news for the gui. Don't hesitate to push a preliminary version. Maybe the review can spot some issues.

**Comment by 3kinox** [comment]
OK, I told him, seems he just managed to solved most of it(he said it was smthg supid in fact).
Ok, will look there too. At the same time I try to wonder how the hell I can get my student to pass their exam with some kind of correct grade...

**Comment by gregory38** [comment]
Perfect. And good luck with your students ;)

**Pull request merged**
