### PR TITLE
DebugTools: Fix iterator invalidation bug in IopBios.cpp

### PR DESCRIPTION
**Pull request by chaoticgd**
### Description of Changes
An iterator invalidation bug in R3000A::loadcore::ReleaseFuncs has been fixed. My [symbol table PR](https://github.com/PCSX2/pcsx2/pull/10224) introduced it.

### Rationale behind Changes
Crashing is bad (except if it's Burnout).

### Suggested Testing Steps
N/A

### CODE REVIEW

**Review by TheLastRar — APPROVED** [review]
Fixes the crash I experienced

**Comment by lightningterror** [comment]
While you're at it can you also fix the new compiler warnings that got introduced in https://github.com/PCSX2/pcsx2/pull/11755https://github.com/PCSX2/pcsx2/pull/10224 ?

**Review by F0bes — APPROVED** [review]
Fixed my reproduction of the crash

**Comment by chaoticgd** [comment]
> While you're at it can you also fix the new compiler warnings that got introduced in #10224 ?

Sure, I'll do that in a another PR now since this was merged.

**Pull request merged**
