### PR TITLE
GameDB: Add Mipmapping and Trilinear to Parappa the Rapper 2

### LINKED ISSUE #7922: [BUG]: PaRappa the Rapper 2 (NTSC-J/SCPS-15017) glitched(?) floor texture in stage 2 with non-Software Renderer
### Describe the Bug

Floor texture looks different in stage 2. (with non-Software Renderer)

wow

### Reproduction Steps

Enter the stage 2 with non-Software Renderer.

### Expected Behavior

shown above(the image).

### PCSX2 Revision

Nightly v1.7.3918

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Intel Core i5-8500 CPU 3.00GHz

### GPU

NVIDIA GeForce GTX 1050Ti

### GS Settings

Default.

### Emulation Settings

Default.

### GS Window Screenshots

_No response_

### Logs & Dumps

[PTR2_SCPS-15017_NonSW_Stage2_texture.zip](https://github.com/PCSX2/pcsx2/files/10463056/PTR2_SCPS-15017_NonSW_Stage2_texture.zip)

### PR DESCRIPTION
**Pull request by Oymat**
### Description of Changes
Adds Full mipmapping to parappa the rapper 2 to fix missing floor textures,
and Trilinear filtering to fix fog in certain levels Closes #7922

### Rationale behind Changes
It's how the game should look like normally.

### Suggested Testing Steps
Make sure it builds correctly. and that nothing more needs to be added.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Can you please do Full mipmapping (2) and Trilinear also, otherwise the fog in one of the other levels is incorrect also.

**Comment by refractionpcsx2** [comment]
Sorry one last thing, periods at the ends of comments please :)

Also add a comment to the trilinear to say "Fixes fog effect."  As shown below

Just full mips:
image

With Trilinear:
image

**Comment by Oymat** [comment]
i'll get it this time hold on

**Comment by refractionpcsx2** [comment]
perfect, thanks.

**Pull request merged**
