### PR TITLE
Deps: Update Flatpak dependencies

### PR DESCRIPTION
**Pull request by j8r**
### Description of Changes
Update Flatpak dependencies: Qt to 6.8, FFMPEG extension and libpcap.

### Rationale behind Changes
Up-to-date dependencies.

### Suggested Testing Steps
Successful build, install the PCSX2 flatpak and run it; I suppose.

### CODE REVIEW

**Comment by j8r** [comment]
The SDK is not available yet.

**Comment by j8r** [comment]
Runtime now available, rebuilding

**Comment by j8r** [comment]
So, I bumped from LLVM17 to LLVM18 since the former has no 24.08 version available.
I don't know if PCSX2 is tested and supposed to work well on LLVM18 though, we may hold up this PR until it is.

**Review by F0bes — APPROVED** [review]
LGTM. Just needs to be tested.

**Review by kamfretoz — APPROVED** [review]
LGTM

image

**Pull request merged**
