### PR TITLE
Appveyor: Drop vs2017 builds.

### PR DESCRIPTION
**Pull request by lightningterror**
It will cut compile time half.

### CODE REVIEW

**Comment by tadanokojin** [comment]
Hm rather than drop build, I think Li got pcsx2 in github actions. It should be faster than appveyor. Perhaps we should look into that instead?

**Comment by lightningterror** [comment]
Sounds like a plan, will leave this one open anyway, maybe a temporary improvement for appveyor till then?

**Comment by tadanokojin** [comment]
Yeah let's see what @turtleli thinks.

**Comment by turtleli** [comment]
IMO merging this PR means dropping support for compiling with VS2017, because we won't know when a commit or PR will break VS2017 compilation if we don't have a buildbot compiling with it.

Personally I would drop it because VS2019 community is free for open source anyway, so it shouldn't be too much of an issue for people to use it.

As for Actions - It's worth considering. I think it allows 20 concurrent jobs (free plan), and testing on my fork suggests that it's slightly faster per job.

**Comment by lightningterror** [comment]
Closing as it was discussed github actions will be a better alternative.

**Pull request closed without merging**
