### PR TITLE
gsdx sw: add extrathreads_height to control the quantity of pixels pr…

### PR DESCRIPTION
**Pull request by gregory38**
Value could range from 1 to 9. Default is 4 and it is potentially the
best option.  Feel free to test some values on your system, behavior
might depends on the core number and thread number

Value is exponential so 4 is 2 times more pixels than 3.

Small value increased thread overhead, big value increase wait/sync latency

### CODE REVIEW

**Comment by ramapcsx2** [comment]
Can you just merge this to master, so we can test it at leisure? :)

**Comment by refractionpcsx2** [comment]
> Can you just merge this to master, so we can test it at leisure? :)

just grab the appveyor builds :P

**Comment by ramapcsx2** [comment]
It's inconvenient still :p I'm asking because this is basically a no-op change and could just go onto master directly. We can test it whenever there's time / without going through appveyor or branches.

**Comment by gregory38** [comment]
Guys, you have the power to merge it :)

**Comment by gregory38** [comment]
Edit and by the way, I think 4 is the best value. But it could still be useful in future, if someone (or I) change thread managements.

**Pull request merged**
