### PR TITLE
PCSX2 GUI: Update of Russian Translation

### PR DESCRIPTION
**Pull request by teorex3**
Bugs and typos fixed. A small update to the translation.

### CODE REVIEW

**Comment by teorex3** [comment]
Later update #, fuzzy some lines are not ready yet

**Comment by RedDevilus** [comment]
Why is there no .mo version?

**Comment by teorex3** [comment]
Add .mo and update year, version

**Comment by lightningterror** [comment]
The following strings require translations, (EE Cyclerate, EE Cycle Skipping, FMV Aspect Ratio, Presets) tooltips.

Also check https://github.com/PCSX2/pcsx2/pull/3230#issuecomment-581320733
It also happens on Russian translations.

**Comment by teorex3** [comment]
> Also check [#3230 (comment)](https://github.com/PCSX2/pcsx2/pull/3230#issuecomment-581320733)
> It also happens on Russian translations.

_18h43m19s_001_

**Comment by teorex3** [comment]
These lines are not in the .po files. 

Enabling Recording Tools
New Input Recording
Current Frame
Power-On
Virtual Pad - Port 1
Virtual Pad - Port 2
PCSX2 Program Log

**Comment by lightningterror** [comment]
Still an issue, check string https://github.com/PCSX2/pcsx2/blob/53efc9da857640226d64110b427b27b5de152855/locales/ru_RU/pcsx2_Iconized.po#L198

**Comment by teorex3** [comment]
PCSX2
PCSX2 (2)

**Comment by teorex3** [comment]
@RedPanda4552 PO/POT/MO Localisation needs to be updated for the First time wizard to include the documentation changes.
can add missing lines too from: https://github.com/PCSX2/pcsx2/pull/3234#issuecomment-581505908

**Pull request merged**
