### PR TITLE
Merge Circuit: Improve offset detection of output circuit

### LINKED ISSUE #1389: GSDX-PCRTC: Blurry Images on FFXII
**Description**:
The entire rendered screen seems to ghost a few pixels to the left or right (this is easily seen around the character's legs) causing the whole screen to appear blurry.

ffxii

* **Last working build** : [v1.5.0-dev-786](http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.5.0-dev-786-g68eb377&platform=windows-x86)
* **Build to cause the issue** : [v1.5.0-dev-790](http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.5.0-dev-790-g60e0f3b&platform=windows-x86)

**GSDump**: **[download link](https://www.dropbox.com/s/dhn7zam59swu0cn/FFXII.rar?dl=0)**

### PR DESCRIPTION
**Pull request by ssakash**
**Summary of Changes**:

* Improve width offset detection of ouput circuits (Fixes #1389)

### CODE REVIEW

**Comment by FlatOutPS2** [comment]
Why did you close the other one instead of updating it?

**Comment by ssakash** [comment]
> Why did you close the other one instead of updating it?

I can't update an unknown repository  (AKA I screwed up my repo :P )

unk

**Comment by FlatOutPS2** [comment]
And all your other closed PR's as well I see. Isn't github great^^

**Comment by gregory38** [comment]
A summary of test status will be nice. My understanding is that a regressions are fixed, and no new regression? Is it correct?

**Comment by ssakash** [comment]
> My understanding is that a regressions are fixed, and no new regression? Is it correct?

Yes, currently that's the case and I see no possibilities for a regression. Though I still suggest to keep it open for 2-3 days before merging it. (Just to be on the safe side)

@FlatOutPS2 

I'll let you handle the regression testing ;)

**Comment by gregory38** [comment]
Ok. Looking at the change, it seems safe to merge.

**Pull request merged**
