### PR TITLE
GS-hw: Adjust Shadow of Rome crc hacks.

### PR DESCRIPTION
**Pull request by lightningterror**
### Description of Changes

GS-hw: Adjust Shadow of Rome crc hacks.
Remove some unneeded crc hacks while making leftover upscale only.
### Rationale behind Changes

Purge/adjust crc hacks, accuracy.
### Suggested Testing Steps

Test Shadow of Rome.

### CODE REVIEW

**Comment by lightningterror** [comment]
HPO Normal
image


HPO Special:
image

**Comment by refractionpcsx2** [comment]
Normal has fringing:

image


But Special has the cursed capcom lines

image

**Comment by lightningterror** [comment]
So both suck, here's a dump from the demo disc.
[Shadow of Rome [Demo] (NTSC-U)_SLUS-29139_20221005201236.zip](https://github.com/PCSX2/pcsx2/files/9717986/Shadow.of.Rome.Demo.NTSC-U._SLUS-29139_20221005201236.zip)

**Comment by refractionpcsx2** [comment]
yyyyup, it's a pick your poison, until somebody has a genius solution for that edge problem (the effect always starts at the edge then multiplies upward)

**Comment by refractionpcsx2** [comment]
as for the speed hack part of the CRC, the framerate halves without it.

**Comment by lightningterror** [comment]
Hm, then I'll adjust the crc hacks to only work when upscaling, and maybe cut off if some aren't needed.

> as for the speed hack part of the CRC, the framerate halves without it.
How much of a speed impact?

**Comment by refractionpcsx2** [comment]
Testing was done, the speed impact wasn't really enough to matter, unless you're on an absolute potato, in which case, upgrade time.

**Review by Mrlinkwii — APPROVED** [review]

**Comment by lightningterror** [comment]
Ok so this is the best outcome, removed unneeded crc hacks, while keeping the leftover upscale only.

**Pull request merged**
