### PR TITLE
Sio Phase 2.5 - Rewrite Pad Support + Add Guitar

### PR DESCRIPTION
**Pull request by RedPanda4552**
### Description of Changes
- Completely replaces all pad code. 
- Reimplements pad protocol as discrete functions, uses an abstract PadBase with each actual controller type as a subclass, each with an independent implementation of the protocol matching that type of pad. 
- Added guitars. 
- GT4 should now properly engage DS2 mode again, so axis triggers can be used for throttle/brake controls again. 
- Other games which may have failed to engage DS2 mode should now be able to.

### Rationale behind Changes
Old pad code was soup, had issues with DS2 mode. 

### Suggested Testing Steps
- Verify inputs all function as expected. 
- Check stick inversion working. 
- Check using pressure (triggers on modern controllers are axes not buttons, bind these to PS2 face buttons).
- Check guitar games working.
- Check macros working.
- Check settings retention between game restarts and full emulator restarts.

### To-Do
- ~~Un-scuff the guitar mapping image.~~
- TAS is undoubtably broken.
- Probably more things.

### Casualties of War
- ~~PS1 mode is inoperable, SIO0 is disconnected from the pads for now.~~

### CODE REVIEW

**Comment by Mrlinkwii** [comment]
Sky Odyssey left  Analog doesn't work on the PR

**Comment by seta-san** [comment]
How about true crimes Los Angeles. Does it still require second controller to be in?

**Comment by RedPanda4552** [comment]
> How about true crimes Los Angeles. Does it still require second controller to be in?

Yes. Best I can tell that is a SIF problem made happy by the additional pad data saturating the bus. Without the extra data it seems to trip over itself.

**Comment by Mrlinkwii** [comment]
Sky Odyssey is fixed Thanks :)

**Comment by TellowKrinkle** [comment]
Not sure why it causes crashes, but `PadBase` needs a virtual destructor and it's the reason the macOS unit tests are failing.

**Comment by RedPanda4552** [comment]
Virtual destructor added fixes Mac build, and fixed a couple regressions that popped up from rebase.

**Comment by RedPanda4552** [comment]
Requesting review for input recording - no clue if what I did will have broken it or not.

**Comment by kage2051** [comment]
> Requesting review for input recording - no clue if what I did will have broken it or not. If I understand it right, PadData.cpp is really the only thing affected and it seems okay? But I can't be 100% sure.

Regarding input recording, it seems they don't errate if starting from savestate right after loading any game (except for games where RTC is very sensitive). Every tests I've done with power-on always desync at the very first moment of actual gameplay. Though even with the 'from savestate' workaround there are moments where a desync will occur.

**Comment by RedPanda4552** [comment]
> > Requesting review for input recording - no clue if what I did will have broken it or not. If I understand it right, PadData.cpp is really the only thing affected and it seems okay? But I can't be 100% sure.
> 
> Regarding input recording, it seems they don't errate if starting from savestate right after loading any game (except for games where clock seed is very sensitive). Every tests I've done with power-on always desync at the very first moment of actual gameplay. Though even with the 'from savestate' workaround there are moments where a desync will occur.
> 
> Note that this issue is happening on the main dev builds.

Mildly interesting, but if the behavior is consistent with the actual nightly releases, that means my changes didn't break anything... I think... It sounds more like input recording just isn't quite working right to begin with at this time?

**Comment by kage2051** [comment]
> Mildly interesting, but if the behavior is consistent with the actual nightly releases, that means my changes didn't break anything... I think... It sounds more like input recording just isn't quite working right to begin with at this time?

I think it has to do with CDVD timing discrepancy between playbacks. This also affects recordings from savestate but they are much less frequent.

**Comment by RedPanda4552** [comment]
Git has made it very clear that it wants this branch to be ruined, that is twice now that it has succeeded in destroying the commits. I will try to salvage at a later time.

Also to-do: Fix duplicate includes on a bunch of files, because, surprise, Git can't handle a rebase without adding a hundred garbage merge conflicts.

**Comment by CookiePLMonster** [comment]
Fixes triggers and the directional analog in [Le Mans 24 Hours](https://wiki.pcsx2.net/Le_Mans_24_Hours) - triggers are now pressure sensitive and the analog actually works.

**Review by Mrlinkwii — APPROVED** [review]

**Comment by tuantquy** [comment]
Macro doesn't work after this update with GOW 2. It requires me to spam the assigned buttons for macros now instead of pressing it down like usual.

https://github.com/PCSX2/pcsx2/assets/138451202/05af1341-370b-478f-a385-64db69af1203

**Comment by IlDucci** [comment]
Just seen this commit in Crowdin and the "Analog light is now {} for port {} / slot {}" string at pcsx2/SIO/Pad/PadDualshock2.cpp:644 needs two custom "On"/"Off" strings so non-English languages can match the gender/number of "Analog light".

**Pull request merged**
