### PR TITLE
3rd party: Update glew and other GL headers to latest version.

### PR DESCRIPTION
**Pull request by ssakash**
I think I'll also merge the plans for the single predefined macro _WIN32 for consistency along with this PR until then, don't merge it yet.

### CODE REVIEW

**Comment by gregory38** [comment]
1/ It only impacts the windows build
2/ It is useless because new defines are already include directly in GLLoader.h (to keep compatibility with linux)

**Comment by refractionpcsx2** [comment]
@gregory38 fair enough :) no point in these files even being in there any more then... I assigned it to you merely so you could check it :)

**Comment by refractionpcsx2** [comment]
Why is your OI_SuperManReturns change in this PR? :P

**Comment by ssakash** [comment]
To prevent merge conflicts.

**Comment by ssakash** [comment]
I have finalized the changes done on the  PR, if anyone wants to give it a ride get the compiled build from here - https://www.dropbox.com/s/kpi08eom34u4d12/PCSX2%20patch26.7z?dl=0

**Comment by gregory38** [comment]
to avoid merge conflict, the best is to create a local branch and to push a branch. It is much easier for everybody.

**Comment by turtleli** [comment]
The glew library is missing from 3rdparty, so there isn't really a point in having glew.h, wglew.h and glxew.h. glxew.h is also not for Windows as well. I suggest that you delete the glew files.

Where did you get wglext.h from? The version at https://www.opengl.org/registry/ is much newer.

**Comment by gregory38** [comment]
Hum, you're right GLEW is only used on ZZogl Linux.

**Comment by ssakash** [comment]
I'll rebase the changes then. :)

**Comment by ssakash** [comment]
@turtleli 

you mentioned glxew.h twice , I guess you meant glext.h ?

**Comment by turtleli** [comment]
No. glext.h isn't part of GLEW.

**Comment by ssakash** [comment]
Yeah, That's right.  I was just curious on why you mentioned it twice.

**Comment by ssakash** [comment]
new one : https://github.com/PCSX2/pcsx2/pull/641

**Pull request closed without merging**
