### PR TITLE
Update .gitignore file.

### PR DESCRIPTION
**Pull request by micove**
Hello:

 - portaudio line not needed and ignored vcxproj/props/etc.
 - update to the new rcdefs.h location

Remaining issues:
```
$ git status --ignored
Ignored files:
 3rdparty/libjpeg/change.log
 3rdparty/portaudio/config.guess
 3rdparty/portaudio/config.sub
 bin/Langs/
 bin/PCSX2-linux.sh
 bin/PCSX2_keys.ini.default
 pcsx2/IPU/yuv2rgb.asm
 pcsx2/gui/Resources/EmbeddedImage.h
 pcsx2/x86/ix86-32/aVif_proc-32.asm
 plugins/CDVDiso/src/mkiso/mkiso.dsp
 plugins/CDVDiso/src/mkiso/mkiso.dsw
 plugins/CDVDpeops/i386.asm
 plugins/dev9ghzdrk/Win32/postBuild.cmd
 plugins/zerogs/dx/x86-32.asm
 plugins/zerogs/dx/x86-64.asm
 plugins/zerogs/opengl/x86-32.asm
 plugins/zzogl-pg/opengl/x86-32.asm
```
These are set to be ignored but are inside the repository.

On a case by case basis they  could be either deleted or excluded from the .gitignore file.

Going from memory the offending lines are
```
*.log                    # add !/3rdparty/libjpeg/change.log. I would use libjpeg-turbo.
*.mo                     # ignores bin/Langs/
/bin/pcsx2*              # windows is not case-sensitive. This line does nothing
*.asm                    # ignores the .asm as expected
/pcsx2/gui/Resources/*.h # if needed add !/pcsx2/gui/Resources/EmbeddedImage.h
```

The .guess/.sub/dsp/dsw could probably be deleted. I have not checked if the postBuild.cmd is needed.

### CODE REVIEW

**Comment by gregory38** [comment]
*.log, ok.

*.mo done on purpose. Those files used to populate my env. Not sure it is still needed.

/bin/pcsx2*. Done for linux to avoid issue with replayer and exe. Ofc, I renamed the exe as PCSX2 so it doesn't fully work anymore.

*.asm . Oups, better add exception for this one. I often various stuff in .asm format. I didn't check that db already contains some file.

Ok for the resources.

**Comment by micove** [comment]
You want to fix them yourself? It's probably easier that way.

From what I understood you want me to add:
```
!/3rdparty/libjpeg/change.log
!/pcsx2/gui/Resources/EmbeddedImage.h
!/pcsx2/IPU/yuv2rgb.asm
!/pcsx2/x86/ix86-32/aVif_proc-32.asm
!/plugins/CDVDpeops/i386.asm
!/plugins/zerogs/dx/x86-32.asm
!/plugins/zerogs/dx/x86-64.asm
!/plugins/zerogs/opengl/x86-32.asm
!/plugins/zzogl-pg/opengl/x86-32.asm
```
and 
maybe remove
```
/bin/pcsx2*
```

Not sure about the *.mo either but it can be left as is.


These files can be removed from the repo (postBuild.cmd always get regenerated).
```
3rdparty/portaudio/config.guess
3rdparty/portaudio/config.sub
plugins/CDVDiso/src/mkiso/mkiso.dsp
plugins/CDVDiso/src/mkiso/mkiso.dsw
plugins/dev9ghzdrk/Win32/postBuild.cmd
```

**Comment by gregory38** [comment]
Feel free to enhance your PR :+1:

**Comment by micove** [comment]
Okay so, I might as well compile it on Linux and see for myself what the issues there are.

I did a regular build using
 - dpkg-buildpackage with ReplayLoaders enabled.
 - ./build.sh --release -DBUILD_REPLAY_LOADERS=TRUE -DCMAKE_BUILD_PO=TRUE

This should test the cases where PackageMode is true and false so I get where all the files go in most cases.

With the new changes it's down to this:
```
Ignored files:
  (use "git add -f <file>..." to include in what will be committed)

	3rdparty/portaudio/config.guess
	3rdparty/portaudio/config.sub
	plugins/CDVDiso/src/mkiso/mkiso.dsp
	plugins/CDVDiso/src/mkiso/mkiso.dsw
```
These can probably be deleted but i left them there.

The only issue with .mo files I saw was that if I used -DCMAKE_BUILD_PO=TRUE with build.sh it updated them. The default is FALSE.

Note: The replay loader is still lower case as in pcsx2_GSReplayLoader.

**Comment by turtleli** [comment]
I think:
 * `/pcsx2/gui/Resources/Thumbs.db` line can be deleted since `Thumbs.db` takes care of that already.
 *  `*.aps` should be added and plugins/USBqemu/Win32/USBqemu.aps should be deleted - those are compiled *.rc files used by the Resource editor for quick loading.

**Comment by micove** [comment]
Oh, thanks!

I never checked for duplication in the .gitignore but it's true and "/pcsx2/gui/Resources/Thumbs.db" should be removed.

There are so many things that I want to remove but I don't since in general it makes the PR take longer to merge. My OCD makes me cry a little inside when I see cruft. I will check the asp file when I reboot into Windows later. Also, I never checked the x64 windows build but hopefully there is nothing there.

**Comment by micove** [comment]
Okay, I incorporated the changes suggested by turtleli and collapsed a bunch of lines using '**' since it's silly to keep adding Win32/x64 every time a new plugin or dependency gets added. I'm practically done since the only thing left is:
```
$ git status --ignored
Ignored files:
 plugins/CDVDiso/src/mkiso/mkiso.dsp
 plugins/CDVDiso/src/mkiso/mkiso.dsw
```
Someone else can delete that cruft.

**Comment by turtleli** [comment]
Works well for me on both Windows and Linux.

**Comment by micove** [comment]
@gregory38 

Anything else that needs fixing? I just rebased this due to the change in the .gitignore so might as well ask. No rush :).

Also, I ran PCSX2 under valgrind to see the cause of the gcc-5.2 segfault I reported a few days ago and it did not segfault. I will look at it later since valgrind complained too much.

**Comment by avih** [comment]
Oops, I didn't recall there's a pending `.gitignore` PR... sorry :)

**Comment by micove** [comment]
Ah, it's fine. You missed the x64 variant of the rcdefs.h but that one is rarely used.

I just did
/3rdparty/**/wx/msw/rcdefs.h

to get both.

**Comment by avih** [comment]
Yes, i just checked the patch ;) thx

**Comment by gregory38** [comment]
I just want to replace *.asm.
by
```
*.asm
! list of asm file
```
Otherwise it will be a nightmare each time I dump a thousand of shaders.

**Comment by micove** [comment]
Oh, okay. I have the list already. Give me a minute or two.

**Comment by micove** [comment]
Done and confirmed that still
```
Ignored files:
        plugins/CDVDiso/src/mkiso/mkiso.dsp
        plugins/CDVDiso/src/mkiso/mkiso.dsw
```

**Comment by gregory38** [comment]
Thanks.

**Pull request merged**
