### PR TITLE
Add Accurate Frame Buffer mask for Windows [GUI] and remove some old options.

### PR DESCRIPTION
**Pull request by ssakash**

### CODE REVIEW

**Comment by turtleli** [comment]
Err... anisotropic box
overlap

**Comment by ssakash** [comment]
oops, looks like I forgot to increment the X of the combo box by 16. Will rebase it properly when I get on to my PC. ;)

**Comment by ssakash** [comment]
updated, It should be fine now.

**Comment by refractionpcsx2** [comment]
You seem to have put some is_open2 stuff back in

**Comment by ssakash** [comment]
I haven't removed those variables yet, I left it as it is for the mean time since other functions were dependent on those and removal will end up in causing some errors. I will remove those is_open variables cleanly in another PR.

**Comment by ssakash** [comment]
though I have removed some old GUI options like windowed mode, Aspect ratio and other stuffs which were being used in the Old GUI. :)

**Comment by refractionpcsx2** [comment]
The reason I say that is because you had removed it in your previous commit, then it went back in with that one :p

**Comment by ssakash** [comment]
yeah, That's confusing :p , I will squash it !

**Comment by ssakash** [comment]
okay, squashed those two commits. now you can review it easier :)

**Comment by turtleli** [comment]
Windows GSdx GUI - I think the "Hardware Mode Settings" group box needs extending to include up to anisotropic filtering. Also, perhaps change "Accurate color clip" to "Accurate Color Clip" for consistency?

Removing the F9 statement  -  You should remove the stored_renderswitch stuff as well. The "Current Renderer: whatever" messages only appear on Windows by the way. You can't see them on Linux.

Removing old config dialog stuff - I'm pretty sure I showed you turtleli@07a03b47a95b83482e978ffcd179f2fa034a044b as a reference?

**Comment by ssakash** [comment]
@turtleli 

You mentioned about that commit before and I had tried deprecating some of those mentioned variables and had errors since they were needed for some other specific functions though, I don't really want to mess up this PR with removal of old variables, maybe you could deprecate those vars when you are splitting those GPU file so it would be appropriate with the PR ?

also . could you check whether the Group box is implemented correctly now ?

**Comment by turtleli** [comment]
Weird.

```
git checkout master
git checkout -b remove-old-config
git format-patch --stdout -1 07a03b4 | git am -3
```
Fix merge conflict.
```
git add plugins/GSdx/GS.cpp
git am --continue
```
Compiles and works fine. PSX stuff still intact.

Groupbox seems fine. By the way, deprecate and remove mean different things.

**Comment by ssakash** [comment]
@turtleli 
Removed those is_gsopen stuffs, could you check out whether it causes any issues ?

**Comment by turtleli** [comment]
PSX stuff works just as badly as it did before, so no changes there. PS2 stuff looks fine to me, but I only did brief checks. Should be ok though.

P.S. Deprecate and remove really do have different meanings.

**Comment by ssakash** [comment]
From my understanding,  Deprecate could be used when a better alternative is used instead of the current function, Since the new dialog is used instead of the old one.

Well,  I do randomly use deprecate instead of remove at most situations, my literary skills suck :p

**Comment by gregory38** [comment]
Honestly I would prefer if you move the GSopen1 gui removal from the first commit to the last commit. Please learn to use branch properly.

To split the commit
1/ rebase and set edit flag to the fisrt commit
2/ uncommit: git reset --soft HEAD~1
3/ unstage: git  reset HEAD --
4/ select the fbmask stuff with git add -p
5/ commit
6/ redo a commit with remaining file
7/ git rebase --continue

Then rebase and sort the commit to squash gsopen stuff.

**Comment by ssakash** [comment]
done :+1: 

I squashed removal of old GSdx plugin dialog and removal of is_gsopen stuffs into a single commit since they seemed relevant. also, added some typo fixes on the commit and placed the IDC define for accurate FB mask.

though the other stuffs relevant to accurate_fbmask have been separated into a different commit.

**Comment by gregory38** [comment]
Did you try to run this new build with an old PCSX2 version? I'm afraid of the removal of PS2EsetEmuVersion

**Comment by turtleli** [comment]
PS2EsetEmuVersion was added for PCSX2 0.9.7 (9fa4944). So it should work fine for any version after that.

**Comment by ssakash** [comment]
I don't really think anyone would try this with such a old version.

**Comment by gregory38** [comment]
To search regression. I think it will be fine. Let's merge it so I can later merge a code that merge all those blending accurate option :)

**Comment by avih** [comment]
@ssakash, you usually add a comma after the word "since", e.g.:
`remove stored_renderswitch since, console message is no longer needed.`

While I'm not a native English speaker myself, I don't think there's ever a case where the word "since" is followed by a comma. Even if there is, it _appears_ to me that most of the time you get it wrong. In general, you shouldn't add a comma after the word "since". FYI.

**Comment by refractionpcsx2** [comment]
I don't think a comma was required, however if you were to use one, it would make more sense after "stored_renderswitch" as this is where you are more likely to pause when saying that sentence.

**Comment by gregory38** [comment]
@refractionpcsx2 we need you on IRC ;)

**Comment by ssakash** [comment]
@avih  @refractionpcsx2  : Thanks for the Information.

**Pull request merged**
