### PR TITLE
Qt: Implement proper data directory selection

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Makes PCSX2-Qt follow the same data directory selection as the wx interface, i.e. `Documents/PCSX2` for Windows, `~/.config/PCSX2` for Linux, and `~/Library/Application Support/PCSX2` for Macs (not sure if correct).

Of course, `portable.ini` will continue to override and use the program directory.

I don't want to bikeshed about whether things should go in `XDG_CONFIG_HOME` or `XDG_DATA_HOME`, I'm just making Qt the same as WX. If you want to argue to change it, you can do so with a follow-up PR ;)

### Rationale behind Changes

Consistency, making it easier to migrate to Qt.

### Suggested Testing Steps

Test Windows and Linux Qt in both portable and non portable mode (I've tested Windows).

### CODE REVIEW

**Comment by stenzek** [comment]
Tested on Linux, seems to work as expected. Although on my system I didn't have `$XDG_CONFIG_HOME` available.

**Comment by j8r** [comment]
No that looks good as is, thanks @stenzek! The most important was to put at least in one of this standard locations.
Solves #5496 and #5599.

**Comment by j8r** [comment]
Most is working well, but I noticed one thing about the `resources` directory in [Flatpak](https://github.com/flathub/net.pcsx2.PCSX2/pull/46), and maybe just Linux in general: `pcsx2` read them at `/app/share/PCSX2/resources` - which were installed there by CMake. However `pcsx2-qt` read them at `/app/bin/resources`, so I have to create a symlink.

I looked at `QtHost.cpp` and `AppConfig.cpp`, but I wasn't able to figure out the logic where Wx Widget sets the directory to `/app/share/PCSX2/resources`.

In both cases, with or without `-DQT_BUILD=TRUE`, CMake install the resources to `/app/share/PCSX2/resources`: `-- Installing: /app/share/PCSX2/resources/`.

The fixes are either:
- install the resources where the binary is when `-DQT_BUILD`
- or better, make the Qt binary read `/app/share/PCSX2/resources`, like the Wx Widget one

**Comment by j8r** [comment]
Where did you find that this package is officially supported by you? From my point of view there is no such statement in the package. Usually people open issues in the dedicated repository, then us packagers communicate there - at least that's what we aim for.

I just wanted to know if it was supposed to work this way or if it was a Linux regression, since the behavior has changed from wxWidget to Qt.

Thanks to have clarified this, it is indeed supposes to work like done in my fix: place the resources directory alongside the binary.
So, logically, it could be done by CMake too.

**Comment by stenzek** [comment]
> Where did you find that this package is officially supported by you?

Because a little while back we had an influx of steam deck people whinging about things being broken, and it had nothing to do with us.

> since the behavior has changed from wxWidget to Qt.

Qt is not wx. Plenty of things are done differently, wx was absolute garbage in many ways and the idea never was to replicate it.

> So, logically, it could be done by CMake too.

Don't really see the need to do anything here tbh. "make install" will copy the binary to the in-tree bin directory, where the resources already are. Alternatively, for development, you can just symlink it into the build directory (which is what I usually do).

**Comment by j8r** [comment]
Thanks for the clarifications.
That's the risk, users not opening issues in the right place, and that's not always obvious to know if the bug comes from the application itself or caused by the packaging - even more in a sandboxed one.

I just noticed the issues link points currently to https://github.com/PCSX2/pcsx2/issues, I could change it to https://github.com/flathub/net.pcsx2.PCSX2/issues.
We could always redirect them here if the issue is an actual emulation problem, not a system one.

**Pull request merged**
