### PR TITLE
Gsdx direct depth sample

### PR DESCRIPTION
**Pull request by gregory38**
Revamp depth effect handling in GSdx ogl.

* Use integral coordinate => avoid downscaling of the depth buffer
* Use texture pointer => avoid extra texture allocation
* Support both 32 & 16 bits depth format

Need to be tested
* depth effect
* upscaling
* DX11 (because I'm nearly sure I broke it)

### CODE REVIEW

**Comment by Blackbird88** [comment]
You fixed #378!
image

**Comment by gregory38** [comment]
You mean the regression (black corner), isn't it?

**Comment by Blackbird88** [comment]
No. You fixed the whole bug. If you look at first post you will notice there were alpha issues

**Comment by gregory38** [comment]
Oh. It was a depth issue after all. Likely due to the 16 bit formats.

**Comment by Blackbird88** [comment]
It should also be noted that this didn't fix #600 so I was right they are separate issues.

**Comment by FlatOutPS2** [comment]
> It should also be noted that this didn't fix #600 so I was right they are separate issues.
That was a software mode issue, the other issue didn't even happen in software mode, so yeah.
Don't know if this was ever mentioned, but Battlefield 2 has exactly the same issue as #600 in software mode.

**Comment by Blackbird88** [comment]
#600 happens in both HW and SW.

**Comment by FlatOutPS2** [comment]
> #600 happens in both HW and SW

But the other issue was only in HW. Battlefield 2 might have the issue in HW too, but you can't tell because black bar that covers all but the very top of the screen.

**Comment by Blackbird88** [comment]
Oh I know what issue you mean. You mean the half screen in BF2:Modern Combat.

**Comment by FlatOutPS2** [comment]
> Oh I know what issue you mean. You mean the half screen in BF2:Modern Combat.
Not half screen, but almost whole screen issue. It's different from any half or quarter screen issue I've seen.

**Comment by FlatOutPS2** [comment]
The new plugin seems to crash PCSX2 whenever I try the enter the video plugin settings menu when a game is running(a 3D scene) with OpenGL.

**Comment by Blackbird88** [comment]
Seems to crash randomly when switching from HW to SW too?

**Comment by bositman** [comment]
Yeah I've reported it already, gregory is looking into it. Temp modified dll for you guys to test without the crashes:
bositman.pcsx2.net/dumps/GSdx-depth-blend-WIP.rar (SSE4)

**Comment by bositman** [comment]
@Blackbird88 FMVs flickering should not be related with this, but most probably with this: https://github.com/PCSX2/pcsx2/pull/1222 You should probably test a GSdx built before it was merged to confirm (it should happen in master too if I'm right)

**Comment by gregory38** [comment]
I know how to fix #600  on the HW renderer. But one step at a time. Need to fix all regression of the above code and previous change (FMV ...)

**Comment by Blackbird88** [comment]
@bositman 
I figured it might be separate issue but wasn't sure since I haven't tested the game in ages. (played it on PS3 since it works perfectly there)

**Comment by FlatOutPS2** [comment]
I can confirm this still fixes Silent Hill 4, but this time doesn't cause a regression in Crash Twinsanity & WRC II. Sadly doesn't solved the remain line at the edges of the effects in those games. Tried several other games, but doesn't resolve any further issues.  TOCA Race Driver 2 is still broken as well.

**Comment by FlatOutPS2** [comment]
I found another thing it solved; in DX9 & 11 HW vertical bars/lines were blocking most of the screen in WRC II(only to be removed with skipdraw), this PR removes the black bars and skipdraw is no longer necessary.

**Comment by gregory38** [comment]
Yes, it was expected a side effect. If the game requires a depth texture and we don't support the conversion, a NULL texture will be returned. Without texture, current draw will be skipped.

**Comment by Kristijan1001** [comment]
Yo how did you fix the gta issue with the map and subtitles ,i have no idea what i am looking, what am i suppose to do i have the last pcsx2 dev build 1988.Thanks a ton !

**Comment by Blackbird88** [comment]
You need to use latest GSdx and then just pick OpenGL HW. Not sure if D3D got this fix yet.

**Comment by Kristijan1001** [comment]
can u please point me to the right direction like a link or something ?

**Comment by Kristijan1001** [comment]
oh ok i see pick openGL in the emulator ,it works map is good now,but problem is i can't use shaders now is it possible for this to get fixed in D3D

**Comment by Blackbird88** [comment]
I'm not developer. You'd have to ask FlatOutPS2. He's only one porting stuff to D3D.

**Comment by Kristijan1001** [comment]
i have no idea who he is or how to contact him xD im pretty new i just stumbled on ur problem for gta then ended up here

**Comment by Kristijan1001** [comment]
ok i see who he is is there any way to message him or ill just tag him hope he sees @FlatOutPS2

**Comment by Kristijan1001** [comment]
i guess no one gaf about this anymore ? @FlatOutPS2

**Comment by MrCK1** [comment]
Please submit a bug report or make a thread in the forums. Asking here is not the place.

**Comment by Kristijan1001** [comment]
ok seems fair i did http://forums.pcsx2.net/Thread-Bug-Report-Grand-Theft-Auto-Vice-City-Stories?pid=557809#pid557809

**Pull request merged**
