### PR TITLE
gsdx-d3d11: ICO depth HLE

### PR DESCRIPTION
**Pull request by tadanokojin**
Port of the ICO HLE fix and update to fb copy on slot 4

### CODE REVIEW

**Comment by tadanokojin** [comment]
@gregory38 I updated with the following
- cache rt depth stencil ptr on `m_state` and update detection
- ternary for `CopyRect` box (and comment about DX api)
- throw error if copy isn't a RenderTarget/Depth
- remove curly braces
- rename `CopyRenderTarget` to `CopyTexture`

I also cleaned up a cast and the if statement for `DrawIndexPrimitive`

**Comment by gregory38** [comment]
Nice now you can split it in smaller commit ;)

**Comment by tadanokojin** [comment]
Split it up.

I also boldly added the assert ;)
Let me know if the changes are good.

**Comment by tadanokojin** [comment]
Also let me know if the pass by reference is okay.

**Comment by tadanokojin** [comment]
Updated

**Pull request merged**
