### PR TITLE
IPU: Combine source files to work around an LTO bug in clang 15

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Works around an LTO bug which seems to occur in clang 15, but not in clang 12. The entire else branch in the 0 case in get_non_intra_block() was being removed...

### Rationale behind Changes

Fixes Burnout 3 crashing in clang builds, probably others.

### Suggested Testing Steps

Get Jordan to try to crash burnout 3 in the same way he managed before. Enabling skip mpeg did it for me.

Test IPU sensitive games, make sure I didn't break anything.

### CODE REVIEW

**Comment by TerryJ82** [comment]
you cant use gpl code in lgpl licensed files without re-licensing the entire file as gpl

**Comment by RedDevilus** [comment]
> you cant use gpl code in lgpl licensed files without re-licensing the entire file as gpl

Where do you see LGPL licensed files with supposed GPL code not licensed as GPL?

**Comment by RedDevilus** [comment]
Then I suggest TerryJ82 (whoever you are) to read upon the correct ways you can use copyright and their respective licenses. As wrong enforcing can lead to unnecessary drama.

**Comment by refractionpcsx2** [comment]
There's several other projects you can adorn your nerd glasses and say "Ackchually you are violating the license" to and they actually are in a more more heinous way than we ever have, if you've come here just to try and find license violations to cause trouble, can you kindly go elsewhere and actually do it where it matters.

Thanks.

**Pull request merged**
