### PR TITLE
GS/HW: Fix preloading targets dirty update

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Avoids preloading data outside of the valid area

### Rationale behind Changes
Valkyrie profile 2 makes a new target with a width of 4 (this is 256 pixels), then only draws to 129x96, but the preload tries to put something next to it, which later causes a shuffle to fail because it thinks the target is dirty (even though it's not going to read it that area) and ends up drawing garbage.  Ideally we'd have perfect rect checking in our Lookup Source code, but they didn't use complete pages, so that kinda ruined my day.

### Suggested Testing Steps
Test valkyrie profile 2

Master:
image

PR:
image

### CODE REVIEW

**Comment by Alezuma** [comment]
@refractionpcsx2  Thank you from the bottom of my heart for the corrections. The terrible forest lines are only appearing now, as far as I have seen, in the first cutscenes in the background of the sky. See an example below:
Valkyrie Profile 2 - Silmeria_SLUS-21452_20240627223444


[Valkyrie Profile 2 - Silmeria_SLUS-21452_20240627223444.zip](https://github.com/user-attachments/files/16023030/Valkyrie.Profile.2.-.Silmeria_SLUS-21452_20240627223444.zip)


I recorded a small gameplay session (GS). Is it possible to correct these lines in the future?

**Comment by refractionpcsx2** [comment]
Someone said disabling native palette gets rid of them, I don't know if that's true or not... I guess I can check your dump tomorrow

**Comment by JordanTheToaster** [comment]
> Someone said disabling native palette gets rid of them, I don't know if that's true or not... I guess I can check your dump tomorrow

Already been removed by myself to fix this issue.

image

**Comment by Alezuma** [comment]
@refractionpcsx2 @JordanTheToaster Thank you, I couldn't fix it manually here, but I'll wait for future updates 😊

**Comment by JordanTheToaster** [comment]
> @refractionpcsx2 @JordanTheToaster Thank you, I couldn't fix it manually here, but I'll wait for future updates 😊

It's automatic you don't need to do anything your build is likely just out of date.

**Comment by Alezuma** [comment]
> > @refractionpcsx2 @JordanTheToaster Thank you, I couldn't fix it manually here, but I'll wait for future updates 😊
> 
> It's automatic you don't need to do anything your build is likely just out of date.

Strange, I am using PCSX2 v1.7.5940, and with the automatic correction settings, the lines appear for me in the first cutscenes. Would you like a save game from the area?

**Comment by Alezuma** [comment]
@JordanTheToaster @refractionpcsx2 I understand now, the lines only appear according to the resolution. I am using 3X (1080p) and @JordanTheToaster is using 8X (2880p/5K). Please Try changing the resolution to 3X (1080p) to see the lines in the cutscene.

**Pull request merged**
