### PR TITLE
GSdx: Linux: Fix build failure on AVX2 processor with disabled TSX, enable SSE4.2, SSE4.1, SSSE3 builds

### PR DESCRIPTION
**Pull request by turtleli**
Version: 1.3.1 GIT f2657ae
Relevant PC Specifications:
CPU: Intel Core i5-4590 @ 3.3Ghz with updated microcode(revision 0x1c, 2014-07-03)
OS: Slackware Linux 14.1, 64-bit with 32-bit chroot, GCC 4.8.2

Issue: On Linux, CPUs with AVX2 instruction sets that have TSX disabled (by microcode update or otherwise) fail to build GSdx. The \__RTM__ macro is undefined, and the TSX RTM instruction set (_xbegin, _xend, _xabort, etc.) is unavailable. Without the microcode update (TSX enabled), the build works fine. Issue #440 may also be related to this, where the vmware build had to use the --nosimd option due to compile errors.

Fix: I've modified the preprocessor check so that the RTM instructions are only used if available. This fixes the build on Linux, I haven't tested it on Windows.

### CODE REVIEW

**Comment by turtleli** [comment]
Apologies, still getting the hang of git, was supposed to only do one commit. First commit fixes what I've described, second commit I think addresses issue #438 in enabling Linux GSdx SSSE3, SSE4.1 and SSE4.2, which I've briefly tested out, but which I was going to comment on first.

**Comment by gregory38** [comment]
Strangely I never have any issue on my PC. It is good for me, but it deserves a comment in the code.

**Comment by turtleli** [comment]
Ok, I've added a comment to the code.

There are additional issues:
1. The TransactionScope class is compiled but not used. I've added a commit that comments it out, I don't mind if that commit doesn't get merged though.
2. If TransactionScope does get used, a runtime check for the RTM instruction set will also be necessary for those that are not compiling their own binaries.

**Comment by gregory38** [comment]
Hum, an 
```#if 0```
will be better to comment the class. It would create less conflict with my atomic branch.

**Comment by turtleli** [comment]
No problem. I've redone the last commit to use #if 0.

**Comment by gregory38** [comment]
Ok good. Thanks very much.

**Pull request merged**
