### PR TITLE
GS-hw: Purge custom resolution entirely.

### PR DESCRIPTION
**Pull request by lightningterror**
### Description of Changes

GS-hw: Purge custom resolution entirely.

Code debt, not used anymore, get rid of it.
### Rationale behind Changes

Custom resolution is not used anymore, get rid of it.
### Suggested Testing Steps

Make sure upscale multiplier still works.

### CODE REVIEW

**Review by JordanTheToaster — APPROVED** [review]

**Review by refractionpcsx2 — APPROVED** [review]

**Comment by Tokman5** [comment]
why UpscaleMultiplier will be limited 8x?
imo 10x is needed for 8k resolution, even though you don't need to add such high res settings at the moment.

**Comment by refractionpcsx2** [comment]
Upscaling would be broken entering custom upscales like that since we don't handle them internally (it needs to be done for each upscale), and unless you have an 8k monitor there isn't much point.  8x is plenty enough.

**Comment by iMineLink** [comment]
Do we still need to support custom x/y float scaling in textures after this?

**Comment by lightningterror** [comment]
> Do we still need to support custom x/y float scaling in textures after this?

We can merge the two.

**Pull request merged**
