### PR TITLE
FreeBSD: Fix compilation

### PR DESCRIPTION
**Pull request by turtleli**
This is a re-attempt at fixing FreeBSD compilation (I reverted the previous attempt in a977f1e6c1c67f1c4fe55cb1dfc760bd7c648bca).

The changes are largely the same.

Changes:
 * Remove ambiguous wxString-related overloads - wxString can be constructed with char*, wxChar* and wxString, so having function overloads that accept all of these types can actually result in ambiguity errors. Compared to the previous attempt, I also removed an assert (which was what caused issues in the previous attempt, the assert doesn't do anything meaningful due to the changes I made) and a FastFormatUnicode overload.
 * Split the thread callback function - Prevents compilation issues on Windows.
 * wx-config change - The wx3.0 pkg on FreeBSD is now configured slightly differently (built against GTK3) so the path has been adjusted to reflect that.

### CODE REVIEW

**Comment by lightningterror** [comment]
Is ISO swapping working fine now? @refractionpcsx2 can you test this?

**Comment by refractionpcsx2** [comment]
> Is ISO swapping working fine now? @refractionpcsx2 can you test this?

Wat? I don't have FreeBSD!

**Comment by lightningterror** [comment]
See https://github.com/PCSX2/pcsx2/commit/93d5b52df34c03a2ed859bba6e06fead3b875e70#commitcomment-30390863

**Comment by refractionpcsx2** [comment]
oh right, uhh I'll try it, I can't remember exactly how to replicate it, can only guess though

**Comment by refractionpcsx2** [comment]
TBH I can't get it to go wrong on Master anymore.

**Comment by turtleli** [comment]
> * Compared to the previous attempt, I also removed an assert (which was what caused issues in the previous attempt, the assert doesn't do anything meaningful due to the changes I made)

**Comment by turtleli** [comment]
I should mention that the ISO swapping issue only affected dev/debug builds before I reverted the commits.

**Comment by refractionpcsx2** [comment]
That may be why then

**Pull request merged**
