### PR TITLE
Swap the order of Fast boot and Full boot.

### LINKED ISSUE #797: Swap the order of "Boot CDVD (full)" and "Boot CDVD (fast)" + change Iso to ISO
Boot CDVD (fast) is used more (and from what I understand it's also what's recommended) than Boot CDVD (full) so it would make sense for it to be listed first.

Another thing I'd like to see would be the changing of Iso to ISO in the CDVD menu. There's only two instances of it from what I can see.

### PR DESCRIPTION
**Pull request by ssakash**
Fixes #797 

also change "Iso" to "ISO" since apparently it was bugging some users. XD

### CODE REVIEW

**Comment by ramapcsx2** [comment]
No, this is not good.
Full boot is listed first because it is the compatible option.
Fast skips the BIOS setup routines that set some registers to specific values that we haven't been able to fully reverse yet.
The reasoning that "fast" is used more often is less important that compatibility.

**Comment by ssakash** [comment]
I have removed the swap part for now and only included the typo fix, It has been synced to the patch at my repository (https://github.com/ssakash/pcsx2/tree/patch-1) but not on the PR yet. probably because you closed this PR ?

**Comment by avih** [comment]
I _think_ that changing "Iso" to "ISO" will require new translation on all languages. Is it worth it?

**Comment by ssakash** [comment]
it has just been capitalized, I don't think it would be a problem. also most of the translation files use ISO instead of Iso in the pcsx2_Main.po file. (just referred to catalan and french)

**Comment by avih** [comment]
> I think that changing "Iso" to "ISO" will require new translation on all languages. Is it worth it?

Correction: This will require new translation for all languages. Is it worth it?

**Comment by avih** [comment]
Apologies. Your patch indeed changes a single "Iso" instance and not the "Iso Selector" menu Item, and this would not matter much for translations indeed.

That being said, if we decide that "ISO" is the correct way, we should do that everywhere instead a PR for each instance. This includes the "Iso Selector" menu item and possibly other places (I didn't check if//how many there are). So every place which is more than just "Iso" will likely require an updated translation.

**Comment by nhydock** [comment]
"ISO" is the proper spelling.  I agree that there should be a single pull request that fixes all inconsistencies about this.

https://en.wikipedia.org/wiki/ISO_image

**Comment by avih** [comment]
If someone wants to work on it, and to save some effort, such change should apply only to UI elements (menu items, titles etc).

Specifically, don't touch console messages and don't touch variable names. If in doubt, ask first.

**Comment by karasuhebi** [comment]
>That being said, if we decide that "ISO" is the correct way

There's no doubt about it, ISO is the correct way: https://en.wikipedia.org/wiki/International_Organization_for_Standardization#Name_and_abbreviations

I also agree that a single PR should change all instances of Iso.

**Comment by yorkiesandskittles** [comment]
That's the wrong article: https://en.wikipedia.org/wiki/ISO_image
But the same rules still apply here. Definitely "ISO."

**Comment by karasuhebi** [comment]
Um...no. I didn't link the wrong article. It's the same thing. This is from your link:
"The name ISO is taken from the ISO 9660 file system used with CD-ROM media"

And this is from the ISO 9660 article:
"ISO 9660, also referred to as CDFS (Compact Disc File System) in Microsoft Windows, is a file system standard published by the International Organization for Standardization (ISO) for optical disc media."

:)

**Pull request closed without merging**
