### PR TITLE
Remove superVU.

### PR DESCRIPTION
**Pull request by arcum42**
superVu has long been obsolete and not maintained. It's largely in pcsx2 because a small handful of games have issues in them. See #1638 .

This does mean changes to the jit code need to keep compatibility with it (which I've already run into trouble with a few times), and whenever we go to 64 bits, I highly doubt it'll be ported.

This pr completely removes superVu. My feeling is that we've got plenty of time to work on fixing those couple games afterwards, or people can use 1.6 to run them. The games are mostly having the same M-Flag issue as well.

### CODE REVIEW

**Comment by orbea** [comment]
Is there a list of games would potentially need to be fixed after this PR is merged?

**Comment by MrCK1** [comment]
> 
> 
> Is there a list of games would potentially need to be fixed after this PR is merged?

The remaining games are here: https://github.com/PCSX2/pcsx2/issues/1638

**Comment by RedDevilus** [comment]
Perhaps also revise memcards section with those pot/po files?

**Comment by arcum42** [comment]
Doublechecked and still seems to be working in Linux. Everyone alright with merging?

**Comment by MrCK1** [comment]
I'm fine with merging.

**Comment by turtleli** [comment]
pcsx2/windows/VCprojects/pcsx2.vcxproj{,.filters} still has references to avuZeroRec.S.

**Comment by arcum42** [comment]
Took care of the avuZeroRec.S references.

**Comment by lightningterror** [comment]
> Everyone alright with merging?

As long as there are no new issues go for it.

**Pull request merged**
