### PR TITLE
GameIndex > Updates & Corrections

### PR DESCRIPTION
**Pull request by pgert**

### CODE REVIEW

**Comment by gregory38** [comment]
Honestly I have the feeling that people don't agree on the syntax name of the game.

**Comment by avih** [comment]
I don't think the name matters much, and I definitely don't know which names are preferred over others. There has been some discussion in the past which I don't think ever got to a proper conclusion about what the names should look like.

Regardless though, I'm closing this PR because it has no title and no commit message.

@pgert please add a commit title and message explaining what this patch changes and why, as well as reference to some discussions where there's a consensus between community  members about the changes in this patch.

**Comment by pgert** [comment]
Isn't "GameIndex > Updates & Corrections" a title?
About correctness of names, regions & compatibility - where lies the required consensus in that?

The only Substantial thing this changes is the improved HD-hack for "Drakan 2",
 which I can't give you any external confirmation of.
If you have this game in PAL, then please try it out for yourself.

**Comment by avih** [comment]
> Isn't "GameIndex > Updates & Corrections" a title?

Barely, but it's not what I was referencing. That title is for the github  PR. I was talking about a title and message for the commit itself.

E.g. click the "Commits" tab at the top of this page, you'll see "No commit message".

In contrast to, e.g. PR #611 where (after you click the commits tab) you see 3 commits where each commit has both a title and a message body (expanded when you click the `...`).

In general, the commit title should be a short description of the patch, and the message body should extend with more info, reasons, references, etc.

>  About correctness of names, regions & compatibility - where lies the required consensus in that?

I don't recall exactly, search the forum. There has been quite a long discussion what's the correct spelling etc for the names at the games DB, and IIRC it never reached a consensus. If it reaches a conclusion, then send a PR for naming changes only with reference to the original discussion.

> The only Substantial thing this changes is the improved HD-hack for "Drakan 2", which I can't give you any external confirmation of. If you have this game in PAL, then please try it out for yourself.

That's good info and that's exactly what should get into the commit title/message. Also, very good practice in general is separating substantial from non-substantial changes into different commits, and giving each of them an appropriate message and explanation.

Specifically I don't have this game and can't test it, but if you add this info and explain exactly what it improves, then others can provide feedback.

**Comment by pgert** [comment]
About commit message: OK, I get it now.

About gametitles: OK, let the mob decide.

I'll split this into one PR ONLY for Drakan 2, another for Region Correctness, and (possibly) a third for Info Outputs.

https://github.com/PCSX2/pcsx2/pull/619

**Pull request closed without merging**
