### PR TITLE
EE SYSCALL: Add missing video modes at SYSCALL 2

### LINKED ISSUE #1054: Bios ps2 Logo off center
On the latest dev builds the Playstation 2 logo you see before a game starts is vertically off center.

### PR DESCRIPTION
**Pull request by ssakash**
**summary of changes**:
* Add missing video modes at EE SYSCALL 2

Build download link: https://ci.appveyor.com/api/buildjobs/jc5g83x435sfk8as/artifacts/pcsx2-v1.3.1-1576-gff780b9-master-65-vs2015-Win32-ReleaseAll.7z

### CODE REVIEW

**Comment by ssakash** [comment]
@rz5

can you check whether DMC3 , Skygunner , Tribes : Aerial assault are still fine on this branch ?

**Comment by rz5** [comment]
DMC3 PAL 60Hz, Skyunner and Tribes all have regressions with this branch. All 3 games get the black bars on the bottom. 

All 3 games set up the DISPLAY register such that when GetFrameRect() is called, we end up with 512 height and the proper height would be 448. This branch alters the little saturation hack condition in order to fix the PlayStation 2 splashscreen but it does so at the cost of causing regressions on the 3 other games.

So we're back at square one with a catch-22 situation. Either we start collecting CRC hacks in the codebase again to fix the height of problem games or we wait till #961 gets fixed and the part of the code which calculates framebuffer/screen height is rewritten and properly fixed.

@ssakash, I propose you undo the GSState::GetFrameRect() changes in this branch and leave the PS2 logo height bug as-is.

**Comment by ssakash** [comment]
Removed second commit since it caused regression on few games, current commit should be good to go.

**Comment by gregory38** [comment]
Could you add the content of those variables in the logging. I don't know what they do. But the syscall uses their content to select the programmation. Ld is a 64 bits load and lw is a 32 bits load. Good luck.

8000bd84:	605942dc 	ld	v0,(0x80015960) @@ gs_hv_param

8000bde4:	1826428c 	lw	v0,(0x80022618)

8000c1fc:	8025428c 	lw	v0,(0x80022580) # set by iop page1 read
8000c218:	8425428c 	lw	v0,(0x80022584)
8000c4c4:	8825428c 	lw	v0,(0x80022588)
8000c508:	8c25638c 	lw	v1,(0x8002258c)

**Pull request merged**
