### PR TITLE
GS/HW: Fix up some down/upscaling behaviour

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Restrict how large a target can be before it downscales to do a copy.

### Rationale behind Changes
This was misfiring when copying a large "downscaled" target on to the framebuffer, which as a result downscaled the framebuffer, since there's no easy way to detect if this can be downscaled or not, so better to restrict the size.

### Suggested Testing Steps
Try Valkyrie Profile 2 and Dragons Quest VIII where it was forcing downscaling.

Keep in mind I'm probably still not going to put anything past "normal" native scaling on Dragons Quest as it causes some bad pixelation still

### CODE REVIEW

**Comment by bigol83** [comment]
OK this is a comparison in battle between Native Scaling set to Aggressive and Native Scaling set to OFF.

Aggressive
Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20240619010131

OFF
Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20240619010143

It's definitely an improvement compared to Master but characters and enemies still get pixelization. I find weird though that only some parts of the graphics become pixelated. Like, you can see 3d elements stay sharp, while characters outlines and the sky, probably because they are both post processing effects, are pixelated. 

At least now it goes back to normal graphics after the battle is over and it's not the whole image that becomes pixelated.

**Comment by refractionpcsx2** [comment]
yeah I dunno right now, I've not looked in to that, don't have much time for the next few days to look in to it either, but I was experiencing the same problem with my dump (though it's less than it was before)

image

**Comment by bigol83** [comment]
> yeah I dunno right now, I've not looked in to that, don't have much time for the next few days to look in to it either, but I was experiencing the same problem with my dump (though it's less than it was before)
> 
> image

Let me check the same spot for me, i never noticed it going pixelated in town, outside of battles.

**Comment by bigol83** [comment]
Yeah, i reproduced it too, it's very picky. This game post processing is crazy. It makes the character morph from a pixelated mess to perfectly sharp depending on angle when a character is affected by a post processing effect, the torch in this case or that's what i think.

Here a gsdump, it's uncompressed, then compressed to 7zip ad then compressed in zip. Any other way the file was too big.

[Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20240619012551_2.zip](https://github.com/user-attachments/files/15893675/Dragon.Quest.VIII.-.Journey.of.the.Cursed.King_SLES-53974_20240619012551_2.zip)

**Comment by refractionpcsx2** [comment]
alright, I'll take a look at that when I get chance, thanks :)

**Comment by BreakPoints** [comment]
Destroy all Humans! also triggers this in a cutscene from the openeing mission. Not sure if this is useful or not but here's the dump. Running the dump seems to avoid the downscale.

Screenshot was taken at 4x native.

Destroy All Humans!_SLUS-20945_20240621205825
[Destroy All Humans!_SLUS-20945_20240621205825.zip](https://github.com/user-attachments/files/15932776/Destroy.All.Humans._SLUS-20945_20240621205825.zip)

**Comment by refractionpcsx2** [comment]
if it doesn't happen in the dump, that's gonna be a problem, cos I need to be able to reproduce it :P

**Comment by BreakPoints** [comment]
Yeah, looks like it triggers on a particular frame and loading any dump or savestate from after will fix it. Same with swapping renderers.

If PCSX2 has a frame advance option I might be able to catch it.

**Comment by refractionpcsx2** [comment]
Okay I tightened up the downscaling in some situations, I need to double recheck everything that was previously fixed, but Dragons Quest seems happy now

**Comment by BreakPoints** [comment]
Latest build still has a downscale during that cutscene in DaH! but it quickly recovers now, happens for just under a second. I remember this game doing some funky stuff with TexturetInRT so maybe that's hitting an edge case.

**Comment by refractionpcsx2** [comment]
can you try making a longer multiframe dump starting before it goes lower and releasing after? This one doesn't show it so I can't do anything with it

**Comment by BreakPoints** [comment]
[Here's the multiframe dump](https://mega.nz/file/71J0xBYL#aocY2midhLO0kghPh5AOqu3cII0xQ46KzNv1KGxQ99Y)

When played back on this PR's build you should see the downscale kick in and end during the camera pan.

**Comment by refractionpcsx2** [comment]
Alright Destroy All Humans shouldn't downscale randomly anymore, dump seems fine :)

**Comment by bigol83** [comment]
Checked Dragon Quest VIII right at the same parts as before, now it looks perfect, no issues anymore. Be gone ugly lines.

**Comment by DonelBueno** [comment]
Breaks Burnout 3+ fixes.

PCSX2_2024_06_22_06_53_40_637
PCSX2_2024_06_22_06_53_53_534
PCSX2_2024_06_22_06_54_03_895

**Comment by bigol83** [comment]
> Breaks Burnout 3+ fixes.
> 
> PCSX2_2024_06_22_06_53_40_637 PCSX2_2024_06_22_06_53_53_534 PCSX2_2024_06_22_06_54_03_895

Try changing other upscaling options too, they might help.

**Comment by escape209** [comment]
> Breaks Burnout 3+ fixes.

I was able to reproduce this in Burnout 3 as well. 
GS dump: [Burnout 3 - Takedown_SLUS-21050_20240622114202.gs.zip](https://github.com/user-attachments/files/15936225/Burnout.3.-.Takedown_SLUS-21050_20240622114202.gs.zip)

**Comment by refractionpcsx2** [comment]
Damn, alright no worries, I'll get that sorted

**Comment by refractionpcsx2** [comment]
Burnout fixed, it's just cos I'd updated the way it detects a downscale and the burnout CRC didn't fudge the downscale properly (since we HLE it), so it stopped detecting it.

All good now.

**Comment by bigol83** [comment]
Just a nitpick, it's not really noticeable as before but there are some battle scenes in Dragon Quest VIII where the game downscales parts of the background. 

No Native Scaling
Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20240622135250

Aggressive Native Scaling
Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20240622135236

[Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20240622134949.zip](https://github.com/user-attachments/files/15936374/Dragon.Quest.VIII.-.Journey.of.the.Cursed.King_SLES-53974_20240622134949.zip)

**Comment by refractionpcsx2** [comment]
That's the whole point? It's depth of field in the distance.

**Comment by bigol83** [comment]
> That's the whole point? It's depth of field in the distance.

Yeah, it's not really an issue, I'm more annoying than Dragon Quest VIII 😛

**Comment by refractionpcsx2** [comment]
I mean the way it works is by doing the depth/post effects in native resolution, and sometimes (like this) it shows up :P So your choice is either don't have the effect (current situation) or have it and have it a bit shimmery from the lower resolution. Hence the name Native Scaling :P

There's unfortunately no magic bullet to make these work without downscaling it. I think Sten wants to try doing a box filter at some point which *might* work, but idk until we do, it may end up as a 3rd option, or not work at all.

**Comment by bigol83** [comment]
Your two PRs already did so much for so many games, it's already a huge jump forward for upscaling. Really appreciate it.

**Comment by DonelBueno** [comment]
Is Round Sprite Half still needed when using native scaling agressive?

**Comment by refractionpcsx2** [comment]
In which game? It really depends what the round sprite was doing.

**Comment by DonelBueno** [comment]
Sorry, forgot to say it is DQ8.

Current GameDB for it is:

  gsHWFixes:
    autoFlush: 1 # Fixes missing bloom from surfaces like windows.
    # halfPixelOffset: 1 # Aligns shadows properly, but causes grid lines to appear in sea travel.
    halfPixelOffset: 2 # Sharpens world in far distances, aligns some bloom better.
    roundSprite: 1 # Fixes font artifacts.
    cpuSpriteRenderBW: 1 # Fixes broken fire sprites.

**Comment by refractionpcsx2** [comment]
if it fixes fonts, it's still needed

**Comment by bigol83** [comment]
I don't know if this belongs here, but Metal Gear Solid 3 intro cutscene i think it's now to blurry (master and this PR) with Native Scaling. 

Also, Align to Native makes a red line appear at the left and top sides of the image. 

Metal Gear Solid 3 - Snake Eater_SLES-82024_20240622230853

Gsdump
[Metal Gear Solid 3 - Snake Eater_SLES-82024_20240622224814.gs.zip](https://github.com/user-attachments/files/15938322/Metal.Gear.Solid.3.-.Snake.Eater_SLES-82024_20240622224814.gs.zip)

Another screenshot where i feel Native Scaling makes everything too blurry, even more so 

This is with Native Scaling Aggressive

Metal Gear Solid 3 - Snake Eater_SLES-82024_20240622231748

Native Scaling Normal

Metal Gear Solid 3 - Snake Eater_SLES-82024_20240622231837

Native Scaling OFF

Metal Gear Solid 3 - Snake Eater_SLES-82024_20240622231937

**Comment by refractionpcsx2** [comment]
That's the effect of the game, software is blurry too. If you don't like it you can manually disable Native Scaling I guess, but I'm going for accuracy :)

image

**Comment by bigol83** [comment]
> That's the effect of the game, software is blurry too. If you don't like it you can manually disable Native Scaling I guess, but I'm going for accuracy :)
> 
> image
> 
> Vs hw
> 
> image

True, i will honestly use Native Scaling OFF in this case. What about Align to Native? You can see it creates a red line in the first part of the cutscene. I am manually using Special Texture.

**Comment by refractionpcsx2** [comment]
> True, i will honestly use Native Scaling OFF in this case. What about Align to Native? You can see it creates a red line in the first part of the cutscene. I am manually using Special Texture.

Post effects are misaligned with Special Texture, I'd rather take the temporary line

**Comment by bigol83** [comment]
> > True, i will honestly use Native Scaling OFF in this case. What about Align to Native? You can see it creates a red line in the first part of the cutscene. I am manually using Special Texture.
> 
> Post effects are misaligned with Special Texture, I'd rather take the temporary line There's also some horrible chunky bar on the left of garbage (not sure if it's with NS or not)

I checked and you are right, in the first gsdump the mask glare and the sun reflection on the pipe is not correct with any other option except Align to Native. Well, no big deal, will crop 1 px to the left, 1 to the top, 1 to the right (because of rainbow garbage).

**Comment by refractionpcsx2** [comment]
yeah, I'm afraid right now it's the best we can do, sorry

**Review by JordanTheToaster — APPROVED** [review]

**Comment by BParks21** [comment]
@refractionpcsx2 Fixed Pixelation in Star Ocean and DQ8 but Prince of Persia The Two Thrones still goes completely pixelated in many areas.

Prince of Persia - The Two Thrones_SLUS-21287_20240622222513

https://drive.google.com/file/d/1DAAHmEts0vootwuTM0YTJIvUJTWficTI/view?usp=sharing

Savestate:
[SLUS-21287 (84F3309D).01.p2s.zip](https://github.com/user-attachments/files/15942366/SLUS-21287.84F3309D.01.p2s.zip)

**Comment by refractionpcsx2** [comment]
Alright, I'll check it out tomorrow, thanks

**Comment by BParks21** [comment]
Thank you sir

**Comment by RaduNastase** [comment]
> I mean the way it works is by doing the depth/post effects in native resolution, and sometimes (like this) it shows up :P So your choice is either don't have the effect (current situation) or have it and have it a bit shimmery from the lower resolution. Hence the name Native Scaling :P
> 
> Looking at your screenshots, that's one of the least bad examples I've seen of it.
> 
> There's unfortunately no magic bullet to make these work without downscaling it. I think Sten wants to try doing a box filter at some point which _might_ work, but idk until we do, it may end up as a 3rd option, or not work at all.


Is there any way to mitigate that shimmering in the depth of field of some games? (MGS3 for example, both foreground and background dof are really pixelated).
It looks great overall in the sense that the effects are there, but in some cases, it appears veey blocky.
LrPs2 core with paraLLEI-gs seems to handle these effects better, with less blockiness. Can ticking some boxes on pcsx2 offer similar outcome?

Thanks!

**Comment by refractionpcsx2** [comment]
You can disable the native scaling, which will likely reduce/nullify the depth of field effect.  parallell-gs managed upscaling by upsampling the entire render from native, so it doesn't do as good of a job as actually upscaling, but the advantage to that is the effects that require native resolution to work correctly (like depth of field) work fine.  PCSX2 doesn't work this way, it truly upscales and the native scaling option attempts to render those effects in native resolution, which does become apparent otherwise.

So yeah you can enable manual GS fixes in the per-game settings, and turn all the options back in the warning popup mentions except native scaling, that's the best you can do (unless you just use LrPS2).

**Comment by RaduNastase** [comment]
> You can disable the native scaling, which will likely reduce/nullify the depth of field effect. parallell-gs managed upscaling by upsampling the entire render from native, so it doesn't do as good of a job as actually upscaling, but the advantage to that is the effects that require native resolution to work correctly (like depth of field) work fine. PCSX2 doesn't work this way, it truly upscales and the native scaling option attempts to render those effects in native resolution, which does become apparent otherwise.
> 
> So yeah you can enable manual GS fixes in the per-game settings, and turn all the options back in the warning popup mentions except native scaling, that's the best you can do (unless you just use LrPS2).


For some reason, if i leave Manual Fixes disabled, the dof is really blocky and shimmery, but setting Half Offset to "Align to Native" and Native Scaling to "Normal" actually produces results very very close to that of LrPs2 paraLLEEI-gs.
The big advantage here is that Blending Mode can be set manually and not locked to the Ultra mode, like in paraLLEI-gs, which is a big performance killer. Even setting it to Full provides considerably extra performance at something like 4k res.

**Comment by refractionpcsx2** [comment]
I guess do that then? it's probably not PS2 accurate, though, but as long as you're happy :)

**Pull request merged**
