### PR TITLE
GS: Support using SW renderer for texture decompression sprites

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

A number of games including the Spiderman series, True Crime: New York City, Kung Fu Panda, L.A. Rush, Call of Duty series, and others, take the idea of texture streaming a step further. Instead of just transferring the textures on demand, they also stored them in RAM in a "compressed" form (similar to VQ texture compression), and "decompressed" them on the GS just before they were drawn! A very clever technique, since the GS had no form of texture compression, outside of "normal" indexed/palette textures. They did this by performing several small sprite draws to apply an additional palette prior to the normal draw.

The result was a disaster for our texture cache. Not only did you have to worry about keeping all these tiny "textures" inside one larger framebuffer, but you also had to merge them back together into a single texture prior to draw, and dispatch all of the sprite draws, which can be upwards of 1,000 per frame. As expected, mobile GPUs absolutely hated it, and desktop GPUs weren't much better. Not only that, but in most cases, the TC couldn't track all this mayhem going on, and you got completely broken textures in the hardware renderers.

Previously, the only solution was to use the software renderer. But, can we identify these "texture decompression" draws, and use the software renderer only for these? The answer was yes, after some experimentation, we found a heuristic which worked for these draws, but did not break others. Another advantage, because the texture data is now present in local memory (due to software being used), they result in hits for the hash cache, further improving performance, and enabling texture replacement.

I don't like the hack for invalidation, but outside of a riskier change rewriting the whole thing (and improving my understanding of local memory at the same time), at least it's safe..

### Rationale behind Changes

Fixes https://github.com/PCSX2/pcsx2/issues/5914
Fixes https://github.com/PCSX2/pcsx2/issues/1320
Fixes https://github.com/PCSX2/pcsx2/issues/5366
Fixes https://github.com/PCSX2/pcsx2/issues/3138
Fixes https://github.com/PCSX2/pcsx2/issues/775
Fixes https://github.com/PCSX2/pcsx2/issues/3055

Any others?

### Suggested Testing Steps

Test affected games.

### CODE REVIEW

**Comment by stenzek** [comment]
> That is a very big commit regarding compatibility indeed. I wonder if the hash cache will have a negative impact on this.

As the textures are block-decompressed in local memory, the hash cache works as expected; some of these games end up with near zero texture uploads per frame. That also means that replacing these textures should be possible.

> I have one question regarding this, can the logic be extended to the FBW screen-clear games as well?

I already believe some of these are already detected in the existing code.

**Comment by AhayriSG** [comment]
https://youtu.be/aIuVne2HKAg?t=310

**Comment by stenzek** [comment]
> As for FBW screan-clear, this seems to only be partially detected but the texture-cache itself stands no chance of actually being able to emulate such a behavior. And as far as I am aware, the only solution to this is the software render.

I'd have to look into what you're describing more closely, but if the expectation is that the clear is propagated to the hardware targets, this PR may not help (it only works in local memory, not the hardware targets). However, in theory, it should set the dirty area of any overlapping targets (and then that would get preloaded)... but the TC tends to struggle when there's overlap involved and it's not pointing directly at the target.

**Comment by RedDevilus** [comment]
Probably the shooter games like call of duty are affected with texture issues.

**Review by JordanTheToaster — APPROVED** [review]

**Comment by refractionpcsx2** [comment]
Can you provide your graphics settings @githubribbon45 ? Need to know what your texture preloading etc are set to.

**Comment by refractionpcsx2** [comment]
good god, what the fuck is that? Okay.

**Comment by stenzek** [comment]
Your settings are completely stupid. Reset to defaults, only enable hash cache and upscaling, and it'll run fine.

**Comment by refractionpcsx2** [comment]
And in the process completely ignored the "Recommended value" part of the description.

**Review by Mrlinkwii — APPROVED** [review]

**Comment by Anuskuss** [comment]
So is it really supposed to be called `cpuSpriteRenderBW`?

**Comment by Sportik-228** [comment]
Hello! can u help me with True crime NYC? PCSX2 v 2.1.56 has flickering textures in the form of dark squares, i used different game versions, graphic settings vulkan, ogl, d3d (SW is good) and have same problem. I dont understand how to install your fix, excuse me
True Crime - New York City_SLES-53616_20240810103001
True Crime - New York City_SLES-53616_20240810103002

**Pull request merged**
