### PR TITLE
Makes VU0f registers display as floats in the debugger

### PR DESCRIPTION
**Pull request by monster860**
image

### CODE REVIEW

**Comment by tadanokojin** [comment]
Isn't this already open at #2779?

**Comment by ramapcsx2** [comment]
Yep, looks like 2 implementations of the same thing.
I'm not actively using the debugger, and I don't have much external input on it either.
If you guys really want this "display as float" feature, I suppose we should do it (and merge one of these) :p

**Comment by lightningterror** [comment]
Which one is better?

**Comment by ramapcsx2** [comment]
https://github.com/PCSX2/pcsx2/pull/2779 has the nicer formatting.
This PR currently shows a higher precision but I don't think this more useful than the easier readability of the other.
So yeah, 2779 gets my vote :p

**Comment by lightningterror** [comment]
Closing in favor of #2779

**Pull request closed without merging**
