### PR TITLE
GS/OpenGL: Use EGL 1.5 platform interface

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Instead of crossing our fingers and hoping that the driver can work out the correct EGL platform/backend, we can use the platform extension to explicitly ask for a platform that matches the window we're creating it for.

EGL 1.5 has been a thing for over a decade, although Mesa at least doesn't implement it fully. But they do implement the platform extension, hopefully everyone else does too...

### Rationale behind Changes

Stops a potential crash due to selecting the wrong EGL platform? Does this actually happen?
Apparently some users were getting a crash in `eglGetDisplay()`... 

### Suggested Testing Steps

Make sure Intel, AMD and NVIDIA OpenGL still works on Linux.

### CODE REVIEW

**Review by Mrlinkwii — APPROVED** [review]
Nvidia linux works

**Review by kamfretoz — APPROVED** [review]

**Comment by TheTechnician27** [comment]
I don't know if this helps, but I ran this PR on my laptop which is running Manjaro and has an Intel iGPU. The device description reads 'Alder Lake-P GT2 [Iris Xe Graphics]'. I just booted into the BIOS with OpenGL, so this was a pretty shallow test.

**Review by kamfretoz — APPROVED** [review]
AMD Radeon RX 6600 XT on Arch Linux checks out ✅

image

**Comment by Mrlinkwii** [comment]
works on Quadro K2200 on linux 
image

**Comment by TheTechnician27** [comment]
Also ran on my GTX 1070 with latest drivers, and there was no issue getting in-game, switching to OpenGL, and playing around for a few minutes.

**Comment by TheTechnician27** [comment]
On my Intel Xe laptop (tested latest commit), Ratchet's doing just fine walking in and out of his house on OpenGL, so all good on my end.

**Pull request merged**
