### PR TITLE
Norwegian translation update

### PR DESCRIPTION
**Pull request by DandelionSprout**
Here's the pull request, as I was told to do on the forums. :)

### CODE REVIEW

**Comment by gregory38** [comment]
No update on the iconized part ? On going ?

**Comment by DandelionSprout** [comment]
Many of the lines in the Iconized file are pretty heavy to translate, 
but I'm working on it on-and-off, with ATM 52 lines translated out of 
85. I expect to get it done sometime this weekend, at which point I'll 
pull-request that one too.


Den 10/03/2017 18.57, skrev Gregory Hainaut:

**Comment by DandelionSprout** [comment]
Now I think I have pull-requested the full Iconized translation, and done the last few final visible brushes on the Main.

I must admit that I was not prepared to do the Iconized translation when I began translating Main earlier this week, so it took ever so slightly more effort for me to do. Hopefully things will work out now! :)

**Comment by gregory38** [comment]
Thanks you for all Norwegian guys :+1:

**Comment by gregory38** [comment]
I will upload the prebuilt mo file later.

**Pull request merged**
