### PR TITLE
Update widescreen patches/cheats

### PR DESCRIPTION
**Pull request by lightningterror**
This syncs the cheats_ws.zip widescreen patches archive with Devina's
archive from 22.02.2018.

https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=271674#pid271674
Compared to the previous content of cheats_ws.zip:
- 4 files deleted 9C4BA2CE, 113035B9E, C565E79E and duplicate 1429EB9F (2)
- 142 files modified
- 760 new files
- 2294 files identical to before
- 28 files that were removed from the forum archive that contained hunting/fishing
games have been re added. Separate archive provied by FlatOut.
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=581186#pid581186

The zip now has a total of 3200 patch files, compared to 2440 before.

Just to be safe please test if the archive works properly on a few games for verification.

Note: I used the 7zip with the Ultra compression method to compress the archive, just throwing this info here if it's important.

### CODE REVIEW

**Comment by avih** [comment]
Previously I tried to give some more detailed statistics when updating this file. I still think it'd be useful to have it here too.

See https://github.com/PCSX2/pcsx2/commits/master/bin/cheats_ws.zip

**Comment by lightningterror** [comment]
Better ?

**Comment by lightningterror** [comment]
I think it should be good now ( hope I didn't make a mistake in the calculation).

**Comment by avih** [comment]
> The zip now has a total of 3200 patch files, compared to 2440 before.

I'm counting 3172 ...

**Comment by avih** [comment]
Also, 2018-02-22 is almost 2 months old. Did you ask Devina at the forum if there's an upcoming archive release or if one can be made? Or for any other notes you should be aware of?

**Comment by lightningterror** [comment]
> I'm counting 3172 ...

Ah yes I forgot to mention that I included the patches that she removed from the archive that contained hunting/fishing games.

**Comment by avih** [comment]
> Ah yes I forgot to mention that I included the patches that she removed from the archive that contained hunting/fishing games.

So where did you take them from? An earlier archive? which one? Add this info too please.

**Comment by lightningterror** [comment]
I added the links to the PR and the info in the commit description.

**Comment by avih** [comment]
The info looks good to me. Thanks. Hopefully it's also correct...

**Comment by lightningterror** [comment]
Actually it's 760 new, not 764. It should be good now.

**Comment by avih** [comment]
If one was nitpicking, they'd say something about a more informative title ;)

**Comment by lightningterror** [comment]
Uh actually I'm not sure it's either 760 or 764, this is driving me nuts. I'll just leave it at that. Someone else can do the calculations.

> If one was nitpicking, they'd say something about a more informative title ;)

We have the description for that already.

**Comment by refractionpcsx2** [comment]
Is this ready then? Is everybody happy? :)

**Comment by lightningterror** [comment]
The archive works so it's something xD

**Pull request merged**
