### PR TITLE
Add new hacks tickbox to GSdx

### PR DESCRIPTION
**Pull request by Sarania**
This is adding the tick boxes for Gregory's new hacks to the Windows side.

I also made them obey whether or not "Enable HW Hacks" is checked.

It should be good, I have tested it a lot.

Edit: The "TC Offset" box labels are slightly out of alignment in this screenshot. I noticed it later, but it's fixed in the code.

### CODE REVIEW

**Comment by avih** [comment]
Looks good. Squash all of them to a single commit and force push? After all, the hack is already in place before this PR, and this PR only adds the Windows UI for it, I think it's better as a single commit.

**Comment by ssakash** [comment]
blyss: make sure to force push, the normal push will not work for the commits for the published commits.

**Comment by Sarania** [comment]
Yeah it makes sense to have it as a single commit. I managed to squash them after some googling.

**Comment by avih** [comment]
Thanks. Next time try to make the title and description more specific, e.g.:
Title: GSdx: add UI for hacks: stretch sprites, align sprites
Rest of the message: The hacks were added on <some changeset>

**Pull request merged**
