### PR TITLE
GameDB: Fix to the name of Asterix & Obelix XXL

### PR DESCRIPTION
**Pull request by JordanTheToaster**
### Description of Changes
Fixes a misnaming of a game.

### Rationale behind Changes
More correct DB more good.

### Suggested Testing Steps
Make sure CI is happy.

### CODE REVIEW

**Review by Mrlinkwii — APPROVED** [review]

**Comment by piau9000** [comment]
Any reason why it's still showing the wrong name for me?

**Comment by JordanTheToaster** [comment]
> Any reason why it's still showing the wrong name for me?

Settings > Rescan All Games.

**Comment by Mrlinkwii** [comment]
@piau9000  you need to rescan games for it to update

**Comment by piau9000** [comment]
It worked. Thanks and sorry for my stupidity.

**Pull request merged**
