### PR TITLE
Update GameIndex.yaml

### PR DESCRIPTION
**Pull request by dfm2525**
### Description of Changes
corrected romanization for Mai-Otome. Mai-Kinoto is a (machine?)translation error.

### Rationale behind Changes
That is the correct romanization of the series https://mai.fandom.com/wiki/Mai-Otome

### Suggested Testing Steps
Game list name updated

### CODE REVIEW

**Comment by Buzzardsoul** [comment]
Use the gameindex.yaml file in your pcsx2 folder and update it. You cannot ctrl c and ctrl v the contents into a txt file like this as it will likely not work.

**Comment by kamfretoz** [comment]
> Use the gameindex.yaml file in your pcsx2 folder and update it. You cannot ctrl c and ctrl v the contents into a txt file like this as it will likely not work.

image

i mean....

**Comment by RedDevilus** [comment]
Wrong title, description and yeah the lines itself are like Spider-Man pointing to itself to do nothing. I do see Mai-Kinoto Hime:

https://www.play-asia.com/mai-kinoto-hime-limited-edition/13/701kz8?ref=google_in

**Review by lightningterror — CHANGES_REQUESTED** [review]
Can you properly only change the lines of the game title you want to update?

**Comment by dfm2525** [comment]
Lol I just used the github's UI to change to name, didn't realize it messes up the whole file.  Sorry.

**Pull request closed without merging**
