### PR TITLE
CDVD: Add CHD file support

### LINKED ISSUE #2584: [Request]Add CHD format support for compressed disc
Hello there, love the project, can we get some CHD love for the pcsx2 as a compressed disk format?

CHD or "Compressed Hunks of Data" - it's a MAME format for storing disk images.

With libchdr from @rtissera this should be doable like the new retroarch cores do
https://github.com/rtissera/libchdr

Some of the benefits the CHD support have:
.-lossless compression
.-15-18% better compression than pbp (this makes a bin cue uncompressed collection almost half its size)
.-its a streamable format, it doesnt need to decompress, just play
.-its increadibly easy to convert entire folders filled with uncompressed psx games with a batch file
.-every disc turns into just one file
.-supports redbook audio in flac compression
.-its becoming the defacto standard for libretro cores with support in mame, saturn, pcengine/turbografx, segacd/megacd, psx beetle and future support for dreamcast (in a few days)

Twice the fun, same space

Thanks in advance
Best regards

### PR DESCRIPTION
**Pull request by siddhartha77**
Note: I realize that instead of cloning into [SleepyMan/pcsx2](https://github.com/SleepyMan/pcsx2) I cloned [PCSX2/pcsx2/](https://github.com/PCSX2/pcsx2/). I've honestly spent too much time on this as is, so I opened a new PR here instead of contributing to the other PR.

My original PR text I posted at https://github.com/SleepyMan/pcsx2/pull/1.

I'm sorry if I've done something wrong here, it's my first time contributing to a GH project. I did a bunch of work on your PR #4045 to fix #2584. Release and Debug (x86 and x64) all compile on Ubuntu 20.04 by following [these instructions](https://github.com/PCSX2/pcsx2/wiki/Installing-on-Linux#how-to-compile-pcsx2-in-2020-ubuntu-2004) as well as Windows with Visual Studio 2019 Community. I have tested both the **build.sh** and **mscompile.cmd** scripts.

With respect to [this comment](https://github.com/PCSX2/pcsx2/issues/2584#issuecomment-730296206): Two 3rd party libraries are required: **flac-1.3.3** and **lzma-19.00**. I was able to use the existing **zlib** library, but unfortunately I needed to use an older **lzma** instead of **xz**. The actual CHD routines were written by the MAMEDEV team and they have chosen to stick with the older **lzma** library. It's certainly possible there could be overlap, but I wanted to push out a working implementation at the cost of one additional library instead of spending days rewriting a complicated piece of code.

I have not added [libchdr ](https://github.com/rtissera/libchdr) as a module because I moved some of its directory structure around. I've also included fixes to allow large file support (>2GB) for CHDs as discussed at rtissera/libchdr/issues/40.

Co-Authored-By: SleepyMan <1133546+SleepyMan@users.noreply.github.com>
Co-Authored-By: Romain TISSERAND <romain.tisserand@gmail.com>
Co-Authored-By: whocares0101 <12903912+whocares0101@users.noreply.github.com>

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
It would be preferrable if you forked the original PR branch, did your fixes in that then PR'd your changes to the original PR's branch, then they can be added on tot he original PR, it's just a little messy and more difficult to track what's going on this way.

**Comment by siddhartha77** [comment]
Okay thanks. Done here: https://github.com/SleepyMan/pcsx2/pull/2

**Comment by refractionpcsx2** [comment]
Okay cool, hopefully SleepyMan will deal with it :)

**Comment by siddhartha77** [comment]
Hey @refractionpcsx2, What would be a reasonable time to wait for @SleepyMan's response? It's been almost a month since he's done anything on GitHub. I'm sorry if this is such a noob question; it's my first time contributing.

**Comment by 0x90shell** [comment]
Perhaps we need to merge sleepy's PR with yours into a single PR? Just give him credit for his work. The PR inception is a big roadblock to merge, because right now we're waiting on sleepy to return from his year(s) long slumber

**Pull request closed without merging**
