### PR TITLE
CI: Static Analysis -- Add Codacy

### PR DESCRIPTION
**Pull request by xTVaser**
I set it up on my fork to offer a demonstration - https://app.codacy.com/gh/xTVaser/pcsx2-rr

Steps to turning this on **(do this before merging this PR)**:
1. You need to be someone with admin access to the PCSX2 repo / org
2. Set up the free OSS plan for the organization - https://github.com/marketplace/codacy
3. Log-in via GitHub if it doesn't already redirect you (can't recall) here - https://www.codacy.com/
4. Add the PCSX2/pcsx2 repo
5. If annotations on PRs are desired, enable them here - https://app.codacy.com/gh/PCSX2/pcsx2-rr/settings/integrations
    - They will look like this - https://github.com/xTVaser/pcsx2-rr/pull/61/files
6. That's it!  Codacy checks will start appearing on PRs and master commits should be scanned and the issues in the repo should be tracked overtime / the dashboard can be used to identify and solve issues.

Codacy automatically enables checks based on the GitHub language stats.  ie if you use python code, it turns on PyLint.

Potential follow-up:
- We can analyze the CPP code further by running `clang-tidy` and sending the report to Codacy from Github Actions so the issues can be tracked.  However, `cppcheck` gives us plenty of issues to chew on for now.

### CODE REVIEW

**Comment by gregory38** [comment]
Why not.having both

**Comment by xTVaser** [comment]
> Why not.having both

I have no issues with that, Looking at coverity's documentation, they seem to have some sort of proprietary scanner so it could very well find issues that `cppcheck` and others avoid.

The main issue is that apparently Coverity has to be manually ran by whoever it was that originally set it up, where as this will run on every commit to master / and on every PR automatically.

About the only thing in regards to coverity this removes is the README badge, which i can leave in place.

**Comment by TheLastRar** [comment]
You can automate an upload to Coverity scan via a script

**Comment by xTVaser** [comment]
Someone with access will have to follow up with that improvement, even if it is automated, I believe this tool has value.  It runs scans that Coverity does not (general code-base cleanup at the very least).

**Comment by lightningterror** [comment]
I can give you coverity access if that's required.

**Pull request merged**
