### PR TITLE
Update GSCrc.cpp

### PR DESCRIPTION
**Pull request by puzzo888**
add crc games front mission 5 rus

### CODE REVIEW

**Comment by Blackbird88** [comment]
You say rus and mark it as JP. What.

**Comment by puzzo888** [comment]
потому что там находится так же английская версия тоже обозначенная как jap,решил не трогать ничего лишнего, я не програмист, подумал что это сделано специально. Если не сложно может ли кто нибудь скомпилировать этот код и выложить в интернете? буду весьма благодарен, не умею собирать

**Comment by avih** [comment]
Courtesy of google translate:

> because there is also an English version is also designated as jap, decided not to touch anything extra, I'm not a programmer, I thought that this was done deliberately. If not difficult if somebody can compile this code and put it on the Internet? will be very grateful, I am not able to collect

**Comment by willkuer** [comment]
You already compiled it with the buildbot by submitting this pr:
https://ci.appveyor.com/project/gregory38/pcsx2/build/1.210-master/job/extli1vcr65bhuqh/artifacts

**Comment by puzzo888** [comment]
errors with the shadows gone, I will try to add all the loaders to pirate Russian versions

**Comment by willkuer** [comment]
> pirate Russian versions

pcsx2 doesn't support piracy

**Comment by puzzo888** [comment]
there was a view of licensing the copy, which put Russian patches, Russian Oficial copies went out very little, so they transferred fans

**Comment by refractionpcsx2** [comment]
I'm not puttiung a code in for a pirate game, we are completely against pirate games. If somebody can come along with a legitimate version of the game (with proof as it's so rare) I will get information from them and add it, until then, no.

**Comment by puzzo888** [comment]
Disk have not sold this game, what you want me to do? Printed new? In Russia there is no possibility to buy the CD which came out 15 years ago only in Japan. Or do you think that all who unsubscribed or are testing this game have an original copy of the CD on hand? You going to lie to me or yourself?

**Comment by refractionpcsx2** [comment]
We don't help pirates, end of story. If you want help, buy a European copy which will already be patched.

**Comment by puzzo888** [comment]
well, then you can remove the crc front mission 5 which is a patch on the English language, because it is a pirated copy. I'll write more about crc 50-70 games in which English is the language of patches, they are also all pirated. Without problems to buy a CD, give please a link on the CD front mission 5 jp where can I buy.

**Comment by willkuer** [comment]
I would like to remind that there is a difference between downloading/buying a pirated patched version and applying a free language patch on your own legally created iso...

**Pull request closed without merging**
