### PR TITLE
GameDB: Fix Enemies Stuck in Armored Core Nine Breaker

### LINKED ISSUE #8587: [BUG]: Armored Core Nine Breaker - Stuck/Broken AI on Some Levels
### Describe the Bug

In Armored Core Nine Breaker, missions that feature small floaty enemies that appear from doors/hatches will get stuck in those doors, never leaving their initial spawn location. In some missions that have this issue, frequent hanging occurs too. This seems to be a long-running issue, as even on 1.6 these same AI are broken.

Here's some examples of what I'm talking about, you can see here on PCSX2 how the AI won't move from spawn.
https://youtu.be/-EyFNgUC8fw?t=28

And yet on real hardware, they do leave spawn.
https://youtu.be/BY4Dtf6e8po?t=41

I'm not entirely sure if this is an AI-related issue or a collision related issue. 
I've tried messing around with the rounding/clamping settings to no avail, but there's a chance I'm just doing it wrong.

### Reproduction Steps

(Reproduction steps shown in videos)

1. Start a new game
2. Go to Training
3. Select Attack > Judgement

### Expected Behavior

AI should leave their spawns and chase the player.

On emulator, they get stuck and never leave the spawn door.

### PCSX2 Revision

v1.7.4344 , v1.6.0

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

i5-7600K

### GPU

GTX 1050ti

### GS Settings

Default

### Emulation Settings

Default (Tested MTVU off)

### GS Window Screenshots

(not a GS-screenshot, but a GIF that shows the AI stuck in place.)
ezgif-5-8a9a2c8067

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by Berylskid**
### Description of Changes
- Reversed instructions that reads each enemies' stature and found a constant that is used for switching stuck and unstuck.
- This patch just makes the constant little bigger. (`3E4CCCCD` -> `3E4CCCE0`)

```
[Fix Enemy Stuck (dynamic)]
author=Berylskid
description=Fix Enemies' stuck. Region free.
dpatch=0,4,1,0,3C023E4C,4,3442CCCD,8,E7A300D0,C,E7A200D4,4,3442CCE0
```

### Rationale behind Changes
Related to #8587 

### Suggested Testing Steps
- Test all kind of MT enemies (except AC enemies like Arena, I mean).
- Test various region versions.

### Known Issues
- [Resolved] Enemies ignore walls

### CODE REVIEW

**Comment by Farran666** [comment]
Nice going! But I do have concerns regarding this dynamic patch. Can't you add 2 or more instructions to compare just to ensure it doesn't mess with more instructions than it needs?

**Comment by Berylskid** [comment]
I think I can. I'd like to add some additional bytes tomorrow.

**Comment by Berylskid** [comment]
Report: If the patched branch is NOP'd, enemies are stuck __even on interpreter__.

**Comment by Berylskid** [comment]
Found a new way to solve this problem, so replaced previous patch with new patch.
Now enemies do not ignore walls.

**Review by AmyRoxwell — APPROVED** [review]
Tested on the PAL version of the game, video below comparing a  bit of gameplay with a real ps2 playthrough on the `JUDGEMENT` mission:
https://www.youtube.com/watch?v=5p6JKCp_eLw

**Review by F0bes — APPROVED** [review]

**Pull request merged**
