### PR TITLE
Update Background Logo to Aquatic Theme

### PR DESCRIPTION
**Pull request by RedDevilus**
Improves background logo that matches the colors.

Also #3445 (Accidentaly pushed old files)

### CODE REVIEW

**Comment by RedDevilus** [comment]
Original logo
Original
First version which applies the Water effect on whole logo
Commit1
Second Version which does the same but doesn't apply it on the text
Commit2

**Comment by RedDevilus** [comment]
Any suggestions/opinions about this? If needed i can still reduce the water effect. Input is handy for everyone and i can't read minds.

**Comment by lightningterror** [comment]
I prefer the original, water effect feels odd with a circuit next to it too.

**Comment by asp0909** [comment]
I prefer the original

**Comment by turtleli** [comment]
I prefer the original.

**Comment by lightningterror** [comment]
Closing as original is preferred.

**Pull request closed without merging**
