### PR TITLE
GameDB: Various fixes

### LINKED ISSUE #10667: [BUG]: Welcome to Universal Studios Japan - Can't move
### Describe the Bug

it's like the character is stuck against an invisible wall. 

### Reproduction Steps

start a game and try to walk.

### Expected Behavior

you can move

### PCSX2 Revision

1.7.5476

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i5-9600

### GPU

rtx 3060

### GS Settings

_No response_

### Emulation Settings

turning mVU Flag Hack off seems to fix it. Don't know if this issue requires futher investigation.

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by JordanTheToaster**
### Description of Changes
Various fixes

Fixes #10667 

### Rationale behind Changes
I hate this game.

### Suggested Testing Steps
Make sure CI is happy.

### CODE REVIEW

**Comment by GitHub-Khi** [comment]
Can you please test this in these GS dumps? When i run around in this area with these new settings, red artifacts sometimes appear for a fraction of a second. Without GameGuard/Game Protection patches it is even worse. I have tested the PAL-G version. The file is too big to upload directly, so i had to upload it somewhere else. I am sorry if i am interfering too much. :)

Multi/Single Frame GS-Dump:
https://www.file-upload.net/en/download-15255750/ValkyrieProfile2-Silmeria_SLES-54646_20240118023029.zip.html

**Comment by JordanTheToaster** [comment]
> Can you please test this in these GS dumps? When i run around in this area with these new settings, red artifacts sometimes appear for a fraction of a second. Without GameGuard/Game Protection patches it is even worse. I have tested the PAL-G version. The file is too big to upload directly, so i had to upload it somewhere else. I am sorry if i am interfering too much. :)
> 
> Multi/Single Frame GS-Dump: https://www.file-upload.net/en/download-15255750/ValkyrieProfile2-Silmeria_SLES-54646_20240118023029.zip.html

Can you try with these new settings performance may be lower now but you can test that too.

**Comment by GitHub-Khi** [comment]
Tricky tricky... . The new settings seem to solve the Lost Forest problem, but have negative effects on other scenarios i think. But i do not know whether it is actually something bad or the first step towards improvement, where some final touch is still missing.

Single Frame GS-Dump First Cutscene 1:
[Valkyrie Profile 2 - Silmeria_SLES-54646_20240118150600.zip](https://github.com/PCSX2/pcsx2/files/13977908/Valkyrie.Profile.2.-.Silmeria_SLES-54646_20240118150600.zip)

Single Frame GS-Dump First Cutscene 2:
[Valkyrie Profile 2 - Silmeria_SLES-54646_20240118151452.zip](https://github.com/PCSX2/pcsx2/files/13977916/Valkyrie.Profile.2.-.Silmeria_SLES-54646_20240118151452.zip)

If the new settings are applied, it might would be advisable to set Software CLUT Render to 1 (Normal) to fix a render issue in the Lost Forest Dungeon, BUT this setting seems to break the fade effect from the Lost Forest to the Dungeon.

Single Frame GS-Dump Lost Forest Dungeon:
[Valkyrie Profile 2 - Silmeria_SLES-54646_20240118152137.zip](https://github.com/PCSX2/pcsx2/files/13977839/Valkyrie.Profile.2.-.Silmeria_SLES-54646_20240118152137.zip)

However, the Half Pixel Offset: Algin To Native setting itself only has advantages for this game. Nevertheless, the game drives us all insane! :D

**Comment by JordanTheToaster** [comment]
I've given up trying to fix the lines for now as it's not possible without totally breaking something else. I hate this game.

**Comment by GitHub-Khi** [comment]
Only give it up if you come to exactly the same results as me. Nevertheless, i commend your commitment to improving various games by changing certain settings. At some point there will surely be a proper solution. :)

**Comment by JordanTheToaster** [comment]
> Only give it up if you come to exactly the same results as me. Nevertheless, i commend your commitment to improving various games by changing certain settings. At some point there will surely be a proper solution. :)

A few of us looked at it and it's a total pain if you can confirm HPO Native doesn't break anything then I can move along with just adding that.

**Pull request merged**
