### PR TITLE
cdvdgigaherz: Reduce stuttering

### PR DESCRIPTION
**Pull request by turtleli**
This should reduce stuttering.

Bootup might be slightly slower, mainly because cdvdReadSector doesn't send a request to the cache if the data isn't present and it's the first thing called (it doesn't really get called after that). I should perhaps make it do so...

### CODE REVIEW

**Comment by FlatOutPS2** [comment]
Yes, bootup is even slower with this PR. It's another 2 seconds slower(adding to the 3 seconds it already slowed down a while ago).

**Comment by turtleli** [comment]
Ok, so I need to see if I can reduce bootup time.

What about stuttering?

**Comment by FlatOutPS2** [comment]
> What about stuttering?

I don't have a game that really suffers from it lying here right now, so I'll need to test that later.

**Comment by turtleli** [comment]
No problem, it might actually be better to wait till I update the PR.

**Comment by turtleli** [comment]
Updated. Bootup time should be a little faster than master.

**Comment by ramapcsx2** [comment]
Best if you always test with a DVD and a CD (PS2) game.
Eject the disc between runs. That should bypass the OS cache.

**Comment by turtleli** [comment]
> Best if you always test with a DVD and a CD (PS2) game

I can't test PS2 CD games because I don't have any (I do have some PSX games though).

Stuttering seems worse on Linux with this PR, so I need to think about this a bit more.

**Comment by FlatOutPS2** [comment]
Overall it feels like stuttering was reduced very slightly on both CD and DVD, but I noticed sometimes a stuttering sequence was faster on the PR on first pass, but on second pass the master seemed slightly faster. :/

Guilty Gear X(one of the games that didn't boot from CD until a while ago).
Master CD boot up: 35+ sec.
PR CD boot up: 40 sec. (confirming boot up is slower)
ISO boot up: barely 1 sec. :P

I also got two readfile errors on boot with both master and PR:

```
 * CDVD Disk Open: CD, 1 tracks (1 to 1):
 * * Track 1: Data (Mode 1) (311128 sectors)

 * CDVD ReadFile failed: sectors 2512-2527: error 23
 * CDVD ReadFile failed: sectors 2512-2527: error 23
```

**Comment by turtleli** [comment]
> Guilty Gear X(one of the games that didn't boot from CD until a while ago).
> Master CD boot up: 35+ sec.
> PR CD boot up: 40 sec. (confirming boot up is slower)
> ISO boot up: barely 1 sec. :P

Those are long boot up times. Are those boot up times specific to that game, some games or all games?

> I also got two readfile errors on boot with both master and PR:

CD reading probably still needs a bit of work. I get a similar error with Suikoden, but I haven't spent time looking at the issue yet.

**Comment by FlatOutPS2** [comment]
> Those are long boot up times. Are those boot up times specific to that game, some games or all games?

Specific to that game. Most other games load reasonably fast(or load slowly on disc and in ISO format).

**Comment by turtleli** [comment]
I'm going to abandon this PR. I'm not sure I can improve it without significantly changing how the threading and caching currently works.

**Comment by ramapcsx2** [comment]
Okay, it appears there isn't a lot of demand for this anyway. It would have been nice but priorities :)

**Pull request closed without merging**
