### PR TITLE
GameDB: Re-ordering gshwfix

### PR DESCRIPTION
**Pull request by RedDevilus**
### Description of Changes

Re-ordering of Star Wars Episode 3 Gshwfixes.
Fixes https://github.com/PCSX2/pcsx2/issues/6813
### Rationale behind Changes

Less hassle.
### Suggested Testing Steps

Test relevant game.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
I've fixed Chaos Field properly, Sniper 2 is also fixed but might still be flashing, not sure. This is done in #6894

Not sure what the Drakengard issue was?

**Comment by RedDevilus** [comment]
image

**Comment by refractionpcsx2** [comment]
okay, that should be fixed on my PR then.  The only one I'm not sure on which might still need software mode is Sniper 2, that'll need checking.

**Comment by RedDevilus** [comment]
I wouldn't be surprised if half of the FMVRenderer switches entries (150 or so now) so 75 of them are just to offset the problem with the right side stretching.

**Comment by refractionpcsx2** [comment]
Possibly! I must admit, I just threw this fix together, I've not checked to see what else it might fix, to be honest.  Might be good to check 🤔

**Comment by RedDevilus** [comment]
Like Monster Rancher 4 is another one

**Comment by refractionpcsx2** [comment]
Ah yeah, maybe the same thing again :) Probably a few of these then!

**Comment by refractionpcsx2** [comment]
If you could test any GS dumps on my PR, That'd be amazing <3

**Comment by refractionpcsx2** [comment]
okay my PR needs a bit of work.... annoyingly

**Comment by refractionpcsx2** [comment]
okay *should* be fixed now

**Comment by refractionpcsx2** [comment]
okay flashing now fixed too :)

**Comment by RedDevilus** [comment]
Gonna be hard to track all the remaining HW FMV games, might just be easier to remove all of them in the GameDB. Test random games and add them back in the yaml if needed.

**Comment by refractionpcsx2** [comment]
Ehhhhh not too happy with that idea lol. guess I have some testing ahead of me..

**Comment by refractionpcsx2** [comment]
I went through looking for ones which suffered from the issues I've been working on, and only a few hit it.  There is some games which have the switch for flickering/flashing, but they still flash, so they probably have a different issue :(

**Comment by NavaZap** [comment]
Front mission 5
image

**Comment by NavaZap** [comment]
i dunno, this just a blind guess but worth to check. 
If a game starts with FMV, it flickering and streched (its solved with changing renderer in graphics setting). If a game starts with memory card checking process, the FMV not bugged.

**Comment by lightningterror** [comment]
> i dunno, this just a blind guess but worth to check. If a game starts with FMV, it flickering and streched (its solved with changing renderer in graphics setting). If a game starts with memory card checking process, the FMV not bugged.

A gsdump will be nice, also check if https://github.com/PCSX2/pcsx2/pull/6894 fixes the issue.

**Comment by lightningterror** [comment]
Want to update the pr that changes the ordering of the gamefix only?

**Comment by NavaZap** [comment]
in front mission 5 https://github.com/PCSX2/pcsx2/pull/6894 fixes the issue.

**Comment by RedDevilus** [comment]
> Want to update the pr that changes the ordering of the gamefix only?

Done.

**Comment by refractionpcsx2** [comment]
Thanks :)

**Pull request merged**
