### PR TITLE
Some post-processing updates.

### PR DESCRIPTION
**Pull request by Asmodean-**
Just a few small post processing updates, to improve the bloom and tonemapping. Plus a small fix for the output order.

### CODE REVIEW

**Comment by avih** [comment]
Could you please add some more info to the commit message? like: 
- fix typo Scalar -> Scaler
- foo
- bar

etc?

**Comment by Asmodean-** [comment]
I'm not exactly sure what you're asking here. You want line by line changes?

Who am I explaining it to? I'm more or less the sole maintainer of the post processing shaders.

**Comment by avih** [comment]
Not line by line, but preferably also not a generic comment like "some post processing updates". Something in the middle, like 2-3 lines explaining what this patch does.

And even if you're the sole maintainer, it's better to have descriptive commit messages than cryptic ones. I promise to read it before I take the PR ;)

**Comment by Asmodean-** [comment]
I feel like I'm doing this, simply for the sake of doing it, but fine ;p

Luckily this is a small commit ;p

* Fixed an old overlooked typo (scalar:scaler)
* Specified some function parameters as input only, for compiler's sake.
* Improved interpolation of the BlendGlow bloom type between light and dark pixels.
* Added a brightpass filter to the bloom to specifiy a light threshold that the bloom will affect.
* Improved some cross processing curve logic.
* Added pre luminance scaling before tone mapping takes place.
* Added both LDR & HDR variants to the tone map options.
* Removed clamping of the tone mapping output.
* Rearranged output of the gamma correction, for a more accurate transition of effects.
* Updated some option descriptions.
* Added the 'BloomCutoff' setting which can a alter the threshold offset for the bloom.
* Adjusted a few option defaults to compensate for logic changes.

**Comment by avih** [comment]
Much appreciated. Thanks :)

**Pull request merged**
