### PR TITLE
Add more profile x64 and more

### PR DESCRIPTION
**Pull request by Zangetsu38**
Add more profile x64 compatible for compilation 
disable profile actually incompatible for compilation x64 (disable, not removed, waiting fix compilation for activate this)
fix compilation x64 for gsdx

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
There is still a lot of work to do on the 64bit stuff before I feel comfortable having VS profiles for it, the work is currently being done by one of our linux devs, so when it's in a better state we can update the VS projects.

**Comment by Zangetsu38** [comment]
@refractionpcsx2 yes I know, I just added the profile of those who could compile without problem, that's all ^^

**Comment by refractionpcsx2** [comment]
Yeah, we can add this later, so i'll leave the PR open and waiting :)

**Comment by Zangetsu38** [comment]
@refractionpcsx2 ok :)

**Comment by gregory38** [comment]
What instruction set did you use ? x64 will be limited to SSE2 for a long time (in the hypothesis that we manage to port all asm code to x64).

**Comment by Zangetsu38** [comment]
@gregory38  tested all the instruction and compiled well.
But we can not test them again ^^

**Comment by refractionpcsx2** [comment]
@gregory38 we can't limit the recompilers to using certain registers, only the actual C code which shouldn't really have any impact i'd imagine.  Aside from that it should act the same as the 32bit version.

**Comment by gregory38** [comment]
There are the special code path in GSdx based on the _M_SSE* variable.

**Comment by refractionpcsx2** [comment]
oh i see what you mean, maybe Zangetsu38 only tested the main emulator? i dunno ;p

**Comment by Zangetsu38** [comment]
We can not test the x64 plugins, you need a x64 .exe for it, so for now we can not test it.

**Comment by refractionpcsx2** [comment]
So how do you know these profiles work?

**Comment by Zangetsu38** [comment]
@refractionpcsx2 I said it was compiling works, like those already in there, it is not tested either.

**Comment by refractionpcsx2** [comment]
Then you have a x64 exe if it's right :P

**Comment by Zangetsu38** [comment]
@refractionpcsx2 Yes ^^, if I had an .exe x64 could test the plugin.

**Comment by refractionpcsx2** [comment]
That's what I'm saying, if you've made x64 profiles and it compiles, you would have an x64 exe.

**Comment by Zangetsu38** [comment]
@refractionpcsx2 yes, it's just that the x64 profile pcsx2 can not works because of several errors: /
the "__asm" cause problem in x64, according to my research there are not x64 compatible.

**Comment by refractionpcsx2** [comment]
definitely not merging this then until that is all dealt with :P

**Comment by Zangetsu38** [comment]
@refractionpcsx2 No but this "PR" is no problem, it just activates the profile that compiles fine on x64, that's all ^^

**Comment by Zangetsu38** [comment]
The rest will have to see after ^^

**Comment by Zangetsu38** [comment]
@refractionpcsx2 I found this for __ASM in x64 https://msdn.microsoft.com/en-us/library/hb5z4sxd%28VS.80%29.aspx 
in x64 use MASM

**Comment by refractionpcsx2** [comment]
Visual Studio will do that by default, we don't need any external programs.

**Comment by Zangetsu38** [comment]
@refractionpcsx2 there need an external program for MASM?

**Comment by refractionpcsx2** [comment]
No, Visual studio comes with ASM compilers for 32 and 64bit. If it doesn't compile it is because the ASM is 32bit ASM and needs to be translated in the code before it will compile.

**Comment by Zangetsu38** [comment]
@refractionpcsx2  Ok, I let the developer then ^^

**Comment by turtleli** [comment]
I tidied up the VS project files a bit and added the 64-bit configurations while I was doing so. So I'm closing this PR.

**Pull request closed without merging**
