### PR TITLE
Qt: Hook up current translations

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Adds languages to language selection list, and fixes up some issues with ImGui glyph ranges.

### Rationale behind Changes

Localization support.

### Suggested Testing Steps

Test a couple of the translations. ImGui is difficult to test for now, since not many of the OSD messages are translated yet. But I did manually verify with some.

### CODE REVIEW

**Comment by IlDucci** [comment]
I'm not sure if this is the right PR, but I think PCSX2 has smoked something weird... 
imagen

**Comment by stenzek** [comment]
Is that on any particular language?

**Comment by IlDucci** [comment]
The test was done in Spanish (Spain).

**Comment by stenzek** [comment]
Good catch, I didn't test any of the non-CJK languages. Should be sorted now.

**Comment by kamfretoz** [comment]
The language don't seems to update at all on change, Arch Linux (AppImage)

image

**Comment by stenzek** [comment]
Yeah, I think Linux is broken, link mentioned it earlier too.

**Comment by stenzek** [comment]
Linux is sorted now (tested with CI AppImage).

**Pull request merged**
