### PR TITLE
CI: Remove Travis-CI and AppVeyor

### PR DESCRIPTION
**Pull request by xTVaser**
Travis-CI has been failing for over a week now, and I don't think there's intentions nor an incentive to fix it with Actions taking it's place.

Bring back the green checkmark? 
image

### CODE REVIEW

**Review by tadanokojin — APPROVED** [review]
#BringGreenBack

**Comment by tellowkrinkle** [comment]
If we're not fixing travis, we need to increase the minimum required cmake to 3.16, as one of the reasons it's failing is because the build doesn't work without PCH (which was added in cmake 3.16)

**Comment by arcum42** [comment]
That's odd, since it should just not precompile it, which is what it used to do all the time when you built pcsx2.

What I do see, looking at the travis failures, is that it's not finding libsamplerate, which isn't surprising because it's a new dependency due to one of the plugin merges.

**Comment by turtleli** [comment]
> That's odd, since it should just not precompile it, which is what it used to do all the time when you built pcsx2.

The non precompiled header build broke when #3782 was merged.

**Comment by tellowkrinkle** [comment]
When you enable PCH, the precompiled header is implicitly included by every cpp file

Some of our cpp files rely on things from the precompiled header but don't `#include` it

**Comment by tadanokojin** [comment]
Is 3.16 going to be too high? Looking at Debian stable it seems they're on 3.13 https://packages.debian.org/buster/cmake

**Comment by tellowkrinkle** [comment]
Personally I think we should keep non-PCH compatibility, and keep travis around to make sure we keep non-PCH compatibility

**Comment by xTVaser** [comment]
Would it not be better for someone to add an Actions configuration that tests non-PCH compatibility?  Travis only runs on master, so you'd only find out _after_ a PR merges if there is a regression.  If we are going to care about the results of Travis, it should be moved back to running on every PR.

**Comment by tellowkrinkle** [comment]
I think it's easiest to enable Travis on PRs, I don't think its speed was ever much of an issue since we get up to 5 builds running concurrently

**Comment by RedDevilus** [comment]
What about the new price changes especially for mac building? 
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by lightningterror** [comment]
Looks like Red is offering to cover our costs.
It would be nice to fix travis first.

**Comment by RedDevilus** [comment]
I mean if macOS builds are safe in the future? But i guess we can just look at Actions instead for those.

**Review by lightningterror — APPROVED** [review]

**Comment by tadanokojin** [comment]
tellow took care of no-pch build in #3942 so this just needs to drop the no pch commit and rebase and and it should be good.

**Pull request merged**
