### PR TITLE
OSD: Change the lower limit of OSD Scale from 100 to 50

### PR DESCRIPTION
**Pull request by Berylskid**
### Description of Changes

Change the lower limit of OSD Scale from 100 to 50.

### Rationale behind Changes

Solved the problem of the OSD being obscured on small rendered window.

### Suggested Testing Steps

Change the OSD Scale to lower value than 100 to make sure what happens.

### CODE REVIEW

**Comment by stenzek** [comment]
This *could* cause issues with certain sizes/padding getting reduced to zero, but it should be floats for the most part.. have to try and see I guess.

**Comment by Berylskid** [comment]
Tested this build, and it worked fine for me at all.

**Comment by Berylskid** [comment]
>

**Comment by Berylskid** [comment]
> This _could_ cause issues with certain sizes/padding getting reduced to zero, but it should be floats for the most part.. **have to try and see** I guess.

Excuse me, does that mean lowering the lower limit to 0 instead of 50?

**Comment by refractionpcsx2** [comment]
No, it just means making sure nothing messes up at 50%.

**Comment by Berylskid** [comment]
All OSDs appear to shrink successfully for me at between 50% and 99%.

**Pull request closed without merging**
