### PR TITLE
Qt: Hook up screenshot button.

### PR DESCRIPTION
**Pull request by arcum42**
### Description of Changes
Hooks up the screenshot button/menu item in QT.

### Rationale behind Changes
The screenshot button should work.

### Suggested Testing Steps
Take a screenshot.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Still not working here.

**Comment by JordanTheToaster** [comment]
Does not work for me.

**Comment by arcum42** [comment]
Alright, suppose I'll need to build qt on Windows and test it then. Worked fine when I tried it in Linux.

**Comment by arcum42** [comment]
Assuming I can actually get the Qt version to compile in Windows, that is. It wasn't picking up on the copy of Qt 6.2 I had installed, so we'll see if updating helps...

**Comment by refractionpcsx2** [comment]
in windows I think you need to use the 6.3 pack we provide here: https://github.com/PCSX2/pcsx2-windows-dependencies/releases/tag/2022-04-13

**Comment by arcum42** [comment]
Ah, fun, no picking it up from environment variables. Alright, grabbing it from there, then.

**Comment by refractionpcsx2** [comment]
yeah if you extract the version folder in to 3rdparty/qt it should auto pick it up

**Comment by arcum42** [comment]
Yep, got it. Compiled, copied over my bios and a copy of Dark Cloud, showed the toolbar, started Dark Cloud, hit the screenshot button, and it saved a screenshot into snaps, so it seems like it's working for me in windows as well...

**Comment by refractionpcsx2** [comment]
can you download the windows artifact and extract it to a new folder so all the ini's etc are reset?

I certainly can't get it to work... I don't have media keys or anything, but pressing F8 does nothing, even though it's set up in the hotkeys.

**Comment by arcum42** [comment]
This is the screenshot button in the gui next to cheats, not F8.

**Comment by refractionpcsx2** [comment]
oh right, do you wanna hook up the hotkey as well then? :P I didn't even know there was a button lol

**Comment by refractionpcsx2** [comment]
Can confirm the button works, now I know exactly what you've hooked up :P (Guess I should have read the first post)

**Comment by arcum42** [comment]
Yeah, I was mostly concerned about getting buttons that didn't do anything in the gui working. Didn't even realise the hotkey wasn't working. :P

I'll take a look.

**Comment by arcum42** [comment]
There we are, now the hotkey works, by my copying the same two lines of code I used for the button in place of a "TO DO" comment...

**Comment by refractionpcsx2** [comment]
excellent lol, well if it works it works :D

**Comment by arcum42** [comment]
It's mostly a matter of popping up something saying we saved it, then calling the same function wx uses. I just had to figure out the qt version of getting the path instead of the wx version. Honestly, figured it would be easy enough, just no one'd gotten to it.

**Comment by refractionpcsx2** [comment]
Yeah, tbh I need to start chipping away at Qt stuff. I just don't know Qt at all, hate GUI stuff and I'm lazy, it's the tri-force of disappointment :D

**Comment by arcum42** [comment]
I learned a little bit of Qt for working with dobiestation, and I already know how to do gui stuff in gtk and wx, plus a little bit of imgui, and I used to know Carbon/Cocoa on the Mac. The more gui systems you know, the easier it tends to be to pick up another one...

I'll admit I'm not even sure what that cheats button that doesn't work is supposed to do, though. :P

**Comment by refractionpcsx2** [comment]
Not a clue, maybe it opens a cheats window? Idk :P @stenzek is the man to ask

**Comment by arcum42** [comment]
Beyond the scope of this pr anyways, I suppose. As is fixing the silly string conversions we do here. Lets turn this path into a wxString, which we turn into a char*, which we then turn into a std::string in the actual function. Great...

**Comment by refractionpcsx2** [comment]
Yeah, I presume all that will come with the pass of ripping out wxString, since the goal is to be able to cut WX out of the Qt build completely.

**Review by JordanTheToaster — APPROVED** [review]

**Pull request merged**
