### PR TITLE
GameDB: GS HW Fix XI

### PR DESCRIPTION
**Pull request by RedDevilus**
### Description of Changes

- Atelier Iris 3 - Grand Phantasm
- Baldur's Gate - Dark Alliance 1 / 2
- Call of Duty 2 - Big Red One
- Dark Cloud 1 / 2
- Mana Khemia 1 / 2
- Sims 2 - Castaway
- Valkyrie 2 - Silmeria
### Rationale behind Changes

Less tinkering.
### Suggested Testing Steps

Test this Square Enix game called Valkyrie 2. + other games.

### CODE REVIEW

**Review by JordanTheToaster — APPROVED** [review]

**Comment by RedDevilus** [comment]
Hmm, full roundsprite seems indeed better. I'll change it ASAP.

**Comment by Neirene** [comment]
Screen Shot 2022-03-24 at 14 42 18
Screen Shot 2022-03-24 at 14 46 02
Screen Shot 2022-03-24 at 14 46 34


Screen Shot 2022-03-24 at 14 45 36

With the same settings (x3 upscale) areas without too many glow effects such as some towns will look very sharp but the ones with effects will look very blurry and buggy, in this game the majority are the later.

**Comment by refractionpcsx2** [comment]
well, you're using patches to remove the effects, so I don't really count that. Try again without your patches and then we can consider it.

**Comment by Neirene** [comment]
> well, you're using patches to remove the effects, so I don't really count that. Try again without your patches and then we can consider it.
Screen Shot 2022-03-24 at 17 28 28
All I did was just enabling this setting (and change to 3x the upscaling) isn't that "Round Sprite" setting what you guys were testing here?

**Comment by Dreadmoth** [comment]
Trilinear filtering might not be ideal for Baldur's Gate Dark Alliance / Champions of Norrath.

The only combination of settings that cause trilinear filtering to affect the fonts at all for me is:
• Vulkan renderer
• Texture filtering set to anything other than Bilinear (Forced)
• GPU palette conversion disabled

...which produces a result almost identical to setting Bilinear (Forced) texture filtering (without trilinear), but with a significantly larger hit to performance (54 FPS vs. 37 FPS in one heavy scene in Champions).

----
FMV software renderer switch may be unnecessary for the PAL versions of Baldur's Gate: Dark Alliance and Dark Alliance II - the videos [look fine](https://user-images.githubusercontent.com/8492684/159969448-826f9a31-8de7-4f1f-bc28-19f3af919901.png) on all hardware renderers for me.

**Comment by RedDevilus** [comment]
@Dreadmoth Yeah, I just removed trilinear as it's more a mess to deal with.

**Comment by refractionpcsx2** [comment]
The Baldurs gate font issues are more upscaling problems, trilinear is like a very bad plaster to cure covid.

**Pull request merged**
