### PR TITLE
GSdx: Rearrange HW Hacks

### PR DESCRIPTION
**Pull request by lightningterror**
New arrangement is done in alphabetical order.
Windows only atm.

Visual preview.
image

### CODE REVIEW

**Comment by gregory38** [comment]
Why not. On linux, I kept HW upscaling hack together.

**Comment by lightningterror** [comment]
Mainly because I can't test and see how it is. Can I have a pic to see how it looks on Linux atm?
And I'll start doing my thing :laughing:

**Comment by lightningterror** [comment]
Updated with Linux changes.

**Comment by gregory38** [comment]
It should be good. I want to check the GUI on Linux before the merge.

**Pull request merged**
