### PR TITLE
Change the word "Enable" to "Apply" in widescreen patches and no-interlacing patches settings

### PR DESCRIPTION
**Pull request by karasuhebi**
### Description of Changes
Removed the word "Enable" from two different checkboxes.

### Rationale behind Changes
The word enable is redundant here. It is implied that the patches are enabled when the box is checked. That's how the rest of the settings in this window work (except for Interlace Offset which, IMO, should be reworked as well to not include the word "Disable")

### CODE REVIEW

**Comment by stenzek** [comment]
I'm not really sure I agree. The other options directly affect the behaviour of PCSX2 (e.g. anti-blur), whereas patches control whether a patch is enabled, which then affects the behaviour of the game.

**Comment by refractionpcsx2** [comment]
tbh I think removing the Enable makes it more implicative that your game will be made widescreen. if anything I'd change it to "Allow", but at this point we're just bikeshedding what it should say :P

**Comment by karasuhebi** [comment]
OK yes, now that you explain it that way (that it affects the behavior of the game, not the emulator) I do see your point.

My main gripe was honestly the fact that it had the word "Enable" so that when you ask someone to enable the option, you're saying "Enable the 'Enable Widescreen Patches' option" which sounds silly. I like ref's suggestion of changing it to "Allow" though. What do we think of that?

**Comment by stenzek** [comment]
It's not really allowing it either - it's not like the default action is to deny, the default action is to not even look for patches to begin with.

Like I said above, the option really needs to be scrapped anyway. It also doesn't make sense for patches for different aspect ratios (I believe there are some now); which one loads?

**Comment by Berylskid** [comment]
How about 'Apply'? Personally, it sounds closer than 'Allow', especially for patches.

**Comment by karasuhebi** [comment]
I really like "Apply" honestly. stenzek would you say it would make sense to use "Apply" instead of "Enable" for now while we wait and see if these global options are to be removed at the end of the day? Or just leave it alone for now?

**Comment by stenzek** [comment]
/shrug, whatever, apply is fine I guess. There's going to be resistance if we remove the option anyway.

**Comment by karasuhebi** [comment]
Change made.

**Pull request merged**
