### PR TITLE
GS/Vulkan: Prefer mailbox presentation for vsync-on

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Also some extra logging to gain some insight into #11280.

### Rationale behind Changes

Apparently users prefer stutter over tearing for PAL...

### Suggested Testing Steps

Smoke test Vulkan renderer.

### CODE REVIEW

**Comment by bigol83** [comment]
Looks good in every game i tested that had issues: Dragon Quest VIII, FF X, Dark Chronicle, vsync works, no more tearing, no stuttering either.

**Review by JordanTheToaster — APPROVED** [review]

**Comment by ichee** [comment]
This causes stuttering in NTSC games after extended play sessions (20min to an hour).

Occurs with both Vulkan HW and software, both tested in fullscreen.

Only way to stop it during current session is to toggle vsync off then on, but it will occur again after the same time interval.

Display refresh rate set to 59.94Hz

Windows 11
RTX 3090
Intel 14900K

**Comment by stenzek** [comment]
Then don't use vsync, or enable sync to host refresh (which will use FIFO instead of mailbox). I changed it to use mailbox over fifo relaxed because users were bitching about tearing, and now you're complaining about stuttering. Can't have it both ways.

**Comment by ichee** [comment]
Stuttering is much worse, reminiscent of the old pcsx2 stuttering issues.

Tearing can at least be taken care of by forcing vsync at the driver level.

Sync to host refresh causes unmanageable tearing in this PR, and runs at unlimited speed when used with vsync.

Mind, none of these issues were an issue before this PR.

**Comment by bigol83** [comment]
> This causes stuttering in NTSC games after extended play sessions (20min to an hour).
> 
> Occurs with both Vulkan HW and software, both tested in fullscreen.
> 
> Only way to stop it during current session is to toggle vsync off then on, but it will occur again after the same time interval.
> 
> Display refresh rate set to 59.94Hz
> 
> Windows 11 RTX 3090 Intel 14900K

Are you using exclusive fullscreen mode with Vulkan?

**Comment by ichee** [comment]
Borderless is the only fullscreen option available with vulkan and software.

Exclusive is only selectable with Direct3D.

**Comment by bigol83** [comment]
> Borderless is the only fullscreen option available with vulkan and software.
> 
> Exclusive is only selectable with Direct3D.

It's available for Vulkan too. 
image

**Comment by ichee** [comment]
Enabling that option still results in stuttering.

Testing with Legaia 2 Duel Saga.

You can toggle fast forward a few times to make the stuttering happen sooner.

**Comment by refractionpcsx2** [comment]
So is the problem just that you used sync to host before and that's tearing at the moment? if so we can look in to that.

The stuttering without shouldn't be any worse than it used to be, and the ultimate solution is always going to be get a VRR monitor, because that's the only way you can perfectly sync PS2 framerates with a PC monitor.

**Comment by ichee** [comment]
No. I didn't use sync to host previously because my refresh rate is 59.94Hz, so I didn't see a need.

Sync to host with this PR has tearing with vsync off, though I don't know how it was on previous builds.

With it on and with vsync on, framerate behaves as if it is set to unlimited. Changing the speed to anything else and back again restores proper limit, but just like vsync on only, it stutters.

Previous builds did not have this issue.

While looking at nvidia driver options in control panel, I noticed a setting `Vulkan/OpenGL present method`.

setting

With this option set to `Prefer layered on DXGI Swapchain`, the stuttering does not occur when using just vsync.



Not sure what the typical behavior for this should be, or if this is something that can be handled natively in pcsx2, but this seems to be a workaround for now if there is nothing else to be changed.

**Pull request merged**
