### PR TITLE
Gsdx texture format v2split

### PR DESCRIPTION
**Pull request by gregory38**
Based on #763: 

* Drop the 2 first commit that impact the AEM until I can test it properly.
* Drop the uniform optimization packing.
* Potentially fix a bad format check on fast-path LTF

It keep the following item:
* normalized coordinate for palette
* reduce uniform buffer state change
* fix the texturing filtering

### CODE REVIEW

**Comment by gendouhydeist** [comment]
@turtleli

can you recompile the plugin thanks!

**Comment by turtleli** [comment]
http://turtleli.unospace.net/GSdx32-texture-format-v2split-SSE2.7z

But someone who exclusively uses Windows should do this ;)

**Comment by gendouhydeist** [comment]
@gregory38 
No more missing textures, it works fine now. Just in case you need GSDump
https://drive.google.com/file/d/0B0xPvbkBqD9DcXB5M0xSSnVZeFE/view?usp=sharing

@refractionpcsx2 
561fa8a still flickers on DX11 but works fine on DX9
https://drive.google.com/file/d/0B0xPvbkBqD9DemNuN3QyNks5OUk/view?usp=sharing

**Comment by gregory38** [comment]
Ah good. I know dump take 5 seconds to generate but my SDD is full and it takes me hours (sometimes days) to found the issue. Besides in the previous case, dump was useless. Dump doesn't play well with the texture cache unfortunately

**Comment by refractionpcsx2** [comment]
@gendouhydeist this branch doesn't contain my changes to the nvidia hack.

**Comment by Kein** [comment]
Regression in SO3 fixed.

**Comment by gregory38** [comment]
ok. Is FFX12 texturing correct too?

**Comment by Kein** [comment]
From the games I tested only SO3 was broken.

**Comment by turtleli** [comment]
32-bit texture filtering issue, Suikoden {4, Tactics} is fixed.

**Comment by gregory38** [comment]
Perfect. Let's merge it. Now I need to understand this AEM stuff. It is really annoying :(

**Comment by bositman** [comment]
Tested Valkyrie Profile 2 forest map, looked just like SW :) Note: Didn't know the game needed ultra blending for some effects :S (save point effect)

**Comment by gendouhydeist** [comment]
Didn't see any difference effects on save point.
As for the forest there was a square lines on the screen.

**Comment by bositman** [comment]
Huh I can't seem to be able to replicate it now, and it also happened with a FFXII save point once..
The lines you get are because you are using scaling which is not what we are testing here. In native it looks perfect.

**Comment by gregory38** [comment]
ultra must only impact that need a special rounding of 16 bits textures. Hopefully a few (technically I can always do it but quality suck).

**Pull request merged**
