### PR TITLE
Travis CI and Appveyor continuous integration

### PR DESCRIPTION
**Pull request by turtleli**
I probably should have done this a lot earlier.

I've added yml files for setting up Travis CI and Appveyor. What they currently do:
 - Travis CI - compile tests with gcc-4.9 and clang-3.7. gcc 5.1 and 5.2 spam errors and Travis CI terminates after logs reach 4mb, so they're unusable.
 - AppVeyor - compile tests and creates downloadable release builds with VS2013 and VS2015, which should help with having PRs tested.

This can be changed to cover more/less configurations, or to include/exclude specific branches (I've left it generic enough so other contributors can test their work compiles if they have Travis CI/AppVeyor setup before sending a PR).

Both provide build logs so if compilation fails, you know what the error is.

Someone will still need to do the final setup, which I can't do since I don't have admin level access (necessary for adding repository hooks).

### CODE REVIEW

**Comment by gregory38** [comment]
```
 gcc 5.1 and 5.2 spam errors and Travis CI terminates after logs reach 4mb, so they're unusable.
```
Any partial logs? Maybe it can be improved a bit or are the previous apt command too verbose (maybe there are some quiet options) 

```
Someone will still need to do the final setup, which I can't do since I don't have admin level access (necessary for adding repository hooks).
```
What must be done?

**Comment by ssakash** [comment]
> What must be done?

 I think Turtleli meant the Appveyor/ TravisCi integration process to the PCSX2/pcsx2 repository.

**Comment by turtleli** [comment]
gcc-5.1, gcc-5.2 - it's an bug that's fixed upstream (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65974). On my Slackware boot it causes 14MB logs (I've since patched gcc 5.2 on my system) when I do a clean compile

Final step is just to give Travis CI and Appveyor the necessary permissions to install repository hooks and to configure it to build only branches with the yml files. You can also choose whether they should build just PRs and if they should also build when commits are pushed to the repository.

**Comment by ssakash** [comment]
Question: Is it also necessary to do a VS2013 build ? would dropping VS2013 build minimize the compilation time taken ?

**Comment by turtleli** [comment]
I figure we still support compiling with VS2013, so yes.

**Comment by gregory38** [comment]
I didn't know that we have deprecated stuff. I will try to look for the permission (any link to where I configure it)

**Comment by ssakash** [comment]
https://github.com/integrations

**Comment by gregory38** [comment]
Ok thanks. I will do it after the merge.

**Comment by turtleli** [comment]
The only real deprecated stuff is some of the gdk_pixbuf stuff (I'll provide messages later) since gdk-pixbuf 2.32. The others are false warnings. I'll post the relevant messages later.

**Comment by turtleli** [comment]
Updated. Builds with gcc-4.9, gcc-5.2 and clang-3.7.

Renamed .travis.sh to travis.sh - I didn't put it in linux_various because we can potentially use Travis CI for OS X in the future.

Oh, and the only deprecated warning seems to be:
```
/home/turtleli/pcsx2/plugins/GSdx/GSLinuxDialog.cpp: In function ‘bool RunLinuxDialog()’:
/home/turtleli/pcsx2/plugins/GSdx/GSLinuxDialog.cpp:526:27: warning: ‘GdkPixbuf* gdk_pixbuf_from_pixdata(const GdkPixdata*, gboolean, GError**)’ is deprecated [-Wdeprecated-declarations]
  GdkPixbuf* logo_pixmap = gdk_pixbuf_from_pixdata(&gsdx_ogl_logo, false, NULL);
                           ^
In file included from /home/turtleli/pcsx2/plugins/GSdx/GSLinuxLogo.h:23:0,
                 from /home/turtleli/pcsx2/plugins/GSdx/GSLinuxDialog.cpp:26:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^
```

**Comment by gregory38** [comment]
Of course gdk stuff was too  easy :(  Future API is https://developer.gnome.org/gio/unstable/GResource.html

**Comment by gregory38** [comment]
Ok let's merge it. It can still be improved later anyway.

**Comment by gregory38** [comment]
I added travis. Appveyor is more complex. Do I need to setup an env?

**Comment by turtleli** [comment]
Appveyor seems to be working, though it's tied to your Github user account.

To allow other people access to the settings you can use https://ci.appveyor.com/team , though you might prefer to create an specific Appveyor account and add users. The process is quite unclear to me. Some more documentation is available at http://www.appveyor.com/docs/team-setup

**Comment by willkuer** [comment]
Maybe some general questions:
How is the build process triggered? Upon new PR or merge or manually? Is only the main repo built or can we use it as well to test branch builds? Is this just like orphis build bot?

**Comment by turtleli** [comment]
By default both Travis CI and AppVeyor will build for both PRs and all branches. It can be tweaked to build only PRs and/or only specific branches.

Travis CI and AppVeyor should automatically run for new PRs. If a PR doesn't need to be tested (e.g. documentation changes), you can use [skip ci] to prevent both from running.

Old PRs can be built by rebasing/adding new commits, but that's only a temporary problem.

**Comment by gregory38** [comment]
hum, travis automatically build the latest commit (and send me an email) but maybe it is also linked to my account. I'm not sure on appveyor because I asked to do a build (just click on every flashy button ;) ).

**Comment by willkuer** [comment]
This is really a great feature!
Thanks for sharing with the us.

**Comment by turtleli** [comment]
I think the .travis.yml can be edited so it doesn't send emails or sends emails when the build status changes (e.g. from pass to fail). For AppVeyor you need to change the settings.

It seems I can edit the Travis CI settings, so I think I can cancel/reschedule runs for any new/updated PRs on my end if they fail for silly reasons.

**Comment by gregory38** [comment]
No worry I'm fine with the email. However I don't know if everybody receive it or only me.

**Comment by turtleli** [comment]
From https://docs.travis-ci.com/user/notifications/

> By default, a build email is sent to the committer and the author, but only if they have access to the repository the commit was pushed to. This prevents forks active on Travis CI from notifying the upstream repository’s owners when they’re pushing any upstream changes to their fork. It also prevents build notifications from going to folks not registered on Travis CI.

So I think only we're the only ones who might receive email from Travis CI, unless some of the others have steathily signed up ;)

**Comment by gregory38** [comment]
Ok. So it works as expected at least for me ;)

**Comment by gregory38** [comment]
I added PCSX2 team in appveyor.

**Comment by gregory38** [comment]
@turtleli 
The build seems to be fired ^^
However it seems there are some issue
```
+sudo apt-get -qq update

+sudo apt-get -qq -y install gir1.2-freedesktop:i386 gir1.2-gdkpixbuf-2.0:i386 gir1.2-glib-2.0:i386 libcairo2-dev:i386 libgdk-pixbuf2.0-dev:i386 libgirepository-1.0-1:i386 libglib2.0-dev:i386 libaio-dev:i386 libasound2-dev:i386 libgl1-mesa-dev:i386 libgtk2.0-dev:i386 liblzma-dev:i386 libpng12-dev:i386 libsdl2-dev:i386 libsoundtouch-dev:i386 libwxgtk3.0-dev:i386 libxext-dev:i386 portaudio19-dev:i386 zlib1g-dev:i386 g++-4.9-multilib

E: Unable to correct problems, you have held broken packages.

The command "./travis.sh before_install" failed and exited with 100 during .

Your build has been stopped.
```

**Comment by micove** [comment]
Oh, travis now has trusty support. Last time I checked they were stuck with Ubuntu 12.04 (precise).

**Comment by willkuer** [comment]
Do we still need the (orphis-)buildbot or can we use AppVeyor instead to comüile windows executables?

**Comment by turtleli** [comment]
Well, I don't see the harm in having both.

**Pull request merged**
