### PR TITLE
OSD: Add option to show PCSX2 version

### PR DESCRIPTION
**Pull request by kamfretoz**
### Description of Changes

This PR adds an option to show the current PCSX2 version on the OSD.

Preview:
Screenshot_20240216_234856

### Rationale behind Changes

For those who want to show the currently running PCSX2 version directly from the OSD.
(ex: handheld devices with more BPM usage in mind).

### Suggested Testing Steps

Test said functionality, and the version shown are correct.

### CODE REVIEW

**Comment by stenzek** [comment]
I'd question why this is necessary; it's just further crowding an already-bloated tab (OSD), and I don't really see why anyone would want to have this visible at all times.

The use case you mentioned (BPM) already shows the version in the main menu.

**Comment by lightningterror** [comment]
I was thinking the same thing.

**Comment by refractionpcsx2** [comment]
> I'd question why this is necessary; it's just further crowding an already-bloated tab (OSD), and I don't really see why anyone would want to have this visible at all times.
> 
> The use case you mentioned (BPM) already shows the version in the main menu.

I think the BPM idea was so the user can show the game running shit, with the version on the screen, not going off to a menu

**Comment by stenzek** [comment]
Right, but to get to the game in the first place, they have to go via the main menu, which shows the version in the corner.

I guess we could add it to screenshots? But that would be something better tied into a "generate support info" type feature, with system specs etc also embedded.

**Comment by kamfretoz** [comment]
Closed as this have been veto'd.

**Pull request closed without merging**
