### PR TITLE
GameDB:  some fixes

### PR DESCRIPTION
**Pull request by nishinji**
### Description of Changes

Enclose the strings by quotation marks
Remove (some) symbols from name-sort that are not read aloud
This is for NTSC-J

### Rationale behind Changes

More consistent code rules
Sorting should be determined by actual pronounce

### Suggested Testing Steps

It is tested on my pc

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Not sure why you're removing brackets from the types of disc? We've pretty consistently done that through the whole DB, but you removed a couple? Doesn't make sense. I'd rather they were there, tbh,

**Comment by nishinji** [comment]
> Not sure why you're removing brackets from the types of disc? We've pretty consistently done that through the whole DB, but you removed a couple? Doesn't make sense. I'd rather they were there, tbh,

Alright. I'll revert it when I have time.

**Review by lightningterror — CHANGES_REQUESTED** [review]
Seems like you messed something up and modified the entire db, could be line endings.
Anyway can you make sure you're only modifying what needs to be modified?

**Comment by nishinji** [comment]
Git is working property I expect
image
Sorry my typo. I regret my folly of using the master branch...

**Review by lightningterror — APPROVED** [review]
Looks good now.

**Pull request merged**
