### PR TITLE
GUI:fix capitalisation in GUI

### PR DESCRIPTION
**Pull request by Mrlinkwii**
fixes capitalisation in GUI

### CODE REVIEW

**Review by RedDevilus — APPROVED** [review]
Commit of the year.

**Comment by refractionpcsx2** [comment]
idk, this might need a few weeks of testing

**Comment by lightningterror** [comment]
> idk, this might need a few weeks of testing

Will it make it for 1.8 tho?

**Comment by tadanokojin** [comment]
This is going to need approval from greg: it's above my pay grade.

**Pull request merged**
