### PR TITLE
pcsx2: generate an exception when recompilation failed

### PR DESCRIPTION
**Pull request by gregory38**
Avoid the cost of checking -1 for a very rare case.

It misses currently a good fallback

@refractionpcsx2, 
What do you think about it? Maybe we can just call opcode.interpret but I'm not sure.

### CODE REVIEW

**Comment by gregory38** [comment]
Something like that
```			
iFlushCall(FLUSH_INTERPRETER);
CALLFunc((uptr)opcode.interpret);
```

**Comment by gregory38** [comment]
``` lookup for the op though ```
Lookup of what exactly? For me interpret is the function pointer of the current opcode. Or did I misunderstand something?
```
// Process the instruction using the interpreter.
// The action is performed immediately on the EE's cpu state.
void (*interpret)();
```

**Comment by gregory38** [comment]
So I try to force the error. Just commented this part of the code
```
	//if( tempi != -1 ) {
	//	_freeXMMreg(tempi);
	//	return tempi;
	//}
```

I got several error message as expected and GoW is still booting. However it hits some assertions on register
```
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
/home/gregory/playstation/emulateur/pcsx2_merge/pcsx2/x86/iCore.cpp(957) : assertion failed:
    Function:  void _freeXMMregs()
    Thread:    EE Core
    Condition: xmmregs[i].type != 0

[00] _freeXMMregs()                               /playstation/emulateur/pcsx2_merge/pcsx2/x86/iCore.cpp:957
[01] iFlushCall(int)                              /playstation/emulateur/pcsx2_merge/pcsx2/x86/ix86-32/iR5900-32.cpp:1066
[02] recompileNextInstruction(int)                /playstation/emulateur/pcsx2_merge/pcsx2/x86/ix86-32/iR5900-32.cpp:1482
[03] recRecompile                                 /playstation/emulateur/pcsx2_merge/pcsx2/x86/ix86-32/iR5900-32.cpp:2130
[04] 0x0x9f72024                                 
[05] 0x0x9f72070                                 
[06] ScopedPtr<BaseR5900Exception>::operator BaseR5900Exception*() const /playstation/emulateur/pcsx2_merge/common/include/Utilities/ScopedPtr.h:106
[07] AppCoreThread::DoCpuExecute()                /playstation/emulateur/pcsx2_merge/pcsx2/gui/AppCoreThread.cpp:558
[08] SysCoreThread::ExecuteTaskInThread()         /playstation/emulateur/pcsx2_merge/pcsx2/System/SysCoreThread.cpp:260
[09] Threading::pxThread::_try_virtual_invoke(void (Threading::pxThread::*)()) /playstation/emulateur/pcsx2_merge/common/src/Utilities/ThreadTools.cpp:545
[10] Threading::pxThread::_internal_execute()     /playstation/emulateur/pcsx2_merge/common/src/Utilities/ThreadTools.cpp:645
[11] Threading::pxThread::_pt_callback_cleanup(void*) /playstation/emulateur/pcsx2_merge/common/src/Utilities/ThreadTools.cpp:169
[12] 0x0xf5fdcefb                                
[13] clone                                       

*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
*PCSX2*: XMM Reg Allocation Error in _getFreeXMMreg()!
```
Conclusion it seems to work but register status is not 100% clean.

**Comment by refractionpcsx2** [comment]
> but register status is not 100% clean.

How do you mean? That looks like it's doing it's job.

**Comment by gregory38** [comment]
dunno :p maybe the assert appears due to my error injection.
The question is "do we need to clean/free register in the catch part ?". However there is a potential issue. I guess we could generate N x86 instruction to generate the EE opcode. If we threw an exception during the compilation of the latest x86 instruction, previous operation mustn't be executed. Otherwise I suspect the flush will pollute the EE-CPU register.

**Comment by refractionpcsx2** [comment]
We would need to free up anything that had been done before the exception was thrown yes, problem being the flushcall might see the newly allocated registers and try and copy their non-existent content (or wrong content) back to the corresponding GPR regs, (like you say, it will pollute it) so we will need to de-allocate anything that has been done before the flush, but only on that instruction, if the GRP was already live in the X86/XMM regs, you wouldn't want to touch it as that wouldn't be dirty data.

**Comment by gregory38** [comment]
what about saving the x86 before opcode instruction generation. It just need a "rewind" in the catch,

**Comment by refractionpcsx2** [comment]
because you would have to do that for every op and that would be slowwwwwwwwwwww

**Comment by refractionpcsx2** [comment]
oh do you mean roll the buffer back? hmm okay maybe that could work...  Maybe the solution in the long term will be to do current op generation in a temp buffer and then write it to the rec code buffer once complete, for safety :p

**Comment by gregory38** [comment]
Yes I mean save the x86ptr before the compilation of the instruction. Then restore it in case of exception, so only latest EE instruction is erased/overwritten.

It feels faster to store a single pointer than to copy buffer data. Besides I think that various functions uses the value of the pointer (memory dispatcher), or maybe it was relative jump. Don't remember :p

**Comment by refractionpcsx2** [comment]
yeh the pointer value is stored for jump locations, we would need to keep a note of the pointer position at the start of the instruction and roll it back if it fails i guess :P

**Comment by gregory38** [comment]
I tried this patch. Rendering is broken if I enable the x86SetPtr statement. What did I miss?
```
diff --git a/pcsx2/x86/ix86-32/iR5900-32.cpp b/pcsx2/x86/ix86-32/iR5900-32.cpp
index 1d1c9c1..e17d7e5 100644
--- a/pcsx2/x86/ix86-32/iR5900-32.cpp
+++ b/pcsx2/x86/ix86-32/iR5900-32.cpp
@@ -1476,14 +1476,16 @@ void recompileNextInstruction(int delayslot)
        else {
                //If the COP0 DIE bit is disabled, cycles should be doubled.
                s_nBlockCycles += opcode.cycles * (2 - ((cpuRegs.CP0.n.Config >> 18) & 0x1));
+
+               u8* rewindPtr = x86Ptr;
                try {
                        opcode.recompile();
                } catch (Exception::FailedToAllocateRegister&) {
-                       // TODO: fallback to interpreter
-#if 0
+                       // Discard recompiled code of the current instruction
+                       //x86SetPtr(rewindPtr);
+                       // Fall back to the interpreter
                        iFlushCall(FLUSH_INTERPRETER);
-                       CALLFunc( (uptr)R5900::Interpreter::OpcodeImpl::MMI::PMFHL );
-#endif
+                       CALLFunc((uptr)opcode.interpret);
                        // TODO: Free register ?
 #if 0
                        //      _freeXMMregs();
```

**Comment by gregory38** [comment]
Hum, I think we have similar issue with the register content. We need to "checkpoint" the register status before the instruction execution. It isn't going to work. I guess a better idea will be to discard completely the full block, and just run the interpreter on the block.  This way, we don't need to flush register.

**Comment by refractionpcsx2** [comment]
yeh, but if this does happen a few times then it's going to make games rather slow.

By the point it fails, nothing should be written as it's just in the reg allocation phase which is before any processing is done,  so just clearing any temp ones should be enough.

**Comment by gregory38** [comment]
Hum. We still need to write the output of previous instruction, no?
Let's take the following example (of my understanding).
```
Block B1
   COMPILE INS I1
       ALLOC register
       GEN X86
   COMPILE INS I2
       ALLOC register <= will fire an exception
      GEN X86
   COMPILE INS I3
      ALLOC register 
      GEN X86
   FLUSH
BLOCK B2
 ...
```
Must be compiled into
```
X86_1
FLUSH
INTERPRETER
X86_3
FLUSH
...
```

If I understand you, 
1/ we can drop the content of the temp register. IMHO, we ought to set inuse = 0 in _freeXMMreg (and equivalent function) when the type is TEMP, what do you think? So the assertion is normal.
2/ Flush the GPR (and others physical) registers, populated by I1.

However I don't understand why the rewinding of the x86ptr breaks everything.

**Comment by refractionpcsx2** [comment]
I think there's a function for clearing the temp regs, but yeh rewinding "should" work.

the reason I "think" it's failing, because things have been pushed out of the registers and other things added, but by rewinding it will "forget" this, but the recompiler wont, meaning what the recompiler is compiling and what the x86 buffer is saying is 2 different things.

**Comment by gregory38** [comment]
Yes, I understand. The status of register use/inuse/loaded isn't in-sync anymore with the value really loaded. I guess it is related to the g_pCurInstInfo/s_pInstCache structure.

Looking at the x86 generated code, I can see some "movaps". So I guess the only instructions are the loading/saving of registers. I'm not sure anymore that we need to rewind, basic implementation must work (as it is currently).

**Comment by refractionpcsx2** [comment]
We could probably get away with it loading in the stuff to the registers then running the interpreter, it will keep things in sync.  Only recompiled performance would suffer slightly from my thought :)

**Comment by gregory38** [comment]
I don't think that it will impact performance to load a couple of registers. I mean we normally don't want to execute this code. It is just a security in case we fail to compile an instruction.

**Comment by refractionpcsx2** [comment]
Well indeed, afaik this doesn't happen, ever, so the impact if it does happen will be small, all I mean is obviously the idea of a recompiler is to make as optimized x86 code as possible :)  But this should work absolutely fine :)

Hopefully Coverity likes it lol

**Comment by gregory38** [comment]
Yeah, it's just to be bullet proof in case in become crazy for no reaons.

**Comment by refractionpcsx2** [comment]
Excellent, that should get rid of a bunch of Coverity issues :)

**Comment by gregory38** [comment]
Yes coverity report plummets => 78 closed, 1 opened.

**Comment by refractionpcsx2** [comment]
So I saw lol, should be fixable :)

do you wanna work on that texture cache resource leak?

**Comment by gregory38** [comment]
It isn't a leak. Code is ugly (hence coverity is lost) but it is working.

**Comment by refractionpcsx2** [comment]
Ok in that case mark it as intentional and ignore :)

**Comment by gregory38** [comment]
I prefer to keep it open. Potentially code can be improved. It is a potential improvement for the future.

**Pull request merged**
