### PR TITLE
Gsdx unsafe fbmask

### PR DESCRIPTION
**Pull request by gregory38**
Miss a nice windows option otherwise it greatly help xenosaga 1 (and likely various *bad* game)

Accurate: 27 fps
Unsafe accurate: 70 fps
Inaccurate: 130 fps

### CODE REVIEW

**Comment by ramapcsx2** [comment]
I can imagine on Windows this could be made one of the various blending accuracy levels. Maybe one step above none.

**Comment by gregory38** [comment]
No, I prefer to separate it. At least for the moment. I want to know if it generate rendering corruption.

**Comment by ramapcsx2** [comment]
Okay, we should provide a named .dll for Windows users and give it to bug squad.

**Comment by gregory38** [comment]
You can have one with orphis bot ( and maybe appveyor but I didn't find where). Otherwise it can be merged safely as the code is protected with an option.

**Comment by gregory38** [comment]
http://bositman.pcsx2.net/gregory_pull_request/pcsx2-v1.3.1-1604-g8d70588-windows-x86.7z

**Comment by tsunami2311** [comment]
@gregory38 yah i never seeing in there i wll test the above link and see how it compared to initial build i linked that had the blend accuracy options with out the  pull down menu

**Comment by gregory38** [comment]
Either the effect was wrongly emulated or wrongly accelerated.

Could you tell me the FPS in the 3 cases ? In native and in your uspcaled resolution?
The 3 cases are
BA = none
BA = basic without hack
BA = basic with hack

I would like to know if it is a GPU or a CPU limitation.

**Comment by tsunami2311** [comment]
will do give me few to redownload the build again, Do you want to to note  GUI had checked and what the INI was for blend too? and you said the hack had to be enabled manual in the ini too? i didnt do that with above test. i get back to with the results

**Comment by gregory38** [comment]
Yes you need to do add the config manually. But no need to test it, I saw some pretty bad draw calls. I need to check them first.

**Comment by gregory38** [comment]
Ok I pushed a small change that would take of the remaining slow down.

**Comment by tsunami2311** [comment]
Build f4e881a 
Accurate Blend=checked
accurate_blend=1 ( not sure why when enabled in ui this is listed at 1 in the ini bugged maybe?)
No limit on FPS
Native= 100fps give or take
3x=100 give or take

Build 8d70588
BA=Basic with out hack
accurate_blending_unit=1
no limit on fps
Native=50 fps give or take

BA=None
accurate_blending_unit=0
no limit on fps
Native=100 fps give or take

This above test i got from the to build i got these before said not to both so get them anyway, not sure what hack was UserHacks_unsafe_fbmask=1 or UserHacks_unsafe_fbmask=true? both resulted in same fps i didnt close and open pcsx2 completely when chaning the ini ( do i need to? ), tell me when you want to me to do more test

**Comment by gregory38** [comment]
Could you test the build bb5cf7e ? Do you need a binary?

**Comment by tsunami2311** [comment]
if by binary you mean it build yes

**Comment by gregory38** [comment]
Could you search here https://ci.appveyor.com/projects
The bot is quite slow (likely need 1H or 2), but you can normally download compiled stuff from it.

First select the commit. Then select win VS2015 or VS2013. Then go in artifact tab.

**Comment by tsunami2311** [comment]
i download the files one and tried to compile but is said i missing stuff i only have run times installed from the all in 1  VS download i have in my sig on forums, i try again though

**Comment by tsunami2311** [comment]
yah i sign in to the  https://ci.appveyor.com/projects found nothing there i will just wait for the build, just post in here

at later time some can explain that to me

**Comment by gregory38** [comment]
Yes, the bot is quite slow, need to wait.

**Comment by gregory38** [comment]
https://ci.appveyor.com/project/gregory38/pcsx2/build/1.120-gsdx-unsafe-fbmask/job/7o82dmpksj2ym9r9/artifacts

**Comment by tsunami2311** [comment]
ok you just want the test result from this build?

and it is 
UserHacks_unsafe_fbmask=1 "enable" and do i close out restart pcsx2 after editing in or does it work on the fly?

**Comment by gregory38** [comment]
Toggle the render 2 times with F9 and it will be good. Normally you will have a huge speed difference.

**Comment by tsunami2311** [comment]
No limit
Blend=none
100 fps ish @ native
100 fps ish @3x

No limit
Blend=Basic
50 fps is @ native
37 fps ish @ 3x

No limit
Blend=basic with hack
100 fps ish @ native
100 fps ish @ 3x

looks good,  on my end, bet this make more sense then the explains of things i found to be happen with the whole opengl runing in fullscreen exlcusive with 16:9~stretch mess hah

**Comment by gregory38** [comment]
@ssakash is there any possibilities to add a new hack ?

@tsunami2311 
Ok great, results are much nicer :)

**Comment by tsunami2311** [comment]
if there anything else u want me to test just let me know, again sorry if testing method and explains get confusing, explain things not something i good at

**Comment by gregory38** [comment]
Yes it is difficult for me to parse your writing ;) I'm good. Just check there is no strange glitches. The current hack isn't allowed by the spec. So it could generate some strange results.

**Comment by tsunami2311** [comment]
gitches in other games i gather?

**Comment by gregory38** [comment]
Yes. But you need that uses a special fbmask on the alpha channel only. I saw it on a couple of gs dump. I don't think the effect is often use.

**Comment by tsunami2311** [comment]
i will test VP2 only game i can think of that might think that might have those issue, that i have

**Comment by danilaml** [comment]
For the record: https://ci.appveyor.com/project/gregory38/pcsx2/history
Find needed commit here (or if you need just build for pr just press details on one of checks: 
image )
And go to artifacts: 
image
@gregory38 would be cool if appveyor and travis badges would be added to readme.md

**Comment by ssakash** [comment]
> Is there any possibilities to add a new hack ?

sorry for the delay, haven't really been having much of a free time recently.

https://github.com/ssakash/pcsx2/commit/c3723a01577e2aac24b2e38757826e9efe4e32ae

**Comment by gregory38** [comment]
@danilaml 
badges ???

@ssakash thanks. The report is more important ;)

**Comment by danilaml** [comment]
@gregory38 like this: 
image
https://docs.travis-ci.com/user/status-images/
http://www.appveyor.com/docs/status-badges/
Or just http://shields.io/

**Comment by ssakash** [comment]
@gregory38 : here's one rebased with master https://github.com/ssakash/pcsx2/commit/62cb8a4a09f5f82a12f0847664e9cd0b5293640f

I actually forgot to do a Git fetch before the rebase so it seemed to not consider turtleli's recent change on GSdx resource script file. should be fixed now. https://github.com/ssakash/pcsx2/pull/14

**Pull request merged**
