### PR TITLE
Use system libzip

### PR DESCRIPTION
**Pull request by guoyunhe**
### Description of Changes

By searching for system libzip, we can increase build speed and decrease binary size on Linux.

### CODE REVIEW

**Comment by stenzek** [comment]
I specifically removed this some time ago because of incompatible versions.

**Comment by Mrlinkwii** [comment]
this will cause issues with systems with incompatible versions

**Comment by guoyunhe** [comment]
@stenzek @Mrlinkwii it is possible to explicit use system libzip by add a new option `USE_SYSTEM_LIBZIP` (OFF by default) and let users decide if they want to use system libzip.

**Comment by TellowKrinkle** [comment]
As an example of the issues that may arise, [Ubuntu libzip](https://packages.ubuntu.com/mantic/libzip4) has no zstd dependency, which means no zstd support, something we use by default for our save states.  Which means such a build would be unable to load a save state made using the appimage.

**Comment by refractionpcsx2** [comment]
Going to assume abandoned, bad idea anyways.

**Pull request closed without merging**
