### PR TITLE
Properly handle spaces in the build path

### PR DESCRIPTION
**Pull request by EmperorArthur**
Ex: /usr/local/Console Emulators/pcsx2/

While I've been watching this for a while now, this is my first contribution.
I apologize if I've done something against guidelines.

### CODE REVIEW

**Comment by willkuer** [comment]
Not sure here but dont you need to add the quotation marks either during initialization or everywhere where you use the variables but not both?

**Comment by EmperorArthur** [comment]
When just working from a bash prompt:
```
EMU=/usr/local/src/Console Emulators/pcsx2/
bash: Emulators/pcsx2/: No such file or directory
EMU="/usr/local/src/Console Emulators/pcsx2/"
cd $EMU
bash: cd: /usr/local/src/Console: No such file or directory
cd "$EMU"
```
So it looks like both are required.  At the very least, they don't hurt anything.

**Comment by willkuer** [comment]
I think at least [L114](https://github.com/EmperorArthur/pcsx2/blob/5252edcd0e75189bc433ef1d348ea50fdb096ae9/build.sh#L114) and [https://github.com/EmperorArthur/pcsx2/blob/5252edcd0e75189bc433ef1d348ea50fdb096ae9/build.sh#L116] need the same quotation marks. At least here on windows.

**Comment by gregory38** [comment]
Might be a better idea to just escape the space with an anti slash (but I didn't tested).

**Comment by EmperorArthur** [comment]
The problem with just escaping spaces is if there are any other characters that might be valid UTF-8 file names, but also cause path issues.

I'm more a fan of just straight encapsulation.  We know it's a single piece of data.  The script should know that as well.

**Comment by gregory38** [comment]
Ok. Could you rebase your change and squash your commit into a single one. Thanks.

**Comment by EmperorArthur** [comment]
Sorry I didn't rebase that.  It's been quite the week for me.

**Pull request merged**
