### PR TITLE
GameDB: Minor Updates and Additions

### PR DESCRIPTION
**Pull request by MrCK1**
After taking a closer look, it turns out my disk has a unique serial that wasn't in the database. 

As a bonus, It even says "Not For Resale" - thanks GameStop :P

### CODE REVIEW

**Comment by FlatOutPS2** [comment]
Usually games that come in a normal PS2 case and have Not For Resale on them are part of a collection boxset. Are you sure this wasn't included in one?

**Comment by MrCK1** [comment]
I didn't find any evidence that it was part of a boxed set, but one site did say that they were pre-order incentives for another game

**Comment by FlatOutPS2** [comment]
I had a look myself and couldn't find any evidence for a box/2 for 1 set either. I did find a promo copy for the xbox though, but that clearly had promotional copy written on the front and back of the case. But with no further evidence suggesting otherwise we'll have to assume it is just a normal promo copy then.

**Comment by refractionpcsx2** [comment]
This is all I can really find on it
http://www.eevideogames.com/catalog/playstation_2_ps2_games/midway_arcade_treasures__promotional_copy/493213

looks rare, hold on to that :)

**Comment by FlatOutPS2** [comment]
The promo in that link has a very noticable Promotional Copy note on the front cover just like the Xbox version. It should have Promo copy printed on the back as well. If it doesn't, I don't believe it's this version.

**Comment by MrCK1** [comment]
I couldn't find any images of the disk on Google; so here's mine ;) ![MATPromoDisk] (http://i.imgur.com/dg9jgDs.jpg)

**Comment by FlatOutPS2** [comment]
Yeah, it clearly says promotional copy on the disc. :p

**Comment by MrCK1** [comment]
I made a few more changes to the DB. Here's the new list of changes

- Added Midway Arcade Treasures (Promo Copy) to DB

- Changed "Test Drive" Compat from 5 to 2. Game never worked, dunno why…

- Changed "Band Hero" Compat to 5

- Changed "Jonny Moesely Mad Trix" Compat to 5

**Comment by FlatOutPS2** [comment]
Did you try the patch for Test Drive?

**Comment by MrCK1** [comment]
I'm not aware of a patch. Could you link me to it?

**Comment by FlatOutPS2** [comment]
Seems like there's only one for the PAL version, which might be outdated. But still worth a shot:
```
//skip FMV sceMpegIsEnd
patch=1,EE,0030aad0,word,24020001
```

**Comment by MrCK1** [comment]
I think it's the wrong game. It had no effect and I didn't see the patch anywhere in the GameDB.

[This game](http://forums.pcsx2.net/Thread-Test-Drive-SLUS-20213-U--29762?pid=401192&highlight=test+drive#pid401192) has never worked. It will get to a load screen with an interactive pong gane and never progress

**Comment by refractionpcsx2** [comment]
Can you try the simulate VIF FIFO? one of the later test drive games needs this

**Comment by MrCK1** [comment]
Test Drive Unlimited is the one that needs the VIF FIFO hack. I'm pretty sure I tried that one with no success.

Off the top of my head, this is what I remember:

-No asserts triggered or outstanding console feedback.

-EE Int and Rec had same results.

-sVU and Micro VU had same results.

-Various hacks had no effect

-CDVD plugin and ripped ISO both had same results 

I'll open a thread for this and get a dump/log up later tonight.

**Comment by refractionpcsx2** [comment]
hmm, don't suppose you can compile my pcsx2-gif-fifo branch and try the GIF FIFO gamefix could you?

**Comment by MrCK1** [comment]
I compiled the branch to no avail. The GIF FIFO branch output is the same as master branch :(



Last few lines ( [Here's the full log] (http://pastebin.com/MDcb4fDw) )
```
RegisterIntrHandler: intr INT_dmaSPU, handler 87020
RegisterIntrHandler: intr INT_dmaSPU2, handler 87020
RegisterIntrHandler: intr INT_SPU, handler 88690
sifcmd sceSifRegisterRpc: rpc_id 534e4b30
IOP Spinning
SNAKE IOP: Soft IRQ Thread Activated.
SNAKE IOP: Child Thread Activated.
SNAKE IOP: Music Thread Activated.
SNAKE IOP: Disk Thread Activated.
Set GS CRTC configuration. Interlace Interlaced. Field Type FRAME. Mode NTSC 640x448 @ 59.940 (59.82)
IPU1 running when IPU1 DMA disabled! CHCR 1 QWC 0
microVU1: Cached Prog = [001] [PC=0028] [List=01] (Cache=0.001%) [0.0mb]
microVU1: Cached Prog = [002] [PC=35a0] [List=01] (Cache=0.002%) [0.0mb]
microVU0: Cached Prog = [000] [PC=09d8] [List=01] (Cache=0.000%) [0.0mb] 
```

If a CDVD plugin issue is still a possibility; the disk always stops reading in the same sector
```
DvdRead: Reading Sector 1531703 (016 Blocks of Size 2064) at Speed=4x
DvdRead: Reading Sector 1531719 (016 Blocks of Size 2064) at Speed=4x
DvdRead: Reading Sector 1531735 (016 Blocks of Size 2064) at Speed=4x
DvdRead: Reading Sector 1531751 (001 Blocks of Size 2064) at Speed=4x
```

**Comment by refractionpcsx2** [comment]
Hmm, not sure then.. Does the debugger give any clue?

**Comment by MrCK1** [comment]
Actuaooy I didn't try that. Any idea as to what I should I look for?

**Comment by refractionpcsx2** [comment]
just see if its stuck in a loop on the EE when it stops and what it's checking. If you're not sure post a screenshot :)

**Comment by MrCK1** [comment]
I actually got it to work. The problem was that the game was in-fact loading; but there was no representation that EE activity was going on.

After waiting a bit with the limiter unclamped, the title screen appeared only to be greeted by an assert :P

**Comment by MrCK1** [comment]
I'll do this some other time, not certain on a few things

**Pull request closed without merging**
