### PR TITLE
dev9ghz: Use .ini for saving settings

### PR DESCRIPTION
**Pull request by TheLastRar**
Use .ini for saving settings.

This seems to be how other plugins save their settings.

Also import settings from the registry (where it was previously saved) if needed.

### CODE REVIEW

**Comment by karasuhebi** [comment]
Related to #601

**Comment by bositman** [comment]
Tested it a bit, loaded previous settings fine but maybe stop trying to load settings again after the ini has been created? Maybe even delete the registry keys after we've imported them. I still get this error for example: Error opening registry key: SYSTEM\CurrentControlSet\Control\Class\{4D36E972-E325-11CE-BFC1-08002BE10318}\PropertiesError opening registry key: SYSTEM\CurrentControlSet\Control\Network\{4D36E972-E325-11CE-BFC1-08002BE10318}\Descriptions\Connection
Available TAP-WIN32 adapters [name, GUID]: (got it with the master version too, just saying)

Also the 'Enabled' checkbox under Ethernet doesn't seem to be saved as checked

**Comment by TheLastRar** [comment]
The "Error opening registry key" occur when getting the list of tap adapters avalible. It has nothing to do with loading the actually loading the plug-in settings.

"'Enabled' checkbox under Ethernet doesn't seem to be saved as checked" This was a typo, I don't know how I didn't pick this up in testing.

I've also added code that deletes the settings leftover in the registry. it will only attempt this if the plugin doesn't find dev9ghz.ini.

I've left "Software\PS2Eplugin\\DEV9" and "Software\\PS2Eplugin", as I'm not sure if any other plug-ins use them.

**Comment by bositman** [comment]
You can delete Software\PS2Eplugin\DEV9 nothing else uses it, but it seems like the linuz iso plugin still uses the registry, got this entry
Software\PS2Eplugin\CDVD\CDVDiso so you can't delete the PS2Eplugin I guess. 
I think it should always attempt to clear the registry after it has loaded the settings from it. So if it finds settings in the registry->create ini->delete registry
Thanks for the work BTW :) Would be great if you could mirror it for the linuz iso plugin (although very low priority)

**Comment by TheLastRar** [comment]
Added suggested changes

**Comment by bositman** [comment]
Good job, thanks :)

**Pull request merged**
