### PR TITLE
F9 toggle message log.

### PR DESCRIPTION
**Pull request by ssakash**

### CODE REVIEW

**Comment by ssakash** [comment]
We decided to change the log message for the F9 toggle since, the previous log message doesn't suit well for those who use D3D9/D3D11/OGL(software mode).

http://forums.pcsx2.net/Thread-Simple-bug-with-the-console-reporting?pid=455457#pid455457

**Comment by avih** [comment]
Please change the commit message to `console: fix message for hw/sw rendering switch`.

**Comment by avih** [comment]
Sorry, to `console: use correct message for hw/sw rendering switch`

**Comment by karasuhebi** [comment]
http://forums.pcsx2.net/Thread-Simple-bug-with-the-console-reporting?pid=455489#pid455489

**Comment by avih** [comment]
What does that mean? please say what you want to say instead of sending me read a full thread and have me guessing what you want me to understand ;)

**Comment by karasuhebi** [comment]
Oh sorry I meant to link to my post on that thread's second page. I want to change the console message.

**Comment by ssakash** [comment]
the render variable values are only numbers, it couldn't be implemented that way. I think the current definition is pretty much understandable. no one would expect the change of a video renderer when we are just toggling the modes.

**Comment by ssakash** [comment]
@avih 
The commit message has been modified to your preference.

**Comment by karasuhebi** [comment]
Oh that's not meant to be actual code, I have no idea what the variable name is or what it contains. I was just trying to explain it in a way that kinda looked like code so you guys would understand what I was suggesting more clearly. I figured they wouldn't be strings since you mentioned a conditional statement was needed. Thanks for clarifying though. :)

"no one would expect the change of a video renderer when we are just toggling the modes."
Bositman and myself disagree. I think the statement needs to be left like it is where it mentions Hardware/Software or implement something like what I said where you use the renderer variable in a conditional statement. And like I said, I think technically speaking, stuff like OGL (Software) and D3D11 (Software) are not modes, but actual renderers. So we ARE switching video renderers.


But you do have a point though, most people look at them as modes, so maybe we can just have the console message read "Toggling GSdx renderer modes" if you don't want to implement the variable in there. What do you guys think?

**Comment by ssakash** [comment]
I think the current "toggling gsdx hardware/software render" is pretty fine. We have mentioned in the console message itself that only the hardware/software mode gets toggled. IDK why would anyone consider the change of the video backend. If you feel any reasons on why users' would confuse it with a different video backend then, please mention why.

**Comment by karasuhebi** [comment]
What about "Toggling renderer mode"? Or finding a way to include which renderer they're being switch to (maybe with a variable)? That way there's no doubts about what renderer they just switched to since it'll say hardware or software. Plus since we are referring to them as modes in the console message, no user will think we're switching to a renderer with a different backend.

**Comment by ssakash** [comment]
There is still the null mode, that might confuse the user's. As I had said earlier, I really think that the current commited log message is fine. That would prevent confusion since, it is mentioned that only the hardware/software mode of the specific renderer is getting toggled.

**Comment by karasuhebi** [comment]
So you don't like the idea of using the variable to print to the console a message with exactly which mode is being used? (hardware/software)

**Comment by ssakash** [comment]
I like the idea of mentioning the renderer used. I was mentioning my opinion on idea of log message on "toggling the render mode". It is almost midnight at my region, I can't make the renderer variable changes now but, I'll look into it tomorrow morning.

**Comment by karasuhebi** [comment]
Sounds good.

**Comment by avih** [comment]
Thanks.

**Pull request merged**
