### PR TITLE
Gsdx half screen snow engine

### PR DESCRIPTION
**Pull request by gregory38**
Require a tons of testing

### CODE REVIEW

**Comment by pgert** [comment]
Care to make a build of this and post it in the GSdx-thread in the forum?

**Comment by ssakash** [comment]
here's the link for the snowblind branch build - https://www.dropbox.com/s/qcgrsvs6ano1u47/Snowblind%20Fix.7z?dl=0

credit goes to @Nobbs66 for compiling it.

**Comment by Ploff** [comment]
I tried running "Champions(of Norrath): Return to Arms" with the plugin provided by ssakash, but I'm still missing half the screen as before.
Tested with resolutions: native, 2x, custom. Renderer: Direct3D11 (Hardware), OpenGL (Hardware)

If I'm doing something wrong, please direct me towards proper instructions.

I want to point out that upon loading a savestate, the other (previously black) half of the screen loads the first frame, and holds that frozen.

**Comment by ssakash** [comment]
@Ploff 
providing GS dump and screenshot of the the specific scene might help. you can make a GS dump by pressing Shift + F8 and the .GS file will be created on the snaps folder of pcsx2 directory.

**Comment by huntzcom** [comment]
Hey, I tried the plugin fix plugin provided. All I can say is wow. Im running at 2 times native res with all graphics enhancements and its running at 60 fps stable in HW mode.
Very impressed.

**Comment by Ploff** [comment]
@ssakash
https://www.sendspace.com/file/0zb5ct

**Comment by ssakash** [comment]
@Ploff 

@huntzcom mentioned that Champions of norrath works perfectly on hardware mode. by any chance did you only try the game by loading save states ? if yes, please load from the memory card instead and give it a try.

**Comment by Ploff** [comment]
@ssakash, I loaded the game without using savestates.

@huntzcom, can you confirm the success with champions of norrath: return to arms, or were you running a different game?

**Comment by huntzcom** [comment]
I was using champions of norrath, champions of norrath return to arms.

**Comment by gregory38** [comment]
I can reproduce the issue with the dump but even SW renderer have some difficulties (on the dump). So I'm not sure I can fix it.

**Comment by gregory38** [comment]
So it is a similar issue but not the same issue :(

**Comment by Ploff** [comment]
I have tested, and can conform that the original Champions of Norrath is working for me, as it did for huntzcom. Return to Arms however, does not.

**Comment by gregory38** [comment]
Yes, it is because the game uses a standard framebuffer width. I need to redo a big chunk of code to support framebuffer properly. If the code is more generic, it might fix others issues bug with the texture cache (or create news one...)

Anyway, if you want, I could provide you a quick patch to apply on this branch until I really fixed it. Basically this patch will replace the 0x140 offset by 0x100 and drop the (t->m_TEX0.PSM == 2) condition.

**Comment by gregory38** [comment]
Let's merge the code. Potentially it remains issue with the framebuffer size detection but so far it is really limited.

**Comment by gregory38** [comment]
Let's merge the code. Potentially it remains issue with the framebuffer size detection but so far it is really limited.

**Comment by Dreadmoth** [comment]
Tested my collection of Snowblind Engine games using the current revision 995ae51:

Baldur's Gate: Dark Alliance (PAL-M5) (SLES-50672) -> No issues
Baldur's Gate: Dark Alliance II (PAL-M3) (SLES-52187) -> No issues
Champions of Norrath (PAL) (SLES-52325) -> Half-screen issue
Champions: Return to Arms (PAL) (SLES-53039) -> Half-screen issue

Used Direct3D11 (Hardware). PCSX2 settings on defaults with speedhacks disabled.
Tried Native through to 3x Native resolution.

In both Baldur's Gate: Dark Alliance games a thin (1 - 4 pixels) border appears on the right and bottom edges of the screen when non-native resolutions are used. Using custom resolutions results in a cut-off, stretched copy of the left half of the frame to be displayed on the right half even if set to a multiple of the native resolution.

In Champions of Norrath the right side of the screen occasionally updates when the camera is in certain positions - though the colour depth seems to be lower and effects like fire aren't displayed on that side. GS dump and screenshot taken with the camera in one of those spots: https://www.mediafire.com/?a8wxmx9tjfbbp02
In other places the distortion effects from torches, etc. seem to interact with the frozen image causing smearing.

**Comment by gregory38** [comment]
Thanks for the tests. Give me some times and I will update the fix for others games that still miss half of the screen.

**Comment by gregory38** [comment]
I created a new PR #575 that will fix Champions* games.

**Comment by hockland** [comment]
Tested the most recent version (3dd3bf6) of pcsx2 with Baldurs Gate 1 in the inn scene. No change. Still 12-13 fps.

**Comment by gregory38** [comment]
I only fix half screen issue. Fps is much more complicated to fix. I have a tons of pending task so I will postpone it.

**Comment by hockland** [comment]
No worries

**Pull request merged**
