### PR TITLE
Magicgate clean

### PR DESCRIPTION
**Pull request by AKuHAK**

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
We've said this before, we don't want to touch Magicgate, you're welcome to branch it off and make your own but we don't want it in the main branch.

**Comment by AKuHAK** [comment]
I apologize, I incorrectly pulled it here

**Comment by AKuHAK** [comment]
_i was trying to pull into my master branch..._

**Comment by refractionpcsx2** [comment]
You missed :P

**Pull request closed without merging**
