### PR TITLE
Build: Unify shared libraries across platforms 

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Use DLLs/shared libraries for:
 - libjpeg
 - libpng
 - libwebp
 - lz4
 - SDL
 - zlib
 - zstd

### Rationale behind Changes

 - Consistency across platforms.
 - ~1MB smaller exe.
 - Slightly quicker LTO times because less codegen.
 - Faster builds because more precompiled deps.
 - Less code.
 - Fewer goshdarn submodules.
 - Enabling me to switch imgui to freetype without bloating the binary further.

### Suggested Testing Steps

 - Make sure all platforms still run as expected.
 - Make sure eyetoy emulation still works, since I swapped jpgd for libjpeg.

### CODE REVIEW

**Comment by seta-san** [comment]
with the working jpg library, eyetoy cameo can work and the format is being set correctly now but the evil usb buffer issues are preventing it.

[   90.2755] EyeToy: Frame buffer overrun, max: 37888 bytes, actual: 38512 bytes
[   90.2757] EyeToy: Frame buffer overrun, max: 37888 bytes, actual: 39408 bytes
[   90.2759] EyeToy: Frame buffer overrun, max: 37888 bytes, actual: 40304 bytes

**Comment by stenzek** [comment]
There shouldn't be any behavioural issues with this PR.

**Comment by seta-san** [comment]
The other jpg library never got close to working. I think it wasn’t even remotely implemented correctly. I think your implementation of this new one actually is correct except some of the old frame buffer code leftover

**Review by Mrlinkwii — APPROVED** [review]

**Review by kamfretoz — APPROVED** [review]

**Comment by stenzek** [comment]
My only concern is that it's not _worse_, i.e. something that worked before, didn't work now.

**Comment by stenzek** [comment]
Drafting due to upstream xz compromise.

See https://www.openwall.com/lists/oss-security/2024/03/29/4

**Review by kamfretoz — APPROVED** [review]
LGTM on Linux and Mac

**Review by Mrlinkwii — APPROVED** [review]

**Review by JordanTheToaster — APPROVED** [review]

**Pull request merged**
