### PR TITLE
Update VMManager.cpp to not count paused time toward time played

### LINKED ISSUE #10497: [Feature Request]: Don't count paused time towards time played
### Description

When you pause the game (Spacebar or System -> Pause), the time played counter should stop counting.

### Reason

I sometimes pause and forget about the game. I end up coming back to multiple hours counted towards my time played.
It now says I have 21 hours in a game when it's more like 5.

### Examples

N/A

### PR DESCRIPTION
**Pull request by TheTechnician27**
### Description of Changes
Between each update to played time, we calculate the sum of the deltas between VM resume and pause in order to subtract that off from the total (paused and unpaused) session time. Also, there was one check 'state == VMState::Paused' which already had a corresponding Boolean called 'paused'. There should be no possibility of a difference between this value and 'paused', so there should be no reason to re-perform this comparison here.

This is my first PR that actually affects anything outside of documentation or the GUI, so please take it with a grain of salt. Still, I really want to get into contributing to PCSX2, so I've done my best here.

### Rationale behind Changes
Hopefully resolves #10497.

Thus, if someone pauses the emulator, that time spent paused will no longer be reflected in the GameList.

### Suggested Testing Steps
Start a game whose serial has little or no playtime on your PCSX2. Pause the emulator for a while, then shut down the emulator and see how playtime is reflected in the game list.

### CODE REVIEW

**Comment by TheTechnician27** [comment]
I forgot to add the 'u64' type to a variable, which is why the checks failed. I'm sorry; I'll have this fixed shortly.

**Comment by bigol83** [comment]
I checked it and i think there is something slightly off with the time played counter 😜

i played for two minutes, then put it in pause for four minutes, this is the result. 
time played

**Comment by TheTechnician27** [comment]
> I checked it and i think there is something "slightly" off with the time played counter 😜
> 
> i played for two minutes, then put it in pause for four minutes, this is the result. 
> time played
> 

Hm... :|

We store session playtime as a u64 before saving it, but it seems this isn't an underflow, since that value would be more enormous than this amount of hours * 3600 (we store time in seconds). This represents about 1,845,000,000,000 seconds played. The closest power of 2 to this is 2^41, nowhere near 2^64. If we eventually write it into a smaller variable, then maybe this is garbage from C++ trying to fit an underflowed u64 into a u32.

Everything I've added does nothing but subtract from the amount of playtime, so it should be 100% impossible for this to dramatically increase playtime (let alone increase playtime at all) without an underflow.

**Comment by TheTechnician27** [comment]
> I checked it and i think there is something "slightly" off with the time played counter 😜
> 
> i played for two minutes, then put it in pause for four minutes, this is the result. 
> time played
> 

Incidentally, does it work as intended if you change those ratios around, i.e. play for about four minutes and pause for about two?

**Comment by bigol83** [comment]
Will check later and report.

**Comment by TheTechnician27** [comment]
@CookiePLMonster Actually, it's not a small nitpick. This was bothering me when I wrote it, because I took one line and had to turn it into three. Do you know if it would be possible to condense this even more to:

```
return static_cast<u64>(std::round(Common::Timer::ConvertValueToSeconds(ctime - s_session_start_time - std::exchange(s_time_paused_since_last_update, 0))));
```

I only create the variable `played_time` so I have time before returning to reset `s_time_paused_since_last_update`, so if this can be done, `played_time` is useless.

**Comment by CookiePLMonster** [comment]
> Do you know if it would be possible to condense this even more to:

Yup, of course that'd work.

**Comment by TheTechnician27** [comment]
> > Do you know if it would be possible to condense this even more to:
> 
> Yup, of course that'd work.

I'll go ahead and add that in once I hopefully figure out and fix this ostensible underflow issue. Don't want to waste too much of PCSX2's build time by committing two changes if I can help it.

**Comment by bigol83** [comment]
Still the same issue with time played counter. This time i let the game run for 4 minutes and then paused for 2 minutes.

time played

**Comment by TheTechnician27** [comment]
Weirdly, I'm able both to replicate and not to replicate this. No matter if I pause or don't, the time played for me increases to 5,124,XXX hours, which is substantially less time than yours but still almost an exact power of 10 less. This feels like it has to be some sort of underflow, but it feels like it should be impossible for `s_time_paused_since_last_update` to ever exceed `ctime - s_session_start_time`, and furthermore, this doesn't seem to exhibit that close-to-a-power-of-2 behavior you sort of expect from an underflow.

**Comment by TheTechnician27** [comment]
It now works for a basic test case. Merging the proposed changes shortly.

**Comment by bigol83** [comment]
Working as intended with latest update. 👍

**Comment by stenzek** [comment]
Code looks fine, not sure what's happened with GitHub, it's displaying the changes from my log window PR in the diff..

**Comment by refractionpcsx2** [comment]
The commit looks to have been mangled to include other changes. Not sure why :/ Did a rebase go wrong?

**Comment by stenzek** [comment]
Looks like you somehow managed to rebase the file, but not the entire tree, so it was a VMManager.cpp from master with a tree from yesterday.

Fixed it for you. In the future, what you'll need to do is:
```
git remote add upstream https://github.com/PCSX2/pcsx2.git
git fetch upstream
git rebase upstream/master
git push -f origin <branchname>
```

After you've added the remote once, no need to add it again.

**Review by Mrlinkwii — APPROVED** [review]

**Pull request merged**
