### PR TITLE
Drop vs2010 support

### PR DESCRIPTION
**Pull request by gregory38**
drop support of Visual Studio 2010
    
    * Severals PR uses C++11 features
    * 2015 will soon be released
    * Win 10 will soon be released

    Require some Windows tests

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Well I use vs 2013 currently, it wouldn't surprise me if the 2010 project is completely out of date.  I think removing it is probably an idea

**Comment by gregory38** [comment]
Well I won't to be sure that others vs version still compile. Of course VS2010 won't compile anymore :stuck_out_tongue:

**Comment by refractionpcsx2** [comment]
I will check it with 2012 and 2013 :)

**Comment by refractionpcsx2** [comment]
With the changes I just comitted, VS2013 still builds absolutely fine. 
I can't test 2012 as I don't have it, but I suspect it's a little out of date currently as the OpenCL project hasn't been added to the solution.  I could merge it from the 2013 project and hope for the best.

**Comment by refractionpcsx2** [comment]
Ok VS2012 is going to be a pain, but I don't think it's related to this commit, so i would say this is fine to merge now and we can deal with vs2012 later

**Comment by refractionpcsx2** [comment]
Oh one thing I'm not sure about, which project Orphis Build Bot uses to build, last i knew it was using 2010, so ill need to find out.

**Comment by gregory38** [comment]
Ok. I don't think so. Otherwise it will break more often :p But you're right it need to be checked.

**Comment by karasuhebi** [comment]
Orphis idles in our IRC channel, you can ask him there.

**Pull request merged**
