### PR TITLE
Use native language GameDB entries

### PR DESCRIPTION
**Pull request by TellowKrinkle**
### Description of Changes
Switches the main display of GameDB entries to the game's native language in Qt (bigpicture coming later)
(Note: I only added native language entries to Japanese games, we still need someone to do it for the Korean games.)
...plus a few modifications to the gamedb validation scripts so you actually see line numbers when validation fails

### Questions:
Should I include an option to force English titles?  If so, where should I put it?

### Rationale behind Changes
It would be pretty goofy to have the entire UI translated into Japanese, but still use English titles

### Suggested Testing Steps
- Make sure your Japanese games show in Japanese in the game list
- Make sure the Japanese games sort properly (should be gojuuon order by pronunciation of the kanji)

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
yeah 100% need to be an english option for the game list, at very least. I can't read or search for kanji, so I need to be able to see that.

i dunno if you wanna put it in the game list settings or just interface, but those are the two places which seem most obvious for it.

**Comment by refractionpcsx2** [comment]
New prefer English titles option works well :) Thanks!

**Comment by refractionpcsx2** [comment]
I guess I'll check the other thing once it builds lol, bad timing

**Review by refractionpcsx2 — APPROVED** [review]

**Comment by refractionpcsx2** [comment]
Works great :)

**Review by kamfretoz — APPROVED** [review]

**Comment by IlDucci** [comment]
Can this be used for other language-localized titles? I would be interested in Spanish (probably adding a rule to add those names strictly to PAL releases/multi versions that only have specific languages).

It's out of scope for this PR, sure, but I think this might be opening a Pandora's Box... with the shape of a Babel's Tower.

**Review by JordanTheToaster — APPROVED** [review]

**Comment by TellowKrinkle** [comment]
> Can this be used for other language-localized titles?

It only allows one additional language per game, but otherwise yes.

Not sure what current the state of gamedb is for those cases, it seemed like we were previously allowing non-English entries as long as they were in scripts recognizable by English speakers (so Latin-based ones).

**Comment by IlDucci** [comment]
> Not sure what current the state of gamedb is for those cases, it seemed like we were previously allowing non-English entries as long as they were in scripts recognizable by English speakers (so Latin-based ones).

Single-language discs already have their localized names. The problem is multilanguage discs with different titles per language (typically first-party games and license-based games).

**Review by Mrlinkwii — APPROVED** [review]

**Comment by TellowKrinkle** [comment]
Note: Currently a draft as I need to rearrange the settings panel controls to avoid increasing the minimum height of the settings window

**Comment by TellowKrinkle** [comment]
Do you think it looks better with or without a groupbox around the game scan settings? (254fc30b2b95e2a0e64b7186afe6e33ba91d16ac vs 6b66338a25dc5619e53137b6f09753917c349ce1)

**Comment by refractionpcsx2** [comment]
> Do you think it looks better with or without a groupbox around the game scan settings? ([254fc30](https://github.com/PCSX2/pcsx2/commit/254fc30b2b95e2a0e64b7186afe6e33ba91d16ac) vs [6b66338](https://github.com/PCSX2/pcsx2/commit/6b66338a25dc5619e53137b6f09753917c349ce1))

Can you provide a screenshot comparison?

**Comment by TellowKrinkle** [comment]
Without: 
Settings without groupbox around game scan stuff
With:
Settings with groupbox around game scan stuff

**Comment by kamfretoz** [comment]
For consistency with the "Prefer English Title" for having groupbox, i'd say also give the Game Scanning section a groupbox as well.

**Comment by seta-san** [comment]
👍

**Comment by seta-san** [comment]
looks great. played around a little seems ready for merge!

**Pull request merged**
