### PR TITLE
GHActions:Mac: Update to macOS 13 / Xcode 14.3

### LINKED ISSUE #9090: [BUG]: Devil May Cry Special Edition (US) Not Rendering on MacOs
### Describe the Bug

On the nightly version of pcsx2 for macos, as of a few recent updates i am unable to render DMC3 Special edition, about a quarter of the screen renders whether it is a fresh boot or a save state but the game is completely frozen. It also ramps up my processor and GPU causing my laptop to get extremely hot while attempting to render the game. The game had been working for weeks before this as i had over 60 hours on it. i attempted a factory reset of my Macbook as well and a full fresh install of the latest version of macOs monterey, the same issue persisted. 

### Reproduction Steps

In order to reproduce the behavior, use a mac device on the latest update for pcsx2, all settings default, and attempt to load into the game Devil May Cry 3 Special edition for the US. The game had been working for weeks before this as i had over 60 hours on it.

### Expected Behavior

the game should have just loaded normally.

### PCSX2 Revision

Latest

### Operating System

macOS 12 (Monterey)

### If Linux - Specify Distro

_No response_

### CPU

1.1 GHz Quad-Core Intel Core i5

### GPU

Intel Iris Plus Graphics 1536 MB

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

Devil May Cry 3 - Dante's Awakening  Special Edition _SLUS-21361_20230626161120

### Logs & Dumps

[Devil May Cry 3 - Dante's Awakening [Special Edition]_SLUS-21361_20230626161120.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11871035/Devil.May.Cry.3.-.Dante.s.Awakening.Special.Edition._SLUS-21361_20230626161120.gs.zst.zip)

### LINKED ISSUE #9092: [BUG]: Twisted Metal Head On Extra Twisted rendering problem
### Describe the Bug

Works fine in single player mode, unusable tearing on player 2 in split screen co-op

### Reproduction Steps

Split screen co-op

### Expected Behavior

_No response_

### PCSX2 Revision

v1.7.4640

### Operating System

macOS 13 (Ventura)

### If Linux - Specify Distro

_No response_

### CPU

M1 Pro

### GPU

M1 Pro

### GS Settings

Haven't changed anything

### Emulation Settings

Haven't changed anything

### GS Window Screenshots

Screenshot 2023-06-26 at 4 43 52 PM

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by TellowKrinkle**
### Description of Changes
#9047, macOS edition
Fixes #9090
Fixes #9092 

### Rationale behind Changes
Less broken

### Suggested Testing Steps
Test the linked issues, as well as #9045

### CODE REVIEW

**Comment by stenzek** [comment]
Are you sure the 12.0 doesn't include the fix? I checked the sources in the LLVM repo for the 14.0.0 branch and it does, and the macos-12 image is listed as having clang-14 here <https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md> (hence why I made #9063).

**Comment by TellowKrinkle** [comment]
Unless I was really unlucky with something, [this build](https://github.com/TellowKrinkle/pcsx2/actions/runs/5384337595) was still broken

We currently use the clang provided with Xcode to compile (which is Apple's fork of clang, and has its own versioning) rather than the homebrew clang, which is the clang 14 listed there.  We could attempt to use that clang, but I haven't really looked into how to use the macOS SDK with external clang.

**Comment by stenzek** [comment]
Hm. I had read about Apple's LLVM tree being behind upstream LLVM, perhaps that is the case here.. Must be fairly behind then, because the fix was committed on 2021/11/ 20, and LLVM 14 was released on 2022/03/25.

**Comment by TellowKrinkle** [comment]
> Are there any downsides to using the macos-13 image at this point?

I wouldn't think so, but I also wouldn't have expected it to still be listed as beta 8 months after the release of macOS 13

**Comment by TellowKrinkle** [comment]
I'll go with probably fine

**Review by stenzek — APPROVED** [review]
Diff LGTM, can't test though.

**Comment by DigitalMajestic** [comment]
Dumps tested good, no dump available for Twisted Metal but it should be good too as the user bisected it to the commit which broke everything else too.

**Review by DigitalMajestic — APPROVED** [review]

**Pull request merged**
