### PR TITLE
GS/HW: Add render fix for complex moves

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

And use it to fix Growlanser. (I'll also use this for Ico later on to avoid readbacks)

### Rationale behind Changes

Regression from #9171.

### Suggested Testing Steps

I only have one GS dump for the series, so I have no idea if this completely fixes the issue. I tried to make the hack fairly generic, so hopefully it'll work cross-region.

@Risae could you check some of these games, and if it's still broken, upload a GS dump please?

### CODE REVIEW

**Comment by Risae** [comment]
Thank you, i will check all affected games later today and let you know if they are fixed without using `Tex in RT`.

**Comment by Risae** [comment]
Things that i noticed:

- PCSX2-windows-Qt-x64-AVX2-pr[9187]-sha[48ac2cf]-title[GSHW Add render fix for complex moves]
- pcsx2-qtx64-avx2.exe
- AMD Ryzen 9 6900HX
- AMD Radeon 680M (iGPU)
- DDR5 SO-DIMM 5600 RAM
- AMD Adrenalin 23.5.2

SLPM-66716 "Growlanser VI":
- After you start the game, without changing any default settings, you will have the "see through" character model issue

Console logging:
```
[  266.6570] [GameDB] Enabled GS Hardware Fix: textureInsideRT to [mode=1]
[  266.6575] [GameDB] Enabled GS Hardware Fix: moveHandler to [mode=0]
```

Growlanser VI_SLPM-66716_20230707172840

[Growlanser VI_SLPM-66716_20230707172840.zip](https://github.com/PCSX2/pcsx2/files/11983641/Growlanser.VI_SLPM-66716_20230707172840.zip)

- After using the PCSX2 GUI to change the renderer to, for example, DirectX12 the "see through" is gone, but there are sudden graphical issues when you move the character:

```
[  646.0907] Reopening GS with new device and new renderer
[  646.1232] Skipping updating pipeline cache 'D:\PCSX2-windows-Qt-x64-AVX2-pr[9187]-sha[48ac2cf]-title[GSHW Add render fix for complex moves]\cache\vulkan_pipelines.bin' due to no changes.
[  646.1894] Creating a 1920x998 windowed swap chain
[  646.2321] D3D12 Graphics Driver Info:
[  646.2324]    D3D_FEATURE_LEVEL_11_0
[  646.2324]    VID: 0x1002 PID: 0x1681
[  646.2324]    AMD Radeon(TM) Graphics
[  646.2324]    Driver Version: 31.0.14057.5006
```

[Growlanser VI_SLPM-66716_20230707173855.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11983750/Growlanser.VI_SLPM-66716_20230707173855.gs.zst.zip)

https://github.com/PCSX2/pcsx2/assets/37260321/90715452-eb98-4c24-a53c-4fdb9cd7d39d

**Comment by stenzek** [comment]
The move handler hw fix is needed for the depth buffer to work correctly.

**Comment by Risae** [comment]
> The move handler hw fix is needed for the depth buffer to work correctly.

I'm not entirely sure where to find the option to turn it on, since `[   30.0522] [GameDB] Enabled GS Hardware Fix: moveHandler to [mode=0]` means its turned off, right?

Screenshot 2023-07-08 105009

**Comment by stenzek** [comment]
No. The mode there is a bit misleading - it's actually an index into the function table. So 0 means it's active.

**Comment by stenzek** [comment]
Last push should sort out the flicker-for-one-frame in the dump above.

It's probably worth trying without tex-in-rt. Enabling manual hw fixes should do the trick there (the move handler will still get applied from the gamedb).

**Comment by Risae** [comment]
> Last push should sort out the flicker-for-one-frame in the dump above.
> 
> It's probably worth trying without tex-in-rt. Enabling manual hw fixes should do the trick there (the move handler will still get applied from the gamedb unless you disable render fixes).

Got it, will try it out once the CI is done

**Comment by Risae** [comment]
I tested the following games:

- SLUS 21571 Growlanser: Heritage of War US http://redump.org/disc/12996/
- SLPM 66716 Growlanser VI: Precarious World http://redump.org/disc/25783/

I enabled `Manual Hardware Renderer Fixes` to turn off `Texture inside RT`. Everything else is on the default settings.

The "see-through" issue still exists after you start both games, but once you change the renderer through the "debug" menu to, for example DX12, it works without an issue. I'm honestly not sure if this is caused by me or if something wrong with PCSX2:

https://github.com/PCSX2/pcsx2/assets/37260321/fed930b1-866f-40af-b270-a994ce0ac147

Here is a GS Dump before i changed the renderer:

[Growlanser - Heritage of War_SLUS-21571_20230709071747.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11994465/Growlanser.-.Heritage.of.War_SLUS-21571_20230709071747.gs.zst.zip)

So far i didn't find any other graphical issues with this PR. I will also ask around the Growlanser Community if they find any other issues.

**Comment by stenzek** [comment]
It should work without changing the renderer... but I think I know what the issue is there.

**Comment by stenzek** [comment]
Hopefully that sorts it out (it wasn't re-grabbing the function on game change, and the BIOS boot portion doesn't have hw fixes enabled).

Also removed tex-in-rt from the gamedb. I suspect it didn't actually need tex-in-rt, and was just relying on it for partial target invalidation previously (which isn't needed now).

**Comment by Risae** [comment]
> Hopefully that sorts it out (it wasn't re-grabbing the function on game change, and the BIOS boot portion doesn't have hw fixes enabled).
> 
> Also removed tex-in-rt from the gamedb. I suspect it didn't actually need tex-in-rt, and was just relying on it for partial target invalidation previously (which isn't needed now).

I tested all of the affected games and it works out-of-the-box now (without `Texture inside RT` and having to change the renderer). I can't really get my debug room cheat (to test various stuff) to work with the new PCSX2 right now, but i think it looks good so far.

**Comment by stenzek** [comment]
Awesome, thanks for checking!

**Pull request merged**
