### PR TITLE
update GameIndex.dbf

### PR DESCRIPTION
**Pull request by ssakash**
added "switch to software rendering during FMV" gamefix to automatic
gamefixes for Shadow Hearts (U) and Kingdom Hearts (U) and, added
playable status for Final Fantasy XII [Collector's Edition].

### CODE REVIEW

**Comment by gregory38** [comment]
A bit off-topic, do you know what is the purpose of this hack (inFMV...) ? And what it does?

**Comment by ssakash** [comment]
yeah, it switches the renderer to software mode while playing FMV. it's basically the constant for gamefix #15 , I have added it to the automatic game fix since, both of the game needs that to play the FMV's properly without any graphical glitches.

**Comment by gregory38** [comment]
Is it for vertical line due to upscaling or others glitches (or it depends)? I'm asking because I'm trying to reduce upscaling glitches.

**Comment by ssakash** [comment]
for Shadow hearts, it's a flickering issue. for Kingdom hearts, there are some messed up textures in the opening cutscenes. all of the following could be fixed by software mode (which the Hack does while the FMV's are played) . AFAIK, the FMV's can't be upscaled Internally hence, there is no chance for  upscaled glitches.

**Comment by ssakash** [comment]
any update on the Commit ?

**Comment by karasuhebi** [comment]
@gregory38 No, this doesn't have to do with upscaling. 

@ssakash What issues are you seeing in KH?

**Comment by ssakash** [comment]
The following graphical glitch is present in the opening Cutscene If, hardware mode is used. Thanks to Nobbs66 for providing the screenshot. the only workaround for the situation is software mode.

http://anony.ws/i/2015/04/02/sidejunk.png

**Comment by karasuhebi** [comment]
Oh OK yeah, that's a problem.

From the testing I just did, that only happens when you have widescreen patches turned off though. Why is @Nobbs66 running Kingdom Hearts in a 16:9 window with widescreen patches turned off? O_o

**Comment by ssakash** [comment]
but still, if the issue is present without the wide screen hack then, I think the sw fmv hack is needed.

**Comment by karasuhebi** [comment]
Yeah I agreed. Look at my first sentence :p I was just mocking @Nobbs66 for stretching the game instead of turning on widescreen patches. XD

**Comment by ramapcsx2** [comment]
The GSdx hack is pretty unstable and not even coded all that nice. I'm very much against automatically applying this hack just like that.

**Comment by karasuhebi** [comment]
Oh I wasn't aware. Is it something that could be fixed by a third person or is it pretty complex and @Gabest would probably have to look at it?

@ssakash I would recommend making another PR just with the compat change for FFXII CE so that can get approved at least.

**Comment by ssakash** [comment]
@ramapcsx2
I didn't have any issues while using this hack, care to provide more info about this ?

**Comment by ssakash** [comment]
@karasuhebi
yeah, I will add them in another PR if, this isn't getting merged. I did also want to add compatibility status for few other games also.

**Comment by ssakash** [comment]
feel free to reopen this PR if, you find this worthwhile.

**Pull request closed without merging**
