### PR TITLE
Debugger: Properly initialize primitive class members

### PR DESCRIPTION
**Pull request by F0bes**
### Description of Changes
Initialize primitive class members that would otherwise be of unknown values 
Also implement the "Copy Address" context menu for the memory view
### Rationale behind Changes
It's my best idea to fix the indeterminate behaviour causing #9813

### Suggested Testing Steps
Try the FPR and VU0 register "show as hex" context menu options.

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
Should just initialize those in-header, makes missing any initializations hard.

**Comment by F0bes** [comment]
Yeah, that's a good point.
I'll do that instead.

**Comment by F0bes** [comment]
Made the change to initialize in the header and also added the "Copy Address" context menu in the memory view.
Ready to merge.

**Review by CookiePLMonster — APPROVED** [review]
Copy Address will be super handy!

**Review by Mrlinkwii — APPROVED** [review]

**Pull request merged**
