### PR TITLE
Qt-GUI - Controlller Images

### PR DESCRIPTION
**Pull request by andercard0**
Added new controller UI images

### Description of Changes
Changed the look of the controller UI from:
before

Into this: 
after

### Rationale behind Changes
Simple brush up :) 

### Suggested Testing Steps
No needed

Also a credit to @joaopsantos16 who help me a lot with it months ago!

### CODE REVIEW

**Comment by coornio** [comment]
Wonder if we can get lines to the respective buttons on the image to help the visual further. Something like this, but less ugly:

https://www.howtogeek.com/wp-content/uploads/2016/03/img_56ea0255baff0.jpg

**Comment by SirFancyBacon** [comment]
I like the concept of the above image, but that would be a lot of lines
image
Quick and dirty mockup obviously

I suppose we could make the layout "nicer" but i'd like to think everyone who uses this emulator can read and knows how a controller is mapped out.

**Comment by RedDevilus** [comment]
It only needs some distance from image to text such as Large Motor and increasing button sizes in horizontal manner, and it will look much better.

**Comment by Daisouji** [comment]
> I like the concept of the above image, but that would be a lot of lines image Quick and dirty mockup obviously
> 
> I suppose we could make the layout "nicer" but i'd like to think everyone who uses this emulator can read and knows how a controller is mapped out.

I think the labels on the side are good enough indicator of what part is what. The lines would be better used in Imgui/no Gui type setting

**Comment by coornio** [comment]
Let's be honest, requiring 4 separate binds for the analog sticks themselves is also a fair amount of clutter. We could potentially shorten it to "one bind" where the user's asked to twirl their stick around?

**Comment by refractionpcsx2** [comment]
> Let's be honest, requiring 4 separate binds for the analog sticks themselves is also a fair amount of clutter. We could potentially shorten it to "one bind" where the user's asked to twirl their stick around?

And how do you choose which axis is which? it's not an "analog stick bind" it's two axis to bind.

**Comment by coornio** [comment]
> > Let's be honest, requiring 4 separate binds for the analog sticks themselves is also a fair amount of clutter. We could potentially shorten it to "one bind" where the user's asked to twirl their stick around?
> 
> And how do you choose which axis is which? it's not an "analog stick bind" it's two axis to bind.

Ah right, that's true. We could shorten it to just two axis binds per stick I suppose, like DS does it.

**Comment by Daisouji** [comment]
Shortening 2 inputs instead of 4 only works out well if there were options to cover the inverting x/y axis

**Comment by coornio** [comment]
> Shortening 2 inputs instead of 4 only works out well if there were options to cover the inverting x/y axis. That's how Ryujinx does their bindings.

I suppose so, not that something like that couldn't be adjusted. It's mostly safe to assume that negative values refer to the down/left directions and positive values to up/right.

**Comment by Zorklis** [comment]
Can we just get the better controller image for now

**Comment by andercard0** [comment]
> It only needs some distance from image to text such as Large Motor and increasing button sizes in horizontal manner, and it will look much better.

Sorry for the huge delay, actually, I could not build it correctly it to see the real result of it, my end issue definitely. I mean, what you can see there is only a mock up of the end result, considering the size of the images it is correct and ready to use so, if you or any other contributor could validate that building it I think it is good to go! My bad again for not let you guys now ealier.

**Comment by Daisouji** [comment]
Your file naming is off: dualshock-2.png <--rename it to that. 
600+400 render to 1200 by 800:  u want to cut a bit maybe 550*333 or 500*367
If you enable, the workflow. the script will build for it for u.

**Comment by Mrlinkwii** [comment]
needs conflicts resolved and controlller Image name corrected

**Comment by dezraj** [comment]
Shouldn't the analog button LED light be red in this new picture to match the one in the PS2 controller?

**Comment by Daisouji** [comment]
CaptureO

I think it's good enough to merg.

**Comment by Mrlinkwii** [comment]
@Daisouji  needs conflicts fixed

**Comment by fantesykikachu** [comment]
@andercard0, to get this merged please:
rebase on master
make sure dualshock-2@2x.png is deleted
squash all of your commits together

**Comment by fantesykikachu** [comment]
@andercard0, it looks like you did not rebase on upstream master as such your PR is trying to delete a file (`dualshock-2@2x.png`) that has already been deleted upstream, this is the source of the conflict.

**Comment by andercard0** [comment]
> 



> @andercard0, it looks like you did not rebase on upstream master as such your PR is trying to delete a file (`dualshock-2@2x.png`) that has already been deleted upstream, this is the source of the conflict.

hi @fantesykikachu apologies for my ignorance.. but, are you saying this ? 
image

where should I perform this action ? I'm using github PC if that somehow matters..

**Comment by Daisouji** [comment]
You can't rebase on web. 
https://learntechsystems.com/git-rebase-and-resolve-conflicts-through-the-github-desktop/

The desktop client can do it. But at this point, I could just submit the PR for you. It's just 1 file LOL

**Comment by andercard0** [comment]
> 

ah, cr*p LOL 
image

**Pull request closed without merging**
