### PR TITLE
pcsx2: auto_ptr is deprecated in favor of auto_ptr

### PR DESCRIPTION
**Pull request by gregory38**
Might need a windows compilation test.

### CODE REVIEW

**Comment by randomstuff** [comment]
I think the title should read "in favor of unique_ptr" :)

**Comment by gregory38** [comment]
neurons loop overflow :p

**Comment by refractionpcsx2** [comment]
Hey it could have been worse, you could have said unique_ptr is depreciated in favour of auto_ptr :P

**Comment by micove** [comment]
To answer the original question, the Build Bot built this branch and all your other branches successfully so it works with VS2013. There is no reason it should fail in VS2015 but I confirmed it works in VS2015 too.

**Comment by gregory38** [comment]
It would be nice to have a summary of C++11 feature supported by VS2013 (or the one not supported, likely few)

**Comment by refractionpcsx2** [comment]
How would a table do you? :) https://msdn.microsoft.com/en-us/library/hh567368.aspx

**Comment by micove** [comment]
Boo, I was about to post that. Anyway, unique_ptr was added in S2010
https://msdn.microsoft.com/en-us/library/ee410601(v=vs.100).aspx

**Comment by refractionpcsx2** [comment]
Sorry xD Didn't mean to steal your thunder :P

**Pull request merged**
