### PR TITLE
Add Simplified Chinese language file

### PR DESCRIPTION
**Pull request by shinyoyo**
Add Simplified Chinese language file.Also uploaded all translation to crowdin.com.

### CODE REVIEW

**Comment by shinyoyo** [comment]
Add Simplified Chinese language file.

**Comment by RedDevilus** [comment]
The correct location is:
https://crowdin.com/project/pcsx2-emulator

So it can be brought in by syncing and not like the old way where people do commits for it directly.

**Comment by RedDevilus** [comment]
Also broke the translations.cpp file formatting.

**Comment by shinyoyo** [comment]
Already uploaded translation to crowdin.com.

**Comment by RedDevilus** [comment]
Thank you, keep in mind we currently don't sync the language to PCSX2 application atm (as far as I know)

**Pull request closed without merging**
