### PR TITLE
gsdx: tex shuffle detection v5

### PR DESCRIPTION
**Pull request by gregory38**
Add back the RT 32 bits format detection but with an extra height check. It isn't perfect but it might help to reduce some bad flickering.

Require lots of testing.

### CODE REVIEW

**Comment by gregory38** [comment]
@prafullpcsx2, I try to implement my idea to reduce flickering issue in GoW even with VU cycle stealing. I'm not sure it works well. And it might introduce regression in others games (suikoden, ricky, ...).

**Comment by prafullpcsx2** [comment]
I will love to test it as soon as I get my hands on a build. I hope someone like @refractionpcsx2  will be kind enough to compile this and link here.

**Comment by refractionpcsx2** [comment]
Ill have a compile later if i can.

**Comment by prafullpcsx2** [comment]
Thanks Ref, i will be waiting.

**Comment by gregory38** [comment]
May I ask you why you don't setup a VS2013 community edition on your PC? Not enough storage?

I give a quick look at god of war 2 fog, depth effect issue (the blue screen in first plane). It is a similar issue as texture shuffle. I only search depth in current frame to avoid pick a wrong stuff. However GoW2 try to do a depth effect at the start of the frame so the depth buffer lookup does a miss (instead of a hit). So I'm curious does the effect works too without VU stealing?

**Comment by ssakash** [comment]
Offtopic: The internet connection speeds are quite slow here on India, I had a lot of trouble on setting up my own working environment for compilation due to the crappy internet speeds provided here. I think @prafullpcsx2 also has similar problems. :)

**Comment by refractionpcsx2** [comment]
Here you go guys http://www.filedropper.com/gsdx32-sse2-ts-take5

**Comment by gregory38** [comment]
Thanks prafull for the test. Result is not better and there is no clean solution to properly detect the effect. The effect are bad due to VU cycle stealing. I don't want to add a new option in GSdx only to support core speedhack.

**Pull request closed without merging**
