### PR TITLE
Update GameIndex.yaml

### PR DESCRIPTION
**Pull request by tokuna2020**
### Description of Changes
some game memcardfilter, name correction.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Memcard filters need to contain the original serial as well as the others which can be read, could you add those to the new ones please? :)

**Comment by tokuna2020** [comment]
ok, original serial added.

**Comment by refractionpcsx2** [comment]
Why are these inconsistent? like SCPS-15107 can see SCPS-15103 but SCPS-15103 can't see SCPS-15107

**Comment by tokuna2020** [comment]
This is a one-way data conversion.
Later title can reference data from earlier titles, but older title itself cannot read data from newer titles.

**Comment by refractionpcsx2** [comment]
okay, as long as there's a reason for it

**Comment by refractionpcsx2** [comment]
Thanks :)

**Pull request merged**
