### PR TITLE
Load the complete ROM1 - 4MB

### PR DESCRIPTION
**Pull request by Florin9doi**
### Description of Changes
- Load the complete ROM1 - 4MB
- EROM is part of ROM1, its exact location vary and can't be predicted, so it was removed. It should already be included in ROM1.
- To work is required a BIOS dump in the following format:
  - ROM0 (4 MB) / **ROM1 (2/4 MB)** / ROM2 (0/512 KB)
- This format ~won't work~ is not recommended:
  - BIN (4 MB) / **ROM1 (256/512 KB) / EROM (1.75/3 MB)** / ROM2 (0/512 KB)
- GsCrt modes 0x82 and 0x83 are incorrect. Maybe someone will fix them but until then at least they will no longer crash.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
why is loading a 4mb block so important? what breaks if you don't do that?  The sizes you said don't work are the sizes of those ROMS as reported by the PS2.

**Comment by Florin9doi** [comment]
The issue is that EROM is stored at different locations across models. On FATs it is stored ar 0x40000 (early), 0x80000 (late) relative to ROM1 base. On SLIMs there are multiple copies stored in ROM1, for PAL, USA, JP, and the proper location is determined dynamically. It's hard to guess the proper address for every bios without additional information.

**Comment by refractionpcsx2** [comment]
okay, but we can't decrypt the EROM anyways, so it doesn't really matter too much.

**Comment by refractionpcsx2** [comment]
if the only issue is the storage location, then the better idea would to be to map it correctly like we do with NVM files depending on the BIOS revision, then it's not a problem.

**Comment by Florin9doi** [comment]
It may offer time to users to extract their BIOS in the expected format for when the decryption will be possible 😄

**Comment by F0bes** [comment]
I assume this is the result of a conversation I had in a discord server with someone else.
Completely ignoring this point I brought up then too:

> okay, but we can't decrypt the EROM anyways, so it doesn't really matter too much.

I'm against this as I don't see the point in this. Even if you really need the erom in it's proper place, let's not break compatibility with the old dumper, and now, the new dumper that was just released. You've failed to provide a good reason to do this.

**Comment by uyjulian** [comment]
I think it would be better to keep compatibility with the broken, old layout alongside the new layout.

**Comment by Florin9doi** [comment]
The underdumped BIOSes will continue to work exactly the same how they work today. The EROM was only loaded so far, but it was not even mapped to memory, it was completely unused.

**Comment by refractionpcsx2** [comment]
If that's true, why didn't you open with that? Not being mapped at all is a much more valid reason than "This thing we can't use is in the wrong place"

However it looks like it was mapped to EROM to me?

**Comment by Florin9doi** [comment]
https://github.com/PCSX2/pcsx2/blob/5e87f6d806fe34e361cb1494e5fee893daf06388/pcsx2/x86/iR3000A.cpp#L805
https://github.com/PCSX2/pcsx2/blob/5e87f6d806fe34e361cb1494e5fee893daf06388/pcsx2/x86/ix86-32/iR5900-32.cpp#L616

**Comment by refractionpcsx2** [comment]
Okay I see what you mean.

**Comment by refractionpcsx2** [comment]
well, it would be nice if you provided a solution for all existing bios dumps, if an .erom file is detected then map that to the correct space in memory.  You can check the BIOS version and adjust the mapped location manually.  I don't agree with not supporting existing roms and rom dumpers to force your own ideal on to everyone.

**Comment by refractionpcsx2** [comment]
Woudl you like to try https://github.com/F0bes/biosdrain/pull/10 along with your PR? Also if you could make your commit names somewhat match our standard that would be cool (an appropriate prefix, like BIOS: or something..)

**Comment by Florin9doi** [comment]
Rebased and prefixed. I tested https://github.com/F0bes/biosdrain/pull/10 on a 90k and it extracts a ROM1 file compatible with this PR, having the expected results - both alone and combined with #4274. After these changes, the bios files may be checked against redump database, eventually automatically.

**Comment by refractionpcsx2** [comment]
Alright, thanks :)

**Pull request merged**
