### PR TITLE
(GSDumpGUI) Make sure all child processes are closed when closing main form

### PR DESCRIPTION
**Pull request by Souzooka**
This change adds a function to handle the main form being closed, in which all processes are forcibly killed if not already killed.

### CODE REVIEW

**Comment by lightningterror** [comment]
Kojin will be happy.

**Comment by Souzooka** [comment]
See the new commit @willkuer

**Comment by willkuer** [comment]
This is a good improvement and most probably sufficient. I however meant that you could consider to put it in the Form.Dispose() method. E.g. if I would put an event in front of Form_closing that set event handled to true or I find a way to close the window without executing the form closing event (ie. task kill, application.Exit(), ...).

For me Form_Closing is rather to display a Closing animation or to stop a timer.

Form.Dispose() is for releasing resources as killing and disposing processes or disposing timers and so on.

Also you could consider that a closed window could still be kept in memory (not sure whether WinForms calls Form.Dispose() on Form.Close() but I wouldn‘t expect it - I didn‘t work with WinForms since a few years). And the question then would arise whether the processes should be disposed or not.

So my suggestion: `Form_Closing => Processes.ForEach(p=> p?.Cancel());` (or however that is done on processes) and public ```void Dispose(bool disposing = true)
{
    // default disposing pattern according to MSDN documentation regarding finalizer and such
    /// and whatever WinForms put there like
    // button1.Dispose();

   Processes.Foreach(p=> p?.Dispose());
}
```

But as I said your solution might suffice...

**Comment by lightningterror** [comment]
What is the status, are we waiting on suggested changes @willkuer or it can be merged like this ?

**Comment by willkuer** [comment]
PR is already a thousand times better than master and this is a dev tool. Just merge it. Nobody really cares if you follow dispose pattern in dev tools.

**Comment by ssakash** [comment]
@willkuer  https://github.com/PCSX2/pcsx2/issues/1637

**Pull request merged**
