### PR TITLE
Qt: Add Video Capture Button to the Toolbar

### PR DESCRIPTION
**Pull request by kamfretoz**
### Description of Changes

This PR adds the Video Capture Button to the Toolbar for easier access, the old way of accessing it through the Tools menu remains unchanged. I have also added a custom icon for it.

List of changes:

- Adjusted the name of the variables to better match the context since there are now more than one way to access the Video Capture feature.
- Added Custom icon to go with the new button.

- Even more polish to the Cobalt Theme (made the inactive text label a bit darker to better distinguish it).

Here's a preview:
Screenshot_20230421_213406

### Rationale behind Changes

Having the button in the toolbar made accessing it easier and potentially allows more people to discover it's existence!
And not having to open the Tools menu everytime to access the feature is a time saver!

### Suggested Testing Steps

Tests if the buttons are working properly! ;)
I have tested it myself (they're working great!) but if you found any issues please do let me know! :D

### CODE REVIEW

**Comment by RedDevilus** [comment]
Maybe the time to also revise the name, Video Capture to perhaps Record or something else as it can also be toggled to do only Audio Recordings, Video-only recording or both.

**Comment by kamfretoz** [comment]
> Maybe the time to also revise the name, Video Capture to perhaps Record or something else as it can also be toggled to do only Audio Recordings, Video-only recording or both.

What do you think about "Start Recording" ?

**Comment by RedDevilus** [comment]
I guess, there is already Input Recording for TAS, so it kinda makes sense.

**Comment by kamfretoz** [comment]
I'm thinking of something in the line of "Record Gameplay" as it is the one we are recording to not be confused with "Input Recording".

**Comment by RedDevilus** [comment]
> I'm thinking of something in the line of "Record Gameplay" as it is the one we are recording to not be confused with "Input Recording".

Keep in mind it still needs to fit the icon space and other languages.

**Comment by refractionpcsx2** [comment]
Record Video would be fine to me, tbh

**Comment by stenzek** [comment]
Bit iffy on this one.. there isn't that free much space in the toolbar, and it's arguably not going to be a highly used feature.

**Comment by kamfretoz** [comment]
I've tested few small screen scenarios:

- 1366x768 screen
1366x768

- 1080p screen with 150% (Recommended) scaling applied
1080p50%

There is quite a bit of free space, and in my opinion its not too cramped.

Also i do hope that even more people knows more about the awesome built-in video recording capability so they don't have to rely with external software like OBS!

**Comment by kamfretoz** [comment]
Rebased with the help of beard and chroma!

**Comment by stenzek** [comment]
If it's maximized, yes. But not at the default window size.

**Comment by refractionpcsx2** [comment]
best to make a copy with no ini files and load fresh so everything is default, then turn the toolbar on.

**Comment by kamfretoz** [comment]
okay yeah that is fair, some of the buttons (Settings and controllers) does indeed got cut off and had to be resized a bit.


default


I see 2 ways to go about this, either we: 
- hope the user plays in maximized mode or they resize the window at some point
- enlarge the size of the default window a little bit

**Comment by stenzek** [comment]
I'm not against the idea of having video capture as an *option* in the toolbar, I just don't think it should be in there by default, since it's such a rarely used feature.

Which means we'd have to make the item set customizable first.

**Comment by refractionpcsx2** [comment]
I suggested changing the screenshot button to be a "Capture" button with a popup/dropdown which you can pick screenshot or video, but I was shot down :P

**Comment by kamfretoz** [comment]
My idea is so that for those who uses the toolbar, more people can be made aware of the availability of such built-in video recording feature which in this case can potentially increase the usage of it for those who needs the feature instead of relying on external software. and in my opinion the recording feature is not a terribly obscure feature that are used by the niches of the niche (like input recording or PINE). And for those don't use the toolbar can still access it through the old ways.

Plus having it in the toolbar is quicker than having to go Tools and pressing video capture.

**Comment by kamfretoz** [comment]
> I suggested changing the screenshot button to be a "Capture" button with a popup/dropdown which you can pick screenshot or video, but I was shot down :P

That could work as well :P

**Comment by stenzek** [comment]
The average user is better off using OBS etc. The encoding in PCSX2 is CPU-only (at least for now), and struggles at higher resolutions unless you have a ton of CPU cores.

**Comment by kamfretoz** [comment]
I understand, in this case i'll close this PR for now.

**Pull request closed without merging**
