### PR TITLE
GSdx: Add missing CRC for Tomb Raider Underworld

### PR DESCRIPTION
**Pull request by lightningterror**
NTSC-U version.

Issue #2027

### CODE REVIEW

**Comment by mirh** [comment]
Would it be possible to squash the two commits? 🙃

**Comment by lightningterror** [comment]
I never was able to do on those type of commits , that update the forked branch , dunno why , maybe I'm missing something.

**Comment by ssakash** [comment]
> I never was able to do on those type of commits 

I've cherry picked the valid commit to master branch, I didn't do squash-merge as I was unsure if it would properly squash the remote tracking commit.

**Comment by gregory38** [comment]
it is the merge commit, isn't it ? A rebase should fix it. A squash merge should work too. Because it does a squash + rebase.

**Comment by lightningterror** [comment]
That's weird , it doesn't work for me , It doesn't even appear when squash / rebasing , all others do.
Maybe it's because I'm using the GitHub desktop that comes with it's git shell and not the other Git application that provides more options.

**Comment by ssakash** [comment]
> it is the merge commit, isn't it ? A rebase should fix it. A squash merge should work too. Because it does a squash + rebase.

Good to know. Thanks for the information. :)

**Comment by mirh** [comment]
> not the other Git application that provides more options

That's quite cooler.

**Pull request closed without merging**
