### PR TITLE
GameDB: Add VU Clamp Mode and GIF FIFO Hack to SOCOM 1

### PR DESCRIPTION
**Pull request by MrCK1**
This PR resolves bad shadows and random sprite/HUD corruption in SOCOM 1.

### CODE REVIEW

**Comment by ssakash** [comment]
What about the performance impact with GIF FIFO hack in the parts of the game? I'm pretty sure @refractionpcsx2 told me it'll be more demanding. (Just wondering if the performance-accuracy trade is worthy enough to leave it on automatically)

**Comment by refractionpcsx2** [comment]
Probably more demanding, but if it needs it, it needs it

**Comment by MrCK1** [comment]
Well the other option is to use the EE Timing Hack, but we can assume this option is at least a bit safer (and supposedly more correct?) :P

In this instance, I didn't see any speed penalties during my testing.

**Comment by refractionpcsx2** [comment]
Yeah it's more correct. I guess it's going to depend on the performance hit to if the users would use one hack over the other. Is there issues in using the ee timing fix?

**Comment by MrCK1** [comment]
I didn't do any thorough testing using the EE Timing hack but I can check later before we merge this.

**Comment by lightningterror** [comment]
> CK: There's no perf difference with EE timing hack, you can merge it.

**Pull request merged**
