### PR TITLE
Atelier Marie + Elie: Salburg no Renkinjutsushi 1&2 Fix

### PR DESCRIPTION
**Pull request by darkxex**
Fix misaligned textures.

### Description of Changes
The game has the textbox textures misaligned, this fixes it.

### Rationale behind Changes
Before:
image
After:
image

### Suggested Testing Steps
Just test the game... this only fix the 2x internal resolution or more....

### CODE REVIEW

**Comment by RedDevilus** [comment]
Maybe instead of calling it splitted text box , you could say it `Fixes the sprites on textbox and characters.`  ?

**Comment by darkxex** [comment]
> 

Sure my friend.

**Comment by RedDevilus** [comment]
If you can squash your 3 commits into one, it should be ready for merge I guess.

**Comment by darkxex** [comment]
wait a moment.

**Pull request closed without merging**
