### PR TITLE
Update pcsx2-qt_ko-KR.ts

### PR DESCRIPTION
**Pull request by Hackjjang**
I want to check the translation results.

### CODE REVIEW

**Comment by RedDevilus** [comment]
You can download the translation file itself and insert the `.qm` files (not sure if `.ts` works) inside the` /translations` folder, Upstream is not a place for testing translations.

**Comment by Felipefpl** [comment]
> I want to check the translation results.

https://crowdin.com/project/pcsx2-emulator

**Comment by RedDevilus** [comment]
https://crowdin.com/project/pcsx2-emulator/ko

image

**Comment by Mrlinkwii** [comment]
@Felipefpl can you join the  discord and we can show you how its done

**Comment by Hackjjang** [comment]
We can use qt linguist.

**Comment by stenzek** [comment]
Linguist, or running `lupdate` manually to compile will work fine. Just drop the resulting .qm file into the `translations` directory.

**Comment by Hackjjang** [comment]
@stenzek DuckStation has also been translated into Korean.

**Comment by RedDevilus** [comment]
@Hackjjang Please don't ping random members. They are free to do whatever they want, whenever they want. If you do want to talk (not pinging), you can do as such in the Discord channel.

**Pull request closed without merging**
