### PR TITLE
Fix some vsync related issues, implement Vulkan adaptive vsync

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Vsync was flaky since the frontend/host display refactoring (my fault). This fixes it and makes it reliable again.

Also adds adaptive vsync (FIFO_RELAXED) for Vulkan.

### Rationale behind Changes

Fixing my bugs.

### Suggested Testing Steps

Make sure vsync works as expected now.

### CODE REVIEW

**Comment by gilderoylockhart01** [comment]
I have a question regarding Vsync, does it takes into account the Gsync technology for 50Hz games? (by that I mean, lowering down the refresh rate of the monitor)?

**Review by JordanTheToaster — APPROVED** [review]

**Comment by stenzek** [comment]
How VRR gets activated depends on the API.

**Comment by gilderoylockhart01** [comment]
With an Nvidia GPU, this will work with DirectX 9/10/11/12 if the window is in fullscreen and exclusive mode (or in flip mode).

**Comment by stenzek** [comment]
Not according to MS's documentation: https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/variable-refresh-rate-displays

We set this flag when vsync is **off**.

**Comment by gilderoylockhart01** [comment]
Okay, for some weird reasons this did work with those settings on my system in the past. Nevermind, now with the PR it works as expected.

**Pull request merged**
