### PR TITLE
cdvdgigaherz: Improve CD handling

### PR DESCRIPTION
**Pull request by turtleli**
Changes:
* Detect the CD data track mode correctly
* Always use a raw sector read to read from a CD, which prevents read errors in some games i.e. Suikoden (SLES-00527)

### CODE REVIEW

**Comment by MrCK1** [comment]
What type of content will this affect? Any non-PS2 disks ect?

**Comment by turtleli** [comment]
CDs.

**Comment by MrCK1** [comment]
Ah ok. I guess I'll make sure Audio CDs still work.

**Comment by turtleli** [comment]
Audio CDs don't really work on my end on master or on this branch? Trying to play track 1 plays the last track, and playing any track only works for ~2 seconds, after which it automatically stops (but pausing/resuming the music repeatedly works).

Did it work at some point?

**Comment by MrCK1** [comment]
Audio CDs have always worked. The EE has to be underclocked to -3 and IOP set to Interpreter. This core timing could be worth a look in the future.

**Comment by turtleli** [comment]
#2096 should fix the track number issue.

**Comment by MrCK1** [comment]
Yeah I'll check that. I'm about to see if the slowdown occurs in older builds - I don't usually use physical disks so I don't remember their behavior that well.

**Comment by bositman** [comment]
@MrCK1  Isn't this ready to merge?

**Comment by MrCK1** [comment]
Yeah this has been ready to merge. Maybe @turtleli  forgot.

**Comment by turtleli** [comment]
Well, I left it unmerged to allow people time to test it. The Suikoden read error in master doesn't seem to cause any actual issues (game still seems to work though I didn't test much), and it's not like anyone else really touches cdvdGigaherz anyway, so I didn't really feel the need to quickly merge this.

**Pull request merged**
