### PR TITLE
GameDB: Change upscaling fix Valkyrie Profile 2

### PR DESCRIPTION
**Pull request by RedDevilus**
### Description of Changes

HPO 1 to 2
### Rationale behind Changes

Normal Vertex has more issues than Special Vertex
### Suggested Testing Steps

Test VP2

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Special (Texture) causes graphical errors in the forest


Normal Vertex:
image

Special Texture:
image

**Comment by JordanTheToaster** [comment]
> Special (Texture) causes graphical errors in the forest
> 
> Normal Vertex: image
> 
> Special Texture: image

Normal Vertex causes lines in trees 

image

Special 

image

**Comment by refractionpcsx2** [comment]
I guess it's a pick your poison thing then..

Does round sprite full also cause any issues elsewhere? in the forest it lessens the green boxes further than half

**Comment by coornio** [comment]
> I guess it's a pick your poison thing then..
> 
> Does round sprite full also cause any issues elsewhere? in the forest it lessens the green boxes further than half

It has an effect on the ghosting that HPO removes, so if you go for Full then the ghosting comes back. 
Speaking of, where may I get a dump of the red forest? :)

**Comment by refractionpcsx2** [comment]
[vp2forest.zip](https://github.com/PCSX2/pcsx2/files/8840833/vp2forest.zip)

here you go

**Comment by coornio** [comment]
Thanks. Frame Buffer Conversion + Preload Frame Data removes the red lines/noise introduced with HPO Special Texture. No effect on anything else from the looks of it.

**Comment by refractionpcsx2** [comment]
Can confirm those options do seem to resolve it...

@JordanTheToaster @RedDevilus do those options have a negative impact elsewhere?

**Comment by refractionpcsx2** [comment]
Preload Frame makes the FMVs flicker, so the SW mode switch for FMV's would also be required.

**Comment by coornio** [comment]
Also noticed that "Disable Depth Emulation" resolves the thick red line on the bottom of the screen in the red forest.

**Comment by refractionpcsx2** [comment]
I'd rather not disable depth, if it can be helped, that can fuck up post effects (and this game does a lot of them in cutscenes)

**Comment by coornio** [comment]
> I'd rather not disable depth, if it can be helped, that can fuck up post effects (and this game does a lot of them in cutscenes)

Sure thing, just pointed it out in case it can turn out to be useful. I don't have the game so I can only check these through the dumps :)

**Review by lightningterror — CHANGES_REQUESTED** [review]
I'd just remove HPO and let the user tinker with it since there's no good option.

**Comment by lightningterror** [comment]
So what will we do about this?

**Comment by refractionpcsx2** [comment]
Since no progress has been made on this and it's really down to user preference tbh, gonna close this.  Users can set it per game if they want something different.

**Pull request closed without merging**
