### PR TITLE
Counters + DMA: Optimize when internal interrupts run

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Optimise when internal interrupts run, reducing exits from the EE, improving performance.
Also improved the EE/IOP sync to split more efficiently.

### Rationale behind Changes
More brrr

### Suggested Testing Steps
Test games, feel free to compare to master :) Make sure nothing broke in the process.

Examples of performance improvements.  FMV's around 10-30% faster, ingame anywhere from 1-7% faster (in testing)

FMV's
image
image

Ingame benchmarks
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by bigol83** [comment]
Two more comparisons

LOTR
onimusha

**Comment by DonelBueno** [comment]
This gives me a 15% speedup on GTA LCS in-game on a Ryzen 5800x, very good.

**Comment by refractionpcsx2** [comment]
15%? wow that's pretty cool, thanks!

**Comment by TransparentBlue** [comment]
About a 25-30% boost in Ape Escape 3 when using the radar (76-80fps to 99-101fps on a 5900X)

**Comment by refractionpcsx2** [comment]
whoa! Neat!

**Comment by bigol83** [comment]
Is this PR up to date with latest master? I would like to compare speed results with master.

**Comment by refractionpcsx2** [comment]
not at the moment, no.  I can rebase it though, I guess.

**Comment by bigol83** [comment]
Look at this, another speedup compared to Master
MGS3

**Comment by refractionpcsx2** [comment]
tiny one, yea :)

**Review by JordanTheToaster — APPROVED** [review]

**Review by Mrlinkwii — APPROVED** [review]

**Pull request merged**
