### PR TITLE
GameDB: Fix patch for Michigan: Report from Hell

### LINKED ISSUE #9223: [BUG]: Michigan - Report from Hell (SLES-53073) - Playability Issue
### Describe the Bug

During the intro scene after starting a new game you're given a task to focus the camera on a group of boxes. In the latest nightly build this event does not seem to trigger properly. Instead of your reticle changing to an orange circle, indicating you can focus on the objects, nothing happens. Because of this, you are unable to progress past this point in the game.

According to the Michigan - Report from Hell Wiki, the last fully playable revision was 3191. Which I was able to test, and was able to progress normally using that build.

Also, this bug does not appear when playing the Japanese version of the game.

### Reproduction Steps

1. Start a new game
2. Interact with Brisco until you're prompted to focus on the boxes next to the starting point

### Expected Behavior

You are expected to be able to interact with these boxes so you can progress the game. When the boxes are interactable and highlighted, your reticle will transform into an orange dot.

### PCSX2 Revision

1.7.4718

### Operating System

Windows 11

### If Linux - Specify Distro

_No response_

### CPU

i9-9900KF

### GPU

RTX 3070 Ti

### GS Settings

All graphics settings are default except for Bilinear Filtering under Display Settings, which is set to None.

### Emulation Settings

All emulation settings are set to default. Attempted to update EE Cycle Rate to 75%, as suggested on the game's wiki to solve other problems, but this did not help.

### GS Window Screenshots

Behavior using revision 4718:
Michigan-Revision4718 mkv_snapshot_00 59_ 2023 07 10_18 14 34

Behavior using revision 3191:
Michigan-Revision3191 mp4_snapshot_01 00_ 2023 07 10_18 15 20

### Logs & Dumps

[Michigan-Dumps4718.zip](https://github.com/PCSX2/pcsx2/files/12009327/Michigan-Dumps4718.zip)

### PR DESCRIPTION
**Pull request by Goatman13**
### Description of Changes
Fix my previous patch to not read corrupted data from stack. 
### Rationale behind Changes
Fixes #9223
### Suggested Testing Steps
Test intro scene with carton boxes, test going to first floor in library (attached card).
https://github.com/PCSX2/pcsx2/files/9310139/Mcd002.zip

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
oh, was t0 == sp? :D

**Comment by Goatman13** [comment]
Original code:
```
0x15D1F0   addiu        $v0, $sp, 0x30    <-- move sp + 0x30 to v0
0x15D1F4   lui          $v1, 0x3F80
0x15D1F8   sqc2         vf30, 0($v0)      <-- store result
0x15D1FC   addiu        $a0, $sp, 0x20
0x15D200   mtc1         $v1, $f3
0x15D204   lwc1         $f1, 0x3C($sp)    <-- read it
0x15D208   cfc2         $t0, vi2, interlocked
```

So when i replaced cfc2 with sqc2, lwc1 read corrupted data. Easy to miss, hard to find.

**Comment by refractionpcsx2** [comment]
oh yeah! It's pointing to the W vector of the read data, isn't it! yeah that's quite a tough one to catch without thinking hard about it, well done! :)

**Comment by refractionpcsx2** [comment]
Anyway, tried the patch locally, works great in both scenarios, thanks!

**Pull request merged**
