### PR TITLE
GameDB: Add VU Clamping to Twisted Metal - Head-On

### PR DESCRIPTION
**Pull request by Hallkezz**
Fixes missing textures in the game. For example, in the cutscene before the final boss.

### CODE REVIEW

**Comment by Mrlinkwii** [comment]
can i have a savestate , just to double check :)

**Comment by Hallkezz** [comment]
> can i have a savestate , just to double check :)

[SCUS-97621 (3DC2FE45).02.zip](https://github.com/PCSX2/pcsx2/files/12566058/SCUS-97621.3DC2FE45.02.zip)

**Comment by Mrlinkwii** [comment]
can i have a before and after because i  because i may  be blind / looking in the  wrong place

**Comment by refractionpcsx2** [comment]
LGTM however can you update the patch while you're here, another bad place showed up in that savestate

patches:
    3DC2FE45:
      content: |-
        author=refraction
        // COP2 rearrangement. RSQRT directly followed by DIV and a few ops using Q causes issues
        // Fixes fire effects
        patch=1,EE,00237eb0,word,4b000060
        patch=1,EE,00237ec0,word,4a0203bd
        patch=1,EE,002461d8,word,4bf4b33c
        patch=1,EE,002461dc,word,4b806d9c
        patch=1,EE,002461e0,word,4bc069fc
        patch=1,EE,002461e4,word,4a54c3bc


it's just the first two patch lines need adding, if you can. Thanks

**Comment by refractionpcsx2** [comment]
Here's comparison screenshots for the clamping change, anyway.

Master:
image
PR:
image

**Comment by refractionpcsx2** [comment]
Thanks!

**Pull request merged**
