### PR TITLE
Fix SPU2x XAudio 2.7 compilation

### PR DESCRIPTION
**Pull request by KrossX**
Includes four headers from the DirectX SDK with some `#include <dxfile>` into `#include "dxfile"` changes.

### CODE REVIEW

**Comment by lightningterror** [comment]
I believe this should also be merged for 1.6 release as it provides us with a fully working build that compiles without issues which will be later the 1.6 branch.

XAudio 2.7 will be dropped for 1.8 release so current pr/code will be only temporarily there.

**Comment by turtleli** [comment]
> as it provides us with a fully working build

? What currently doesn't work?

**Comment by lightningterror** [comment]
There is an issue with newer VS 2017/19 with compiling spu2x on Windows 10, a misdetection between 2.7 and 2.8. I don't know the full details since I'm on w7 still.

**Comment by KrossX** [comment]
This just makes XAudio 2.7 build without requiring DX SDK. It should also avoid it being skipped when built on a Windows 8+ OS so that such a build would include XAudio 2.7 for Windows 7 users.

Current automatic builds work just fine.

**Comment by turtleli** [comment]
> It should also avoid it being skipped when built on a Windows 8+ OS so that such a build would include XAudio 2.7 for Windows 7 users.

This doesn't make sense to me. It should build the same regardless of operating system.

**Comment by KrossX** [comment]
It just means that if `_WIN32_WINNT >= 0x602` there's no reason to skip 2.7. It's currently set as 0x600, if undefined.

Still, automatic builds are building just fine. This just makes it easier for me to build it by switching branches. Also, if W7 support will be removed after 1.6 release, there's no reason to merge this at all.

**Comment by lightningterror** [comment]
> Also, if W7 support will be removed after 1.6 release, there's no reason to merge this at all.

Don't take away my baby :cry:

**Comment by mirh** [comment]
> Don't take away my baby

You were the one saying this?
It's not like you can keep W7 if you drop 2.7. 

And of course it doesn't make sense for me to do so.

**Comment by lightningterror** [comment]
We had a discussion on discord to use Xaudio on windows 10 and Portaudio on lower.

**Comment by tadanokojin** [comment]
@turtleli Li, it does build but you need some SDK for win10. Otherwise there is a define guard that produces some nonsense build error about your windows not being recent.

**Comment by turtleli** [comment]
It builds on my end without requiring modifications.

What error message pops up?

**Comment by tadanokojin** [comment]
> This version of XAudio2 is available only in Windows 8 or later. Use the XAudio2 headers and libraries from the DirectX SDK with applications that target Windows 7 and earlier versions.

#2727

**Comment by turtleli** [comment]
That's not actually talking about what Windows version you're using.

It's saying that you're trying to support Windows 7 and earlier (detected from the _WIN32_WINNT define) and that the header is for XAudio2.8+.

That error should only pop up if the DXSDK is not detected.

**Comment by mirh** [comment]
> We had a discussion on discord to use Xaudio 2.8 on windows 10 and Portaudio on lower.

Eww. I don't know, it always gave me a very cheap impression I can't put my finger on. 
But whatever.

**Comment by lightningterror** [comment]
I also tested a while back with appveyor vs 2019 and got the same result, maybe I was missing something extra?
https://ci.appveyor.com/project/lightningterror/pcsx2/builds/25959443/job/6mkahcx923lg1ep2

`         C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\xaudio2.h(20,1): error C1189:  #error:  "This version of XAudio2 is available only in Windows 8 or later. Use the XAudio2 headers and libraries from the DirectX SDK with applications that target Windows 7 and earlier versions." [C:\projects\pcsx2\plugins\spu2-x\src\Windows\Spu2-X.vcxproj]`

**Comment by turtleli** [comment]
https://github.com/appveyor/ci/issues/2953

**Comment by KrossX** [comment]
Turteli, click this thing -> https://discord.gg/TCz3t9k

**Comment by tadanokojin** [comment]
> It's saying that you're trying to support Windows 7 and earlier (detected from the _WIN32_WINNT define) and that the header is for XAudio2.8+.

Would be nice if it just error out with the link to the SDK. Error is kinda confusing and I'm not the first to think so.

Anyway, not to be off-topic. Is it even legal to include MS code like this?

**Pull request closed without merging**
