### PR TITLE
GunCon2: Add screen parameters for more games

### PR DESCRIPTION
**Pull request by Comfarol**
first ever commit on github hope this is right

### Description of Changes
Added Vampire Night PAL cross hair values
Improved Time Crisis 3 and 2 values

### Rationale behind Changes
Alot of PAL values missing for light gun games

### Suggested Testing Steps
Calibrate and play

### CODE REVIEW

**Review by stenzek — APPROVED** [review]
LGTM. If you know how, could you amend the commit to `GunCon2: Add screen parameters for more games` or something similar. If you're not, that's fine, whoever merges this can change the title then.

**Comment by Comfarol** [comment]
> LGTM. If you know how, could you amend the commit to `GunCon2: Add screen parameters for more games` or something similar. If you're not, that's fine, whoever merges this can change the title then.

like that or is it something else?

**Comment by stenzek** [comment]
Nah, needs to be the commit (for history purposes). It's okay, whoever merges can squash+amend it.

**Review by Mrlinkwii — APPROVED** [review]

**Comment by dudesh34** [comment]
noice...is there a way to dusable the flash effect in those games.

**Comment by F0bes** [comment]
From my understanding, the way the gun works is by making the targets the **only** thing drawn on the screen.
[source](https://youtu.be/SWFxuwaZ2nI?t=111)

You might be able to remove the flashing by patching the game (not a feature that can be supported automatically by the emulator), but you might end up breaking the light gun feature entirely.

**Comment by dudesh34** [comment]
> From my understanding, the way the gun works is by making the targets the **only** thing drawn on the screen. [source](https://youtu.be/SWFxuwaZ2nI?t=111)
> 
> You might be able to remove the flashing by patching the game (not a feature that can be supported automatically by the emulator), but you might end up breaking the light gun feature entirely.

yep, i just cant play with the flashes, makes me feel ill...i guess i will stick to the old patched versions.

**Pull request merged**
