### PR TITLE
Pad: Add Pop'n Music controller type

### PR DESCRIPTION
**Pull request by RedPanda4552**
### Description of Changes
Adds an implementation of the Pop'n Music controller. Yep, that's the whole thing.

Side note: Like with guitars, automatic mapping with this controller type will make no damn sense at all because it isn't a normal gamepad. That is not a bug, that is a consequence of having a unique button layout, and it is up to the user to do it manually if they want mappings that make sense. Get over it.

### Rationale behind Changes
Easier for users to set up than trying to guess what DS2 controls they need to map to for a Pop'n controller to make "sense". At least some of the games don't strictly require the Pop'n Music controller, but perhaps others might, so that's another reason.

### Suggested Testing Steps
Fire up one of the Pop'n Music games, see if the controller reacts the way you expect it to.

### CODE REVIEW

**Comment by RedPanda4552** [comment]
As per usual, I am no artist, and I have suppled a scuffed png for the reference image in the mapping screen. Please hold merge until we can get a proper svg for it.

**Comment by RedDevilus** [comment]
How does this supposed eldritch horror draft of a png look like? ;)

**Comment by RedPanda4552** [comment]
Another point of interest is that we do not have font icons directly suitable for these buttons, since they are all circles with solid colors. I went ahead and just used the DS2 button icons which would match the literal bitmask that the Pop'n controller uses.

I am open to changing that, but someone would need to find a way to supply icons which can somehow convey both position and color of the buttons, in a tiny and monochromatic font icon that will render as text at the bottom of the OSD. Not exactly something I think there's a better solution for, but I hope I can be proven wrong on this one.

**Review by stenzek — APPROVED** [review]
Looks fine from a quick glance

**Pull request merged**
