### PR TITLE
GS/HW: Optimize TC source size based on CLAMP

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Seems that quite a few games use a large TW/TH, then use region clamp/region repeat to sample from a subset of this area.

This makes the hash cache size explode, as well as preventing texture replacement. So let's fix that.

In addition, we can hopefully get rid of the invalid tex0 hack too, since this will take care of these cases.

TODO still:
- [x] Fix none preloading with region textures
- [x] Add field to replacement texture filenames for clamp/region
- [x] Fix Metal
- [x] Waste less space in the uniform buffer
- [x] Get rid of invalid tex0 hack.
- [x] Fix lupin not working with none preloading

### Rationale behind Changes

Making texture replacements better, less vram usage, and more performance.

### Suggested Testing Steps

Test games which previously had hash cache issues.

### CODE REVIEW

**Comment by stuken** [comment]
This had caused a regression with Ridge Racer V. The intro sequence explodes the hash cache, runs between 2-15fps and is more corrupted than usual.

image

**Comment by Cyberosis** [comment]
This appears not to load replacement textures. unless I'm doing something wrong. option works in nightly.

**Comment by refractionpcsx2** [comment]
are you using textures you made from this PR? because it's very possible the signatures have changed in this PR compared to master.

**Comment by Cyberosis** [comment]
using textures made by this PR. strangely they work in nightly even though nightly spits out different, more broken textures.

**Comment by refractionpcsx2** [comment]
okay well maybe hold out, I know Sten was doing some work on trying to get texture hashes etc right in this PR, so maybe that will have an effect. Come back later :)

**Comment by Cyberosis** [comment]
will do

**Comment by stenzek** [comment]
Non-region replacements weren't being parsed correctly, should be fine now.

**Pull request merged**
