### PR TITLE
GameDB: Add Disable InstantVU to MGS 3 Subsistence

### PR DESCRIPTION
**Pull request by JordanTheToaster**
### Description of Changes
Disables InstantVU1 to fix missing letters in text such as the letter E also adds more fixes and missing fixes for Forever Kingdom / Evergrace 2.

### Rationale behind Changes
Missing l tt rs ar bad,

### Suggested Testing Steps
Make sure CI is happy.

### CODE REVIEW

**Comment by nobleflame** [comment]
Hi, just letting you know that this change has halved my frame rate. 

Even if I manually InstantVU1, the game still runs with a very unstable frame rate, fluctuating between 30 and 45 fps. 

In the QT dev build prior to this, v1.7.4015, the game ran at a consistent 60 fps.

**Comment by refractionpcsx2** [comment]
Maybe this can be replaced with the InstantDMA gamefix instead, like MGS 2 (though the fixes for MGS 2 seem to be all over the place)

**Comment by nobleflame** [comment]
Worth looking at - thanks for this. I know the fix in this pull request aimed to fix letters displaying incorrectly, but as this completely breaks the frame rate, I don't see it as worth while.

**Comment by refractionpcsx2** [comment]
@nobleflame it should be all working and faster once #8686 merges.

**Comment by nobleflame** [comment]
> @nobleflame it should be all working and faster once #8686 merges.

Blimey, that was quick! You guys are wizards :)

**Pull request merged**
