### PR TITLE
Gsdx 1.0

### PR DESCRIPTION
**Pull request by gregory38**
Ok time to merge the big change.

@refractionpcsx2 
Could you check latest addition still compile on windows and DX is still working as bad as before.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
I will test this tonight, might actually have some free time :P

**Comment by bositman** [comment]
I propose we add the new logos too ;)

**Comment by refractionpcsx2** [comment]
OK DX doesn't seem to fall over or generally look any worse, in fact the blur on VP2 nearly works, which is weird :P

MGS3 on minimal crc or lower = 80fps, with partial or higher 180fps

**Comment by gregory38** [comment]
Well blur will (mostly) work if CRC is below full.

Great. Let's merge it. So people can test it more easily.

**Comment by refractionpcsx2** [comment]
I did get a weird error but i wasn't able to reproduce it, i think i modified some settings then loaded a different game, but i got

Totally mismatched window handles on OverrideWndProc!
Totally mismatched window handles on OverrideWndProc!
Totally mismatched window handles on OverrideWndProc!
Totally mismatched window handles on OverrideWndProc!
Totally mismatched window handles on OverrideWndProc!
Totally mismatched window handles on OverrideWndProc!
Totally mismatched window handles on OverrideWndProc!

that many times ;p

**Comment by gregory38** [comment]
I think it is a gui issue, likely the tooltip. It might be a good idea to review it a little :+1:

**Comment by refractionpcsx2** [comment]
I tried making tooltips come up, swapping renderers, switching settings, bringing the settings up while the emulator was running, escaping then opening them and changing options and resuming, nothing seemed to trigger it :(

**Comment by DonelBueno** [comment]
Sorry for the noob question, but what does this improve? Are games more accuratelly emulated now in hardware mode both in OGL and DX?

**Comment by refractionpcsx2** [comment]
That's the idea,  it brings hardware mode closer to software

**Comment by ssakash** [comment]
> I propose we add the new logos too ;)

I thought the plan was for the next stable release ?

**Comment by bositman** [comment]
It was for the new version of GSdx, and this is marked as GSdx 1.0

**Comment by refractionpcsx2** [comment]
It got updated to 1.0 as gsdx was like 0.18. even the thread on the forum got changed to 1.0

**Comment by gregory38** [comment]
Hum, I hope you didn't put 2.0 in the new logo  ;)

**Comment by bositman** [comment]
Nope the logos don't have any number on them ;)

**Comment by DonelBueno** [comment]
Why hasn't mipmapping implemented on GSDX hardware mode yet? Is it harder to be implemented in hardware than it is in software or it was just lack of time?

**Comment by gregory38** [comment]
For sure it is harder to implement on HW.

The complexity of mipmap in HW is the texture management. If game uses mipmap in a traditional way, it must be doable. However it could be easily a nightmare. GS textures doesn't really have a size, neither a format. GS textures are a pointer to a raw data + an header of how to interpret them.

It takes times. It took me 3 months to add proper support for pseudo 8 bits/16 bits texture conversion and real depth support. Mipmapping is just a small part of GSdx limitation.

**Comment by DonelBueno** [comment]
Wow, I didn't know it was so complicated, it's usually simple in other systems.

Do you think DX12 and Vulcan will allow such things to be implement in hardware easier?

**Pull request merged**
