### PR TITLE
locale: purge wx locale files

### PR DESCRIPTION
**Pull request by Mrlinkwii**
### Rationale behind Changes

not needed anymore 
### Suggested Testing Steps
<!-- If applicable, including examples you've already tested with / recommendations for how to test further is very helpful! --!> watch CI go brr

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
For what it's worth, where should new translations be submitted?

**Comment by stenzek** [comment]
Probably via crowdin, but hasn't been decided yet

**Comment by Felipefpl** [comment]
Please, let it be transifex, much easier/better to work with.

**Comment by refractionpcsx2** [comment]
> transifex

fuck that, they charge $70 a month!

**Comment by RedDevilus** [comment]
Hell, then I would just use weblate at that point. Original plans for crowdin has free option afaik.

**Comment by IlDucci** [comment]
> Please, let it be transifex, much easier/better to work with.

Just to add my two cents, I HATE that many of the ALT+Keypad number combos are locked in Transifex, forcing me to use their cumbersome menu to add special characters around.

**Comment by Felipefpl** [comment]
> fuck that, they charge $70 a month!

@refractionpcsx2 - I found out this https://www.transifex.com/open-source/

**Comment by refractionpcsx2** [comment]
```Eligible projects are the ones with publicly available source codes licensed under an OSI-approved license, and have no funding, revenue, or commercialization model.```

We have funding from github sponsors + ads.  So I guess we'll have to see if they'd make an exception.

**Comment by Felipefpl** [comment]
I see, i hope they do.

**Pull request merged**
