### PR TITLE
Revert "Qt: Hide manual hardware fixes from global settings"

### PR DESCRIPTION
**Pull request by Buzzardsoul**
Reverts PCSX2/pcsx2#8381

Reason: We need it to debug gs dumps.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
No, it's removed because users can't be trusted, you can use the per game fixes with gs dumps.

**Comment by Buzzardsoul** [comment]
> No, it's removed because users can't be trusted, you can use the per game fixes with gs dumps.

Not if it's a game that you don't own.

**Comment by refractionpcsx2** [comment]
It doesn't matter, it still uses the game ident

**Comment by Mrlinkwii** [comment]
@Buzzardsoul 

you can use per game settings

**Comment by Buzzardsoul** [comment]
A gs debugger like the one we previous had would be preferable if possible. But in the meantime, I will look for another way.

**Comment by refractionpcsx2** [comment]
Thank you benevolent one.

**Pull request closed without merging**
