### PR TITLE
GS: Enable small framebuffers at 1x

### PR DESCRIPTION
**Pull request by tellowkrinkle**
### Description of Changes
- Stops the texture cache from downscaling targets when used as a source
- Enables smaller framebuffers even when rendering at 1x (previously only enabled at 2x+)
- Adds some optimizations to move sampling to hardware when possible (minor perf improvement on GT4)

Note: I did this by editing the vertex and fragment shaders to support rescaling normalized coordinates.  An alternative way to do it would be to just allocate full scale textures in this case.  Preferences?  (sampling the target directly mentioned below would need this approach)
Note2: This changes the renderer's interpretation of a texture whose `size / scale` does not match `tw` and `th` from "stretch to fit" to "use a 1-1 pixel scale".  Not sure if this breaks anything?  If it does, maybe those things should have set their scale properly...

### Rationale behind Changes
- Improves speed of Burnout at 1x on integrated GPUs with low memory bandwidth due to its access patterns making TC convert framebuffers to and from depth formats constantly (by reducing the size of those framebuffers).
- Improves the image quality of Burnout when upscaled to be the multiplier you selected and not that times 80% or so then nearest-neighbor upscaled back to 100%
- Should make removing the extra copies we do when using a target as a source a bit easier (future improvements, not included in this PR)

Example at 2x upscale:
ExampleA
ExampleB

### Suggested Testing Steps
Test 1x and 2x upscale for lots of games

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
The second picture definitely looks much better, the first picture is very blurry

**Comment by tellowkrinkle** [comment]
Not sure blurry is how I'd describe it, nearest neighbor is really garbage for non-integer upscales
Either way it looks terrible

**Comment by refractionpcsx2** [comment]
I'm afraid this doesn't work so well with mipmapping, as seen here in ratchet

image

should look like

image

GSDump:
[ratchetmips.zip](https://github.com/PCSX2/pcsx2/files/7921747/ratchetmips.zip)

**Comment by tellowkrinkle** [comment]
Mipmap issues should hopefully be fixed

**Comment by refractionpcsx2** [comment]
That's fixed, but there is another issue, it looks like the "half_right" code no longer works for Baldurs Gate 2 or Justice League. Seems OK on master.

image


Here's some dumps for you
[baldurgate2.zip](https://github.com/PCSX2/pcsx2/files/7965892/baldurgate2.zip)
[justiceslow.zip](https://github.com/PCSX2/pcsx2/files/7965893/justiceslow.zip)

**Comment by tellowkrinkle** [comment]
Should be fixed

**Comment by Dreadmoth** [comment]
Ratchet & Clank looks much nicer at any upscaled resolution 👍

-----
Videos seem to be broken in Baldur's Gate: Dark Alliance - this should be one of the intro logos:

BGDA-brokenvideo

Also affects the background in the main menu.
Occurs with all hardware renderers, native or upscaled.

[GS dump](https://github.com/PCSX2/pcsx2/files/7967868/BGDA_broken_menu_video_pr5387.zip)


-----
Champions of Norrath performance is significantly reduced (particularly on the main menu), without any noticeable change to image quality.


[Master menu](https://user-images.githubusercontent.com/8492684/151735540-4f0e4170-c3c1-4448-ab98-c11938e1c89b.png) (64 FPS)


[PR menu](https://user-images.githubusercontent.com/8492684/151735560-8b2a07bc-b35d-421d-b789-0b0eac60b5a4.png) (17 FPS)


[Master in-game](https://user-images.githubusercontent.com/8492684/151735581-a99bd8c3-1a67-455b-b440-85a1c2e38c89.png) (59 FPS)


[PR in-game](https://user-images.githubusercontent.com/8492684/151735585-7832302c-063f-478b-a757-33d0e42057f8.png) (27 FPS)

-----
Transformers has some kind of half-opacity fullscreen overlay which is upscaled on master, but appears to render at native resolution with nearest-neighbour scaling on this PR, resulting in the game looking progressively more pixelated as resolution is increased beyond 2x Native.

[Master 4x Native](https://user-images.githubusercontent.com/8492684/151733449-9b70b6b6-bdb5-49f7-ae5e-85fbd01ed322.png)

[PR 4x Native](https://user-images.githubusercontent.com/8492684/151733463-579bd1c2-43b6-4f13-bc48-6756d9446df6.png)

[GS dump](https://github.com/PCSX2/pcsx2/files/7967681/transformers_pixelation_pr5387.zip)

**Comment by tellowkrinkle** [comment]
Oh this PR is from when we had an issue with upscaling
Let me rebase and see if it's fixed for you

**Comment by tellowkrinkle** [comment]
Okay I'll look into it

**Comment by tellowkrinkle** [comment]
Transformers and Baldur's Gate should be fixed
Champions of Norrath perf probably as well but not sure so please retest

**Comment by tellowkrinkle** [comment]
Okay perf should be fixed

**Review by refractionpcsx2 — APPROVED** [review]

**Comment by refractionpcsx2** [comment]
Perf has returned, no visible bugs

**Comment by tellowkrinkle** [comment]
OK let me squash in the tmp commits then

**Comment by DonelBueno** [comment]
This PR introduces a glitch in Gran Turismo 4, a darkened area at the bottom of the screen, as can be seen in the following screenshot:

PCSX2_2022_02_18_18_33_50_735

It happens in any resolution above native and no change in settings fixes it.

**Comment by refractionpcsx2** [comment]
Can you provide a GS Dump?

**Comment by DonelBueno** [comment]
There you go:
[gs_20220219065418.gs.zip](https://github.com/PCSX2/pcsx2/files/8101885/gs_20220219065418.gs.zip)

**Comment by refractionpcsx2** [comment]
It works fine, you need to set Half Pixel Offset to "normal".

**Comment by DonelBueno** [comment]
Feeling kinda dumb right now x_x 
I thought it was a glitch because it didn't need that before this PR.

Thanks for the help.

**Pull request merged**
