### PR TITLE
OSD/FSUI: Adjust PromptFont for more readability

### PR DESCRIPTION
**Pull request by kamfretoz**
### Description of Changes

This PR attempts to redesign some of the icons used from PromptFont to maximize readability.

Credit to MBee/maxihplay for the new redesigned icons!

Preview:
Screenshot_20231216_111049

Screenshot_20231216_111109

Screenshot_20231216_111240

### Rationale behind Changes

👀 100

### Suggested Testing Steps

See if there's more icon that either needs changing or can be improved further.

### CODE REVIEW

**Review by lightningterror — COMMENTED** [review]
Having the sdl dpad colors swapped would be better, currently it looks like you're holding 3 buttons pressed at once.

**Review by Mrlinkwii — APPROVED** [review]

**Comment by MBeeBR** [comment]
> Ter as cores do dpad sdl trocadas seria melhor, atualmente parece que você está segurando 3 botões pressionados ao mesmo tempo.

?

**Comment by kamfretoz** [comment]
> Having the sdl dpad colors swapped would be better, currently it looks like you're holding 3 buttons pressed at once.

Fixed.
Screenshot_20231217_084224

**Comment by lightningterror** [comment]
That's much better.

**Comment by kamfretoz** [comment]
Added a guitar icon to the Input indicator too (bottom left).
Screenshot_20231217_191437

**Review by Mrlinkwii — APPROVED** [review]

**Review by JordanTheToaster — APPROVED** [review]

**Pull request merged**
