### PR TITLE
Fix regressions from WIL migration

### LINKED ISSUE #4785: [BUG]: Crash bug in SPU Reset (OK or Cancel from Config) [XAudio Only]
### Describe the Bug

When leaving the SPU Configuration screen while a game is active, the emulator locks up then crashes.

### Reproduction Steps

Start a game (any game) using any of the windows builds
Open the SPU settings
Cancel or Ok out of the settings (changes not necessary)

Window goes unresponsive, fades out, hangs a moment and then finally closes.

### Expected Behavior

It probably shouldn't do that.

### PCSX2 Revision

a546cb8

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

Xeon 1680v2

### GPU

GTX 1060

### GS Settings

_No response_

### Emulation Settings

_No response_

### GS Window Screenshots

_No response_

### Logs & Dumps

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/7188662/emuLog.txt)

### PR DESCRIPTION
**Pull request by CookiePLMonster**
### Description of Changes
This PR fixes two regressions caused by the ATL -> WIL migration (#4523):
* A "loudly failing" `wil::CoInitializeEx_failfast` revealed that subsystems (SPU, PAD etc.) initialization/cleanup was all over the place threading wise - initial setups were done on the **EE Core** thread, while teardown/reinit caused by opening settings was done on the **Main Thread**. This didn't play nice with COM initializations (and maybe other things), so I made sure PCSX2 delegates teardown/init to an appropriate thread.
* `GSSource` is implemented in means of `CUnknown`, which appears to violate one of COM rules and creates an object with a refcount of 0 instead of 1. I updated the code to account for this, together with a lengthy comment explaining what needs to be changed if this ever changes (as then it'll create a resource leak). This caused an assertion when stopping the GS Capture.

### Rationale behind Changes
Regressions are bad.

### Suggested Testing Steps
Test the following:
* Pausing/Resuming
* Opening/Closing all settings menus when no game is loaded
* Opening/Closing all settings menus when a game is loaded and not paused
* Starting and stopping the GS Capture

Fixes #4785.

### CODE REVIEW

**Comment by RedPanda4552** [comment]
Running through menus:
General Settings ✅ 
Memory Cards ✅ 
Graphics Settings ✅ 
Audio Settings ✅ 
Gamepad Settings ✅ 
Network Settings ✅ 
USB Settings ✅ 
Spamming Pause/Resume to death ✅ 
GS Capture ✅

**Comment by CookiePLMonster** [comment]
Updated with a bug fix for a `CoInitialize` failure when switching from PortAudio to XAudio2. Turns out PortAudio had its teardown code commented out years ago
https://github.com/PCSX2/pcsx2/commit/decf1da7638fe97f8f48b77e5ee3b46bc9785db4#diff-aaa168868a4ad1f55fb091df0b60a91b712a656dd728e853b397d73d3392fff5R248
but seems like now with the threading changes from this PR, it can be performed safely.

**Comment by CookiePLMonster** [comment]
Updated with a regression fix for `GSTexture11::Save`, RAII-based `Unmap()` was called after the pointers were mutated and thus failed. Now the call preserves the pointers to avoid this issue.

**Review by tadanokojin — APPROVED** [review]
LGTM, DX is no longer crashing.

**Comment by Squall-Leonhart** [comment]
This seems to have fixed a ucrtbase.dll crash that could happen when exiting the emulator while a game is actively running

Thanks CookiePLMonster.

**Pull request merged**
