### PR TITLE
GUI: Only add extension to new memcards on save

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Changes the memcard screen to only add the extension to new memcards on save.

### Rationale behind Changes
Because overengineering it to automatically take off the old extension and put it back on constantly not only causes problems (because it didn't work right) there's also no need, better just to add the extension when you save, and deny the use of decimal points.

### Suggested Testing Steps
Make some memcards, try different names, I'm sure something will break it and I won't care :)

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
I'm not sure how I'd do that, however I've changed it so if you try to put an extension (or specifically a decimal point) it won't let you, it'll remove any decimals.

IMO having to deal with extensions is more confusing for the user, unless of course they spent a lot of time making memory cards in PCSX2, like yourself :P

**Comment by RedDevilus** [comment]
On Qt, PS1 memcards make .ps2 instead of .mcr

**Comment by refractionpcsx2** [comment]
That's what this fixes?

image

**Comment by RedDevilus** [comment]
Yeah, that's what I meant that it fixed that behavior.

**Pull request merged**
