### PR TITLE
cdvdgigaherz: Read raw CD sectors one by one

### PR DESCRIPTION
**Pull request by turtleli**
A multi sector raw disk sector read that reads data from two tracks of different types will not complete successfully. Reading the sectors one at a time should fix the issue.

@MrCK1 Could you test the PS1 game(s) that previously had read errors?

### CODE REVIEW

**Comment by MrCK1** [comment]
Will do when I get a chance

**Comment by zuzma** [comment]
I'm probably wrong since I was just looking at the redump wiki and wikipedia, but it looks like it needs channel p for PlayStation games. Dunno if that would be the reason, unless i'm looking in the wrong spot. It also doesn't look like libcrypt games would work either

**Comment by turtleli** [comment]
Hmm. Code should be less likely to have read issues, though I might have misdiagnosed the problem. I probably need to add in some debug code, though I'm not sure I'll find anything out from doing so.

I do note that redump says that the first track has 31528 sectors but the log says it has 31678 sectors.

**Comment by zuzma** [comment]
Well it sounds like it's working properly then if it's adding 150 sectors. It was just a shoot in the dark really

**Comment by turtleli** [comment]
I added debug stuff to the commit. It won't fix the issue, but it might give me a better idea of what's failing (it may also completely confuse me too).

@MrCK1 Could you provide another log of the same game? Thanks.

**Comment by MrCK1** [comment]
@turtleli [Here's another one](http://pastebin.com/62iCHZjH)

**Comment by turtleli** [comment]
The log confuses me since the sense buffer is all 0. I don't know whether the read is succeeding but just not returning 2352 bytes. Commit has been updated again, so it needs another test.

**Comment by ramapcsx2** [comment]
This pr works better than master with my Battle Arena Toshinden 2 (PAL) CD.
With master, it just crashes shortly after the PSX logo. With this version, it gets ingame but can't load battles.

**Comment by FlatOutPS2** [comment]
> This pr works better than master with my Battle Arena Toshinden 2 (PAL) CD.
With master, it just crashes shortly after the PSX logo. With this version, it gets ingame but can't load battles.

Does the ISO load the battles?

**Comment by ramapcsx2** [comment]
Yep, the PCSX2 internal iso reader works fine with an image of this disc.

**Comment by ramapcsx2** [comment]
Hm, the battles not loading could be a core timing thing.
When I read data off a real disc, there's additional delays (just like on the real console).
Those could affect compatibility.
It'd be great to test this more reliably with the delays added to the internal reader.
Would adding forced spinwaits work?

**Comment by willkuer** [comment]
But if the internal loader works why should delay be a problem? Less delay than by using iso's barely should be possible..

**Comment by ramapcsx2** [comment]
I meant that the extra delays could have a positive effect. That's why I also want to try adding them to the internal loader.
In effect, this would produce more "sector not ready yet" situations when the core asks for new data.
The PSX is as sensitive to this as is the PS2, maybe even more so.
This would purely be for testing of course. It doesn't have to be fancy as it wouldn't stay for long.

**Comment by FlatOutPS2** [comment]
The latest master with the extra delay improves a random demo disc I tried. With the previous commit it only loaded an intro video when booting from the disc, now it loads the main menu just like the ISO.

**Comment by ramapcsx2** [comment]
Nice to know. The other PSX DMA channels require timing as well.

**Comment by turtleli** [comment]
So are there any disc read errors with this PR (from the actual disc reading itself, not those related to emulation issues)?

Oh, and if you see a ` * CDVD: SPTI short transfer of x bytes` message then I'd be interested in seeing the emulog too.

**Comment by ramapcsx2** [comment]
I didn't have time to test this in-depth. But from what I saw, it is an improvement for compatibility.
Performance might drop though? Not sure.

**Comment by turtleli** [comment]
@MrCK1 Retest IRHA Drag Racing?

**Comment by MrCK1** [comment]
@turtleli I'll test IHRA later tonight, I don't have my USB CD/DVD drive with me

**Comment by MrCK1** [comment]
So I've actually discovered another game that still has this issue. I didn't spot it before because the game used to crash until SPU2 was fixed.

The game is Rascal (absolutely horrible game :p)

I'll post the log when I get to my laptop later

**Comment by lightningterror** [comment]
https://github.com/PCSX2/pcsx2/projects/2
Can these Projects in progress be closed since the issues are resolved ?

**Comment by MrCK1** [comment]
@lightningterror PSX mode is moving at a slow progress. The projects allow us to keep track of what changes have been made in the past.

**Comment by lightningterror** [comment]
Ah okay , I thought In Progress topics are closed once they are resolved so nvm.

**Comment by FlatOutPS2** [comment]
> Ah okay , I thought In Progress topics are closed once they are resolved so nvm.

The topics could be moved to a "Finished" column. Keeping 'em in the "In Progress" section does indicate they're still in development.

**Pull request merged**
