### PR TITLE
GameDB: Add GS HW fixes for Wild Arms Alter Code F

### PR DESCRIPTION
**Pull request by RafaelTrepaUnCarballo**
### Description of Changes
It adds a gshack (wildArmsHack: 1) for all releases of Wild Arms Alter Code F (SCAJ-30002, SCPS-17002, SCPS-19251, SCPS-19253, SLUS-20937).

### Rationale behind Changes
The game needs this hack to prevent the appearance of buggy lines around text in resolutions above native.

Without hack, x2 res
gs_20220319165228_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937
With hack, x2 res
gs_20220319165247_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937

### Suggested Testing Steps
Rise the internal resolution and just go to the title screen to check if the text is rendered correctly.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
A few things.

Firstly, can you put a space after the # in your comments
Secondly please end your comment with a period
and lastly, please correct your commit name to match our format, for example "GameDB: Add GS HW fixes for Wild Arms Alter Code F"

Thanks  :)

**Comment by RedDevilus** [comment]
I wonder if round sprite also works. Wild Arms seems to enlarge Font and other 2D elements which in some cases are needed.

**Comment by RafaelTrepaUnCarballo** [comment]
> I wonder if round sprite also works. Wild Arms seems to enlarge Font and other 2D elements which in some cases are needed.

Round Sprite half/full fixes most of the issue, removing the lines around characters, but in some menus it creates a single line below the text (title menu, object sub-menu...), cuts 1px of some long characters like "y" (description popup) and moves the text 1px below compared to software/OpenGL/OpenGL+WildArms.

For example: Round Sprite: half (full is the same) creates an underline below "the memory card is not formatted":
gs_20220319203245_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937

Software:
gs_20220319204639_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937---SOFTWARE

OpenGLx2 hackless
gs_20220319204643_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937---OPENGLx2

OpenGLx2 Wild Arms hack: (slightly thicker, excluding that everything is OK)
gs_20220319204709_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937---OPENGLx2 WildArms hack

OpenGLx2  Round Sprite Half (practically perfect, except for moving the text 1px down)
gs_20220319204834_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937---OPENGLx2 Round Sprite Half

OpenGLx2 Round Sprite Full (the same as Half)
gs_20220319204903_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937---OPENGLx2 Round Sprite Full
-------------------
Software:
gs_20220319205331_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937---Software

OpenGLx2 Hackless:
gs_20220319205333_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937---OpenGLx2

OpenGLx2 Wild Arms hack: (thicker)
gs_20220319205404_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937---OpenGLx2 Wild Arms Hack

OpenGLx2 Round Sprite Half/Full (1px down, the "y" looks like a "v")
gs_20220319205524_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937--- OpenGLx2 Round Sprite Half
-----------------
Software:
gs_20220319204943_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937---Software

OpenGLx2 hackless:
gs_20220319205131_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937---OPENGLx2

OpenGLx2 Wild arms hack:
gs_20220319205203_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937---OPENGLx2 Wild Arms hack

OpenGLx2 Round Sprite Full
gs_20220319204952_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937---OPENGLx2 Round Sprite Full

...I think i've abused the github image hosting enough for today :)

**Comment by RafaelTrepaUnCarballo** [comment]
What's if that line below the "place" and memory text isn't a bug and it's supposed to be there?
It's there in Software and OpenGLx1.

gs_20220319212101_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937

**Comment by refractionpcsx2** [comment]
can you find PS2 footage to check, that would be the better way to test, because there is a few instances (Dark Cloud 2 is the best example) where our sprite alignment doesn't work quite right, even in software.

That doesn't however explain the cut off Y

**Comment by Tzerinas** [comment]
From an LP.

87-Update29_69

**Comment by RafaelTrepaUnCarballo** [comment]
> From an LP played on PS2.

So the inferior line is just a bug from the Software Render. I think there's no reason to activate Round Sprite instead of Wild Arms hack then.

**Comment by refractionpcsx2** [comment]
Damn, I didn't see your commits were all split out and named incorrectly >.<

In future PR's if you could squash down your work, especially if it's something small like this, and label them in our usual style like "GameDB: Added fixes for Wild Arms Alter Code F" or whatever, not the title.  I did mention this earlier.

**Pull request merged**
