### PR TITLE
GameDB: DaH1 & DaH2 bloom and lens flare

### PR DESCRIPTION
**Pull request by BreakPoints**
### Description of Changes

Fixes lens flare occlusion and improves bloom alignment when scaling.

### Rationale behind Changes

Fixes some graphics, the busted shadow mask unfortunately still makes these games ugly to play on GS-HW.

### Suggested Testing Steps

Check bloom and lens flares.

### CODE REVIEW

**Comment by Mrlinkwii** [comment]
GS dump please :slightly_smiling_face:

**Comment by BreakPoints** [comment]
> GS dump please 🙂 also what is DaH1 & DaH2?

No problem: [gs_20220724174056_Destroy All Humans_ 2_SLUS-21439.zip](https://github.com/PCSX2/pcsx2/files/9176192/gs_20220724174056_Destroy.All.Humans_.2_SLUS-21439.zip)

Sorry, Destroy all Humans! (1 + 2), I can amend the commit/pull request titles if needed.

**Comment by Mrlinkwii** [comment]
is their a gs dump for Destroy all Humans! 1 ?

**Comment by BreakPoints** [comment]
> is their a gs dump for Destroy all Humans! 1 ?
Didn't upload as the issues seem to be identical between 1 and 2, here's a dump of 1: [gs_20220724174908_Destroy All Humans__SLUS-20945.zip](https://github.com/PCSX2/pcsx2/files/9176215/gs_20220724174908_Destroy.All.Humans__SLUS-20945.zip)

**Comment by JordanTheToaster** [comment]
Personally from looking the only fixes I'd say are worthwhile right now is autoflush the others can be revisited once the game is working properly in hardware mode.

**Comment by BreakPoints** [comment]
> Personally from looking the only fixes I'd say are worthwhile right now is autoflush the others can be revisited once the game is working properly in hardware mode.

With these fixes I believe the only graphical issue is the shadow mask corruption. That corruption actually made the misalignment fixes easier as the bloom takes shadows into account so I was able to line up the bloom with the gaps in the corrupted shadow mask.

I doubt fixing the shadows will make any difference to the bloom alignment.

**Comment by refractionpcsx2** [comment]
I tried your settings, and tbh merge sprite did nothing, most of the other settings are kind of subjective, but tbh although it underblooms,I prefer just Autoflush and HPO: Norma(Vertex); It's not as bloomy but hardware mode isn't anyway, even in Native resolution.
There's likely other stuff going on and you're trying to compensate for which isn't right, which isn't really the idea for the upscaling hacks, so we should really employ the KISS methodology here (Keep It Simple, Stupid)

image

**Comment by BreakPoints** [comment]
I don't believe these change the intensity of the bloom, just better align it so less of the overall image is bright, just highlights where bloom should be. I wasn't able to see any differences with HPO: Norma(Vertex), only Special and above.

The issue is a lot easier to see in DaH2 and in daytime maps, here's an example of what each setting does. I would encourage opening all in tabs and flicking between them. The sky against the shadow texture is a good place to look.

All off:
All Off


Half Pixel Offset (bloom shifts a bit):
Half Pixel Offset


Half Pixel Offset + Round Sprite (bloom shifts more but seams can be seen in bloom texture, highlighted):
Half Pixel Offset + Round Sprite Edit


Half Pixel Offset + Round Sprite + Merge Sprite (Fixes seams)
Half Pixel Offset + Round Sprite + Merge Sprite


Similar fixes were accepted for R&C but I concede that these are more aggressive (Texture - Aggressive, in fact).

**Comment by BreakPoints** [comment]
Half Pixel Offset (Texture - Aggressive) + Wild Arms Hack does a better job and doesn't require Round Sprite + Merge Sprite:
gs_20220725022947_Destroy All Humans_ 2_SLUS-21439

**Comment by RedDevilus** [comment]
GameDB isn't used for making random hacks and see what fits, it can have other worse effects in other locations that you don't see at first.

The real fix is going to be in the fixing itself like the texture cache and other incorrectly emulation of post-processing.

**Comment by BreakPoints** [comment]
I understand, Round Sprite and Wild Arms Hack do have other noticeable changes and shouldn't be included. Half Pixel Offset and Auto Flush, however, operate off the same logic as other GameDB entries.

HPO in Ratchet and Clank 3 & 4 improve misaligned post processing where a real fix would be preferable. Auto Flush fixes occlusion issues with lens flares in GoW, as in these games.

**Comment by BreakPoints** [comment]
Any opinions on autoFlush: 1 + halfPixelOffset: 3?

@refractionpcsx2 If you'd prefer HPO:1, I'd argue we'd just remove that hack as well as I can't find any improvements or changes to it being set only to Vertex.

**Comment by refractionpcsx2** [comment]
Agressive didn't really look any better to me tbh, just even more too bright.

**Comment by BreakPoints** [comment]
Ah, if you're working off of my DaH1 dump it's not very obvious, mind trying this from the menu?
[gs_20220724174908_Destroy All Humans__SLUS-20945.zip](https://github.com/PCSX2/pcsx2/files/9193820/gs_20220724174908_Destroy.All.Humans__SLUS-20945.zip)

Off:
Off


Vertex:



Texture:



Texture Aggressive:

**Comment by refractionpcsx2** [comment]
what about using round sprite or something?

**Comment by BreakPoints** [comment]
An earlier version of this pull request also included round sprite full and merge sprites to fix an unwanted side effect of rounding but I was told this wasn't the place to experiment. You can see my screenshots of the results in DaH2 further up.

**Comment by refractionpcsx2** [comment]
full is nearly always destructive, I meant more "half"

**Comment by BreakPoints** [comment]
No change on half, I'm afraid, otherwise I'd probably have taken screenshots of that too.

**Comment by refractionpcsx2** [comment]
Bummer :(

**Comment by refractionpcsx2** [comment]
Just a passing comment.. Here's my pre-round sprite PR with Special(Texture) and nothing else

image

**Comment by BreakPoints** [comment]
I don't think that looks any better than master with Special(Texture) but it's difficult to tell

**Comment by refractionpcsx2** [comment]
It does, without preround its still a bit offset, which you can see at the top of the ufo

**Comment by BreakPoints** [comment]
You're right, it's much easier to spot on the spindle to the left of the UFO and after replicating your settings.

Screenshot 2022-07-27 005205

We can leave this PR until #6553 is merged and set HPO to Special(Texture). Doubt these games are being played on GS-HW as it stands

**Comment by refractionpcsx2** [comment]
Yeah sure, I dunno how long my pr is going to be, I need to sit down and work on it and make it suck less

**Comment by lightningterror** [comment]
Closing as the game has many issues, the hacks don't really fix anything, just hides issues or make them worse.

**Comment by BreakPoints** [comment]
I disagree that these make anything worse, sprite occlusion is broken without auto flush and misaligned post process effects are commonly fixed with HPO in other games with the same side effects.

I do agree that it's not important while the game suffers worse problems that make it barely playable in GS-HW.

**Pull request closed without merging**
