### PR TITLE
Emotion Wars Part 2: The Vector Unit Strikes Back

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Bunch of stuff to make the micro mode VU recs faster.

### Rationale behind Changes

Vroom vroom.

### Suggested Testing Steps

Find broken games. Probably a few.

### CODE REVIEW

**Review by lightningterror — COMMENTED** [review]
Some new microVU_IR.h warnings to clean up.
https://github.com/PCSX2/pcsx2/actions/runs/3718646908/jobs/6306985933#step:11:1082

**Comment by HelicopterP** [comment]
My findings do far:
MGS3 Subsistence - SPS and missing geometry during intro
DOA Hardcore - hang after selecting character

**Comment by stenzek** [comment]
Turns out I completely forgot to pipe CFC2/CTC2 through the register cache..

> MGS3 Subsistence - SPS and missing geometry during intro

Fixed

> DOA Hardcore - hang after selecting character

Couldn't test this, but it might be the same issue

**Comment by HelicopterP** [comment]
Indeed DOA2 is fine now.

**Comment by ehw** [comment]
I did some tests with this PR with the following games (all Redump verified). Tests were done with default/stock settings in a new folder, comparing this PR and the current latest main:

Arctic Thunder (USA)
Armored Core 2 - Another Age (USA)
Armored Core 2 (USA)
Bomberman Kart (Europe) (En,Fr,De)
Bomberman Kart DX (Japan)
Bouken Jidai Katsugeki - Goemon (Japan)
Bouncer, The (USA) (En,Ja)
Burnout 3 - Takedown (USA)
CART Fury - Championship Racing (USA)
Chulip (USA)
Cyber Troopers - Virtual-On Marz (USA)
Dark Cloud (USA)
Dark Cloud 2 (USA) (v2.00)
Ephemeral Fantasia (USA)
Extermination (USA)
Ferrari F355 Challenge (USA)
Gauntlet - Dark Legacy (USA)
Gran Turismo 3 - A-Spec (USA) (v1.10)
Gran Turismo 4 (USA) (v2.00)
Grandia II (USA)
Grandia III (USA) (Disc 1)
Grandia Xtreme (USA)
Jak 3 (USA) (En,Fr,De,Es,It,Pt,Ru)
Jak and Daxter - The Precursor Legacy (USA) (En,Fr,De,Es,It) (Rev 1)
Jak II (USA) (En,Ja,Fr,De,Es,It,Ko) (v2.01)
Jet X2O (USA)
Legaia 2 - Duel Saga (USA)
Mega Man X7 (USA)
Mega Man X8 (USA)
Mystical Ninja Goemon Zero (USA) (Beta)
Okage - Shadow King (USA)
OutRun 2006 - Coast 2 Coast (USA) (En,Fr,Es)
Ridge Racer V (USA)
Rogue Galaxy (USA)
S.L.A.I. - Steel Lancer Arena International (USA)
Sega Ages 2500 Series Vol. 8 - Virtua Racing - FlatOut (Japan)
Sega Ages 2500 Series Vol. 26 - Dynamite Deka (Japan)
Sega Ages 2500 Series Vol. 27 - Panzer Dragoon (Japan)
Sega Ages 2500 Series Vol. 31 - Dennou Senki - Virtual On (Japan)
Sega Bass Fishing Duel (USA)
Sega Rally 2006 (Japan)
Sega Rally Championship (Japan)
Shadow of Destiny (USA)
Shinobi (USA) (En,Ja)
Silent Hill 2 (USA) (En,Ja,Fr,De,Es,It) (v2.01)
Silent Hill 3 (USA) (En,Ja,Fr,De,Es,It,Ko)
Silent Hill 4 - The Room (USA) (En,Ja)
Soulcalibur III (USA)
Splashdown - Rides Gone Wild (USA)
Splashdown (USA) (v2.01)
Spy Fiction (USA)
Suikoden III (USA)
Vampire Night (USA)
Virtua Cop - Elite Edition (Europe)
Virtua Fighter - 10th Anniversary Edition (Europe) (En,Fr,De,Es,It)
Virtua Fighter 4 - Evolution (USA)
Wave Rally (USA)
WinBack - Covert Operations (USA) (En,Ja)
WinBack 2 - Project Poseidon (USA)
WipEout Fusion (USA)
WRC - World Rally Championship (USA)

Out of all the games, these have issues:

Silent Hill 2 - Extremely slow when starting a new game.
Gauntlet Dark Legacy - Extremely slow when starting a new game, missing graphics.

PRs are always fun with benchmarks. Here are some that I did by using savestates on static scenes:

sega rally championship 95
sega rally 2006
okage
megaman x8
megaman x7
legaia 2
jet x2o
jak 2
jak and daxter
jak 3
grandia xtreme
wrc
wipeout pure
winback 2
winback
wave rally
virtua fighter 4 evolution
virtua cop elite edition
vampire night
suikoden iii
splashdown - rides gone wild
soul calibur 3
silent hill 4
silent hill 3
shinobi
shadow of destiny


For the most part, a few games gained some additional frames here and there. Some don't seem to have any change at all. And there are a small amount that seems to have lost some frames. Shadow of Destiny seems to have taken the worst hit with the PR.

Hope this helps.

**Comment by RedDevilus** [comment]
A bit annoying that you didn't do consistency where PR is top or bottom alone for charts but thanks for testing nonetheless.

**Comment by RedDevilus** [comment]
What are your other specs? And perhaps better compared with Gsdumps as you aren't comparing the same situation anymore as one moment they can run good or bad for any PCSX2 version.

**Comment by refractionpcsx2** [comment]
> A bit annoying that you didn't do consistency where PR is top or bottom alone for charts but thanks for testing nonetheless.

That's just what CapFrameX does, it puts the faster one on top.

**Comment by ehw** [comment]
Here are my specs:
Processor:	AMD Ryzen 7 5800X 8-Core Processor
 Number of Cores:	16
 Speed:	4.7 GHz
 Stepping:	0
 Family:	19
 Model:	21
 CPU ID:	178BFBFF00A20F10

RAM	16 GB (G.SKILL Trident Z Royal RGB 3600MHz)

Video Card	NVIDIA GeForce RTX 3080
 Chipset	NVIDIA GeForce RTX 3080
 Manufacturer	Nvidia
 Hardware T&L	Yes
 Total Menmory	18 GB
 Dedicated Memory	10 GB
 Driver Version	31.0.15.2756
 Vertex Shader Version	5.1
 Pixel Shader Version	5.1
 Plug and Play ID	VEN_10DE&DEV_2206&SUBSYS_403D1458&REV_A1
 Device	2206
 Vendor ID	10DE
 Driver version 527.56

Motherboard: ASRock X570 Taichi (BIOS: P5.00)



Single frame Gsdumps for Silent Hill 2 and Gauntlet Dark Legacy in roughly the same area. One for this PR, the other for the main branch. Is this what you want? I never used savestates for these two games. I only used savestates for doing the benchmarks:
https://www.mediafire.com/file/0ssjc4sdzcdo5i2/gsdumps.zip/file

**Comment by refractionpcsx2** [comment]
Sorry I think Red was getting lost in his ideas, GS Dumps are useless for debugging non-GS issues.  Thanks anyways.

**Comment by stenzek** [comment]
Silent Hill 2 should be fine now.
Shadow of Destiny regression should also be fixed.

**Comment by ehw** [comment]
Thanks stenzek!

I can confirm Silent Hill 2 and the regression in Shadow of Destiny is fixed now. Thank you for taking a look at those.

Gauntlet Dark Legacy is still broken, no change.

Here's a quick benchmark with CapFrameX for Silent Hill 2 for those curious. This was taken with James overlooking Silent Hill 2 in the beginning of the game, after the letter from Mary:

image

**Comment by HelicopterP** [comment]
Gauntlet Dark Legacy is broken on master too.  Did it ever work correctly?

**Comment by refractionpcsx2** [comment]
have you tried the VU Sync or Full VU0 Sync gamefixes on Gauntlet to see if that fixes it?

image

**Comment by refractionpcsx2** [comment]
So I checked master, and that's fine, it's definitely just broken on this PR. Sten is aware.

**Comment by ehw** [comment]
Checked the latest commits, Gauntlet is fixed now. :)

Since the initial commit for this PR, Legaia 2 has gotten faster. This seems to be the one game I have that benefits the most from these changes. 

image

I have some other PS2 games I have to backup that I can use to test. When I have time and I'll do some more testing for any bugs or regressions.

**Comment by MrCK1** [comment]
Retested on latest commit [7d091e5](https://github.com/PCSX2/pcsx2/pull/7599/commits/7d091e553a60e408b469550ab4c9adf3aaa20724) , Cartoon Network Racing is broken with VU1 recompiler after loading a race -it will show a black screen. VU1 interpreter will restore the graphics to normal.

**Comment by ehw** [comment]
Just wanted to update. I did some more testing and didn't encounter any major issues with the following games.

Arctic Thunder (USA)
Armored Core 2 (USA)
Armored Core 2 - Another Age (USA)
Bomberman Jetters (Japan)
Bomberman Kart (Europe) (En,Fr,De)
Bomberman Kart DX (Japan)
Bouken Jidai Katsugeki - Goemon (Japan)
Bouncer, The (USA) (En,Ja)
Burnout 3 - Takedown (USA)
CART Fury - Championship Racing (USA)
Chulip (USA)
Crazy Taxi (USA) (Greatest Hits)
Cyber Troopers - Virtual-On Marz (USA)
DDRMAX2 - Dance Dance Revolution 7th MIX (Japan)
Dark Cloud (USA)
Dark Cloud 2 (USA) (v2.00)
Ephemeral Fantasia (USA)
Extermination (USA)
Ferrari F355 Challenge (USA)
Final Fantasy X (USA)
Final Fantasy X-2 (USA, Canada)
Final Fantasy XII (USA)
Gauntlet - Dark Legacy (USA)
Gran Turismo 3 - A-Spec (USA) (v1.10)
Gran Turismo 4 (USA) (v2.00)
Grandia II (USA)
Grandia III (USA) (Disc 1)
Grandia Xtreme (USA)
Jak 3 (USA) (En,Fr,De,Es,It,Pt,Ru)
Jak II (USA) (En,Ja,Fr,De,Es,It,Ko) (v2.01)
Jak and Daxter - The Precursor Legacy (USA) (En,Fr,De,Es,It) (Rev 1)
Jet X2O (USA)
Kingdom Hearts (USA)
Kingdom Hearts II (USA)
Legaia 2 - Duel Saga (USA)
Maximo - Ghosts to Glory (USA)
Mega Man Anniversary Collection (USA)
Mega Man X - Command Mission (USA)
Mega Man X Collection (USA)
Mega Man X7 (USA)
Mega Man X8 (USA)
Midway Arcade Treasures (USA)
Midway Arcade Treasures 2 (USA)
Midway Arcade Treasures 3 (USA)
NiGHTS into Dreams... (Japan)
Okage - Shadow King (USA)
OutRun 2006 - Coast 2 Coast (USA) (En,Fr,Es)
Ridge Racer V (USA)
Rogue Galaxy (USA)
S.L.A.I. - Steel Lancer Arena International (USA)
Sega Ages 2500 Series Vol. 19 - Fighting Vipers (Japan)
Sega Ages 2500 Series Vol. 26 - Dynamite Deka (Japan)
Sega Ages 2500 Series Vol. 27 - Panzer Dragoon (Japan)
Sega Ages 2500 Series Vol. 31 - Dennou Senki - Virtual On (Japan)
Sega Ages 2500 Series Vol. 8 - Virtua Racing - FlatOut (Japan)
Sega Bass Fishing Duel (USA)
Sega Rally 2006 (Japan)
Sega Rally Championship (Japan)
Shadow of Destiny (USA)
Shadow the Hedgehog (USA) (En,Ja,Fr,De,Es,It)
Shinobi (USA) (En,Ja)
Silent Hill 2 (USA) (En,Ja,Fr,De,Es,It) (v2.01)
Silent Hill 3 (USA) (En,Ja,Fr,De,Es,It,Ko)
Silent Hill 4 - The Room (USA) (En,Ja)
Sonic Gems Collection (Europe, Australia) (En,Fr,De,Es,It)
Sonic Heroes (USA) (En,Ja,Fr,De,Es,It)
Sonic Mega Collection Plus (USA)
Sonic Riders (USA) (En,Ja,Fr,De,Es,It)
Sonic Riders - Zero Gravity (USA) (En,Ja,Fr,De,Es,It)
Sonic Unleashed (USA) (En,Ja,Fr,De,Es,It)
Soulcalibur II (USA)
Soulcalibur III (USA)
Splashdown (USA) (v2.01)
Splashdown - Rides Gone Wild (USA)
Spy Fiction (USA)
Suikoden III (USA)
Super Monkey Ball Deluxe (USA)
Tekken 4 (USA)
Tekken 5 (USA)
Tim Burton's The Nightmare Before Christmas - Oogie's Revenge (USA)
Vampire Night (USA)
Virtua Cop - Elite Edition (Europe)
Virtua Fighter - 10th Anniversary Edition (Europe) (En,Fr,De,Es,It)
Virtua Fighter 4 - Evolution (USA)
WRC - World Rally Championship (USA)
Wave Rally (USA)
WinBack - Covert Operations (USA) (En,Ja)
WinBack 2 - Project Poseidon (USA)
WipEout Fusion (USA)
XGIII - Extreme G Racing (USA)
XGRA - Extreme G Racing Association (USA)

I haven't done anymore benchmarking though, I wasn't sure if you wanted benchmarks done at the moment in case you were still adding things to the PR. I did do some benchmarking with the commits from before, and I'm still seeing some games have slightly worse performance on average in comparison to the main branch even after multiple attempts - it seems consistent too. Let me know if you want me to look into it.

**Comment by refractionpcsx2** [comment]
Thank you for testing all those games. Can you give a list of some of the games you're seeing performance regressions on? if you can also check the OSD to see which components have the highest percentages, that would be great.

**Comment by ehw** [comment]
> Thank you for testing all those games. Can you give a list of some of the games you're seeing performance regressions on? if you can also check the OSD to see which components have the highest percentages, that would be great.

Sure, I can work on this sometime tomorrow. You mean PCSX2's OSD and not CapFrameX's (Riva Tuner), correct? I can take screenshots of the window with the OSD enabled for both main branch and pr too, if this helps.

**Comment by refractionpcsx2** [comment]
> > Thank you for testing all those games. Can you give a list of some of the games you're seeing performance regressions on? if you can also check the OSD to see which components have the highest percentages, that would be great.
> 
> Sure, I can work on this sometime tomorrow. You mean PCSX2's OSD and not CapFrameX's (Riva Tuner), correct? I can take screenshots of the window with the OSD enabled for both main branch and pr too, if this helps.
> 
> EDIT: (If its with PCSX2's OSD, is it with the framelimiter on or off?)

yes PCSX2's OSD with the frame limiter off

**Comment by ehw** [comment]
Okay, I tested a bunch of games and made notes of which ones seem to have definite framerate losses with this PR.

What I did was ran each game in master (v1.7.3807) and 9d317e2 in three passes each. This should help determine a median framerate for each build, and eliminate a possibility of a margin of error. I made savestates on relatively static scenes that push VU a little bit and started with a fresh PCSX2 folder for both versions, and did the following:

1.) Opened pcsx2
2.) Load game
3.) Load savestate
4.) Remove the limit on the framerate
5.) Use CapsFrameX for 30 seconds
6.) Once the jingle plays after the 30 second are up, I print screen'd the window with OSD enabled and saved it to a .png.
7.) Did this 3 times each in each version of PCSX2.

This is what I got:
**Lost frames:**
Bouken Jidai Katsugeki Goemon - Lost 6~8 FPS
CART Fury: Championship Racing - Lost 10~11 FPS
Chulip - Lost 12~14 FPS
Extreme-G Racing: XG3 - Lost 3-4 FPS (Not sure)
Ferrari F355 Challenge - Lost 9-12 FPS
Grandia II - Lost 23~26 FPS
The Bouncer - Lost 9~11 FPS
Virtua On Marz - Lost 16-17 FPS

**Gained frames:**
Arctic Thunder - Gained 135-137 FPS
Armored Core 2: Another Age - Gained 14-15 FPS
Armored Core - Gained 9 FPS
Bass Fishing Duel: Sega Sports - 14-15 FPS
Bomberman Kart DX - Gained 7-9 FPS
Grandia III - Gained 27-28 FPS
Legaia 2: Duel Saga - Gained 52-61 FPS

**No difference (loss or gain is too small to notice):**
Bomberman Jetters
Burnout 3
Crazy Taxi
Dark Cloud
Ephemeral Fantasia
Extermination
Extrem-G Racing XGRA
Final Fantasy X
Final Fantasy XII
Gauntlet Dark Legacy
Gran Turismo 3
Gran Turismo 4
Grandia Xtreme
Jak 3
Jak and Daxter
Shadow of Destiny

**Inconclusive (can't really say if it did anything or not)**
Bomberman Kart - Possibly lost at least 3 frames but unsure due to the nature of this game.
Dark Cloud
Final Fantasy X-2

I made too many images to post in this PR, so I compressed all the graphs and OSD images here:
https://www.mediafire.com/file/z2bp0jbngqgpkm0/pcsx2+pr7599+testing.zip/file

Hope this helps.

**Comment by stenzek** [comment]
I'm doubting FFX for sure. I was seeing +15% in VU bottlenecked areas.

**Comment by RedDevilus** [comment]
I guess I should test it myself to see what's up.

**Comment by stenzek** [comment]
Should also mention a possible explanation for small performance differences when **not** VU1 bottlenecked - because the VU thread is more efficient now, it's probably spending more time sleeping, which means the EE thread has to wait longer for it to wake up at times.

Easy way to confirm this is with MTVU off. If it's slower with MTVU off, then it's a regression. If not, then it's fine - we're only talking borderline margin of error differences here anyway.

**Review by JordanTheToaster — APPROVED** [review]

**Comment by ehw** [comment]
I think I understand now. I was only focused on raw frame output, not VU efficiency. I didn't think about scenarios where one thread might be bottlenecked over another. Sorry for wasting your time.

**Comment by stenzek** [comment]
It's still relevant, but taking a miniscule perf hit in non-VU bottlenecked scenarios is worthwhile for the improvement it brings to VU bottlenecked scenarios. In these cases, it's so small it's almost within margin of error.

**Review by Mrlinkwii — APPROVED** [review]

**Pull request merged**
