### PR TITLE
Gsdx texture format

### PR DESCRIPTION
**Pull request by gregory38**
The first 2 commits try to setup AEM properly with real texture cache support.

The last commit corrects potential texturing issue.

It requires both GL&DX tests. Typical games that really need to be tested.
* VP2 (forest?)
* FFX12
* Suikoden

### CODE REVIEW

**Comment by gregory38** [comment]
@turtleli 
IIRC, you noticed texturing issue in 32bits mode on suikoden. Could you test this branch?

**Comment by turtleli** [comment]
Initial tests seems good, 32-bit texture issue is fixed in OpenGL for Suikoden 4 and Suikoden Tactics.

**Comment by turtleli** [comment]
Windows build for other people to test: http://turtleli.unospace.net/GSdx32-texture-format-SSE2.7z

**Comment by gregory38** [comment]
Thanks :+1:

**Comment by gendouhydeist** [comment]
@gregory38 GSDump
On OGL lots of textures are missing, no cursor, no window border, and no button are being displayed when going to progressive mode.
https://drive.google.com/file/d/0B0xPvbkBqD9DbU56YW9acjJYSTg/view?usp=sharing

On DX11 cursors and window border are blinking to black then returns to normal every 3 seconds.
https://drive.google.com/file/d/0B0xPvbkBqD9DYlJDdHM0RTE0VzQ/view?usp=sharing

**Comment by tsunami2311** [comment]
Do i need to use latest git build for this too or will the plugin suffice?

**Comment by gregory38** [comment]
I rebased the branch to latest master to get the VP2 regression fix. Didn't have time to debug dump above.

**Comment by gendouhydeist** [comment]
can somebody recompile Gsdx plugin base on this branch thanks!

**Comment by tsunami2311** [comment]
VP2
http://www.filedropper.com/vp2forestdx11

http://www.filedropper.com/vp2forestopengl

http://www.filedropper.com/vp2regressionopengl

FF12
http://www.filedropper.com/ff12forcedtfdx11

http://www.filedropper.com/ff12forcedtfopenglregression

Regression in both dont happen in opengl of build 
"PCSX2 1.3.1-20150807020829 - compiled on Aug  7 2015"

I will check current gits and report back, as side not the Flicker black textures that happens in bios cube  with scaling happens in VP2  on menu the arror flickers

**Comment by tsunami2311** [comment]
regression in VP2/FF12 opengl is part of pcsx2-v1.3.1-956-gf9fe2ee build

**Comment by turtleli** [comment]
Windows build updated, use my previous link.

**Comment by gregory38** [comment]
Thanks you for the build. I hope Orphis will be free soon to update the bot.

**Comment by gendouhydeist** [comment]
DX11 texture flickers, borders, and cursor.
OGL a lot of textures missing, border and cursor are missing.

https://drive.google.com/file/d/0B0xPvbkBqD9DMlNUWUs0cTFTNXc/view?usp=sharing
https://drive.google.com/file/d/0B0xPvbkBqD9DeUdPemx6MHlJaDQ/view?usp=sharing

**Comment by refractionpcsx2** [comment]
The flickers are due to the Nvidia bug workaround on windows 10, for some reason it's sent it even crazier.  Currently we choose either flickering textures or bouncing screen.

**Comment by Kein** [comment]
Anyone has compiled plugin?

**Comment by ssakash** [comment]
turtleli had provided it in his second post at this issue.

**Comment by Kein** [comment]
Broke Star Ocean 3:
SW: http://i.imgur.com/8BAl4sM.png
OGL: http://i.imgur.com/2YmCbyq.png (scaling used)

Dump: http://www38.zippyshare.com/v/k9IUbpkF/file.html

**Comment by gregory38** [comment]
@gendouhydeist 
No need to generate a dump for each options/renderer of GSdx. They don't have any impact.

@gendouhydeist, @Kein 
Anyway, I didn't manage to reproduce the issue on my side. What is your driver Nvidia or AMD?
Any strange error message in the emulog?

**Comment by Kein** [comment]
@gregory38 
Log: http://www.everfall.com/paste/id.php?qh2nage04ine
OpenGl status: http://www.everfall.com/paste/id.php?fq65nl5gc33z
Driver: 353.38

**Comment by gendouhydeist** [comment]
Nothing unusual here.
Log: http://pastebin.com/yRnZFpr5
GPU: GeForce GTX 970/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver: NVIDIA 355.60

**Comment by gregory38** [comment]
Hum. I will split the PR into 2 small PR. The 2 first commits likely broke somethings in the texture cache. It could explain why I can't reproduce it in the texture cache. I need to review my code.

**Comment by gregory38** [comment]
Ok I redo the PR see #782. Could you test the new one. I hope it will work better.

**Comment by gregory38** [comment]
A small question, was the regression with or without 8 bits-texture enabled.

**Comment by gendouhydeist** [comment]
It was enabled, tried disabling the 8 bit texture works fine.

**Comment by gregory38** [comment]
I will provide the build later

**Comment by gregory38** [comment]
Build of the latest change:
http://bositman.pcsx2.net/gregory_pull_request/pcsx2-v1.3.1-1031-g6344b46-windows-x86.7z

Please test it. Thanks.

**Comment by gendouhydeist** [comment]
everything works fine on VP2, so now anisotropic filtering are now disabled when 8-bit textures enabled?

**Comment by gregory38** [comment]
Great. Aniso was never compatible with 8 bits tex

**Comment by gendouhydeist** [comment]
Which Suikoden 3 or 4? I'll test the remaining games once I get the game.

**Comment by gregory38** [comment]
Test both :+1:  Test others game too. Changes are quite big.

**Pull request merged**
