### PR TITLE
128MB Memory card support re-pull request [again].

### PR DESCRIPTION
**Pull request by XxDeathB3TCHxX**
I edited it (again) as the code for 128MB memory card was already there, I just added the option to create 128mb memory card & deleted the useless comment which seems to leave white blank spaces according to github. As I didn't know how to force push this commit neither did I know how to amend the last commit, I had to make another, it shouldn't add the changes from before.

### CODE REVIEW

**Comment by turtleli** [comment]
So are there any benefits or should this just be closed?

**Comment by ramapcsx2** [comment]
There were compatibility problems at sizes > 64MB, but I don't remember which exactly.
Since 64MB worked well with the problem games, we decided against the 128MB option.
Folder Memory Cards provide basically unlimited space :)

**Comment by XxDeathB3TCHxX** [comment]
I tried few games, Final Fantasy VII Dirge Of Cerberus, X-Men Legends, Jak-X, Jak 3, The Simpsons Hit & Run, Resident Evil 4, Resident Evil Code X Veronica, Van Helsing, they worked as expected, no issues, the only problem I faced is longer loading times when the games are accessing the memory cards (ofc since it's larger mem card), but all works as expected for these games. I think it needs more testing imo.

@willkuer could you clarify what did you mean by the top questions?

The 128MB memory card code was already there, it's just that it wasn't applied as an option when creating a memory card.

**Comment by willkuer** [comment]
The question was whether you ever experienced or could imagine a situation where neither a 64MB memory card nor a folder memory card could solve an issue that you could solve with a 128MB card.

**Comment by ramapcsx2** [comment]
Also try creating a battle record save with Star Ocean 3. That game had some particular checks in place.

**Comment by RedPanda4552** [comment]
Sample size matters here. Just because it works for your test pool does not mean it is safe for most others. And since folder memory cards already solved the memory card problem forever, there's no value to adding an option for capacity, since it will inevitably introduce problems that the existing, limitless system does not have.

**Comment by lightningterror** [comment]
So what are going to do with this ?

**Comment by bositman** [comment]
I see 0 benefits and some possible troubles, so I vote for closing.

**Comment by lightningterror** [comment]
Closing since most of us are against.

**Pull request closed without merging**
