### PR TITLE
Qt: Asynchronous loading of covers (and 6.3.1 update)

### LINKED ISSUE #6490: [BUG]: The game grid scrolling performance is heavily degraded by setting the covers
### Describe the Bug

The game grid scrolling performance is heavily degraded by setting the covers, especially when the grid is zoomed out to fit more items on every page

### Reproduction Steps

* Set the view to game grid
* Set covers for more than a page of homebrew/apps/games
* Zoom all the way out
* Scroll a page down
```
📦📦📦🗕🗖 ❎ 〰️ 🕛
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦💽💽💽💽📦 〰️ 🖲️
📦💽💽💽💽📦 〰️ ⬇
📦💽💽💽💽📦 〰️ ⬇
📦📦📦📦📦📦
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```
* The GUI thread freezes for a few seconds (2-10s) until a page of covers is loaded
```
📦📦📦🗕🗖 ❎ 〰️ 🕐
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦💽💽💽💽📦 〰️ 🖲️
📦💽💽💽💽📦
📦💽💽💽💽📦
📦📦📦📦📦📦
  ⌛ ⌛ ⌛ ⌛
  ⌛ ⌛ ⌛ ⌛
  ⌛ ⌛ ⌛ ⌛
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```
* The second page is loaded
```
📦📦📦🗕🗖 ❎ 〰️ 🕑
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦💽💽💽💽📦 〰️ 🖲️
📦💽💽💽💽📦
📦💽💽💽💽📦
📦📦📦📦📦📦
  💽💽💽💽
  💽💽💽💽
  💽💽💽💽
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```
* The second page is focused and the GUI is unblocked
```
  💽💽💽💽
  💽💽💽💽
  💽💽💽💽
📦📦📦🗕🗖 ❎ 〰️ 🕒
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦💽💽💽💽📦 〰️ 🖲️
📦💽💽💽💽📦
📦💽💽💽💽📦
📦📦📦📦📦📦
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```

### Expected Behavior

* Scroll a page down
```
📦📦📦🗕🗖 ❎ 〰️ 🕛
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦💽💽💽💽📦 〰️ 🖲️
📦💽💽💽💽📦 〰️ ⬇
📦💽💽💽💽📦 〰️ ⬇
📦📦📦📦📦📦
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```
* The grid should scroll to the next page immediately and display temporarily placeholders
```
  💽💽💽💽
  💽💽💽💽
  💽💽💽💽
📦📦📦🗕🗖 ❎ 〰️ 🕐
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦⌛ ⌛ ⌛ ⌛📦 〰️ 🖲️
📦⌛ ⌛ ⌛ ⌛📦
📦⌛ ⌛ ⌛ ⌛📦
📦📦📦📦📦📦
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```
*  The covers should be loaded in background from the disk
```
  💽💽💽💽
  💽💽💽💽
  💽💽💽💽
📦📦📦🗕🗖 ❎ 〰️ 🕑
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦💽💽💽💽📦 〰️ 🖲️
📦💽💽💽💽📦
📦💽💽💽💽📦
📦📦📦📦📦📦
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```

### PCSX2 Revision

PCSX2 Nightly - v1.7.2991

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Also updates all platforms to 6.3.1 for consistency.

### Rationale behind Changes

Fixes #6490.

### Suggested Testing Steps

Test scrolling with a larger number of covers, general UI functionality (due to version bump).

### CODE REVIEW

**Comment by Florin9doi** [comment]
I tested this change and it works nice except one issue. The cache size is updated by resizing the window, but isn't updated by zooming out, causing an infinite loading when the program is started having the zoom level at the middle and then zooming all the way out. Half a page is loaded, then everything is dropped and the other half is loaded, then everything is dropped again and so on.

**Comment by stenzek** [comment]
I can't reproduce what you're describing: start with zoom in middle, zoom out seems fine to me?

**Comment by Florin9doi** [comment]
Yes, that's how I reproduce it:

1. maximize the window and set the zoom level at middle
2. restart the program
3. zoom out

 
https://user-images.githubusercontent.com/2995486/180642597-b8ecf69d-dfc2-4c88-9208-b9259ccc811d.mp4

**Comment by stenzek** [comment]
I couldn't reproduce this specifically, but I did notice that it could issue redundant loads/invalidates after a scale change, so I added a counter to prevent that.

**Review by JordanTheToaster — APPROVED** [review]

**Review by Mrlinkwii — APPROVED** [review]

**Comment by refractionpcsx2** [comment]
Can confirm I was having the bug, but manifested in a way where nothing loaded if I put the zoom level all the way down. But Sten has now fixed it :)

**Comment by wefalltomorrow** [comment]
Thanks for fixing this :)

**Pull request merged**
