### PR TITLE
Update Copyright notices/disclaimers 2017

### PR DESCRIPTION
**Pull request by lightningterror**
Update all Copyright notices/disclaimers in scripts to 2017

It is a new year after all.

Thoughts ?

### CODE REVIEW

**Comment by MrCK1** [comment]
I think we generally only change the copyright if we modify the files. It helps us keep track

**Comment by FlatOutPS2** [comment]
What @MrCK1 said.

**Comment by avih** [comment]
There's no need to change the year every year for every file.

Also:

> Keep in mind that a copyright notice is not mandatory in the U.S. or Canada or in most countries. Its purpose is to educate others or to remind others that copyright exists in your work and to respect that copyright. Including a copyright notice on your website or blog may help diminish the myth that all online content is free.

From here http://www.copyrightlaws.com/copyright-basics/copyright-notice-year/ .

**Comment by gregory38** [comment]
Year ought to be aligned with the latest file modification (If I remember correctly gnu recommendation). It just too painful without a script to do it so nobody bother.

**Comment by gregory38** [comment]
@lightningterror is it ok to close your PR or you don't want to integrate some parts of it ?

**Comment by lightningterror** [comment]
If none of the disclaimers need to be updated sure.

If some can actually be updated then you can merge only those. It's up to you guys :)

I can revert the others that don't need to.

**Comment by FlatOutPS2** [comment]
Most of the affected files are from third party projects and should definitely not be modified. The other files should only be modified if they've already been updated in 2017 without modifying the copyright date. You would need to check per file.

Definitely remove the LilyPad files you added. Those were already scheduled to be updated by my LilyPad PR.

**Comment by ssakash** [comment]
I see that you have changed ``Gregory hainaut`` to ``Gregory Hainaut``, at least that part should be merged I guess. It's a shame that even Gregory doesn't get his name right :P

**Comment by lightningterror** [comment]
@ssakash hahah , ok is this better now? Rest of the changes have been reverted.

**Comment by gregory38** [comment]
What would be nice is a PERL/Python script that
* take a file as input
* get the last commit date from a git command
* get copyright information from the header
* then add/update copyright info based on the previous data

**Comment by FlatOutPS2** [comment]
Most of the core files are copyright `PCSX2 Dev Team`. Why are the copyrights for GSdx `Gregory` and `Gabest` only?

**Comment by gregory38** [comment]
Initially all plugins came from different repository with different licences. Plugins that weren't rewritten by `PCSX2 Dev Team` got different licence. You could remove me, and put `PCSX2 Dev Team` instead but Gabest and others must remain.

**Comment by lightningterror** [comment]
So which ones need updating ?

**Comment by MrCK1** [comment]
Just replace the 4 instances of ```Gregory Hainaut``` with ```PCSX2 Dev Team```

**Comment by lightningterror** [comment]
Okay , this can be merged now.

**Comment by ssakash** [comment]
@gregory38 

Next time, please do a squash merge. Don't really love the pollution in Git history.

history

**Comment by gregory38** [comment]
... ooups, I though about it but info didn't reach my finger ...

**Comment by lightningterror** [comment]
I'm not sure how to do that yet xD , gotta learn first xD

**Comment by FlatOutPS2** [comment]
Good thing this didn't happen to https://github.com/PCSX2/pcsx2/pull/1758 (yet). :p

**Comment by gregory38** [comment]
I'm waiting to break the 100 commits wall ;)

**Pull request merged**
