### PR TITLE
Qt: Icon Refresh

### PR DESCRIPTION
**Pull request by kamfretoz**
### Description of Changes

This PR brings in some changes to some of the icons such as the BIOS icon, memory card icon and the DJ Turntable icon and more.

Credit to: MBee/Maxihplay

Preview:
Screenshot_20240117_115619

image

### Rationale behind Changes

Eyecandy++

### Suggested Testing Steps

Make sure the icons shows up properly.

### CODE REVIEW

**Comment by kamfretoz** [comment]
Also redesigned the analog OSD icons, if you have any feedbacks please let me know!

image

**Comment by kamfretoz** [comment]
New iteration of the analog icon:

Screenshot_20240119_102416

**Comment by kamfretoz** [comment]
The PR is pretty much complete now and are ready for testing.

Here are some preview for the final changes:

- New and Tweaked PCSX2 icon (you can go to the commits detail for comparison:
PCSX2_Final_512px


- Added Pencil icon to the Edit Cheats/Patches
image

- Tweaked the BIOS, Memory Card, Advanced and Debug icons.
Screenshot_20240121_173717

- New icons for Pop'n Music and DJ Turntable Controller.
Screenshot_20240121_173904

- And lastly a small adjustment to the trash icon.
Screenshot_20240121_174049

**Comment by RedDevilus** [comment]
Pop n Music with less detail? And some others are kinda minor so not really against it though.

**Comment by kamfretoz** [comment]
> Pop n Music with less detail? And some others are kinda minor so not really against it though.

Compared from the original, it only removes the small and barely visible Start and Select button on the top left.
Here's from master:
image

**Comment by Sythenz** [comment]
Only just personal preference - but considering font-weight distribution, thinner icons would be a little better?

**Comment by kamfretoz** [comment]
Which icon are you referring to?

**Pull request merged**
