### PR TITLE
Ee recompiler stack alignment

### PR DESCRIPTION
**Pull request by gregory38**
Need careful test on both Windows and Linux.

### CODE REVIEW

**Comment by gregory38** [comment]
@refractionpcsx2 @sudonim1, your feedback are welcome.

**Comment by refractionpcsx2** [comment]
As long as windows is stable (I can't foresee there being a problem, but no harm in checking right? :P ) Looks fine to me, potential of 1-2 instructions saved per block, can't argue with that, every little helps.

**Comment by gregory38** [comment]
Actually I'm more afraid of the third commit and potentially it can be done better. By the way, it will fix the issue #506 
By the way, I started to write a mini doc of the EE rec internal for the future.

**Comment by refractionpcsx2** [comment]
hmm, do jumps actually provide a return address? obviously call does as it's basically call subroutine, but i thought jumps just went to that location and you were on your own from there, that could be an issue if i'm right, but if i'm not then you should be fine :P

We can test it anyway, see if it crashes

**Comment by refractionpcsx2** [comment]
I just ran this through a few games and it didn't crash, so that's good right? :)

**Comment by gregory38** [comment]
Jump was enough because those 2 functions never return. They jump directly to ExitRecompiledCode

**Comment by gregory38** [comment]
By the way, do you keep the frame pointer (EBP) on Windows build? If I remove it on linux, I get a crash. Dunno, if I can do it now.

**Comment by sudonim1** [comment]
Jumping into any C++ function seems like a very bad idea in retrospect but I don't think this really fixes things because now the inline asm function tail jumps out after a call (without a LEAVE on windows), again messing with the stack pointer.  The tail should probably be moved into the recompiler output after the CALL instruction or the entire function should be replaced with a dynamically generated function ala JITCompile.

**Comment by micove** [comment]
@gregory38 
Currenly,Debug & Devel keep the pointer while Release omits the pointer. 

https://msdn.microsoft.com/en-us/library/2kxx5t2c.aspx

**Comment by refractionpcsx2** [comment]
> Currenly,Debug & Devel keep the pointer while Release omits the pointer.
> 
> https://msdn.microsoft.com/en-us/library/2kxx5t2c.aspx

Not sure that would be relevant as it is compiler code, so the recompiler would still do it, the C compiler wouldn't optimise that out.

**Comment by gregory38** [comment]
@micove thanks for the info. It would require more test but it seems to work now without the frame pointer.

@refractionpcsx2 I think it is relevant because C functions are called from the REC.

**Comment by gregory38** [comment]
Good news. If I remove the frame pointer in master tree, I get a crash at boot. The game is booting with the fix.

**Comment by gregory38** [comment]
Let's dream about a small perf increase in linux.
@refractionpcsx2 I redid the third commit based on pseudo feedback. Feel free to give it a shot.

**Comment by refractionpcsx2** [comment]
I'll give it a shot, I'll have to redownload the branch, modifying PR's like that really confuses TortoiseGit, it thinks it's up to date :P

**Comment by refractionpcsx2** [comment]
Ok just gave it another go, worked absolutely fine :)

**Comment by gregory38** [comment]
```
I'll give it a shot, I'll have to redownload the branch, modifying PR's like that really confuses TortoiseGit, it thinks it's up to date :P
```
Oh. The alternative is to recreate a new branch so you still need to dl it.

```
Ok just gave it another go, worked absolutely fine :)
```
Good news :) Another five year old bug fixed

**Comment by gregory38** [comment]
Ok I merged the code. If there any issue, complain will come soon enough :p

**Comment by refractionpcsx2** [comment]
OMG IT'S ALL BROKEN, THIS TOTALLY RUINED IT!!


just kidding, good job :P

**Comment by gregory38** [comment]
lol

1.4 will be a very nice linux release (except various remaining issues :p )

**Pull request merged**
