### PR TITLE
Readme: Update and Remove Redundant Info

### PR DESCRIPTION
**Pull request by MrCK1**
### Description of Changes
This PR updates the frontpage readme to be more concise. Much of the old information has been moved over to the new documentation site and no longer needs to be duplicated.

### Rationale behind Changes
Cleanliness, remove duplicate data

Preview of changes:
image

### CODE REVIEW

**Comment by RedDevilus** [comment]
I wouldn't say that the minimum and recommended stuff is in an obsolete location.

**Comment by lightningterror** [comment]
Imo readme was fine as it was.

**Comment by stenzek** [comment]
Gonna go against the trend and say that the docs site is probably a better location, so long as it's clearly linked.

Nobody reads long readmes anyway, and it's not like this is the only source of information for the project.

**Comment by refractionpcsx2** [comment]
I don't agree with removing the explanations of virtual machines, recompilers etc, they are quite relevant to the project overall.  I don't really mind the rest of the info getting removed from there.

**Comment by MrCK1** [comment]
Added the section back to include information about recompilers, etc.. Should be all set to go.

**Review by Mrlinkwii — APPROVED** [review]

**Review by kamfretoz — APPROVED** [review]

**Pull request merged**
