### PR TITLE
GameDB: Hardware Fixes for Burnout 2

### PR DESCRIPTION
**Pull request by ElTioRata**
**Rationale behind Changes**

Fixes sun appearing in front of everything and bloom effect.

Software
software

Hardware (master)
hardware

Hardware (with fixes)
hwfix

[GS dump](https://drive.google.com/file/d/1QerfzHMnAuc3b5rKdWGFIOiZO7wq_pRf/view?usp=sharing)

Btw this is my first contribution and I barely use GitHub so if something is off, y'all tell me.

### CODE REVIEW

**Comment by F0bes** [comment]
There has been an issue in your changes and you're changing ~58 thousands lines of the gamedb.
I recommend 
- Reverting your changes
- Making your changes again (making sure you don't format the gamedb)
- Amend your commit with your new version
- Force push

**Comment by Mrlinkwii** [comment]
@ElTioRata  if you have a discord account , if you want i can help you  if you join the pcsx2 server :)

**Comment by refractionpcsx2** [comment]
every 
autoFlush: 1 # Fixes bloom and sun rendering in front of everything.
line has 2 whitespaces on the end, need to remove those

**Comment by DonelBueno** [comment]
Anyway to fix the bloom when upscaling?

**Comment by refractionpcsx2** [comment]
> 

half pixel offset Special (texture) looks the least gross, but it's not lined up well

**Comment by ElTioRata** [comment]
HPO set to 'Normal (Vertex)' and Round Sprite set to 'Full' aligns it better than HPO set to 'Special Texture' but I found it somehow looking worse for some reason.

**Comment by refractionpcsx2** [comment]
yeah that's why I preferred special texture, the bloom looks broken in HPO Normal

**Comment by JordanTheToaster** [comment]
HPO Special autoflush on sprites only and GPU CLUT look probably the best you will get.

image

**Comment by DonelBueno** [comment]
I also suggest adding "Force Nearest" on "Bilinear Dirty Upscale" to get rid of color banding on sun glare:

PCSX2_2023_08_12_18_02_24_971



PCSX2_2023_08_12_18_02_17_334

**Comment by refractionpcsx2** [comment]
Yep, I agree

**Comment by Parallax71** [comment]
fantastico arreglo, muchas gracias. Una pregunta, en Manhunt pasa algo similar, ¿el arreglo sería viable?

**Comment by ElTioRata** [comment]
> fantastico arreglo, muchas gracias. Una pregunta, en Manhunt pasa algo similar, ¿el arreglo sería viable?

#6553 si el problema es el que se muestra en el PR, vas a tener que esperar a que esté terminado

**Pull request merged**
