### PR TITLE
Qt: Icon Revamps

### PR DESCRIPTION
**Pull request by kamfretoz**
### Description of Changes

This PR aims to revamp, redefine and overhaul the icons that were used for the Qt UI.

~~At the moment, it's incomplete and I'm planning to adjust more of the icons in the future, so I'll be putting this PR in draft for now.~~
Should be ready now.

All feedback are appreciated! :D

Here is some comparison:
Screenshot_20230610_200056

Screenshot_20230610_200137

Screenshot_20230610_200501

Screenshot_20230610_200355

### Rationale behind Changes

Some of the icons don't fit well and didn't exactly convey the proper meaning of each settings menu.
Feel free to suggest any changes you feel necessary to the icons! 

### Suggested Testing Steps

See if the icon shows up properly and are looking great!

### CODE REVIEW

**Comment by Owelm** [comment]
Great work !

Could you tell me the size of the icon in pixel please?

**Comment by kamfretoz** [comment]
Ready for review and testing!

**Comment by refractionpcsx2** [comment]
I thought you were going to do the savestate icons as well, we did discuss it, what happened to those? 

Also were you going to address the memcard icon inside the "Create" screen? I know you said it was broken, and I can see you've removed the previous icon that was *supposed* to be there.

**Comment by kamfretoz** [comment]
> I thought you were going to do the savestate icons as well, we did discuss it, what happened to those?

I kinda backpedalled on the plan because some people say the icon don't need changing, but i can work on it if we'll keep on going with the plan

> Also were you going to address the memcard icon inside the "Create" screen? I know you said it was broken, and I can see you've removed the previous icon that was _supposed_ to be there.

Initially my plan was only to replace the memory card icon on the "Create" screen with the newly one i made, but i notice that the icon itself doesn't show up at all, even on master, and it has been broken for a while now

I tried diving into the code itself to see what's wrong but i couldn't figure it out. 

Also if you're referring to the removed icon, i did clean up a lot of unused icons including the old memcard icon, were you referring to that one?

**Review by Mrlinkwii — APPROVED** [review]

**Review by stenzek — APPROVED** [review]
Code changes seem fine

**Pull request merged**
