### PR TITLE
SPU2-X: Reverb rewrite

### PR DESCRIPTION
**Pull request by sudonim1**
This is based on http://problemkaputt.de/psx-spx.htm and http://drhell.web.fc2.com/ps1/ by Martin Korth and "Dr. Hell" respectively, who mostly agree on the reverb engine's inner workings.  The whole thing, especially the old implementation, is too tangled for me to say how it differs, I just rewrote it to the new spec.

This is definitely still not correct, and testing makes me suspect the cross-channel reflection ("DIFF") code.  Actual test programs need to be written, which is very unpleasant because all the SPU code has to be done on the IOP and just designing good investigatory tests for this is difficult.  Nonetheless, the improvement is marked.

I split the work into a functional commit and a register renaming commit for ease of review while rebasing.

### CODE REVIEW

**Comment by FlatOutPS2** [comment]
inux builds will also fail on this PR due to clang-format issue.

**Comment by sudonim1** [comment]
I used the clang format plugin.  What do you want from me, blood?

**Comment by sudonim1** [comment]
Actually the FIR might be there, it turns out the implementation I ripped out has a signedness error, doing an unsigned division on samples with predictably awful results.  I'm getting close results now I'm experimenting with it, but I haven't found a FIR length that's right yet (if one exists).

**Comment by sudonim1** [comment]
Correction: I have no idea any more.  I had a version which came very close to PS2 output but I lost it and don't know what I did any more.

**Comment by ramapcsx2** [comment]
This is still a tremendous improvement. Any title making good use of reverb will sound better now, but it especially benefits PSX :)

**Comment by sudonim1** [comment]
Since opening this I think I've worked out that all the significant difference from the old code is the two all pass filters.  I have no idea how a fast digital all pass filter is meant to work so both versions are greek to me though.  The remaining issues are probably either in a missing input filter or in the uh whatever you call the simple filter used for same/diff.

**Comment by ramapcsx2** [comment]
It would be best if we do another round of hardware reverb samples. This time with different waveforms.
I imagine a square wave of left channel only, right channel only and both channels.

**Comment by sudonim1** [comment]
I'm personally inclined to merge it soon if there are no objections since I don't know when I'm going to get around to figuring out the remaining differences from real hardware.

**Comment by ramapcsx2** [comment]
No objections. Go ahead please :)

**Comment by sudonim1** [comment]
Okay I guess nothing's broken or got noticeably worse.

**Pull request merged**
