### PR TITLE
CDVD: fix sceCdReadConsoleID on bios v1.70 and up

### PR DESCRIPTION
**Pull request by AKuHAK**

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Are you sure? My 1.7 bios works fine?

image

**Comment by bigol83** [comment]
My 2.20 Bios works god too 

PS2 BIOS (Europe)_20060210-142424_20240328135951

**Comment by refractionpcsx2** [comment]
Is that on master @bigol83 or this PR?

**Comment by kamfretoz** [comment]
So does mine (v2.20)

**Comment by bigol83** [comment]
> Is that on master @bigol83 or this PR?

That is on Master

**Comment by AKuHAK** [comment]
@refractionpcsx2 PS2 OSD doesn't use `sceCdReadConsoleID` anywhere, it is rare system call. If you use real console dump you can check what does show PS2Ident in Serial section and if it is match serial on the sticker.

**Comment by refractionpcsx2** [comment]
Then what does the BIOS use?

**Comment by AKuHAK** [comment]
sceCdReadConsoleID returns 8 bytes very similar to ilink.ID. Bytes from 5 to 7 contains console serial number, there is also some interesting information inside, but it is easiest check.

**Comment by AKuHAK** [comment]
> Then what does the BIOS use?

sceCdReadModelName

**Comment by refractionpcsx2** [comment]
I can't tell what PCSX2 says cos PS2Ident doesn't work on it. I tried the new version and the one previous to your fork.

**Comment by AKuHAK** [comment]
> I can't tell what PCSX2 says cos PS2Ident doesn't work on it. I tried the new version and the one previous to your fork.

https://github.com/AKuHAK/PS2Ident/actions/runs/8466667797
there is PCSX2 build in actions

**Comment by refractionpcsx2** [comment]
Alright, I checked it, this is from Master PCSX2
image

PR:
image

PS2 the BIOS came from for prosperity (Can't check the serial on the case because I replaced the lid, no idea where the original is)
Screenshot 2024-03-28 13-36-59

**Comment by refractionpcsx2** [comment]
Thanks for that

**Comment by kamfretoz** [comment]
Master PCSX2:
Screenshot_20240328_212733

PR:
Screenshot_20240328_213100

Console:
IMG_20240128_124035_Anu_4

Physical Serial:

IMG_20240328_205130_KFZ_1

**Pull request merged**
