### PR TITLE
Prevent console from snapping to main window.

### PR DESCRIPTION
**Pull request by ThomasConnor**

### CODE REVIEW

**Comment by bositman** [comment]
...any reason?

**Comment by ThomasConnor** [comment]
Any time I move the pcsx2 app window the console snaps to the right hand side, when i changed the AutoDock value in the PCSX2_ui.ini file it started remembering its position and it seems like a much smarter behaviour to me. With the default behavior the console can jump out of the desktop on startup like - http://i.imgur.com/679gAjt.png (you can just see the console frame on the far right) and I would have to move it to my prefered position every time i started the program. When i changed the AutoDock value it now behaves how I would expect it to and can be resized and moved and it will remember those values on next startup - http://i.imgur.com/6ZlwD5W.png and won't jump to the app window when thats moved I can't think of a good reason to have the console snap enabled and there are a few to disable it. It'd still be configurable so changing the default value seems like the best thing to me.

**Comment by ssakash** [comment]
Looks Good to me :+1:

**Comment by refractionpcsx2** [comment]
It would be better to add it as an option to the console window or something, some people (like me) prefer the console to follow the main window.

**Comment by ThomasConnor** [comment]
k, I'll try write up a patch to add it as an option in the "Log" menu of the console window. Sidenote: Should the name of the "Log" menu be changed to File or Menu or Options? The name of the menu isn't very related to the options it has.

**Comment by refractionpcsx2** [comment]
Probably should be renamed options yes

**Comment by ramapcsx2** [comment]
@ThomasConnor Do you still want to do this?

**Comment by ThomasConnor** [comment]
@ramapcsx2 yeah i still intend to do this. Had the menu entry and most of the command it should do done but I've updated my pc and need to reinstall visual studio. Is there a gui builder addon you use or does it have to be done manually? You can go ahead and close this request though and I'll submit another one when I have something working.

**Comment by refractionpcsx2** [comment]
It  has to be done manually im afraid.

**Comment by ramapcsx2** [comment]
Right, it's all manual.
You can keep this PR open and merge in your new work or close it yourself and open a new one later. Your choice :)

**Comment by gregory38** [comment]
I'm closing the PR to keep the list of open topic reasonable. Reopen it when you're ready or open a new one.

**Pull request closed without merging**
