### PR TITLE
Documentation: Update README.md to reflect project's age.

### PR DESCRIPTION
**Pull request by TheTechnician27**
### Description of Changes
Updated 'more than ten years old' to 'more than twenty years old'. Groundbreaking stuff. Eat your heart out, @stenzek.

### Rationale behind Changes
The project is more than twenty years old now.

### Suggested Testing Steps
Make sure the word 'twenty' is spelled correctly and that the project is, indeed, more than twenty years old.

### CODE REVIEW

**Comment by F0bes** [comment]
Please follow the proper commit naming scheme.
Example:
Documentation: xyz
Or
Readme: xyz

**Comment by TheTechnician27** [comment]
@F0bes Done!

**Comment by F0bes** [comment]
> @F0bes Done!

Sorry, I was more concerned with the actual commit name, as this will be permanent history in our repo.
image

**Comment by TheTechnician27** [comment]
> > @F0bes Done!
> 
> Sorry, I was more concerned with the actual commit name, as this will be permanent history in our repo. image

Got it. How would I change the commit name? Or do I need to resubmit my PR?

**Comment by F0bes** [comment]
I'm unsure if you can do it through GitHubs website. I think it'd be best for you to clone to repository, checkout this pr, change the commit name and amend to the current commit. Or redo your pr, whatever is easier for you.

**Comment by arcum42** [comment]
My own personal thought would be that maybe it could be reworded not to have a definite number, so that this commit doesn't end up having to be redone in another ten years or so. "has been running for many years" or some such?

**Comment by Stefano-VLN** [comment]
What about "since 2002"?

**Comment by refractionpcsx2** [comment]
saying "Since 200x" would be better, but I don't know what that X is.  The first release was in 2002, but I don't know if the project started in 2002 or 2001. 

Maybe @bositman could chime in, since he was there from the start.

**Comment by mirh** [comment]
https://web.archive.org/web/20020414112336/http://www.pcsx.net/cgi/robboard.cgi?action=display&num=594
https://web.archive.org/web/20130128095233/http://pcsx2.net/download/finish/15-pcsx2-v0-026/21-pcsx2-v0-026-binary.html
It was released quite unceremoniously without much back info. The oldest file is dated early March. 

https://web.archive.org/web/20021026124630/http://www.cenetworks.com/html/interviews/pcsx2_interview/
The official founding stone is presumably "whenever university students in greece starts to prepare for their exams".

**Comment by refractionpcsx2** [comment]
I know the first release was in 2002, I wanna know when it started, he doesn't say what year he was doing exams, it could have been 2 years previous, or the previous year, or the current year, I don't know..

**Comment by mirh** [comment]
The [purported](http://www.hardwaretidende.dk/hard/artikel/02/03/21/8875950) first ps2 demo is dated 2001, and it seems hard for a [tutorial](https://web.archive.org/web/20020628234641/http://ps2dev.livemedia.com.au/kb/kb.asp?T=720) released in early march to have "helped a lot" something in development for more than a few months. 

With this said much (much) later interviews set the date at "early 2001". 
https://forums.pcsx2.net/Thread-blog-The-History-of-PCSX2?page=7#pid406094
https://web.archive.org/web/20120920083045/http://pcsx2.net/234-interview-at-goodgame-hr.html
But it seems quite a stretch and their vague retelling doesn't really inspire confidence tbh

**Pull request merged**
