### PR TITLE
Translating more Strings to Catalan:

### PR DESCRIPTION
**Pull request by Dokman**
* Sorry for my lack of time in this year

### CODE REVIEW

**Comment by Dokman** [comment]
Not merge after i can give to you a little more of job please

**Comment by gregory38** [comment]
Do you plan to translate more? I regenerated the POT file to update it.

Could you rebase it (do  a backup before)? Unfortunately I'm afraid it will generate lots of conflicts. If it is too difficult for you, just post your current po somewhere, I will handle the merge.

**Comment by Dokman** [comment]
i can do it ^^ it's work but yes... it can be posible ^^ so tomorrow i will start to rebase it

**Comment by gregory38** [comment]
Did you finish to translate it? You either need to drop the initial commit or squash all of them.

**Comment by Dokman** [comment]
I will squash it into one commit and oush it this weekend

**Comment by gregory38** [comment]
What is the status ?

**Comment by Dokman** [comment]
Sorry if i can push it this week i will push it, i have to do a lot of work sorry man :S i am busy with my grade of programmer T.T

**Comment by gregory38** [comment]
Please post somewhere your latest po file so I can integrate it.

**Comment by trader5896** [comment]
@Dokman, when you are going to release the files? :DD

**Comment by gregory38** [comment]
ping

**Comment by Dokman** [comment]
@gregory38  @ghost Sorry for this inactive days, i had depression when i can i will push it

**Comment by Dokman** [comment]
@gregory38 today i will open a new pull request i close this one with my newest source

**Pull request closed without merging**
