### PR TITLE
GS: Use 16bit RGBA float for HDR copies - WIP

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### SUPERSEEDED BY #7161

~~Pending #7131 being merged before this becomes viable.~~

### Description of Changes
Use 16bit floats for HDR copies, instead of 32bit.

### Rationale behind Changes
16bit floats are faster to copy on the GS and it *might* be precise enough for us to get away with it, but this is a test to find out if it does cause any problems. This does bring a 40% performance boost in Sly 2 when GPU limited, maybe more, I became CPU limited :(

### Suggested Testing Steps
Try games, make sure colours aren't funky compared to master, note any performance increases.

### CODE REVIEW

**Comment by Dreadmoth** [comment]
Sly 2 shadows suffer from "strings" in some scenes - most visible when jumping, or when shadows are at steep angles:

Master:
Master
PR:
PR

[GS Dump](https://github.com/PCSX2/pcsx2/files/9726992/Sly_2_shadows_PR7132.zip)

> This does bring a 40% performance boost in Sly 2 when GPU limited, maybe more

More confirmed >💯%  :

Master:
Sly2Master

PR:
Sly2PR

i7-4770, 1070 Ti, default settings except 3x Native

**Comment by refractionpcsx2** [comment]
As said in the second line of the OP, this isn't ready, it's waiting on something else before this will function correctly.

But thanks for testing.

**Comment by refractionpcsx2** [comment]
Okay other PR was merged, this is now read for testing :) @Dreadmoth now you can go nuts 😄

**Comment by refractionpcsx2** [comment]
Results are going to depend on hardware. For example on my 5900x and 2080Ti, Sly 2 shows no performance increase at x3, but double in x8.

x3 build 3376
image

x3 PR
image

x8 build 3376 
image

x8 PR
image

**Comment by refractionpcsx2** [comment]
Full spectrum Warrior

3x build 3376
image

3x PR (120fps boost)
image

**Pull request closed without merging**
