### PR TITLE
GameDB: VU rounding fixes for Guitar Hero series and Hitman Contracts.

### PR DESCRIPTION
**Pull request by MrCK1**
Guitar Hero series: Fix cut-off numbers and restore missing whitespace in combo meter

Hitman Contracts: Fix missing light shafts under lamps

### CODE REVIEW

**Comment by atomic83GitHub** [comment]
The original Guitar Hero also need VU rounding to positive as you can see.

With Chop/zero:
capture

With positive:
capture2

**Comment by MrCK1** [comment]
@atomic83GitHub What region are you using?

**Comment by atomic83GitHub** [comment]
The region is Pal-M5

**Comment by MrCK1** [comment]
Just making sure, is it `SLES-54093`?

**Comment by atomic83GitHub** [comment]
No, it's SLES-54132

**Comment by FlatOutPS2** [comment]
If someone can confirm this is also needed for a PAL version of GH2/GHEncore and NTSC version of GH, then it should be safe to include it for all regions instead of just the one.

**Comment by MrCK1** [comment]
I don't own the PAL version, but it's highly likely to be needed in all regions :P

**Comment by ssakash** [comment]
So let's merge it (or) wait for confirmation on the PAL version?

**Comment by FlatOutPS2** [comment]
Wait for confirmation. Like @MrCK1 said it's most likely to be required for all regions.

**Comment by FlatOutPS2** [comment]
@MrCK1 Did you check if someone reported this issue for other regions on the forum or wiki (or maybe even youtube video)? Then we could add the other regions with a mention of which region was confirmed.

**Comment by MrCK1** [comment]
I just checked the compatibility list. The European versions will need the hack as well - I'm looking for other regions as we speak ;)

**Comment by MrCK1** [comment]
I added the additional regions for the various Guitar Hero games. Hitman Contracts is untouched as there aren't any reliable videos on YouTube.

**Pull request merged**
