### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by xTVaser**

### CODE REVIEW

**Comment by xTVaser** [comment]
Regarding not running a bunch of builds everytime this happens, I weighed out the options that are available to do so, and I decided to just make these commits not run CI at all.
- One option is to use a `concurrency` group https://docs.github.com/en/actions/using-jobs/using-concurrency
  - This would allow you to only have 1 set of jobs per group, and it would auto-cancel other ones in progress.  The issue with this approach is there isn't an easy way to make it branch specific.  We don't really want a bunch of concurrency limits happening on everything _except_ this PR
- So instead, you can modify the commit message to include an identifier to skip the workflows:
  - https://developer.crowdin.com/configuration-file/#configuration-file-for-vcs-integrations
  - https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
  - https://sourcegraph.com/search?q=context%3Aglobal+commit_message%3A+%22%5Bci+skip%5D%22&patternType=standard&sm=1&groupBy=repo

This feels fine as these PRs should only ever be updating the `.ts` files, and it's reasonably trust-worthy that they are in a valid format as they are being machine generated.

**Comment by Felipefpl** [comment]
Recent updates were added on crowdin, wouldn't be a better idea to wait till ppl had time to update their translations? I'm a translator myself and i finished my work but there are several ppl there still updating the translations. I hope we'll have at least 7 days to update the translations before 2.0.0 is released. :+1:

**Comment by RedDevilus** [comment]
Next release is still going to take quite awhile, translators have waited years at this point.

Though having waited this long has streamlined the process and most stuff are translatable from English tooltips and others.

I wouldnt worry about it. In the past translations were done the most in feature freeze which is not the period we are in yet.

**Comment by stenzek** [comment]
> Recent updates were added on crowdin, wouldn't be a better idea to wait till ppl had time to update their translations?

We need to get the translation sources into the tree so that they can be hooked up to Qt, tested, and any fonts for ImGui rendering set (still need to figure that out for Linux..)

**Comment by stenzek** [comment]
> Regarding not running a bunch of builds everytime this happens, I weighed out the options that are available to do so, and I decided to just make these commits not run CI at all.

Part of the issue here is the fact that the CI runs for every commit pushed to every branch. This is also an issue with master builds - it duplicates and runs both a PR-style workflow, as well as the release workflow.

I'd propose skipping such builds if the repository is `pcsx2`. If I remember correctly, part of the reason for having them run on commit push was so that the CI could run on forks, so this wouldn't break that functionality.

(also, an aside, we'd want to squash all these when merging.)

**Review by Mrlinkwii — APPROVED** [review]

**Comment by xTVaser** [comment]
> Part of the issue here is the fact that the CI runs for every commit pushed to every branch. This is also an issue with master builds - it duplicates and runs both a PR-style workflow, as well as the release workflow.
I'd propose skipping such builds if the repository is pcsx2. If I remember correctly, part of the reason for having them run on commit push was so that the CI could run on forks, so this wouldn't break that functionality.

I'm aware of this issue, it's not so CI could run on forks, it's because some people **wanted builds pushed to pcsx2 branches** to run on CI without having to make a PR.  An easily solution is to whitelist a pattern instead of just allowing **all** branches to build, but I have no idea what the current opinions are for this.

But yeah even if that was fixed it would atleast eliminate half the builds, but each commit's PR run would still trigger.  It's unfortunate that Crowdin does a single commit per file.

**Comment by refractionpcsx2** [comment]
> I'm aware of this issue, it's not so CI could run on forks, it's because some people **wanted builds pushed to pcsx2 branches** to run on CI without having to make a PR. An easily solution is to whitelist a pattern instead of just allowing **all** branches to build, but I have no idea what the current opinions are for this.
> 

This has already been resolved :) Sten made it so it skips the branch builds, if the branch is the main repo, so forks still run

**Comment by xTVaser** [comment]
ah I see, if people are happy with that it's a very good change especially with how long the builds are.

**Comment by refractionpcsx2** [comment]
It's been something that's annoyed me for a long time,  since I do all my PR's on the main repo :D

**Pull request merged**
