### PR TITLE
Updated the italian translation and gameindex titles

### PR DESCRIPTION
**Pull request by Leucos8**

### CODE REVIEW

**Comment by gregory38** [comment]
@avih 
Doe the update of gameindex.dbf have any impact on your new flow?

**Comment by avih** [comment]
Not sure what you're asking, but if you ask if names fixes affect the db update somehow, then they don't.

However, there has been some discussion at the forum not very long ago about naming conventions: http://forums.pcsx2.net/Thread-GameIndex-dbf-naming-consistency

I think it would be best if people first agree on the conventions, and then we can follow a single convention. I personally don't really mind what the convention is, as long as there is one and people mostly agree on it.

**Comment by Leucos8** [comment]
Yeah, those are pretty useless changes in gameindex.dbf. Maybe I've hit the commit button too fast, sorry for the bother. I'm following the naming conventions on Gamefaqs, it seems they don't like " - " and instead use ": ".
No problem if you don't want to merge these changes.

**Comment by gregory38** [comment]
I merged first commit.

**Pull request closed without merging**
