### PR TITLE
psxmode: SPU2-X backwards compatibility with the original SPU

### PR DESCRIPTION
**Pull request by ramapcsx2**
psxmode: SPU2-X backwards compatibility

### CODE REVIEW

**Comment by FlatOutPS2** [comment]
Is the sound mostly correct now?

**Comment by ramapcsx2** [comment]
Not sure about correct but it's working. There'll be details like pitch mod nuances and the whole core still runs at 48khz but overall, it's good :)

**Comment by ramapcsx2** [comment]
Oh yea, and reverb is dangerous. Due to the nature of the beast, it can go off in some situations. I've tested a few games and it's fine in those. But don't be surprised if it runs into a feedback loop (loud!).
Getting reverb right is very hard.

**Comment by MrCK1** [comment]
I can hear the new reverb during the PSX intro, but there's no music on the title screen for C12:Final Resistance

**Comment by FlatOutPS2** [comment]
Just tried it with Driver and it sounds really good. During gameplay all sounds and music seem to work. FMV's don't have any sound yet though.

**Comment by ramapcsx2** [comment]
No CD music yet. It will require CDVD plugin support.

**Comment by FlatOutPS2** [comment]
From what I recall, in Driver the FMV sounds aren't CD tracks.

I also noticed a few notes in the music on some levels in Driver are wrong. One of the notes was just an empty beep.

**Comment by ramapcsx2** [comment]
Okay, I'll check Driver out.
I've also noticed some garbage data (bleeps, adpcm error logs in console) randomly in Chrono Cross.

**Comment by FlatOutPS2** [comment]
Driver isn't very crashy. I've only had crashes when trying to restart a level. Otherwise I haven't had any crashes.

**Comment by ramapcsx2** [comment]
Okay, I have Driver in mind. There's still lots to do anyway. This pr is to get things going :)

**Comment by sudonim1** [comment]
Don't ever expect full compat with psx games, this is basically an experiment and it will be a miracle if most playstation games end up being only moderately buggy, let alone pcsx2 becoming a playstation emulator replacement.

**Pull request merged**
