### PR TITLE
Windows: Potential fix for XAudio2.7 unload crashes

### PR DESCRIPTION
**Pull request by turtleli**
Changes:
 - GSPanel now uses the CS_OWNDC style - it's apparently required for OpenGL. Might fix some OpenGL pause and resume/renderer switching crashes.
 -  An extra LoadLibrary call for XAudio2_7.dll is used in the SPU2-X XAudio2 backend - Might fix the XAudio2 crashes. See http://blogs.msdn.com/b/chuckw/archive/2015/10/09/known-issues-xaudio-2-7.aspx

Needs testing since I don't experience the above crashes on my system, though neither change should make things worse. Build at https://ci.appveyor.com/project/turtleli/pcsx2/build/1.50-test-build/artifacts

### CODE REVIEW

**Comment by turtleli** [comment]
GSPanel CS_OWNDC commit removed - unlikely it'll fix anything (but if anyone wants to test, use the link in the initial post).

**Comment by avih** [comment]
So basically the patch says "if there's an XAudio2_7.dll (or a debug one) available, keep a reference to it to avoid potential crash on exit".

Questions:
- Why didn't you follow the MSDN example more closely? (the win version ifdev, the load flags on system32, etc).
- Did you check that debug builds indeed load the debug DLL? (not that it matters much though, as the important case is release builds).

**Comment by turtleli** [comment]
Potentially it deals with the 10-15 minute XAudio2 related crashes (but I honestly don't know if it does since I've had no feedback).

> Why didn't you follow the MSDN example more closely? (the win version ifdef, the load flags on system32, etc).

The system32 load flag isn't supported on Windows XP, so I decided not to use the flag since I don't know what would happen and I don't have an XP VM. If I include the ifdef defines, it still won't compile against newer XAudio2 libraries since there are other things which are XAudio2 2.7 specific. I think it would be nicer if all the ifdef work to support newer Xaudio2 versions was done as one commit.

> Did you check that debug builds indeed load the debug DLL? (not that it matters much though, as the important case is release builds).

Yes

**Comment by ramapcsx2** [comment]
Hm, I've got an unrelated question regarding WinXP. When building with VS2015, the SPU2-X (and only it) don't load in XP anymore. VS2013 builds worked fine. Is that related to the new XA2 version by chance? Any idea how to restore XP compatibility?

**Comment by turtleli** [comment]
I don't think it is - it should still be using 2.7 since we're using the DXSDK headers.

I'll PR a branch that makes the LoadLibrary error codes more useful instead of 0 - maybe it'll offer clues as to why it's not loading.

**Comment by ramapcsx2** [comment]
Great, that should help.

**Pull request merged**
