### PR TITLE
GameDB: additions & fixes

### PR DESCRIPTION
**Pull request by rufotheone-fr**
### Description of Changes
A bunch of additions & fixes XD

### Rationale behind Changes
Because we want it to be the best DB!

### Suggested Testing Steps
...

### CODE REVIEW

**Comment by rufotheone-fr** [comment]
BTW @refractionpcsx2 I've got a question about DB: a game like "Fantastic 4" on PS2 has a localized title on cover ("Les 4 Fantastiques" in french) but the title screen stays in english => what should we pick for the DB: the title screen or the localized cover?

**Comment by noigeaR** [comment]
If you change the game names to only the localized titles, wouldn't that mean we would have to change all Japanese titles to their localized name too to be consistent?
ワンダと巨像 instead of Shadow of the Colossus. Because the game is only called ワンダと巨像 both on the title screen and the box cover.

**Comment by Mrlinkwii** [comment]
> If you change the game names to only the localized titles, wouldn't that mean we would have to change all Japanese titles to their localized name too to be consistent? ワンダと巨像 instead of Shadow of the Colossus. Because the game is only called ワンダと巨像 both on the title screen and the box cover.

@noigeaR 
No , i think due to the fact we cant guarantee the user has the necessary  fonts/symbols installed    for  ワンダと巨像  thus its out  of the question , what should be going into the Gamedb is either the direct translation of the or the name using latin aplhabet  ,  not ワンダと巨像 , i think red made an issue over this #4771 ,

**Comment by rufotheone-fr** [comment]
@noigeaR I don't see why we can't use the romanized speeling (Wanda to Kyozou in the case of SotC). But that's the point of my question: the accuracy of the GameDB

**Comment by tellowkrinkle** [comment]
> No , i think due to the fact we cant guarantee the user has the necessary fonts/symbols installed for ワンダと巨像 thus its out of the question , what should be going into the Gamedb is either the direct translation of the or the name using latin alphabet , not ワンダと巨像 , i think red made an issue over this #4771

No system in 2022 is missing a Japanese font.  Doubly so if the user owns a Japanese copy of the game.

**Comment by refractionpcsx2** [comment]
The problem is, idiots like me don't speak japanese, so when somebody says "oh ワンダと巨像 is broken" I don't have a freaking clue what I'm looking for, or what the game is called.  Romaji at least gives me a fighting chance.

**Comment by rufotheone-fr** [comment]
> BTW @refractionpcsx2 I've got a question about DB: a game like "Fantastic 4" on PS2 has a localized title on cover ("Les 4 Fantastiques" in french) but the title screen stays in english => what should we pick for the DB: the title screen or the localized cover?

^^^^^^^
The original question ^^;

**Comment by refractionpcsx2** [comment]
oh, you can pick the french version, sure. I have no issue with that, as long as it's Romanised

**Comment by rufotheone-fr** [comment]
> oh, you can pick the french version, sure. I have no issue with that, as long as it's Romanised

Re Katuru Fuantasutiku ! 🤣

**Comment by noigeaR** [comment]
I'm all for romanized Japanese titles, but this PR changes titles like "Godfather, The (Le Parrain)" to only the localized title "Perrain, Le", so to be consistent, the Asian releases would have to be changed to use only their localized titles too.

Using only localized titles looks good for end users and makes it easy for them to find their games in the game list on PCSX2, but it makes it more difficult to apply fixes to all regional variants of a game in the GameDB. My personal favorite would be to use the localized name with English title added in parenthesis.
Wanda to Kyozou (Shadow of the Colossus)
This means the game shows up under the name expected by a native speaker, but still can easily be found in the GameDB when searching for Colossus.
That's only my personal opinion though and I support whatever decision the PCSX2 team makes.

**Comment by rufotheone-fr** [comment]
That's why I asked.
But, there's already a bunch of localized titles in the DB (like "007 - Nagusame no Houshuu" for Quantum of Solace).
I mean : if a PCSX2 user got an iso, he should know what it is (if he dumped it or any "other" way) so a fully localized title in DB shouldn't be a problem

**Comment by refractionpcsx2** [comment]
I think the titles should be localised but in roman characters, so yes it should be called Wanda to Kyozou.  As long as the Wiki has all the different region names, then I'm happy for the gamedb to have the localised name.  There's no reason we should translate them all to english (except ease of maintainers finding them)

**Comment by noigeaR** [comment]
> I think the titles should be localised but in roman characters, so yes it should be called Wanda to Kyozou.

It is "Wanda to Kyozou (Shadow of the Colossus)" in the GameDB right now. I'll remove the part in brackets in my next GameDB PR then.

**Comment by refractionpcsx2** [comment]
cool, I'm fine with that

**Comment by Mrlinkwii** [comment]
@rufotheone-fr  can you squash and  rebase  the commits ?

**Comment by rufotheone-fr** [comment]
> @rufotheone-fr can you squash and rebase the commits ?

I'll be glad to... but how can I do that with Github Desktop?

**Comment by Mrlinkwii** [comment]
> > @rufotheone-fr can you squash and rebase the commits ?
> 
> I'll be glad to... but how can I do that with Github Desktop?

can you join the discord ( see readme for link  ) and ill help you their just not to pollute  the PR :)

**Comment by rufotheone-fr** [comment]
Okay, I'll join ASAP

**Comment by rufotheone-fr** [comment]
PR kinda messy, I'm closing this one and open a clean one

**Comment by refractionpcsx2** [comment]
Messy how? Link was going to talk you through sorting it out..

**Comment by rufotheone-fr** [comment]
I'm VERY sorry for this...
Until now I used to edit the files directly through github.com but for this repo I thought it would be nice to switch to Github Desktop but... as you can see with the different commits, I've completely messed my master branch T_T
Link helped me on discord but we didn't managed to sort this...

Sorry refraction, it won't happen again.

**Comment by refractionpcsx2** [comment]
It's alright, but I recommend learning how to use Git, it's quite advantageous to know how to get yourself out of a bind like this, it's pretty powerful (but can be confusing).

**Pull request closed without merging**
