### PR TITLE
USB: Don't crash and burn if there is no ini file for pcsx2.

### PR DESCRIPTION
**Pull request by arcum42**
### Description of Changes
Prevents DeviceProxy from going backwards from the beginning of an iterator.

### Rationale behind Changes
If there is no ini file, such as on first bootup, Ports[i].DeviceType is initialized to -1, which will cause the emulator to crash when it reaches this point.

### Suggested Testing Steps
Check to make sure this doesn't cause any issues with usb.

### CODE REVIEW

**Comment by stenzek** [comment]
Can you change the call site instead? <https://github.com/PCSX2/pcsx2/blob/master/pcsx2/USB/USB.cpp#L77>

```
const DeviceProxy* proxy = (portcfg.DeviceType != DEVTYPE_NONE) ? RegisterDevice::instance().Device(portcfg.DeviceType) : nullptr;
```

and

<https://github.com/PCSX2/pcsx2/blob/master/pcsx2/USB/USB.cpp#L564>
```
const DeviceProxy* proxy = (device != DEVTYPE_NONE) ? rd.Device(device) : nullptr;
```

**Comment by arcum42** [comment]
@stenzek
Just added in those changes.

**Review by stenzek — APPROVED** [review]

**Review by lightningterror — COMMENTED** [review]
Commits should be properly named with prefixes.

**Comment by refractionpcsx2** [comment]
It's fine, I'll just squash it

**Comment by arcum42** [comment]
@lightningterror @refractionpcsx2 
Did an interactive rebase blaming it on USB.

**Comment by refractionpcsx2** [comment]
Darn it, now I have to wait for the poor CI again :joy:

**Comment by arcum42** [comment]
Well, that's what a silly policy like having to have prefixes on every commit leads to...

**Pull request merged**
