### PR TITLE
Update GSCrc.cpp

### PR DESCRIPTION
**Pull request by netoale**
added french version of Simpsons The Game 0x5C1EBF61

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Can somebody confirm the EU version isn't just a typo? Those CRC's are hugely close.

**Comment by netoale** [comment]
Hi! it seems that crc 0x5C1EBD61 is for the german version (see the last post of [this page about graphic bug in "simpsons game"](http://forums.pcsx2.net/archive/index.php/thread-3034-9.html)

I have French version of this game, and I copy/paste 0x5C1EBF61 this value form the pcsx2 console when i start the game.

Both German and French vertion seems to have very close CRC .
Thanx

**Comment by refractionpcsx2** [comment]
That is an obscure coincidence! The likelyhood of this happening is very very small, but stranger things have happened, alright, I'll merge this then :)

**Comment by willkuer** [comment]
I think it is that small that it is considered to be impossible. Would be interesting to redo the probability calculation. This is probably similar to a birthday attack - which is possible but with this amount of games...

**Comment by mirh** [comment]
My (i dunno which version) SLES-51897-P# has 0x73E68475 CRC. 
If it can help, software version is reported to be 1.01 (rather than 1.00 as I usually see). 

EDIT: And.. wtf? It doesn't seem to be listed.

**Comment by refractionpcsx2** [comment]
lol yeh i nearly made that mistake :P

**Pull request merged**
