### PR TITLE
Add version number setting, run first time wizard if number doesn't m…

### PR DESCRIPTION
**Pull request by Kingcom**
…atch. To wipe settings for a new release.

### CODE REVIEW

**Comment by willkuer** [comment]
Why?

Core hardly changes and even if it happens mostly somewhere deep and not close to the settings. The latest relevant change (ee overclock) was implemented to be backwards compatible.

I would rather be annoyed to see the wizard again and again.

But you probably had some issues with the current implementation?

**Comment by Kingcom** [comment]
It came out of a discussion in IRC. For some reasons the settings need to be reset, possibly because of incompatibilities with the previous release version.

**Comment by willkuer** [comment]
So i am against that commit from a user's perspective.

Just citing the soirce here:
> // Wizard completed successfully, so let's not torture the user with this crap again!

**Comment by gregory38** [comment]
@willkuer there are issues. Not everythings is backward compatible.

**Comment by ramapcsx2** [comment]
When going to 1.4.0 on a machine with 1.2.1 installed, 1.4.0 will just default to using the My Documents pcsx2_ui.ini which has all the plugin paths set to the 1.2.1 installation. Also all the inis will have legacy values, some of which should most definitely be changed when using 1.4.0.
This attempt is only to fix the plugin paths but the issue is very complex, once you start moving between versions / back and forth.
Ideally PCSX2 should never use any system / core configuration files from other versions.

**Comment by willkuer** [comment]
It's ok for me if there are real issues. I just have the feeling that for plugins this would be a more reasonable step. I never had issues with core updates...

**Comment by ramapcsx2** [comment]
This is already included. Wonder why it doesn't see a merge conflict..

**Comment by ssakash** [comment]
@ramapcsx2 

Because you haven't included the commit in master branch.

**Comment by ramapcsx2** [comment]
Yep, totally missed that. Thanks :)
This is correct though, as we're redoing configs later.

**Pull request closed without merging**
