### PR TITLE
gsdx tc: allow a hit on older depth buffer

### LINKED ISSUE #1757: Full Spectrum Warrior - GSdx HW vertical lines regression
***PCSX2 version:***
v1.5.0-dev-1779-g83b5bdb

***PCSX2 options:***
Default + VU1 set to SuperVU

***Plugins used:***
Default

***Description of the issue:***
Vertical lines flicker onscreen.

***How to reproduce the issue:***
Use Hardware renderer and load a mission.

***Last known version to work:***
Regression caused by:
https://github.com/PCSX2/pcsx2/pull/1185

GS Dump: 
[Full Spectrum Warrior - vertical lines regression.zip](https://github.com/PCSX2/pcsx2/files/696708/Full.Spectrum.Warrior.-.vertical.lines.regression.zip)

### PR DESCRIPTION
**Pull request by gregory38**
Avoid an issue when rendering take some shortcut (Full Spectrum Warrior)

Close #1757

### CODE REVIEW

**Comment by FlatOutPS2** [comment]
The main issue is gone, but I noticed there's still a flash of vertical lines before a cutscene.

**Comment by gregory38** [comment]
Hum, could you try to do the same pattern on the FIXME line (check the diff you will understand)

**Comment by FlatOutPS2** [comment]
> Hum, could you try to do the same pattern on the FIXME line (check the diff you will understand)

I was already building it. :)

**Comment by gregory38** [comment]
I propose that we test a couple of game to avoid extra regression. I will edit the commit message to remove the close. Then we merge it.

Is the flash really annoying?

**Comment by FlatOutPS2** [comment]
> Is the flash really annoying?

Yes, but I'm not sure how often it occurs. I'll need to get a bit further in the game to figure that out. I'll try to trap it in a GS dump if it returns regularly.

**Comment by FlatOutPS2** [comment]
It seems to happen before almost all cutscenes. I think I captured a decent example in this GS Dump:

http://forums.pcsx2.net/attachment.php?aid=61832

**Comment by gregory38** [comment]
So adding the extra condition give `0x7FFF mask + 16 bit depth` give better result. But the rendering is still wrong, you just see it less. The texture channel effect is now trigger but input texture is garbage. Due to the depth miss. So instead, I will just skip the draw call. Rendering will still be bad but you might not see it.

**Comment by FlatOutPS2** [comment]
It seems to work, I haven't see the garbage lines anymore. 👍 

I'll go check a few more cutscenes and do some regression checking.

**Comment by gregory38** [comment]
Ok. I will merge it to improve the test coverage. I really hope it won't create any regression.

**Comment by ssakash** [comment]
>  I really hope it won't create any regression.

Sorry for the bad news but it seems to cause regression in Jackie Chan Adventures. ( Refer https://github.com/PCSX2/pcsx2/issues/1838)

**Pull request merged**
