### PR TITLE
Gsdx cleanup and fixes

### PR DESCRIPTION
**Pull request by turtleli**
1st commit removes some old code that isn't used anymore. Tested on Windows VS2013 and Linux. I've also modified the VS2012 project files but haven't tested that, though it should work.

2nd commit makes a few wording corrections to the Linux configure dialog.

### CODE REVIEW

**Comment by ssakash** [comment]
not sure if serious, you have removed a lot of useful functions. you have also removed the PSX GSdx plugin settings GUI format and it will break stuffs on there. :disappointed:

**Comment by turtleli** [comment]
No I haven't. The currently used dialogs are the IDD_CONFIG (the first time bug thing) and the IDD_CONFIG2 dialog. The functions I've removed are available in an updated form in the GS* files.

**Comment by ssakash** [comment]
IIRC, IDD_GPUCONFIG is still used for the PSX emulators. also, you removed the copyright license, why ?

**Comment by turtleli** [comment]
What PSX emulators work with GSdx? I found http://ngemu.com/threads/gsdx-plugin-vsync-fixed-for-psx-emulators.169945/ which suggests that it doesn't work well on PSX emulators.

The copyright is deleted because the file is deleted.

**Comment by refractionpcsx2** [comment]
As far as i was aware it works with pretty much any plugin based PSX emulator, so I wouldn't really remove all the GPU files and references to them.

**Comment by ssakash** [comment]
yes, I would still suggest not to remove the format for the PSX emulators. though this certainly needs a review from @gregory38

**Comment by turtleli** [comment]
Perhaps it should be split off into another plugin then? I'll try looking for some PSX emulators (the ones with source available) and look at the call paths.

**Comment by refractionpcsx2** [comment]
That's a plausable Idea, splitting gsdx in to 2 plugins.

**Comment by turtleli** [comment]
ePSXe - runs, but doesn't remember settings.
PCSXR - 500-600 ish frames per second on my PC, doesn't remember settings.

So it's somewhat broken on PSX emulators

**Comment by refractionpcsx2** [comment]
Ok the remembering the settings is broken, but aside from that, it works

**Comment by ssakash** [comment]
that's strange, I though that the whole GUI for the plugin settings depended on that resource file.

**Comment by turtleli** [comment]
The IDD_GPUCONFIG PSX1 dialog is accessed through GPUconfigure. PCSX2 accesses dialogs via GSconfigure and has no way to access the PSX1 dialog (unless you play with the debugger).

image

Dialog looks like this.

**Comment by turtleli** [comment]
Oh, seems the settings can be remembered, not all of them work (resolution doesn't but windowed does) but it needs the inis folder to exist first.

**Comment by gregory38** [comment]
The only issue of this code is the incompatibility with valgrind.

Otherwise it is fine (on windows). Maybe just move the code into a separate dir.

**Comment by turtleli** [comment]
The PSX code relies on the DirectX 9 and 11 Software Renderer code and whatever that depends on (though it could possibly be made to work with more if someone was to fix up the code). So splitting the PSX code would mean some code being duplicated.

So would people prefer leaving the code alone or splitting it off?

I'll pull the 1st commit off so the wording fixes that can be committed after a bit more discussion.

**Comment by refractionpcsx2** [comment]
If you can split it and make both work, that would be great, but it isn't a huge problem as it is, the PSX stuff is quite adequately segregated

**Comment by turtleli** [comment]
I've taken the commit off so the linux wording corrections can be committed

I think when I find time I'll look at the code and see what the best approach is. If the codes are quite different, I'll split it up. If not, I'll leave it alone or just tidy things up.

**Pull request merged**
