### PR TITLE
Fixed broken link; Add wiki link; Formatting

### PR DESCRIPTION
**Pull request by katamaritaco**
Added the wiki link and better description.
Fix broken link of 'todo'.
Formatted 'Coding Style' to 'Code Formatting Guidelines' for consistency.
Added the Commenting Etiquette link as well.

### CODE REVIEW

**Comment by katamaritaco** [comment]
I saw https://github.com/PCSX2/pcsx2/pull/889 after I made the initial PR. I took the suggested changes from there, as the issue was a few months stale. I think this should serve as a nice baseline for the future, but of course it would be nice if it was fleshed out a bit more - particularly with an up-to-date task list, and consolidation of the two that exist on github's wiki pages (but that is a different task).

**Comment by gregory38** [comment]
```
 particularly with an up-to-date task list, and consolidation of the two that exist on github's wiki pages 
```
Hell, no. Don't consolidate them. One is general todo list. The others one is mine (but anyone is free to pick up my idea). However they need some udpate :(

**Comment by katamaritaco** [comment]
I didn't consolidate for that reason, I know the differences between the files. 

In the future, for simplicity and ease of on-boarding for newcomers, there really should only be one todo list. Maybe a section at the end of the generalized todo list with "ideas for graphics improvements suggested by gregory38. be cautious" or something? 

Is there any other source that exists that is more current for todo tasks? It'd be great to have one central place where tasks are always up-to-date. If not, is this PR ready to be integrated?

**Comment by gregory38** [comment]
Just to reformulate my GSdx todo list is MY dashboard. Most of it are random ideas. It isn't a good start because half are likely bad idea that will fill the garbadge.

**Pull request merged**
