### PR TITLE
Atomic relax

### PR DESCRIPTION
**Pull request by gregory38**
Related to issue #1437 and #998 

Relax atomic operation to avoid memory barrier.

Edit: require MTGS / MTVU and GSdx-SW heavy test.
Edit2: require VU cycle stealing test too.

### CODE REVIEW

**Comment by gregory38** [comment]
If it works well, I will remove the deprecated old atomic.

**Comment by gregory38** [comment]
@FlatOutPS2 could you do some test of this branch. Thanks you.

**Comment by FlatOutPS2** [comment]
Just tested Tourist Trophy with SW, MTVU and VCS on current master and PR. Hardly any difference I wouldn't attribute to noise. I did notice on both builds being in the vehicle select screen with MTVU hack on would actually drop performance, while it improved performance on track. :/

**Comment by gregory38** [comment]
Ok. Main goal is to test if it is still working :) Atomic is quite touchy.

Honestly I don't expect a real speed boost, but thread management could be smoother. Unfortunately it doesn't improve issue #1437 so I need to big further.

**Comment by gregory38** [comment]
Maybe I will revert some atomic relaxing if it doesn't improve the issue #1437 too dangerous for no gain.

**Comment by gregory38** [comment]
Ok.  I rebased my work. I did a couple of modification. Some variables are more relaxed. And potentially fixes a deadlock (that likely never happen).

**Pull request merged**
