### PR TITLE
remove encounter of old GUI format in the First time configuration.

### PR DESCRIPTION
**Pull request by ssakash**

### CODE REVIEW

**Comment by bositman** [comment]
I remember there was some other issue that prevented us from using this 'easy' solution...I looked around but didn't find it though. I think @avih knew something about it

**Comment by gregory38** [comment]
In my opinion it would be better to understand why gsopen2 isn't detected and to fix the emulator (core) to use it. If you can reproduce the issue, set a breakpoint on it to find the culprit.

**Comment by ssakash** [comment]
@bositman 

I know that there is a other format for the PSX emulators. but, I don't really know what the old format present at First time configuration do.

**Comment by gregory38** [comment]
Did you try to set isOpen2 = true in the GSopen2 function?

**Comment by gregory38** [comment]
Hum, nobody must anymore GSopen1 interface. Except the replayer which is purely a debugger (and people don't need the gui anyway). V2 was added in 28 january 2010 for PCSX2 0.9.7.

I propose to completely wipeout the old GSopen1 gui. It just completely outdated.

**Comment by ssakash** [comment]
Setting isopen2 to true wil also produce the same result as the following commit. 

About the latter remark, should I completely remove the GSopen interface ? Doesn't it have any other uses ?

**Comment by gregory38** [comment]
I mean the dialog gui (not the GSopen function). So you could remove.
1/ is_gsopen2 variable
2/ IDD_CONFIG and related stuff from the resource file.

Result will be the same as your commit but with a lighter code.

**Comment by ssakash** [comment]
1/ could be done. 2/ that IDD file is for the older format GUI variables in GSdx plugin settings,  could be good for reducing the outdated GUI but, @bositman said that the older format GUI had a certain use somewhere so, I'm not sure about that. I still can't find what it's useful for though.

**Comment by gregory38** [comment]
the only purpose is to allow to use a gui to configure the plugin for quite old version of PCSX2.

It is still possible to use the new GUI to configure most option. And the 3-4 extra option related to gsopen1 can be done manually in GSdx.ini.

Honestly if the code is never called anymore, just remove it. There is enough mess in the code.

**Comment by ssakash** [comment]
I guess I will change the current IDD_CONFIG2 to IDD_CONFIG. since we are planning to remove the IDD_CONFIG itself I guess this method would be better and we wouldn't need the ternary operator.

**Comment by gregory38** [comment]
No keep the 2. By the way someone opens a pr with potentially a better fix. Don't do anything for the moment

I don't know what is the opinion on windows dev on this subject.

**Comment by ssakash** [comment]
so, no need to remove  IDD_CONFIG ?  I will wait till how it goes with the core fix. :)

**Comment by gregory38** [comment]
Ok. Let's close this PR. We will go with the #587, if you want to give it a test :)

**Pull request closed without merging**
