### PR TITLE
Move list erase to bottom of ProcessEvents()

### PR DESCRIPTION
**Pull request by tacchinotacchi**
Refer to  #1392
Sorry, I messed up with git and accidentally closed pull request D:

### CODE REVIEW

**Comment by FlatOutPS2** [comment]
pull requests can be closed, and reopened. ;)

**Comment by tacchinotacchi** [comment]
I'd like to concentrate on code instead of learning git :P
No seriously, I'll have to learn git

**Comment by gregory38** [comment]
@turtleli I let's you manage if you don't mind. Code is too complex for me.

**Comment by turtleli** [comment]
Hmm. Code is difficult for me as well!

While I understand the logic behind the change, it does makes ProcessEvents() non thread safe - if it's called from two different threads the same event will be invoked twice and a double delete will take place. While ProcessEvents() currently is only called from one thread (AFAIK), I think it would be best if it remains thread safe.

**Comment by tacchinotacchi** [comment]
You understand perfectly - my commit is based on the assumption the function does not need to be thread safe. Your pick.

**Comment by turtleli** [comment]
I'm going to say no. I don't like the idea of making the function non thread safe. If it does introduce issues it might be really painful to debug.

**Pull request closed without merging**
