### PR TITLE
GSdx Merge Circuit: Fix regressions

### PR DESCRIPTION
**Pull request by FlatOutPS2**
Fixes screen shaking in Tenchu: Wrath Of Heaven, and graphical issues in NASCAR 09.

### CODE REVIEW

**Comment by ssakash** [comment]
Well, did this seriously get merged? The code is definitely wrong as it doesn't allow any offset values above 10, haven't checked it yet but I'm 100% sure that it'll break split screen rendering in Time Crisis 2.

**Comment by ssakash** [comment]
Also it's not really your fault, FlatOut. I blame the awful code, the merge circuit code in GSdx is full of hacks and it obscures the actual intention of the code in a lot of ways. so would be nice to properly clean up the code someday.

**Comment by ssakash** [comment]
Also in case someone asks me for a GS dump - I can't provide it right now as I'm nowhere remotely close to my desktop/laptop, but IIRC I did provide a GS dump of ``Time Crisis 2`` to turtleli in some pull request, so try looking for the dump if you want to fix it. :P

**Comment by FlatOutPS2** [comment]
No need, I found the Time Crisis dump in my dump archive and you're correct I does break the split screen. What number should be the max then, 640?

**Comment by ssakash** [comment]
> What number should be the max then, 640?

I don't think having a guess based constant is a nice idea as it isn't generic and it would just obfuscate the already hacked up code in ``GSRenderer::Merge()``.

The question falls down to,

* Will having a max limit of ``640`` fix the regression we're facing with ``NASCAR 09``? **Probably yes**.

* Though will it be accurate to PS2 behavior? **It won't**.

I suggest you do what you think is right, I'm obviously no expert in GSdx. However for future PCRTC related PR's, would be nice if you could ask my feedback before it gets merged :P 

If you're highly insistent on going with a max limit idea then please do the checks only for the frame memory, not for the output circuit dimension.

**Pull request merged**
