### PR TITLE
Bump up C++ version to c++17 for gcc & clang

### PR DESCRIPTION
**Pull request by AmFobes**
_This does not implement c++17 std::filesystem!_

### CODE REVIEW

**Comment by tellowkrinkle** [comment]
Personally I feel like we should be switching over to `target_compile_features(target PRIVATE cxx_std_17)` for requesting a c++ standard

**Comment by AmFobes** [comment]
> Personally I feel like we should be switching over to `target_compile_features(target PRIVATE cxx_std_17)` for requesting a c++ standard
You want to set that for each target or is there a way to globally set that project wide?

**Comment by tellowkrinkle** [comment]
I would say per target, but there is `CMAKE_CXX_STANDARD` which is global

**Comment by orbea** [comment]
Can this be postponed till after `1.7.0` is released?

**Comment by AmFobes** [comment]
What's the benefit of waiting?

**Comment by orbea** [comment]
I just want at least one 64-bit compatible release that doesn't require newer compilers.

**Comment by AmFobes** [comment]
Alright well windows is already using the newer standard. It's not my call anyways.

**Comment by gregory38** [comment]
Release won't happen tomorrow. 2-3 years old compiler should be fine. It is "recent" but not bleeding edge.

**Comment by orbea** [comment]
2-3 years is still relatively modern when you consider older distros...

**Comment by gregory38** [comment]
Debian stable has gcc 8 already. And next year it will become old stable. We won't lag dev for distribution that have 3+ years old toolchain. They can still keep 1.6 (which is already a damn good emulator).

**Comment by orbea** [comment]
> They can still keep 1.6 (which is already a damn good emulator).

Which still requires multilib and I do not understand how using an older C++ standard for a little longer is holding back development, but I suppose it doesn't matter to anyone else I'm stuck supporting gcc-5.5.0...

**Comment by refractionpcsx2** [comment]
We have some coding going on in the background which uses C++17 and will probably be PR'd in the next couple of weeks.  Holding off until then won't be of any benefit for you.

If you have an outdated compiler, then use an older version, we aren't going to hold back progress and not use features because you don't keep your system up to date.

**Comment by gregory38** [comment]
Besides there is no issue to use multilib. It just takes some extra megabytes. Even ssd GB are pretty cheap nowadays. 64 bits won't bring you any extra performance anyway.

**Comment by orbea** [comment]
> Besides there is no issue to use multilib.

You vastly underestimate the extra burden multilib has on package maintainers.

**Comment by kenshen112** [comment]
Maintainer of Arches pcsx2-git here. There's a burden?

**Comment by AmFobes** [comment]
Alright ladies and gentlemen I've decided to not be lazy. 
I have set the c++17 standard for PCSX2 and the relevant plugins individually.

**Review by tadanokojin — APPROVED** [review]

**Review by lightningterror — APPROVED** [review]

**Pull request merged**
