### PR TITLE
Common: cleanup

### PR DESCRIPTION
**Pull request by tadanokojin**
### Description of Changes
Reorganize the common directory:
- merge `x86emitter` and `Utilities` into a single project
- force include the precompiled header on windows
- normalize the include directories (files are included relative to root for now so they are namespaced to `common/`)

### Rationale behind Changes
Reorganization of the project and future plans to remove wx

"Common" is a popular organizational idiom across many emulator projects at this point and I think it's useful. The idea is to have a home for OS abstraction and utilities used across multiple projects.

### Suggested Testing Steps
just make sure everything still builds

### TODO
- [x] normalize OS/arch specific includes (ifdef instead of exclude from build)
- [x] VS filters
- [x] macos (cmake)
- [x] linux (cmake)
- [x] figure out what to actually include in the PCH (Dependencies.h has a bunch of random stuff in it)

### After Merge Plans
- Cleanup Dependencies.h (need to define no getext macro project wide and separate things out)
- Clang format
- Remove wx dependency from our new common project
- Remove any pcsx2 specific naming
- reorganize the source tree so it's not relative to root anymore
- start pulling stuff out of pcsx2 and former plugins

### CODE REVIEW

**Comment by tadanokojin** [comment]
```
➜  common git:(common-cleanup) ✗ egrep -Rho "#include <.*>" | sort | uniq -c
      1 #include <ShTypes.h>
      1 #include <VersionHelpers.h>
      1 #include <algorithm>
      4 #include <atomic>
      1 #include <cassert>
      1 #include <cpuid.h>
      4 #include <cstdio>
      3 #include <cstdlib>
      4 #include <cstring>
      1 #include <ctype.h>
      3 #include <errno.h>
      2 #include <list>
      1 #include <mach/mach.h>
      1 #include <mach/mach_error.h>
      1 #include <mach/mach_init.h>
      1 #include <mach/mach_port.h>
      2 #include <mach/mach_time.h>
      2 #include <mach/semaphore.h>
      1 #include <mach/task.h>
      1 #include <mach/thread_act.h>
      4 #include <memory>
      1 #include <mutex>
      2 #include <pthread.h>
      1 #include <pthread_np.h>
      1 #include <queue>
      1 #include <semaphore.h>
      3 #include <signal.h>
      1 #include <stack>
      2 #include <stdexcept>
      1 #include <stdint.h>
      1 #include <sys/mman.h>
      1 #include <sys/prctl.h>
      1 #include <sys/sysctl.h>
      3 #include <sys/time.h>
      1 #include <sys/types.h>
      1 #include <thread>
      1 #include <time.h>
      1 #include <timeapi.h>
      5 #include <unistd.h>
      2 #include <vector>
      2 #include <windows.h>
      3 #include <wx/app.h>
      1 #include <wx/apptrait.h>
      1 #include <wx/config.h>
      1 #include <wx/crt.h>
      1 #include <wx/cshelp.h>
      1 #include <wx/datetime.h>
      1 #include <wx/display.h>
      2 #include <wx/event.h>
      1 #include <wx/file.h>
      3 #include <wx/filefn.h>
      1 #include <wx/filename.h>
      4 #include <wx/gdicmn.h>
      1 #include <wx/image.h>
      1 #include <wx/intl.h>
      1 #include <wx/log.h>
      1 #include <wx/mstream.h>
      1 #include <wx/msw/wrapwin.h>
      1 #include <wx/spinctrl.h>
      2 #include <wx/stream.h>
      7 #include <wx/string.h>
      4 #include <wx/thread.h>
      1 #include <wx/tokenzr.h>
      1 #include <wx/tooltip.h>
      2 #include <wx/utils.h>
      1 #include <wx/window.h>
      1 #include <wx/wizard.h>
      7 #include <wx/wx.h>
      1 #include <xmmintrin.h>
```

**Comment by tadanokojin** [comment]
I'm happy with this for now. I'm going to go through `Dependencies.h` and define the `WXINTL_NO_GETTEXT_MACRO` macro in the build system in a follow up before this starts getting too big.

**Review by xTVaser — APPROVED** [review]
Builds fine on Release AVX2 | Win32
Was this `resource.h` missed as part of the filter cleanup? It looks like it belongs with GSdx's GUI stuff?
image

**Comment by tadanokojin** [comment]
fixed here: https://github.com/PCSX2/pcsx2/commit/b61f6d517bd0401e7f066308bf97a7c2d9095c46

just a little out of sync with master

**Comment by refractionpcsx2** [comment]
Build all the 32bit builds and x64 AVX2 Release for prosperity, all built fine.

**Pull request merged**
