### PR TITLE
 Gamedb: fixup wrong titles and add game fixes 

### PR DESCRIPTION
**Pull request by Mrlinkwii**
### Rationale behind Changes

a more correct Gamedb
### Suggested Testing Steps

none

### CODE REVIEW

**Comment by HelelSingh** [comment]
Hi. If you don't mind can you also fixup the title in two entries for **Initial D - Special Stage** mislabeled as **Initial D - Street Stage** (that's the PSP game).

Thanks in advance.

**Comment by Mrlinkwii** [comment]
> Hi. If you don't mind can you also fixup the title in two entries for **Initial D - Special Stage** mislabeled as **Initial D - Street Stage** (that's the PSP game).
> 
> Thanks in advance.
whats the serial ?
:slightly_smiling_face:

**Comment by HelelSingh** [comment]
**SCAJ-25008** and **SLPM-74420**.

**Comment by Mrlinkwii** [comment]
@HelelSingh  can you double check that for me :+1:

**Comment by HelelSingh** [comment]
All good. Thanks again.

**Pull request merged**
