### PR TITLE
gsdx-texture-cache: Improve fix for snow engine game

### PR DESCRIPTION
**Pull request by gregory38**
Instead to hardcode the half-buffer size to 0x140, the new code
compute it.

To avoid regression, I limit the code to big target (>= 1024 pixels)

Please test it (on any games)

### CODE REVIEW

**Comment by Dreadmoth** [comment]
Compiled and tested the plug-in:

Baldur's Gate: Dark Alliance -> still good, haven't noticed any new issues
Baldur's Gate: Dark Alliance II -> still good, haven't noticed any new issues
Champions of Norrath -> half-screen issue fixed
Champions: Return to Arms -> half-screen issue fixed

Used same settings, game versions and PCSX2 version as I did with my [previous tests](https://github.com/PCSX2/pcsx2/pull/545#issuecomment-108066055).

Nice work! :+1:

**Comment by Dreadmoth** [comment]
Uploaded the plug-in for anyone who wants to test but can't compile it themselves: https://www.mediafire.com/?ppn6yhcc7kqf8b6

Hopefully I didn't mess it up somehow - first time I've used Visual Studio

**Comment by gregory38** [comment]
good initiative :+1:

**Comment by Meowmel** [comment]
What a coincidence, just did a short 5h marathon playing Champions of Norrath co-op with a friend - Dolphin sadly started to shit itself playing Baldur's Gate 1: Dark Alliance from where we stopped last week. :(
Used v1.3.1-449-g6c8f7a0 from the Buildbot. OGL SW Mode still has the "gsdx out-of-memory texturing temporarily disabled" with heavy texture flickering (starting at the forest), 4GB Patch on the pcsx2.exe fixes this. After this, no crashes, no texture problems anymore. Will do more testing after some sleep. OGL HW worked as well, but we had some fps problems with 2 on-screen characters.

**Comment by karasuhebi** [comment]
Will the need for NTCore's 4GB patch go away when PCSX2 goes fully x64?

**Comment by gregory38** [comment]
On linux we have 4GB as default on 64 bits kernel.

However I do think it is possible to reduce memory consumption. First we need to find the source. Then find a solution :p

**Comment by Ploff** [comment]
Can confirm Champions: Return to Arms has been fixed.

Also tested Tekken 5, no new issues to report.

**Comment by mirhl** [comment]
@karasuhebi
Given we have access to pcsx2 sources, why can't large address aware flag be included in the code?

**Comment by gregory38** [comment]
Ok. Let's go in the wild.

LA flags doesn't solves VRAM limitation neither performance drop. Code can be fixed (nearly sure)

**Comment by Dreadmoth** [comment]
Updated to a5fe847, tested again:

Both Baldur's Gate: Dark Alliance games work fine - same as previous version tested.

Both Champions games have a new problem: right side of the screen is stretched and far right side is cut off - this occurs at native resolution and at multiples of native resolution. [GS dumps and screenshots](https://www.mediafire.com/?tqq6ki3kp65wb6q).

Also tested Drakan: The Ancients' Gates: it works normally at native resolution and multiples of native resolution, but custom resolutions don't work - if custom is selected the game renders at native resolution. I'm not sure if this issue is new to this particular build - might have appeared due to some other recent change. I remember custom resolutions working correctly in Drakan with the PCSX2 1.2.1 release.

**Comment by gregory38** [comment]
@refractionpcsx2, it seems height detection is not yet perfect.

Custom resolution is broken due to auto detection support. I think Ref want to remove it completely.

**Comment by refractionpcsx2** [comment]
I thought I did last night ?

**Comment by refractionpcsx2** [comment]
In 0a46729 it has been changed so height is set based on the buffer width again and set before the custom resolutions are selected

**Comment by Dreadmoth** [comment]
Tested 0946958 - Champions games fixed, Baldur's Gate games still good :)

**Comment by Blinkyrocket** [comment]
What about performance? I used the fix and the screen looks great at 4x native, now the only problem is FPS

**Comment by gregory38** [comment]
Performance isn't important currently. Priority is on accuracy.

**Comment by Blinkyrocket** [comment]
Might not need it anyway, I got the latest SVN and have speed hacks set to around 2 on both and am playing the beginning of Champions at constant 60 frames, performance problem might be solved for me but the beginning isn't as performance intensive as the rest of the game.

**Comment by Blinkyrocket** [comment]
Nope, still slows to 34 fps in caves.

**Comment by SWEG1337** [comment]
Hi, thanks for your work. I am new in the emulator world and I need some help. I have downloaded the plugins from Dreadmoth and put all the files in my pcsx2 folder. Do I need to enable something somewhere because I still can't play Baldur's Gate Dark Alliance.

**Comment by refractionpcsx2** [comment]
Frm dreadmoth? Just get the latest git build from pcsx2.net, it should be working fine

**Comment by Dreadmoth** [comment]
Yeah, the [latest git build](http://pcsx2.net/download/development/git.html) should work and should have less graphical issues than the plug-in from this revision.

**Comment by SWEG1337** [comment]
Okay, so I have downloaded the latest GIT build but BG: DA is still cut in half - and runs extremely slow when run in SW mode but with the half screen fixed. (I believe it is, when I press F9). Do you guys know if I do anything wrong here?

**Comment by refractionpcsx2** [comment]
Sounds like you're using a custom resolution where the width is less than 1280.

use the Native x# options or Native Resolution

**Comment by SWEG1337** [comment]
It is a fresh install, so I haven't changed anything in regards to resolution. The res I see in options is 640*480 - I have also applied the 4GB patch which helped a bit with the speed when run in SW but it is still extremely slow.

**Comment by refractionpcsx2** [comment]
Yeh use hardware mode with one of the scaling options, not the custom resolution, that will break it.

even if you use Native if you want it smallish.

**Comment by SWEG1337** [comment]
Okay nice, so I played around with the settings to get the best result. Now it runs 100% smooth with no hiccups or anything, and even cinematics looks nice with no robot voice. I used the Direct3D11 renderer and 2x native scaling with 8bit textures enabled.
Thanks to everyone for helping.

**Comment by refractionpcsx2** [comment]
No problems :) There will be crashes and slow points, the game eats memory, so make sure you save often :)

**Comment by karasuhebi** [comment]
@SWEG1337 Glad @refractionpcsx2 was able to help you out, but please next time don't clutter up the discussion for a Pull Request with support questions. That's what the forums are for:
http://forums.pcsx2.net/Forum-General-Discussion-and-Support-Windows

**Comment by YaakovSmirnoff** [comment]
I cant even find a download button

**Comment by mirhl** [comment]
This is **merged** in pcsx2. 
There's nothing to see here anymore. Just download official release.

**Pull request merged**
