### PR TITLE
Move icons (Emulation Settings, Plugin BIOS selector) to the left

### PR DESCRIPTION
**Pull request by turtleli**
Benefits:
 * Fixes the minimise then restore dialog bug on the Emulation Settings and Plugin/BIOS selector, where the bottom GUI elements become misplaced.
 * Fixes a bug on 200% DPI (and maybe 175% DPI) where it's difficult to use GUI elements near the top (i.e. GS Plugin selector, Enable Speedhacks, etc.) since part of it becomes unclickable.
 * Makes Windows and Linux look more similar.
 * Makes it easier for me to work on the GUI stuff - currently I cannot see the whole Emulation Settings dialog when I use 200% dpi with my monitor, so it makes testing rather annoying. After the change, I can.

Does anyone object to this?

Before:
before
After:
after

### CODE REVIEW

**Comment by ssakash** [comment]
If it does have benefits, I don't have any problem with it.

>Fixes the minimise then restore dialog bug on the Emulation Settings and Plugin/BIOS selector, where the bottom GUI elements become misplaced.

I don't encounter any such issues, could you give more information relevant to this ?

while the new sorting of the listbook icons do look a little cool, isn't there any alternative to fix the following issues rather than changing the sorting order ? It does affect the consistency though,

either way, @avih  , @refractionpcsx2  , @gregory38  should look at this.

**Comment by karasuhebi** [comment]
I have no objections to it. I actually welcome it since it makes it look like the Linux settings, which I say is a good thing for consistency.

**Comment by turtleli** [comment]
@ssakash I had this on Windows 8.1 and 10 after minimising and restoring the dialog
bug

If there is an alternative fix then I don't know what it is.

**Comment by ssakash** [comment]
@turtleli 

 Thanks for the Information, I had never noticed this issue. If there are no other available alternatives then, it's fine IMO.

**Comment by refractionpcsx2** [comment]
I have no problem with this as long as there is enough vertical room for lower resolutions,  or a scrollbar for the top options then it's fine :)

**Comment by turtleli** [comment]
Anyone using a 960x600 resolution will like the changes ;)

Extra changes:
 * Cleanup - removed stuff I forgot about.
 * All platforms have listbook icons on left - I thought listbook = dialog menu icons on OS X, from the wxWidgets documentation pictures it's not. So it should be ok I think.

I'll squash the last commit into the first one before merging, which I'll do either later today or tomorrow.

**Comment by vsub** [comment]
Any idea why the icons don't look like the "After" image in the first post(I'm using the latest beta)
The white box is not that wide and the distance between the icons is not that big which results in couple of problems

When you select GS Window(which is actually GS new row Window),the text is partially hiding the Speed Hacks(which is actually Speedh... when not selected and Speedha new row ks when selected)icon and when you click on the Speed Hacks icon,the icon is hiding the GS Window Text.

The "Game Fixes" is also not "Game Fixes" but Game new row Fixes.

I'm using 1920x1080 at 96dpi(100%)

**Comment by turtleli** [comment]
Hmm. That's annoying :(

I don't really know why. It's probably a combination of 
1. Icon width used to determine width of white box, not the max of the icon width and text. If I increase the icon size or remove the icons altogether it'll probably sort itself out.
2. Different sizing algorithm used on Windows 7 and Windows 10. Windows 7 probably adds less space around the icons.

I might have to set up a Windows 7 VM to see if I can fix this. Worst case is that I'll have to revert the change.

**Comment by vsub** [comment]
I find what's wrong but I don't know if this can be considered a bug(to make it look correctly,you are forced to use certain settings)

Right click on the desktop=>Personalize=>Window Color=>Advanced appearance settings=>Icon=>Size
The default size is 32 and it looks correctly that way.
I can change few settings to make it look the same as with 16(which I use)and still use 32

Is it possible to force a size to the white box and the icons(to not be dependent on windows settings)?

**Comment by turtleli** [comment]
It might be difficult, wxWidgets automatically sizes the white box. I'll see if I can find a solution or workaround, it might take quite a bit of time though.

**Comment by willkuer** [comment]
But just doubling icon size does not solve the issue?

**Comment by turtleli** [comment]
I did icon size adjustments in #807 if a user is using DPI scaling, but the dialog size might be a bit of a problem for 96dpi if I just doubled the icon size. Maybe allowing users to change the icon size or not use icons at all will solve the problem, but I don't really know at this stage.

**Comment by vsub** [comment]
Yes,just doubling the icon size(32)does fix the problem but the desktop icons don't look good at all(too much space between them)

Btw,I don't know if this will help but the regedit key that keep that info is
HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics\Shell Icon Size
Just a random idea...how about getting the value and set the icon size to 32 in the window if the value is lower than 32

**Pull request merged**
