### PR TITLE
GSdx: GSHwHack.cpp cleanup

### PR DESCRIPTION
**Pull request by lightningterror**
Cleanup trailing whitespaces , indentation , rows , comments.

A little bit of ocd satisfaction.

### CODE REVIEW

**Comment by lightningterror** [comment]
Aww that was supposed to be a secret.

Anyway that didn't serve any purpose as i see.

**Comment by MrCK1** [comment]
Well didn't test the code for.regressions? That's the most important step.

**Comment by gregory38** [comment]
don't bother with formatting stuff. The plan is to reformat the full plugin with clang-format after the 1.6 release

**Comment by lightningterror** [comment]
Hmm well I already did the pr. What do you suggest we do about it @gregory38 ?

**Comment by gregory38** [comment]
if all modif are related format, you can drop it. I'm sorry you lose time on it.

**Comment by lightningterror** [comment]
-	else
-	{
-	}

The only code I removed if that counts xD

**Comment by gregory38** [comment]
nope doesn't count. I think I will reformat the plugin after the bulk of GSdx PR are merged.

**Comment by lightningterror** [comment]
@MrCK1 No regressions ofc :)

@gregory38 I'll leave it to you then :)

**Pull request closed without merging**
