### PR TITLE
Qt: Drop libsamplerate dependency for Qt+MSVC

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

See above.

### Rationale behind Changes

It's only used by USB/WASAPI, which doesn't exist in Qt.

### Suggested Testing Steps

Make sure CI passes.

### CODE REVIEW

**Comment by seta-san** [comment]
Isn’t usb coming to qt?

**Comment by refractionpcsx2** [comment]
Eventually, but not yet

**Comment by stenzek** [comment]
Ideally, with a rewrite...

**Review by Mrlinkwii — APPROVED** [review]

**Comment by tellowkrinkle** [comment]
Mind doing it on the cmake project while you're at it?
image

**Comment by stenzek** [comment]
Done.

**Pull request merged**
