### PR TITLE
BIOSHLE: Use BIOS settings on fastboot

### LINKED ISSUE #480: Feature Request: Save/Load BIOS settings from (CFG) file
So I was wondering if it would be possible to implement a feature that would let you save the current BIOS settings to a file and then be able to edit it as needed. 

The main reason I want to see this feature implemented is because (at least in Burnout 3: Takedown) Boot (Fast) seems to use the default BIOS settings/doesn't load the current BIOS settings (since it skips it), whereas Boot (Full) does. A personal gripe I have is with games that set 16:9 Widescreen mode based on the BIOS settings.

By having the BIOS settings be loaded from a file (or maybe even be editable within PCSX2's menu interface), things would be a good bit more convenient, even if not all games have this 'problem.'

Thanks in advance.

PS. While I would be very happy to see this feature implemented, I wouldn't mind at all if it isn't possible to add in.

### PR DESCRIPTION
**Pull request by refractionpcsx2**
Should fix bad fonts when booting a game fast
Selects correct language for games depending on your BIOS setting when using fast boot
Stops games such as Guitar Hero 2 from crashing on fast boot.

PR also now corrects timezones in games.

Fixes #480

### CODE REVIEW

**Review by RedDevilus — APPROVED** [review]
image

Master: Bios on Dutch
Fast: French
Full: Dutch

PR:   Bios on Dutch
Fast: Dutch
Full:  Dutch
Works for me, i even went into bios to change it.
PR:   Bios on French
Fast: French
Full:  French

**Comment by RedDevilus** [comment]
Prince Caspian a game that keeps on giving. Timezone sensitivities (i have GMT+1 with Daylight Saving Time)

Master:
Full: Uses GMT + 1 ignoring DST
Fast: Uses GMT +9 aka Japan time

PR:
Full: Uses GMT + 1 but applies DST correctly
Fast: Uses GMT + 1 but applies DST twice ( does minus 2 hours)

**Comment by CookiePLMonster** [comment]
GTA Vice City Stories - testing date/time (BIOS setting: GMT+1, DST enabled):

Master:
Full: Uses GMT+1 and DST
Fast: Uses GMT+9

PR:
Full: Uses GMT+1 and DST
Fast: Uses GMT+1 and DST


TOCA Race Driver 3 Demo - testing an Aspect Ratio option (BIOS setting: 16:9; Widescreen Cheats disabled):

Master:
Full: Game is 16:9
Fast: Game is 4:3

PR:
Full: Game is 16:9
Fast: Game is 16:9

**Comment by RedDevilus** [comment]
Ignore my previous results, i confused myself.

BIOS is set to 19 (summer time), BIOS is set to 18 (winter time)
Summertime;
Full: Same as BIOS clock ( CORRECT )
Fast: Same as BIOS clock ( CORRECT )
Wintertime (currently using on windows);
Full: Same as BIOS and Windows clock  ( CORRECT )
Fast: Same as BIOS and Windows clock ( CORRECT )

**Pull request merged**
