### PR TITLE
GameDB: Matrix Path Of Neo Fixes

### PR DESCRIPTION
**Pull request by JordanTheToaster**
### Description of Changes
Fixes broken post processing by using autoflush.

Master:
Matrix, The - Path of Neo_SLUS-21273_20230622094040

PR:
Matrix, The - Path of Neo_SLUS-21273_20230622094056

### Rationale behind Changes
Broke game bad.

### Suggested Testing Steps
Make sure CI is happy.

### CODE REVIEW

**Comment by legend800** [comment]
@JordanTheToaster @refractionpcsx2 

This is not a full fix. Other stages highlight this better than the one chosen above. Merge Sprite is much better at fixing the over-brightness and actually addressing the biggest playability issue - the annoying character halos. 

Merge Sprite is a hair darker than it should be but you can mostly fix with Post Processing Brightness. So with Merge Sprite + brightness adjust, it's 95% close to Software as you can see below. This new commit even now forces me to disable Auto-Flush since it makes the character halos persist with Merge Sprite on. 

Auto-Flush Off:
af off1

Auto-Flush On (brightness fixed, but char halos are still broken)
af on1

Merge Sprite on + brightness at 70 (halos perfect, gamma a tad off)
merge sprite1

Software:
software1

I just hope we can find a way to avoid all the hacks and get HW looking just like Sofware, with just better resolution. ;)

**Comment by refractionpcsx2** [comment]
aside from some misalignment, how it is now with autoflush looks exactly like software (besides some upscaling misalignment), merge sprite just destroys the lighting completely.

**Comment by legend800** [comment]
The misalignment is everything. It's unplayable with "double" ghosting over everything. With Auto-Flush forced on now, you're condemning everyone to the ghosting problem unless they override it. That's bad. 

Merge Sprite looks just like Software on most levels - it does not DESTROY the lighting "completely" at all. See below. It fixes the primary playability issue with this game and users can boost lighting in other levels if they want, else it's perfectly fine with no ghosting. 

Have tried playing a level with all the ghosting? I recommend some time with the game, since videos/screens don't do the issue justice, before these assessments are made. 

Merge Sprite - **_NO brightness fix_**
merge sprite

Software:
software

**Comment by Mrlinkwii** [comment]
A) its not "unplayable" B) if you have an issue with upscaling  , you can enable manual fixes :)

**Comment by refractionpcsx2** [comment]
You could play in native resolution where it should be fine, we don't take upscaling issues as it says in the issue templates.

You're also welcome to force your own settings in the per-game settings, or you can also work out a patch to remove the lighting that causes the problem.

**Pull request merged**
