### PR TITLE
Fix Goemon hack for prototype builds (by @Sazpaimon)

### PR DESCRIPTION
**Pull request by swosho**

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
We've been here before, no prototype fixes.  You're welcome to use your own fork.

There's potentially a better fix coming, so just wait for that.

**Comment by swosho** [comment]
My bad! Accidentally pushed it to the main repo ○|￣|_
Thanks for the heads up about a potential fix.

**Comment by JosepMC154** [comment]
> There's potentially a better fix coming, so just wait for that.

Any news on this? I would really like to play the English build with mainline PCSX2.

**Comment by F0bes** [comment]
Sorry, no new news. We also don't support prototype or romhack copies of games.

**Pull request closed without merging**
