### PR TITLE
FolderMemcard: Keep open handles on files.

### PR DESCRIPTION
**Pull request by AdmiralCurtiss**
Discussed in #666. This keeps all files in the virtual memory card open while the emulator is running, preventing other programs/users from modifying or deleting them. Oddly enough not all programs seem to respect that, somehow; Notepad++ still can edit the file, HxD cannot, Windows Explorer can't delete or rename/move. So this could probably be improved but it's much better than before.

Additionally, since the opportunity presented itself, I now adjust the host file system file timestamps to match the memory card's internal ones.

### CODE REVIEW

**Comment by bositman** [comment]
Don't see any reason not to use this, thanks :)

**Comment by bositman** [comment]
Hm not sure if this build caused this (will investigate) but I experienced this: I already had a folder save file for a game (BASLUS-21448). Downloaded a save from someone else, replaced my folder's contents with his but PCSX2 still loaded my old save. I then deleted the folder completely, moved the folder with the new save and only then did the new save actually got loaded...it was like my old save was cached, even if the files had been overwritten with different ones

**Comment by bositman** [comment]
Also, the file lock system even locked a RAR backup file I created inside the super folder ( BASLUS-21448.rar ) while PCSX2 was running that particular game. Minor I guess but still a bug

**Comment by AdmiralCurtiss** [comment]
We have no way of knowing if a file in the memory card folder is a file the PS2 and its software cares about or not, so we just have to assume all of them are. So yes, if you put a backup file in your memory card folder, it will be loaded into the virtual memory card, and thus locked while the emulator is running.

**Comment by bositman** [comment]
Hm fair enough, although it was in the super folder, not inside the particular game's save folder

**Comment by AdmiralCurtiss** [comment]
To be fair, I have yet to see a non-homebrew piece of software that stores files in the root of the memory card, so it's probably fine to not load those when filtering is enabled. Still though.

**Comment by karasuhebi** [comment]
>it was like my old save was cached, even if the files had been overwritten with different ones

What about this issue @AdmiralCurtiss? Did you figure out what was causing it?

**Pull request merged**
