### PR TITLE
Flatpak: Add screenshots

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Needed for us to push to flathub.

This will probably fail until https://github.com/PCSX2/pcsx2-net-www/pull/235 is merged and the site is updated.

### Rationale behind Changes

Packaging

### Suggested Testing Steps

Make sure flatpak build passes in CI

### CODE REVIEW

**Comment by stenzek** [comment]
Drafting because apparently pcsx2.net is blocking actions... might need to just stash the screenshots in the repo instead.

**Comment by xTVaser** [comment]
I don't think pcsx2.net is blocking actions.  I dug into the `appstream-util` code and the error seems related to the format, not the download.  I'm also able to `curl` the images locally -- which is what the cli basically does as well.

https://github.com/hughsie/appstream-glib/blob/main/libappstream-glib/as-app-validate.c#L523

I'd recommend just trying normal `png`s or `jpg`.  It sucks that the CLI code doesn't capture the error (third argument) and log it out instead of swallowing it.  Another option is to make sure the runners have `libwebp` installed but, pngs seem totally fine?

**Comment by stenzek** [comment]
Yeah, sounds plausible. I did run it locally on Ubuntu 23.04 and it was fine... but obviously with different system libraries to the actions runner.

I'll probably just put them in the repo, and reduce the number to one or two.

**Comment by stenzek** [comment]
Note: The build failed here because the links in the xml point to master, and it doesn't exist yet. I verified it works fine on my fork, so should be fine after merge.

**Pull request merged**
