### PR TITLE
GS/HW: Add "Merge Targets" texture-in-RT mode

### LINKED ISSUE #55: Destroy all Humans
There is graphical artifacts covering the entire screen in Hardware mode, both DX/GL, software is fine. 

destroy all humans

### LINKED ISSUE #785: Odd shadows in Hardware mode for Aqua team, Ninja golf
"Evil dead"
http://imgur.com/SgGQ0w9

"Aqua team"
http://imgur.com/NDCRx0M

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

This mode can construct a source from one or more targets currently on the GPU, taking into consideration differing page pitches.

Fixes shadows in Destroy All Humans. Can also be used for Guitar Hero, although that has a bunch of other clear/invalidation issues in play too.

Before:
Untitled
After:
Untitled

My rambling about DAH:
> so they render the shadow map, and to deal with world-space that fall outside the range, since the PS2 has no "clamp to border colour" option, they need a black rectangle around the shadow map
most games will just draw a 1px line in such cases
> but no, this bugger offsets the base pointer by -32 (effectively moving the texture towards the right, with the right most page moving down one row), then redraws it with slightly offset texture coordinates
> why they couldn't just offset the coordinates instead of shifting the base pointer?
> so I've come up with a convoluted "create a source from multiple targets and local memory" method, that also handles differing page pitches (which is needed for guitar hero)
> if I'm going to create a whacky solution, I want it to be applicable to more than one game 😛

### Rationale behind Changes

Closes #55.
Closes #785.

### Suggested Testing Steps

Test DAH, I'm not sure if the second game is affected though.
Make sure nothing else is broke.
See if anything else can use this fix? (except Guitar Hero).

### CODE REVIEW

**Comment by seta-san** [comment]
oldest bug issue being fixed :)

**Comment by yellows111** [comment]
Hey, these shadow errors look like what's happening in Poinie's Poin with it's motion blurs with Render Textures enabled. (Was required for a fix for a regression introduced in v1.7.4110 [#8245])

Would this happen to improve that field?

**Comment by stenzek** [comment]
No, unless it was offsetting BPs backwards, or using different pitches (but that part isn't enabled yet).

**Comment by yellows111** [comment]
> No, unless it was offsetting BPs backwards, or using different pitches (but that part isn't enabled yet).

Just tested this, and your assumption was correct. Still looks like it has a strange dark scanline filter with Merge Targets enabled.

However it seems there are some regressions with the game in the branch.
Poinie's Poin_SCPS-15013_20230226152528
[Poinie's Poin_SCPS-15013_20230226152528.gs.gz](https://github.com/PCSX2/pcsx2/files/10834014/Poinie.s.Poin_SCPS-15013_20230226152528.gs.gz)

Poinie's Poin_SCPS-15013_20230226152142
[Poinie's Poin_SCPS-15013_20230226152142.gs.gz](https://github.com/PCSX2/pcsx2/files/10834015/Poinie.s.Poin_SCPS-15013_20230226152142.gs.gz)

**Comment by Dreadmoth** [comment]
>Test DAH, I'm not sure if the second game is affected though.

Destroy All Humans! 2 is affected. 👍

A small issue remains - shadows in the right-most 64 pixels (native) get stretched (clamped?) to the right edge.

Before:
DAH2before
After:
DAH2after
Software:
DAH2SW

GS dump: [Destroy All Humans 2 - Make War not Love_SLES-54384_Shadows.gs.gz](https://github.com/PCSX2/pcsx2/files/10836945/Destroy.All.Humans.2.-.Make.War.not.Love_SLES-54384_Shadows.gs.gz)

**Comment by stenzek** [comment]
Yeah, I'm aware of the right-side-stretching thing, it affects DAH1 too.

**Comment by stenzek** [comment]
Right side issues should be fixed now. Also auto enabled the fix for DAH2 in the gamedb.

**Pull request merged**
