### PR TITLE
Search for wx-config-3.0 and wxrc-3.0.

### PR DESCRIPTION
**Pull request by micove**
The comment made it look as an arch-only thing which was misleading.
.
Gentoo uses
wx-config-3.0 and wxrc-3.0 which are still masked (~).

The current code ONLY overrides the user input if a valid wxWidgets_CONFIG_EXECUTABLE AND wxWidgets_wxrc_EXECUTABLE is found. This avoids:

WX28_API=TRUE, wxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config-3.0
WX28_API=FALSE, wxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config-2.8

This ensures we pick a correct version if auto-detected. If nothing is auto-detected it defaults to whatever the user gave and if the user gave nothing then whatever FindwxWidgets.cmake found. A second user input validation is done by APIValidation.cmake which gives a fatal error in the case the IF-block was never triggered or the auto-detection was wrong.

To avoid the 1st level of error detection and correction and allow any input, including this:
WX28_API=TRUE, wxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config-3.0
WX28_API=FALSE, wxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config-2.8

Then merge PR #422 and let APIValidation.cmake stop the build w/o trying to automatically fix it first.
Note: WX_version() in APIValidation did not exist back then so forcing to use the correct executable was needed at that point.

### CODE REVIEW

**Comment by micove** [comment]
Okay, let fix the silliness of wxwidgets.

Using:
```
find_package(wxWidgets COMPONENTS base core adv)
message("wxWidgets_CONFIG_OPTIONS=${wxWidgets_CONFIG_OPTIONS}")
message("wxWidgets_FOUND=${wxWidgets_FOUND}")
message("wxWidgets_INCLUDE_DIRS=${wxWidgets_INCLUDE_DIRS}")
message("wxWidgets_LIBRARIES=${wxWidgets_LIBRARIES}")
message("wxWidgets_LIBRARY_DIRS=${wxWidgets_LIBRARY_DIRS}")
message("wxWidgets_DEFINITIONS=${wxWidgets_DEFINITIONS}")
message("wxWidgets_DEFINITIONS_DEBUG=${wxWidgets_DEFINITIONS_DEBUG}")
message("wxWidgets_CXX_FLAGS=${wxWidgets_CXX_FLAGS}")
message("wxWidgets_USE_FILE=${wxWidgets_USE_FILE}")
```

Current behaviour if wx2.8 and wx3.0 are installed and WX28_API=TRUE
Current behaviour if only wx3.0 installed and and WX28_API=TRUE
```
$./build.sh --wx28
<deleted>
-- Found wxWidgets: TRUE  
wxWidgets_CONFIG_OPTIONS=--unicode=yes
wxWidgets_FOUND=TRUE
wxWidgets_INCLUDE_DIRS=/usr/lib/i386-linux-gnu/wx/include/gtk2-unicode-3.0;/usr/include/wx-3.0
wxWidgets_LIBRARIES=-L/usr/lib/i386-linux-gnu;-pthread;;;-lwx_baseu-3.0;-lwx_gtk2u_core-3.0;-lwx_gtk2u_adv-3.0
wxWidgets_LIBRARY_DIRS=/usr/lib/i386-linux-gnu
wxWidgets_DEFINITIONS=_FILE_OFFSET_BITS=64;WXUSINGDLL;__WXGTK__
wxWidgets_DEFINITIONS_DEBUG=
wxWidgets_CXX_FLAGS=-pthread
wxWidgets_USE_FILE=/usr/share/cmake-3.0/Modules/UsewxWidgets.cmake
<deleted>
CMake Error at cmake/ApiValidation.cmake:67 (message):
  Mismatch between wx-config version (3.0.2) and requested WX API (2.8.x)
```

Current behaviour if only wx2.8 installed and and WX28_API=FALSE
```
 ./build.s
-- Found wxWidgets: TRUE  
wxWidgets_CONFIG_OPTIONS=--unicode=yes
wxWidgets_FOUND=TRUE
wxWidgets_INCLUDE_DIRS=/usr/lib/i386-linux-gnu/wx/include/gtk2-unicode-release-2.8;/usr/include/wx-2.8
wxWidgets_LIBRARIES=-L/usr/lib/i386-linux-gnu;-pthread;-Wl,-z,relro;;-L/usr/lib/i386-linux-gnu;;;-lwx_baseu-2.8;-lwx_gtk2u_core-2.8;-lwx_gtk2u_adv-2.8
wxWidgets_LIBRARY_DIRS=/usr/lib/i386-linux-gnu;/usr/lib/i386-linux-gnu
wxWidgets_DEFINITIONS=_FILE_OFFSET_BITS=64;_LARGE_FILES;__WXGTK__
wxWidgets_DEFINITIONS_DEBUG=
wxWidgets_CXX_FLAGS=-pthread
wxWidgets_USE_FILE=/usr/share/cmake-3.0/Modules/UsewxWidgets.cmake
CMake Error at cmake/ApiValidation.cmake:70 (message):
  Mismatch between wx-config version (2.8.12) and requested WX API (3.0.x)
```

Current behaviour if wx2.8 and wx3.0 are installed and WX28_API=FALSE (works)
Current behaviour if only wx2.8 installed and and WX28_API=TRUE (works)
Current behaviour if only wx3.0 installed and and WX28_API=FALSE (works)


Now using this patch
```
--- a/cmake/SearchForStuff.cmake
+++ b/cmake/SearchForStuff.cmake
@@ -23,6 +23,18 @@ else()
     set(wxWidgets_CONFIG_OPTIONS --unicode=yes)
 endif()
 
+if(WX28_API)
+    set(wxWidgets_CONFIG_OPTIONS ${wxWidgets_CONFIG_OPTIONS} --version=2.8)
+else()
+    set(wxWidgets_CONFIG_OPTIONS ${wxWidgets_CONFIG_OPTIONS} --version=3.0)
+endif()
+
+if(GTK3_API)
+    set(wxWidgets_CONFIG_OPTIONS ${wxWidgets_CONFIG_OPTIONS} --toolkit=gtk3)
+else()
+    set(wxWidgets_CONFIG_OPTIONS ${wxWidgets_CONFIG_OPTIONS} --toolkit=gtk2)
+endif()
+
 # wx2.8 => /usr/bin/wx-config-2.8, /usr/bin/wxrc-2.8
 # lib32-wx2.8 => /usr/bin/wx-config32-2.8, /usr/bin/wxrc32-2.8
 # wx3.0 => /usr/bin/wx-config-3.0, /usr/bin/wxrc-3.0
```

New behaviour if wx2.8 and wx3.0 are installed and WX28_API=TRUE (semi-works)
It detects correctly but APIValidation.cmake says it's wrong.
```
./build.sh --wx28
<deleted>
-- Found wxWidgets: TRUE  
wxWidgets_CONFIG_OPTIONS=--unicode=yes;--version=2.8;--toolkit=gtk2
wxWidgets_FOUND=TRUE
wxWidgets_INCLUDE_DIRS=/usr/lib/i386-linux-gnu/wx/include/gtk2-unicode-release-2.8;/usr/include/wx-2.8
wxWidgets_LIBRARIES=-L/usr/lib/i386-linux-gnu;-pthread;-Wl,-z,relro;;-L/usr/lib/i386-linux-gnu;;;-lwx_baseu-2.8;-lwx_gtk2u_core-2.8;-lwx_gtk2u_adv-2.8
wxWidgets_LIBRARY_DIRS=/usr/lib/i386-linux-gnu;/usr/lib/i386-linux-gnu
wxWidgets_DEFINITIONS=_FILE_OFFSET_BITS=64;_LARGE_FILES;__WXGTK__
wxWidgets_DEFINITIONS_DEBUG=
wxWidgets_CXX_FLAGS=-pthread
wxWidgets_USE_FILE=/usr/share/cmake-3.0/Modules/UsewxWidgets.cmake
<deleted>
CMake Error at cmake/ApiValidation.cmake:67 (message):
  Mismatch between wx-config version (3.0.2) and requested WX API (2.8.x)
```

New behaviour if only wx3.0 installed and and WX28_API=TRUE
New behaviour if only wx2.8 installed and and WX28_API=FALSE
It correctly says that we could not find a valid library but ApiValidation ends the build.
```
./build.sh --wx28
-- Could NOT find wxWidgets (missing:  wxWidgets_FOUND) 
wxWidgets_CONFIG_OPTIONS=--unicode=yes;--version=2.8;--toolkit=gtk2
wxWidgets_FOUND=FALSE
wxWidgets_INCLUDE_DIRS=
wxWidgets_LIBRARIES=
wxWidgets_LIBRARY_DIRS=
wxWidgets_DEFINITIONS=
wxWidgets_DEFINITIONS_DEBUG=
wxWidgets_CXX_FLAGS=
wxWidgets_USE_FILE=/usr/share/cmake-3.0/Modules/UsewxWidgets.cmake
CMake Error at cmake/ApiValidation.cmake:67 (message):
  Mismatch between wx-config version (3.0.2) and requested WX API (2.8.x)
===========================================================================
 ./build.sh
-- Could NOT find wxWidgets (missing:  wxWidgets_FOUND) 
wxWidgets_CONFIG_OPTIONS=--unicode=yes;--version=3.0;--toolkit=gtk2
wxWidgets_FOUND=FALSE
wxWidgets_INCLUDE_DIRS=
wxWidgets_LIBRARIES=
wxWidgets_LIBRARY_DIRS=
wxWidgets_DEFINITIONS=
wxWidgets_DEFINITIONS_DEBUG=
wxWidgets_CXX_FLAGS=
wxWidgets_USE_FILE=/usr/share/cmake-3.0/Modules/UsewxWidgets.cm
CMake Error at cmake/ApiValidation.cmake:70 (message):
  Mismatch between wx-config version (2.8.12) and requested WX API (3.0.x)
```

New behaviour if wx2.8 and wx3.0 are installed and WX28_API=FALSE (works)
New behaviour if only wx2.8 installed and and WX28_API=TRUE (works)
New behaviour if only wx3.0 installed and and WX28_API=FALSE (works)

I deleted my gtk3 version of wxwidgets but:
New behaviour if wx2.8 and wx3.0 are installed and WX28_API=FALSE,GTK3_API=TRUE
```
./build.sh --gtk3
-- Could NOT find wxWidgets (missing:  wxWidgets_FOUND) 
wxWidgets_CONFIG_OPTIONS=--unicode=yes;--version=3.0;--toolkit=gtk3
wxWidgets_FOUND=FALSE
wxWidgets_INCLUDE_DIRS=
wxWidgets_LIBRARIES=
wxWidgets_LIBRARY_DIRS=
wxWidgets_DEFINITIONS=
wxWidgets_DEFINITIONS_DEBUG=
wxWidgets_CXX_FLAGS=
wxWidgets_USE_FILE=/usr/share/cmake-3.0/Modules/UsewxWidgets.cmake

CMake Error at cmake/ApiValidation.cmake:57 (message):
  Your current WxWidget version doesn't support GTK3.  Please use
  -DGTK3_API=FALSE option

```


Basically with the new patch
WX_vs_GTK3()
WX_version()
are not needed and only
WX_vs_SDL()
is needed.

Also it works even if it finds an old wx-config
```
# update-alternatives --set wx-config /usr/lib/i386-linux-gnu/wx/config/gtk2-unicode-release-2.8
# wx-config --version
2.8.12
# ./build.sh
<deleted>
-- Found wxWidgets: TRUE  
wxWidgets_CONFIG_OPTIONS=--unicode=yes;--version=3.0;--toolkit=gtk2
wxWidgets_FOUND=TRUE
wxWidgets_INCLUDE_DIRS=/usr/lib/i386-linux-gnu/wx/include/gtk2-unicode-3.0;/usr/include/wx-3.0
wxWidgets_LIBRARIES=-L/usr/lib/i386-linux-gnu;-pthread;;;-lwx_baseu-3.0;-lwx_gtk2u_core-3.0;-lwx_gtk2u_adv-3.0
wxWidgets_LIBRARY_DIRS=/usr/lib/i386-linux-gnu
wxWidgets_DEFINITIONS=_FILE_OFFSET_BITS=64;WXUSINGDLL;__WXGTK__
wxWidgets_DEFINITIONS_DEBUG=
wxWidgets_CXX_FLAGS=-pthread
wxWidgets_USE_FILE=/usr/share/cmake-3.0/Modules/UsewxWidgets.cmake
<deleted>
CMake Error at cmake/ApiValidation.cmake:70 (message):
  Mismatch between wx-config version (2.8.12) and requested WX API (3.0.x)
```

**Comment by micove** [comment]
Also, if we get really picky we don't need to test for wxWidgets_wxrc_EXECUTABLE since I believe we don't use it and any version of the compiler would work too. I only left it because the old code tested for it but if could be simplified by removing it.

**Comment by micove** [comment]
Okay, I removed
WX_vs_GTK3()
WX_version()

Squashed it into commit 2.
Also I changed commit 2 to use list(APPEND) since wxWidgets_CONFIG_OPTIONS is a list and looks cleaner than a long set(). Behavior stays the same.

I did a small test by adding
```
message("wxWidgets_wxrc_EXECUTABLE=${wxWidgets_wxrc_EXECUTABLE}")
```
```
#rm /usr/bin/wxrc
#./build.sh
-- Found wxWidgets: TRUE  
wxWidgets_CONFIG_OPTIONS=--unicode=yes;--version=3.0;--toolkit=gtk2
wxWidgets_FOUND=TRUE
wxWidgets_INCLUDE_DIRS=/usr/lib/i386-linux-gnu/wx/include/gtk2-unicode-3.0;/usr/include/wx-3.0
wxWidgets_LIBRARIES=-L/usr/lib/i386-linux-gnu;-pthread;;;-lwx_baseu-3.0;-lwx_gtk2u_core-3.0;-lwx_gtk2u_adv-3.0
wxWidgets_LIBRARY_DIRS=/usr/lib/i386-linux-gnu
wxWidgets_DEFINITIONS=_FILE_OFFSET_BITS=64;WXUSINGDLL;__WXGTK__
wxWidgets_DEFINITIONS_DEBUG=
wxWidgets_CXX_FLAGS=-pthread
wxWidgets_USE_FILE=/usr/share/cmake-3.0/Modules/UsewxWidgets.cmake
wxWidgets_wxrc_EXECUTABLE=wxWidgets_wxrc_EXECUTABLE-NOTFOUND
```

The resource compiler was not found wxWidgets_wxrc_EXECUTABLE-NOTFOUND
and it compiled since not finding wxrc does not trigger wxWidgets_FOUND=FALSE.

**Comment by gregory38** [comment]
I think, useless function in cmake/ApiValidation.cmake can be removed too.

**Comment by micove** [comment]
Oh, okay was not sure if you still wanted the dead code there just in case.

**Comment by micove** [comment]
Done remove the 2 functions, the wx_gtk3_c_code, and an empty line.

**Comment by gregory38** [comment]
IMHO git history is enough :)

**Pull request merged**
