### PR TITLE
Improve texshuffle detection

### PR DESCRIPTION
**Pull request by gregory38**
This code improve the detection of texture shuffle effect. It seems to be fine on my limited testcase.

Could you do a quick test on your side too.

@refractionpcsx2 could you share a build to @prafullpcsx2

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Ill compile it and link a build in a mo :)  love the naming "not_really_16bits", that's the kinda thing i do lol. At least it makes sense :)

**Comment by refractionpcsx2** [comment]
Here we go, Windows SSE2 build: http://www.filedropper.com/gsdx32-sse2-imp-texshuf

**Comment by prafullpcsx2** [comment]
It certainly improves the things a little bit, the messed up half screen doesn't come up after pressing start button ingame now. But the closeup camera shots are still messed up. GS dump attached.
http://www.filedropper.com/showdownload.php/ricky10-7

rickyproblem

**Comment by gregory38** [comment]
The new version seem to work with the gs dump. Could you retry it? And test other game too.

**Comment by prafullpcsx2** [comment]
I will retry as soon as @refractionpcsx2 shares new build here.

**Comment by refractionpcsx2** [comment]
I'll do one later tonight, i have a gig with my band so it may be gone 11pm GMT by the time i get to it.

**Comment by refractionpcsx2** [comment]
Sorry for the delay, here's the build http://www.filedropper.com/gsdx32-sse2-imp-texshuf2

**Comment by prafullpcsx2** [comment]
Awesome stuff @gregory38. It's fixed now. :) Is there any chance to fix/hackfix texture corruption issue with this game now? Is it similar to fbmask problems we had with fifa games? Thanks for the build @refractionpcsx2

**Comment by gregory38** [comment]
It is a mipmap issue. You have the same issue on SW renderer if you disable mipmap. Sorry I won't fix it soon.

**Pull request merged**
