### PR TITLE
Remove cheats file from redundant folder

### PR DESCRIPTION
**Pull request by FlatOutPS2**
Persona 4 cheats file and the cheats folder a redundant, as the
installer doesn't use this folder/file, but creates a seperate cheats folder
in My Documents/PCSX2 and the Binary release creates a cheats folder the
first time you start up PCSX2.

This can also confuse users of the installer package, as shown here: http://forums.pcsx2.net/thread-54286.html

### CODE REVIEW

**Comment by karasuhebi** [comment]
In dev builds, portable mode is enabled by default which means PCSX2 wouldn't create a cheats folder in the user's profile. Just because you don't use it doesn't mean it's redundant.

**Comment by FlatOutPS2** [comment]
> In dev builds, portable mode is enabled by default which means PCSX2 wouldn't create a cheats folder in the user's profile. Just because you don't use it doesn't mean it's redundant.

But it will still create the cheats folder the first time you start PCSX2, just like it creates the other folders like cheats_ws, inis, etc.

**Comment by karasuhebi** [comment]
Fair point. I take back my objection then.

**Comment by turtleli** [comment]
Anyone have objections to the file being removed? I'll merge tomorrow if there's no complaints.

**Pull request merged**
