### PR TITLE
Replace ScopedArray with unique_ptr

### PR DESCRIPTION
**Pull request by turtleli**
Both do the same thing, so let's just use unique_ptr now that the compilers we support have decent C++11 support.

### CODE REVIEW

**Comment by gregory38** [comment]
Hum, did you look to replace `ScopedPtr` too?

**Comment by gregory38** [comment]
And I think it would be better to have a global/general include somewhere to include all the C++ stuff (or maybe at least add the <memory> include in the scopedptr.h file. The global idea is that we ought code right away without searching all the standard C++ include.

**Comment by turtleli** [comment]
Yes, I plan to replace ScopedPtr too, I PR'd this to see whether there would be any objections to me doing so.

I could probably add any other C++ headers to Dependencies.h, that's where all the other header stuff seems to be.

**Comment by gregory38** [comment]
No objection.

**Pull request merged**
