### PR TITLE
Fix Japanese Title Fix (Not -en) & Speed Hacks

### PR DESCRIPTION
**Pull request by nassau-tk**
### Description of Changes

Fix Trial & Demo titles.
Fix 2games speed hack.
I used the difference tool to edit it to make sure there was no waste.
I'm sorry to bother you all, but please check.
*I'm not touch name-en: about Zero (Fatal Fram series) & options code.
*I got base .yaml latest file  today morinig.
### Rationale behind Changes

I couldn't fix it and thought of giving up. 
However, if this is not a problem, the modification of the Japanese title is almost finished, so I tried again.
I look forward to your support.
*I don't have any Linux-machine. So, I worked only Win-PC.

### CODE REVIEW

**Comment by TellowKrinkle** [comment]
This looks pretty good.  I made a few changes:
- I separated the name changes into a different commit from the speed hacks.

In doing so, it appears you've also removed the `bilinearUpscale: 1 # Smooths out bloom on lights` from `SCES-52033`.  I assume that was an accident?  If so, I'll undo it.

**Comment by nassau-tk** [comment]
> This looks pretty good. I made a few changes:

Oh...Very good Infor for me.
 
> * I separated the name changes into a different commit from the speed hacks.

I'll leave it to you.

> In doing so, it appears you've also removed the `bilinearUpscale: 1 # Smooths out bloom on lights` from `SCES-52033`. I assume that was an accident? If so, I'll undo it.

Sorry, Looks like I didn't check it enough.
Of course, I have no intention of deleting it from the original data.
So, It would be helpful if you could restore it.

**Comment by TellowKrinkle** [comment]
> Of course, I have no intention of deleting it from the original data.
> So, It would be helpful if you could restore it.

I restored it.

**Comment by Berylskid** [comment]
余計なお世話かもしれませんが、これを機にPCSX2のDiscordサーバーに参加してみませんか？
Githubより気軽に質問とかできますし、少数ですが私みたいに日本語できる人もいますよ。

**Comment by nassau-tk** [comment]
> 余計なお世話かもしれませんが、これを機にPCSX2のDiscordサーバーに参加してみませんか？ Githubより気軽に質問とかできますし、少数ですが私みたいに日本語できる人もいますよ。

ありがとうございます！一応Discordは登録してあるんですよ～！
自分は、この程度のテキストいじるレベルしかできないですけどねｗ
もしディスコで見かけたらよろしくお願いします！

**Pull request merged**
