### PR TITLE
GS: Replace separate HW renderers with single shared renderer

### PR DESCRIPTION
**Pull request by tellowkrinkle**
### Description of Changes
Replaces GSRendererOGL and GSRendererDX11 with one shared GSRendererNew and a new RenderHW virtual method on GSDevice

### Rationale behind Changes
- Less split code
- New renderers don't have to duplicate all 1500-ish lines of stuff that was in GSRendererOGL/GSRendererDX11.  The replacement method in GSDevice is usually about 250 lines and much more straightforward.

### Suggested Testing Steps
Please test DX11 and OGL renderers for regressions, I'm sure I accidentally broke stuff

### Future Changes
- Merge GSRendererNew and GSRendererHW (and make GSRendererHW final)

I want to delay this to give time for any existing forks of PCSX2 that have other renderers to migrate to the new interface and PR fixes for any issues that pop up in the process.  Any existing GSRendererHW subclasses should continue to work until this is carried out.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Code-wise looks fine to me, of course pending testing and bug fixing (if any) :)

**Comment by lightningterror** [comment]
Sly 2, Mission impossible, Crash twinsanity shadows are broken on gl, I'd check fbmask/colclip interaction.
[Dumps.zip](https://github.com/PCSX2/pcsx2/files/7717689/Dumps.zip)
.

**Comment by lightningterror** [comment]
Channel shuffle on GT4 seems also pretty broken, both renderers.
[GT4 - channel shuffle 2019.zip](https://github.com/PCSX2/pcsx2/files/7718003/GT4.-.channel.shuffle.2019.zip)

**Comment by lightningterror** [comment]
CS on terminator too.
[terminator3_opaque_wall_1.zip](https://github.com/PCSX2/pcsx2/files/7718042/terminator3_opaque_wall_1.zip)

**Comment by tellowkrinkle** [comment]
OpenGL-only issues should be fixed, it was me not properly incorporating the BlitRect change

I couldn't see any difference for the GT4 one, can you tell me what I'm supposed to be looking for?

**Comment by tellowkrinkle** [comment]
Okay everything's fixed

**Comment by lightningterror** [comment]
And a warning to be taken care of.

https://github.com/PCSX2/pcsx2/runs/4559268130?check_suite_focus=true#step:9:675

**Review by Mrlinkwii — APPROVED** [review]
Works well

**Review by JordanTheToaster — APPROVED** [review]
All good on my collection.

**Review by lightningterror — COMMENTED** [review]
Dithering looks a bit wrong on dx11, feels like the dither matrix is wrong that we receive in shader, difference is a bit harder to spot but it's there.

[Castlevania_shadows.zip](https://github.com/PCSX2/pcsx2/files/7740981/Castlevania_shadows.zip)

**Review by lightningterror — APPROVED** [review]
Aside from the dithering issue, which will be fixed in a follow up commit all other dumps I tested seem fine.
Merge time.

**Pull request merged**
