### PR TITLE
GSVertexTrace::FindMinMax improvements

### PR DESCRIPTION
**Pull request by tellowkrinkle**
*when you spend a bunch of time optimizing a function because you think it accounts for 30% of runtime but that was actually due to the compiler being stupid and not issues with the algorithm*

This PR contains the following changes:

- Prevents clang from optimizing out our denormal-removal shuffles (10x faster than before for people who compile with clang!)
- Run divides on four elements at a time instead of two elements and two useless numbers
- ~~Run per-vertex instead of per-primitive for all things that need to apply to all vertices of a primitive anyways (prevents double-checking vertices in triangle strips, and also reduces pointer chases in the main loop)~~ This broke stuff
- Remove inaccurate stq
  - With the above division improvements, on processors with partially-pipelined division (Ivy Bridge and later, Bulldozer and later), accurate stq is actually faster (according to both IACA of [inaccurate](https://gist.github.com/tellowkrinkle/36124c0871ce3bd1ebdb5d6a7dd5e1b4#file-findminmax00-analysis-hsw-txt) vs [accurate](https://gist.github.com/tellowkrinkle/36124c0871ce3bd1ebdb5d6a7dd5e1b4#file-findminmax01-analysis-hsw-txt) and [LLVM MCA](https://analysis.godbolt.org/z/xqvY64)).  On older CPUs expect performance to be about 2/3 of the old algorithm before taking into account improvements from not double-checking vertices.  
  - ~~There seems to be a check of `accurate_stq` when the OGL backend is deciding whether to use geometry shaders to process sprites, does anyone know if that's important or just something someone threw in there that's okay to remove?~~ Reason found, added as comment

In the end, ignoring clang issues, GSVertexTrace::FindMinMax goes from taking about 3% of MTGS thread runtime to 1.5% on my computer.  (Most of the time was spent doing OpenGL things so if you have a more efficient OpenGL driver it might make more of a difference for you)

### CODE REVIEW

**Comment by orbea** [comment]
This brings the slowdowns on Xenosaga Episode 1 during the third cut scene from ~40-45 fps to ~50-55 fps when using clang11.

**Comment by tellowkrinkle** [comment]
> This brings the slowdowns on Xenosaga Episode 1 during the third cut scene from ~40-45 fps to ~50-55 fps when using clang11.

Curious, after this patch, are clang builds slower than gcc builds here?

**Comment by frymezim** [comment]
@iMineLink or @gregory38 might be able to help review this pull request.

**Comment by orbea** [comment]
> Curious, after this patch, are clang builds slower than gcc builds here?

I tested this again with commit https://github.com/PCSX2/pcsx2/commit/88983caaba01ad69d90569ca16f1267977219fca in the first slowdown which starts in the third cutscene right after KOS-MOS appears and lasts for two lines of dialogue.

* gcc-9.3.0 without this PR: 50-55 fps
* clang-11.0.0 without this PR: ~45 fps (Clearly slower than gcc)
* gcc-9.3.0 with this PR: ~50-55 FPS (About the same or maybe slightly slower than without this PR?)
*clang-11.0.0 with this PR: 50-55 fps (Roughly the same as gcc)

I think this PR doesn't make a significant difference when gcc while it clearly improves performance with clang so that it matches gcc better.

**Comment by lightningterror** [comment]
I'd add a prefix to the last commit `gsdx-ogl:`.

**Comment by lightningterror** [comment]
Would be nice to rename GSdx to GS in commit names as GS was merged.

**Pull request merged**
