### PR TITLE
SPU2: Refactoring for Qt and new features

### LINKED ISSUE #6427: [Feature Request]:  Audio Hotkeys
### Description

Options to Mute, Increase, and Decrease Audio

### Reason

I think it would make things just more convenient. 

### Examples

basically how Duckstation does it, with notification of the current volume level (when things muted, increased,decreased)

### LINKED ISSUE #6912: [BUG]: Moving the volume slider with a game running causes audio screeching
### Describe the Bug

Moving the slider up or down while in a game causes a screeching noise.

### Reproduction Steps

Move the volume slider while a game is running

### Expected Behavior

Volume change should be smooth and not distorted. 

### PCSX2 Revision

pcsx2-v1.7.3241-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### LINKED ISSUE #7268: [Feature Request]: Decrease Lower Limit On Audio Latency (Qt)
### Description

In older versions of PCSX2, you could set the audio latency down to 4ms.
While this still works if you modify the settings directly, the Qt user interface does not allow you to do this.

### Reason

Being able to reduce the audio latency should be possible via the UI rather than through the .ini.
Having a lower audio latency improves responsiveness between the game and the sound effects, and would be useful when emulating rhythm games.

### Examples

Latency set to 15 (Current UI lower bound)
https://user-images.githubusercontent.com/44537737/197370281-01315eac-6c10-4b5d-a93f-a8e8095ebe80.mp4

Latency set to 1 (Done by modifying PCSX2.ini)
https://user-images.githubusercontent.com/44537737/197370360-5d480cb8-38ac-420c-83eb-4fc9c2bc592d.mp4

### LINKED ISSUE #7585: [Feature Request]: Selecting Audio Output Device
### Description

Hello, I'm using PCSX2 nightly 1.7.3714 (555b8efcadd14a1111dc1b784653ab67452c6624) with Qt backend. Emulation works great. Now I want to change the audio output device to my HDMI monitor, but I don't see the options in Audio Settings.

Having option to change output device allows users to change the sound output from the default device (e.g. laptop speakers) to other devices (e.g. HDMI monitor or 3.5mm speakers/headphones) without changing the default output device.

### Reason

Having option to change PCSX2 audio output devices makes switching sound outputs easier. For example, I can route the PCSX2 audio output to HDMI or external speakers while keeping system notification sound and music player at the internal laptop speaker (which is the default device).

### Examples

I use an FL Studio ASIO as an example. this is how their output device selection looks like.

gambar

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Partial cleanup of some of the old gross plugin code.

Adds:
 - Volume control hotkeys.
 - Output device selection.
 - Splits latency control into target latency (timestretcher) and output latency (cubeb).
 - Adds "minimal" latency option for output (cubeb).
 - Direct volume control instead of doing a full config reload.

### Rationale behind Changes

Closes #6912.
Closes #6427.
Closes #7268.
Closes #7585.

### Suggested Testing Steps

 - Test audio output on Windows and Linux, make sure nothing broke.
 - Test new latency and device options.
 - Test new hotkeys.

### CODE REVIEW

**Review by JordanTheToaster — APPROVED** [review]

**Review by Mrlinkwii — APPROVED** [review]

**Comment by bslenul** [comment]
Hey! As mentioned in https://github.com/PCSX2/pcsx2/issues/7600#issuecomment-1368200414 now as soon as you right click > properties any game, it will systematically create the game .ini with this inside:

> [SPU2/Mixing]
FinalVolume = 100

Literally as soon as the properties window appears, so even if you don't touch anything, you'll have the game .ini created.

**Comment by refractionpcsx2** [comment]
That's unrelated from this PR. We see the issue, no need to spam everywhere SPU related.

**Comment by bslenul** [comment]
Ah, I've been asked to test this PR yesterday so I thought it was related, my bad. Although I don't feel like I "spam everywhere", I haven't mentioned my issue anywhere else :p 

Anyway, sorry about that!

**Comment by Fafner1000** [comment]
Hi Stenzek, this commit broke the increase/decrease target speed hotkeys. Any chance you could fix them? Thank you.

**Comment by RedPanda4552** [comment]
@Fafner1000 Not a valid issue, this is likely an issue with your per-game settings. Please use the Discord for support: https://discord.com/invite/TCz3t9k

**Comment by Fafner1000** [comment]
> @Fafner1000 Not a valid issue, this is likely an issue with your per-game settings. Please use the Discord for support: https://discord.com/invite/TCz3t9k

Already talked with a couple of devs in Discord, there is an issue open and we isolated the problem to this commit. You can try yourself, build v1.7.3827 works fine and after this it broke and has been broken since then.

**Pull request merged**
