### PR TITLE
Deffered initialization of GSVector constants

### LINKED ISSUE #999: Accessing Plugins Menu Causes Temporary Freeze on "Enumerating Available Plugins"
Whenever I go to the Plugins menu, PCSX2 temporarily freezes (for as long as 5 minutes at one point - I had to close PCSX2 because it never started responding again.) It appears to freeze when looking for the AVX2 GSdx plugin, but **it is there.** I'm guessing the problem is that my CPU doesn't support the AVX2 extension (it's an Athlon X4 750K and I know for a fact that it doesn't.) The freeze is completely consistent.

CPU: AMD Athlon X4 750K @ 4.1GHz
GPU: AMD Radeon HD 7770
OS: Windows 8.1 x64
RAM: 4GB DDR3

### PR DESCRIPTION
**Pull request by Sergeeeek**
Temporarily fixes #999 and #1423

### CODE REVIEW

**Comment by ssakash** [comment]
Looks good to me but the problem is, this method won't work when the plugins are renamed. Though it's still effective on preventing those momentary lag / crash issues for newbie users so good job ;)

On the other hand, it would be better to squash your commits.

**Comment by gregory38** [comment]
For me, it isn't a good solution. So it is a no.

The main issue is call of AVX instruction in global constructor.
* first solution is to defer object constructor
* second solution is to dedicated constructor that don't use AVX for the global constructor. For example using init-list.
* Anothers solution could be a kind of try { } catch (but I dunno if it could work with invalid instruction. I think there is a special signal handler on linux).

**Comment by ssakash** [comment]
@Sergeeeek 

I think you need to do a ``git rebase upstream/master`` to avoid the extra stuffs on your diff.

> For me, it isn't a good solution. So it is a no.

Yes, it isn't an ideal solution but I think it's a good temporary solution to avoid issues like #1423 for people who try out the latest development builds. Either way, It's your choice if this gets merged (or) not.

**Comment by Sergeeeek** [comment]
Ok, I fixed the commits. Yeah I think it's a good temp solution, meanwhile I'll work on defering initialization of globals.

**Comment by turtleli** [comment]
> second solution is to dedicated constructor that don't use AVX for the global constructor. For example using init-list.

I tried this a few days ago using some QEMU VMs. It worked on Windows but not on Linux. I think it's because vector instructions are used to do floating point operations. gdb caught a SIGILL signal and the backtrace indicated it was initialising a GSVector4 with floats. I don't know if there are more issues on Linux.

**Comment by FlatOutPS2** [comment]
This issue is most affecting users of the stable 1.4.0. So I don't think this temporary solution will help many people. I'd say it's better to just properly fix this eventually.

**Comment by Sergeeeek** [comment]
Is it ok to get rid of some constants in GSVector like ps0123? They are accessed only through getter functions anyway.

**Comment by gregory38** [comment]
Need to check the generated code but I'm afraid it will create extra instruction to generate the new data instead to use the address only.

**Comment by Sergeeeek** [comment]
@gregory38 I could make them static in the function, they shouldn't be initialized before DllMain.

**Comment by gregory38** [comment]
Again, need to check generated code ;) But I'm not sure static is free. 

Why not just use an empty default constructor. And during the GSInit (after the sse check), populate the content of the variable with the good value.

**Comment by Sergeeeek** [comment]
Ok, so I did that, but when the AVX2 plugin loads and isn't supported it still crashes it :sob:

It doesn't crash when I compile in Debug-AVX2 though, so I assume that's because of compiler optimizations?

**Comment by turtleli** [comment]
I assume you are using Windows. CRC::m_map uses an unordered_map, and vector instructions are used when that is initialised (at least when VS2015 is used).

**Comment by Sergeeeek** [comment]
@turtleli yes, I'm on windows. So there are 2 solutions: make that class a singleton or put m_map into CRC::Lookup() as a static variable. Which one would be better?

**Comment by turtleli** [comment]
static would probably be easier if it works.

**Comment by gregory38** [comment]
CRC::Lookup is only called once at the init. I'm not even sure the map is useful. Anyway an ordered map will be more than enough (or even a vector 500 cmp won't hurt any modern CPU).

**Comment by Sergeeeek** [comment]
I moved m_map into Lookup, but it still crashes.

**Comment by gregory38** [comment]
where ?

I'm afraid that most/all global variable must be removed/deferred :(

Here a dump of the global init symbol of master gsdx
```
00033cd7 <_GLOBAL__sub_I_gl_BlendColor>:
00033e9b <_GLOBAL__sub_I__ZN7GLState3fboE>:
00034e03 <_GLOBAL__sub_I_PSEgetLibType>:
00035e71 <_GLOBAL__sub_I__ZN15GPUDrawScanlineC2Ev>:
0004179b <_GLOBAL__sub_I__ZN28GPUDrawScanlineCodeGeneratorC2EPvjS0_j>:
000498ea <_GLOBAL__sub_I__ZN14GPULocalMemory6m_xxxaE>:
0004a5c0 <_GLOBAL__sub_I__ZN11GPURendererC2EP8GSDevice>:
0004c305 <_GLOBAL__sub_I__ZN13GPURendererSWC2EP8GSDevicei>:
000512d3 <_GLOBAL__sub_I__ZN25GPUSetupPrimCodeGeneratorC2EPvjS0_j>:
000533c2 <_GLOBAL__sub_I__ZN8GPUStateC2Ev>:
000560b6 <_GLOBAL__sub_I_gsopen_done>:
0005637a <_GLOBAL__sub_I_GSAlignedClass.cpp>:
000564cc <_GLOBAL__sub_I__ZN7GSBlock9m_r16maskE>:
00056d74 <_GLOBAL__sub_I__ZN9GSCaptureC2Ev>:
0005950a <_GLOBAL__sub_I__ZN6GSClutC2EP13GSLocalMemory>:
00059d36 <_GLOBAL__sub_I__ZN12GSCodeBufferC2Ej>:
0005a36e <_GLOBAL__sub_I__ZN3CRC7m_gamesE>:
0005baf9 <_GLOBAL__sub_I__ZN8GSDeviceC2Ev>:
0006b416 <_GLOBAL__sub_I__ZN10GSDeviceSWC2Ev>:
0006b613 <_GLOBAL__sub_I__ZN12GSDeviceNull6CreateEP5GSWnd>:
0006bb27 <_GLOBAL__sub_I__ZN11GSDirtyRectC2Ev>:
0006bfe5 <_GLOBAL__sub_I__ZN16GSDrawingContext16GetSizeFixedTEX0ERK9GSVector4bb>:
0006d48a <_GLOBAL__sub_I__ZN14GSDrawScanlineC2Ev>:
000793fb <_GLOBAL__sub_I__ZN27GSDrawScanlineCodeGenerator6m_testE>:
0007a017 <_GLOBAL__sub_I_GSDrawScanlineCodeGenerator.x86.avx.cpp>:
0007aab3 <_GLOBAL__sub_I_GSDrawScanlineCodeGenerator.x86.avx2.cpp>:
0007b54f <_GLOBAL__sub_I_GSDrawScanlineCodeGenerator.x64.cpp>:
0008f97e <_GLOBAL__sub_I__ZN27GSDrawScanlineCodeGenerator8GenerateEv>:
00090dfd <_GLOBAL__sub_I_GSDrawScanlineCodeGenerator.x64.avx.cpp>:
00091220 <_GLOBAL__sub_I__ZN6GSDumpC2Ev>:
00091cbc <_GLOBAL__sub_I_GSFunctionMap.cpp>:
00096486 <_GLOBAL__sub_I_s_crc_hack_level>:
0009839c <_GLOBAL__sub_I__Z10AddTooltipP10_GtkWidgeti>:
000a0d70 <_GLOBAL__sub_I__ZN13GSLocalMemory12pageOffset32E>:
000b76dc <_GLOBAL__sub_I__ZN10GSDumpFileC2EPc>:
000b7ce5 <_GLOBAL__sub_I__ZN9GSPerfMonC2Ev>:
000b857f <_GLOBAL__sub_I__ZN5GSPng8SaveFileERKSsNS_6FormatEPhS3_iiiibb>:
000bc09c <_GLOBAL__sub_I__ZN16GSRasterizerData9s_counterE>:
000bf4bf <_GLOBAL__sub_I__ZN10GSRendererC2Ev>:
000c020d <_GLOBAL__sub_I_GSRendererCL.cpp>:
000c762d <_GLOBAL__sub_I__ZN12GSRendererHWC2EP14GSTextureCache>:
000cae74 <_GLOBAL__sub_I_GSRendererNull.cpp>:
000cc00c <_GLOBAL__sub_I__ZN13GSRendererOGLC2Ev>:
000d79b8 <_GLOBAL__sub_I__ZN12GSRendererSWC2Ei>:
000d8b7d <_GLOBAL__sub_I__Z14dialog_messageiPb>:
000d9ae9 <_GLOBAL__sub_I__ZN24GSSetupPrimCodeGenerator7m_shiftE>:
000da705 <_GLOBAL__sub_I_GSSetupPrimCodeGenerator.x86.avx.cpp>:
000db1a1 <_GLOBAL__sub_I_GSSetupPrimCodeGenerator.x86.avx2.cpp>:
000dbc3d <_GLOBAL__sub_I_GSSetupPrimCodeGenerator.x64.avx.cpp>:
000e719d <_GLOBAL__sub_I__ZN24GSSetupPrimCodeGenerator8GenerateEv>:
000e7c39 <_GLOBAL__sub_I_GSSetupPrimCodeGenerator.x64.cpp>:
000e8d5e <_GLOBAL__sub_I__ZN11GSShaderOGLC2Eb>:
000f2041 <_GLOBAL__sub_I__ZN7GSStateC2Ev>:
000feef9 <_GLOBAL__sub_I_blockTable32>:
000fefed <_GLOBAL__sub_I__ZN9GSTextureC2Ev>:
00105d81 <_GLOBAL__sub_I_s_IS_OPENGL>:
00107fa1 <_GLOBAL__sub_I__ZN16GSTextureCacheSWC2EP7GSState>:
00109df1 <_GLOBAL__sub_I__ZN17GSTextureCacheOGLC2EP10GSRenderer>:
0010b133 <_GLOBAL__sub_I__ZN7PboPool8m_bufferE>:
0010b24a <_GLOBAL__sub_I__ZN13GSTextureNullC2Ev>:
0010b5e3 <_GLOBAL__sub_I__ZN11GSTextureSWC2Eiii>:
0010b758 <_GLOBAL__sub_I__ZN8GSThreadC2Ev>:
0010ca71 <_GLOBAL__sub_I__ZN6GSUtil10GetLibNameEv>:
0010cf8d <_GLOBAL__sub_I__ZN10GSVector4i5m_xffE>:
0010e2b6 <_GLOBAL__sub_I__ZN13GSVertexTrace8s_minmaxE>:
00116cc2 <_GLOBAL__sub_I__ZN7GSWndGL18PopulateGlFunctionEv>:
001175bc <_GLOBAL__sub_I__ZN8GSWndOGLC2Ev>:
001176a2 <_GLOBAL__sub_I_GSWndEGL.cpp>:
0011ff5f <_GLOBAL__sub_I__ZN7GSdxApp12LoadResourceEiRSt6vectorIhSaIhEEPKc>:
00121ac8 <_GLOBAL__sub_I__Z6formatPKcz>:
```
FWIW, those functions will dispatch to a `__static_initialization_and_destruction_0` function that will do the various init of the object.

**Comment by turtleli** [comment]
g_pos_scale and g_pos_scale2 in GSRendererSW.cpp still needs to have initialisation deferred.

**Comment by gregory38** [comment]
What is the status ?

**Comment by Sergeeeek** [comment]
Sorry, I've been kinda busy lately. If somebody wants to they can finish it.

2016-07-22 19:40 GMT+03:00 Gregory Hainaut <notifications@github.com>:

**Comment by gregory38** [comment]
@turtleli do you think we can merge current PR (with commit squashed) and then with add the missing stuff.

**Comment by turtleli** [comment]
No. There's at least one bug in the changes.

I'll probably work on this in a few days time to see if I can get it to work on both Windows and Linux.

**Comment by gregory38** [comment]
Ok. You're the man :+1: Thanks.

This way, I can look to improve a bit onepad. (aka transfuse lilypad PS2 state management)

**Comment by turtleli** [comment]
Closing - superseded by #1477.

**Pull request closed without merging**
