### PR TITLE
Allow user define wxWidgets_CONFIG_EXECUTABLE

### PR DESCRIPTION
**Pull request by nE0sIghT**
Recently added stuff for wxWidgets search on Arch Linux breaks compilation on Gentoo. This change allows user to pass wxWidgets_CONFIG_EXECUTABLE variable to cmake and to bypass Arch Linux stuff.

### CODE REVIEW

**Comment by micove** [comment]
How did it break?

It should only overwrite the user input if it finds BOTH files.  The only ways that I could think of right now it could "break" compilation are if you do stuff like:
1. Have both versions installed and give incompatible options:
-DWX28_API=FALSE and do -DwxWidgets_CONFIG_EXECUTABLE="/usr/bin/wx-config-2.8"
since WX28_API overrides the user input which was erroneous. This case should trigger the new APIvalidation.cmake before even reaching this if-block and stop the compilation.
OR
2. Try to use a local copy in a custom path with a valid one in the system's path ("/usr/bin/wx-config-3.0" and "/usr/bin/wxrc-3.0")
-DWX28_API=FALSE and do -DwxWidgets_CONFIG_EXECUTABLE="/foo/local/bin/wx-config-3.0"
which would be valid but most of the dependency searching would break in this case.

I'm guessing the 1st case happened but I could be missing something. The 2nd case should not cause build failure.

What I did find is that it's missing a wx3.0, IF-block but should not cause a failure to build if the user used -DwxWidgets_CONFIG_EXECUTABLE.
```
+        if(NOT WX28_API AND EXISTS "/usr/bin/wx-config-3.0" AND EXISTS "/usr/bin/wxrc-3.0")
+            set(wxWidgets_CONFIG_EXECUTABLE "/usr/bin/wx-config-3.0")
+            set(wxWidgets_wxrc_EXECUTABLE "/usr/bin/wxrc-3.0")
        elseif(WX28_API AND EXISTS "/usr/bin/wx-config-2.8" AND EXISTS "/usr/bin/wxrc-2.8")
            set(wxWidgets_CONFIG_EXECUTABLE "/usr/bin/wx-config-2.8")
            set(wxWidgets_wxrc_EXECUTABLE "/usr/bin/wxrc-2.8")
        endif()
```
Seems like Gentoo changes the file name on wx3.0
```
http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/x11-libs/wxGTK/files/wxGTK-3.0.0.0-collision.patch?revision=1.1&view=markup
```

Also, If we are going to check for user input might as well check for both. Although using any wxrc should be safe.
```
if(NOT DEFINED wxWidgets_CONFIG_EXECUTABLE AND NOT DEFINED wxWidgets_wxrc_EXECUTABLE )
```
or
```
if(NOT DEFINED wxWidgets_CONFIG_EXECUTABLE OR NOT DEFINED wxWidgets_wxrc_EXECUTABLE )
```
depending on how strict we want to be.

**Comment by nE0sIghT** [comment]
First of all as i see now this PR is useless because passing wxWidgets_CONFIG_EXECUTABLE works without this change.

Here is failed build log: https://bpaste.net/show/3fd7d81d12e7
Strange here is:
```
-- Cross compilation is disabled.
-- Compiling a i386 build on a x86_64 host.
```
CMAKE_CROSSCOMPILING not defined and 64 bit wx-config detected and used as i think.
I do not pass CMAKE_TOOLCHAIN_FILE nor CMAKE_CROSSCOMPILING to cmake - should that must be autodetected?

Build works with passing correct wxWidgets_CONFIG_EXECUTABLE

**Comment by micove** [comment]
That is trying to cross compile amd64 to i386 but is picking up the 64bit libraries.

change
```
-DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999_build/gentoo_toolchain.cmake
```
to 
```
-DCMAKE_TOOLCHAIN_FILE=CMAKE_TOOLCHAIN_FILE=cmake/linux-compiler-i386-multilib.cmake
```

and it should say cross compilation enabled and pick the correct libraries.

Also I'm not sure what name gentoo uses for wx-config

If it's not /usr/bin/wx-config32-2.8
If it's not /usr/bin/wx-config32-3.0

You might need to do somethng like
 -DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config-2.8-32
-DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config-3.0-32

Whatever the correct name is,

**Comment by nE0sIghT** [comment]
Thanks for pointing to right direction.
Overriding CMAKE_TOOLCHAIN_FILE for amd64 prevents build failure.

**Pull request closed without merging**
