### PR TITLE
Update pthreads to 2.9.1

### PR DESCRIPTION
**Pull request by micove**
Update pthreads from 2.8.0 to 2.9.1.

Version 2.8.0 is from 2006 and was lacking 64bit support. I tested the 4 plugins + core and they worked like before. I also ran the test suite on the release version and got 
```
ALL STATIC TESTS DONE.
```
which is the success message for the static library version. The old one did not pass the tests.

The complete 3rdparty folder should now compile in x64 (after I update some of the other projects).

### CODE REVIEW

**Comment by avih** [comment]
How much do we still need the local pthread changes?

Do you think it would be easier to maintain if instead of `Move the 3 public headers to the include folder` we'd keep them in place but add the pthreads include dir as global?

**Comment by micove** [comment]
>How much do we still need the local pthread changes? They seem fairly minimal.

Well the VS2015 changes are the one I did recently since it wont compile with VS2015. Upstream only tests with VS2013.

I originally did not include the == and != operator. It just required modifying the instances of where it happened which are not that many. I readded it since I was not sure it would break the linux build and require an #ifdef. I think the original intention was avoiding #ifdef's. Saying all that I only found one instance:

```
bool Threading::pxThread::IsSelf() const
{
	// Detached threads may have their pthread handles recycled as newer threads, causing
	// false IsSelf reports.
	return !m_detached && (pthread_self() == m_thread);
}
```
to
```
bool Threading::pxThread::IsSelf() const
{
	// Detached threads may have their pthread handles recycled as newer threads, causing
	// false IsSelf reports.
	return !m_detached && (pthread_self().p == m_thread.p);
}
```

It's just adding ".p" in the worst case
```
#if _WIN32
	return !m_detached && (pthread_self().p == m_thread.p);
#else
	return !m_detached && (pthread_self() == m_thread);
#endif 
```

My linux partition is a little broken at the moment so I could not check it there.

>(the goal of both these questions is to check whether we can use stock pthreads without further mods to make it overall easier to maintain/upgrade)

Yes, I realized. I removed a few things that made it non-std and tried my best to get closer to stock as possible. The header thing is that they have a private "config.h" header and that could pollute the include path since the odds of clashing with something are high. I could just leave them in the topdir and move them in postbuild that would only require a change in the vcxproj, make it easier to upgrade and avoid the pollution.

**Comment by micove** [comment]
Well, I just checked the Linux headers file in glibc
```
/* Thread identifiers.  The structure of the attribute type is not
   exposed on purpose.  */
typedef unsigned long int pthread_t;
```

Can't do ".p" in Linux. It would require ifdef's

Also, upstream recommends not using SEH and just using the default exception handling but I left it using Async SEH because hopefully there was a good reason PCSX2 was using it. SEH seems to be a little buggy. Upsteam has the more technical reasons in the README/FAQ files.

**Comment by avih** [comment]
Interesting.

The VS2015 change - so what happens without those two tests? does it not get `HAVE_STRUCT_TIMESPEC` from elsewhere? and if not, how does that hurt us? break the build? performs sub-optimally? Regardless though, it would hopefully get fixed upstream, and when that happens we'll drop it.

The `IsSelf` thingy, do you know why it should be tested differently for windows/linux? even if they do test differently, my opinion is that the fix should not be at the 3rd party code. But then again, it's a pretty small fix.

I agree that having global but pthreads specific `config.h` is annoying, and I also not super in favor of post build copying. Let's keep it as is (moved/copied).

Anyway, nothing is major here, and I think we can merge as is. But maybe adding a small text file `pcsx2_update_pthreads.txt` with 3 lines explaining the steps for the next upgrade could be helpful.

Thanks for looking into it. Merge when you see fit :)

**Comment by avih** [comment]
Or maybe add this info as part of the commit messages. I.e. why are the headers copied, and the reasoning behind the local changes.

**Comment by micove** [comment]
Timespec is in the standard but MS added it in VS2015 so it was redefinition error and it would not compile. The performance is the same since the local definition in pthreads is the same as the one from MS.

**Comment by micove** [comment]
Got trigger happy there and forgot to answer the rest

>The IsSelf thingy, do you know why it should be tested differently for windows/linux? even if they do test differently, my opinion is that the fix should not be at the 3rd party code. But then again, it's a pretty small fix.

In Linux the values compared are integers while in Windows is s structure. Therefore == works in Linux by default while in Windows you need to compare the element in the structure.

>Anyway, nothing is major here, and I think we can merge as is. But maybe adding a small text file pcsx2_update_pthreads.txt with 3 lines explaining the steps for the next upgrade could be helpful.

Okay, I will add it in the commit message. I redid the commits a few times and started getting lazy with the commit messages.

**Comment by micove** [comment]
Commit 1 is now a untouched dump of the upstream sources.
Commit 2 now includes the moving of files and a updated commit message to reflect this.
Commit 3 is the same as before.

I also reduced the delta since modifying config.h was not really needed and adding the timespec thing only on pthread.h is enough. 

I will test again and merge unless  there is an objection or someone wants to change the SEH thing.

**Comment by avih** [comment]
@sudonim1 @gregory38 , thoughts on the SEH thingy?

Otherwise looks good to me.

**Comment by micove** [comment]
Apparently, it was also needed in config.h. There was a reason I did it yesterday. Okay, it's now equivalent to the one I originally did and tested. The only changes from the original are the improved commit messages and that I moved the include stuff to the second commit.

For the SEH thing this is an excerpt from the FAQ
```
Q 2	Which of the several dll versions do I use?
---	or,
	What are all these pthread*.dll and pthread*.lib files?

Simply, you only use one of them, but you need to choose carefully.

The most important choice you need to make is whether to use a
version that uses exceptions internally, or not (there are versions
of the library that use exceptions as part of the thread
cancellation and cleanup implementation, and one that uses
setjmp/longjmp instead).

There is some contension amongst POSIX threads experts as
to how POSIX threads cancellation and exit should work
with languages that include exceptions and handlers, e.g.
C++ and even C (Microsoft's Structured Exceptions).

The issue is: should cancellation of a thread in, say,
a C++ application cause object destructors and C++ exception
handlers to be invoked as the stack unwinds during thread
exit, or not?

There seems to be more opinion in favour of using the
standard C version of the library (no EH) with C++ applications
since this appears to be the assumption commercial pthreads
implementations make. Therefore, if you use an EH version
of pthreads-win32 then you may be under the illusion that
your application will be portable, when in fact it is likely to
behave very differently linked with other pthreads libraries.

Now you may be asking: why have you kept the EH versions of
the library?

There are a couple of reasons:
- there is division amongst the experts and so the code may
  be needed in the future. (Yes, it's in the repository and we
  can get it out anytime in the future, but ...)
- pthreads-win32 is one of the few implementations, and possibly
  the only freely available one, that has EH versions. It may be
  useful to people who want to play with or study application
  behaviour under these conditions.
```

Basically only pthreads4w provides SEH everything else uses _CLEANUP_C.

Also this 
```
It is recommended that you let pthread.h use it's default __CLEANUP_C
for both library and application builds. That is, don't define any of
the above, and then link with pthreadVC.lib (MSVC or MSVC++) and
libpthreadGC.a (MinGW GCC or G++). The reason is explained below, but
another reason is that the prebuilt pthreadVCE.dll is currently broken.
Versions built with MSVC++ later than version 6 may not be broken, but I
can't verify this yet.
```
and
```
Use of other than the "C" version of the library is now discouraged.
That is, the "C++" version fails some tests and does not provide any
additional functionality.
```

Does not give me confidence in the SEH code path. I left it there since PCSX2 always been using SEH.

**Comment by micove** [comment]
MS documentation
https://msdn.microsoft.com/en-us/library/1deeycx5.aspx
```
If you use /EHa, the image may be larger and might perform less well
because the compiler does not optimize a try block as aggressively.
It also leaves in exception filters that automatically call the
destructors of all local objects even if the compiler does not see any
code that can throw a C++ exception. This enables safe stack unwinding
for asynchronous exceptions as well as for C++ exceptions. When you use
/EHs, the compiler assumes that exceptions can only occur at a throw
statement or at a function call. This allows the compiler to eliminate
code for tracking the lifetime of many unwindable objects, and this can
significantly reduce code size.

We recommend that you not link objects compiled by using /EHa together
with objects compiled by using /EHs in the same executable module. If you
have to handle an asynchronous exception by using /EHa anywhere in your
module, use /EHa to compile all the code in the module. You can use
structured exception handling syntax in the same module as code that's
compiled by using /EHs, but you can’t mix the SEH syntax with try, throw,
and catch in the same function.

Use /EHa if you want to catch an exception that's raised by something
other than a throw.
```


Anyway the change is trivial
```
--- a/common/vsprops/pthreads.props
+++ b/common/vsprops/pthreads.props
@@ -3,11 +3,7 @@
   <ItemDefinitionGroup>
     <ClCompile>
       <AdditionalIncludeDirectories>$(SolutionDir)3rdparty\pthreads4w\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
-      <PreprocessorDefinitions>PTW32_STATIC_LIB;__CLEANUP_SEH;%(PreprocessorDefinitions)</PreprocessorDefinitions>
-      <ExceptionHandling>Async</ExceptionHandling>
+      <PreprocessorDefinitions>PTW32_STATIC_LIB;%(PreprocessorDefinitions)</PreprocessorDefinitions>
     </ClCompile>
-    <ResourceCompile>
-      <PreprocessorDefinitions Condition="'$(ProjectName)'=='pthreads4w'">__CLEANUP_SEH;%(PreprocessorDefinitions)</PreprocessorDefinitions>
-    </ResourceCompile>
   </ItemDefinitionGroup>
 </Project>
\ No newline at end of file
```

It can be done later. I'm merging the rest since there is no change of the current behavior.

**Comment by avih** [comment]
Thanks, it builds and runs fine :)

Both @sudonim1 and @gregory38 know that PCSX2 uses SEH but not sure what it implies for pthreads. Keeping the same behavior as before is probably the safer approach indeed.

Maybe some day someone will investigate we we can build pthreads without it and stay safe.

**Pull request merged**
