### PR TITLE
cdvdgigaherz: Dual layer DVD fixes

### PR DESCRIPTION
**Pull request by turtleli**
Changes:
 * CDVDgetDualInfo now returns the first layer 1 LSN (logical sector number) instead of the last layer 0 LSN.
 * PTP (Parallel Track Path) DVDs should no longer be recognised as OTP (Opposite Track Path) DVDs.
 * Single layer DVDs are no longer reported as dual layer DVDs and vice versa.

Note: Reading from dual layer DVDs might still be broken (someone please test). However, these changes should be correct if I have correctly understood the internal ISO reader and old CDVD plugin compatibility code in PCSX2.

### CODE REVIEW

**Comment by prafullpcsx2** [comment]
It still doesn't help GT4. May be something else is wrong here? Champions of Norrath is another dual layer game and it also doesn't seem to work for me with cdvdgigaherz (it gives tlb miss).

**Comment by turtleli** [comment]
Ok, so dual layer is still broken. I'll probably just get GT4 and see if I can figure out what else is broken.

**Comment by ramapcsx2** [comment]
This used to work, I'm pretty sure. What happened?

**Comment by FlatOutPS2** [comment]
When loading GT4 disc the logs reads:
" * CDVD: Disk Type: Single-Layer DVD
 * CDVD Disk Open: DVD, Single layer or unknown:"
It doesn't seem to be detected as dual layer.

**Comment by prafullpcsx2** [comment]
@ramapcsx2 : AFAIK it never worked with cdvdgigaherz, even cdvdolio had problems with dual layer discs. peopscdvd is the only cdvd plugin which seems to work. It works with internal iso plugin though.

Can someone recall when and why cdvdgigaherz was chosen as default cdvd plugin and peopscdvd was dropped? I haven't faced any problems with peopscdvd. Only problem with it was It used to be very slow but after the team modded it reading speeds were pretty good.

**Comment by refractionpcsx2** [comment]
Is this somehow related to this issue? http://forums.pcsx2.net/Thread-CDVD-Bug-Report-CDVD-Disk-Type-No-Disc-PAL-CDVD-Gigaherz

**Comment by ramapcsx2** [comment]
Okay, I went over my stack of games and there's no DVD9 title among them. So I only imagined testing this part :p

**Comment by prafullpcsx2** [comment]
@refractionpcsx2 : It might be related because Champions of Norrath is showing the exact problem reported in that thread. It says no disk when using full boot and gives TLB miss on fast boot. Actual issue was discussed here 

http://forums.pcsx2.net/Thread-I-m-getting-TLB-Miss-if-I-use-Gigahertz-CDVD-on-almost-any-game

Something to do with plugin having issues with low level calls to cdvd drive.

**Comment by refractionpcsx2** [comment]
> Can someone recall when and why cdvdgigaherz was chosen as default cdvd plugin and peopscdvd was dropped?

@prafullpcsx2 peops block caching/threading wasn't very good, the experience was a lot less stuttery when using dvdgigaherz, plus it was being actively developed where pete obviously disappeared years ago ;p

**Comment by turtleli** [comment]
> CDVD: Disk Type: Single-Layer DVD

Might be funny Windows ioctl business. I've added a debug commit, if someone could provide me log output from a DVD9 game then I might have an idea of what is happening. I need to figure out whether the ioctl for reading any layer descriptor is failing completely, or just the ioctl for reading the layer 1 layer descriptor is failing.

> CDVD Disk Open: DVD, Single layer or unknown:

@prafullpcsx2 Could you check whether this line shows up when using peopscdvd with a DVD9 game? I think there's some mismatch between what the plugins and old plugin compatibility layer returns and what PCSX2 is expecting. It doesn't seem to affect functionality, but would be nice to fix.

The forum bug I don't have much of a clue on, though it does indeed look like it doesn't like the ioctl stuff.

**Comment by prafullpcsx2** [comment]
@turtleli : Check this http://www.filedropper.com/logs_6

**Comment by turtleli** [comment]
@prafullpcsx2 Thanks for the logs. Could you also use a non-debug build of both PCSX2 and cdvdgigaherz from this PR? Debug builds don't output to stdout/stderr correctly (unless run via the VS debugger I think), so I'm missing a few debug messages. Specifically I'm looking for lines that start with "GIGA", which will appear almost immediately after booting.

Looking at the logs peops has
```
CDVD Disk Open: DVD, Single layer or unknown:
```
while the internal ISO reader has
```
CDVD Disk Open: DVD, Double layer:
```
Main reason is that PCSX2 seems to expect 0 for success, which the ISO reader provides, but not the plugins or compat code, which use 1 for success instead...

**Comment by prafullpcsx2** [comment]
* CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 2) (2763936 sectors)
 * CDVD: Opening drive '\\.\I:'...
GIGA BEFORE layer descriptor 0 fetch
GIGA LAYERS - 1:1
GIGA BEFORE layer descriptor 1 fetch
GIGA SUCCEEDED layer descriptor 1 fetch
 * CDVD: setSpindleSpeed success (11080KB/s)
 * CDVD: IO thread started...
 * CDVD: Disk Type: Double-Layer DVD
 * CDVD: KeepAlive thread started...
(IsoFS) Block 0x10: Primary partition info.
(IsoFS) Filesystem is ISO9660

**Comment by turtleli** [comment]
Well, I found an endian issue. The start sector for DVD-ROM discs should be 0x00030000 for each layer (except for layer 1 of OTP DVDs).  dld.ld.StartingDataSector however has a value of 768 (0x00000300).

I'll deal with it tomorrow.

**Comment by FlatOutPS2** [comment]
Can you check the EndDataSector too? It seems to be wrong as well.

**Comment by turtleli** [comment]
Yeah, that's inverted too (EndLayerZeroSector as well), I should finish typing my full observations next time ;)

The MMC-6 specs (READ DISC STRUCTURE command, Physical Format Information) indicates that the MSB comes first. I assumed Windows would do the byte swapping for us, but it doesn't.

**Comment by turtleli** [comment]
Changes:
 * Fixed sector address endian issues
 * Fixed CDVDGetTOC failure for both DVDs and CDs (someone please check I haven't broken CD games by fixing a bug)
 * Fixed wrong dual-layer DVD track info
 * Fixed DVD layer 1 reading issues
 * Removed unnecessary IOCTL_DVD_READ_STRUCTURE calls when detecting the media type and calculating the layer 1 start LSN
 * Fixed last resort DVD size calculations

I got GT4, and it seems to work for me :)

Side note (bug unrelated to PR) - PCSX2 doesn't terminate properly if I full/fast boot using CDVDgigaherz without a disk inserted.

**Comment by FlatOutPS2** [comment]
I can confirm that GT4 boots fine with the new commit, and the video's work too.

And PCSX2 does indeed not terminate properly when booting on Plugin without a disc inserted.

**Comment by prafullpcsx2** [comment]
GT4 Mounted iso through virtual drive still isn't working. Will check with Actual disk later.

**Comment by prafullpcsx2** [comment]
GT4 works and Champions of Norrath actually gets detected now (without tlb miss errors) but it still doesn't boot and goes directly to PS2 memory card screen.

**Comment by MrCK1** [comment]
@prafullpcsx2 are you running GT4 off of a disk or ISO? I'm still getting stuck at the same spot - must be something on my end :P

**Comment by prafullpcsx2** [comment]
@MrCK1 : If you using iso through virtual disc make sure you mount the .mds file and not .iso file although it works even with mounting  .iso file with cdvdpeops

**Comment by turtleli** [comment]
cdvdpeops uses the same strategy as the ISO reader - it starts from the middle logical sector, then scans for a volume descriptor which is where layer 1 starts. cdvdgigaherz actually reads the layer information from the disc itself, which is why a .mds works and a .iso doesn't - the .mds provides the layer information.

There might be a better strategy than starting from the middle of the disk/ISO:
```
Read Sector 16 (Layer 0 Volume descriptor)
Read bytes 80-83 (Layer 0 sector count in little endian format)
if (disk/ISO sector count > layer 0 sector count) {
    dual layer disc
    layer 1 starting sector = layer 0 sector count
} else if (disk/ISO sector count == layer 0 sector count) {
    single layer dvd
} else {
    funny business going on
}
```
It's out of scope for the PR though.

@MrCK1 Is it an actual disk you're using?

**Comment by prafullpcsx2** [comment]
Time to merge this?

**Comment by MrCK1** [comment]
@turtleli 

No, I've been using an .iso ripped from my disk. I used to read the game directly from the disk, but even then I had to use the same .pnach for it to work.

Maybe I just have a bad copy? The PS2 HW had these issues as well apparently; getting stuck in the same spot after the copyright screen.

**Comment by FlatOutPS2** [comment]
> Maybe I just have a bad copy? The PS2 HW had these issues as well apparently; getting stuck in the same spot after the copyright screen.

Wasn't that an issue with certain PS2 versions, not the actual game? If you reimage it as an .mds it should work.

Or just use the disc like I did.

**Comment by prafullpcsx2** [comment]
You can you winiso to convert it to mds and most probably it will work.

**Pull request merged**
