### PR TITLE
PAD (Windows): Remove DirectInput and Force Hide cursor options. Clean up includes/remove old code

### PR DESCRIPTION
**Pull request by MrCK1**
- This PR will remove the DirectInput API option for PC mice and keyboards. It also gets rid of the "Force Hide" cursor option which is buggy and superseeded by the same option already present in the GS Window options. I ended up taking the time to adjust the GUI a bit but that can be left out of the PR if we don't want that in here.

- Tried to tidy up some of the library includes by moving them to the Global.h header (similar structure to SPU2). Also removed some unused includes and code in certain files.

image

### CODE REVIEW

**Review by GovanifY — APPROVED** [review]
LGTM by me!

**Comment by CookiePLMonster** [comment]
Can DInput for keyboards go too? It kinda only makes sense for gamepads/controllers.

**Comment by MrCK1** [comment]
> 
> 
> Can DInput for keyboards go too? It kinda only makes sense for gamepads/controllers.

I forgot this was still open, I can run it by the rest of the team and I'll remove it if we're OK with that as well. Shouldn't be any issue removing it anyway

**Comment by MrCK1** [comment]
PR has been rebased again with requested changes from @CookiePLMonster . Here is the current GUI state

image

**Review by RedDevilus — APPROVED** [review]
Fix the alignment 🐃 and it's fine as-is

**Pull request merged**
