### PR TITLE
Plugins: Remove PADSSSPSX and xpad.

### PR DESCRIPTION
**Pull request by MrCK1**
Given their inactive state in the project, I am proposing to fully remove the two pad plugins; PADSSSPSX and xpad. 

In my opinion, both plugins have reduced functionality and are currently superseded by Lilypad and Onepad respectively. (Prior to this PR, the two plugins are already disabled in CMake prior to this PR but were still included in the old_plugins solution.)

In addition, I removed zeropad from CMakeLists which was leftover from its' removal in 2011. CDVDiso was also lurking in one of the Linux files so I took care of that as well

I understand that this may be a controversial subject for some; so please let me know if you have comments, suggestions, ect.

### CODE REVIEW

**Comment by lightningterror** [comment]
Smash that purge button.

**Comment by MrCK1** [comment]
Requested change has been pushed. This can be merged in a few hours incase anyone else has comments.

**Comment by lightningterror** [comment]
Maybe we could also purge ZeroGS in the future.

**Comment by MrCK1** [comment]
@lightningterror I have plans for those, but I'm taking baby steps ;)

**Pull request merged**
