### PR TITLE
Qt: Help menu icon fix for macOS user

### PR DESCRIPTION
**Pull request by kamfretoz**
### Description of Changes

macOS's icon requires a special treatment according to @TellowKrinkle and the new help menu icon breaks on the dark theme so here's an attempted fix for it, if you have a better icon replacement please let me know.

This PR also contains yet another smol adjustment to the Cobalt theme (god i hate perfectionism)

### Rationale behind Changes

well...
image

### Suggested Testing Steps

macOS users please give this a go.
Open up the help menu and see if it looks right.

### CODE REVIEW

**Comment by DigitalMajestic** [comment]
The Discord icon is squished but at least it's there.

Screenshot 2023-04-23 at 2 29 02 PM

**Review by stenzek — APPROVED** [review]

**Comment by kamfretoz** [comment]
That should be it 😅

**Comment by TellowKrinkle** [comment]
Are these supposed to have white borders around them?

**Comment by kamfretoz** [comment]
> Are these supposed to have white borders around them?

Yeah, the idea is that because GH logo has poor contrast on the default Dark Fusion theme (mainly on non-macOS systems), we decided to add small white outline around them

The outline was added to GH and Discord logo only, because the discord logo exhibit similar symptoms on few of the other themes

**Comment by TellowKrinkle** [comment]
I don't think the outlines really work at 32x32.  They go from "not visible" to "barely visible" on the matching themes, and they make the icons look worse on any other theme.

The GitHub one we can use the same black/white switching mechanism we have for all the other icons

Not sure what to do about the Discord icon for blue themes though.  Would it make more sense to just use a black/white icon for that as well?  Or see if it's possible to use the rounded background icon on windows/linux and the black one on macOS?

**Comment by RedDevilus** [comment]
Outlines will never fix it, if there was a way to insert custom variations that match best themes beyond just the usual limitation of the white and dark palette might be better.

**Comment by kamfretoz** [comment]
Looks like i will have to make separate icons for each black/white themes in order for them to truly fits in both cases, I'll look into it.

**Pull request merged**
