### PR TITLE
Windows 64-bit compile fixes

### PR DESCRIPTION
**Pull request by turtleli**
This fixes some 64-bit compilation issues on Windows.

### CODE REVIEW

**Comment by ramapcsx2** [comment]
I can't even remember how the sampling profiler would be used. Is it still good for anything?

**Comment by turtleli** [comment]
I'm not sure. I think VS2015 can do the same job. Maybe it can be removed?

**Comment by refractionpcsx2** [comment]
It's still got it :) https://blogs.msdn.microsoft.com/visualstudioalm/2015/10/29/profile-your-cpu-in-the-debugger-in-visual-studio-2015/

**Comment by gregory38** [comment]
On linux, I added "perf event" support (not sure it support all recompiler). But it allow to profile EE JIT block (and potentially you could profile PS2 game). Standard tool only show recompiler 80% but don't give any details. I suspect it was the purpose of this sampling code, but I didn't managed to understand it.

**Comment by turtleli** [comment]
I think the sampling code only gives a rough indication of how much time is spent in the recompilers. Visual Studio provides a very detailed breakdown of where time is spent, so I'm going to remove the code. If the code is needed again it'll still be in the history.

**Comment by ramapcsx2** [comment]
Okay, hope no one misses this ;)

**Comment by gregory38** [comment]
I'm fine to merge it. Do we need more test?

**Pull request merged**
