### PR TITLE
Documentation: Add script to generate PDF documentation from markdown via pandoc

### PR DESCRIPTION
**Pull request by xTVaser**
Used this for a decent PDF template - https://github.com/Wandmalfarbe/pandoc-latex-template

Could have done more with it like made title pages for each PDF, but thought that might have been annoying for users (a blank page to always scroll past). I didn't do a whole lot of formatting or overrode the default templates settings so if there are issues with the generated PDFs call them out and i can try to fix them up.

I included source links to the github repo in each PDF, my rationale being if a user found a problem they could easily PR a fix.  Though this can also be removed if not deemed useful.

Pandoc also has language support, so perhaps that is something that could be looked into in the future for atleast the main configuration guide https://github.com/Wandmalfarbe/pandoc-latex-template#changing-the-document-language though I'm not sure how exactly it works, may not even be useful in the way i think it would be.

### CODE REVIEW

**Comment by lightningterror** [comment]
Is it ready?

**Comment by xTVaser** [comment]
from my perspective yes, but it would be nice to know if people like the PDF format.  I'm not sure if anyone has looked at them yet.

**Comment by RedDevilus** [comment]
Some examples on my end:

image

image

image

Besides a bit much whitespace on start and end of the files, which i don't really mind.

They look good overall as result.

**Comment by RedDevilus** [comment]
Even the bookmarks work as intended:

image

**Review by RedDevilus — APPROVED** [review]

**Comment by tadanokojin** [comment]
I like it

**Review by tadanokojin — APPROVED** [review]

**Comment by tadanokojin** [comment]
> I included source links to the github repo in each PDF, my rationale being if a user found a problem they could easily PR a fix. Though this can also be removed if not deemed useful.

I noticed that you use 1.6.0 branch, so gameindex.md will not exist.

**Comment by Mrlinkwii** [comment]
looking great with the PDF format  
image

**Pull request merged**
