### PR TITLE
Simplify BuildBot and add a helper script for compilation.

### PR DESCRIPTION
**Pull request by micove**
I got a chance to test it and it currently works.

Notes:
- I included the old_plugins.sln since it only adds 1 min of compilation. Should, I remove it from buildbot.xml? Related, I think the old_plugins.sln should either be removed or those 6 plugins + bzip  readded to the main solution since it adds extra complexity and since they are technically "supported" I always end up testing them.

- I just named the user-only file mscompile.cmd. Feel free to suggest a better one. Build.cmd is sorted too close to build.sh and msbuild.cmd would clash with msbuild.exe therefore I just put mscompile.cmd so Explorer.exe sorts it closer to the VS solutions.

- I also lowered the default verbosity from n[ormal] to m[inimal] since it's too chatty. All the important information gets outputted to the two log files which should make error reporting easier to paste.

### CODE REVIEW

**Comment by micove** [comment]
I already tested it the only issue is to get a consensus on old_plugins.sln and maybe change the default portable.ini value to NUL like the bot does.

```
echo Creating empty portable.ini file
type NUL > %env.PCSX2_TARGET_COPY%\portable.ini
```

**Comment by gregory38** [comment]
I think the goal of the old_plugin was kinda drop the old/unsupported plugins. Still useful for us to test a feature but completely useless for users.

**Comment by micove** [comment]
Okay, sort of like the EXTRA_PLUGINS then. I will think about it later to see if it's better to just comment out the line or straight out remove the multiple solution support in the file. If the bot is never going to build them then it's probably better to just remove it since it just adds extra complexity but it's still kind of nice to test that everything builds with just 1 command. Oh,decisions.

**Comment by turtleli** [comment]
I like the changes - I was experimenting with AppVeyor (https://ci.appveyor.com/project/turtleli/pcsx2), I used the buildbot.xml (minus the old_plugins line) and it worked great.

**Comment by micove** [comment]
Hehe, old_plugins get no love.

A nice thing is that using a script to simulate exactly what the build bot was doing (+ old plugins) it took me ~32 mins to compile everything while using the xml took me ~16.The build bot currently takes ~26 minutes so hopefully it goes down to ~13 or better yet 11 min like AppVeyor took (Time Elapsed 00:11:17.1).

**Comment by turtleli** [comment]
Well, I had to remove the old_plugins since zzogl doesn't compile because I don't have the CG toolkit stuff installed, and AppVeyor doesn't seem to have it either.

On a side note - USBqemu exists both on the main solution and the old_plugins.

**Comment by micove** [comment]
Yes, I was thinking about removing it from one solution in the MSVS cleanup branch I'm working on. I only have the plugins to do. I still need confirmation to which solution it should stay in. It's an easy change so I left it until after I finish that branch.

**Comment by avih** [comment]
IMO zzogl should be on old plugins since it's effectively not used anymore, but USBQemu should be at the main solution IMO since it has derivatives which are still being developed (I wouldn't mind having a copy of this one at our repo https://github.com/jackun/USBqemu-wheel ).

**Comment by micove** [comment]
Yeah, we are on the same page. I never intended to move zzogl to the main solution. I was planning on removing USBqemu from old_plugins and leave it on the main solution. I still planned to ask in the appropriate PR before doing/merging it to make sure that was the intended behavior. It ended up being discussed in an unrelated PR.

**Comment by micove** [comment]
Got a chance to work on this a bit. It's probably done.

I commented out the old_plugins line and simplified it a bit as shown in the super originally named "SQUASH ME" commit. I already tested it and debug/devel/release work as intended.

**Comment by bositman** [comment]
Bot builds are now 15mb and include a huge pcsx2.pdb file along with pcsx2.exp and pcsx2.lib on the root of the archive, same in the plugin folder (for each plugin)

**Comment by micove** [comment]
Only, 1187. I was modifying the build steps when that happened.

**Comment by bositman** [comment]
True story :P

**Comment by micove** [comment]
Anyway, I forgot to mention that I had rescheduled 1187 and it's ~5mb now.

@turtleli 
Appveyor is kind of neat since it allows you to generate all 3 configurations as 7z:
https://ci.appveyor.com/project/micove/pcsx2

**Comment by turtleli** [comment]
Yeah, I tried that once with ReleaseAll and DebugAll (before the current buildbot.xml version), it got quite close to the 30 minute time limit. So I went back to only doing the ReleaseAll config.

Appveyor would be really useful for PRs I think, we can have an automatically generated build to get that little bit more of additional testing.

**Comment by micove** [comment]
It seems the timeout limit for free accounts got bumped to 40 minutes. Also using a matrix the timeout applies to the individual jobs and not the sum of the 3 jobs from what I read. The longest job is ReleaseAll at ~12-14 minutes so we stay under the limit by a good margin.

Yes, I set it up to generate all three for when I need to generate a build for others to test. Although debug is kind of broken since I get assertion errors in the menus and stuff so it could be dropped.

**Comment by turtleli** [comment]
Seems you're right on the 40 minute timeout. :)

I don't know what happened with the menus, I think it worked when I was doing the wx3.0 transition but maybe I have bad memory. But yeah, there's plenty of things that trip assertions in the debug builds.

**Comment by turtleli** [comment]
Hmm. The menu assertions might be a Windows 10 thing, my Windows 7 VM has no issues, and I did the wx3.0 transition on Windows 8.1.

**Pull request merged**
