### PR TITLE
GameDB: Beyond good and evil fix 2

### PR DESCRIPTION
**Pull request by atomic83GitHub**
Fix some typo issue with positive.

This PR can be merge.

[skip ci]

### CODE REVIEW

**Comment by ssakash** [comment]
You need to rebase this with the master branch, if you're not sure how to do it, feel free to ask. Just don't close this and open a new PR again. xD

**Comment by atomic83GitHub** [comment]
Yes, I am not sure about how doing this, can you help me on that？

**Comment by ssakash** [comment]
If you rebase now directly to the master branch, you'll have a merge conflict and it'll be a PITA to deal with if you're inexperienced on it. A better solution for a beginner would be to delete your current commit, rebase and then commit the change again.

To do that, open the git shell and enter the commands highlighted in the parenthesis.

1/ Remove your commit first (``git reset --hard HEAD~1``)

2/ Add a new remote for PCSX2 repo (` git remote add real https://github.com/PCSX2/pcsx2`)
**Note:** The name I'm using here is "real", you can use anything you like.

3/ Get the current data of remote repository (``git fetch real``)

4/ Now to do the actual rebase (``git rebase real/master``)

5/ Now just commit your change again (the code currently present in this PR) and then force push it using (``git push -f``) and you're good to go.

If you have any further doubts regarding these commands, feel free to ask. We're more than happy to help you on it. 👍

**Comment by ssakash** [comment]
It might seem a bit complicated at first but it's really easy to get hang of it if you use these commands regularly over the Github application UI.

**Pull request merged**
