### PR TITLE
crc hack for Ponkotsu Roman Daikatsugeki: Bumpy Trot ( Steambot Chronicles JP)

### PR DESCRIPTION
**Pull request by ssakash**

### CODE REVIEW

**Comment by ssakash** [comment]
added CRC hack for the japanese version of steambot chronicles. since, according to bakubaku (forum member) the CRC hack for the US version also fixes the vertical line issue in the Japanese version.

http://forums.pcsx2.net/Thread-Vertical-line-fix-and-crc-hack-for-Bumpy-Trot-Jap-version-of-Steambot-Chronicles

**Comment by avih** [comment]
Thanks!

**Comment by MoochMcGee** [comment]
Why not just fix the underlying issue instead of adding countless amounts of CRC hacks?

**Comment by Bigpet** [comment]
@MoochMcGee why not "just" make a pull request with the fix instead of taking potshots like a petulant child or continue to work on your "better than pcsx2" emulator

**Comment by avih** [comment]
You're welcome to post fixes patches.

**Comment by ssakash** [comment]
well, it's just a temporary fix unless someone manages to find the Underlying issue.

**Comment by avih** [comment]
> well, it's just a temporary fix until someone manages to find the Underlying issue.

This is probably an alias for "forever".

**Comment by pauldacheez** [comment]
And that's why pcsx2 is generally considered dead.

**Pull request merged**
