### PR TITLE
sync with GSdx.ini variable.(fix earlier typo)

### PR DESCRIPTION
**Pull request by ssakash**

### CODE REVIEW

**Comment by ssakash** [comment]
apparently, I had made a Typo on the variable for the round sprite hack. This should fix it :)

**Comment by karasuhebi** [comment]
On GSSettings.cpp, please remove the extra blank lines you added. They should be 83 and 85.

Also, I think line 84 should read as follows:
"Carries **a** total of three states: Unchecked (off), Grayed ~~check box~~ (on for all sprites) **and** **C**hecked ~~box~~ (on for flat sprites)";

For reference, this is your line:
"Carries total of three states, Unchecked (off), Shaded check box (on for all sprites) checked box (on for flat sprites)";

**Comment by gregory38** [comment]
I think it will be better to drop shaded/flat adjective. It is not related. It is related to the texture filtering (linear or nearest).

Honestly I don't care for 2 old values in gsdx.ini. File size won't even be bigger (smallest sector is 4K). Very few people edit the file manually.

**Comment by karasuhebi** [comment]
So what should we call that state for the checkbox? Filled in?

Fair enough, we will leave the GSdx.ini files as is.

**Comment by ssakash** [comment]
@karasuhebi 
The changes are done.
about the checkbox,
I already discussed about the swapping value problem on the three state checkbox on the GSDX thread on the plugin forums. 

@gregory38 
I could still make it as a 2 state checkbox with the values 0/1 for the variables. just let me know if, you think it's fine.

**Comment by karasuhebi** [comment]
@ssakash: Thanks for making those changes. I know you guys discussed it in the GSdx thread, but I didn't agree. I just never got around to posting in the thread explaining why. Which is why I'm doing it now.

**Comment by ssakash** [comment]
so, what's the conclusion ? what should I implement ?

* 2 state checkbox (dropping the flat sprite variant)  (or)  3 state checkbox in the right order ?

I think it would be Ideal to think about this before making the changes, the 3 state check box sounds nice but, sorting the order requires the change of the native format of BS_AUTO3STATE which will mean changing the format of all the other settings which use the three state checkbox. the another method is for gregory to swap the value for functions of the round offset hack.

**Comment by karasuhebi** [comment]
Let's wait for @gregory38 to explain what he meant because we both understood different things. I understood that he was talking about dropping a word from the description, not dropping a state. You understood he was talking about dropping a state. Better wait until he clarifies it.

**Comment by gregory38** [comment]
When you map a texture into a polygon (here a sprite), you have 2 ways to interpolate the texel value (you read texel  coordinate 2.3 not 2 not 3).
Either you use a nearest filter => 2.3 will be come 100% of 2
Either you use a bilinear filter => 2.3 will become 70% of 2, with 30% of 3

Level 1 of this hack only apply to texture that use a nearest filter. The prediction of the behavior remains possible for various draws commands.

Level 2 of this hack apply also to texture that use a bilinear filter. Prediction of mapping of those texture is quite complicated so it is a bonus. Sometime it will work, sometime it will break badly.

I need to remove old code (I miss some left overs).

**Comment by karasuhebi** [comment]
So...what did you mean when you said "drop the shaded/flat adjetive"? Did you mean remove those words from the description? Or did you mean remove a checkbox state?

**Comment by gregory38** [comment]
Remove them from the description, replace them with better word ;)
Flat mean that primitive variable won't be interpolated between the vertex.
Shaded mean that primitive variable will be interpolated between the vertex.

Flat/Shader are uncorrelated of the texture filtering (nearest/linear).

**Comment by karasuhebi** [comment]
Understood. Shaded is talking about the state of the checkbox itself though. Would it be OK to leave that? Or would you rather change it to something else? The Sprite hack and WildArmsOffset hack call it 'half option'. Wanna use that? I prefer saying 'Filled in checkbox'.

**Comment by ssakash** [comment]
okay, I will change the description. though, I fear that the normal users might not understand the meaning.

**Comment by gregory38** [comment]
I think wrong word won't help to improve the understanding. Maybe you don't need to enter into details.

**Comment by karasuhebi** [comment]
In my opinion trying to describe what the two options do to users is a good idea. That way they know what to look for in a game or at least what to expect to see if the hack is working for them. We just need to think hard and find an easy way to describe the basics instead of going into too many details.

**Comment by ssakash** [comment]
If you have some idea on making the description look simple then, feel free to say. :smiley: 

Though, I still think it would be nice if I also add the indepth explanation.

**Comment by karasuhebi** [comment]
I updated my previous comment. Check out the last line of [this comment](https://github.com/PCSX2/pcsx2/pull/528#issuecomment-99913867) for my suggested replacement for the word 'flat'.

**Comment by tsunami2311** [comment]
Why not just call(nearest/linear)  in the description of the states?  which if we call it that no need to swap states around for (check/box)

As for the pull downmenu unless all the hacks states the gsdx uses that has multiple states  are all changed to drop down menu all at the same time, i think it better to just keep it the way it is for Consistency

**Comment by karasuhebi** [comment]
Because level 2 is a 'fully on' option, it applies to both nearest and linear. With my method there's no need to confuse users with words like 'nearest filter' and 'linear filter'. It's just "on for some sprites" and "on for all sprites".

Also there's already no consistency. The MSAA option has a drown-down menu. Might as well make all of the 3-state hacks into drop-down menus. There's only like 3 of them anyway. I'd rather an option take up more space and be less confusing than keeping it as a checkbox and risk confusing the user more.

**Comment by tsunami2311** [comment]
MSAA is the only thing and i dont see this as hack it should be listed in the main GSDX config window JUST like AF/TF so i not sure why it listed as one or ever was. 

everything else in  HW HACK section is though is. Unless the all the hacks that use multiple states  are change to be the same at same time why both? beside at this point think we all can agree we just need the UI function of round sprite to work correctly.

**Comment by karasuhebi** [comment]
MSAA in PCSX2 is a hack. It breaks games. Just ask @Sarania.

I'm not sure what you're saying here. I did suggest that all multiple state hacks be changed to drown-down menus. From my previous comment: "Might as well make all of the 3-state hacks into drop-down menus".

But yes I agree, this needs to get merged ASAP. We can work on changing it once it's been merged. @gregory38?

**Comment by Sarania** [comment]
It's a hack. Since I was asked :p

**Comment by tsunami2311** [comment]
MSAA is AA just like FXAA  and FXAA is AA too and its not hack nor is in the hack section. 

MSAA dont belong in the hack section never has either just no bother to put it where it belongs. which another topic. work ui for the round sprite hack is need

**Comment by Sarania** [comment]
FXAA is not in the hack section because it doesn't break things. Same for Anisotropic Filtering.

MSAA breaks many different games, about 25% of games I've played break in some way with it.

**Comment by tsunami2311** [comment]
MSAA does not break game it cause graphic glitchs cause it compatibly issue with effect and how there done just like it does  in PC games too ,but it not hack it still just AA, just cause it has compatibly issue  like alot PC game have compatibly issue with MSAA  does not mean it hack in PCSX 2, just mean MSAA has compatibly issue which widely know.

MSAA dont belong in hack section , but that is another topic i see the this pull has went threw and the round sprite hack does work.

**Comment by Sarania** [comment]
No, there are games it actually breaks(cf. Grandia III).

**Comment by ssakash** [comment]
@karasuhebi 

>  Could you explain the issue of swapping the value of the 3-state checkbox here? You said:
"changing the variables for the states require changing the native function for the BS_AUTO3STATE and it would influence all the other hacks which use the three state check box and it would get messy".I don't see how that is possible. :-\ Granted I'm not a coder but don't you assign the value (AKA what it does) of a checkbox state every time you implement a new checkbox?
I mean clearly it can be done. Look at Texture Filtering. That checkbox works the way I'm saying: shaded checkbox is "3D textures only" and the checkmarked checkbox is "all textures".
"Though, there is still a clean alternative for making it the right way. that would require gregory to swap the value for the Hw hack and it would be sorted out the right way. but still, gregory feels that it would be better to have the values at the current way for future access."
I think I'm understanding now. You're saying the way a 3-state checkbox works is a certain way for the HW Hacks dialog and it can't be changed for each individual checkbox in there? If so, that would explain why the Texture Filtering checkbox works the way the correct way since it's not part of that HW Hacks dialog box.

I'll explain it in simple words, normally three states use the following variable for the three different states.
0 >> unchecked.  1>> check  2>> shaded. (this is the native value for the three state checkbox and can't be changed)

The only way to have it in the right order: swap the functions of the variable [round offset hack] which could be done by gregory.

The texture filtering works the right way since, the variable values are set the right way for the function. Example:- write filter=1 in the GSDX.ini and the UI will display the checked form. also, the function does the same thing since the value 1 was coded to do bilinear filtering on both 3d and 2d textures. In our case on the round offset hack , the value 1 : the hack is applied to the texture that uses the nearest filter. I hope you understand it :smile:

**Comment by karasuhebi** [comment]
So it seems to me that all that needs to be done is swap the order of the functions in the round offset hack then. That shouldn't be too hard, right @gregory38?

**Comment by gregory38** [comment]
No the correct solution is to swap in the gui. Filter is awful, I don't want the same here.
Seriously look at it (in 1 of the hotest path of GSdx...)
```
	bool bilinear = m_filter == 2 ? m_vt.IsLinear() : m_filter != 0;
```

So you create an array
```
char swap_3_states_box[16] = { 0, 2, 1, 0}; // The last 13 possibilites will be 0 in case the user edit GSdx.ini with filter > 2 (16 will crash).  (you could put an assert too or an extra check)
```
Then it is easy
```
CheckDlgButton(m_hWnd, IDC_ROUND_SPRITE, swap_3_states_box[theApp.GetConfig("UserHacks_round_sprite_offset", 0)]);
```
```
theApp.SetConfig("UserHacks_round_sprite_offset", swap_3_states_box[(int)IsDlgButtonChecked(m_hWnd, IDC_ROUND_SPRITE)]);
```
I let's you fix/improve the syntax/wording.

**Comment by ssakash** [comment]
This looks like a feasible solution, I'll send the PR for this after I get the console message and the anisotropic filtering part done. Thanks for the idea.

**Pull request merged**
