### PR TITLE
Multinull revision 2

### PR DESCRIPTION
**Pull request by uyjulian**
I combined the null plugins into one.
There should be no more problems now because I based the plugins of the original null plugins' source code, didn't rewrite from scratch.

### CODE REVIEW

**Comment by gregory38** [comment]
It misses the build for windows.

**Comment by uyjulian** [comment]
Should I do VC12 only? (Don't add into other VC11/VC10 file?)

**Comment by gregory38** [comment]
All (10/12/13), otherwises a regression will happen.

**Comment by uyjulian** [comment]
Alright, gotta dig out those old versions...

**Comment by uyjulian** [comment]
Oh, turns out I can open those vc10/vc11 files with vc12 without having to upgrade those files. Great! That will make things way easier.

**Comment by uyjulian** [comment]
Okay, done adding multinull to vs2010/vs2012/vs2013 files.

**Comment by gregory38** [comment]
Currently, if you don't enable EXTRA_PLUGINS options on linux, only CDVD/dev9/FW/USB null plugins are built (ie no GS/PAD/SPU2 null plugins). It is possible to restore this behavior.
1/ It reduces a bit compilation time.
2/ It reduces the number of bug report because people doesn't have any display with the GSnull plugin...

**Comment by uyjulian** [comment]
`#ifdef`s I guess then?
Allright, I'll do that then.

**Comment by bositman** [comment]
Can't build, am I missing something?
Log: http://pastebin.com/SVNMrTQY

**Comment by avih** [comment]
What is it good for?

**Comment by uyjulian** [comment]
@bositman There's something wrong with the `Pcsx2Types.h` file, and I'm trying to figure out what is happening...

@avih duplicate code/filecount reduction.

**Comment by avih** [comment]
It doesn't cost anyone anything that the file count is high.

These files are isolated and don't clutter other parts of the code. The fact that each null plugin only does one plugin makes it easier for developers who wish to start a new plugin. You might as well just remove all the null plugins and that's it, instead of unifying all of them into one.

Small null plugins make an excellent starting point if someone wants to develop a new plugin, and a big multinull plugin is less useful.

Obviously a lot of work went into this patch. I'd suggest that next time you intend to submit a PR which touches hundreds of files, open a discussion first and get some confirmation that such PR would be welcomed.

If there was such a discussion and one of the devs said it's welcome, then please ignore what I've said, though I still hold the opinion that this is effort which is not worth the time you put into it, and IMO actually hurts the usefulness of null plugins.

**Comment by uyjulian** [comment]
@avih The point of the null plugin unify was to remove duplicate code.
For example, the configure code was duplicated like 7 times (one for each null plugin), is that really needed?
For those that want a starting point for a plugin, one plugin with unified coding style is better than 7 plugins with different people, different coding styles doing it.
One source file for each part of the plugin with all defs for each part (CDVD.cpp, DEV9.cpp, FW.cpp, etc)
Better more readable then more confusing?

**Comment by gregory38** [comment]
Normally there is common code for logging/configuration in common/include/PS2Eext.h

**Comment by uyjulian** [comment]
@gregory38 yes, I use that code, but I wrap it in one struct.

**Comment by ramapcsx2** [comment]
I remember wondering about the use of any "null" plugin, back when Jake decided to add a few more of them. The rationale was along the lines of avih's comment: Provide a base structure for new plugin coders to work with..

**Comment by avih** [comment]
I'm closing this now. Any dev can open it if they think it's required.

Next time, please discuss changes with the devs before submitting/coding a PR, especially if it's going to be a big PR.

**Comment by ramapcsx2** [comment]
Sorry we didn't merge it, @uyjulian 
It just didn't seem very useful to begin with and it ended up touching a lot of files.
Please do discuss your ideas before going ahead next time.

**Pull request closed without merging**
