### PR TITLE
GS/Core: Purge frameskipping.

### PR DESCRIPTION
**Pull request by lightningterror**
### Description of Changes

GS/Core: Purge frameskipping.
### Rationale behind Changes

Get rid of frameskipping, won't be added to Qt.
Follow up from #5011
### Suggested Testing Steps

Make sure nothing got broken.

### CODE REVIEW

**Comment by labib2002** [comment]
so..
"After a discussion it seems it might still be useful, holding off on merging for now." 
it's not useful anymore?

**Comment by refractionpcsx2** [comment]
nope, frame skipping has always been kinda terrible, and there's other things to help, like "skip present duplicate frames" to help ease the burden.

**Comment by F0bes** [comment]
Can't hold on to things forever. There have been plenty of performance improvements now.

**Review by JordanTheToaster — APPROVED** [review]

**Review by stenzek — APPROVED** [review]
Non-wx bits LGTM

**Pull request merged**
