### PR TITLE
SPU: Fix bugs in recent commits, redesign DMA slightly

### PR DESCRIPTION
**Pull request by refractionpcsx2**
Savestate bump, sorry

Should fix the games broken by the recent work hopefully.....

### CODE REVIEW

**Comment by tadanokojin** [comment]
I'm sure you already know but for preservation purposes this fixes the recent regression on Tom and Jerry War of The Whiskers.
Testers shall be fired.

**Comment by atomic83GitHub** [comment]
Fixes the sound regression in ESPN NFL 2K5.

**Comment by atomic83GitHub** [comment]
Be carefull not to play Titeuf Mega Compet right now with this PR, the speakers could explode.

**Comment by rspretty** [comment]
Fixed character voice issues in Final Fantasy X.

**Comment by refractionpcsx2** [comment]
> Fixed character voice issues in Final Fantasy X.

They were broken?? Did I break those recently?

**Comment by rspretty** [comment]
In Final Fantasy X(JP), character voice issue(stuttering sound and random freeze) occured after "SPU2: Improve DMA Write timing. Better sync DMA speeds with IOP " patch.
Now works perfect with this tree. Thank you.

**Comment by refractionpcsx2** [comment]
Awesome, thanks for letting me know :)

**Pull request merged**
