### PR TITLE
Digimon Battle chronicle Gsdx crc hack.

### PR DESCRIPTION
**Pull request by ssakash**
the current patch fixes the graphical glitches in the game during battle at the RubberTree Falls Stadium,

### CODE REVIEW

**Comment by avih** [comment]
Unless you forgot to include some files, like the actual CRC hack itself, not only this patch doesn't fix anything, it also wouldn't compile, since there's no function by the name of `DigimonBattleChronicle`.

**Comment by avih** [comment]
This is the second time I'm requesting this from you, please don't post pull requests before you test that your patch works and you understand what your patch does.

**Comment by avih** [comment]
Apologies, it does compile, but as far as I can tell it still does nothing. If you think otherwise, please reopen this PR.

**Comment by archshift** [comment]
As a side note, if a project maintainer closes an issue or PR, the person who submitted it is not able to reopen it.

**Comment by avih** [comment]
He can still request to open it and we will if it has merit.

**Comment by ssakash** [comment]
I still didn't add the CRC hack ( should have mentioned in my first post), I'm currently testing the compiled build (including the CRC hack) unfortunately, it also triggers other issues while fixing the targeted issue.(that's why, I didn't send the CRC hack to PR) I'll check for a way on fixing it without any side effects, will add the whole commit a little later after testing that it is stable enough and doesn't cause any issues.

**Pull request closed without merging**
