### PR TITLE
translations: Syncing Crowdin translations

### PR DESCRIPTION
**Pull request by xTVaser**

### CODE REVIEW

**Review by Mrlinkwii — APPROVED** [review]

**Comment by xTVaser** [comment]
apparently merging this would be a problem https://discord.com/channels/309643527816609793/1123611486623891556/1196188818026549258

This doesnt have to be merged, i just had to rerun crowdin's syncing feature (so new strings in `master` end up in crowdin to be translated).

**Comment by stenzek** [comment]
Merging so I can figure out what languages need additional fonts/glyph ranges scanned.

**Comment by refractionpcsx2** [comment]
I don't think "The new log window probably won't be translated" is a good reason not to merge this.

**Comment by HarmfulBreeze** [comment]
> apparently merging this would be a problem https://discord.com/channels/309643527816609793/1123611486623891556/1196188818026549258
> 
> This doesnt have to be merged, i just had to rerun crowdin's syncing feature (so new strings in `master` end up in crowdin to be translated). Re-running said feature, automatically opens a PR.

I did not say merging this PR would be a problem, instead I was referring to old translations being re-submitted on Crowdin.



> I don't think "The new log window probably won't be translated" is a good reason not to merge this.

That's not what I said either. I was just surprised by the timing that I thought was not the best and this PR could've benefitted from waiting a few more days.

**Pull request merged**
