### PR TITLE
BIOS/HLE: Improve handling of OSD params when fast booting

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Improves the HLE handling of OSD Region Params by keeping a HLE structure of them in memory.
Also force language setup on next full boot after creating a new .NVM file.

### Rationale behind Changes
Before we didn't take in to account any offsets or sizes of reads for Set/GetOsdConfigParam2 which caused memory corruption and returning bad values in some games (Notably Need for Speed Hot Pursuit didn't read the Daylight Savings flag right).  This was compounded by the fact that when the BIOS reads the NVM, a bunch of the data gets reordered and mixed together.

This improves the emulation of these extra settings when Fast Boot is used.

Forcing setup on next full boot after creating an NVM is because the defaults make assumptions on region just so games have *something* to go off, but now when you full boot after this, you will get to pick your language/timezone properly.

### Suggested Testing Steps
Test Need for Speed Hot Pursuit and GTA Vice City Stories with and without DST, maybe some other games.

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
True Crime: New York City now respects DST when saving too.
image

**Comment by bigol83** [comment]
This fixes GTA San Andreas saves timestamp too.

**Comment by refractionpcsx2** [comment]
Nice! :) I wonder if any games crashed because of this, but I don't think they did.

**Comment by bigol83** [comment]
I only played the amount of time needed to check if saving showed the correct timestamp, but didn't experience any crashes.

**Review by JordanTheToaster — APPROVED** [review]

**Review by kamfretoz — APPROVED** [review]

**Pull request merged**
