### PR TITLE
x86regs:  iCore.h cleanup.

### PR DESCRIPTION
**Pull request by arcum42**
### Description of Changes
Change x86regs[i].reg to be signed, as -1 is used as unsigned on it. Change some defines to enums.

### Rationale behind Changes
We are testing if it's >=0 and assigning it -1 in at least one place, so it logically should be signed. Those defines are clearly acting as enums, so it's better to actually have them be enums.

### Suggested Testing Steps
See if anything breaks due to now honoring regs being -1 and other changes.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
I expect the correct fix here is to make it s8, because it should be able to be set to -1 (unassigned)

**Comment by arcum42** [comment]
That's a possibility as well. I wonder if anything actually sets it to -1?

**Comment by refractionpcsx2** [comment]
yes, in microVU_IR.h line 969 :)

**Comment by arcum42** [comment]
Alright, so the current behavior is broken, then...

**Comment by refractionpcsx2** [comment]
yeah, I'm guessing it was intended to go negative

**Comment by arcum42** [comment]
Well, changed it to be signed, so the question will now be if anything breaks. :P

**Comment by refractionpcsx2** [comment]
I guess that's what the testers are for :D

**Comment by refractionpcsx2** [comment]
but yeah looking at the existing comment, I assume the original intention was 0 was the "unassigned" value, but I guess that changed along the way :D

**Comment by arcum42** [comment]
I *was* wondering what the difference between unused and unassigned was...

**Comment by refractionpcsx2** [comment]
I don't think there is :P the .reg field is what VI register the x86 reg contains, and that can technically be 0-15, so negative 1 would be a "not a valid reg" value, or unused/unassigned.

**Comment by arcum42** [comment]
I suppose the other question would be the difference between 0/-1 for not in use, and the inuse flag in the same struct.

A lot of these defines should probably be consts or enums, too, but that's probably for another day...

**Comment by refractionpcsx2** [comment]
well all these variables can be different depending on what they're doing, so they can't really be const.

**Comment by arcum42** [comment]
Oh, I was thinking of the defines above the struct. X86TYPE_TEMP, XMMINFO_READLO, and so on. Seems like it'd make sense as an enum of x86types and one of xmminfo, for example.

**Comment by refractionpcsx2** [comment]
oh, yes, that should probably be an ENUM

**Comment by arcum42** [comment]
At the risk of pr creep, changing this to a general cleanup pr, and taking care of the enums.

**Comment by stenzek** [comment]
I can't remember if I ended up using the negative value for temps or not, so to be honest, I'd rather you leave it as-is until I can check all the call sites.

**Comment by arcum42** [comment]
Alright, I'll close this for the moment, then.

**Comment by stenzek** [comment]
There's no temps allocated currently via the VI register allocator, so *technically* -1 isn't needed as a reg value. But, for consistency with the XMMs, I think it's probably a good idea to change it to signed. And in case anyone does allocate temps though the MicroVU allocator, not that those should persist across instructions.

So this should be fine, although I'd remove the comment about not used/unassigned - that's not the case.

**Review by refractionpcsx2 — APPROVED** [review]

**Pull request merged**
