### PR TITLE
Change Playstation to PlayStation in the About dialog and the CLI dialog.

### PR DESCRIPTION
**Pull request by karasuhebi**
Changed the word "Playstation" to the proper "PlayStation" in the About
dialog and the Command Line Options dialog. Thanks to @ssakash for finding the proper files for me!

### CODE REVIEW

**Comment by karasuhebi** [comment]
Oops, I didn't notice the missing space. How do I squash?

BTW, does someone know where the title for the CLI window is stored? I just noticed it says "Commandline Options" instead of "Command-Line Options" or "Command Line Options".

**Comment by ssakash** [comment]
here's the dialog helper text for Command Line Options : https://github.com/PCSX2/pcsx2/blob/ca0aeb8e6280fe1a64006474806ea81ac2313f43/pcsx2/gui/AppMain.cpp#L403

to squash commits, you should insert these commands at git shell : 

> git rebase -i HEAD~n   // n is no. of commits you need to view ( in your case three after the next change)

> next, you will enter a text editor. you should change "pick" to "squash" for commits which you want to squash into a previous commit. note: one commit should definitely contain "pick". (without quotes obviously)  then save the text editor and close it. 

> after that, you're branch should probably change from blue color to a different one. then you should do : git push --force  ,then your changes will get updated on the PR.

**Comment by karasuhebi** [comment]
I'll make that its own PR I think. I was just asking on here because it seemed pertinent. Should I name it Command-line or Command Line? What do the devs think? @gregory38 @refractionpcsx2 @ramapcsx2 @avih?

**Comment by bositman** [comment]
I don't think anyone cares, to be honest :P Is this all, if so I'll merge it

**Comment by gregory38** [comment]
Hum in the future (until we release a new version), we won't accept new change because
1/ It is a tiny-micro details.
2/ it impacts translation.

**Comment by karasuhebi** [comment]
So should we just tag it with 1.4.0 and leave it open?

**Comment by gregory38** [comment]
Hum, maybe. I need to check if those strings are translated or not.

**Comment by micove** [comment]
```
$ find -type f -print0 | xargs -0 grep Playstation | grep -v "^Binary" | wc -l
211
```

```
$ find locales/ -type f -print0 | xargs -0 grep Playstation | grep -v "^Binary" | wc -l
108
```

Just like the other one I remember (iso -> ISO) there are a lot of instances that would remain unchanged and about half in the locales folder.

**Comment by gregory38** [comment]
Only the string in about dialog is translated

**Comment by karasuhebi** [comment]
OK so...what now? I'm confused as to what my next step here is.

**Comment by pgert** [comment]
These strings ought to be altered in the process.

"Playstation game discs are not supported by PCSX2.  If you want to emulate PSX games then you'll have to download a PSX-specific emulator, such as ePSXe or PCSX."
pcsx2\CDVD\CDVD.cpp

"PCSX2 requires a *legal* copy of the PS2 BIOS in order to run games.\n
You cannot use a copy obtained from a friend or the Internet.\n
You must dump the BIOS from your *own* Playstation 2 console."
pcsx2\gui\FirstTimeWizard.cpp

Full support for ANSI would enable the nicer "PlayStation®"\"PlayStation®2".
As I remember, Visual Studios have a problem with this.
Strange that such a "modern" system prefers ASCII.

**Comment by willkuer** [comment]
I think its more c++ that is restricted. That's just how it was designed and therefore ASCII will always work better than other charsets.
C# uses unicode natively. C# and C++ can be coded in VisualStudio using their charsets. I dont think visual studio is the bad guy here.

**Comment by karasuhebi** [comment]
>Only the string in about dialog is translated

@gregory38 Alright so what does that mean for me? What do I need to do? Are we leaving the PR open until the next major release since the About dialog is translated or should I re-do the PR without the About dialog change so we can merge it?

@pgert also mentioned some other strings that should be changed but I'm assuming those are translated as well?

**Comment by pgert** [comment]
> Hum in the future (until we release a new version), we won't accept new change because
> 1/ It is a tiny-micro details.
> 2/ it impacts translation.

Strings that affect translation have been added through f11596f,
 so the second argument isn't (absolutely) valid anymore.
Just sayin.

> @pgert also mentioned some other strings that should be changed but I'm assuming those are translated as well?

Yes, they are.

**Comment by gregory38** [comment]
Change are minors. I postponed them after 1.44 release.

**Comment by gregory38** [comment]
Please rebase your commit if you still want to merge it.

**Comment by gregory38** [comment]
I did the rebase and the merge

**Comment by karasuhebi** [comment]
Thanks!

**Pull request closed without merging**
