### PR TITLE
Greg/gsdx smaller gui

### PR DESCRIPTION
**Pull request by gregory38**
@FlatOutPS2 did I forget something ?

### CODE REVIEW

**Comment by FlatOutPS2** [comment]
Only that it closes https://github.com/PCSX2/pcsx2/issues/1830 ;)

**Comment by gregory38** [comment]
Thank. I completely forgot it...

**Comment by gregory38** [comment]
@turtleli is is better on your VM ? It should be small enough now.

**Comment by turtleli** [comment]
GTK2 - it's small enough.
GTK3 - it's small enough, but for GTK 3.22 and later, it's better to add this line as well:
```
gtk_scrolled_window_set_propagate_natural_height(GTK_SCROLLED_WINDOW(scrollbar), true);
```
It'll avoid having a scrollbar when it isn't necessary, and the dialog resize behaviour is better (without it, the tab contents won't resize if the user resizes the dialog height)

Side note: there's quite a few deprecated warnings with the GTK3 compile.

**Comment by i30817** [comment]
Thanks for this. Depending on the GTK3 ability to zoom out to show which widget is selected wasn't fun.

**Comment by gregory38** [comment]
@turtleli 
Done. Thanks for the tip.

```
Side note: there's quite a few deprecated warnings with the GTK3 compile.
```
I guees the warnings are related to GTK4. It would be so much easier if all distributions used the same GTK version for wxWidget.

**Pull request merged**
