### PR TITLE
Coverity: some clean up stuffs and control flow issues.

### PR DESCRIPTION
**Pull request by ssakash**
CDVD commit: (https://scan3.coverity.com/reports.htm#v10075/p11624/g10075g/fileInstanceId=6857270&defectInstanceId=1703193&mergedDefectId=146818)

* Value of CDVD_MODE_2352 is 0, the code won't enter the switch case statement. either way, this scenario still won't happen because of the early return above in case of CDVD_2352. just remove the the unreachable code to satisfy coverity and clean up the code.

GSDX commit: (I spotted this one, not sure whether it is in coverity (it might be ?) )

* This bool variable isn't used anywhere on the code , @rama added this on :30e538a

The intent was probably to verify the current render which is already being done without this variable for the hacks dialog. (see line 555 of GSSettingsdlg.cpp )

### CODE REVIEW

**Comment by avih** [comment]
These changes don't require lengthy commit messages. Please change them as follows:
`GSDX: Remove unused variable` (and that's it)
`CDVD: Remove unreachable code` (that's it, plus the comment where you removed the code)

**Comment by gregory38** [comment]
I don't like the fix. There is a high probability that compiler will now issue a warning due to a missing case in the switch. Behavior of the code is well described.

**Comment by willkuer** [comment]
Jnodefault is a template for a default or? I guess a compiler wouldn't care for missing cases if a default is implemented...

**Comment by ssakash** [comment]
> Jnodefault is a template for a default or

Just a define for default case with assertion trigger for debug/devel builds.

**Comment by ssakash** [comment]
@avih 

Updated the commit message and the code to include the comment for ```CDVD_MODE_2352```

**Comment by avih** [comment]
> I don't like the fix. There is a high probability that compiler will now issue a warning due to a missing case in the switch. Behavior of the code is well described.

I agree the current code isn't bad, I don't think this change is mandatory and I do think the `switch` block should reference all values which is why I requested to add the comment. However, I don't think Coverity would issues a warning on this (it's just a `#define`, not even an `enum`), and if it would, then I won't like this warning since the `switch` statement is perfectly good IMO also with the suggested change.

Maybe a better change would be to put everything into the `switch` block, but it's probably not worth the time and effort, again, because ultimately I agree the current code isn't bad.

Maybe better to indeed just not accept this change.

Regarding the unused variable, is this the only unused variable in GSdx? if not please remove all of them in a single PR. While at it, please check for unused variables throughout PCSX2 and remove them too in this single PR.

It's really better for a PR to really "cover" a subject and not address every bit of it in its own PR.

So I'm closing this PR now.

If you feel like removing unused variables, please do this for all of PCSX2 in a single PR, and make sure you don't remove variables which are not used currently but are used if some sections of the code are re-enabled.

**Comment by avih** [comment]
@ssakash in general, @gregory38 is currently doing Coverity cleanups. It would have been better to just mention it to him such that he could add it to his cleanups if he thinks it's required, instead of sending a cleanup PR while another member is already working on this subject.

**Comment by ssakash** [comment]
@avih 

Thanks, got it. currently I don't think I have the time to check all the files for unused variables, maybe I'll try it later.

**Comment by avih** [comment]
If you do, please consult with gregory before you start working on it. Thanks.

**Pull request closed without merging**
