### PR TITLE
Plugin Selector: Make plugins easier to read (remove Git version string).

### PR DESCRIPTION
**Pull request by MrCK1**
This PR simply shortens the displayed plugin name by removing the version/build time from the displayed string to make it easier to read in release builds.

For instance,
Current
```Lilypad (2015121311175709) 0.11.0 [lilypad]```

Proposed
 ```Lilypad 0.11.0 [lilypad]```

### CODE REVIEW

**Comment by FlatOutPS2** [comment]
The build time can be useful when a user accidentally uses an outdated plugin in a newer PCSX2 build(is known to happen after copying a newer build over an older one). The actual version numbers are rarely updated.

FYI, you need to use clang format(probably just replace the tabs with spaces) in the plugin files or they won't compile on Linux. ;)

**Comment by mirh** [comment]
I also agree with flatout. 
When i mix/mess/hack/compile myself stuff, it starts to get really difficult to distinguish what's what. 

On an "official release" though, I agree that shouldn't be there. 
...
Besides, why are you removing the version from dlls, instead of the "check" inside UI?

**Comment by MrCK1** [comment]
Maybe a better solution would be to shorten the build time string to ```YYYY/MM/DD``` instead of removing it entirely?

**Comment by MrCK1** [comment]
I'm lazy, not really interested in doing this anytime soon :P

**Pull request closed without merging**
