### PR TITLE
Capture: Implement audio file customization

### PR DESCRIPTION
**Pull request by sonicfind**
### Description of Changes
Gives users the ability to change the channel arrangement (mono or stereo) for a captured wav file.

### Rationale behind Changes
We're most likely leaning towards a complete separation of audio and video capture - or really, allowing for audio to be captured separately from video if a user chooses to do so. It makes sense to thus add some switchable options to expand the use cases.

Also, wavfile.h/cpp from soundtouch had a lot of irrelevant functions for our context, so moving towards a completely custom version of those files that can be used on any pc config is probably best.

### Suggested Testing Steps
1. Check to ensure that pcsx2_ui.ini has these written correctly.
2. Check in some external audio program (audacity pre-3.0 for example) that the wav format matches what settings were chosen.

### CODE REVIEW

**Comment by sonicfind** [comment]
Yea see, I knew there had to be something I missed with regards to the other system configs. 😅

**Comment by refractionpcsx2** [comment]
I'd recommend grabbing the sample rate from the SPU2 if you can and multiplying the number based on that, because I'm not sure how happy it would be if somebody decided to record PS1 mode since you have it hard coded to 48khz (and multiples)

**Comment by sonicfind** [comment]
Ah, I don’t own any PS1 games, so I wasn’t aware it worked in PS1 mode. Good to know. Guess I am doing that.

**Comment by sonicfind** [comment]
That was.... much easier than I expected.

**Comment by lightningterror** [comment]
Closing as it's not currently being worked on.

**Pull request closed without merging**
