### PR TITLE
Rename ConfigSoundtouch.cpp to ConfigSoundTouch.cpp

### PR DESCRIPTION
**Pull request by xantares**
Fixes build on a case-sensitive filesystem

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Can you make sure it matches in both the CMake and VS project files (and also the filters) just to make sure it's consistent please.

**Comment by xantares** [comment]
it's the other way around in the vs files

**Comment by refractionpcsx2** [comment]
why did you close this?

**Comment by tellowkrinkle** [comment]
image
Personally I'd say rename and change in VS for consistency

**Comment by xantares** [comment]
ok

**Pull request merged**
