### PR TITLE
Hdr colclip

### PR DESCRIPTION
**Pull request by gregory38**
This branch replaces the standard inaccurate colclip algo with a new version based on HDR rendering. I expect speed to be comparable however it reduces the likelihood to have an overflow of the color. This new algo also provides a good speed up of the high level of blending. Therefore I extend it to support properly destination alpha testing (fog effect) :)

Code really needs a good testing and also some performances measurement between the basic/medium/high level of blending accuracy. Maybe medium and high could be merged together.

### CODE REVIEW

**Comment by gregory38** [comment]
@prafullpcsx2
It is your turn to work now :p 

Seriously, I remember that FIFA used to need ultra accurate blend for the lighting effect on the ground. Could you try to play with the new blending level and check the speed impact?

**Comment by refractionpcsx2** [comment]
I'm guessing the windows dialog will need updating?

**Comment by gregory38** [comment]
No, I don't think so. It must be automatic based on the vector content.

**Comment by refractionpcsx2** [comment]
Cool, that's good to know :)

**Comment by prafullpcsx2** [comment]
I think you once explained what were the differences between all different blending units. Can you paste that post here also? I want to know whether Ultra means Full + FBMask or there are other differences too? I am asking this because Main FIFA games now give correct lighting effect (only on top half of the screen) with Full but they also require FBMask so I have to select Ultra as the option.

**Comment by gregory38** [comment]
Hum, maybe if we remove the linux define, it will show a tooltip ;)

none => easy ;)
basic => fbmask + impossible blend + draws that do a single texture mapping without self-intersection (only require a texture flush so nearly free from a cpu PoV) + draws that don't need barrier (for example As*Cs)
Normally basic give you already lots of goodies with a very speed penality. Note, in this case the impossible blend are the one of the form (1 + X).

Medium: do it for all sprites rendering (because they're often use in post processing effect, note most of them are already covered in previous level. It just a small addition)

High: do the destination alpha blending too. Typically the game that could render better in DX9. This level also add the few remaining case of accurate color clipping (not sure one remains actually).

Full: run nearly everything on the shader (except some small corner case). It is the old ultra_accurate blend.
Ultra: nearly the same as full, it is only to test a different rounding of color (I expect similar result as full, barely faster).

High is the latest playable level from my point of view and it must emulate 95% of the effect correctly.

**Comment by prafullpcsx2** [comment]
@gregory38 : FBMask isn't working with medium, Full & Ultimate. Is it the expected behaviour?

**Comment by gregory38** [comment]
no

**Comment by prafullpcsx2** [comment]
Working only with basic, high and ultra. But this was the first build that I compiled. So may be I messed up something on my side. Will reconfirm after testing with another build.

**Comment by gregory38** [comment]
usual small regression :p nothing to see ;)

**Comment by prafullpcsx2** [comment]
Compiled latest version and it's working fine now. 

Here are some performance results:-

FIFA 2010 (to get correct field) - 61 fps then 66 fps now
God of war 2 (to get correct fog effect) - 26 fps then 72 fps now ( Unbelievable) 
Kya - No noticeable difference at native resolution but at X3 resolution 55 fps then 65 fps now

**Comment by gregory38** [comment]
OoO, if you're asthmatic (no offense) PC can handle blending at high level, I may need to remove the "high-end" part in the tool tip :+1:
Could you compare the difference of perf between the different level of blending. Maybe medium&high can be merged together.

**Comment by gregory38** [comment]
@prafullpcsx2 I pushed the 2 fixes of socom2 here. This way you have only a single build to test. I deeply hope it will work nicely.
Please recheck the performance too.

**Comment by prafullpcsx2** [comment]
I found no regressions so far. Socom 2 text is also fixed. Performance is on par with builds before Socom 2 fix. Incase anyone else wants to test this here is Windows sse2 version:-

http://www.filedropper.com/gsdx32-sse2-hdrcolclip

**Comment by gregory38** [comment]
@prafullpcsx2 could you check the shadows of hulk too?

@aphirst could you check this branch (you just need to compile GSdx) on your Intel driver. I want to be sure there is no massive regression due to the lack of texture barrier.

**Comment by prafullpcsx2** [comment]
Hulk shadows are fine.

**Comment by aphirst** [comment]
I did a build from this branch just now, and things seem to work just like before. I can provide some more specific detail if you need?

**Comment by karasuhebi** [comment]
This might be a dumb question but are any of these changes going to affect the way color shows up in games? Are you making adjustments to the colors? Before I didn't think that but now you're even mentioning HDR so I'm wondering if colors will be less console-accurate now?

**Pull request merged**
