### PR TITLE
SPU2: Small tweaks to ADSR and IRQ address triggers

### LINKED ISSUE #2314: SPU2-X: Project Zero II audio stuttering
***PCSX2 version:***
v1.5.0 2286

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
Audio stutters or plays too fast when characters speak during gameplay (does not seem to affect cutscenes/FMV). 

***How to reproduce the issue:***
Play the game. In certain locations the voices will stutter and/or play too fast. Also seems to affect Project Zero III/Fatal Frame III based on mention of bug [here](https://wiki.pcsx2.net/PCSX2_Documentation/Google_Code_svn_repository_comments_archive_5000_to_5499).

***Last known version to work:***
PCSX2 v1.1.0 r5403

This is a regression caused by [this](https://github.com/PCSX2/pcsx2/commit/7dc3b25ddf5ae789bc0c897866eaf6af0c35cdef) commit by @sudonim1 

EDIT: Link to SPU2-X plugin build with regression removed: [Custom SPU2-X plugin](https://forums.pcsx2.net/attachment.php?aid=65729)

### LINKED ISSUE #8286: [BUG]: Spyro Enter the Dragonfly cutscene audio is delayed and cut
### Describe the Bug

In Spyro Enter the Dragonfly all the cutscenes (Intros, midgame and endings) have the audio delayed and the cutscenes end before the audio does. This might affect other sounds in the game, but it's most noticeable in the cutscenes since they requiere sync. This issue seems to be present since the game was made playable in PCSX2.

### Reproduction Steps

Launch the game and start a new game to watch the intro cutscene with audio desynced and cut.

These are a couple of videos showcasing the issue, they are old, but the issue is still the same.
https://www.youtube.com/watch?v=q2ndlQNMWoc
https://www.youtube.com/watch?v=sdJWeTqsolw

### Expected Behavior

Audio playing at the correct time.

Here's an old video recorded from an actual PS2 showing the audio playing correctly:
https://www.youtube.com/watch?v=-xJCAQMnhhs

### PCSX2 Revision

v1.7.4156

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

_No response_

### CPU

i7-6700K

### GPU

NVIDIA GeForce GTX 960

### GS Settings

It happens in both hardware and software.

### Emulation Settings

All settings are default.

### GS Window Screenshots

_No response_

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Adjusts the maximum value the ADSR can adjust by and the inclusiveness of the IRQ addressing.

### Rationale behind Changes
ADSR can adjust by 0x4000 per tick, not 0x3fff as we had it clamped to before, this was incorrect, causing Spyro Enter the Dragonfly to hang.

IRQ addressing was including the end address when testing if an IRQ should fire, however the end address isn't read, so it doesn't make much sense that it would trigger it, plus it was causing Fatal Frame/Project Zero 2 speech not to work correctly. Limited testing has shown it wouldn't trigger.

### Suggested Testing Steps
Test Spyro - Enter the Dragonfly and Fatal Frame/Project Zero 2, plus a bunch of other games which are sensitive to SPU2 stuff in the past https://github.com/PCSX2/pcsx2/issues?q=is%3Aissue+sort%3Aupdated-desc+spu2+is%3Aclosed+label%3ASPU2

Thanks to Goatman13 and Ziemas for their efforts in debugging/testing said changes :)

Fixes #2314

### CODE REVIEW

**Comment by Buzzardsoul** [comment]
Does not fix #8286

**Comment by refractionpcsx2** [comment]
I'll remove that then, I was under the impression that was the problem.

**Review by Buzzardsoul — APPROVED** [review]
No regressions on my end

**Comment by refractionpcsx2** [comment]
Thanks :) I'm just waiting for Link to try some of his shitty games before I hit the button.

**Review by Mrlinkwii — APPROVED** [review]

**Pull request merged**
