### PR TITLE
GameDatabase: Automatic GS hardware fixes

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

This PR allows automatic GS hardware fixes (trying to avoid the word hack) to be applied from the game database, which will significantly improve the user experience over time since they won't have to go looking at the wiki for what upscaling fixes to apply.

I've done a few games (GTA: SA, GoW/GoW2), but there'll be many others. I'll leave that to the rest of the community :)

The keys are integer based, with 0 being disable and 1 being enable, for some options these numbers correspond to the dropdown values (e.g. for round sprite, 0 is off, 1 is half, 2 is full, and so on).

Mipmaps, point list palette and texture-in-rt were also moved from the C++ source to the game database. They're also easier to maintain now, since they use serials instead of CRCs, when adding them, you only need to have one region of the game, since you don't need to get the executable hashes of all of them.

Lastly, I purged a bunch of the title crcs from GSCrc.cpp. I'd be lying if I said that didn't feel good.

### UI CHANGE NOTE:

**"Enable HW Hacks" is now "Manual HW Hacks".**

This means that if you enable the option, no gamedb GS fixes will be applied. So basically, it's similar to how game fixes work now. For debugging you can turn it on, but in most cases, once we fill the gamedb in, it can stay off for users  :)

### Rationale behind Changes

This has been needed for a long time, because otherwise people never stop asking "how to fix reflections in san andreas" etc.

### Suggested Testing Steps

Test games which needed mipmapping and make sure it auto enables still (e.g. Jak).

Test games which use point list palette (see diff).

Test GTASA/GoW and make sure the fixes automatically apply (I've done this).

### CODE REVIEW

**Comment by coornio** [comment]
Not sure if this is accounted for, but it might be a good idea to consider allowing selecting HW hacks as required for native hardware experienced, and what's necessary for when upscaling. There might be situations where one hack might only fix an issue when upscaling, but introduce problems otherwise. I could be wrong of course.

**Comment by refractionpcsx2** [comment]
have you got an example of a non-upscaling hack which fixes upscaling only?

**Comment by coornio** [comment]
> have you got an example of a non-upscaling hack which fixes upscaling only?
> 
> But the gamefixes will be overridden if the user manually enables hw hacks.

That was fast!

Also, not entirely sure. I think I might have come across one such instance but I can't say for certain, I'd have to look through my library blindly and again experiment in each one for a "seamless" upscale experience. I don't keep a ledger. I probably should have :P 

As for gamefixes being overridden, that's fine since its modus operandi would be for the database to eventually be curated and set in stone, so to speak. It may still be a good idea however to mark in some way which hacks the gamefixes enable. Maybe an asterisk. It would be purely contextual, instead of having someone dive into the database directly to look them up. It would also make it easier to do maintenance on the gamefixes down the line when accuracy improves further and their use becomes more limited or outright deprecated.

**Comment by stenzek** [comment]
> It may still be a good idea however to mark in some way which hacks the gamefixes enable

It logs the enabled fixes when the game is loaded (and on any subsequent settings loads in Qt).

**Comment by dio-gh** [comment]
How will offsets work (upscaling stuff)? Is GameDB going to have to store offsets for each resolution scaling level? Seems viable, since there's only a relatively limited number of integer multipliers that need covering.

**Comment by refractionpcsx2** [comment]
I'm not sure the GameDB has a place for Texture Offsets because they do have to be modified depending on the resolution you're at and could cause further issues.

**Comment by stenzek** [comment]
Texture offsets removed, GS dumps now include the serial (so hw fixes get pulled in, sorry for the version dump).

GS dumps now have screenshots embedded (to provide more context), and contain the serial/title in the filename.

**Comment by coornio** [comment]
> GS dumps now have screenshots embedded (to provide more context), and contain the serial/title in the filename.

Are we certain that embedding the screenshot is a good idea? As far as I'm aware, they're taken at window resolution, whatever that may be, and could be quite large as a result. Maybe it'd be best to implement a potential "resolution limiter" of sorts to resize the screenshot and try and keep their size under control?

Then again, I'm not quite certain if maintaining the screenshot at its initial capture resolution has any particular benefit aside from the issue being debugged being clearer to see. Ignore me if there's more to it :P

**Comment by stenzek** [comment]
> Are we certain that embedding the screenshot is a good idea? As far as I'm aware, they're taken at window resolution, whatever that may be, and could be quite large as a result. Maybe it'd be best to implement a potential "resolution limiter" of sorts to resize the screenshot and try and keep their size under control?

If you read the diff, you'd see the embedded screenshot is 640x480.

> Then again, I'm not quite certain if maintaining the screenshot at its initial capture resolution has any particular benefit aside from the issue being debugged being clearer to see. Ignore me if there's more to it :P

It's useful when you have tends of dumps in the directory and are trying to figure out which one to run when checking for regressions.

**Comment by Tzerinas** [comment]
Regarding offsets: Is it possible to have that handled via a simple game specific note in the QT interface when it becomes standard in the future?  It still would have to be done manually, but it would at least remove the need to look them up/possibly get outdated info.

**Comment by coornio** [comment]
> If you read the diff, you'd see the embedded screenshot is 640x480.

Fair enough, I was considering situations with non-standard resolutions such as widescreen but they'd be silly to have enabled at all for dumps to begin with. Maybe in the future where everything works right and we can afford to care about widescreen patches and upscaling fixes :D

**Comment by stenzek** [comment]
> with non-standard resolutions such as widescreen

The embedded screenshot is just used for the preview in the GSDump, which has a fixed aspect ratio anyway. I see no reason to overcomplicate this.

**Comment by RedDevilus** [comment]
I do have to wonder if some games have a (near) static texture offset even with different upscaling multipliers. I guess in the future if needed it can be re-added and where half-pixel offset fixes it, you shouldn't use the texture offset in its stead anyway.

**Comment by lextra2** [comment]
> Texture offsets removed, GS dumps now include the serial (so hw fixes get pulled in, sorry for the version dump).

Can you clarify? 'Removed' from the gamedb or removed completely from the emulator?

**Comment by RedDevilus** [comment]
We are talking about using it for automatic gamesettings. Not removing it for manual values from the GUI.

**Comment by lextra2** [comment]
> We are talking about using it for automatic gamesettings. Not removing it for manual values from the GUI.

Thanks for clarifying!

**Comment by RedDevilus** [comment]
Fixes https://github.com/PCSX2/pcsx2/issues/5062

**Comment by RedDevilus** [comment]
image
Users: Hurray no tinkering
GameDB contributors: RIP life

**Comment by RedDevilus** [comment]
I haven't tested all settings, using san andreas as template.

Autoflush works fine with 0 and 1 values
Conservative framebuffer doesn't do anything with 0 and 1 values
Skipdraw: Tried testing skipdraw on 1 and offset at 100 (and some other combinations) however they don't correspond to GUI version 1 100, though it looks more closer to higher ranges.

**Comment by RedDevilus** [comment]
GameDB:
image

Same as manual:
image

But manual doesn't allow the second box to be lower than first box.

**Comment by RedDevilus** [comment]
Another issue is (without running a game) once you enable manual HW Hacks , apply the setting, then disable the manual HW Hacks it will do:
image

However if you make sure Manual HW hacks aren't activated and you restart PCSX2 application it does it correctly:
image


Probably also didn't like me adding all gs hw fixes with value of 1:
image

**Comment by stenzek** [comment]
> Conservative framebuffer doesn't do anything with 0 and 1 values

Seems fine to me.

> Skipdraw: 

I've renamed skipdraw to `skipDrawStart` and `skipDrawEnd`, where end must be greater or equal to start (validated by lint).

> Another issue is (without running a game) once you enable manual HW Hacks , apply the setting, then disable the manual HW Hacks it will do and run the game:

Couldn't reproduce this.

**Comment by RedDevilus** [comment]
- Gay settings (remove skipDraw, skipDrawOffset,TextureOffsetX, TextureOffsetY to avoid dropping GameDB errors)
```
  gsHWFixes:
    autoFlush: 1
    conservativeFramebuffer: 1
    cpuFramebufferConversion: 1
    disableDepthSupport: 1
    wrapGSMem: 1
    preloadFrameData: 1
    fastTextureInvalidation: 1
    textureInsideRT: 1
    alignSprite: 1
    mergeSprite: 1
    wildArmsHack: 1
    pointListPalette: 1
    mipmap: 1
    trilinearFiltering: 1
    skipDraw: 1
    skipDrawOffset: 1
    halfBottomOverride: 1
    halfPixelOffset: 1
    roundSprite: 1
    textureOffsetX: 1
    textureOffsetY: 1
- Boot ISO (SLES-52541 GTA San Andreas)
- GameDB goes mad
- GameDB says it enabled all GS HW fixes:
```
```
Elf entry point @ 0x00100008 about to get recompiled. Load patches first.
[GameDB] Has not been initialized yet, initializing...
[GameDB] 10834 games on record (loaded in 38.82ms)
[GameDB] Searching for 'sles-52541' in GameDB
[GameDB] Found 'sles-52541' in GameDB
[GameDB] Searching for patch with CRC 'a1b3f232'
[GameDB] No CRC-specific patch or default patch found
(GameDB) Changing VU0/VU1 clamp mode [mode=2]
[GameDB] Enabled GS Hardware Fix: autoFlush to [mode=1]
[GameDB] Enabled GS Hardware Fix: conservativeFramebuffer to [mode=1]
[GameDB] Enabled GS Hardware Fix: cpuFramebufferConversion to [mode=1]
[GameDB] Enabled GS Hardware Fix: disableDepthSupport to [mode=1]
[GameDB] Enabled GS Hardware Fix: wrapGSMem to [mode=1]
[GameDB] Enabled GS Hardware Fix: preloadFrameData to [mode=1]
[GameDB] Enabled GS Hardware Fix: fastTextureInvalidation to [mode=1]
[GameDB] Enabled GS Hardware Fix: textureInsideRT to [mode=1]
[GameDB] Enabled GS Hardware Fix: alignSprite to [mode=1]
[GameDB] Enabled GS Hardware Fix: mergeSprite to [mode=1]
[GameDB] Enabled GS Hardware Fix: wildArmsHack to [mode=1]
[GameDB] Enabled GS Hardware Fix: pointListPalette to [mode=1]
[GameDB] Enabled GS Hardware Fix: mipmap to [mode=1]
[GameDB] Enabled GS Hardware Fix: trilinearFiltering to [mode=1]
[GameDB] Enabled GS Hardware Fix: halfBottomOverride to [mode=1]
[GameDB] Enabled GS Hardware Fix: halfPixelOffset to [mode=1]
[GameDB] Enabled GS Hardware Fix: roundSprite to [mode=1]
[GameDB] Searching for 'sles-52541' in GameDB
[GameDB] Found 'sles-52541' in GameDB
[GameDB] Searching for patch with CRC 'a1b3f232'
[GameDB] No CRC-specific patch or default patch found
```

- Boot ISO again (SLES-52541 GTA San Andreas) (So don't swap games)
- GameDB goes mad
- GameDB says it's seeing manual gamefixes and disabling most GS HW fixes
```
Elf entry point @ 0x00100008 about to get recompiled. Load patches first.
[GameDB] Searching for 'sles-52541' in GameDB
[GameDB] Found 'sles-52541' in GameDB
[GameDB] Searching for patch with CRC 'a1b3f232'
[GameDB] No CRC-specific patch or default patch found
(GameDB) Changing VU0/VU1 clamp mode [mode=2]
[GameDB] Hardware fixes are enabled, not using automatic fixes.
[GameDB] Skipping GS Hardware Fix: autoFlush to [mode=1]
[GameDB] Enabled GS Hardware Fix: conservativeFramebuffer to [mode=1]
[GameDB] Skipping GS Hardware Fix: cpuFramebufferConversion to [mode=1]
[GameDB] Skipping GS Hardware Fix: disableDepthSupport to [mode=1]
[GameDB] Skipping GS Hardware Fix: wrapGSMem to [mode=1]
[GameDB] Skipping GS Hardware Fix: preloadFrameData to [mode=1]
[GameDB] Skipping GS Hardware Fix: fastTextureInvalidation to [mode=1]
[GameDB] Skipping GS Hardware Fix: textureInsideRT to [mode=1]
[GameDB] Skipping GS Hardware Fix: alignSprite to [mode=1]
[GameDB] Skipping GS Hardware Fix: mergeSprite to [mode=1]
[GameDB] Skipping GS Hardware Fix: wildArmsHack to [mode=1]
[GameDB] Enabled GS Hardware Fix: pointListPalette to [mode=1]
[GameDB] Enabled GS Hardware Fix: mipmap to [mode=1]
[GameDB] Skipping GS Hardware Fix: trilinearFiltering to [mode=1]
[GameDB] Skipping GS Hardware Fix: halfBottomOverride to [mode=1]
[GameDB] Skipping GS Hardware Fix: halfPixelOffset to [mode=1]
[GameDB] Skipping GS Hardware Fix: roundSprite to [mode=1]
[GameDB] Searching for 'sles-52541' in GameDB
[GameDB] Found 'sles-52541' in GameDB
[GameDB] Searching for patch with CRC 'a1b3f232'
[GameDB] No CRC-specific patch or default patch found
```

Other issue seems to be that along with lint checker you renamed skipDraw and skipDrawOffset to skipdrawstart and skipdrawend
And from what I see deleted texture offset as valid?

**Comment by refractionpcsx2** [comment]
> Other issue seems to be that along with lint checker you renamed skipDraw and skipDrawOffset to skipdrawstart and skipdrawend And from what I see deleted texture offset were removed?

Not just the lint checker, s_gs_hw_fix_names[] is also wrong, maybe others, didn't check, so it freaks out if you try to use skipDraw/skipDrawOffset

As for the misdetection of manual fixes thing, that's weird, cos you click "boot fast" let it load, then click "boot fast" again, the first lot of them will freak out about manual fixes, but the second lot of checking the DB (I have *no idea* why we check twice) it says it enables them normally, idk if this actually takes effect though.

**Comment by refractionpcsx2** [comment]
Additionally for clarity, would it be better having it as "skipDrawOffset" and "skipDrawCount", cos "skipDraw" sounds like a toggle

**Comment by refractionpcsx2** [comment]
RE: Lint, it looks like you left the old variables under allowed_gs_hw_fixes, but changed the rest.

**Comment by pgert** [comment]
pcsx2/GameDatabase.cpp:
Console.Warning("[GameDB] Hardware fixes are enabled, not using automatic fixes.");

"[GameDB] Hardware fixes are enabled, not using automatic fixes." ->
 "[GameDB - gsHWFixes] 'Manual HW Hacks' are enabled, not applying any automatic HW-fixes."?

Less confusing, yes?

**Comment by refractionpcsx2** [comment]
Make a new issue please if you wish to request something changed. Don't just pick a merged PR to make suggestions.

**Comment by RedDevilus** [comment]
> pcsx2/GameDatabase.cpp: Console.Warning("[GameDB] Hardware fixes are enabled, not using automatic fixes.");
> 
> "[GameDB] Hardware fixes are enabled, not using automatic fixes." -> "[GameDB - gsHWFixes] 'Manual HW Hacks' are enabled, not applying any automatic HW-fixes."?
> 
> Less confusing, yes?

It was already planned to be changed, it's on the list of ever-growing stuff.

**Pull request merged**
