### PR TITLE
wxWidgets 3.1.6 Compatibility

### PR DESCRIPTION
**Pull request by tellowkrinkle**
### Description of Changes
Makes PCSX2 compile properly on wxWidgets 3.1.6

### Rationale behind Changes
It's nice when things compile

### Suggested Testing Steps
Try compiling with wxWidgets 3.1.6

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Can you fix your commit names, please :)

**Comment by tellowkrinkle** [comment]
> Can you fix your commit names, please :)

Do you have any recommended prefixes?

**Comment by refractionpcsx2** [comment]
GUI/WX I guess

**Comment by refractionpcsx2** [comment]
Screw it, jus WX will do.

**Pull request merged**
