### PR TITLE
gsdx: mirror RGBAQ to 0x11

### LINKED ISSUE #2427: [GSDx] Ridge Racer V [SLUS-20002] Missing Shadows - All Renders
***PCSX2 version:***
All Versions

- **Notes**:
All Renders.

***PCSX2 options:***
No options have effect.

- **Note**: 

***Plugins used:***
GSdx32-SSE4.dll [GSdx 20180503003203 (MSVC 19.00 SSE4.1/AVX) 1.1.0]

- **Note**: 
DX11HW/SW

***Description of the issue:***

Car shadows alternate at a steady interval from white to invisible

https://i.gyazo.com/0d1941ba6e881329dbedfc43cff66dc6.png

https://i.gyazo.com/d153d51d23f66e461e695ddc0bcb35ab.png

GS Dumps avail here:
https://forums.pcsx2.net/Thread-Vector-Units-Bug-Report-Ridge-Racer-V-PAL-NTSC

***How to reproduce the issue:***
Start the game. Enter a race. Observe lack of shadows.

***Last known version to work:***
I checked latest annual builds for 2011 thru 2017 (missing a 2015 build)
Car Shadows have 'Never worked' period. All renders. 

***PC specifications:***
CPU: AMD 4.0GHz X4 GPU: R9 270X 2GB OS: Win7 x64

### PR DESCRIPTION
**Pull request by tadanokojin**
fixes #2427

### CODE REVIEW

**Comment by ramapcsx2** [comment]
Is it likely that the other regs are mirrored and used in the same way?
If so, we probably don't want countless duplicate entries right away, but a warning on use of a potentially mirrored reg would be good.

**Comment by refractionpcsx2** [comment]
It needs to be tested on a ps2, something we plan on doing at some point

**Comment by tadanokojin** [comment]
You've got 0x10, 0x12, and 0x13 available. Could account for PRIM, ST and UV.

**Comment by ramapcsx2** [comment]
Just those?
I would just add them pro-forma in that case.
If you've got a call to the register handler with that index, what else should happen?
It can either mirror, or drop the call (on hardware). And I mostly doubt it should be dropped.

**Comment by refractionpcsx2** [comment]
I don't think it's a good idea to just guess add them, in case that is wrong, or there's some weird mapping, it would be better to run tests first.

**Comment by ramapcsx2** [comment]
Yeaahh.. Well, as long as it's not forgotten :p 
This PR itself should be good though, right?

**Comment by gregory38** [comment]
Good job.

**Pull request merged**
