### PR TITLE
Patch: Add new toggleable cheat and patch interface

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

This PR adds a new interface for toggling patches/cheats on and off. Gone are the days of having to manually edit pnach files and comment out lines, or juggle/rename multiple files with different suffixes.

Mod creators can ship their entire set of patches as a single file, and users can choose what options they want to enable.

Same with cheats. You even get a tree view there (similar to how I did it in DuckStation), which is ideal for choosing "one or more of N options".

Not sure if it's worthwhile adding a 60 FPS option globally as discussed in #8874. If there is a sufficiently high number of patches which do work correctly, then maybe, but otherwise if it's only a handful, those can just be enabled via the patch menu.

Big picture UI still needs doing. I don't have the energy for that at the moment.

Example of the updated pnach file format: 
[77E61C8A.txt](https://github.com/PCSX2/pcsx2/files/11567361/77E61C8A.txt)

Format changes:
 - Basically, everything after a square bracket label is grouped with that patch.
 - You can specify description (comment is used if it is not), and parent. Parent creates the tree view shown in the screenshot below, backslashes separate tree nodes.
 - Old cheat files will continue to work as-is. Anything without labels will be loaded and applied as long as the global cheat option is enabled. The UI adds a summary line at the bottom of the list if this is the case.

### Rationale behind Changes

The old method of doing stuff sucked.

Test patches in screenshots courtesy of https://cookieplmonster.github.io/mods/gran-turismo-4/

Ignore the FIXME at the bottom, it's since been changed.

image

image

### Suggested Testing Steps

Make sure old cheats still work.
Make sure gamedb patches still work.
Make sure widescreen patches work via the option, and the patches menu.
Make sure new cheats with labels (square brackets) work.
Make sure cheats in groups display correctly.

Note to testers: You'll need a new patches.zip file to replace cheats_wi.zip/cheats_ni.zip.

[patches.zip](https://github.com/PCSX2/pcsx2/files/11567354/patches.zip)

We'll coordinate the merge with the PCSX2 patches repo, but for now, you can use this file. Drop it in the resources directory.

### CODE REVIEW

**Comment by kamfretoz** [comment]
Tested on Arch Linux, PCSX2 crashes with `munmap_chunk(): invalid pointer` when opening game properties and when launching the game after booting the BIOS.

Screenshot_20230526_082246

No traceback is printed.

**Comment by Berylskid** [comment]
Tested on Windows 10.
- PCSX2 crashes at opening "Properties..." in gamelist
- PCSX2 crashes at starting to run a game.
- PCSX2 can boot BIOS.

Here's a [Crash Dump](https://github.com/PCSX2/pcsx2/files/11573352/pcsx2-qt.exe.12948.zip) which was generated in `%USERPROFILE%\AppData\Local\CrashDumps\`.

**Comment by Berylskid** [comment]
Tested on Windows 10.
> Note to testers: You'll need a new patches.zip file to replace cheats_wi.zip/cheats_ni.zip.

With `patches.zip`, PCSX2 doesn't crash at opening per-game setting or starting game.

**Comment by DragonautMk** [comment]
Amazing!
This will really upgrade the user experience!

**Comment by stenzek** [comment]
Should all be sorted now. I've modified the workflow to pull from my pcsx2_patches fork, until the main repo is updated.

**Comment by kamfretoz** [comment]
Screenshot_20230526_193428
Screenshot_20230526_193423

Now it no longer crash!

**Comment by Tokman5** [comment]
When you toggle a specific item in `Cheats` tab, double clicking an item will work correctly, but by clicking a checkbox, `Applying settings...` log doesn't show up and the ini file is not saved correctly.

Otherwise, I used non-English characters (i.e. Japanese) for label names, group names and comments, and all of them still work well.

**Comment by stenzek** [comment]
> When you toggle a specific item in Cheats tab, double clicking an item will work correctly, but by clicking a checkbox, Applying settings... log doesn't show up and the ini file is not saved correctly. (tested on windows 10)

Whoops. Forgot to connect the event handler 🤦‍♂️  Fixed.

**Pull request merged**
