### PR TITLE
readme: Add discord shield + remove coverity

### PR DESCRIPTION
**Pull request by RedDevilus**
### Description of Changes

Changed chat to PCSX2 Discord shield which means logo and color change added.
### Rationale behind Changes

More obvious to endusers and cleaner.
### Suggested Testing Steps

Just on main page of PCSX2/PCSX2 github and click on the invite.

### CODE REVIEW

**Review by GovanifY — APPROVED** [review]

**Comment by GovanifY** [comment]
@RedDevilus We can just look at the rich diff in github's diff viewer, no need to screencap everything

**Comment by RedDevilus** [comment]
That's not in the changes, that's why i screencapped it.

**Comment by GovanifY** [comment]
Oh you mean the color? I don't think we care

**Comment by GovanifY** [comment]
squash your commits and it should be good to go imo

**Pull request merged**
