### PR TITLE
Dev9ghz: Fix crash on close when ethernet adapter fails to load in winPcap

### PR DESCRIPTION
**Pull request by TheLastRar**
Fix crash on close/shutdown when we fail to load the selected Ethernet adapter in WinPcap.

The plugin will now also behave like dev9null when Ethernet is disabled (which will be done when we encounter the above situation).

Should Fix https://github.com/PCSX2/pcsx2/issues/959

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
@Volkanite can you test this at all or do you need a build?

**Comment by Volkanite** [comment]
Tested and works. Good job @TheLastRar

**Comment by refractionpcsx2** [comment]
Thanks for the PR :)

**Comment by ssakash** [comment]
coverity misses the most important null dereference checks :p

**Comment by TheLastRar** [comment]
Are plugins even checked on coverity?

**Comment by refractionpcsx2** [comment]
Yep they are :)

**Pull request merged**
