### PR TITLE
gsdx ogl: tekken5: only trigger channel effect shader when frame buffer is a single page

### PR DESCRIPTION
**Pull request by gregory38**
Fix missing model regression.

Please test tekken5

### CODE REVIEW

**Comment by bositman** [comment]
Seems to be working fine now even on CRC None/minimum/partial

**Comment by gregory38** [comment]
You need at least minimum for some effects in some stages (...moon...).

**Comment by bositman** [comment]
I tested all this with CRC minimum
Oh if you mean all stages issues, some are still there, like the Burning Temple issue (horizontal line on character's bodies) and additional issues if using scaling.
pcsx2 2016-10-16 13-18-42-18

You need both align sprite for vertical black lines to get fixed and half pixel offset when upscaling to fix ghosting, but you also get this then:
pcsx2 2016-10-16 13-21-37-64

**Comment by gregory38** [comment]
Good. Those are known issues. The first one is the typical half bottom issue. For the 2nd one, I need to find a way to merge properly sprite for processing effect. Or maybe I could just round them.

**Comment by FlatOutPS2** [comment]
The characters are back, but now there are all kinds of shadowy things moving accross the screen.

**Comment by gregory38** [comment]
which scene ? I didn't notice it on the missing model dump. However, I'm not sure the effect is correctly rendered

**Comment by FlatOutPS2** [comment]
Never mind, the issue only appears with the default Full CRC hack level.

**Comment by gregory38** [comment]
Cool :+1:

**Pull request merged**
