### PR TITLE
Greg/gsdx gtk3

### PR DESCRIPTION
**Pull request by gregory38**
Replace GTK  deprecated code by modern GTK3. Nothing was tested yet. And I suspect that I misses some paddings for the table. Anyway it is a start.

(PS: yeaah I upgraded my debian to stretch)

### CODE REVIEW

**Comment by gregory38** [comment]
@turtleli feels free to give it a look. I'm really not confident on the monitor API to get the screen size.

**Comment by turtleli** [comment]
The GtkGrid stuff doesn't seem to expand to use the full dialog width.

I haven't looked at the monitor stuff yet.

**Comment by gregory38** [comment]
Oh. It seems it is done with properties. I need to look at it. And I need to find a way to run the gui in standalone mode.

**Comment by turtleli** [comment]
Latest commit doesn't have any effect.

**Comment by gregory38** [comment]
Ok. I propose to merge this PR with both GTK3 define disabled. I need to rebuild wx with GTK3 support to implement the code properly. At least the PR factorize a bit the code so it would reduce the number of warning and will help future fixes.

**Pull request merged**
