### PR TITLE
gsdx-d3d11: enable splitting of alpha in dumps

### PR DESCRIPTION
**Pull request by tadanokojin**
This allows d3d11 to dump textures in a similar fashion to OGL.

Previous behavior was to output the texture with alpha.
Instead, let's split it as outputting the texture with alpha can produce a completely transparent texture which is useless for debugging.

### CODE REVIEW

**Comment by tadanokojin** [comment]
I updated it to use the OGL define.
With regards to `dds` I noticed TextureSW uses it

https://github.com/PCSX2/pcsx2/blob/dc2eed6ca1e4811048b1def95eec8f32fcbb96a1/plugins/GSdx/Renderers/SW/GSTextureSW.cpp#L88-L90

If I remove the check, TextureSW break if it's passed a depth texture?

**Comment by gregory38** [comment]
Hum, is dds = true used somewhere. If yes does it impact the sw renderer.

**Comment by tadanokojin** [comment]
This is the only place I see it:
https://github.com/PCSX2/pcsx2/blob/a020c98421698e5293f81419cd91089e8eede25c/plugins/GSdx/Renderers/HW/GSRendererHW.cpp#L942-L958

Doesn't appear SW uses it, I guess the check is just redundant.

**Comment by gregory38** [comment]
Remove it. The only place this variable make sense is in sw renderer (I don't think sw has an internal format)  On the hw you can check the internal format of texture to know if it is a depth buffer.

**Comment by tadanokojin** [comment]
Consider it done.

**Comment by gregory38** [comment]
Fine for me. Don't hesitate to ping me, I easily forget stuff.

**Comment by lightningterror** [comment]
Dump works fine both debug and release test so merging this.

**Pull request merged**
