### PR TITLE
gsdx: Use std::thread and std::function for GSJobQueue

### PR DESCRIPTION
**Pull request by turtleli**
Changes:
 * Use std::thread on all platforms - I removed the GSThread class because I feel it's now unnecessary.
 * Makes GSJobQueue non-inheritable - std::function is used instead to specify the worker function - it's probably slightly safer this way (see commit message).

### CODE REVIEW

**Comment by gregory38** [comment]
Nice jobs. Did you run some benchmark ?

**Comment by turtleli** [comment]
I didn't notice any performance difference on my system.

**Comment by willkuer** [comment]
what would be a good benchmark? sw mode with many threads?

**Comment by turtleli** [comment]
Well, that's more or less what I did - I ran GS dumps in sw mode with a few threads.

**Comment by gregory38** [comment]
Perfect, it is the same on my PC too.

**Pull request merged**
