### PR TITLE
Fix & Add Many Japanese GameTitle

### PR DESCRIPTION
**Pull request by nassau-tk**
### Description of Changes

Fixed a large number of Japanese game titles.
*Trial & Demo will fix later.
 
### Rationale behind Changes

This is a difficult task for non-Japanese people, so I did it myself.
*I'm JP.

### Suggested Testing Steps

Put on the "resources" folder and check booting PCSX2.
If  the .yaml file has problem then PCSX2 will not boot(Crash).

### CODE REVIEW

**Comment by Mrlinkwii** [comment]
it looks like the CI for cheking thegame-db failed https://github.com/PCSX2/pcsx2/actions/runs/12328904962/job/34415585188?pr=12084

**Comment by nassau-tk** [comment]
Fm...

What is limit at line?

**Comment by F0bes** [comment]
The issue is you have two `name` keys

```
FVGK-0015:
  name: "伯爵と妖精 ～夢と絆に思いを馳せて～ [初回限定版]"
  name-sort: "はくしゃくとようせい ゆめときずなにおもいをはせて [しょかいげんていばん]"
  name: "Hakushaku to Yousei - Yume to Kizuna ni Omoi o Hasete [Limited Edition]"                <--- Same key at the second line!!
  region: "NTSC-J"
  ```
 
 I think you were intending to set `name-en` instead
 ie
 ```
 name-en: "Hakushaku to Yousei - Yume to Kizuna ni Omoi o Hasete [Limited Edition]"
 ```

**Comment by nassau-tk** [comment]
OK!
I will check once more again.

**Pull request closed without merging**
