### PR TITLE
Add support for CHD format

### LINKED ISSUE #2584: [Request]Add CHD format support for compressed disc
Hello there, love the project, can we get some CHD love for the pcsx2 as a compressed disk format?

CHD or "Compressed Hunks of Data" - it's a MAME format for storing disk images.

With libchdr from @rtissera this should be doable like the new retroarch cores do
https://github.com/rtissera/libchdr

Some of the benefits the CHD support have:
.-lossless compression
.-15-18% better compression than pbp (this makes a bin cue uncompressed collection almost half its size)
.-its a streamable format, it doesnt need to decompress, just play
.-its increadibly easy to convert entire folders filled with uncompressed psx games with a batch file
.-every disc turns into just one file
.-supports redbook audio in flac compression
.-its becoming the defacto standard for libretro cores with support in mame, saturn, pcengine/turbografx, segacd/megacd, psx beetle and future support for dreamcast (in a few days)

Twice the fun, same space

Thanks in advance
Best regards

### PR DESCRIPTION
**Pull request by SleepyMan**
A few caveats in this pull request.

- I really hate cmake, so if there are things that are wrong, please, include advice on how to fix when pointing out the problem. Thanks.
- This implementation actually implements loading parent/clone CHD files as well, but support for it has to wait to be merged: rtissera/libchdr#42
- For parent/clone CHD, it currently uses "in the same directory" convention. As long as parent is in the same directory, it will find it (by CHD SHA1, no need for full reading/hashing)
- It also implements grandchildren CHD, that is:

Original -> Child -> Grandchild

or even:

Disc 1 -> Mod of Disc 1
\-> Disc 2 -> Mod of Disc 2

For grandchildren, a small modification is needed for chdman. It currently only loads one child via command line argument. mamedev/mame#7594

- There is no async read for libchdr, so for the async version, I just block and use the sync version.

As is, running make install actually copies libFLAC files, since it's probably running its cmake install script when I included it to build it. If someone knows how to include libchdr's project for building, but not actually for installing, enlighten me, please.

It was mostly tested with beaumanvienna/pcsx2@a0958a6f097122fb29449ed031ff87aaa700d1c5 on a x86_64 Arch Linux machine, but I compiled with latest master and tested for a few days, and no problems detected.

Sorry, this was done in July, but I hadn't had time to clean this for a pull request. Hope it's a good Christmas gift to all.

Edit: Fixes #2584 

Edit 2: I hate cmake... It can find libchdr in my machine, but not in the CI. If someone can help clean the mess I made in cmake files, I'd appreciate.

In the "Generate CMake" step:
...
Could NOT find CHD (missing: CHD_ROOT_DIR) 
...

### CODE REVIEW

**Review by tadanokojin — COMMENTED** [review]
I suggest you move the external into a subfolder like is done for yaml and xz.
```
- 3rdparty
  - libchdr
    - libchdr.vcxproj
    - libchdr.vcxproj.filters
    - libchdr (submodule)
      - CMakeLists.txt
      - src
      - include
 ```

For the visual studio stuff you can use yaml as an example. Or if you don't have access to a Windows machine and don't want to bother playing the "wait for the CI build to see if it works" game, myself or @xTVaser can help you with it.

**Comment by tellowkrinkle** [comment]
Cmake find scripts are for finding system libraries.  Just use `add_subdirectory` for submodules, and add `EXCLUDE_FROM_ALL` to prevent its targets from being installed
Also if chd has its cmake scripts set up reasonably (it may or may not) you don't need the manual `include_directories` either

You can use the import of fmt or yaml-cpp as a reference

**Comment by SleepyMan** [comment]
> Cmake find scripts are for finding system libraries. Just use `add_subdirectory` for submodules, and add `EXCLUDE_FROM_ALL` to prevent its targets from being installed
> Also if chd has its cmake scripts set up reasonably (it may or may not) you don't need the manual `include_directories` either
> 
> You can use the import of fmt or yaml-cpp as a reference

I just removed all the libchdr cmake stuff, and replaced it with a single `add_subdirectory(3rdparty/libchdr/libchdr)` (now in a subfolder, like yaml-cpp). Headers are included and found correctly, but the library is not linked, thus giving undefined reference. It seems like I need to add libchdr's library manually? Any pointers on the correct way of doing this?

**Comment by tadanokojin** [comment]
Attached patch with some MSVC stuff but because this PR is dependent on https://github.com/rtissera/libchdr/pull/42 for `chd_read_header` I can't work any further.

[msvc.zip](https://github.com/PCSX2/pcsx2/files/5749296/msvc.zip)

**Comment by tellowkrinkle** [comment]
You still need to add libchdr's target to the list of targets linked to pcsx2 (include `chdr-static` in `pcsx2FinalLibs`)

**Comment by siddhartha77** [comment]
I've done a bunch of work on this PR and talk about it here. I'm fairly new to GH and am not sure if I should create a new PR or do a PR of a PR. Anyway, this commit will fix this issue and compiles Release and Debug on both Linux and Windows.

**Comment by liberodark** [comment]
For why you dont make a new PR with : https://github.com/siddhartha77/pcsx2

**Comment by refractionpcsx2** [comment]
> For why you dont make a new PR with : https://github.com/siddhartha77/pcsx2
> Have any issue or something else for non merge this PR : [SleepyMan#2](https://github.com/SleepyMan/pcsx2/pull/2)
> @siddhartha77

Because I asked him to PR it to @SleepyMan to combine it with his work.  Making a separate PR using his work would be very rude and undermine his work.

**Comment by rtissera** [comment]
@SleepyMan @siddhartha77 @refractionpcsx2 can we work together to get this into PCSX2 ?
I made some big changes in libchdr upstream making it easier to integrate.
Discord ?

**Comment by rtissera** [comment]
https://github.com/rtissera/libchdr/pull/42 merged

**Comment by RedDevilus** [comment]
Can the OP make sure that all the builds/checks works fine?

**Comment by refractionpcsx2** [comment]
Superseeded by #4314 and merged in to master.  if you want to add your new features later when it's implemented upstream, let us know.

**Pull request closed without merging**
