### PR TITLE
GS-OGL: Correct a minor typo

### PR DESCRIPTION
**Pull request by Berylskid**
### Description of Changes
- extenstion -> extension
- Removed unnecessary "t" from this word.

### Rationale behind Changes
- Just a correction of typo.

### Suggested Testing Steps
- I'm not sure.

### CODE REVIEW

**Comment by stenzek** [comment]
To be honest, this whole thing could be removed - it's not going to be very reliable, since other applications can allocate VRAM too, which would throw out the tracking.

**Comment by Berylskid** [comment]
If removing the whole thing makes PCSX2 better, I'd like to do that. Which lines should be removed or commented out?

**Comment by stenzek** [comment]
Pretty much what comes up here: https://github.com/PCSX2/pcsx2/search?q=available_vram

**Comment by Berylskid** [comment]
Done. Created a PR for removing them. (#8389 )

**Comment by Berylskid** [comment]
Changed line has been removed by #8389

**Pull request closed without merging**
