### PR TITLE
Update AudioSettingsWidget.cpp

### PR DESCRIPTION
**Pull request by xujibbs**

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
hmm I'm not sure what you've done here is right, that stuff is inside a QT_TRANSLATE_NOOP which I believe is supposed to be so it doesn't translate it on purpose (the comments suggest this too).
I'm sure it needs to be done differently, I would check other dropdown menus for examples.

**Comment by IlDucci** [comment]
It needs to be done differently, and there is a confusion with the comments:
 - The words "Cubeb"/"Xaudio2" should not be translated, but the text inside the parentheses should, so those strings should be made translatable. The comments are for translators.

**Comment by stenzek** [comment]
Yup, this is incorrect. It might need a qApp->translate call later (although these strings should be declared in the core to begin with)

**Comment by stenzek** [comment]
Superseded by #9078.

**Pull request closed without merging**
