### PR TITLE
Onepad GUI for Linux - New wxWidget interface (Images)

### PR DESCRIPTION
**Pull request by kust2708**
Add images for the new GUI
See PR : https://github.com/PCSX2/pcsx2/pull/924

### CODE REVIEW

**Comment by gregory38** [comment]
I only see a single png but multiple .h. How are they generated?

**Comment by gregory38** [comment]
As a side note, we have a tool to convert png to h on the core. + cmake stuff. This way .h are generated at runtime.
Check pcsx2/CMakeLists.txt
```
### Generate the resources files
file(MAKE_DIRECTORY ${res_bin})

add_custom_command(OUTPUT  "${res_bin}/Dualshock.h"  COMMAND perl ${CMAKE_SOURCE_DIR}/linux_various/hex2h.pl "${res_src}/Dualshock.jpg" "${res_bin}/Dualshock" )

foreach(res_file IN ITEMS
        AppIcon16 AppIcon32 AppIcon64 BackgroundLogo ButtonIcon_Camera
        ConfigIcon_Appearance ConfigIcon_Cpu ConfigIcon_Gamefixes ConfigIcon_MemoryCard
        ConfigIcon_Paths ConfigIcon_Plugins ConfigIcon_Speedhacks ConfigIcon_Video Breakpoint_Active Breakpoint_Inactive)
    add_custom_command(OUTPUT  "${res_bin}/${res_file}.h" COMMAND perl ${CMAKE_SOURCE_DIR}/linux_various/hex2h.pl "${res_src}/${res_file}.png" "${res_bin}/${res_file}" )
endforeach()
```
Can't you do the same?

**Comment by kust2708** [comment]
The png file is just a model. Only .h are used by the plugin.

**Comment by gregory38** [comment]
sure but you didn't code the .h manually, did you?  If someone want to improve the image, it will need the original source.

**Comment by kust2708** [comment]
Of course not ! Unfortunately, I didn't save pictures in .png file.

**Comment by gregory38** [comment]
which format?

**Comment by avih** [comment]
> As a side note, we have a tool to convert png to h on the core. + cmake stuff. This way .h are generated at runtime.

FWIW, `xxd` which is available on most *nix systems (and windows) can convert binary files into c h file, or into hexviewe text file and few others formats (and can also convert it back from the file to a binary file).

**Comment by gregory38** [comment]
Well current tools is based on wx.

Example of .h content:
```
class res_Breakpoint_Active
{
public:
	static const uint Length = 220;
	static const u8 Data[Length];
	static wxBitmapType GetFormat() { return wxBITMAP_TYPE_PNG; }
};

const u8 res_Breakpoint_Active::Data[Length] =
{
....
};
```

And normally there is a nice class to load the data: ```EmbeddedImage```. Not used for the debugger resources, it is a shame.

**Comment by kust2708** [comment]
I chose to use this method because of the plugin independance. I can't use core headers from the plugin because of the path issue. Is it possible to use such tools from plugins ?

**Comment by gregory38** [comment]
The tools is a separate scripts. And Cmake is common for the core and the plugins.

However ```pcsx2/gui/Resources/EmbeddedImage.h``` must be moved in common/include/Utilities/.
This way onepad could include it. Either directly or with the full common package.
The initial goal of common was to include all wx GUI usefuls tools so plugin can rely on it.

**Comment by kust2708** [comment]
That seems to be a good alternative effectively.

**Comment by gregory38** [comment]
Besides it will make the PR tidy. No more .h image to include. Github will only display the image (at least png image).

**Comment by kust2708** [comment]
In this case I need to draw again each ~20 images. I only save in .h file ...

**Comment by gregory38** [comment]
Seriously, you didn't keep the source ! I'm sorry for you. (Can't you open the .h on gimp).

**Comment by kust2708** [comment]
Can't be open with Gimp. I was more focus on the code than the images, ahah.

**Comment by gregory38** [comment]
Open source is all about source not code ;)

**Comment by kust2708** [comment]
My bad. sorry for that. I finally found a way to convert my headers to png files thanks to OpenCV.

**Comment by gregory38** [comment]
Cool :)

**Comment by kust2708** [comment]
Conversion done. Know I must change a big part of the opPanel code.

**Comment by gregory38** [comment]
Ok it is much better. Could you squash your commit to a single one. Potentially it could be merged with the previous PR, now that PR is 0 lines of change (vs 50K). Otherwise I'm fine to merge the image.

**Comment by kust2708** [comment]
I tried to use the perl script to generate header from png. But it still not working ... headers can't be found on compilation. 
```
set(compiled_images "${CMAKE_BINARY_DIR}/plugins/onepad/ImgHeader")
set(image_sources "Img")

### Generate the resources files
file(MAKE_DIRECTORY ${compiled_images})

foreach(result_file IN ITEMS
        analog circle cross dp_bottom dp_left dp_right dp_up dualshock2
        joystick_cursor l1 r1 l2 r2 l3 r3 select square start triangle)
    add_custom_command(
        OUTPUT ${compiled_images}/${result_file}.h
        COMMAND perl ${CMAKE_SOURCE_DIR}/linux_various/hex2h.pl ${image_sources}/${result_file}.png ${compiled_images}/${result_file})
endforeach(result_file)
```

I will squash commits soon (I want commit my modifications on the onepad-gui branch before).

**Comment by gregory38** [comment]
Did you add the include?

From pcsx2/CMakeLists.txt
# additonal include directories
include_directories(
					gui
					x86
```
                    ${CMAKE_BINARY_DIR}/pcsx2/gui
```
)

**Comment by kust2708** [comment]
The directory used by this CMake is "gui/Resources" but isn't in the include_directories. I'm trying to add the directory without success for the moment.

**Comment by gregory38** [comment]
```
include_directories("${CMAKE_BINARY_DIR}/plugins/onepad/ImgHeader")
```

**Comment by gregory38** [comment]
oh wait maybe the script add a sub directory.

**Comment by gregory38** [comment]
Did you do this part in cmake
```
# Warning: the declaration of the .h are mandatory in case of resources files. It will ensure the creation
# from the bin2cpp tools at the good moment (ie .h must be created before the pcsx2 compilation)
# Gui resources headers
set(res_bin "${CMAKE_BINARY_DIR}/pcsx2/gui/Resources")
set(res_src "${CMAKE_SOURCE_DIR}/pcsx2/gui/Resources")
set(pcsx2GuiResources
    ${res_bin}/AppIcon16.h
....
    ${res_bin}/Breakpoint_Inactive.h
```

**Comment by kust2708** [comment]
Yes, I wrote the same.
The full file :
```
# Check that people use the good file
if(NOT TOP_CMAKE_WAS_SOURCED)
    message(FATAL_ERROR "
    You did not 'cmake' the good CMakeLists.txt file. Use the one in the top dir.
    It is advice to delete all wrongly generated cmake stuff => CMakeFiles & CMakeCache.txt")
endif()

set(compiled_images "${CMAKE_BINARY_DIR}/plugins/onepad/ImgHeader")
set(image_sources "Img")
set(linux_sources "Linux")
set(linux_headers "Linux")


set(OnePadGuiResources
    ${compiled_images}/analog.h
    ${compiled_images}/circle.h
    ${compiled_images}/cross.h
    ${compiled_images}/dp_bottom.h
    ${compiled_images}/dp_left.h
    ${compiled_images}/dp_right.h
    ${compiled_images}/dp_up.h
    ${compiled_images}/dualshock2.h
    ${compiled_images}/joystick_cursor.h
    ${compiled_images}/l1.h
    ${compiled_images}/r1.h
    ${compiled_images}/l2.h
    ${compiled_images}/r2.h
    ${compiled_images}/l3.h
    ${compiled_images}/r3.h
    ${compiled_images}/select.h
    ${compiled_images}/square.h
    ${compiled_images}/start.h
    ${compiled_images}/triangle.h
    )

# plugin name
set(Output onepad-1.1.0)
set(onepadFinalFlags "")

# onepad sources
set(onepadSources
	controller.cpp
	GamePad.cpp
	SDL/joystick.cpp
	keyboard.cpp
	KeyStatus.cpp
	onepad.cpp)

# onepad headers
set(onepadHeaders
	bitwise.h
	controller.h
	GamePad.h
	SDL/joystick.h
	keyboard.h
	KeyStatus.h
	onepad.h)

# onepad Linux sources
set(onepadLinuxSources
	${linux_sources}/ini.cpp
	${linux_sources}/dialog.cpp
	${linux_sources}/linux.cpp
    ${linux_sources}/opPanel.cpp
    ${linux_sources}/GamepadConfiguration.cpp
    ${linux_sources}/JoystickConfiguration.cpp)

# onepad Linux headers
set(onepadLinuxHeaders
	${linux_headers}/linux.h
    ${linux_headers}/opPanel.h
    ${linux_headers}/GamepadConfiguration.h
    ${linux_headers}/JoystickConfiguration.h)

# onepad Windows sources
set(onepadWindowsSources
	)

# onepad Windows headers
set(onepadWindowsHeaders
	)

if (SDL2_API)
	set(onepadFinalLibs
		${SDL2_LIBRARIES}
	)
	add_definitions(-DSDL_BUILD)
else()
	set(onepadFinalLibs
		${SDL_LIBRARY}
	)
	add_definitions(-DSDL_BUILD)
endif()

set(onepadFinalLibs
	${onepadFinalLibs}
	${GTK2_LIBRARIES}
	${X11_LIBRARIES}
)

set(onepadFinalSources
	${onepadSources}
	${onepadHeaders}
	${onepadLinuxSources}
	${onepadLinuxHeaders}
    ${OnepadGuiResources}
)

include_directories(
    ${compiled_images}
)

### Generate the resources files
file(MAKE_DIRECTORY ${compiled_images})

foreach(result_file IN ITEMS
        analog circle cross dp_bottom dp_left dp_right dp_up dualshock2
        joystick_cursor l1 r1 l2 r2 l3 r3 select square start triangle)
    add_custom_command(
        OUTPUT ${compiled_images}/${result_file}.h
        COMMAND perl ${CMAKE_SOURCE_DIR}/linux_various/hex2h.pl ${image_sources}/${result_file}.png ${compiled_images}/${result_file})
endforeach(result_file)

add_pcsx2_plugin(${Output} "${onepadFinalSources}" "${onepadFinalLibs}" "${onepadFinalFlags}")
```

**Comment by gregory38** [comment]
try a full path for image source.

**Comment by gregory38** [comment]
And check if file are properly created on the correct place
``` find build -name "*.h" ```

**Comment by kust2708** [comment]
Nothing in the build folder =/

**Comment by gregory38** [comment]
By nothing, you mean nothing at all or no new file
how do you build? Try to use the build.sh script, it is easier to start.

**Comment by kust2708** [comment]
Nothing from the plugin sorry
The output : 
```
[kustom@Geo-laptop pcsx2]$ find build -name "*.h"
build/pcsx2/gui/Resources/ConfigIcon_Video.h
build/pcsx2/gui/Resources/ConfigIcon_Cpu.h
build/pcsx2/gui/Resources/BackgroundLogo.h
build/pcsx2/gui/Resources/ConfigIcon_Plugins.h
build/pcsx2/gui/Resources/Breakpoint_Active.h
build/pcsx2/gui/Resources/ButtonIcon_Camera.h
build/pcsx2/gui/Resources/Dualshock.h
build/pcsx2/gui/Resources/AppIcon16.h
build/pcsx2/gui/Resources/AppIcon32.h
build/pcsx2/gui/Resources/ConfigIcon_Speedhacks.h
build/pcsx2/gui/Resources/AppIcon64.h
build/pcsx2/gui/Resources/ConfigIcon_Appearance.h
build/pcsx2/gui/Resources/ConfigIcon_Gamefixes.h
build/pcsx2/gui/Resources/ConfigIcon_Paths.h
build/pcsx2/gui/Resources/ConfigIcon_MemoryCard.h
build/pcsx2/gui/Resources/Breakpoint_Inactive.h
build/common/include/svnrev.h
[kustom@Geo-laptop pcsx2]$ 
```

**Comment by kust2708** [comment]
I compile with the build.sh since the beginning.

**Comment by gregory38** [comment]
I finish my spu2x gui improvement and I will do it.

**Comment by kust2708** [comment]
It's okay, take your time. I go sleeping now. Maybe after a good night the solution will become obvious. Thanks a lot for your help.

**Comment by turtleli** [comment]
Typo - You have One**P**adGuiResources and One**p**adGuiResources. Probably best use **o**ne**p**adGuiResources for consistency ;)

**Comment by gregory38** [comment]
You just beat me.

**Comment by kust2708** [comment]
Greaaaat, that works now.

**Comment by gregory38** [comment]
Ok great I will merge the image. So you could you rebase on your next pr on it.

**Pull request merged**
