### PR TITLE
Replace Stretch sprite hack with Round sprite hack.

### PR DESCRIPTION
**Pull request by ssakash**

### CODE REVIEW

**Comment by Bigpet** [comment]
Could you maybe rebase this on top of master and squash some of the commits? It looks a little silly to have 18 commits for 10 changed lines.

**Comment by ssakash** [comment]
the following PR replaces the present stretch sprite offset hack with the round offset hack on the PCSX2 UI. Gregory mentioned to replace the older hack with the new one on the UI. the option is a three state check box.

It's actually a updated version of the stretch sprite hack. I can't rebase it now since, I'm currently on my smartphone right now. 

@avih 
please squash it, Thanks !

**Comment by avih** [comment]
I'm not your battler. What @Bigpet said.

**Comment by Sarania** [comment]
@ssakash Yeah, you can squash it yourself. Just use git rebase to squash them and then force the push over the top of them. BTW thanks for mentioning how much I helped you with this :p

https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by ssakash** [comment]
yeah, I tried to rebase it. it shows a error - "could not apply [commit number] [commit message]."

**Comment by Bigpet** [comment]
Honestly, it's 10 lines, you can either manually re-create the changes into one commit on top of master or [use the diff](https://github.com/PCSX2/pcsx2/compare/master...ssakash:master.diff) and apply that to the current master

**Comment by ssakash** [comment]
sorry for the trouble, https://github.com/PCSX2/pcsx2/pull/516

**Pull request closed without merging**
