### PR TITLE
gsdx: disable GCC optimization when checking SSE/AVX support

### LINKED ISSUE #1859: Linux: Crash caused by presence of libGsdx-AVX2.so plugin on non-AVX CPU
Hey all,

I'm running Ubuntu 16.10 x64 (w/ GTX 780 & 378.13 drivers) on an i7 930 CPU. My system is running the latest version of PCSX2 from the official PPA.

If I open the Plugin/BIOS selector, PCSX2 hangs for a few seconds and crashes. The Stack Trace, from the Ubuntu error report, indicates an issue between the **libGsdx-AVX2.so** plugin and **/lib/ld-linux.so.2** (_/lib/i386-linux/gnu/ld-2.24.so_). When running PCSX2 via a terminal, the last entry recorded after crashing is **Illegal instruction (core dumped)**.

This has occurred over the builds i've tested during the last month or so. So far, deleting the plugin stops the crash from happening.

If there's any other specific information anyone would like, let me know.

### PR DESCRIPTION
**Pull request by gregory38**
Fix #1859 (not tested)

### CODE REVIEW

**Comment by turtleli** [comment]
Doesn't work on GCC 6.3.

My previous analysis was wrong, it's not the initialisation which uses vector instructions, its actually `if(!g_cpu.has(checks[i].type))` (it's still related to the array size though).

**Comment by gregory38** [comment]
Oh. I'm curious what does GCC generate ?

**Comment by turtleli** [comment]
See https://godbolt.org/g/WRhm6h

**Comment by gregory38** [comment]
Thanks you. Ok it is related to the 64 bits type.

**Comment by turtleli** [comment]
Latest commit doesn't fix the issue. If you add the pragmas to the previous godbolt link and choose the "compile to binary and disassemble the output" option you'll still see VEX encoded instructions (I also checked the disassembly on Fedora).

Side note: pragmas need to be ifdef'd - AppVeyor shows 300+ warnings ;)

**Comment by gregory38** [comment]
where is this option `"compile to binary and disassemble the output"` On the right panel I can see the asm. Code is SSE4 (which doesn't solve fully the issue). But AVX is gone. 
I think I will remove the uint64 type.

**Comment by turtleli** [comment]
> where is this option "compile to binary and disassemble the output"

It's the 11010 near the top of the asm panel.

> Code is SSE4 (which doesn't solve fully the issue). But AVX is gone.

It seems that if -mavx is in the command line then it'll use the VEX encoded instructions even if the pragma is there.

**Comment by gregory38** [comment]
Hum... I will just use an uint32 type.

**Comment by gregory38** [comment]
So I limit the check to 32 bits. It would be annoying to support AVX512 on i386 but it won't happen soon. There is an assert to avoid the pitfall. Otherwise the other solution will be to put intrinsics to do the check ourself with SSE2.

**Comment by turtleli** [comment]
Seems to work for CheckSSE. However, I managed to reproduce the crash on accessing the plugin/BIOS selector panel (I think no-simd and native avx2 compilation produces different code for me, so I didn't see the issue the first time). It seems the initialisation of `g_cpu` can use avx instructions.

BTW, the GSdx GUI height is too big for a x768px screen - I can't see the ok button on my VM (set to 1024x768), and that's with the logo missing too.

The logo actually doesn't show up on some distros (I think it's because the pixdata format loader has been removed from recent gdk-pixbuf versions), though I can fix that (well, I still think all the GSdx logos should just be removed).

**Comment by gregory38** [comment]
Of course, there are plenty of uint64 in the constructor... Geez... 

Which tab is too big ? I guess the HW hack. It is strange that it doesn't fit in a 768p screen.
For the logo, I guess it misses a dependency on cmake. It would be nice to fix it. Not for the logo, but for the embedded shaders (current PERL solution is quite dirty)

**Comment by turtleli** [comment]
> Which tab is too big ? I guess the HW hack.

Postprocessing/OSD, but the HW hack tab might also be too big.

**Comment by gregory38** [comment]
@turtleli could you check the new commit. I will do a separate PR to reduce the GUI size, potentially with a resync on latest flatout addition.

**Comment by turtleli** [comment]
Works on my end.

**Pull request merged**
