### PR TITLE
VU: optimise entering VU JITs

### PR DESCRIPTION
**Pull request by refractionpcsx2**
### Description of Changes
Keeps note on how many cycles it needs for the next block to save exiting the EE JIT and entering the microVU JIT for no reason

### Rationale behind Changes
Entering/exiting a JIT is slow, this hopefully reduces it at least a little, especially when COP2 is being hammered.

### Suggested Testing Steps
Test EE bound games, if your game isn't EE bound, you probably won't notice any difference.

Some example performance increases on my end

Ratchet & Clank
Master: 86-89fps
PR:	95-100fps

Tekken Tag
Master: ~73fps
PR:	~87fps

My Street
Master: 148-157fps
PR:	153-160fps

### CODE REVIEW

**Review by tadanokojin — COMMENTED** [review]
you spelled optimize wrong >:(

**Comment by refractionpcsx2** [comment]
> you spelled optimize wrong >:(

image

**Comment by RedDevilus** [comment]
Chart of original 3 games:
image

Or improvement in %:
image

**Comment by RedDevilus** [comment]
Individual Charts:
Ratchet
image
Tekken Tag:
image
My Street:
image

**Comment by Anuskuss** [comment]
**Rachet & Clank 3**: 41 FPS -> 48 FPS

**Pull request merged**
